### ISSUE TITLE
Reactor webclient is not using the span in the context

### ISSUE THREAD

**Issue by jtktam** [open-telemetry/opentelemetry-java-instrumentation#10011]
**Describe the bug**
I have a spring boot webflux project that makes a webservice call to an external endpoint.  I create a new trace, the two spans are created correctly but the webclient call is created in a separate trace.

**Steps to reproduce**
https://github.com/jtktam/traceSpawn

it's a simplified parts of the code that matter.  it will connect to a dummy endpoint to retrieve a json.  i run the agent in debug mode to get a better idea of the output

java \
-Dotel.javaagent.configuration-file=./opentelemetry-javaagent.properties \
-Dotel.javaagent.debug=true \
-javaagent:./opentelemetry-javaagent.jar \
-jar target/trace-1.0.0-SNAPSHOT.jar \
--spring.profiles.active=local

**What did you expect to see?**
in the debug log below, i expect the 'GET' span to share the same trace id 9da3711931e78e50decf8d4ffdca8e76
but it is starting a new trace with trace id d22b20ee412d69dff41c703c59d1a7a1

what i can see is that the internal (manual created) span is not continuing when it gets to webclient

            return this.webclientBuilder.build()
                    .get()
                    .uri(retrieveUri)
                    .retrieve()
                    .bodyToMono(Post.class)
                    .contextWrite(Context.of(Span.class, span))
                    .onErrorResume(WebClientResponseException.class, error -> {
                        if (error.getStatusCode().equals(HttpStatus.NOT_FOUND)) {

I am contextWrite the span into the webclient but it's not being used as the parent span

**What did you see instead?**
[otel.javaagent 2023-12-05 20:54:10:749 -0500] [reactor-http-nio-3] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'GET' : d22b20ee412d69dff41c703c59d1a7a1 8845d6fd499df1c3 CLIENT [tracer: io.opentelemetry.spring-webflux-5.3:1.32.0-alpha] AttributesMap{data={http.response_content_length=292, net.peer.name=jsonplaceholder.typicode.com, http.status_code=200, thread.id=67, http.method=GET, thread.name=pool-8-thread-3, http.url=https://jsonplaceholder.typicode.com/posts/1}, capacity=128, totalAddedValues=7}
[otel.javaagent 2023-12-05 20:54:10:751 -0500] [reactor-http-nio-3] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'run' : 9da3711931e78e50decf8d4ffdca8e76 46d90a8cc0f9a710 INTERNAL [tracer: dev.porkchop.trace:1.0.0-SNAPSHOT] AttributesMap{data={thread.id=45, thread.name=parallel-1}, capacity=128, totalAddedValues=2}
[otel.javaagent 2023-12-05 20:54:10:751 -0500] [reactor-http-nio-3] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'getPost' : 9da3711931e78e50decf8d4ffdca8e76 ad2a1578b88445ab INTERNAL [tracer: dev.porkchop.trace:1.0.0-SNAPSHOT] AttributesMap{data={thread.id=67, userId=1, thread.name=pool-8-thread-3, title=sunt aut facere repellat provident occaecati excepturi optio reprehenderit, body=quia et suscipit
s

**What version and what artifacts are you using?**

Artifacts:
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.0</version>
        <relativePath/> 

        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-spring-webflux-5.3</artifactId>
            <version>1.32.0-alpha</version>
        </dependency>

**Environment**
Compiler: Java 21
OS: OSX Sonoma

**Comment by laurit** [comment]
> I am contextWrite the span into the webclient but it's not being used as the parent span

This is a flawed assumption, span from reactor context isn't used.

Web client instrumentation uses the span that is current in the otel context at the time when subscribe is called as the parent.
After https://github.com/jtktam/traceSpawn/blob/3b8be61029b2b4ca4194aa3b03b52807998818cc/src/main/java/dev/porkchop/trace/schedulers/PostSpawnScheduler.java#L99 add ` try (Scope ignored = span.makeCurrent()) {`
add
```java
    private static <T> Mono<T> wrap(Mono<T> mono) {
        io.opentelemetry.context.Context context = io.opentelemetry.context.Context.current();
        return new Mono<T>() {

            @Override
            public void subscribe(CoreSubscriber<? super T> coreSubscriber) {
                try (Scope ignored = context.makeCurrent()) {
                    mono.subscribe(coreSubscriber);
                }
            }
        };
    }
```
and use it on https://github.com/jtktam/traceSpawn/blob/3b8be61029b2b4ca4194aa3b03b52807998818cc/src/main/java/dev/porkchop/trace/schedulers/PostSpawnScheduler.java#L104 to wrap the returned mono.
Also when you are using the agent you don't need to use the library instrumentation for spring webflux, this is already included in the agent.

**Comment by jtktam** [comment]
Thank you for the pointer, I have been struggling with this for 2 days.  After testing your wrapper works, if there is no thread / context switch, which is expected.  I will restructure my approach.

instead of having to scope the call, if it used .contextWrite(Context.of(Span.class, span)) it would have been easier to intergrate with the reactor paradigm?

**Comment by trask** [comment]
> instead of having to scope the call, if it used .contextWrite(Context.of(Span.class, span)) it would have been easier to intergrate with the reactor paradigm?

this is how it works under the hood, check out https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/reactor/reactor-3.1

**Comment by jtktam** [comment]
> > instead of having to scope the call, if it used .contextWrite(Context.of(Span.class, span)) it would have been easier to intergrate with the reactor paradigm?
> 
> this is how it works under the hood, check out https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/reactor/reactor-3.1

i got it working by wrapping the webclient call in a try(scope) block, and i removed the .contextWrite() line.

are you suggesting that it works with the contextwrite or did i misunderstand?

**Comment by jtktam** [comment]
Thank you very much for the help.  I have learnt a lot and got it working now.
