### ISSUE TITLE
Add ability to set Context explicitly for logback appender

### ISSUE THREAD

**Issue by fugafree** [open-telemetry/opentelemetry-java-instrumentation#10040]
### Is your feature request related to a problem? Please describe.

My problem is that the only way to set context for the appender is to use the ThreadLocal based `Context`, because the appender uses `Context.current()` inside. This is not good for me, because my application is a reactive one, where ThreadLocal based solutions can not be used. (I already use the Java SDK, but was able to solve the propagation of `Context` without ThreadLocal so far.)

### Describe the solution you'd like

The only way to solve this is to pass the `Context` via one of the already existing capabilities of the appender to propagate information. I found the key-value pairs as the only possible solution as it capable of passing an Object and it does not use a thread based state (ThreadLocal).
So for example by setting a specific value in key-value pairs, we could set the `Context` explicitly for each individual log calls.

### Describe alternatives you've considered

Use some other propagation capability of logback which support passing any type and does not use thread based state.

### Additional context

If we can agree on an implementation plan, I'm happy to implement the solution if you don't have the resources.

**Comment by fugafree** [comment]
My implementation ideas so far:
- add a configuration to `OpenTelemetryAppender`: `captureContextViaKey` or `captureContextKey` string. Default value null or empty string. If set,`LoggingEventMapper` will look for `Context` in key-value pairs with a key defined in the variable. Pro: user defines the key that they want to use.
- provide a public static setter method in `LoggingEventMapper`, which can be used to set a `Context` on an `ILoggingEvent`. With this, the way how the appender stores and reads the `Context` become an internal implementation, the user don't need to know about it. And the key for the key-value pairs could be an internal variable. Con: the key must not be used by the user.

**Comment by laurit** [comment]
Usually when we need to pass context from reactive to non-reactive we just put the context into thread local before calling the non-reactive code. Could you elaborate why it wouldn't work here? Do you have a sample app that would show the issue?

**Comment by fugafree** [comment]
It could work with that way, yes, our only issue with that proposal is that it would lead to an error prone code. A bit safer way would be to have an explicit variable setting somehow, just like for every other information in the log (message, level, ...). Also this seemed to be a pattern in the whole Java SDK, that explicit context set was always possible in all APIs, so why not in case of logging. Again: I'm more than happy to provide a pull request.

**Comment by trask** [comment]
> I found the key-value pairs as the only possible solution

hi @fugafree! which specific logback/slf4j API is this?

**Comment by fugafree** [comment]
Hello @trask,
slf4j: https://www.slf4j.org/api/org/slf4j/spi/DefaultLoggingEventBuilder.html#addKeyValue-java.lang.String-java.lang.Object-
The one that is captured when `captureKeyValuePairAttributes` is turned on in `OpenTelemetryAppender`.

Because the others, for example MDC is again uses global context, and markers did not even worked for me. It added only the name of the marker (LS_MAP_FIELDS) to the `LogRecord`, not the actual values in the marker.
Also key values are typed, so it could contain a `Context`.

**Comment by laurit** [comment]
@fugafree using `Context.current()` is a common pattern in this repository. If using `Context.current()` doesn't work in your use case and we fix it as you have suggested you'd still run into the same issue when you'd use any other instrumentation, are you planning to rework all of them? Perhaps it would make more sense to fix the underlying issue instead so that all instrumentations that rely on `Context.current()` would work. Perhaps you could share a minimal sample application that allows reproducing the issue you are facing.

**Comment by fugafree** [comment]
As I mentioned, I can workaround this problem, so my request is noting more just a little improvement idea to make our life more convenient.
Regarding your comment that every instrumentation uses `Context.current()`, you are right. And to be honest now that you pointed this out, I also think this feature does not fit in the concept of the instrumentation of this library. I'm closing this request.
Thanks you for your time and comments.
