### ISSUE TITLE
After turning on trace, the CPU usage will double

### ISSUE THREAD

**Issue by runtu666** [open-telemetry/opentelemetry-java-instrumentation#10059]
### Describe the bug

After turning on trace, the CPU usage will double

### Steps to reproduce

1. do not use trace , check cpu usage
2.turn on trace , check cpu usage

### Expected behavior

low CPU useage rise or no rise

### Actual behavior

cpu usage doubled than before

### Javaagent or library instrumentation version

1.22.1

**Comment by kenfinnigan** [comment]
Can you do the same comparison with [v1.32.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.32.0)?

**Comment by runtu666** [comment]
After I tried it, I found that this version also has the same problem.  @kenfinnigan

**Comment by kenfinnigan** [comment]
Can you provide any details on what dependencies the project has? Is the doubling of cpu forever or only a short period?

Any additional information you can provide is helpful in understanding where the problem might be
