### ISSUE TITLE
Enhancement Request: Enrich Spans with Detailed Exception Attributes

### ISSUE THREAD

**Issue by agent-adam** [open-telemetry/opentelemetry-java-instrumentation#10069]
### Is your feature request related to a problem? Please describe.

The OpenTelemetry Java agent's method instrumentation (using `otel.instrumentation.methods.include`) doesn't captures exception/error info in the spans 

### Describe the solution you'd like

Proposed Enhancement:
Enhance the [MethodInstrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/methods/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/methods/MethodInstrumentation.java) class to enrich spans with more detailed information about exceptions when they occur. This would involve modifications in the [stopSpan](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/methods/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/methods/MethodInstrumentation.java#L75) method of MethodAdvice to extract and add detailed attributes from the Throwable object to the span.

Rationale:
Detailed exception information in spans is crucial for diagnosing issues in distributed systems. Including stack traces, error messages, and other relevant exception details can significantly improve the observability and debuggability of applications.

example of change
```
@Advice.OnMethodExit(onThrowable = Throwable.class, suppress = Throwable.class)
public static void stopSpan(...) {

    // new code to enrich span with detailed exception info
    if (throwable != null) {
        // Add code to extract details from throwable and add to span
    }
}
```

any issues in doing so or would folks be open to this feature being added ?

**Comment by laurit** [comment]
@agent-adam as far as I can tell it already does this in https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/30ddf6a66cca10f1f845b83c3f8a35c0c797edaa/instrumentation-annotations-support/src/main/java/io/opentelemetry/instrumentation/api/annotation/support/async/AsyncOperationEndSupport.java#L71

**Comment by agent-adam** [comment]
Thanks @laurit !! 
Sorry I should of tested this before posting.
Was able to confirm that errors are marked on the span. Running java agent 1.29 on with the following config and method

`OTEL_INSTRUMENTATION_METHODS_INCLUDE=com.<PATH>.ClientController[test]`

```
public class ClientController {
    public void test() throws NullPointerException {
        throw new NullPointerException("Test");
    }
 ```
 
 results in an error span 
 
 ```
 {"traceId":"2f97487738f9771c03acb168a6b15dd0","parentId":"39845d0dd5dc1c2e","id":"294985790360fea3","name":"cli...{"code.function":"test","code.namespace":"com.salesforce.monitoring.instrumentation.example.ClientController","error":"","otel.library.name":"io.opentelemetry.methods","otel.library.version":"1.25.1-alpha","otel.status_code":"ERROR",
 ...
 "thread.name":"http-nio-9501-exec-1"}}
 
 ```

**Comment by agent-adam** [comment]
Feature already added
