### ISSUE TITLE
performance degradation after agent injection

### ISSUE THREAD

**Issue by tuhao1020** [open-telemetry/opentelemetry-java-instrumentation#10063]
### Describe the bug

I'm using https://github.com/killme2008/aviatorscript
performance degradation after agent injection
```
String expression = "a-(b-c)>100";
Instant start = Instant.now();
Expression compileExp = AviatorEvaluator.compile(expression);
Instant finish = Instant.now();
System.out.println("elapse: " + Duration.between(start, finish).toMillis());
```

before injection: about 1ms
after injection: > 10ms

### Steps to reproduce

```
String expression = "a-(b-c)>100";
Instant start = Instant.now();
Expression compileExp = AviatorEvaluator.compile(expression);
Instant finish = Instant.now();
System.out.println("elapse: " + Duration.between(start, finish).toMillis());
```

### Expected behavior

no performance issue

### Actual behavior

performance degradation

### Javaagent or library instrumentation version

1.24.0

### Environment

**JDK**: Temurin 17.0.4
**OS**: mac Sonoma
Spring Boot 3.2.0
Aviator 5.3.3

**Comment by trask** [comment]
is this related to #10071?

**Comment by laurit** [comment]
Try with the latest version of the agent, should work a bit better.

**Comment by tuhao1020** [comment]
@trask  yes， I'll try IgnoredTypesConfigurer @laurit

**Comment by tuhao1020** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/164358d78827e9b0e8d75a5e38b7f7c9a80571f8/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/ignore/GlobalIgnoredTypesConfigurer.java#L15-L24

it works
