### ISSUE TITLE
How using OTEL auto instrumentation in JAVA service we can populate the trace id/ span id in headers in response 

### ISSUE THREAD

**Issue by aayushi760** [open-telemetry/opentelemetry-java-instrumentation#10067]
### Is your feature request related to a problem? Please describe.

If we put trace id, span id , parent span id in response header it would be pretty easy to debug the failed call

### Describe the solution you'd like

Some library which will induce the ids in  header

**Comment by laurit** [comment]
Have you considered using `Span.current().getSpanContext().getTraceId()` from opentelemetry api and adding the response header yourself?
