### ISSUE TITLE
Configure Spring scheduler instrumentation programmatically

### ISSUE THREAD

**Issue by MartinEmrich** [open-telemetry/opentelemetry-java-instrumentation#10076]
### Is your feature request related to a problem? Please describe.

On my quest to disable regular/scheduled/healtcheck traces, I came across #7511 mentioning the command line option `-Dotel.instrumentation.spring-scheduling.enabled=false` to disable auto instrumentation of all Spring `@Scheduled` methods.

I'd like to have the same within a "fat jar" with no reliance on the command line. I already can enable the java agent with `RuntimeAttach.attachJavaagentToCurrentJvm();`

### Describe the solution you'd like

Do the same programmatically. Something like a hypothetical

````
OpenTelemetryRuntimeDoohicky otelRuntime = RuntimeAttach.attachJavaagentToCurrentJvm();
otelRuntime.disableScheduledInstrumentation();
````

or even fancier:

````
otelRuntimeDisableScheduleInstrumentation(MyNoisyOftenCalledScheduled.class);
````

### Describe alternatives you've considered

As above: the command line works, but IMHO the java command line should not be needed to express the developer's (my) intent regarding tracing/instrumentation. Also it looks cleaner on the command line.

**Comment by trask** [comment]
I think this should work:

```
System.setProperty("otel.instrumentation.spring-scheduling.enabled", "false");
RuntimeAttach.attachJavaagentToCurrentJvm();
```

**Comment by MartinEmrich** [comment]
Yes, that works.
