### ISSUE TITLE
Otel java agent transaction name issue with instrumenting springboot application 

### ISSUE THREAD

**Issue by SenthilkumarRasan** [open-telemetry/opentelemetry-java-instrumentation#10088]
We are in the process of migrating from elastic apm agents to open telemetry agents to collect traces.
We have completed agent instrumentation and getting the data with traces in elastic backend.
Issue we have is our application has huge number of documents and url will have docid in url path.
elastic apm java agent creates transactions with controller name as root span which helps us in identifying problematic controller methods and stats by controller. With otel agent, we see traces with http url as transaction name(root span is http and controller is child span). This creates huge number of transactions(one for each url) and makes it difficult to correlate controller methods with high latency. Is there any specific instrumentation required to add to make springboot controller as root span without touching application code. 

Thanks
Senthil

**Comment by baole229801** [comment]
Hi everyone,
Does anyone know how this can be fixed?

**Comment by trask** [comment]
hi @baole229801, can you open a new issue and provide specific details? thanks
