### ISSUE TITLE
Lambda layer unable to hook in to GlobalOpenTelemetry.get()

### ISSUE THREAD

**Issue by Thul95** [open-telemetry/opentelemetry-java-instrumentation#10082]
### Describe the bug

When in AWS lambda using the java agent layer, both for layer v1 and v2. You can't access the Opentelemetry instance defined by the layer. `GlobalOpenTelemetry.get()` returns a ` DefaultOpenTelemetry{propagators=DefaultContextPropagators{textMapPropagator=NoopTextMapPropagator}}`.

However my code is correctly instrumented and traces are being forwarded to my collector also context is correctly propagated/injected on to produced records on my Kafka topic.

### Steps to reproduce

Deploy AWS java lambda with layer arn:aws:lambda:${aws:region}:184161586896:layer:opentelemetry-javaagent-0_2_0:1 and try to get the global opentelemetry instance `GlobalOpenTelemetry.get()`.

### Expected behavior

`GlobalOpenTelemetry.get()` returns the OpenTelemetry instance used by layer.

### Actual behavior

`GlobalOpenTelemetry.get()` returns OpenTelemetry.noop()

### Javaagent or library instrumentation version

- arn:aws:lambda:${aws:region}:184161586896:layer:opentelemetry-javaagent-0_1_0:1
- - arn:aws:lambda:${aws:region}:184161586896:layer:opentelemetry-javaagent-0_2_0:1

### Environment

**JDK**: 17

**Comment by laurit** [comment]
Please report this to https://github.com/open-telemetry/opentelemetry-lambda
