### ISSUE TITLE
Move the Spring Auto-Configuration doc to opentelemetry.io

### ISSUE THREAD

**Issue by jeanbisutti** [open-telemetry/opentelemetry-java-instrumentation#10083]
### Is your feature request related to a problem? Please describe.

Move the Spring Auto-Configuration documentation to the opentelemetry.io website

### Describe the solution you'd like

Move and adapt the documentation Readme: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md

**Comment by jeanbisutti** [comment]
@zeitlinger Could you please add the `spring boot starter` label?

**Comment by zeitlinger** [comment]
let's do this after https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9950

**Comment by Tejasker** [comment]
Hi @jeanbisutti , @zeitlinger is this issue related to a modification in the Document ie adding the Spring Auto-Configuration & modify the original Read.me then I can take up the issue & try to resolve it (Ie make modifications accordingly)

**Comment by jeanbisutti** [comment]
> Hi @jeanbisutti , @zeitlinger is this issue related to a modification in the Document ie adding the Spring Auto-Configuration & modify the original Read.me then I can take up the issue & try to resolve it (Ie make modifications accordingly)

@Tejasker The goal is to add and adapt the content of [this Readme](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md) to [this website page](https://opentelemetry.io/docs/instrumentation/java/automatic/spring-boot/).

**Comment by jeanbisutti** [comment]
@Tejasker @zeitlinger Are you interested in doing it this week? If not, I could create a PR next Wednesday or next Thursday.

**Comment by Tejasker** [comment]
@jeanbisutti, thanks for asking but I am new to open source, and while stumbling upon the large code base of open-telemetry either for front-end or other services,  feels like much overwhelming. not exactly sure where to start but 
I hope I can learn from your contribution✌️✌️.
Next time with the relativeness of your contribution I can move forward and will contribute 🤞🤞

**Comment by jeanbisutti** [comment]
@Tejasker The conversion of Groovy tests to Java could be a good way to start contributing: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7195

**Comment by jaydeluca** [comment]
@jeanbisutti if you haven't started this yet, I could take a shot at it

**Comment by jeanbisutti** [comment]
> @jeanbisutti if you haven't started this yet, I could take a shot at it

Not yet @jaydeluca. Great, don't hesitate to create a PR (even in draft) in the[ official documentation repo](https://github.com/open-telemetry/opentelemetry.io). I could have a look and provide feedback. Thanks!

**Comment by jaydeluca** [comment]
@jeanbisutti I started a draft PR:
https://github.com/open-telemetry/opentelemetry.io/pull/3758

I was unsure where to include the "Quickstart" instructions and the associated Dependency information. It seems like we want to distinguish between using the starter library and configuring everything separately, yes?

**Comment by jeanbisutti** [comment]
> @jeanbisutti I started a draft PR: [open-telemetry/opentelemetry.io#3758](https://github.com/open-telemetry/opentelemetry.io/pull/3758)
> 
> I was unsure where to include the "Quickstart" instructions and the associated Dependency information. It seems like we want to distinguish between using the starter library and configuring everything separately, yes?

@jaydeluca Thank you very much! By reading the new page, some sections could perhaps be moved to have on the same place the feature description and the necessary dependency. That may ease the reading. I will start to add comments to the draft PR.

**Comment by jaydeluca** [comment]
@jeanbisutti I was thinking we could update the existing docs in this repo as well with some of the changes made to the documentation site updates.

* Update [default value ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md?plain=1#L460)of `otel.exporter.otlp.endpoint` to `<http://localhost:4318>`
* Update [default value](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md?plain=1#L461) of `otel.exporter.otlp.protocol` to `http/protobuf`

If you agree, I can make the changes (and anything else you think might be worth changing)

**Comment by jeanbisutti** [comment]
> @jeanbisutti I was thinking we could update the existing docs in this repo as well with some of the changes made to the documentation site updates.
> 
> * Update [default value ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md?plain=1#L460)of `otel.exporter.otlp.endpoint` to `<http://localhost:4318>`
> * Update [default value](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md?plain=1#L461) of `otel.exporter.otlp.protocol` to `http/protobuf`
> 
> If you agree, I can make the changes (and anything else you think might be worth changing)

@jaydeluca The goal is to move the documentation of the readme files to the opentelemetry.io website. We could perhaps redirect to the website from  the [autoconfigure readme](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md) and the [Zipkin starter readme](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/starters/zipkin-spring-boot-starter/README.md), as we have done for the [OpenTelemetry starter readme](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/starters/spring-boot-starter/README.md).

What do you think?

If you agree, don't hesitate to create a PR in this repo!

**Comment by jaydeluca** [comment]
Sounds good @jeanbisutti,  I will take care of this. I'll wait until after https://github.com/open-telemetry/opentelemetry.io/issues/3911 is done since the links will change from that.

**Comment by jeanbisutti** [comment]
> Sounds good @jeanbisutti, I will take care of this. I'll wait until after [open-telemetry/opentelemetry.io#3911](https://github.com/open-telemetry/opentelemetry.io/issues/3911) is done since the links will change from that.

@jaydeluca we've actually kept a single page for Spring Boot, see https://github.com/open-telemetry/opentelemetry.io/pull/3985
