### ISSUE TITLE
Missing instrumentation for Apache HttpClient 5?

### ISSUE THREAD

**Issue by elbiocaetano** [open-telemetry/opentelemetry-java-instrumentation#10099]
### Discussed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/9969

<div type='discussions-op-text'>

<sup>Originally posted by **elbiocaetano** November 29, 2023</sup>
Hi 👋🏼 ,
We used to instrument Apache v4.3 using the library `io.opentelemetry.instrumentation:opentelemetry-apache-httpclient-4.3`. Now we are upgrading our Apache client to HttpClient v5, but I could not find an instrumentation for this version. I found the java-agent(`io.opentelemetry.javaagent.instrumentation:opentelemetry-javaagent-apache-httpclient-5.0`), but that looks not to have the same classes and features as the instrumentation one.
My question is: can we do the instrumentation as before somehow? Basically we would need a HttpClient with the OpenTelemetry injected in the request, to gather the tracing related to the http requests.
One example on what I want, on instrumentation for apache 4.3:

```java
JerseyClientBuilder jerseyClientBuilder = new JerseyClientBuilder(environment);
    jerseyClientBuilder.setApacheHttpClientBuilder(
        new HttpClientBuilder(environment) {
          @Override
          protected org.apache.http.impl.client.HttpClientBuilder createBuilder() {
            return ApacheHttpClientTelemetry.builder(openTelemetry).build().newHttpClientBuilder();
          }
        });
```

https://github.com/SDA-SE/sda-dropwizard-commons/blob/master/sda-commons-server-auth/src/main/java/org/sdase/commons/server/opa/OpaBundle.java#L182

Thanks in advance.</div>

**Comment by elbiocaetano** [comment]
I created a PR adding instrumentation for apache http client 5. I based on apache httpclient 4.3 implementation and adjusted to the new imports and APIs. I would appreciate your comments and suggestions.

**Comment by laurit** [comment]
Resoled in #10100
