### ISSUE TITLE
Optimize HttpClientTracer methods for invalid spans

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1009]
In particular, `startScope(Span, ...)` and `end*(Span, ...)` methods can be optimized for invalid spans.

This will be important after removing `CallDepth` (#907) which will then make the invalid span route more common.

**Comment by breedx-splk** [comment]
@trask Would you mind adding a little detail about what makes a span invalid and what that optimization might look like?

**Comment by trask** [comment]
@breedx-splk thx, #1840 addresses this, I'll note in that PR that it closes this issue

**Comment by mateuszrzeszutek** [comment]
@trask the PR you linked probably isn't going to be merged soon (😄 ), would you mind adding some explanation here? (Or closing this issue if it's no longer valid)

**Comment by trask** [comment]
oh ya, this is done now / no longer valid 👍
