### ISSUE TITLE
Add a way to disable specific attributes for metrics

### ISSUE THREAD

**Issue by SHaaD94** [open-telemetry/opentelemetry-java-instrumentation#10119]
### Is your feature request related to a problem? Please describe.

On the scale of thousands pods, some attributes are being less useful and create substantial load on the monitoring system.
For example attribute `net.sock.peer.port` of `http.server.*` metrics.

### Describe the solution you'd like

I would like to have some config to disable sending specific attributes.

### Describe alternatives you've considered

Currently we block them on the side of collector/storage, but in this case client side aggregation doesn't work due to cardinality of these tags.

**Comment by laurit** [comment]
This can be done using metric views https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator Note that the latest version of spec https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md does not include `net.sock.peer.port` you can use the `OTEL_SEMCONV_STABILITY_OPT_IN` flag to opt in to the new behavior.

**Comment by SHaaD94** [comment]
Thank you, I will have a look
