### ISSUE TITLE
Baggage MDC propagation in Webflux

### ISSUE THREAD

**Issue by bikerp** [open-telemetry/opentelemetry-java-instrumentation#10127]
### Discussed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/10112

<div type='discussions-op-text'>

<sup>Originally posted by **bikerp** December 21, 2023</sup>
I'm using otel.instrumentation.logback-mdc.add-baggage settings to add baggage into logs. I can see the baggage in logs for the same thread. However the baggage is not propagated to Webclient threads. Sounds like a bug to me.</div>

Here is the sample repository for demonstating the issue [otel-baggage](https://github.com/bikerp/otel-baggage)

**Comment by laurit** [comment]
Mono runs with the context that was active when mono was subscribed, try
```java
        Mono<String> mono = getRandomNumber(0, 10)
                .flatMap(__ -> register(player))
                .doFinally(signalType -> {
                    service.hello();
                    log.info("Finished with {}", signalType);
                });
        return new Mono<>() {
            @Override
            public void subscribe(CoreSubscriber<? super String> actual) {
                Baggage baggage = Baggage.builder().put("player", player).build();
                try (Scope scope = baggage.makeCurrent()) {
                    log.info("Play started for player {}", player);
                    mono.subscribe(actual);
                }
            }
        };
```
