### ISSUE TITLE
Global refactorings sometimes require IntelliJ cache invalidation

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1014]
I noticed it now when pulling master and noticed it once before, for some reason some imports get stuck unresolvable after global refactoring. I've only ever seen it on this repo. Not sure if it's specific to our Gradle configuration, but worst case we may at least provide a documentation about this behavior. Gradle "Reload all projects" doesn't solve it but restart and invalidate caches does.

![image](https://user-images.githubusercontent.com/198344/90327690-5676b300-dfd1-11ea-8d2c-3d3aea40b143.png)

**Comment by iNikem** [comment]
Cannot reproduce
