### ISSUE TITLE
The start timestamp of the downstream root span is not accurate enough

### ISSUE THREAD

**Issue by huyifan233** [open-telemetry/opentelemetry-java-instrumentation#10142]
### Is your feature request related to a problem? Please describe.
When there are calls between different applications, we find that there is an error in the start time of the upstream application span and the downstream application span.

We have marked the problematic spans with red boxes in the picture below.
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/25559907/aabba732-f5f5-4fd4-a6aa-89fd9d199235)
We have an upstream application called
`mall-insights-server-ot`  and a downstream application called `mall-gateway-ot` .

The **SpanName** of the `mall-insights-server-ot` is `POST /components/api/v1/mall/user_info` and the **SpanId** is `9588bfd6b377799b`, which start time is `1703841901617469200`.

The **SpanName** of the `mall-gateway-ot` is `/components/api/v1/mall/user_info` and the **SpanId** is `96e6798999a0cc91 `, which start time is `1703841901617000000`.

It is obvious that the start time of the downstream span loses nanosecond-level accuracy.

We checked the source code and found that after the downstream application receives the request, the agent will first create a `PropagatedSpan` and put it in the context.
Then when creating span in the `io.opentelemetry.instrumentation.api.instrumenter.Instrumenter#doStart` method , `io.opentelemetry.sdk.trace.SdkSpan#startSpan` will be called. Since `parentSpan` is an instance of `PropagatedSpan`, a new `AnchoredClock` will be created.
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/25559907/8bbab98e-b545-4a9d-a3ed-98fa8f0a1b04)

**It is worth noting that the initialization value of the `epochNanos` variable in AnchoredClock has lost nanosecond-level accuracy, which is used to set startEpochNanos.**  
`epochNanos` will be set using io.opentelemetry.sdk.common.SystemClock#now, which returns `TimeUnit.MILLISECONDS.toNanos(System.currentTimeMillis())`
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/25559907/41f5942f-95ec-4c3a-a53c-7ad0ae0a52be)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/25559907/f4209aa7-f552-4e84-84c7-2b33d7be7c8d)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/25559907/0e115f40-d394-42f9-9129-da1c0029c56b)

### Describe the solution you'd like

We use the `HttpClient` components as an example.
Is it possible to record the nanosecond-level start timestamp `startTimestampInNano` and `startNano=System.nanoTime()` in the request header of the upstream application.
When the downstream application restores the context from the http header, we could use `startTimestampInNano` + `System.nanoTime() - startNano` as the startEpochNanos of the downstream's root span.

**Comment by laurit** [comment]
Are you using jdk8? If you were using a newer jdk then jdk apis that https://github.com/open-telemetry/opentelemetry-java/blob/227580ba0956fcd43429d684b7e0798c8723481a/sdk/common/src/main/java9/io/opentelemetry/sdk/internal/Java9VersionSpecific.java#L40 allow getting current time with nanosecond precision could be used.

> We use the HttpClient components as an example.
Is it possible to record the nanosecond-level start timestamp startTimestampInNano and startNano=System.nanoTime() in the request header of the upstream application.
When the downstream application restores the context from the http header, we could use startTimestampInNano + System.nanoTime() - startNano as the startEpochNanos of the downstream's root span.

Have a look at https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/lang/System.html#nanoTime() values for `System.nanoTime()` are not guaranteed to be comparable between jvm instances.

**Comment by huyifan233** [comment]
> Are you using jdk8? If you were using a newer jdk then jdk apis that https://github.com/open-telemetry/opentelemetry-java/blob/227580ba0956fcd43429d684b7e0798c8723481a/sdk/common/src/main/java9/io/opentelemetry/sdk/internal/Java9VersionSpecific.java#L40 allow getting current time with nanosecond precision could be used.
> 
> > We use the HttpClient components as an example.
> > Is it possible to record the nanosecond-level start timestamp startTimestampInNano and startNano=System.nanoTime() in the request header of the upstream application.
> > When the downstream application restores the context from the http header, we could use startTimestampInNano + System.nanoTime() - startNano as the startEpochNanos of the downstream's root span.
> 
> Have a look at https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/lang/System.html#nanoTime() values for `System.nanoTime()` are not guaranteed to be comparable between jvm instances.

Thanks for your reply. 
We are using jdk8 and I read the api description of `System.nanoTime()` and found that their origins will be inconsistent for different jvm instances, which means the idea I proposed before is not feasible.
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/25559907/0b1d112f-e7f2-4c33-bd50-3b2721f4a3e7)

**Comment by laurit** [comment]
> Is there any way to solve this problem on jdk8?

The best way to solve this is updating the jdk. If that is not an option you could try building a custom agent that uses a better time source. For example you could try using JNI, JNA or JNR to call `gettimeofday` which should give time microsecond precision.
