### ISSUE TITLE
 Is there a better way to transform Jedis 4.x ?

### ISSUE THREAD

**Issue by huyifan233** [open-telemetry/opentelemetry-java-instrumentation#10167]
### Is your feature request related to a problem? Please describe.

Jedis client version we are using is **4.3.2**

We found that OpenTelemetry JavaAgent has transformed `redis.clients.jedis.Connection#sendCommand`. Then we checked the `sendCommand` method and found that this method does not seem to wait for the return of the redis server after sending the redis command. Will the span duration calculated in this way be accurate? 

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jedis/jedis-4.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v4_0/JedisConnectionInstrumentation.java

### Describe the solution you'd like

Is it a better way to transform`redis.clients.jedis.Connection#executeCommand(redis.clients.jedis.CommandObject<T>)`?

We noticed that several methods(`auth`, `clientSetname`, `select`, `ping` and `quit`) used when jedis initialized the connection or disconnected the connection directly called `sendCommand` instead of calling `executeCommand`. Could these methods be transformed separately?

**Comment by laurit** [comment]
@huyifan233 Is this a hypothetical question? Have you observed something that makes you believe that the span duration is not correct or did you come to this conclusion based on looking at the source code? If you look closely at the source code that you linked you'll notice that the span isn't really ended in the `sendCommand` method but in https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/a780d1e9b96483b8ac0e9bb1691efcb6cf234a6d/instrumentation/jedis/jedis-4.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jedis/v4_0/JedisInstrumentation.java#L62
