### ISSUE TITLE
Metrics lost when application in high load

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#10173]
### Describe the bug

When my application in high load, memory 70%, cpu 90%, it will lost metrics, it it a bug or feature?

### Steps to reproduce

1. run app
2. imitate high load environment
3. otlp will not upload metrics info

### Expected behavior

otlp can upload metrics normally

### Actual behavior

otlp will not upload metrics info

### Javaagent or library instrumentation version

1.15.0

### Environment

**JDK**: 11
**OS**: centos

### Additional context

the application metrics info was a bit too much, maybe it's one of the reason?

**Comment by laurit** [comment]
`1.15.0` is 1,5 years old please verify that this also happens with the latest release.
