### ISSUE TITLE
Add support for MyBatis framework

### ISSUE THREAD

**Issue by steverao** [open-telemetry/opentelemetry-java-instrumentation#10186]
### Is your feature request related to a problem? Please describe.

As a widely used persistence layer framework, `MyBatis` is widely used. Currently, the Span focus for database calls is only specific database types. For example, when using the mariadb client to call the database, the application layer will take a lot of time, but the specific database call will take very little time. It is not clear where the intermediate time is spent. , if the Mybatis can be supported, the time-consuming support of this type of framework can be clearly displayed to users. Will the community consider supporting it?

### Describe the solution you'd like

Add support for `MyBatis` framework

**Comment by AlchemyDing** [comment]
Project is here: [https://github.com/mybatis/mybatis-3](https://github.com/mybatis/mybatis-3)

**Comment by laurit** [comment]
> For example, when using the mariadb client to call the database, the application layer will take a lot of time, but the specific database call will take very little time.

Are you sure that this extra time is spent in MyBatis? I would have thought that MyBatis itself doesn't do much and even if you create spans for it they'd not be much different from the underlying jdbc spans.

**Comment by steverao** [comment]
> > For example, when using the mariadb client to call the database, the application layer will take a lot of time, but the specific database call will take very little time.
> 
> Are you sure that this extra time is spent in MyBatis? I would have thought that MyBatis itself doesn't do much and even if you create spans for it they'd not be much different from the underlying jdbc spans.

I did a preliminary implementation and found that this time-consuming process is actually much more time-consuming than underlying JDBC. For a simple application, the overall time consumption of Mybatis is about 2 times that of pure JDBC. The result are as follows:
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/25423978/1d857d38-1d37-4f63-8fd5-81ecf1034a01)
If we support relevant span, users will have a complete global perspective, which includes the connection pool acquisition time and database statement execution time, which can help users to better understand the complete time-consuming of their database-related operations.
