### ISSUE TITLE
Patch request: 1.32.1

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-instrumentation#10194]
### Is your feature request related to a problem? Please describe.

Requesting a patch to 1.32.1 to include a `jackson-databind` fix (from upstream sdk) and to improve the sqs instrumentation.

### Describe the solution you'd like

Patch 1.32.1 with the following PRs cherry picked:

* SDK 1.33.0 (#10041)
* SQS forEach support (#10062)

Thanks!

**Comment by trask** [comment]
> SDK 1.33.0 (https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10041)

I wasn't able to automatically backport this due to merge conflicts. Can you cherry-pick it manually and send PR to `v1.32.x` branch?

**Comment by breedx-splk** [comment]
I'll see what I can do.

**Comment by laurit** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.32.1
