### ISSUE TITLE
Change spring boot starter default otlp protocol from grpc to http/protobuf in 2.0.0

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#10206]
### Is your feature request related to a problem? Please describe.

I think we should probably switch the default otlp protocol in the spring boot starter (as well as the java agent) for 2.0.0

### Describe the solution you'd like

Switch the default otlp protocol in the spring boot starter for 2.0.0

**Comment by trask** [comment]
@jeanbisutti @zeitlinger do either of you have time to do this today or tomorrow before the 2.0.0 release goes out?

**Comment by wangzlei** [comment]
@trask @jeanbisutti Could you help us understand this issue, other than respect otel specification, is there other reason? We have production already sticks on grpc, want to get your insights whether we should move to http/protobuf after upgrading to 2.0, which is a breaking change in our production.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options

https://github.com/open-telemetry/opentelemetry-specification/blob/v1.28.0/specification/protocol/exporter.md#specify-protocol

**Comment by trask** [comment]
hi @wangzlei! this change was primarily done to align with the specification and other OpenTelemetry languages

**Comment by wangzlei** [comment]
Hi, @trask 
Are we good to continue use grpc in the future? 
Or I raise a stupid question, why OTel SDK would provide 3 options to customer: grpc, http/protobuf, http/json. Is there any performance or environment reason so customer has to manually override the default value?
