### ISSUE TITLE
Camel 2.x Timer Executions have Same Trace ID?

### ISSUE THREAD

**Issue by shameekagarwal** [open-telemetry/opentelemetry-java-instrumentation#10209]
### Describe the bug

so we have old apps running on camel 2.x  
luckily, camel 2.20+ has an [instrumentation library](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md)  
so, i upgraded my app to camel v2.22.5 and am adding auto instrumentation to them

however, for the [timer component](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/camel-2.20/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/apachecamel/decorators/TimerSpanDecorator.java)  
what i noticed is, all runs of the timer component have the same trace id :(  
is this expected? this does not feel right

e.g. i send my trace data to elasticsearch's apm  
our timer component runs every 5 minutes  
the ui crashes because every timer's run subsequently triggers a bunch of db and network calls  
and kibana tries to show all of them under the same trace id  
and the entire thing grows very quickly

### Steps to reproduce

Camel 2.22+

### Expected behavior

different trace id for every run

### Actual behavior

same trace id is used for every run

### Javaagent or library instrumentation version

1.31.0

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
Please provide a minimal sample app that reproduces the issue.

**Comment by shameekagarwal** [comment]
closing this, when i tried creating a minimal example, it worked  
there is some configuration that is causing this issue it seems, will try and debug the issue
