### ISSUE TITLE
Manage the SDK configuration issues in the Spring starter

### ISSUE THREAD

**Issue by jeanbisutti** [open-telemetry/opentelemetry-java-instrumentation#10213]
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10212#discussion_r1449020874 It may have other configuration issues to manage with the Spring starter.

### Describe the solution you'd like

Log warning or raise exception as the SDK does?

**Comment by trask** [comment]
> raise exception as the SDK does?

👍
