### ISSUE TITLE
when will 1.33.0 be released ?

### ISSUE THREAD

**Issue by flodetan** [open-telemetry/opentelemetry-java-instrumentation#10223]
### Is your feature request related to a problem? Please describe.

opentelemetry-java-instrumentation usually release a new version in the middle of each month. 2023 Dec should release 1.33.0. when will it be released ?

### Describe the solution you'd like

opentelemetry-java-instrumentation usually release a new version in the middle of each month. 2023 Dec should release 1.33.0. when will it be released ?

**Comment by laurit** [comment]
Next releases will be `2.0.0` and `1.32.1`, hopefully they'll be released in the next few days.
