### ISSUE TITLE
In vertx, traces information cannot be passed normally between multiple handlers

### ISSUE THREAD

**Issue by wang007** [open-telemetry/opentelemetry-java-instrumentation#10221]
### Describe the bug

In vertx-web, multiple handlers are used, but the next handler cannot fetch traces information
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/15957476/a001c41f-284d-4087-a371-163fe7ea2dd3)

### Steps to reproduce

*

### Expected behavior

*

### Actual behavior

*

### Javaagent or library instrumentation version

1.32.0

### Environment

Jdk: 8
OS: mac
vertx

**Comment by wang007** [comment]
try to use [VertxContextStorage](https://github.com/eclipse-vertx/vertx-tracing/blob/master/vertx-opentelemetry/src/main/java/io/vertx/tracing/opentelemetry/VertxContextStorageProvider.java) , but still failed.

**Comment by laurit** [comment]
Please provide a minimal sample application that reproduces your issue.

**Comment by wang007** [comment]
sorry， use [VertxContextStorage](https://github.com/eclipse-vertx/vertx-tracing/blob/master/vertx-opentelemetry/src/main/java/io/vertx/tracing/opentelemetry/VertxContextStorageProvider.java)  pass otel context normally，but logback cannot print trace_id

**Comment by wang007** [comment]
```
public class WorkerVerticle extends AbstractVerticle {

    private static final Logger logger = LoggerFactory.getLogger(WorkerVerticle.class);

    @Override
    public void start(Promise<Void> startPromise) throws Exception {

        Router router = Router.router(vertx);
        Redis client = Redis.createClient(vertx);
        RedisAPI api = RedisAPI.api(client);

        router.route("/test").handler(rc -> {
            logger.info("request /test");
            api.get("aaa").onComplete(ar -> {
                logger.info("redis callback: " + ar);
            });
            rc.end("ok");
        });

        vertx.createHttpServer().requestHandler(router).listen(8080);
    }
}
```

result:
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/15957476/9b01e5f3-a217-4153-a23e-ad9aad092484)

**Comment by wang007** [comment]
logback pattern:
```
    <property name="pattern"
              value="%d{yyyy-MM-dd HH:mm:ss.SSS} [%mdc{trace_id}] %(%-5level) - %([%20.20thread]) %(%40.40logger):%-3L  %(%msg%n)"/>
```

**Comment by wang007** [comment]
I'm not sure. I guess there's something wrong with the AgentContextWrapper agent processing

**Comment by laurit** [comment]
@wang007 could you provide a fully functional sample app that reproduces your issue as a github repository or zip. Include any instructions needed for reproducing the issue.

**Comment by wang007** [comment]
[starter.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/14161968/starter.zip)

add variable in your env variable 
`JAVA_TOOL_OPTIONS=-javaagent:./opentelemetry-javaagent.jar`

**Comment by laurit** [comment]
Instrumentation for vertx-redis-client was added in https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0 you will have to update your java agent.

**Comment by wang007** [comment]
only support context stroage to record traceid in logs?

**Comment by laurit** [comment]
> only support context stroage to record traceid in logs?

sorry, I have no idea what you mean by this.

**Comment by laurit** [comment]
> Printing a traceid to the log only retrieves the span information from the context, so why do you need to do a specific vertx-redis instrumentation？

OpenTelemetry specification defines semantic conventions for database clients https://github.com/open-telemetry/semantic-conventions/tree/main/docs/database We have instrumentations for multiple redis clients and other database clients that follow these semantic conventions. Naturally we also wish to have a similar instrumentation for vertx redis client. Having the context propagate to the callbacks is only a part of what the instrumentation does.

**Comment by wang007** [comment]
Naturally we also wish to have a similar instrumentation for vertx redis client. Having the context propagate to the callbacks is only a part of what the instrumentation does.

https://github.com/eclipse-vertx/vertx-tracing/blob/master/vertx-opentelemetry/src/main/java/io/vertx/tracing/opentelemetry/VertxContextStorageProvider.java

**Comment by laurit** [comment]
> But I actually used the context storage provided by vertx, which provides the context propagation mechanism by way of vertx context.
https://github.com/eclipse-vertx/vertx-tracing/blob/master/vertx-opentelemetry/src/main/java/io/vertx/tracing/opentelemetry/VertxContextStorageProvider.java

You are not using it in the sample app you provided. When using manual instrumentation you could replace the default context storage mechanism with the vertx once, but when using the javaagent that wouldn't work.

**Comment by wang007** [comment]
Is this a bug? Next will not do this function support, because this is the spi extension interface

**Comment by laurit** [comment]
> Is this a bug?

If you are referring agent not using the `VertxContextStorageProvider` then this is not a bug. Agent is started with the jvm, at this point your application and vertx classes may not be available.

> Next will not do this function support, because this is the spi extension interface

I have no idea what you mean by this.

**Comment by wang007** [comment]
ContextStorageProvider is SPI extension interface. Are there plans to support this feature for javaagent instrumentation?

**Comment by laurit** [comment]
> ContextStorageProvider is SPI extension interface. Are there plans to support this feature for javaagent instrumentation?

We have no such plans. Using it inside the agent is not feasible. Agent applies to the whole jvm, in one jvm you can have multiple applications which may or may not be running on vert.x. Context storage based on vert.x might not be appropriate for all of these. Additionally agent starts immediately when the jvm is started, vert.x classes may not be available at this point. Using SPI implementations that are provided by user code in the agent would surely create a mess that is hard to debug. That being said it does not mean that agent could not use vert.x context propagation mechanisms to propagate context in vert.x applications. We already do this for grpc, kotlin coroutines, zio. If there is need for vert.x specific context propagation that uses vert.x context to propagate otel context it could be implemented. For this to be considered it would require use cases that would show that the current approach is inadequate.

**Comment by wang007** [comment]
think you @laurit

**Comment by miteshaghera** [comment]
@wang007 How did you solve your problem? I'm facing exactly same issue. I have problem with only when I publish to or receive message from clustered event bus at that time it doesn't propagate tracing information in header.

@laurit After debugging, I found that `AgentContextStorage` doesn't delegate call to `VertxContextStorage`. AFAIK in vert.x, opentelemetry context needs to be attached to vert.x context for propagation in different places like eventbus.

**Comment by jianchaoxudd** [comment]
Hey @miteshaghera and @laurit , not sure if this is related, we are facing a issue where the Context is lost/reset after a Grpc/HttpClient2 call. However, VertxContextStorage still has the context.

**Comment by trask** [comment]
@jianchaoxudd can you open a new issue and provide a repro that can be used to troubleshoot / debug the issue?

**Comment by jianchaoxudd** [comment]
hey @trask ,

Thanks for quick response! I just create this [issue](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11860) with repro.
