### ISSUE TITLE
Both mongo-3.1 and mongo-3.7 instrumentation have same latestDepTest

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1023]
When looking at `latestDepTest`, I noticed that mongo-3.1 and mongo-3.7 both have the same latestDepTest version of `+`. This is unusual since it means that the old instrumentation works with the newer libraries. From what I can tell, mongo 3.7 instruments a new pattern for building a mongo client. Does it make sense to merge the instrumentation and just test both cases?

**Comment by trask** [comment]
Changed to `required-for-ga` with priority `p3`, to consider it for GA, since it is proposing a change to which instrumentation modules we publish (and I agree the overlap between `mongo-3.1` and `mongo-3.7` is confusing)

**Comment by anuraaga** [comment]
couchbase seems to be similar - while latestDepTest isn't exactly the same (spring-data-couchbase version is a bit different, java-client version is same), it seems to have a similar pattern. In fact, 2.6 instrumentation doesn't seem to work without 2.0 instrumentation available which is even more strange.

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
