### ISSUE TITLE
There is something wrong about the release note

### ISSUE THREAD

**Issue by steverao** [open-telemetry/opentelemetry-java-instrumentation#10232]
### Describe the bug

It doesn't contain github id of relevant contributors in [release note](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0) of 2.0.0, does it need to be adjusted?
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/25423978/09053a46-4b8b-48f9-b887-59b80004b4b9)

### Steps to reproduce

https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0

### Expected behavior

Add correct relevant contributors information

### Actual behavior

It doesn't contain github id of relevant contributors now.

### Javaagent or library instrumentation version

2.0.0

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
contributors list has been updated
