### ISSUE TITLE
I get the traceId in the function using @KafkaListener, but it is 0000000000.....

### ISSUE THREAD

**Issue by xiaoyao2246** [open-telemetry/opentelemetry-java-instrumentation#10247]
### Describe the bug

I used SpringBoot to build an application that annotated a function to consume Kafka messages using the @KafkaListener annotation; In this function, I want to print the currently consumed TraceId, and it prints out "000000000000000000000000".

However, TraceId exists in Trace data

May I ask why this is?

### Steps to reproduce

The code looks something like this：
```
    @KafkaListener(id = "xxxx", topics = {"xxxxx"}, containerFactory = "xxx", groupId = "xxxxx",
            autoStartup = "true")
    public void onMessageForPin(List<ConsumerRecord<String, String>> consumerRecords, Acknowledgment ack, Consumer<?, ?> consumer) {
        Span current = Span.current();
        String skTraceNo = current.getSpanContext().getTraceId();
        //All printed here are 00000000...
        System.out.println(skTraceNo);
    }
```

### Expected behavior

I want to print out the currently consumed traceId, consistent with the Trace data

### Actual behavior

I got "000000000000000000000000000."

### Javaagent or library instrumentation version

opentelemetry-agent 1.12x

### Environment

JDK :1.8
opentelemetry-agent : 1.12x
spring-kafka : 2.4.0.RELEASE
spring-boot : 2.2.2.RELEASE

### Additional context
The java argument I use is

```
-javaagent:/usr/opentelemetry/opentelemetry-javaagent-all.jar
            -Dotel.traces.sampler=parentbased_traceidratio
            -Dotel.traces.sampler.arg=0.2
            -Dotel.instrumentation.hibernate.enabled=false
            -Dotel.instrumentation.spring-data.enabled=false
            -Dotel.instrumentation.spring-webmvc.enabled=false
            -Dotel.instrumentation.servlet.enabled=false
            -Dotel.instrumentation.spring-integration.enabled=false
            -Dotel.instrumentation.spring-webflux.enabled=false
```

_No response_

**Comment by laurit** [comment]
1.12.0 is almost 2 years old, try with the latest version.

**Comment by xiaoyao2246** [comment]
@laurit 
Hi, I know 1.12 is not the latest version.
But now we have a large number of services using this version, so I want to figure out the cause of this problem and how to solve it, I need to measure the cost of upgrading the version and fixing this problem

**Comment by laurit** [comment]
If it does not work with the latest version then please provide a minimal application that reproduces the issue. If it works with the latest version then, if you so wish, you can find the commit/release that fixes the issue with doing a binary search with git bisect or by trying out the releases/commits between the latest and 1.12.0.
