### ISSUE TITLE
kafka_consumer_commit_sync_time_ns: duplicate metric name

### ISSUE THREAD

**Issue by lichenglin** [open-telemetry/opentelemetry-java-instrumentation#10289]
### Describe the bug

I have a java spring boot project. it use spring-kafka library to send kafka message.

when I upgrade agent version from 1.x to 2.0 . 

got error message in promethues exporter.

An Exception occurred while scraping metrics: java.lang.IllegalArgumentException: kafka_consumer_commit_sync_time_ns: duplicate metric name

but when I disable kafka moudule by  set env 

`OTEL_INSTRUMENTATION_KAFKA_ENABLED=false`, it works,

seems there is a confilict in `spring-kafka` and `kafka-client` moudules

### Steps to reproduce

create a spring boot project , add env 

JAVA_TOOL_OPTIONS="-javaagent:opentelemetry-javaagent.jar";OTEL_LOGS_EXPORTER=logging;OTEL_METRICS_EXPORTER=prometheus;OTEL_TRACES_EXPORTER=jaeger ;SPRING_PROFILES_ACTIVE=local

### Expected behavior

http endpiont return 200

### Actual behavior

http endpiont return 500

### Javaagent or library instrumentation version

2.0

### Environment

**JDK**:  17
**OS**: linux

**Comment by laurit** [comment]
Please provide a minimal application that reproduces the issue along with instructions needed to reproduce.

**Comment by lichenglin** [comment]
[yunwei-spring-demo.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/13986775/yunwei-spring-demo.zip)


> Please provide a minimal application that reproduces the issue along with instructions needed to reproduce.

**Comment by lichenglin** [comment]
> > [yunwei-spring-demo.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/13986775/yunwei-spring-demo.zip)
> > > Please provide a minimal application that reproduces the issue along with instructions needed to reproduce.
> 
> What do I have to do with the test app to reproduce the issue? Do I have to run kafka? Something else?

1. deploy a kafka at localhost.
2. run `mvn -DskipTests=true clean package`
3. run `java -D"otel.metrics.exporter"=prometheus -D"spring.proifles.active"=dev  -javaagent:opentelemetry-javaagent-2.0.0.jar -jar target/yunwei-spring-demo-0.0.1-SNAPSHOT.jar`
4. visite http://127.0.0.1:9464/
5. get error 
An Exception occurred while scraping metrics: java.lang.IllegalArgumentException: kafka_consumer_commit_sync_time_ns: duplicate metric name

**Comment by laurit** [comment]
Kafka metrics are reported by both kafka clients instrumentation and spring boot actuator instrumentation. You'll have to disable one of them. Try adding `-Dotel.instrumentation.kafka-clients-metrics.enabled=false` or `-Dotel.instrumentation.spring-boot-actuator-autoconfigure.enabled=false`.
@zeitlinger should we also disable the actuator instrumentation by default?

**Comment by zeitlinger** [comment]
> Kafka metrics are reported by both kafka clients instrumentation and spring boot actuator instrumentation. You'll have to disable one of them. Try adding `-Dotel.instrumentation.kafka-clients-metrics.enabled=false` or `-Dotel.instrumentation.spring-boot-actuator-autoconfigure.enabled=false`. @zeitlinger should we also disable the actuator instrumentation by default?

Yes, that was actually the intention of disabling micrometer - I didn't realize that there are other ways to get spring boot related metrics.
Maybe we should even consider this a bug fix for 2.0.0?

**Comment by trask** [comment]
> Maybe we should even consider this a bug fix for 2.0.0?

I would support that
