### ISSUE TITLE
Document logging configuration

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java-instrumentation#1032]
- Document why we are using slf4j instead of j.u.l.
- Want to configure log destination, log format
- Slf4j simple logger is very limited and shaded properties are not documented
- Document slf4j simple logger properties
- simplelogger.properties on the classpath
- Use / document external properties
- opentelemetry-javaagent.properties

**Comment by iNikem** [comment]
During SIG meeting we decided that current logging is purely implementation detail and is not part of the public surface. The only official way to alter javaagent logging is by using `otel.javaagent.debug` configuration property.
