### ISSUE TITLE
Added error in the tracking container

### ISSUE THREAD

**Issue by wanghao123123** [open-telemetry/opentelemetry-java-instrumentation#10332]
### Describe the bug

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38528031/a874e445-51f1-4734-8389-c92ba4cd5706)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38528031/cc41b4d2-6e6f-452a-a7ae-d44c083fe4ca)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38528031/de72dae9-8363-491c-add9-f2a34644de24)

### Steps to reproduce

1

### Expected behavior

1

### Actual behavior

1

### Javaagent or library instrumentation version

2.0

### Environment

**JDK**:
  8
**OS**:
 linux

### Additional context

1

**Comment by steverao** [comment]
From your logs, are you using the Spring Cloud Gateway application or other mounting probes to have this problem?

**Comment by laurit** [comment]
Could you provide a sample app that allows reproducing this.
