### ISSUE TITLE
RxJava1 instrumentation lacks tests

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1033]
There seem to be some indirect tests of Rxjava in other projects but unit tests in its project would make it easier to fix problems related to it's instrumentation.

**Comment by trask** [comment]
Closed by #2191 and #2672

**Comment by anuraaga** [comment]
Think this was about rxjava1

**Comment by trask** [comment]
Closing, it is at least transitively tested via couchbase-2.0 and hystrix-1.4 instrumentation, can revisit later if anyone has renewed interest.
