### ISSUE TITLE
MapConverter does not get initialized if some exporters are turned off

### ISSUE THREAD

**Issue by pmitura-lucid** [open-telemetry/opentelemetry-java-instrumentation#10344]
### Describe the bug

The `MapConverter` for `OTEL_RESOURCE_ATTRIBUTES` uses a `ConditionalOnBean` statement, that only includes it in the context if multiple exporter beans are in context at the same time: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/bc034f3b1b8d66e6c9f5a133407922278bc87086/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java#L66-L77

This, however, means that if only one of them us turned off (e.g. you do not want to use the logger exporter), and the resource attributes are set, the context initialization will fail with:
```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, java.lang.String>]
```

### Steps to reproduce

1. Set up a Spring Boot sample project with OTEL as specified in https://opentelemetry.io/docs/languages/java/automatic/spring-boot/
2. In envvars, include a sample `OTEL_RESOURCE_ATTRIBUTES` map (e.g. `var1=sample1,var2=sample2`), and turn off one of the exporters.
3. Run the application.

### Expected behavior

The application starts up.

### Actual behavior

The application startup fails on
```
Could not bind properties to 'OtelResourceProperties' : prefix=otel.resource, ignoreInvalidFields=false, ignoreUnknownFields=true","context":"default"}
```
due to 
```
 Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, java.lang.String>]
 ```

### Javaagent or library instrumentation version

1.34.1

### Environment

**JDK**: Corretto 21
**OS**: MacOS Ventura
Spring Boot 3.2.2

**Comment by laurit** [comment]
@zeitlinger could you take a look. I guess the intent was to create the map converter when any of these beans are present, but it really requires for all of them to be present.

**Comment by zeitlinger** [comment]
Yes, that's right - I didn't realize that.
