### ISSUE TITLE
Allow closing observers in oshi library

### ISSUE THREAD

**Issue by manikmagar** [open-telemetry/opentelemetry-java-instrumentation#10358]
### Is your feature request related to a problem? Please describe.

[oshi library](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/oshi/library) helps to capture the Process and System metrics. 

All observers are built with a callback but none of the returned `AutoCloseables` are captured for a clean shutdown at the end.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/oshi/library/src/main/java/io/opentelemetry/instrumentation/oshi/ProcessMetrics.java#L23C3-L38C16

```
public static void registerObservers(OpenTelemetry openTelemetry) {
    Meter meter = openTelemetry.getMeterProvider().get("io.opentelemetry.oshi");
    SystemInfo systemInfo = new SystemInfo();
    OperatingSystem osInfo = systemInfo.getOperatingSystem();
    OSProcess processInfo = osInfo.getProcess(osInfo.getProcessId());

    meter
        .upDownCounterBuilder("runtime.java.memory")
        .setDescription("Runtime Java memory")
        .setUnit("By")
        .buildWithCallback(
            r -> {
              processInfo.updateAttributes();
              r.record(processInfo.getResidentSetSize(), Attributes.of(TYPE_KEY, "rss"));
              r.record(processInfo.getVirtualSize(), Attributes.of(TYPE_KEY, "vms"));
            });
.
.
....
}
```

### Describe the solution you'd like

I would like the `registerObserver` method to return a list of AutoCloseables instead of void.  I am happy to send a PR if the proposed change is okay.

```
  public static List<AutoCloseable> registerObservers(OpenTelemetry openTelemetry) {
    Meter meter = openTelemetry.getMeterProvider().get("io.opentelemetry.oshi");
    SystemInfo systemInfo = new SystemInfo();
    HardwareAbstractionLayer hal = systemInfo.getHardware();
    
    List<AutoCloseable> observables = new ArrayList<>();
    observables.add(meter
        .upDownCounterBuilder("system.memory.usage")
        .setDescription("System memory usage")
        .setUnit("By")
        .buildWithCallback(
            r -> {
              GlobalMemory mem = hal.getMemory();
              r.record(mem.getTotal() - mem.getAvailable(), ATTRIBUTES_USED);
              r.record(mem.getAvailable(), ATTRIBUTES_FREE);
            }));

    ..... add other observers .....

    return observables;
}
```

This will then allow any calling classes to manage the cleanup.

[Java runtime metrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/runtime-telemetry/runtime-telemetry-java8/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/java8/MemoryPools.java#L64-L80) utilizes this proposed approach.

### Describe alternatives you've considered

I can create a custom implementation in my code and re-implement this but I would prefer to use this standard library instead.   I am happy to send a PR if the proposed change is okay.

**Comment by trask** [comment]
hi @manikmagar! it looks like the `runtime-telemetry` module is already using this pattern, so it sounds like a good idea to me

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/2a67c7e41fb9782096d40caa97197f1a90ea1319/instrumentation/runtime-telemetry/runtime-telemetry-java8/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/java8/GarbageCollector.java#L69

**Comment by manikmagar** [comment]
Thank you @trask for the super speedy response :). I will send the PR shortly.
