### ISSUE TITLE
Add the Spring resource detector to the OTel Spring starter

### ISSUE THREAD

**Issue by jeanbisutti** [open-telemetry/opentelemetry-java-instrumentation#10368]
### Is your feature request related to a problem? Please describe.

See https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10277#issuecomment-1918812591

### Describe the solution you'd like

Add the detector to the OTel Spring starter or the Spring autoconfigure dependency

We have to decide if the spring starter should support the [SDK loading style](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/aws-resources/src/main/resources/META-INF/services) -> this question is moved to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10409

**Comment by zeitlinger** [comment]
SDK loading style is discussed here: #10409
