### ISSUE TITLE
Add support Jetty 12

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#10387]
Spring Boot 3.2 uses Jetty 12 - to get full jetty support.

**Comment by trask** [comment]
> otherwise you don't get any server spans

I thought the servlet instrumentation would create the server span if the app server specific instrumentation didn't already?

**Comment by zeitlinger** [comment]
> > otherwise you don't get any server spans
> 
> I thought the servlet instrumentation would create the server span if the app server specific instrumentation didn't already?

No, apparently that doesn't happen - I've checked that in a [test](https://github.com/grafana/grafana-opentelemetry-java/blob/main/examples/jetty/spring-boot-non-reactive-3/build.gradle#L3)

**Comment by breedx-splk** [comment]
> > > otherwise you don't get any server spans
> > 
> > 
> > I thought the servlet instrumentation would create the server span if the app server specific instrumentation didn't already?
> 
> No, apparently that doesn't happen - I've checked that in a [test](https://github.com/grafana/grafana-opentelemetry-java/blob/main/examples/jetty/spring-boot-non-reactive-3/build.gradle#L3)

I'm also surprised by this result, and while yes sure, we should support the latest Jetty, I think it would be helpful to understand _why_ the servlet instrumentation didn't kick in.

**Comment by zeitlinger** [comment]
Turns out my test was misleading - we get a different server span, rather than no span at all.

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/2832627/3e1c3d68-b015-4815-adcf-30e1dc0ba458)
