### ISSUE TITLE
Add JDBC auto-instrumentation to the OTel starter

### ISSUE THREAD

**Issue by jeanbisutti** [open-telemetry/opentelemetry-java-instrumentation#10388]
Avoid user configuration and dependency addition (data source wrapping) for JDBC instrumentation.

**Comment by jeanbisutti** [comment]
Enable JDBC instrumentation without the need of any user configuration and have something that works with both a JVM runtime and a GraalVM native one.

**Comment by zeitlinger** [comment]
@jeanbisutti I think this can be closed
