### ISSUE TITLE
 Remove port and url in UrlInstrumentation. This requires updating tests.

### ISSUE THREAD

**Issue by heyams** [open-telemetry/opentelemetry-java-instrumentation#1039]
Do we need to remove url and port from HttpUrlInstrumentation as well?  
I forgot the reason why this was added to #912.  @trask

**Comment by trask** [comment]
Hey @heyams, I think since we set the port and url in `HttpClientTracer` now, this is not needed to be set in `UrlInstrumentation` anymore

**Comment by trask** [comment]
Closing in favor of #1045
