### ISSUE TITLE
Using agent, is it possible to automatically add span-links and relate sub-spans to the root span?

### ISSUE THREAD

**Issue by zhangjiabin1010** [open-telemetry/opentelemetry-java-instrumentation#10406]
### Is your feature request related to a problem? Please describe.

When performing aggregate analysis on sub-spans, I want to see what root spans the callers of the sub-span have. If traceid is used directly for correlation, the SQL statement will be very complicated and the query efficiency will be slow.

I hope that each span can have a field or attribute or link data ,have root_span = 'XXX', or root_span_id = 'xxxx', so that reverse search can be very convenient.

I found in the documentation that there is
[span-links](https://opentelemetry.io/docs/concepts/signals/traces/#span-links).

But I don’t know how to add it automatically in the agent of opentelemetry-java-instrumentation. Is it possible to achieve this function using extension? I have no idea.

Looking forward to anyone's ideas or suggestions, thanks.

### Describe the solution you'd like

Span add a field or attribute, root_span = 'XXX', or root_span_id = 'xxxx'

**Comment by laurit** [comment]
> When performing aggregate analysis on sub-spans, I want to see what root spans the callers of the sub-span have.

What do you mean by the `root spans`? The root span of the whole trace, or something else?

**Comment by zhangjiabin1010** [comment]
> > When performing aggregate analysis on sub-spans, I want to see what root spans the callers of the sub-span have.
> 
> What do you mean by the `root spans`? The root span of the whole trace, or something else?

Yes, The root span of the whole trace.

For example, trace: span A==>span B==>spanC

Expected results:
Add root_span = 'span A' to span A,
Add root_span = 'span A' to span B,
Add root_span = 'span A' in span C

This makes it easy to find the callers of each span.

**Comment by laurit** [comment]
I think the easiest way would be to use a `SpanProcessor`. In the `onStart` method you can use `LocalRootSpan.fromContextOrNull(...)`(https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/1f5fe2fdc3ffd1a1d5036b7432cf45537cddb8ad/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/LocalRootSpan.java#L45) and set the local root span id as an attribute on the span.
