### ISSUE TITLE
Re-use entire SDK auto-config in spring starter

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#10409]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10292 is re-using the OTLP exporter logic from SDK auto-config.

There are still parts of the SDK auto-config that are not re-used currently, such as [sampler](https://github.com/open-telemetry/opentelemetry-java/blob/c8e1e3619e922981922a1034ce07e2a13e99d819/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java#L162)

Technically, we could call the auto-config as a black box - and it would respect the spring properties.

## What are the problems with this approach?
- Users cannot supply beans programmatically, because the entire object graph is created in auto-config. Example: [SdkLoggerProvider](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/0fe6495d752d1de982aff9e5dedf224e885c2c5f/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java#L122)
- SpiHelper uses META-INF loading ([example](https://github.com/open-telemetry/opentelemetry-java/blob/5b497b115d567c725cb74dc1543f5e02e41b3fbf/exporters/otlp/all/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.traces.ConfigurableSpanExporterProvider#L1)) - wheres in Spring, users expect that `@Bean`s are collected - we should probably load both to meet the expectations of Spring users and library authors alike.

## Use Case 1: User supplies tracer provider

As a spring boot user, I want to provide my own instance of `SdkTracerProvider` (but let the framework configure the rest).
 
I'll configure the `SdkTracerProvider` programatically, using `SdkTracerProvider.builder()...`.

Right now, this use case is supported with `@ConditionalOnMissingBean`, which instructs spring to prefer a user supplied object if available:

[full code](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/3aa0f05b0ebb8263193e813d245cbfea1d9a5f90/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java#L105-L119)

```java
    @Bean    
    @ConditionalOnMissingBean
    public SdkTracerProvider sdkTracerProvider(..) { .. }
```

The above code copies [this part](https://github.com/open-telemetry/opentelemetry-java/blob/ee6c9867d736af7359003e0b2f61ebf082e6fe3e/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/AutoConfiguredOpenTelemetrySdkBuilder.java#L414-L426) of the SDK auto-config code - just to add this annotation.

## What can we do?

We can make the SpiHelper flexible enough that it allows 
- to pass in a discovery strategy
- to pass a callback interface that checks for user supplied objects - user supplied beans in the case of spring
- maybe also a callback to register the created objects in the spring bean context (not sure if there's a use case for that)

**Comment by jeanbisutti** [comment]
@zeitlinger 


> There are still parts of the SDK auto-config that are not re-used currently, such as [sampler](https://github.com/open-telemetry/opentelemetry-java/blob/c8e1e3619e922981922a1034ce07e2a13e99d819/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java#L162)

Do you have other examples in addittion to the sampler?

> Users cannot supply beans programmatically, because the entire object graph is created in auto-config

Could you please elaborate? The user could define his own `SdkTracerProvider` bean that could replace the one provided by the starter.

**Comment by zeitlinger** [comment]
> Do you have other examples in addittion to the sampler?

- resource providers: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10368
- batch processors: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8963, https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8962
- log limits: https://github.com/open-telemetry/opentelemetry-java/blob/c8e1e3619e922981922a1034ce07e2a13e99d819/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/LoggerProviderConfiguration.java#L116
- otel.metrics.exemplar.filter
- also span and metrics cardinality limits

**Comment by zeitlinger** [comment]
> The user could define his own `SdkTracerProvider`

Please see Use case 1 (but we can also discuss in a meeting :smile: )
