### ISSUE TITLE
should we remove deprecated properties before spring boot GA?

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#10418]
- the deprecated [enable](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/87615cc9d9577bdec93b00d9cffe5357913714a6/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/exporters/internal/ExporterConfigEvaluator.java#L16) checks
- [@WithSpan](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/c66c59a5b83a8ac41ddf788835f5e59bade3e886/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/instrumentation/annotations/InstrumentationAnnotationsAutoConfiguration.java#L35)
- [Propagation type](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e46ae82e943e9bd0075239e2f595ce15cee86caf/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/propagators/PropagationProperties.java#L18)

First issue to remove deprecated properties: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10450

**Comment by trask** [comment]
I'd personally support removing deprecated properties in the next monthly release (as long as there was a release already where they were deprecated). I think better to do it sooner than later given that we are doing a lot of improvements to the spring boot starter lately and so it will likely see a good number of new users in the near future.

**Comment by zeitlinger** [comment]
Some of the deprecation PRs are not [merged](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10408) or [created](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10409)

**Comment by zeitlinger** [comment]
done in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10454
