### ISSUE TITLE
update docs of spring starter properties

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#10419]
What should we do about the [spring starter config properties docs](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/3bd4558b66bb2c3a376be6d5af7ba662fdd8d814/instrumentation/spring/spring-boot-autoconfigure/README.md?plain=1#L393-L402) - because they are outdated and incomplete

- remove because it's in spring metadata
- remove because it will eventually move to opentelemetry.io
- update
- generate automatically from spring metadata

**Comment by jeanbisutti** [comment]
All the Spring starter related documentation was moved to  opentelemetry.io: https://opentelemetry.io/docs/languages/java/automatic/spring-boot/

See also https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10083#issuecomment-1920156944

**Comment by zeitlinger** [comment]
OK, then I guess the question applies to https://opentelemetry.io/docs/languages/java/automatic/spring-boot/#enablingdisabling-exporters - which has deprecated properties and is incomplete

**Comment by zeitlinger** [comment]
The docs have already been moved to opentelemetry.io - all changes to that page for 2.2.0 are tracked in https://github.com/open-telemetry/opentelemetry.io/issues/4027
