### ISSUE TITLE
Normalize "IN(?, ?, ...)" substrings in db.statement span attribute to "IN(?)" 

### ISSUE THREAD

**Issue by swar8080** [open-telemetry/opentelemetry-java-instrumentation#10442]
### Is your feature request related to a problem? Please describe.

Hello, we're looking to use `db.statement` as an attribute in span metrics to get RED metrics for each query

Currently, SQL queries using `IN` with a variable number of values will each generate a different `db.statement`, varying only by the number of `?` in the `IN` part. That can cause high cardinality span metrics and makes the metrics difficult to analyze

### Describe the solution you'd like

Replace all `IN(...)` statements in SQL `db.statement`s with a constant value like `IN( ? )`

### Describe alternatives you've considered

Using the otel collector to normalize the query string

### Additional context

Let me know if this would need to first be approved as a semantic convention

**Comment by trask** [comment]
this makes sense to me

possibly `IN(?, ...)` to be more explicit that it could be one or more elements

> Let me know if this would need to first be approved as a semantic convention

I don't think so, as there's no specification for how to normalize queries at this point

**Comment by laurit** [comment]
> possibly IN(?, ...) to be more explicit that it could be one or more elements

I suspect that backends might attempt to parse these queries so it might be better to ensure that normalization does not introduce syntax errors

**Comment by swar8080** [comment]
Would this new behaviour need to be turned on with configuration or a feature flag? Just wondering in case I or someone else ends up implementing this
