### ISSUE TITLE
Remove UrlInstrumentation

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1045]
HTTP URLs are already covered by `HttpUrlConnectionInstrumentation`.

Plus, this instrumentation only captures exceptions that occur, and "logs" those exceptions as spans (it doesn't capture any durations).

**Comment by dengliming** [comment]
> this instrumentation only captures exceptions that occur, and "logs" those exceptions as spans (it doesn't capture any durations).

Make sense for me. `remove it `+1
