### ISSUE TITLE
Updating to opentelemetry-bom 1.35.0 introduces a dependency on an incubator extension

### ISSUE THREAD

**Issue by pmitura-lucid** [open-telemetry/opentelemetry-java-instrumentation#10541]
### Describe the bug

After updating to opentelemetry-bom 1.35.0 (from 1.34.1), filters used in the Web MVC instrumentation depend on an `ExtendedSpan` incubator extension that is not included in the spring boot starter of this instrumentation library.

This causes calls to REST endpoints to fail during runtime, with an exception in a filter described below.

### Steps to reproduce

- Create a sample instrumented Spring Boot application as described in https://opentelemetry.io/docs/languages/java/automatic/spring-boot/, with the following relevant parts of the maven setup:

```xml
<dependencyManagement>
    <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom</artifactId>
        <version>1.35.0</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
    <dependency>
        <groupId>io.opentelemetry.instrumentation</groupId>
        <artifactId>opentelemetry-instrumentation-bom-alpha</artifactId>
        <version>2.0.0-alpha</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
    ...
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>io.opentelemetry.instrumentation</groupId>
        <artifactId>opentelemetry-spring-boot-starter</artifactId>
    </dependency>
    ...
</dependencies>
```

- Introduce a sample REST controller
- Run the application, and call the endpoint

### Expected behavior

The endpoint call succeeds

### Actual behavior

The endpoint call causes the instrumentation to throw a `ClassNotFoundException` exception for `ExtendedSpan` in filters:
```
java.lang.ClassNotFoundException: io.opentelemetry.extension.incubator.trace.ExtendedSpan
	at io.opentelemetry.sdk.trace.SdkSpanBuilder.startSpan(SdkSpanBuilder.java:220)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.doStart(Instrumenter.java:192)
	at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.start(Instrumenter.java:131)
	at io.opentelemetry.instrumentation.api.instrumenter.PropagatingFromUpstreamInstrumenter.start(PropagatingFromUpstreamInstrumenter.java:31)
	at io.opentelemetry.instrumentation.spring.webmvc.v6_0.WebMvcTelemetryProducingFilter.doFilterInternal(WebMvcTelemetryProducingFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	...
```

### Javaagent or library instrumentation version

2.0.0-alpha

### Environment

**JDK**: Corretto 21
**OS**: Mac OS Ventura
Spring Boot 3.2.2

### Additional context

As a workaround, the following dependency can be included in runtime to resolve the issue:
```xml
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-extension-incubator</artifactId>
            <version>1.35.0-alpha</version>
            <scope>runtime</scope>
        </dependency>
```

**Comment by laurit** [comment]
@pmitura-lucid could you try with https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.1.0 and see if that resolves the issue.

**Comment by pmitura-lucid** [comment]
Upgrading to v2.1.0 does resolve it, thank you!

**Comment by vordimous** [comment]
For future devs, this may or may not help your specific question, but I am in a gradle project and found that using the `"io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom"` and `"io.opentelemetry:opentelemetry-bom"` with their compatible versions, and setting the `"opentelemetry.version"` explicitely to be the same as `opentelemetry-bom`. Then the `"io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter"` would have all of its versions line up correctly.

```
set("opentelemetry.version", "1.53.0")
{ module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom", version = "2.19.0" }
{ module = "io.opentelemetry:opentelemetry-bom", version = "1.53.0" }
{ module = "io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter" }
```
