### ISSUE TITLE
java r2dbc databaseclient auto instrumentation not working when using .mapProperties() to map the result

### ISSUE THREAD

**Issue by alfozan42** [open-telemetry/opentelemetry-java-instrumentation#10544]
### Describe the bug

using opentelemetry-javaagent version: 1.32.1

using DatabaseClient to send a request to the db, there are several forms the data could be returned in including:
- .map(BiFunction<Row, RowMetadata, User> biFunction) 
- .mapProperties(User.class)

.map(BiFunction biFunction) works and is picked up by the instrumentation, however .mapProperties(User.class) goes completely undetected.

### Steps to reproduce

query the database using databaseclient then map the result using .mapProperties()

databaseClient
            .sql("select * from user where ...")
            .bind("a", b)
            .bind("c", d)
            .bindValues(e)
            .mapProperties(User.class).all();

### Expected behavior

the database call would be instrumented and shows up as a span in the trace

### Actual behavior

the database call span doesn't show up

### Javaagent or library instrumentation version

1.32.1

### Environment

**JDK**: 17
**OS**: Windows 10
**Spring Boot**: 3.2.2

**Comment by laurit** [comment]
Could you provide a minimal application that reproduce the issue.
