### ISSUE TITLE
detect service.name and service.version based on `Implementation-Title` and `Implementation-Version`

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#10615]
### Is your feature request related to a problem? Please describe.

- produces better results than jar file detector
- is not limited to spring boot, where a specialized detector based on build metadata exists: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10515

### Describe the solution you'd like

- see https://stackoverflow.com/questions/921667/how-do-i-add-an-implementation-version-value-to-a-jar-manifest-using-maven
- possible implementation: https://github.com/grafana/grafana-opentelemetry-starter/blob/main/src/main/java/com/grafana/opentelemetry/OpenTelemetryConfig.java#L211-L232

### Gradle

```groovy

jar {
    manifest {
        attributes("Implementation-Title": project.name, "Implementation-Version": version)
    }
}
```

**Comment by jeanbisutti** [comment]
>produces better results than jar file detector

Could you please elaborate

**Comment by zeitlinger** [comment]
> > produces better results than jar file detector
> 
> Could you please elaborate

Jar files sometimes get renamed in docker build files (e.g. to `app.jar`) - while metadata gets preserved.
