### ISSUE TITLE
how to disable the truncated of the db.statement

### ISSUE THREAD

**Issue by lichenglin** [open-telemetry/opentelemetry-java-instrumentation#10616]
### Is your feature request related to a problem? Please describe.

we found when there is a long sql. otel will truncate the sql. is there any way to disable it?

### Describe the solution you'd like

no truncate. keep the orginal sql.

**Comment by laurit** [comment]
Although it is possible to limit the max length of an attribute https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#attribute-limits by default this is not done. What is the size where the db statement is truncated? Are you sure that it is the agent that truncates not your backend or something else?

**Comment by laurit** [comment]
Could be https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/ddd780ad413932545861bab617e11329b148e424/instrumentation-api-incubator/src/main/jflex/SqlSanitizer.jflex#L53 You can verify whether this by disabling the sanitizer https://opentelemetry.io/docs/languages/java/automatic/configuration/#db-statement-sanitization
