### ISSUE TITLE
Add support for redisson instrumentation.

### ISSUE THREAD

**Issue by dengliming** [open-telemetry/opentelemetry-java-instrumentation#1061]
see: [https://github.com/redisson/redisson](https://github.com/redisson/redisson)

This framework provides redis-based functions, especially distributed locks, which are mainly used in our current projects. Recently, I plan to submit a PR to support it. Does it make sense to support it?

**Comment by iNikem** [comment]
If you use the library and want it being monitored, then of course :) Community contributions are welcomed!
