### ISSUE TITLE
Add extension functions for Ktor plugins

### ISSUE THREAD

**Issue by marychatte** [open-telemetry/opentelemetry-java-instrumentation#10617]
Hello!
In Ktor we added an [example](https://github.com/ktorio/ktor-samples/tree/main/opentelemetry) that uses your [plugins](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/ktor) for Ktor. We also added extension functions for [client](https://github.com/ktorio/ktor-samples/tree/main/opentelemetry/client/src/main/kotlin/opentelemetry/ktor/example/plugins/opentelemetry/extractions) and [server](https://github.com/ktorio/ktor-samples/tree/main/opentelemetry/server/src/main/kotlin/opentelemetry/ktor/example/plugins/opentelemetry/extractions) plugins that allow writing existing code in the Ktor DSL style. We want to suggest adding these functions to your source code to make the experience for Ktor users even better

**Comment by laurit** [comment]
[We'd welcome a contribution for this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/ISSUES.md#contribution-welcome)
