### ISSUE TITLE
Add tests for BaseTracer

### ISSUE THREAD

**Issue by heyams** [open-telemetry/opentelemetry-java-instrumentation#1063]
If there are any tests that came to mind when you wrote this TODO, I think it's better to file an issue with some examples. I have no idea how to resolve this TODO right now :P

_Originally posted by @anuraaga in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1040_

**Comment by trask** [comment]
Closing, looks like we have this already #986
