### ISSUE TITLE
Update runtime-telemetry-java17 to use stable semconv where applicable

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#10696]
Looks like it's still using the old semconv, e.g.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/cfd40a8c17e6889c2e8f28c166376619673cd3fb/instrumentation/runtime-telemetry/runtime-telemetry-java17/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/java17/internal/classes/ClassesLoadedHandler.java#L27

**Comment by robsunday** [comment]
I can take this on, please assign to me
