### ISSUE TITLE
The container.id resource attribute returned by ContainerResource.java does not work for a lot of container environments

### ISSUE THREAD

**Issue by liurui-1** [open-telemetry/opentelemetry-java-instrumentation#10719]
### Describe the bug

The container.id resource attribute returned by ContainerResource.java does not work for a lot of container environments. [CgroupV1ContainerIdExtractor.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV1ContainerIdExtractor.java) is OK. The problem is at [CgroupV2ContainerIdExtractor.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java). When the "/proc/self/cgroup" file does not include the container.id, with the "/proc/self/mountinfo" file, the [CgroupV2ContainerIdExtractor.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV2ContainerIdExtractor.java) usually returns a wrong value.

### Steps to reproduce

I have several typical "/proc/self/mountinfo" files (from Docker, Kubernetes and Openshift environments) can be used for test.
[mountinfo.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/14448084/mountinfo.zip)

### Expected behavior

```
For mountinfo-1: 188329f95b930c32eeeffd34658ed2538960947e166743fa3743f5ce3d739b40
For mountinfo-2: f2a44bc8e090f93a2b4d7f510bdaff0615ad52906e3287ee956dcf5aa5012a91
For mountinfo-3: a8f62e52ed7c2cd85242dcf0eb1d727b643540ceca7f328ad7d2f31aedf07731
For mountinfo-4: f23ec1d4b715c6531a17e9c549222fbbe1f7ffff697a29a2212b3b4cdc37f52e
```

### Actual behavior

```
For mountinfo-1: 188329f95b930c32eeeffd34658ed2538960947e166743fa3743f5ce3d739b40
For mountinfo-2: b136f3d296b4c2024b3e7ad816f2a804a47cf1acc3d445075c6d78cf159ef58d
For mountinfo-3: 2ac4c84cb0d3c3beb04beeef6ccf71c17b5fdd0252ce3a2b66bc2fdd0aaa1814
For mountinfo-4: 757a1c14bdd68b907c41f15436c0c2f9ec5a4cd4317135fcc1c4a64188db98d0
```
Only environment 1 is correct.

### Javaagent or library instrumentation version

[Version 1.33.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.33.0)

### Environment

**JDK**:
JDK 11
**OS**:
Ubuntu 20.04.6 LTS

### Additional context

I have code changes to support all my environments. I may create a PR if required.

**Comment by laurit** [comment]
@liurui-1 a PR would be awesome

**Comment by liurui-1** [comment]
Hi @laurit , I have submitted a [PR](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10737) for this issue.

**Comment by laurit** [comment]
Resolved with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10737
