### ISSUE TITLE
How to disable multiple annotations?

### ISSUE THREAD

**Issue by hatharom** [open-telemetry/opentelemetry-java-instrumentation#10722]
It is more of a question

With this environment variable OTEL_INSTRUMENTATION_OPENTELEMETRY_INSTRUMENTATION_ANNOTATIONS_EXCLUDE_METHODS
how to exclude all methods in a class or package?

The documentation says is must be in a format like 
my.package.MyClass1[method1,method2];my.package.MyClass2[method3]

But wildcarding doesnt work.Nor listing only package level.
 If I really have to write out all the method names then this envvar pretty useless in case of numerous withspan annotations

**Comment by laurit** [comment]
If you don't specify the method name it will exclude all methods in the given class.

**Comment by hatharom** [comment]
> If you don't specify the method name it will exclude all methods in the given class.

it doesnt:
my.package.MyClass1[*]
my.package.MyClass1

neither of these work

**Comment by laurit** [comment]
I tested it and indeed you are correct, currently there doesn't seem to be a way to exclude all methods from a class without listing the methods. I'll create a PR to address this.
