### ISSUE TITLE
Metrics :  test the metrics exporter end-to-end with the javaagent

### ISSUE THREAD

**Issue by philippeLepage** [open-telemetry/opentelemetry-java-instrumentation#1075]
# Test case - Default Config
Using OpenTelemetry as the exporter, validate that custom metrics created in an application are relayed properly through the java agent.

## Reason behind this validation
Excerpt from a [gitter conversation](https://gitter.im/open-telemetry/opentelemetry-java-instrumentation#) on August 19th 2020.

@philippeLepage
> I noticed that the TraceInstaller has 2 methods for creating its Span Exporter and Metrics Exporter.
> 
> One for the default config : [TraceInstaller. installExporters](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/090cdd782bd1889c23f082f587087c5500bddb19/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java#L64) 
> 
> And one for a provided jar that would contain the exporter(s) : [TraceInstaller.installExportersFromJar](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/090cdd782bd1889c23f082f587087c5500bddb19/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java#L91)
> 
> Now, I assume that I am using the default since I am not providing an external jar.  And OpenTelemetry exporter cannot be more default then anything else!
> 
> So, I must be passing through [TraceInstaller. installExporters](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/090cdd782bd1889c23f082f587087c5500bddb19/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java#L64)?  But what I noticed is that in that case, only the SpanExporter is being created.  No MetricsExporter?  
> 
> This is how I start my application : 
> 
> ```
> java -javaagent:"opentelemetry-javaagent-all-0.7.jar" \
>         -Dotel.exporter=otlp  \
>         -Dotel.otlp.endpoint=localhost:55680 \
>         -Dotel.resource.attributes=service.name=myservice \
>         -Dotel.bsp.schedule.delay=1000 \
>         -Dotel.imr.export.interval=1000 \
>         -Dotel.otlp.metric.timeout=1000 \
>         -Dio.opentelemetry.javaagent.slf4j.simpleLogger.defaultLogLevel=debug \
>      -jar "./target/myApp.jar"  
> ```

@trask :
> hi @philippeLepage! I'm not sure what might be wrong, i think it should be working, but i'm also not completely sure we've tested the metrics exporter end-to-end with the javaagent. Can you open an issue for this?

**Comment by wyTrivail** [comment]
looks like only spanexporter gets created by default based on [TraceInstaller. installExporters](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/090cdd782bd1889c23f082f587087c5500bddb19/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/TracerInstaller.java#L64).

do we want to create MetricExporterFactory in this method as well? or this is the expected behavior that for people who want to emit metrics through this javaagent, they will need to provide an external jar?

**Comment by iNikem** [comment]
Metric exporters should definitely be configured the same was as span exporters.

**Comment by philippeLepage** [comment]
Another excerpt from gitter :

**Comment by wyTrivail** [comment]
created a pr to fix this issue, https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1098, hope it helps
