### ISSUE TITLE
Document supported app servers in the README

### ISSUE THREAD

**Issue by johnbley** [open-telemetry/opentelemetry-java-instrumentation#1076]
I think it would be helpful if the README included a section about supported app servers (possibly including versions).  I took a poke around and saw that we have instrumentation, unit tests, or smoke tests involving at least Jetty, Tomcat, and Wildfly.  I know that the line between app server and framework/library can get blurry, but it would be helpful if somebody evaluating the project could quickly grep for `tomcat` and then look more deeply rather than erroneously deciding "oh, they don't seem to support Tomcat" and abandoning us.

**Comment by brianashby-sfx** [comment]
Linked PR: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2020

**Comment by trask** [comment]
Closed by #2020
