### ISSUE TITLE
GlobalOpenTelemetry - Auto Instrumentation - Custom Logging Framework Support  - Default Exporter

### ISSUE THREAD

**Issue by akumaburn** [open-telemetry/opentelemetry-java-instrumentation#10839]
### Is your feature request related to a problem? Please describe.

There doesn't appear to be default OLTP logging provider for GlobalOpenTelemetry

### Describe the solution you'd like

Were using our own custom logging framework (not log4j/jboss/or any of the others), we would like to be able to write log messages to the same endpoint were using for traces, but this doesn't appear to be supported. We would like this feature implemented (preferably with custom attributes support). 

Something like:

    private static final LoggerProvider loggerProvider = GlobalOpenTelemetry.getLoggerProvider();
    private static final Logger logger = loggerProvider.loggerBuilder("your.logger.name").build();

    public static void processMessages(List<LogMessage> messages) {
        // Additionally, send these messages to OpenTelemetry
        for (LogMessage message : messages) {
            // The specifics of this depend on your LogMessage class structure
            logger.logBuilder(Severity.INFO)
                   .setAttribute("custom.attribute", "value") // Customize as needed
                   .setBody(message.toString()) // Adjust based on your message format
                   .emit();
        }
    }

Here's the attributes we use for logging for example:

    private String  messageGUID;
    private Integer level;
    private String sessionGUID;
    private String    environment;
    private String    instanceID;
    private String    apiID;
    private String    servletID;
    private String    spanGUID;
    private String    traceUUID;
    private Timestamp timestamp;
    private String    message;

**Comment by laurit** [comment]
See https://github.com/open-telemetry/opentelemetry-java/blob/f83c020d4d2a11f16be8af739790718bb3413cba/api/all/src/main/java/io/opentelemetry/api/OpenTelemetry.java#L117-128

**Comment by akumaburn** [comment]
Why do we even have this stalebot

**Comment by akumaburn** [comment]
@laurit I meant the https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java , doesn't have `implements OpenTelemetry` in its class declaration.

Forgive me for assuming it was an OpenTelemetry instance but I noticed now that it can be accessed via `GlobalOpenTelemetry.get().getLogsBridge()` and that you have a `ObfuscatedOpenTelemetry globalOpenTelemetry` which holds the actual OpenTelemetry instance.
