### ISSUE TITLE
Extend JAX-RS/Jersey instrumentation

### ISSUE THREAD

**Issue by mityayak** [open-telemetry/opentelemetry-java-instrumentation#1086]
JAX-RS/Jersey instrumentation is missing auto-instrumentation for ReaderInterceptor, MessageBodyReader, ContainerResponseFilters, WriterInterceptor, MessageBodyWriter.
Take a look at https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/filters-and-interceptors.html and "10.4. Filter and interceptor execution order" chapter there.
Or you can see execution order diagram - https://www.baeldung.com/jersey-filters-interceptors#execution-order

**Comment by pavolloffay** [comment]
I have started looking into this. 

Since the client read and server write interceptors are invoked after the filters we will have to create new spans in the interceptors. 

Do we want to make the interceptor spans optional? If so how is this be handled? By using a different instrumentation name `io.opentelemetry.auto.jaxrs-client.interceptor-2.0`?

**Comment by laurit** [comment]
@mityayak Do you want the instrumentation to create a span for each filter and interceptor invocation?

**Comment by mityayak** [comment]
> @mityayak Do you want the instrumentation to create a span for each filter and interceptor invocation?

Yes I think it should be a new span for each interceptor

**Comment by iNikem** [comment]
> > @mityayak Do you want the instrumentation to create a span for each filter and interceptor invocation?
> 
> @laurit Yes I think it should be a new span for each interceptor and filter

What additional useful information will that provide? If there is a change of 5 filters, you will end up with 5 almost identical spans. Do you have a specific use-case that would benefit from that?

**Comment by mityayak** [comment]
> > > @mityayak Do you want the instrumentation to create a span for each filter and interceptor invocation?
> > 
> > 
> > @laurit Yes I think it should be a new span for each interceptor and filter
> 
> What additional useful information will that provide? If there is a change of 5 filters, you will end up with 5 almost identical spans. Do you have a specific use-case that would benefit from that?

We have multiple custom interceptors each doing they own custom logic and I would like to include them into auto-tracing.

**Comment by trask** [comment]
hey @mityayak, how about adding `@WithSpan` annotation on those custom interceptors?

**Comment by mityayak** [comment]
> hey @mityayak, how about adding `@WithSpan` annotation on those custom interceptors?

Yup that should work. I was just interested in having auto instrumentation in the same way as I got traces for all my endpoints without adding annotations manually.

**Comment by trask** [comment]
thx @mityayak! going to close this as we tend to be pretty conservative with capturing `INTERNAL` spans

**Comment by trask** [comment]
hey @mityayak! we try to be conservative about adding `INTERNAL` spans, since they tend to have high noise-to-value ratio for most users. we also try to be conservative about adding configuration options, since it's additional code paths that need to be tested and maintained. in this case also it looks like there is a good alternative via the `@WithSpan` annotation.

**Comment by mityayak** [comment]
@trask Forcing people to add WithSpan annotation would defeat main purpose of this project which is "ability to gather telemetry data from a Java application without code changes".  Filters and interceptors are crucial part of JAXRS specification and majority of applications with jaxrs usage are using them.

**Comment by mityayak** [comment]
You can think about it in a way as if for "Servlets" library you implemented only servlets and not filters

**Comment by trask** [comment]
> You can think about it in a way as if for "Servlets" library you implemented only servlets and not filters

We only capture the outermost SERVER span (first servlet or filter to be entered). We don't capture any INTERNAL spans for nested filters or for a servlet inside of a filter, for similar reasons mentioned above about INTERNAL spans.

**Comment by mityayak** [comment]
> > You can think about it in a way as if for "Servlets" library you implemented only servlets and not filters
> 
> We only capture the outermost SERVER span (first servlet or filter to be entered). We don't capture any INTERNAL spans for nested filters or for a servlet inside of a filter, for similar reasons mentioned above about INTERNAL spans.

@trask JAXRS filters and interceptors are outer entities. They are not executed inside of any other spans, i.e. they are not internal.

**Comment by trask** [comment]
Re-opening since it seems some clarity is still needed here

**Comment by trask** [comment]
@mityayak I'm still unclear on this, 

> JAXRS filters and interceptors are outer entities. They are not executed inside of any other spans, i.e. they are not internal.

aren't they executed inside of a servlet request or application server request span that is already captured by other instrumentation?

maybe you could provide a small sample application to show exactly the kind of request you are talking about?
