### ISSUE TITLE
Add some span attribute to baggage so that downstream services can gain some information of calling service.

### ISSUE THREAD

**Issue by GlassyYang** [open-telemetry/opentelemetry-java-instrumentation#10889]
### Is your feature request related to a problem? Please describe.

Sometimes, services want to know some information on which service send the request, the request is about to which entity (such as user id, order id, etc.), and this information is not always passing by parameters.  Mayby javaagent should add a feature to add some soan attributes to baggage configuably to support this situation.

### Describe the solution you'd like

I want javaagent to automaticlly add some span attributes to baggage so than downstream services can gain the information, but currently the javaagent seems like not support.

### Describe alternatives you've considered

The javaagent can automatically add some span attributes to baggage.

**Comment by steverao** [comment]
Maybe `SpanProcessor` can meet your demand, for more information you can see:

1. Relevant concept: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-processor
2. Relevant case: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/README.md#extensions-examples

**Comment by GlassyYang** [comment]
I have read the code before and know than `SpanProcessor` can meet the request, but I can't find any implementation class to do this. Can I contribute to this repository? If not, I will realize by myself and use it in my own environment. Anyway, I think it a useful feature which can connect between baggage and span easily. It's a good way to deliver some common information between services without adding tracing relative code to services, which is commonly inconvenient.

**Comment by steverao** [comment]
> I have read the code before and know that `SpanProcessor` can meet the request, but I can't find any implementation classes to do this. Can I contribute to this repository? If not, I will realize by myself and use it in my own environment. Anyway, I think it a useful feature which can connect between baggage and span easily. It's a good way to deliver some common information between services without adding tracing relative code to services, which is commonly inconvenient.

Sorry, I didn't understand what you want to do clearly. Can you explain more about your thought?

**Comment by GlassyYang** [comment]
I mean, there are no such implementation of `SpanProcessor` in javaagent I can use directly. Should we add one?

**Comment by laurit** [comment]
Instead of implementing every feature requested by the users we offer an [extension mechanism](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension) that allows users to extend the agent as suited by their needs. For example you could build an extension that provides a custom baggage propagator that copies the attributes you are interested in into the baggage before delegating to the default `W3CBaggagePropagator`. I don't think you can implement this using the `SpanProcessor` as inside the `SpanProcessor` you can't easily add new baggage entries.
