### ISSUE TITLE
 How to filter traces that don't need to be collected

### ISSUE THREAD

**Issue by commonfurture** [open-telemetry/opentelemetry-java-instrumentation#10886]
### Is your feature request related to a problem? Please describe.

There is a java service here that uses opentelemetry-agent.jar to automatically collect traces. Now I have a problem. As long as an exception is thrown in the service, it will be collected by the  opentelemetry-agent.jar . Is there a way to filter out the exception traces that do not need to be collected?

### Describe the solution you'd like

I hope to filter traces that don't need to be collected by configuring span names.

**Comment by trask** [comment]
hi @commonfurture! I believe you could achieve this using a [Java agent extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension#extensions), or maybe more easily by configuring an [OpenTelemetry Collector processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor)
