### ISSUE TITLE
Spring Cloud Gateway thread context information not cleared.

### ISSUE THREAD

**Issue by GhostBoyBoy** [open-telemetry/opentelemetry-java-instrumentation#10894]
### Describe the bug

**Describe the bug**
env:  jdk17, macos(m2), javaagent: 2.2(1.36), springcloud gateway version: 3.1.4, spring boot: 2.6.13, spring cloud: 2021.0.5
maven: 3.9.4
`<dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-api</artifactId>
            <version>1.36.0</version>
        </dependency>`

desc: Using the gateway global filter to pass data using [io. opentelemetry.api. baggage. Bagage], multiple requests for the same thread context data are consistent with the same traceID. After testing, it was found that if [io. opentelemetry. api. baggage. Bagage] is not used, it is normal.

![image](https://github.com/open-telemetry/opentelemetry-java/assets/38995810/3d84403e-8c06-48eb-b802-6da78047e4f9)

### Steps to reproduce

Global filters use [io. openTelemetry. api. baggage. Baggage] to add data

### Expected behavior

Request ended, thread context cleared to generate a new traceid

### Actual behavior

Multiple requests, same thread with the same traceid

### Javaagent or library instrumentation version

2.2

### Environment

**JDK**: 17
**OS**: mac os m2

**Comment by laurit** [comment]
From the provided screenshot it is clear that the bug is in your code. The scope returned from `makeCurrent` must be closed, failure to do so may result in leaking a context.

**Comment by GhostBoyBoy** [comment]
> From the provided screenshot it is clear that the bug is in your code. The scope returned from `makeCurrent` must be closed, failure to do so may result in leaking a context.

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38995810/8d8f1354-fc5a-4cc3-bb28-0508eb6eb417)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38995810/2c2cfd67-02b8-400d-a0bb-f6b7205b47fb)

This method is not feasible because when [reactor-http-nio-5] executes close(), the thread pool above receives a new request

**Comment by GhostBoyBoy** [comment]
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38995810/9a9e8659-c593-4a73-bb28-a982eaea5060)
This method is also not feasible because the data has not yet been passed to the next application and has been cleared. The next application requests headers without Bagge content.

**Comment by GhostBoyBoy** [comment]
> From the provided screenshot it is clear that the bug is in your code. The scope returned from `makeCurrent` must be closed, failure to do so may result in leaking a context.

Please tell me the correct way to close it?

**Comment by laurit** [comment]
`Mono` uses the context from the time when `Mono` is subscribed. See https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e4e224beffa4eeee62765648718e3927d38d9218/instrumentation/spring/spring-webflux/spring-webflux-5.3/library/src/main/java/io/opentelemetry/instrumentation/spring/webflux/v5_3/TelemetryProducingWebFilter.java#L36 for inspiration. The code there also wraps the subscriber, you probably won't need that. Just set the baggage to whatever you want around calling `source.subscribe(actual);`

**Comment by GhostBoyBoy** [comment]
> `Mono` uses the context from the time when `Mono` is subscribed. See
> 
> https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e4e224beffa4eeee62765648718e3927d38d9218/instrumentation/spring/spring-webflux/spring-webflux-5.3/library/src/main/java/io/opentelemetry/instrumentation/spring/webflux/v5_3/TelemetryProducingWebFilter.java#L36
> 
> for inspiration. The code there also wraps the subscriber, you probably won't need that. Just set the baggage to whatever you want around calling `source.subscribe(actual);`

Sorry, I still don't know how to do it. Can you write a simple demo code?

**Comment by laurit** [comment]
> Sorry, I still don't know how to do it. Can you write a simple demo code?

No, I can't. I don't know enough about spring cloud gateway to be able to easily produce a working demo application. You will have to provide a minimal sample application along with any instructions needed for reproducing the issue that you have.

**Comment by GhostBoyBoy** [comment]
> > Sorry, I still don't know how to do it. Can you write a simple demo code?
> 
> No, I can't. I don't know enough about spring cloud gateway to be able to easily produce a working demo application. You will have to provide a minimal sample application along with any instructions needed for reproducing the issue that you have.

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38995810/44e3dda7-4e87-441a-9af6-6b909ea414f5)
ok, handle it this way, right?

**Comment by GhostBoyBoy** [comment]
> > Sorry, I still don't know how to do it. Can you write a simple demo code?
> 
> No, I can't. I don't know enough about spring cloud gateway to be able to easily produce a working demo application. You will have to provide a minimal sample application along with any instructions needed for reproducing the issue that you have.

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38995810/787d889e-6347-4bfb-b1b4-89bf76170f06)
This problem seems to be solved by handling multiple requests with the same thread without duplicate trace IDs, and the baggage data is also passed to other applications.
