### ISSUE TITLE
extensions Supports Multi-Level Directory

### ISSUE THREAD

**Issue by crossoverJie** [open-telemetry/opentelemetry-java-instrumentation#10928]
### Is your feature request related to a problem? Please describe.

```shell
-Dotel.javaagent.extensions=/extensions

tree extentions/
extentions/
├── 1.jar
└── next
    └── next.jar
```

This only load `1.jar`

### Describe the solution you'd like

We'd better load `next.jar`, contains all subdirectories under the current directory(/extensions).

**Comment by laurit** [comment]
I'd be more inclined to say that we don't want to support this. Recursively scanning directories can be time consuming and in the presence of symbolic links could contain loops. Have you considered instead using something like `find /absolute/path/ -name "*.jar" | tr '\n' ',' | sed 's/,$/\n/'` and using the result for `-Dotel.javaagent.extensions` (it can be set to comma separated list of jars).
If you believe that this is a useful feature you are welcome to raise the discussion at the java SIG meeting or elaborate here why this feature should be implemented.
