### ISSUE TITLE
Double Server span create by lambda instrumentation

### ISSUE THREAD

**Issue by cleverchuk** [open-telemetry/opentelemetry-java-instrumentation#10931]
### Describe the bug

This relates to this [issue](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7808). The bug still exists when running on Java 8 or 11 lambda runtimes. One thing that's different is the customer class loader is `lambdainternal.CustomerClassLoader` which is different from `com.amazonaws.services.lambda.runtime.api.client.CustomerClassLoader`

### Steps to reproduce

Deploy and invoke a sqs lambda handler with the javaagent. Ensure the handler name has `::handleRequest` suffix and not just the class name.

### Expected behavior

Only one server span.

### Actual behavior

Two server spans were created

### Javaagent or library instrumentation version

2.2.0

### Environment

**JDK**: 8 and 11
**OS**: linux

**Comment by laurit** [comment]
cc @tylerbenson

**Comment by serkan-ozal** [comment]
@laurit @tylerbenson I think I can take this one if no one has started working on it. We also need to add `lambdainternal` package prefix in addition to `com.amazonaws.services.lambda.runtime.api.client` prefix to be skipped for handler instrumentation.

**Comment by serkan-ozal** [comment]
@laurit @tylerbenson Here it is: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10942
I have also made simple hacks to get the AWS Lambda runtime internal classes directly from AWS Lambda environment to be sure that we are not missing anything.
