### ISSUE TITLE
Debug argument does not work

### ISSUE THREAD

**Issue by jamesylgan** [open-telemetry/opentelemetry-java-instrumentation#1095]
Hi open-telemetry team!

I was trying to turn on debug logging today and noticed that the arg to enable debugging that's included in the README doesn't work (does not enable debug logging):
`-Dio.opentelemetry.javaagent.slf4j.simpleLogger.defaultLogLevel=debug`

Instead, this is what worked:
`-Dio.opentelemetry.auto.slf4j.simpleLogger.defaultLogLevel=debug`

Does anyone have an idea for why this might be? I'm wondering if it's a local issue or if the docs need to be updated.

**Comment by trask** [comment]
Hi @jamesylgan! Oops, it looks like I broke the doc, and updated it to reflect latest SNAPSHOT (our goal is to keep the doc updated to latest RELEASE only). I will fix 👍.
