### ISSUE TITLE
 No method level trace information output

### ISSUE THREAD

**Issue by goodLuckForWorld** [open-telemetry/opentelemetry-java-instrumentation#10960]
**Describe the bug**
I'm using latest OpenTelemetry Java Agent for getting trace info from controller to  query data base ,but there is no method level invoke trace export to zipkin,（only start(controller info) and end(db info:like sql statment,database url...)）,I want to get method name witch invoke db access

**Steps to reproduce**
below is my config:
java -javaagent:opentelemetry-javaagent.jar 
-Dotel.service.name=test 
-Dotel.exporter.zipkin.endpoint=http://192.168.0.3:9411/api/v2/spans 
-Dotel.traces.exporter=zipkin 
-Dotel.metrics.exporter=none 
-Dotel.logs.exporter=none 
-Dotel.instrumentation.methods.enabled=true 
-Dotel.instrumentation.common.default-enabled=true 
-Dotel.instrumentation.opentelemetry-api.enabled=true 
-Dotel.instrumentation.opentelemetry-instrumentation-annotations.enabled=true 
-Dotel.instrumentation.common.experimental.controller-telemetry.enabled=true 
-jar myApp.jar

I set -Dotel.instrumentation.methods.enabled=true but there is no methods level trace info,can you help how could I get such info with auto config,Thanks you!

**Comment by zhangjiabin1010** [comment]
Is there a solution to this problem, I need it too。
