### ISSUE TITLE
Application stop when enabling Metrics

### ISSUE THREAD

**Issue by baole229801** [open-telemetry/opentelemetry-java-instrumentation#10961]
### Describe the bug

We running an OpenJDK 21 application and having opentelemetry agent attached to collect traces and metrics, which is the newest version agent.
[otel.javaagent 2024-03-27 08:42:07:956 +0700] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 2.2.0
[otel.javaagent 2024-03-27 08:42:07:957 +0700] [main] DEBUG io.opentelemetry.javaagent.tooling.VersionLogger - Running on Java 21.0.2. JVM OpenJDK 64-Bit Server VM - Red Hat, Inc. - 21.0.2+13-LTS

This is the configuraton: of the agent:
otel.javaagent.enabled=true
otel.service.name=...
otel.resource.attributes=...
otel.traces.exporter=otlp
otel.logs.exporter=none
otel.metrics.exporter=otlp
otel.exporter.otlp.traces.endpoint=http://nginx.elastic.svc.cluster.local:8200/v1/traces --> Traces sent to Elastic
otel.exporter.otlp.metrics.endpoint=http://otelcol-prometheus-collector.elastic.svc.cluster.local:4318/v1/metrics --> Metrics sent to Otel Collector and collected by Prometheus

When using otel.metrics.exporter=otlp, after a while, the application stop working, we have tried many configuration and found that disabling metric otel.metrics.exporter=none, the application start working stable.

I have the debug log of the agent when starting up the application, but cannot show here public.

### Steps to reproduce

[otel.javaagent 2024-03-27 08:42:07:956 +0700] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 2.2.0
[otel.javaagent 2024-03-27 08:42:07:957 +0700] [main] DEBUG io.opentelemetry.javaagent.tooling.VersionLogger - Running on Java 21.0.2. JVM OpenJDK 64-Bit Server VM - Red Hat, Inc. - 21.0.2+13-LTS

This is the configuraton: of the agent:
otel.javaagent.enabled=true
otel.service.name=...
otel.resource.attributes=...
otel.traces.exporter=otlp
otel.logs.exporter=none
otel.metrics.exporter=otlp
otel.exporter.otlp.traces.endpoint=http://nginx.elastic.svc.cluster.local:8200/v1/traces --> Traces sent to Elastic
otel.exporter.otlp.metrics.endpoint=http://otelcol-prometheus-collector.elastic.svc.cluster.local:4318/v1/metrics --> Metrics sent to Otel Collector and collected by Prometheus

### Expected behavior

We have applications running with this topology working fine, they run jdk8 jdk11 jdk17, but for jdk21 we have this issue

### Actual behavior

Application stop receiving requests

### Javaagent or library instrumentation version

opentelemetry-javaagent - version: 2.2.0

### Environment

**JDK**:
**OS**:

**Comment by steverao** [comment]
Is there any error logs printed when your application stop?

**Comment by baole229801** [comment]
2024-03-28T03:25:44.067Z	error	prometheusexporter@v0.93.0/log.go:23	error encoding and sending metric family: write tcp 10.252.7.99:8889->10.253.5.86:44768: write: broken pipe
	{"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
	github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.93.0/log.go:23
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1.2
	github.com/prometheus/client_golang@v1.18.0/prometheus/promhttp/http.go:192
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
	github.com/prometheus/client_golang@v1.18.0/prometheus/promhttp/http.go:210
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2136
net/http.(*ServeMux).ServeHTTP
	net/http/server.go:2514
go.opentelemetry.io/collector/config/confighttp.(*decompressor).ServeHTTP
	go.opentelemetry.io/collector/config/confighttp@v0.93.0/compression.go:147
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.47.0/handler.go:225
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
	go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.47.0/handler.go:83
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2136
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
	go.opentelemetry.io/collector/config/confighttp@v0.93.0/clientinfohandler.go:28
net/http.serverHandler.ServeHTTP
	net/http/server.go:2938
net/http.(*conn).serve
	net/http/server.go:2009

This is the error log from otel collector when using receiver = otlp, exporter = prometheus

**Comment by laurit** [comment]
> Could this issue related to otel collector?

Here we only deal with issues related to the open telemetry java instrumentation. For collector issues you should turn to the collector folks.
