### ISSUE TITLE
When the netty module processes http requests, use the url as the span name

### ISSUE THREAD

**Issue by lichenglin** [open-telemetry/opentelemetry-java-instrumentation#10993]
### Is your feature request related to a problem? Please describe.

We will use the sping gateway as the entry point for traffic and find that when the request passes through the component,netty generates a span name of this "gateway-v2: POST ReactiveCompositeDiscoveryClient_CRITEO - TEST ", it doesn't look friendly.

I have upload the trace json in jaeger.

### Describe the solution you'd like

We hope the contents of "url.path =criteo-test/api/Report/lineItem" to be the span name

### Additional context

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/8294900/7ec40dc9-cb59-4476-9204-1cbe549bfd27)
[trace.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/14818674/trace.txt)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/8294900/d46d15a8-68a9-4e87-ab48-1d457a61b2bc)

**Comment by laurit** [comment]
Opetelemetry specification https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name gives guidelines for naming http spans. These guidelines state that

> Instrumentation MUST NOT default to using URI path as span name, but MAY provide hooks to allow custom logic to override the default span name. 

`ReactiveCompositeDiscoveryClient_CRITEO - TEST` comes from `http.route` this should correspond to the route id in the spring cloud gateway. Have you considered changing the route ids in your application to get better span names?

**Comment by chenglinli0** [comment]
Solved , I create a global filter and change the span name.
`return chain.filter(exchange.mutate().request(exchange.getRequest().mutate().header("otel.user.id", userId).header("otel.source.ip", ipAddress).build()).build()).then(Mono.fromRunnable(() -> {
            HttpHeaders headers = exchange.getResponse().getHeaders();
            Span.current().updateName(exchange.getRequest().getPath().value());
            headers.add("otel.trace.id", Span.current().getSpanContext().getTraceId());
        }));`
