### ISSUE TITLE
Tracing for Spring Data CoroutineCrudRepository methods is timed incorrectly

### ISSUE THREAD

**Issue by ofelbaum** [open-telemetry/opentelemetry-java-instrumentation#11035]
### Describe the bug

It looks like traces collected for Spring Data repositories (backed by CoroutineCrudRepository) are reflecting just "assembly" phase. They typically are measured in microseconds (μs).

### Steps to reproduce

Here is the project to demonstrate the issue https://github.com/ofelbaum/r2dbc-coroutine-demo

### Expected behavior

Span duration for spans collected by "io.opentelemetry.spring-data" instrumentation is reflecting actual duration of an RDBMS operation

### Actual behavior

Span duration for spans collected by "io.opentelemetry.spring-data" instrumentation is not reflecting actual duration of an RDBMS operation

### Javaagent or library instrumentation version

https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.2.0/opentelemetry-javaagent.jar

### Environment

**JDK**: Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29)
**OS**:  macOS 14.2.1

### Additional context

Looks like this issue is closely related to another https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9500

**Comment by ofelbaum** [comment]
@laurit Thanks. I appreciate your help with fixing this.

As it was mentioned the issue might be fixed in [#11168](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11168).
I upgraded javaagent library from 2.2.0 to [2.4.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.4.0) in [sample demo](https://github.com/ofelbaum/r2dbc-coroutine-demo) I prepared, but still have the issue :(

**Comment by laurit** [comment]
Try the agent from https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/10596784571?pr=12131 You can find it in the Artifacts section at the bottom of the page. Let us know whether it resolves the issue.
