### ISSUE TITLE
Need to create a bean OtlpHttpSpanExporter before opentelemetry spring boot starter.

### ISSUE THREAD

**Issue by DineshkumarVG** [open-telemetry/opentelemetry-java-instrumentation#11052]
Hi,
   I am using oauth authentication for otel collector, The token needs to be changed one hour once. I need to set that dynamically. I have used your setHeader with supplier and it was working as expected. I am trying to implement that using @Bean annotation. but springboot auto configuration injects the bean before the bean i have created. Anyone please help on this or is there anything i have missed? 
   
   It was working fine with the version 2.1.0-alpha

**Sample code for reference.**
**build.gradle**

`dependencyManagement {
    imports {
        mavenBom("io.opentelemetry:opentelemetry-bom:1.36.0")
        mavenBom("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:2.2.0-alpha")
    }
}

implementation("io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter")`

**Bean File**

`@AutoConfiguration
@ConditionalOnClass({OpenTelemetry.class})
@AutoConfigureOrder(Ordered.HIGHEST_PRECEDENCE)
public class RefreshToken { 

   @Bean
    public OtlpHttpSpanExporter otlpHttpSpanExporter() {
            Supplier<Map<String, String>> mapSupplier = () -> {
                Map<String, String> map = new HashMap<>();
                try {
                    map.put("Authorization", "Bearer " + refreshToken());
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                return map;
            };
            return OtlpHttpSpanExporter.builder().setHeaders(mapSupplier)
                    .setEndpoint("url").build();
        }
}`

**Comment by jack-berg** [comment]
Transferred to `opentelemetry-java-instrumentation` because this is related to the spring boot starter.

**Comment by jack-berg** [comment]
cc @jeanbisutti, @zeitlinger

**Comment by zeitlinger** [comment]
This breaking change is a consequence of https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10453 - I didn't call this out as a breaking change, because I simply couldn't image a use case that would break :disappointed: 

Anyways, there's a way to get your setup running:

- You have to create a new exporter with a different name, e.g. "otlp-dynamic-header"
- You have to use "otlp-dynamic-header" instead of the default "otlp"
- You have to register a bean that supplies "otlp-dynamic-header" - similar to this [integration test](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/beddb114142e262ed7d48ac3b68412fb3b865c0d/smoke-tests-otel-starter/src/test/java/io/opentelemetry/smoketest/OtelSpringStarterSmokeTest.java#L88-L131)

**Comment by zeitlinger** [comment]
I'm keeping this issue open to document this use case.

**Comment by zeitlinger** [comment]
Note: it's also possible to use "otlp" as the key - it will replace the already configured otlp exporter

**Comment by DineshkumarVG** [comment]
@zeitlinger , Thanks for your input. Correct me if my understanding is wrong. GlobalOpenTelemetry will not set the configuration for second time. How can i make it happen?
Could you please provide the any sample code for reference to use otlp as the key?

**Comment by zeitlinger** [comment]
I've created a draft PR that demonstrates both: https://github.com/open-telemetry/opentelemetry-java-examples/pull/378

Disclaimer: I haven't tested it manually.

**Comment by DineshkumarVG** [comment]
I will try it from my end the same you have shared as example code... @zeitlinger  Thank you..

**Comment by DineshkumarVG** [comment]
Thank you @zeitlinger ,
I verified from my end and it was working fine. I didn't set any GlobalOpenTelemetry object. I simply used like the shared code in my Configuration class.

```
@Bean
ConfigurableSpanExporterProvider otlpSpanExporterProvider() {
        return new OtlpSpanExporterProvider();
}
```

```
private static class OtlpSpanExporterProvider
            implements ConfigurableSpanExporterProvider {

        @Override
        public String getName() {
            return "otlp";
        }

        @Override
        public SpanExporter createExporter(ConfigProperties config) {
            OtlpHttpSpanExporterBuilder builder = OtlpHttpSpanExporter.builder();
            OtlpConfigUtil.configureOtlpExporterBuilder(
                    DATA_TYPE_TRACES,
                    config,
                    builder::setEndpoint,
                    builder::addHeader,
                    builder::setCompression,
                    builder::setTimeout,
                    builder::setTrustedCertificates,
                    builder::setClientTls,
                    builder::setRetryPolicy);

            Supplier<Map<String, String>> mapSupplier = () -> {
                Map<String, String> map = new HashMap<>();
                try {
                    map.put("AUTHORIZATION", "Bearer " + refreshToken());
                } catch (Exception e) {
                    throw new RuntimeException(e);
                }
                return map;
            };
            return builder.setHeaders(mapSupplier).build();
        }
		
		private String refreshToken(){
		return "token"
		}
    }
```
I removed  AutoConfigureListener implementation but it was working fine . Is there any impact by removing  AutoConfigureListener? 

As per my understanding, we are just injecting the bean with dynamic header.

Could you please explain me more on this and how it work?

Is this changes will be the standard one in future also?

**Comment by zeitlinger** [comment]
> Thank you @zeitlinger , I verified from my end and it was working fine. I didn't set any GlobalOpenTelemetry object. I simply used like the shared code in my Configuration class.

great :tada: 

> I removed AutoConfigureListener implementation but it was working fine . Is there any impact by removing AutoConfigureListener?

it creates metrics about the span export (i.e. if there were errors)

> As per my understanding, we are just injecting the bean with dynamic header.

correct

> Could you please explain me more on this and how it work?
> Is this changes will be the standard one in future also?

I can't follow - can you make the questions more concrete or add an example?

**Comment by DineshkumarVG** [comment]
Please refer the code i just shared in the comment above, i just modified now and it was working as expected for my use case.

I need some clarification on this: 

-     I used your code and need to know how its working? In high level i understood that we are just injecting a bean but it would be more helpful if there is any explanation on this for more understanding.
-     GlobalOpenTelemetry should not be set twice, but in that bean we are trying to set that. Is it okay to use like this?
-     Can i use the shared solution as a standard one?

**Comment by zeitlinger** [comment]
> I used your code and need to know how its working? In high level i understood that we are just injecting a bean but it would be more helpful if there is any explanation on this for more understanding.

Yes, you're injecting an exporter.

The exporter is loaded here: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/SpanExporterConfiguration.java#L82-L86

There's an additional translation of spring beans to "SPI": https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java#L140-L146

> GlobalOpenTelemetry should not be set twice, but in that bean we are trying to set that. Is it okay to use like this?

You should to not to use GlobalOpenTelemetry at all (for that reason, I'll also remove that hint from the PR).

- the global causes problems in some cases that are hard to detect
- in spring, there's no reason to use a global. Just inject `@Autowired OpenTelemetry`

> Can i use the shared solution as a standard one?

yes

**Comment by DineshkumarVG** [comment]
Thank you for your explanation @zeitlinger , As you recommened i just removed GlobalOpenTelemetry bean from my code.
Removed Code :
```
@Bean
 OpenTelemetryInjector registerGlobalOpenTelemetry() {
     return GlobalOpenTelemetry::set;
 }
```

As a result i can export the spans but at the same time i could able to see this info log in my application.

```
Apr 10, 2024 4:07:21 PM io.opentelemetry.api.GlobalOpenTelemetry maybeAutoConfigureAndSetGlobal
INFO: AutoConfiguredOpenTelemetrySdk found on classpath but automatic configuration is disabled. To enable, run your JVM with -Dotel.java.global-autoconfigure.enabled=true
```

**Comment by zeitlinger** [comment]
Ah, that means someone is trying to access the global.

Can you set a breakpoint and copy the stack trace of the caller? https://github.com/open-telemetry/opentelemetry-java/blob/cb44b2b18c474f80478184ff1665bc3fa5d2ced3/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L236

**Comment by DineshkumarVG** [comment]
I dont see any stack trace there. globalOpenTelemetry is null while calling get() method, that's why i received this info log.
[](https://github.com/open-telemetry/opentelemetry-java/blob/cb44b2b18c474f80478184ff1665bc3fa5d2ced3/api/all/src/main/java/io/opentelemetry/api/GlobalOpenTelemetry.java#L73)

**Comment by DineshkumarVG** [comment]
It was called by this method

```
  public static MeterProvider getMeterProvider() {
        return get().getMeterProvider();
    }
```
And this method is called by this line
https://github.com/open-telemetry/opentelemetry-java/blob/cb44b2b18c474f80478184ff1665bc3fa5d2ced3/exporters/common/src/main/java/io/opentelemetry/exporter/internal/ExporterMetrics.java#L89

**Comment by zeitlinger** [comment]
> My springboot project was launched smoothly, once i try to export the spans by hitting api it was occurred. The `get()` method was called by this method
> 
> ```
>   public static MeterProvider getMeterProvider() {
>         return get().getMeterProvider();
>     }
> ```
> 
> And this method is called by this line https://github.com/open-telemetry/opentelemetry-java/blob/cb44b2b18c474f80478184ff1665bc3fa5d2ced3/exporters/common/src/main/java/io/opentelemetry/exporter/internal/ExporterMetrics.java#L89

Interesting! 
I belive this is a result of removing "I removed AutoConfigureListener implementation but it was working fine . Is there any impact by removing AutoConfigureListener?"

**Comment by DineshkumarVG** [comment]
I tried by adding AutoConfigureListener again in my code, the same info log persist.

The current code..

```
@Bean
ConfigurableSpanExporterProvider otlpSpanExporterProvider() {
        return new OtlpSpanExporterProvider();
}

private static class OtlpSpanExporterProvider
            implements ConfigurableSpanExporterProvider, AutoConfigureListener {

        private final AtomicReference<MeterProvider> meterProviderRef =
                new AtomicReference<>(MeterProvider.noop());


        @Override
        public String getName() {
            return "otlp";
        }

        @Override
        public SpanExporter createExporter(ConfigProperties config) {
            OtlpHttpSpanExporterBuilder builder = OtlpHttpSpanExporter.builder();
            Supplier<Map<String, String>> mapSupplier = () -> {
                Map<String, String> map = new HashMap<>();
                try {
                    map.put("Authorization", "Bearer " + refreshToken());
                } catch (ObservabilityException e) {
                    throw new RuntimeException(e);
                }
                return map;
            };
            return builder.setHeaders(mapSupplier).build();
        }

        @Override
        public void afterAutoConfigure(OpenTelemetrySdk openTelemetrySdk) {
            meterProviderRef.set(openTelemetrySdk.getMeterProvider());
        }
		
		private String refreshToken(){
		return "token";
		}
    }
```

**Comment by zeitlinger** [comment]
Can you check the value of [seenAttrs](https://github.com/open-telemetry/opentelemetry-java/blob/551e764df8b6ea08d4b759fccb71e5b228fd3e7d/exporters/common/src/main/java/io/opentelemetry/exporter/internal/ExporterMetrics.java#L51)?

**Comment by DineshkumarVG** [comment]
Hey @zeitlinger I didn't set `builder.setMeterProvider(meterProviderRef::get)` in my application. now the log is gone. 
Thanks for your support ....

**Comment by DineshkumarVG** [comment]
Hi @zeitlinger ,
     Previously we are using otel java agent for instrumentation, currently we changed that to opentelemetry-springboot-starter dependency to achieve dynamic authentication. The dynamic authetication achieved but noticing that while using agent the span count is 8 for a single api , but using springboot dependency the span count is 1 (Controller level) for the same api. Is there anything i am missing or this is how the dependency behaves.
On other hand We are using microservice with 2 springboot application,  Both application having otel springboot dependency with different app name, I am hitting a api and it lands on app1 and communicates with app2. While seeing the result we are seeing 2 different traces. app1 having trace1 and app2 having trace2 (i.e) nested traces is not happening. Anyone please share the thoughts on this.

**My code :**
```
dependencyManagement {
    imports {
        mavenBom("io.opentelemetry:opentelemetry-bom:1.37.0")
        mavenBom("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:2.2.0-alpha")
    }
} 

implementation("io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter")
```

**The Env variables:** 
```
OTEL_EXPERIMENTAL_EXPORTER_OTLP_RETRY_ENABLED=true;
OTEL_EXPORTER_OTLP_ENDPOINT=url;
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf;
OTEL_LOGS_EXPORTER=none;
OTEL_METRICS_EXPORTER=otlp;
OTEL_PROPAGATORS=tracecontext;
OTEL_RESOURCE_ATTRIBUTE=environment=dev;
OTEL_SERVICE_NAME=app1;
OTEL_TRACES_EXPORTER=otlp;
OTEL_TRACES_SAMPLER=traceidratio;
OTEL_TRACES_SAMPLER_ARG=1

```
Note: The same configuration working for java agent.

**Comment by zeitlinger** [comment]
> currently we changed that to opentelemetry-springboot-starter dependency to achieve dynamic authentication.

You could also use an [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/README.md) BTW 

> The dynamic authetication achieved but noticing that while using agent the span count is 8 for a single api , but using springboot dependency the span count is 1 (Controller level) for the same api. Is there anything i am missing or this is how the dependency behaves?

I guess it's because the starter doesn't support the same number of libraries out of the box - or because the spring starter is a bit more picky about how you use beans like RestTemplate (see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11054)

If you provide details about the spans, I can double check.

**Comment by DineshkumarVG** [comment]
**Current span:**
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/166195913/1ea69083-9349-4190-8432-d9ffc766c5c4)

**Previous span:**
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/166195913/46aa0001-dd4c-4112-8738-0ace244fa3e2)

**Comment by zeitlinger** [comment]
please go to the span details and look for the "library name"

**Comment by DineshkumarVG** [comment]
Please refer here
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/166195913/d0117cd3-156f-419f-b3c4-561afd865f28)

**Comment by DineshkumarVG** [comment]
Can you please explain me how to do that? I don't have an idea on this..

**Comment by zeitlinger** [comment]
I don't know how to do that in your UI, but you can always turn on [console logging](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#logging-exporter) - which was called "logging" in older releases.

**Comment by DineshkumarVG** [comment]
I am using otel to export metrics and traces and we set logs as none. 
**The library name of previous span is** 
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/166195913/a25aafe1-cde2-4a80-8cfc-0781eb794188)
**The library name of current implementation (after migrating to springboot starter)**
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/166195913/3b95b442-71c6-4188-88f8-2a2836c3d993)

**Comment by DineshkumarVG** [comment]
@zeitlinger  For your information, 
While exploring otel java agent  i could see these package inside opentelemetry/instrumentation/api folder 
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/166195913/f7217c0e-5fb3-4399-9c1d-5fb0550a223a)
While exploring opentelemetry-instrumentation-api provided by springboot starter I could see the shared packages
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/166195913/18618cb1-0dcd-46ed-883b-581b3c74b2d7)

Do you think is this because of this changes?

**Comment by zeitlinger** [comment]
@DineshkumarVG let's do a call to investigate the issue.

**Comment by DineshkumarVG** [comment]
Hi @zeitlinger , Sounds great.. Shall we connect through slack? Or any other medium are you comfortable with?

**Comment by zeitlinger** [comment]
CNCF slack sounds good :smile:

**Comment by zeitlinger** [comment]
sure - I'm still pretty free tomorrow

**Comment by zeitlinger** [comment]
Here are the expected spans (from the call)

1: the server span.

The server span has a different library name - but the functionality is equivalent.

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/2832627/be6e46ed-eab4-483b-98f4-528b062fc43e)

2: Different spans related to database queries. The spring starter needs to be set up to support DB queries: https://opentelemetry.io/docs/languages/java/automatic/spring-boot/#jdbc-instrumentation

2.1: spring data adds more details about the query - and is not supported in the starter

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/2832627/b87af086-83b0-4230-b51b-6546f4a0d342)

2.2: You should see the DB query once you follow the instructions (2).

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/2832627/e18a054d-97f0-477e-8b08-8b73641a6a9f)

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/2832627/0b12db76-7be2-4709-b76d-5d345f52c504)

2.3: Hibernate adds more details about the query - and is not supported in the starter

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/2832627/852ec0e1-cca2-4448-83da-5ca8410ef006)

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/2832627/69f27f5f-7de1-438c-93c3-3c3914b09b6e)

3: HTTP URL connection

HTTP URL connection is not supported in the starter - and I have no idea how to make it work outside a java agent.

Final thoughts:

- For any missing feature, feel free to create a ticket. The team might not have time, but can give you feedback if/how you can contribute missing features.
- The spring starter seems to be less verbose regarding the DB queries. In recent versions of the java agent, the default verbosity has been reduced to create less spans based on user feedback that it was too much.

**Comment by DineshkumarVG** [comment]
Sounds Great @zeitlinger , Thank you for dedicating your time and attention to this matter. Your engagement is greatly appreciated. 👏  . Will proceed next steps on this.

**Comment by zeitlinger** [comment]
OK, closing then - please re-open if needed.

**Comment by zeitlinger** [comment]
This is a very old ticket - please open a new issue and describe the problem. 

Thanks
