### ISSUE TITLE
SpringScheduling use same traceId

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-java-instrumentation#11062]
### Describe the bug
Same traceId
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/11512994/1c5b22c1-e9a3-4970-83b5-979c277ea73b)
I don't know it is because Okhttp or SpringScheduling ?

Okhttp stack
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/11512994/2761bd76-5a05-41f1-a684-d8f1e7bf847b)

### Steps to reproduce

I can't

### Expected behavior

-

### Actual behavior

-

### Javaagent or library instrumentation version

1.28.x

### Environment

**JDK**:
**OS**:

**Comment by steverao** [comment]
From your description above, it seems normal. You can learn more about trace in https://opentelemetry.io/docs/specs/otel/overview/#traces

**Comment by chenjazz** [comment]
> From your description above, it seems normal. You can learn more about trace in https://opentelemetry.io/docs/specs/otel/overview/#traces

It is not normal. Every schduling should use a new traceId.But not same traceId

**Comment by chenjazz** [comment]
> From your description above, it seems normal. You can learn more about trace in https://opentelemetry.io/docs/specs/otel/overview/#traces

I think it is okhttp instrumentation bug

**Comment by steverao** [comment]
> > From your description above, it seems normal. You can learn more about trace in https://opentelemetry.io/docs/specs/otel/overview/#traces
> 
> I think it is okhttp instrumentation bug

Sorry, at first, I misunderstood your problem. Can you provide a minimal demo to help us debug the problem?

**Comment by laurit** [comment]
Looking at the provided info I can't really tell whether something is wrong or what exactly has the same trace id. Also I can not see how you came to the conclusion that is a bug in the okhttp instrumentation. Please explain.

**Comment by chenjazz** [comment]
@trask @laurit I agree that it be a context leak,but I can not find which instrumentation's bug.So I add the code to `SpringSchedulingRunnableWrapper` temporarily :
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/11512994/7e907ce7-2bb4-44af-960f-cf535df2e340)
I will continue to find it.

**Comment by trask** [comment]
Try with `-Dotel.javaagent.experimental.thread-propagation-debugger.enabled=true`, that may help provide clues about where the leak is happening (these issue mentioning [thread-propagation-debugger](https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-java-instrumentation+thread-propagation-debugger&type=issues) could provide helpful reading)

**Comment by laurit** [comment]
@chenjazz if the parent span is set for the spring scheduling span then could you let us know what the parent span is. From the screenshot you provided we can't see the parent span.

**Comment by lghinet** [comment]
hello,
any news on this one?

**Comment by lghinet** [comment]
just create a simple spring boot app, with a @Schedule job for every minute, and you'll have a single trace with a root spans for each tick, but all of them in the same trace, and it's getting too large at some point 
thanks

**Comment by laurit** [comment]
@lghinet if you believe you have found a bug please create a new issue and include a minimal sample application that reproduces the issue.
