### ISSUE TITLE
The metric values for the connection pool in the alibaba-druid instrumentation may be incorrect.

### ISSUE THREAD

**Issue by huange7** [open-telemetry/opentelemetry-java-instrumentation#11072]
### Describe the bug

When I checked the druid connection pool stats, I noticed that the number of idle connections is sometimes negative, which doesn't make sense.
<img width="1086" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/48885776/c76b6ed6-f3e5-42da-9f0f-225d25bb5bc8">

### Steps to reproduce

When using Druid as a database connection pool and generating a large number of requests, the issue can be reproduced.

### Expected behavior

The number of idle connections should be greater than or equal to zero.

### Actual behavior

The number of idle connections is sometimes negative

### Javaagent or library instrumentation version

v2.2.0

### Environment

**JDK**: 17
**OS**: macos
**Druid**: 1.2.14

### Additional context

In the java agent, the method DruidDataSource.getPoolingCount() - getActiveCount() is intended to calculate the number of idle connections. However, since poolingCount in DruidDataSource already signifies the count of idle connections, I suspect there's a mistake in the code's logic.
Therefore, it would be correct to directly use DruidDataSource.getPoolingCount as the number of idle connections.

code: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/alibaba-druid-1.0/library/src/main/java/io/opentelemetry/instrumentation/alibabadruid/v1_0/ConnectionPoolMetrics.java#L44

If that's correct, can you leave it to me to resolve this issue?

**Comment by steverao** [comment]
cc @AlchemyDing

**Comment by AlchemyDing** [comment]
In the Druid document, the description of `PoolingCount` is `The current usefull connection count`
[https://github.com/alibaba/druid/blob/master/core/src/main/resources/support/http/resources/js/lang.js#L106](https://github.com/alibaba/druid/blob/master/core/src/main/resources/support/http/resources/js/lang.js#L106)
At the same time, I also looked at the `idle` for `druid` in the `skywalking-javaagent,` and it seems to be the same
[https://github.com/apache/skywalking-java/blob/main/apm-sniffer/apm-sdk-plugin/druid-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/druid/v1/PoolingAddDruidDataSourceInterceptor.java#L64](https://github.com/apache/skywalking-java/blob/main/apm-sniffer/apm-sdk-plugin/druid-1.x-plugin/src/main/java/org/apache/skywalking/apm/plugin/druid/v1/PoolingAddDruidDataSourceInterceptor.java#L64)

**Comment by AlchemyDing** [comment]
So I'm confused about the meaning of PoolingCount

**Comment by huange7** [comment]
When get a connection from the connection pool (https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L1674), the pool will decrement poolingCount by 1 (https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L2403C9-L2403C30) and increment activeCount by 1 (https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L1824).

Therefore, I believe that once a connection is being used, it is no longer considered a useful connection within the connection pool.

**Comment by wu-sheng** [comment]
I am not clear about the conclusion here. What do those numbers of connections mean?

We should align the tag meaning with other plugin, as SkyWalking treats tag meaning seriously, and run statistics on them.

As you described, then PoolingCount is not the actual count of pooling.

**Comment by AlchemyDing** [comment]
> When get a connection from the connection pool (https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L1674), the pool will decrement poolingCount by 1 (https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L2403C9-L2403C30) and increment activeCount by 1 (https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L1824).
> 
> Therefore, I believe that once a connection is being used, it is no longer considered a useful connection within the connection pool.

I agree. In Druid, the criteria for determining if the connection pool is full is based on the condition 'poolingCount + activeCount >= maxActive'.
[https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L4040](https://github.com/alibaba/druid/blob/master/core/src/main/java/com/alibaba/druid/pool/DruidDataSource.java#L4040)

**Comment by huange7** [comment]
> I am not clear about the conclusion here. What do those numbers of connections mean?
> 
> We should align the tag meaning with other plugin, as SkyWalking treats tag meaning seriously, and run statistics on them.
> 
> As you described, then PoolingCount is not the actual count of pooling.

Here's my understanding: when other programs call `getConnection`, at that point, the connection is taken out of the connection pool. Therefore, it temporarily ceases to be a part of the pool, which is why the poolingCount decreases by one. It's only when the connection is returned to the pool with recycle after use that it becomes part of the pool again.

**Comment by laurit** [comment]
Resoled with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11079
