### ISSUE TITLE
Printing version throws exception

### ISSUE THREAD

**Issue by erikcostlow** [open-telemetry/opentelemetry-java-instrumentation#1108]
Running with the latest agent throws an exception when it prints its version number; then the agent says it's unknown.

VersionLogger looks for a file named "opentelemetry-javaagent.version" but gradle produces one based on the project name, called javaagent.version.

Which is the best fix? Looking for the file that's created or changing the one that gets generated?

**Comment by trask** [comment]
Hi @erikcostlow! Let's use `opentelemetry-javaagent.version`. The file name probably got broken when we removed the (redundant) `opentelemetry-` from the module name.

**Comment by iNikem** [comment]
Just a heads up: I will submit a PR today which changes how version is printed and does not rely on that file at all. That will solve this issue and #750

**Comment by erikcostlow** [comment]
Thanks, sorry I missed that ticket. Closing this.
