### ISSUE TITLE
Add support for HTTP metric events

### ISSUE THREAD

**Issue by gfuller1** [open-telemetry/opentelemetry-java-instrumentation#1109]
Implementation for this spec https://github.com/open-telemetry/opentelemetry-specification/pull/739. The instrumentation should be reporting http metrics along with http span events.

**Comment by gfuller1** [comment]
I think the best way to create http metric events within open telemetry is to generate them from span events. This will allow the data to be consistent between the two events (labels/attributes and duration values) and make the work to implement this a lot easier than writing http metric instrumentation for every framework.

**Comment by trask** [comment]
Hey @gfuller1! Check out `HttpServerTracer` and `HttpClientTracer`. I think those would be good places to implement metrics in a way that applies every framework.

**Comment by lichenglin** [comment]
I think it's not only about http. Sql or other instrumentation point also need to create metric duration the span code;

**Comment by lichenglin** [comment]
Maybe instrumentation can add some "event and listener" to solve such problem.

**Comment by mateuszrzeszutek** [comment]
It looks like this is already implemented as [HttpClientMetrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpClientMetrics.java) and [HttpServerMetrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpServerMetrics.java) in the Instrumenter API.
