### ISSUE TITLE
Use consistent span names with Spring AMQP AnonymousQueues

### ISSUE THREAD

**Issue by swar8080** [open-telemetry/opentelemetry-java-instrumentation#11132]
### Is your feature request related to a problem? Please describe.

Spans for applications using spring's AMQP `AnonymousQueue` have randomly generated names like `spring.gen-t5CcsV0tTdOBu0wKk7_8_A process`. This can make searching inconvenient and generate high cardinality span metrics. These spans are coming from the rabbitmq-2.7 auto-instrumentation. 

Here's the spring code for reference https://github.com/search?q=repo%3Aspring-projects%2Fspring-amqp%20spring.gen&type=code

### Describe the solution you'd like

Use a constant name for these spans, like `spring.gen-<generated>`, maybe similar to how it's done for auto-generated queue names starting with `amq.gen` in the [existing auto-instrumentation code](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f20cb41bf7e8b0e8e539aeac6f75673137974b05/instrumentation/rabbitmq-2.7/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/rabbitmq/DeliveryRequest.java#L40).

### Describe alternatives you've considered

Having apps name their queues or fixing the span names in the OTEL collector

### Additional context

I can try implementing this

**Comment by laurit** [comment]
@swar8080 feel free to submit a PR, don't forget to add a test
