### ISSUE TITLE
Propagate span-context for Kafka Clients by injecting and extracting in message headers

### ISSUE THREAD

**Issue by mnottheone** [open-telemetry/opentelemetry-java-instrumentation#1113]
Right now, auto instrumentation records spans for Kafka clients, but context propagation is missing. Let me know if I am wrong and I tried running it myself and span-ids were missing in message headers. <br>Context propagation for Kafka clients was supported for opentracing using [java-kafka-client](https://github.com/opentracing-contrib/java-kafka-client) . This is really helpful for applications involving Kafka. 

Changes involved will be implementing inject and extract in TextMapPropagator. I can see explicitly only propagator's setter and getter are implemented in [InjectAdapter](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/kafka-clients-0.11/src/main/java/io/opentelemetry/instrumentation/auto/kafkaclients/TextMapInjectAdapter.java) and extractAdapter. Any specific reasons? Didn't find any blocker in OpenTelemetery API.

Can we add context propagation for kafka clients ?

I don't know the best way to get it done. But happy to learn and make a pull request.

**Comment by iNikem** [comment]
There is code in place to propagate trace context via kafka headers: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/7969a83dde7c567b0ed07e7ea2c314673eb49e23/instrumentation/kafka-clients-0.11/src/main/java/io/opentelemetry/instrumentation/auto/kafkaclients/KafkaProducerInstrumentation.java#L114 If that does not work, then something is broken and we should investigate it. Can you confirm it does not work?

**Comment by mnottheone** [comment]
I tried in debug mode and can see traceparent ( traceId-spanId.. ) in headers. But issue is spans from producers and consumers are not getting stitched in Jaeger. There are separate Traces/spans for producer and consumer messages. It lead me to assumption that context in not propagated.

**Comment by trask** [comment]
Hi @mnottheone! Kafka propagation works for me, can you provide a standalone repro so we can try it out and see what might be different for your case?

**Comment by mnottheone** [comment]
Hi! I tried replicating in standalone, it was working. I simply removed some extra code for JaegerTracer (Jaeger and OpenTracing libs) and  it also started working. Thanks a lot for prompt responses. Closing this issue.

**Comment by Samarth888** [comment]
Hi, I am experiencing a similar problem where I am getting separate traces for producer and consumer instead of a single flow. I am using auto instrumentation and using Zipkin backend. I have also checked through debug mode and ensured that the headers are present, so I am not able to analyze if this is a propagation issue or something else.

**Comment by carlos045** [comment]
I hav the sake issue @Samarth888
