### ISSUE TITLE
Instrumenting JDK classes

### ISSUE THREAD

**Issue by erikcostlow** [open-telemetry/opentelemetry-java-instrumentation#1115]
docs/contributing/writing-instrumentation.md describes a situation of instrumenting core JDK classes, using the example "URLConnection, because it can intercept even the JDK's classes. Such libraries will not have manual instrumentation but will have auto instrumentation."
For an initial experimentation, I used the following code to target java.io.File. The instrumentation is present because I have another AutoService targeting a known file and it's working. It's basically the same thing in an application-level class.
```java
@AutoService(Instrumenter.class)
public final class FileInstrumentation extends Instrumenter.Default {
  public FileInstrumentation() {
    super("file");
  }

  @Override
  public ElementMatcher<TypeDescription> typeMatcher() {
    // paraphrased from the ClassLoader example
    return NameMatchers.namedOneOf("java.io.File")
            .or(extendsClass(named("java.io.File")));
  }

  @Override
  public String[] helperClassNames() {
    return new String[] { Constants.class.getName() };
  }

  @Override
  public Map<? extends ElementMatcher<? super MethodDescription>, String> transformers() {
    return singletonMap(
            ElementMatchers.isConstructor().and(takesArgument(0, named("java.lang.String"))),
        FileInstrumentation.class.getName() + "$LoadClassAdvice");
  }

  public static class LoadClassAdvice {
    @Advice.OnMethodEnter
    public static void onEnter(@Advice.Argument(0) String name) {
      System.out.println("CALLING THE FILE");
      System.out.println("NAME IS " + name);
    }
  }
```

Following this, the File(String) constructor does not apply the class advice. It could be that the class requires retransformation, I've mis-targeted, or something else is wrong.

**Comment by trask** [comment]
Hey @erikcostlow! I suspect this is because of https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/matcher/GlobalIgnoresMatcher.java#L107-L124

**Comment by erikcostlow** [comment]
Yes. You're right on the mark there, thank you for the response.
For future readers, the line to add looks like this:
```java
if(name.equals("java.io.File")){
  return false;
}
```
