### ISSUE TITLE
spring doc updates for 2.4.0

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#11212]
- [ ] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11211
- [ ] https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11184
- [ ] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11263
- [ ] https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11258

**Comment by trask** [comment]
@zeitlinger good to close this now?

**Comment by zeitlinger** [comment]
no - the docs have not been written yet
