### ISSUE TITLE
Kafka batch consume trace broken

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#11218]
### Describe the bug

When i use kafka batch consume, the trace will broken

### Steps to reproduce

```java
@RestController
@Slf4j
public class SpringKafkaController {
    @Resource
    private KafkaTemplate<String, String> kafkaTemplate;

    @RequestMapping("/kafka/send")
    public String sendMessage() {
        kafkaTemplate.send("test-topic", "test");
        return "success";
    }

    @KafkaListener(topics = {"test-topic"})
    public void listen(List<ConsumerRecord<String, String>> records) {
        log.info("receive message");

        records.forEach(ConsumerRecord -> {
            log.info("topic: {}, partition: {}, offset: {}, key: {}, value: {}", ConsumerRecord.topic(), ConsumerRecord.partition(), ConsumerRecord.offset(), ConsumerRecord.key(), ConsumerRecord.value());
        });
    }
}
```

<img width="1199" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/10825900/8fb8a11e-b465-4194-a24f-4a71f9a21401">

consumer log trace will disappear when i set batch consumer "spring.kafka.listener.type=batch", ps: when the type is single, it's all ok

### Expected behavior

show trace normally

### Actual behavior

no trace info

### Javaagent or library instrumentation version

1.32.0

### Environment

**JDK**: 8
**OS**: macos

**Comment by laurit** [comment]
@xiangtianyu Please provide a minimal application that reproduces your issue.

**Comment by laurit** [comment]
I didn't try to run the sample app. My guess is that since you are using `spring-kafka:2.5.14.RELEASE` which is older than `2.7.0` that is the earliest supported version you get the spans from plain kafka client instrumentation. Spans for the spring kafka listener methods are created by spring-kafka instrumentation so not having a trace in `log.info("receive message");` isn't surprising. Kafka client instruments iterating over `ConsumerRecords`, here you are using `List<ConsumerRecord<String, String>>` so that not working is also expected.

**Comment by xiangtianyu** [comment]
> I didn't try to run the sample app. My guess is that since you are using `spring-kafka:2.5.14.RELEASE` which is older than `2.7.0` that is the earliest supported version you get the spans from plain kafka client instrumentation. Spans for the spring kafka listener methods are created by spring-kafka instrumentation so not having a trace in `log.info("receive message");` isn't surprising. Kafka client instruments iterating over `ConsumerRecords`, here you are using `List<ConsumerRecord<String, String>>` so that not working is also expected.

You are right, i tried to use 2.7.0, the trace is all ok. So it means that old version kafka will not support in the future? I must update my kafka version?

**Comment by laurit** [comment]
> So it means that old version kafka will not support in the future?

If a reasonable PR is provided older versions may be supported.

> I must update my kafka version?

either update spring kafka version or rework the instrumentation to support older versions

**Comment by xiangtianyu** [comment]
Thanks, i will consider it
