### ISSUE TITLE
Add configuration options to enable experimental jvm metrics after version 2.0.

### ISSUE THREAD

**Issue by zhangjiabin1010** [open-telemetry/opentelemetry-java-instrumentation#11231]
### Is your feature request related to a problem? Please describe.

I need indicators like this:
jvm.memory.init
jvm.system.cpu.utilization
jvm.buffer.memory.usage ...

### Describe the solution you'd like

-Dotel.jvm.experimental-metrics.enabled=true
or
-Dotel.metric.jvm.memory.init.enabled=true
-Dotel.metric.jvm.system.cpu.utilization.enabled=true

### Additional context

I didn't find how to configure this function
https://opentelemetry.io/docs/specs/semconv/runtime/jvm-metrics/

**Comment by laurit** [comment]
Experimental jvm metrics are enabled with `-Dotel.instrumentation.runtime-telemetry.emit-experimental-telemetry=true`. Implementation is located in https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-telemetry/runtime-telemetry-java8/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/java8/internal

**Comment by zhangjiabin1010** [comment]
> 实验性 jvm 指标通过`-Dotel.instrumentation.runtime-telemetry.emit-experimental-telemetry=true`.实现位于[https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-telemetry/runtime-telemetry-java8/library/src/main/java/io/opentelemetry/仪器/运行时度量/java8/内部](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-telemetry/runtime-telemetry-java8/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/java8/internal)

Already solved, thank you for your answer.
