### ISSUE TITLE
Disable Auto instrumentation by telemetry type

### ISSUE THREAD

**Issue by bcarter97** [open-telemetry/opentelemetry-java-instrumentation#11264]
### Is your feature request related to a problem? Please describe.

the library I am using does not carry trace information through threads, so auto instrumentation creates orphan spans which I would like to disable.

### Describe the solution you'd like

I would like to disable auto instrumentation for tracing, while keeping the metrics. This would ideally happen through configuration.

### Describe alternatives you've considered

specifically this is for gRPC and I have investigated using https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/grpc-1.6/library with success, however it requires a lot of boilerplate to achieve the same result as auto instrumentation.

### Additional context

Originally discussed [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11057#issuecomment-2067752910), with the hope that `OTEL_INSTRUMENTATION_<FRAMEWORK>_ENABLED: 'false'` could be extended to something like `OTEL_INSTRUMENTATION_<FRAMEWORK>_<INSTRUMENTATION_TYPE>_ENABLED: 'false'`

**Comment by laurit** [comment]
@bcarter97 see https://github.com/open-telemetry/opentelemetry-specification/pull/3877 and https://github.com/open-telemetry/opentelemetry-java/pull/6375 for the java implementation. You should be able to configure this via an [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension) when using the agent in the next version, this is new so not present in an existing release.

**Comment by trask** [comment]
hi @bcarter97! eventually this will be easily configurable via system properties / yaml configuration file, but for now if you want to implement it you'll need wait for this week's release and then dive in and write your own java agent extension using these new experimental APIs

**Comment by bcarter97** [comment]
Thanks!
