### ISSUE TITLE
Decide on what modules contain public APIs

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1129]
A couple of options to start discussion:

**Option 1:**
Merge `auto-api` module (back) into `javaagent-bootstrap`

This would leave us with public API in 2 modules:
* `javaagent-tooling`
* `javaagent-bootstrap`

**Option 2:**
Rename `auto-api` to `auto-runtime-api`, and split out `auto-matcher-api` from `javaagent-tooling`, and introduce `javaagent-spi`(?) for `TracerCustomizer`, `ExporterConfig`, `SpanExporterFactory`, etc

This would remove all public API from `javaagent-tooling` and `javaagent-bootstrap`, and leave us with public API in 3 modules:
* `auto-runtime-api`
* `auto-matcher-api`
* `javaagent-spi`(?)

The `auto-*-api` modules would be public API for creating auto instrumentation.

The `javaagent-spi`(?) module would be for creating a custom Javaagent distribution.

**Comment by anuraaga** [comment]
Yeah option 2 feel natural to me. Right now we indeed have a tricky split between classes in the tooling / bootstrap modules that isn't intuitive.

**Comment by iNikem** [comment]
I am still somewhat confused about what classes should go where, but `auto-runtime-api` seems like a strange name to me :)

**Comment by anuraaga** [comment]
Heh yeah need a reminder of what auto runtime API is. SPI I think used by initializer or exporter, matcher used by instrumentation. Is the rest agent initialization code?

**Comment by anuraaga** [comment]
Want to knock this out soon to get closer to our final artifacts sooner than later. I looked again and am wondering

- Do we need to split auto-matcher-api / auto-runtime-api? What if we move `matcher` package and `Instrumenter` interface to `auto-api`. IIUC, it should be possible to have a single artifact that auto-instrumentation depends on instead of two. We would probably also move some of `auto-api` back into bootstrap, `AgentClassLoader`, `InternalJarURLHandler` don't seem like they would ever be needed in auto-instrumentation modules. 

- We do need to move our SPI classes somewhere - there are too many public classes in `javaagent-tooling` for us to let users depend on it as a standard practice (e.g., `Constants.java`). I think these could also just be stuffed into `auto-api` - it's all the public API exposed by our agent, which includes SPI.

Thoughts? Will start with PRs with any vote in any direction :)

**Comment by anuraaga** [comment]
Realized `auto-api` needs to be in bootstrap classloader right now since it's used by instrumentation but isn't injected into user classloader. I wonder if instead of putting it in bootstrap, it's better to only inject what's used into user classloader.

**Comment by trask** [comment]
> Realized `auto-api` needs to be in bootstrap classloader right now since it's used by instrumentation but isn't injected into user classloader. I wonder if instead of putting it in bootstrap, it's better to only inject what's used into user classloader.

`auto-api` is needed in the bootstrap classloader because we instrument some classes in the bootstrap class loader (also small startup performance gain if we don't need to inject classes into class loaders)

> We do need to move our SPI classes somewhere

Yeah, I think that would be nice too, what do you think of option 2 above?

**Comment by iNikem** [comment]
> * Do we need to split auto-matcher-api / auto-runtime-api?

I second this question. Why exactly do we need 2 artifacts/packages for auto instrumentation api?

**Comment by trask** [comment]
> I second this question. Why exactly do we need 2 artifacts/packages for auto instrumentation api?

One lives in bootstrap class loader (e.g. so that all instrumentation can access it), one lives in agent class loader (so that it can access bytebuddy, etc).

**Comment by iNikem** [comment]
But for whom is this important? I mean, let's assume I am writing my own auto instrumentation or even repackaging the agent. I need to compile my classes and for that I need both auto-api and bytebuddy related classes. But when I package my final distribution, what I essentially do is inserting my new code into existing javaagent-all.jar from Otel. At what time the differences in runtime "packaging" of different classes from Otel javaagent are important to me?

**Comment by trask** [comment]
Oh, I see. Yes, from a consumer perspective a single `auto-api` makes sense. We'll need to split that single `auto-api` artifact into two parts when building the javaagent jar, but that seems manageable.

**Comment by iNikem** [comment]
Continuing this train of thoughts and thinking about consumers... They probably have different needs during compile and runtime. Do we need to provide them with artifacts which reflect runtime requirements? Like that one about different classloaders. Developers, consumers of our artifacts, don't care about that. Maybe something similar to #482 will be better for them?

**Comment by trask** [comment]
Closing in favor of #1186
