### ISSUE TITLE
Investigate instrumentation / exporters duplicate dependencies

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1135]
We have dependencies included into the final agent jar twice if they're used by both instrumentation and exporters. Usually duplicate dependencies should only result in a larger jar but otherwise be harmless but we've seen issues that may indicate some dependency version conflict happening - it's not an obvious conflict though but probably needs some more investigation.

See #1119

**Comment by trask** [comment]
@anuraaga we've done a lot of clean up of what gets pulled into the agent jar recently, should we close this, or do you have something additional in mind?
