### ISSUE TITLE
spring boot test versions

### ISSUE THREAD

**Issue by zeitlinger** [open-telemetry/opentelemetry-java-instrumentation#11357]
### Is your feature request related to a problem? Please describe.

question from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11262#issuecomment-2111038995

> we have the capability to test with earliest supported boot version, by using library dependencies, but looks like we aren't taking advantage of that capability and are just pinning the spring boot library dependencies to the latest 2.x and 3.x versions
> it's a good question though, as typically we test all the instrumentation against an "earliest supported version" (and document that as the earliest supported version).
> we should decide if/how we want to test/support earlier Spring Boot minor versions

**Comment by zeitlinger** [comment]
@trask the tests are mainly in the smoke tests, where the version comes from the plugin id.

would this still work?

**Comment by trask** [comment]
maybe could run the smoke tests twice, e.g. once with earliest 2.x version and one with latest 2.x version?

**Comment by zeitlinger** [comment]
there's no image build step - we'd just need to update the version 

@laurit do you have an idea how to do that?

**Comment by trask** [comment]
check out https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/facdc1826dee05bf534a07e3c281fcad846bea83/instrumentation/reactor/reactor-kafka-1.0/javaagent/build.gradle.kts#L43-L62 (there are other similar examples in this repo also)

**Comment by zeitlinger** [comment]
that doesn't work - the version here has to be exact: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/ed083ef5356327afb51d502facaaa9f583aa0e67/smoke-tests-otel-starter/spring-boot-reactive-3/build.gradle.kts#L3

**Comment by 4orty** [comment]
@zeitlinger 
So to summarize, is it available from spring boot version 2.4.0?

**Comment by zeitlinger** [comment]
> [@zeitlinger](https://github.com/zeitlinger) So to summarize, is it available from spring boot version 2.4.0?

here's the answer: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11474/files#diff-5625e3601fa0ad3a6a2824239e5a2fde71c149597d31394f9224a08c24be7b9dR42-R43

We didn't test specifically what works for 2.4
