### ISSUE TITLE
agent version 2.3， The span attribute of the database span is missing db.operation

### ISSUE THREAD

**Issue by zhangjiabin1010** [open-telemetry/opentelemetry-java-instrumentation#11369]
### Describe the bug

After upgrading the agent to version 2.3, 
there is no db.operation in the span attributes of databases such as oracle and postgres.

### Steps to reproduce

The following is the span data collected:  
  
            {
              "traceId": "232ca492da8af16623bebfe65e235407",
              "spanId": "a88ae62a9678eb76",
              "parentSpanId": "d324ad6c3cbf9c61",
              "name": "SELECT link_monitor.usertest",
              "kind": 3,
              "startTimeUnixNano": "1715825338514041100",
              "endTimeUnixNano": "1715825338563625300",
              "attributes": [
                {
                  "key": "db.statement",
                  "value": {
                    "stringValue": "select user0_.id as id1_0_0_, user0_.age as age2_0_0_, user0_.name as name3_0_0_ from link_monitor.usertest user0_ where user0_.id=?"
                  }
                },
                {
                  "key": "db.system",
                  "value": {
                    "stringValue": "postgresql"
                  }
                },
                {
                  "key": "server.port",
                  "value": {
                    "intValue": "31003"
                  }
                },
                {
                  "key": "db.connection_string",
                  "value": {
                    "stringValue": "postgresql://122.237.99.140:31003"
                  }
                },
                {
                  "key": "server.address",
                  "value": {
                    "stringValue": "122.237.99.140"
                  }
                },
                {
                  "key": "thread.id",
                  "value": {
                    "intValue": "137"
                  }
                },
                {
                  "key": "db.user",
                  "value": {
                    "stringValue": "postgres"
                  }
                },
                {
                  "key": "thread.name",
                  "value": {
                    "stringValue": "http-nio-8181-exec-3"
                  }
                },
                {
                  "key": "entryId",
                  "value": {
                    "stringValue": "fb6a7f9f0664d0f7"
                  }
                },
                {
                  "key": "db.name",
                  "value": {
                    "stringValue": "postgres"
                  }
                }
              ],
              "status": {}
            }
          ]
        }
      ],
      "schemaUrl": "https://opentelemetry.io/schemas/1.24.0"
    }
  ]
}

### Expected behavior

Contains db.operation or db.operation.name

### Actual behavior

missing db.operation

### Javaagent or library instrumentation version

v2.3

### Environment

**JDK**:1.8
**OS**:centos7

**Comment by laurit** [comment]
@zhangjiabin1010 did this work in a previous version? What instrumentation generates this span? Would it be possible to provide a minimal sample application that reproduces the issue?

**Comment by zhangjiabin1010** [comment]
> @zhangjiabin1010这在以前的版本中有效吗？什么仪器产生这个跨度？是否可以提供一个重现该问题的最小示例应用程序？

It is work in version 1.32.   ScopeName = 'io.opentelemetry.jdbc' ,
The service source code is not here with me, so I can't provide an example.

**Comment by laurit** [comment]
To me the most likely explanation is that you have disabled the sql statement sanitizer. Besides sanitizing the query sanitizer is also used to extract the operation and table name.

**Comment by zhangjiabin1010** [comment]
> 对我来说，最可能的解释是您已禁用 sql 语句清理程序。除了清理之外，查询清理程序还用于提取操作和表名称。

Yes, that's the reason, maybe it should be added to the documentation. thanks for reply

**Comment by trask** [comment]
re-opening, as @laurit pointed out elsewhere it may make sense to capture `db.operation` even when sanitization is enabled
