### ISSUE TITLE
http_requests_total not present in metrics collected using otel java agents jar 2.30

### ISSUE THREAD

**Issue by anand188** [open-telemetry/opentelemetry-java-instrumentation#11370]
### Describe the bug

Tomcat sent env .bat with jar and otlp endpoint and http set to collect metrics.
Then otel-collector to collect the metrics and prometheus with grafana all running with latest docker images.

Only http_server_request_duration_seconds_bucket,http_server_request_duration_seconds_sum ,http_server_request_duration_seconds_count are there not http_requests_total  is this correct am i supposed to query only what i have or missing something in configuration or its bug ?

### Steps to reproduce

Tomcat sent env .bat with jar and otlp endpoint and http set to collect metrics.
Then otel-collector to collect the metrics and prometheus with grafana all running with latest docker images.

Only http_server_request_duration_seconds_bucket,http_server_request_duration_seconds_sum ,http_server_request_duration_seconds_count are there not http_requests_total  is this correct am i supposed to query only what i have or missing something in configuration or its bug ?

### Expected behavior

http_requests_total is excpected

### Actual behavior

Only http_server_request_duration_seconds_bucket,http_server_request_duration_seconds_sum ,http_server_request_duration_seconds_count

### Javaagent or library instrumentation version

2.3.0

### Environment

**JDK**:
**OS**:
Tomcat windows

**Comment by laurit** [comment]
Otel does not define a metric named `http_requests_total`

**Comment by anand188** [comment]
can you also point me to document where it says these are HTTP metrics captured by OTEL without any code changes by default

**Comment by laurit** [comment]
> can you also point me to document where it says these are HTTP metrics captured by OTEL without any code changes by default

https://opentelemetry.io/docs/specs/semconv/http/http-metrics/

**Comment by anand188** [comment]
Thanks 

http.server.active_requests   is Experimental  it says ? how i turn or configure to collect experimental metrics

**Comment by laurit** [comment]
Add `-Dotel.instrumentation.http.server.emit-experimental-telemetry=true` to jvm arguments.

**Comment by anand188** [comment]
Thanks very much for prompt responses
