### ISSUE TITLE
Check async redis instrumentation

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1139]
I just noticed that for example, `LettuceAsyncClientTest` doesn't actually verify multiple spans end up in the same trace.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/lettuce/lettuce-5.0/src/test/groovy/LettuceAsyncClientTest.groovy

This might be because we don't have a root span in the test, or because the instrumentation of the future return types doesn't work correctly. We should have test cases for this too.

**Comment by trask** [comment]
Closed by #3839
