### ISSUE TITLE
Duplicate Apache HTTP spans for single requests

### ISSUE THREAD

**Issue by hannahchan** [open-telemetry/opentelemetry-java-instrumentation#11401]
### Describe the bug

When using the Java agent in a codebase that has its own wrappers around Apache HTTP clients, we get duplicate HTTP client spans for individual requests.

I think this is happening because the wrappers extend `org.apache.http.client.HttpClient` or `org.apache.http.nio.client.HttpAsyncClient` and the Java agent type matches against these. Since these wrappers wrap another `HttpClient` or `HttpAsyncClient`, we get duplicate spans.

Strangely, these seem to be sibling spans rather than nested spans.

I also tried this by wrapping the wrapper and managed to get three spans to appear.

We have also not set the `otel.instrumentation.experimental.span-suppression-strategy` and assume we are using the default `semconv` span suppression strategy.

### Steps to reproduce

Create a wrapped HTTP client like the one below and instrument the application with the Java agent.

```java
public class WrappedHttpClient extends CloseableHttpClient {
    private final CloseableHttpClient delegate;

    public WrappedHttpClient(CloseableHttpClient delegate) {
        this.delegate = delegate;
    }

    @Override
    protected CloseableHttpResponse doExecute(HttpHost target, HttpRequest request, HttpContext context) throws IOException {
        return delegate.execute(target, request, context);
    }

    @Override
    public void close() throws IOException {
        delegate.close();
    }

    @Override
    public HttpParams getParams() {
        return delegate.getParams();
    }

    @Override
    public ClientConnectionManager getConnectionManager() {
        return delegate.getConnectionManager();
    }
}
```
In the above example, `CloseableHttpClient` extends `org.apache.http.client.HttpClient`.

### Expected behavior

Only one span to be created.

### Actual behavior

Two sibling spans are created.

### Javaagent or library instrumentation version

Java agent v2.4.0

### Environment

Tested with HTTP clients from `org.apache.httpcomponents` version 4.1.5 and 4.5.14.

### Additional context

I haven't yet looked into the metric side of things but suspect double counting to be happening.

**Comment by hannahchan** [comment]
After doing a bit of code surfing, I think I've identified why I am seeing sibling spans instead of nested spans. It's because of the following code in `TracingProtocolExec.java`.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/b80dee7d9a3b19a17ded9b90372b9b6cb34fa3d6/instrumentation/apache-httpclient/apache-httpclient-4.3/library/src/main/java/io/opentelemetry/instrumentation/apachehttpclient/v4_3/TracingProtocolExec.java#L50-L55

When the wrapped `HttpClient` executes, it uses the same parent context that as set by the wrapping `HttpClient`.

**Comment by hannahchan** [comment]
I've also attempted to identify why `org.apache.http.nio.client.HttpAsyncClient` has the same behaviour (duplicate sibling spans) however the complexity of the wrapper I'm investigating and the instrumentation itself currently exceeds my level of knowledge about `HttpAsyncClient`. I might come back to this later.

As the for a solution to the problem outlined in this PR, I currently don't know what that might be.

**Comment by laurit** [comment]
Could you provide a minimal sample application that reproduces the issue.

**Comment by hannahchan** [comment]
> Could you provide a minimal sample application that reproduces the issue.

I just tried and failed to reproduce the issue in a blank minimalistic application. I'm currently investigating my production application further. I'm not ready to conclude anything yet.
