### ISSUE TITLE
-Dotel.instrumentation.http.server.capture-request-headers=Cookie  may cause http request 404

### ISSUE THREAD

**Issue by pepeshore** [open-telemetry/opentelemetry-java-instrumentation#11464]
### Describe the bug

when I run my demo with
` java -javaagent:opentelemetry-javaagent.jar -Dotel.instrumentation.http.server.capture-request-headers=Cookie spring-tomcat-jdk17-0.0.1-SNAPSHOT.jar`
All HTTP requests return a 404 error
And I notice that if the request has no header named Cookie, the request returns successful

### Steps to reproduce

1. Download my demo [spring-tomcat-jdk17-0.0.1-SNAPSHOT.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/15450301/spring-tomcat-jdk17-0.0.1-SNAPSHOT.zip)
2. Change the file extension from .zip to .jar.
3. Run the demo with command ` java -javaagent:opentelemetry-javaagent.jar -Dotel.instrumentation.http.server.capture-request-headers=Cookie spring-tomcat-jdk17-0.0.1-SNAPSHOT.jar`
4. Initiate an HTTP request with command `curl 'http://127.0.0.1:8080/tomcat/hello'   -H 'accept: text/html' `, a string 'hello' is returned
5. Initiate an HTTP request with command `curl 'http://127.0.0.1:8080/tomcat/hello'   -H 'accept: text/html'   -H 'cookie: ca=hbcda'`, a 404 error occurs

### Expected behavior

a string 'hello' is returned

### Actual behavior

a 404 error occurs

### Javaagent or library instrumentation version

2.4

### Environment

**JDK**:
**OS**:

**Comment by AlchemyDing** [comment]
Please create a repository and provide the source code of this demo.
