### ISSUE TITLE
Run tests with full agent jar

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1146]
This could probably come after supporting running tests with a mini module-specific agent jar. We should also have a mode, probably built in the nightly build, to run tests with the full agent jar. Currently, we have no way of catching simple packaging issues like instrumentation not being bundled at all.

**Comment by iNikem** [comment]
See #1422 . That bug would be found by our tests if we used full agent jar.

**Comment by iNikem** [comment]
Btw, @anuraaga have you thought already how will we get hold of the traces produced by tests?

**Comment by trask** [comment]
in-memory otlp listener launched by the test?

**Comment by iNikem** [comment]
> in-memory otlp listener launched by the test?

You mean actually listening on a network port and accepting OTLP?

**Comment by anuraaga** [comment]
@iNikem I missed replying to this issue - yeah I was thinking using network as last resort should always be possible. But we have some test-specific logic in the agent related too bootstrap classloader, so assuming that's an ok thing and not something to remove completely, another approach that came to mind is test-specific logic to have spans exported to a list in the bootstrap classloader and just read directly.

**Comment by trask** [comment]
> have spans exported to a list in the bootstrap classloader and just read directly.

the only complication is that the SDK classes (e.g. `SpanData`) live in AgentClassLoader, so we can't use them directly during test verification

**Comment by trask** [comment]
Adding a note here, when we do this, to make sure that the instrumentation classes (`src/main/java`) are not on the classpath when running the tests, in order to catch problems like https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1585#issuecomment-723670977

**Comment by anuraaga** [comment]
> the only complication is that the SDK classes (e.g. SpanData) live in AgentClassLoader, so we can't use them directly during test verification

Thought a bit about this, and perhaps this isn't a big deal if the spans are exported to the bootstrap classloader as serialized protos - test would be able to deserialize them trivially without any shading issues.

**Comment by anuraaga** [comment]
And another thought, not sure about it, but if this test-exporter used the exporter_jar mechanism, IIUC, getting the spans from tests could be as simple as the agent providing a reference to the exporter classloader through the bootstrap. We can make it package-private and still access it through reflection from tests I think. Then classload the test exporter, which would have methods for accessing the serialized protos.

**Comment by anuraaga** [comment]
With my mental model refreshed on this I am going to try a stab at it. Work on context interop will also go much nicer knowing the instrumentation of properly shaded in the tests.

**Comment by trask** [comment]
🤞🤞

**Comment by anuraaga** [comment]
This happened!
