### ISSUE TITLE
Auto instrumentation disabling jBoss MBeans

### ISSUE THREAD

**Issue by dv-morais** [open-telemetry/opentelemetry-java-instrumentation#11470]
### Describe the bug

Hello everyone,

I have been following the steps of this [Link](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jmx-metrics/javaagent/README.md) to make the agent to capture data from the java MBeans but when I'm trying to capture data from the 'jboss.as' to 'jboss.as.expr' I noticed that when I have the opentelemetry agent activated these metrics does not appear at the MBeans list. Do I have to do something to not make these metrics disabled?

### Steps to reproduce

1. activate java auto-instrumentation agent with the jboss EAP 6.4 application server.
2. 'jboss.as' and 'jboss.as.expr' does not appear at the MBeans list.

### Expected behavior

'jboss.as' and 'jboss.as.expr' appearing at the MBeans list to be captured using the steps of this [Link](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jmx-metrics/javaagent/README.md)

### Actual behavior

The steps of this [Link](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jmx-metrics/javaagent/README.md) cant be fulfilled because the 'jboss.as' and 'jboss.as.expr' disappear when the agent is enabled.

### Javaagent or library instrumentation version

2.3.0

### Environment

**JDK**: 1.8.412
**OS**: amazon linux 2
JBOSS EAP 6.4

**Comment by laurit** [comment]
Could you try with https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.4.0 and let us know whether this issue is still present.

**Comment by steverao** [comment]
> I updated the agent and...vuala! Worked like a charm!

It seems the problem has solved in 2.4.0, so close it now
