### ISSUE TITLE
Request for Documentation and Environment Variables for Collecting Experimental Data

### ISSUE THREAD

**Issue by leon4652** [open-telemetry/opentelemetry-java-instrumentation#11483]
### Is your feature request related to a problem? Please describe.

Hello,

I am currently using the 'automatic instrumentation' feature of agent-java to collect gRPC data.

First, I referred to the following issues:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11370
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/11231

To automatically instrument experimental data, it seems necessary to add an environment variable such as sometime instrumentation .. emit-experimental-telemetry=true.

In practice, I was able to collect data from the JVM buffer area using the variable otel.instrumentation.runtime-telemetry.emit-experimental-telemetry=true.
However, I was not successful in collecting data from a similar area, the system, despite setting the environment variable otel.instrumentation.system-telemetry.emit-experimental-telemetry=true.
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/system-metrics.md

I searched the documentation but could not find specific naming conventions.
I would like to know what environment variables need to be set to collect experimental values for specific areas.
If you have any related documentation or information, I would appreciate your help.

Thank you.

### Describe the solution you'd like

.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by laurit** [comment]
Otel java agent does not produce the system metrics described in https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/system-metrics.md Have a look at https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/hostmetricsreceiver/README.md

**Comment by leon4652** [comment]
I'm sorry for the delayed response.
I understand the issue. We had written logic to directly parse the gRPC sent from the Agent instead of using the Otel Collector, which naturally resulted in collecting only the basic Metric data provided by the Agent.

Thanks to you, we are using a great library. I appreciate your kind response and efforts.
