### ISSUE TITLE
Java agent not capturing database and connection pool metrics as expected

### ISSUE THREAD

**Issue by parasjain993** [open-telemetry/opentelemetry-java-instrumentation#11496]
### Describe the bug

I am using javaagent to collect traces and metrics for a java spring application (no spring-boot). Everything works well except for the fact that none of the database and connection pool metrics mentioned [here](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-metrics.md) are captured/emitted by the agent (other metrics like http, jvm, kafka are showing up). Although the spans for the database queries are showing up as expected in the emitted traces with all expected attributes.

### Steps to reproduce

Happens consistently in my environment (shared the env and library details below). I also tried using [opentelemetry-jdbc](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/jdbc/library) and wrapped the datasource with `GlobalOpenTelemtry.get()` with no effect. I see `OpentelemetryDatasource` wrapped around as expected but it seems to have only instrumentation related to tracing and not metrics.

<img width="1276" alt="Screenshot 2024-06-01 at 2 10 10 AM" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/8363178/6589bca8-86c3-4220-9ba3-de7aa6002158">

### Expected behavior

The database metrics should be captured by the agent by default, just like it is creating spans for the DB calls.

### Actual behavior

Database and connection pool metrics are not captured, even though other default metrics are shown.

### Javaagent or library instrumentation version

Checked with 2.0.0 and 2.4.0

### Environment

**JDK**: 17
**OS**: Linux (Red Hat Enterprise Linux 8.9)
**javaagent**: Tested on `2.0.0` & `2.4.0`

**Otel agent config** 
export OTEL_SERVICE_NAME=ABC
export OTEL_JAVAAGENT_ENABLED=true
export OTEL_JAVAAGENT_DEBUG=true
export OTEL_TRACES_EXPORTER=console
export OTEL_TRACES_SAMPLER=parentbased_always_on
export OTEL_METRICS_EXPORTER=console
export OTEL_EXPERIMENTAL_METRICS_VIEW_CONFIG=${HOME}/etc/otel-metrics-view.yaml
export OTEL_LOGS_EXPORTER=none

**DB config**
library: `spring-jdbc 5.3.23`
connection-pool: `apache.commons.dbcp2.BasicDataSource`
driverClass: `net.sourceforge.jtds.jdbc.Driver`
driverURL: `jdbc:jtds:sqlserver://DBSERVER/DBNAME;progName=PROGNAME;packetSize=32768`

### Additional context

I generally use Prometheus exporter for metrics, but the database metrics were not captured/shown even when I used console exported

**Comment by laurit** [comment]
[db.client.operation.duration](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-metrics.md#metric-dbclientoperationduration) was added to spec a week ago, java agent does not implement it yet. Missing connection pool metrics could indicate that agent does not have instrumentation for the connection pool that you use.

**Comment by parasjain993** [comment]
> [db.client.operation.duration](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-metrics.md#metric-dbclientoperationduration) was added to spec a week ago, java agent does not implement it yet. Missing connection pool metrics could indicate that agent does not have instrumentation for the connection pool that you use.

ok. I am using apache.commons.dbcp2. I also tried using [opentelemetry-jdbc](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/jdbc/library) and wrapped the ds with `GlobalOpenTelemtry.get()` with no effect.

**Comment by laurit** [comment]
Metrics should be collected for commons dbcp2, but the metrics collection seems to depend registering `BasicDataSource` with jmx mbean server. https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/de30e3120a77e89368aa983b837c06706001ed35/instrumentation/apache-dbcp-2.0/javaagent/src/test/java/io/opentelemetry/javaagent/instrumentation/apachedbcp/v2_0/ApacheDbcpInstrumentationTest.java#L28-L30 I think we should see whether this can be made to work without requiring the `preRegister` call.

**Comment by laurit** [comment]
Calling
```java
dataSource.setJmxName("io.opentelemetry.db:name=" + dataSourceName);
```
triggers metrics collection without the need to call `preRegister`.

**Comment by parasjain993** [comment]
Thanks again for checking this, but for some reason the DB pool metrics are still not getting captured for me with below:
`BasicDataSource ds = BasicDataSourceFactory.createDataSource(properties);`
`ds.setJmxName("io.opentelemetry.db:name=" + name);`
`DataSource telemetrizedDS = JdbcTelemetry.create(GlobalOpenTelemetry.get()).wrap(ds);`

**Comment by laurit** [comment]
Initially you claimed to be using the agent now you seem to be using manual instrumentation, please clarify which you are using.
When you are using manual instrumentation then `JdbcTelemetry` does not produce the connection pool metrics, you have to use `ApacheDbcpTelemetry`, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/apache-dbcp-2.0/library/README.md#usage
If you can't get this working then please provide a minimal application that reproduces your issue along with necessary instructions.

**Comment by parasjain993** [comment]
Sorry if I may have gotten confused with `JdbcTelemetry` here, but you mean below should do the trick with java agent?Because its still not working out for me.
`BasicDataSource ds = BasicDataSourceFactory.createDataSource(properties);`
`ds.setJmxName("io.opentelemetry.db:name=" + "abc");`

**Comment by laurit** [comment]
> Because it still was not working out for me. 

Please provide a minimal sample application that reproduces the issue if you wish for someone to have a look at why it does not work for you.

> I assume rest may get added gradually.

Connection pool instrumentations generally have only the metrics that the pool implementation itself provides. If more metrics are needed then the pool implementation may need to be changed.
