### ISSUE TITLE
Simplify io.opentelemetry.instrumentation.api.cache.Function(s) after dropping Java 7

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1151]
Drop `io.opentelemetry.instrumentation.api.cache.Function` and remove/simplify much of `io.opentelemetry.instrumentation.api.cache.Functions`.

**Comment by iNikem** [comment]
We ended up not merging `io.opentelemetry.instrumentation.api.cache.Function`
