### ISSUE TITLE
Logback `OpenTelemetryAppender` Use jdk `Proxy` to wrap `ILoggingEvent` may not good.

### ISSUE THREAD

**Issue by HuiWang1995** [open-telemetry/opentelemetry-java-instrumentation#11532]
### Is your feature request related to a problem? Please describe.

`Proxy` will create class file and save in meta space, which will cause full gc when it is  filled.

Obviously, we will generate a proxy class for each log output, which will fill it up quickly.

### Describe the solution you'd like

I think we can just rewrite the method with a specific subclass and then package it, without generating a new dynamic proxy class every time.

### Describe alternatives you've considered

Concrete subclass that only compile once instead.

### Additional context

```java
 Proxy.newProxyInstance(
                ILoggingEvent.class.getClassLoader(),
                new Class<?>[] {ILoggingEvent.class},
                (proxy, method, args) -> {
                  if ("getMDCPropertyMap".equals(method.getName())) {
                    return eventContextMap;
                  } else if ("getLoggerContextVO".equals(method.getName())) {
                    return vo;
                  }
                  try {
                    return method.invoke(event, args);
                  } catch (InvocationTargetException exception) {
                    throw exception.getCause();
                  }
                });
```

**Comment by HuiWang1995** [comment]
> > `Proxy` will create class file and save in meta space, which will cause full gc when it is filled.
> > Obviously, we will generate a proxy class for each log output, which will fill it up quickly.
> 
> You seem to be mistaken on how jdk proxies work, the proxy class is create only once for given class loader and interfaces.

it`s call in method, and not a global var, it will have cache? then only create once?

**Comment by laurit** [comment]
> it`s call in method, and not a global var, it will have cache? then only create once?

https://github.com/openjdk/jdk11/blob/37115c8ea4aff13a8148ee2b8832b20888a5d880/src/java.base/share/classes/java/lang/reflect/Proxy.java#L413
