### ISSUE TITLE
Instrumentation shouldn't force suppress new traces

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1155]
Currently, we have conditions in the logic itself to prevent starting traces from database clients like here

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1148/files#diff-a9ba30229bfd53ce71738c8fd3f84f50R73

But some users may want traces for individual database calls. This should be configurable somehow rather than hard-coded in the instrumentation.

**Comment by trask** [comment]
@anuraaga can we close this in favor of #1822?

**Comment by anuraaga** [comment]
I don't think this is about nested spans - the ones suppressed don't have any parent available IIUC.

**Comment by trask** [comment]
oh, I understand now, I agree we shouldn't suppress CLIENT spans if there is no parent

(it sort of makes sense to me to suppress INTERNAL spans if there's no parent, since then they aren't "internal" to anything)

do you remember where you saw this behavior?
