### ISSUE TITLE
Does MessageWithDestination.java assume that the client is always a JMS sender?

### ISSUE THREAD

**Issue by himamulch** [open-telemetry/opentelemetry-java-instrumentation#11551]
### Describe the bug

Hi, We have a python client that puts messages to an MQ, which are then consumed by a downstream Java application which is enabled with auto instrumentation using _opentelemetry-javaagent_.  We see that the instrumentation library is throwing null pointer during runtime at this line https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v2.4.0/instrumentation/jms/jms-common/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jms/MessageWithDestination.java#L34C4-L34C36

It looks like it is due to Jms Destination not being available on the message. Could you please clarify if this expected.

Thanks

### Steps to reproduce

Have a python (may be non-Java) client app produce MQ messages and a Java app which is enabled with auto instrumentation using opentelemetry-javaagent consume those messages.

### Expected behavior

Auto instrumentation should generate spans as expected

### Actual behavior

The instrumentation library throws null pointer exception

### Javaagent or library instrumentation version

java agent version 2.2.0

### Environment

Java 11

### Additional context

Is the JMS Destination expected to be set on messages from non Java client apps as well?

**Comment by trask** [comment]
can you share a stack trace for the NullPointerException? thanks

**Comment by himamulch** [comment]
Hi @trask 

```
[otel.javaagent 2024-06-06 17:46:47:357 +0000] [pool-4-thread-22] DEBUG io.opentelemetry.javaagent.bootstrap.ExceptionLogger - Failed to handle exception in instrumentation for com.ibm.mq.jms.MQMessageConsumer
java.lang.NullPointerException
        at io.opentelemetry.javaagent.instrumentation.jms.MessageWithDestination.create(MessageWithDestination.java:34)
        at com.ibm.mq.jms.MQMessageConsumer.receive(MQMessageConsumer.java:215)
        at cotown.lib.common.pubsub.jms.subscriber.JmsReceiver.receiveMessage(JmsReceiver.java:208)
        at cotown.lib.common.pubsub.jms.subscriber.JmsBatchReceiver.run(JmsBatchReceiver.java:77)
        at cotown.lib.common.pubsub.jms.subscriber.JmsBatchReceiver.start(JmsBatchReceiver.java:140)
```
