### ISSUE TITLE
Support tracing the ClickHouse Java HTTP client

### ISSUE THREAD

**Issue by devurandom** [open-telemetry/opentelemetry-java-instrumentation#11562]
### Is your feature request related to a problem? Please describe.

ClickHouse Java HTTP client (https://github.com/ClickHouse/clickhouse-java) queries currently show up only as HTTP traces.

### Describe the solution you'd like

It would be nice if queries by the ClickHouse Java HTTP client were instrumented like database requests (in addition to the underlying HTTP requests), e.g. with a `db.query.text`, cf. https://opentelemetry.io/docs/specs/semconv/database/database-spans/.

### Describe alternatives you've considered

* Automatic HTTP client instrumentation shows that a request happens, but not the query. Relying on them is not an alternative.
* Manual instrumentation of code that calls the ClickHouse Java HTTP client. This works, but is inconvenient.

**Comment by laurit** [comment]
[We'd welcome a contribution for this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/ISSUES.md#contribution-welcome)

**Comment by jaydeluca** [comment]
@devurandom are you planning on contributing this? Otherwise I am interested in working on it.

**Comment by devurandom** [comment]
> @devurandom are you planning on contributing this? Otherwise I am interested in working on it.

Please go ahead! :)

**Comment by devurandom** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11660 was merged. Should this be closed? Or will that happen when 2.6.0 is released?

**Comment by laurit** [comment]
Resolved with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11660
