### ISSUE TITLE
Error message: Unable to parse response body, HTTP status message: Not Found

### ISSUE THREAD

**Issue by 1095071913** [open-telemetry/opentelemetry-java-instrumentation#11600]
### Describe the bug

[otel.javaagent 2024-06-15 20:59:25:693 +0800] [OkHttp http://localhost:4318/...] WARN io.opentelemetry.exporter.internal.http.HttpExporter - Too many log messages detected. Will only log once per minute from now on.
[otel.javaagent 2024-06-15 20:59:25:693 +0800] [OkHttp http://localhost:4318/...] WARN io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export logs. Server responded with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found

### Steps to reproduce

`mkdir -p /usr/local/patpet/opentelemetry/prometheus
mkdir -p /usr/local/patpet/opentelemetry/otel-collector
cd /usr/local/patpet/opentelemetry

cat >./prometheus/config.yml <<-'EOF'
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'example'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
EOF

cat > ./otel-collector/config.yml <<-'EOF'
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/jaeger:
    endpoint: "jaeger:14250"
    #endpoint: "localhost:4318"
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [prometheus]
EOF

cat > docker-compose.yml <<-'EOF'
version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.102.1
    container_name: otel-collector
    command: ["--config=/etc/config.yml"]
    volumes:
      - ./otel-collector/config.yml:/etc/config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "14250:14250"
      - "16686:16686"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
EOF
docker-compose up -d

` middleware.sh，

After execution

`java 
-javaagent:opentelemetry-javaagent.jar
-Dotel.traces.exporter=otlp
-Dotel.exporter.otlp.protocol=http/protobuf
-Dotel.exporter.otlp.endpoint=http://localhost:4318
-Dotel.resource.attributes=service.name=gateway
-Dotel.metrics.exporter=none
-jar xx.jar`

An error will be reported after execution

Similar problem：https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5529

### Expected behavior

Run successfully

### Actual behavior

[otel.javaagent 2024-06-15 20:59:25:693 +0800] [OkHttp http://localhost:4318/...] WARN io.opentelemetry.exporter.internal.http.HttpExporter - Too many log messages detected. Will only log once per minute from now on.
[otel.javaagent 2024-06-15 20:59:25:693 +0800] [OkHttp http://localhost:4318/...] WARN io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export logs. Server responded with HTTP status code 404. Error message: Unable to parse response body, HTTP status message: Not Found

### Javaagent or library instrumentation version

https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.4.0

### Environment

**JDK**:17
**OS**:ubuntu22
**project**:springboot3

**Comment by laurit** [comment]
You have not configured logs pipeline in the collector. Either configure the logs pipeline or disable logs exporter in the agent with `-Dotel.logs.exporter=none`

**Comment by 1095071913** [comment]
> You have not configured logs pipeline in the collector. Either configure the logs pipeline or disable logs exporter in the agent with `-Dotel.logs.exporter=none`

Now `-Dotel.logs.exporter=none` is configured, but jaeger is not collecting information. Why

**Comment by laurit** [comment]
> Now -Dotel.logs.exporter=none is configured, but jaeger is not collecting information. Why

Probably because in the collector you are using `otlp/jaeger` exporter but the endpoint you have set `jaeger:14250` is not an otlp endpoint. I have not tried setting it up myself, probably you should be using `endpoint: http://jaeger:4317`, don't forget to also export that port. Consult jaeger documentation on what endpoint you should be using for otlp and whether it uses http or https.

**Comment by 1095071913** [comment]
> > Now -Dotel.logs.exporter=none is configured, but jaeger is not collecting information. Why
> 
> Probably because in the collector you are using `otlp/jaeger` exporter but the endpoint you have set `jaeger:14250` is not an otlp endpoint. I have not tried setting it up myself, probably you should be using `endpoint: http://jaeger:4317`, don't forget to also export that port. Consult jaeger documentation on what endpoint you should be using for otlp and whether it uses http or https.



> > Now -Dotel.logs.exporter=none is configured, but jaeger is not collecting information. Why
> 
> Probably because in the collector you are using `otlp/jaeger` exporter but the endpoint you have set `jaeger:14250` is not an otlp endpoint. I have not tried setting it up myself, probably you should be using `endpoint: http://jaeger:4317`, don't forget to also export that port. Consult jaeger documentation on what endpoint you should be using for otlp and whether it uses http or https.

Thanks for your reply. It has been resolved

**Comment by sulthans** [comment]
@1095071913 I am getting below error,
message":"Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317

Configured in Springboot application,

Added code,

 @Bean
    public OtlpHttpSpanExporter otlpGrpcSpanExporter() {
        return OtlpHttpSpanExporter.builder().setEndpoint("http://localhost:4317").build();
    } 

docker-compose.yml :

services:
  collector:
    container_name: collector
    image: otel/opentelemetry-collector:0.108.0
    command:
      ["--config=/etc/config.yml"]
    volumes:
      - ./docker/collector/otel-collector.yml:/etc/config.yml
    restart: always
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # http receiver
      - "8889:8889" # Prometheus exporter metrics
      - "55679:55679"

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"

  jaeger-all-in-one:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14250:14250"
      - "6831:6831/udp"

otel-config.yml :

    receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:

  prometheus:
    endpoint: "0.0.0.0:8889"
#    enable_open_metrics: true
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]

environment variables :

  OTEL_TRACES_EXPORTER=otlp;
 OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf;
 OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:4317/v1/traces

**Comment by sulthans** [comment]
@1095071913 @laurit 
i have used the same confi,

config.yml 

 receivers:
otlp:
protocols:
grpc:
http:

processors:
batch:

exporters:
prometheus:
endpoint: "0.0.0.0:8889"
otlp/jaeger:
endpoint: "jaeger:14250"
#endpoint: "localhost:4318"
tls:
insecure: true

service:
pipelines:
traces:
receivers: [otlp]
processors: []
exporters: [otlp/jaeger]
metrics:
receivers: [otlp]
processors: []
exporters: [prometheus]


docker-compose.yml

 version: "3"

services:
otel-collector:
image: otel/opentelemetry-collector:0.102.1
container_name: otel-collector
command: ["--config=/etc/config.yml"]
volumes:
- ./otel-collector/config.yml:/etc/config.yml
ports:
- "4317:4317"
- "4318:4318"
- "8889:8889"

prometheus:
image: prom/prometheus:latest
container_name: prometheus
ports:
- "9090:9090"
volumes:
- ./prometheus/config.yml:/etc/prometheus/prometheus.yml

jaeger:
image: jaegertracing/all-in-one:latest
container_name: jaeger
ports:
- "6831:6831/udp"
- "14250:14250"
- "16686:16686"

grafana:
image: grafana/grafana:latest
container_name: grafana
ports:
- "3001:3000"


started with java  -javaagent:/Users/sulthans/Documents/ws/lib/opentelemetry-javaagent.jar -Dotel.logs.exporter=none  -Dotel.traces.exporter=otlp -Dotel.exporter.otlp.protocol=http/protobuf -Dotel.exporter.otlp.endpoint=http://localhost:4318 -Dotel.resource.attributes=service.name=gateway -jar build/libs/test-1.jar


App is not onboarded in jaeger, but not getting tracing the endpoint executed in my local.

<img width="1706" alt="Screenshot 2024-09-05 at 8 52 29 AM" src="https://github.com/user-attachments/assets/d3964e9b-be85-4c19-b070-bbfee1823dc3">

**Comment by laurit** [comment]
@sulthans usually it is not a good idea to add comments to a closed issue as these are just ignored. I'd guess that `endpoint: "jaeger:14250"` is not correct. If you wish for someone to take a look create a new issue, include a minimal sample that reproduces the issue along with any instructions necessary.

**Comment by GeoffreyStemys** [comment]
In my case it was because even with the proper flags in the prometheus-kube-stack helm chart: 
```
prometheusOperator:
  prometheusSpec:
    enableOTLPReceiver: true
```
The CRD should also be at recent versions:

```shell
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.92.1/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagerconfigs.yaml -n grafana
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.92.1/example/prometheus-operator-crd/monitoring.coreos.com_alertmanagers.yaml -n grafana
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.92.1/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml -n grafana
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.92.1/example/prometheus-operator-crd/monitoring.coreos.com_probes.yaml -n grafana
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.92.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheusagents.yaml -n grafana
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.92.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml -n grafana
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.92.1/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml -n grafana
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.92.1/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml -n grafana
kubectl apply --server-side -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.92.1/example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml -n grafana
```

Then the resulting prometheus pod will be auto-generated with the proper arguments:
```shell
Args:
  --web.enable-otlp-receiver
```
