### ISSUE TITLE
@WithSpan as Configuration Setting for javaagent

### ISSUE THREAD

**Issue by Aaron-Ritter** [open-telemetry/opentelemetry-java-instrumentation#11627]
### Is your feature request related to a problem? Please describe.

There is source code i am not in control of and the javaagent does not discover the part out of the box because the specific code is executed in async threads with a to javaagent unknown class/method name, but i still would like to add OTEL Spans to it. 

### Describe the solution you'd like

Similar to the possibility of excluding annotations: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/opentelemetry-instrumentation-annotations-1.16 I'd like to add annotations as a configuration by identifying a configuring a setting where i can define all methods to be included to auto-instrumentation.

### Describe alternatives you've considered

I can and add the @WithSpan annotation on a subsequential method but this creates two issues. 

1. I miss what happens before that but still would like to know
2. I'd have to implement it in 50 different places where some of them again I am not in charge with

This is especially useful for a quick end 2 end discovery without having to involve to many different teams or even vendors.

**Comment by laurit** [comment]
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/methods Is this what you are looking for?

**Comment by Aaron-Ritter** [comment]
Exactly 🤦! I am slightly confused why i didn't see this in the first place. Thanks
