### ISSUE TITLE
Lettuce 5.1 instrumentation adds args also in db.statement attribute

### ISSUE THREAD

**Issue by RashmiRam** [open-telemetry/opentelemetry-java-instrumentation#1170]
As per the Semantic conventions mentioned here  https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md#call-level-attributes,  We can obfuscate  value to exclude sensitive information. Args to Redis commands might have sensitive information. Lettuce 5.1  adds args to the `db.statement` attribute key. https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/lettuce/lettuce-5.1/src/main/java/io/opentelemetry/instrumentation/auto/lettuce/v5_1/OpenTelemetryTracing.java#L268

I checked in other versions of lettuce 4.0 & 5.0, only command is added to `db.statement` Shall we go ahead with only command getting added to this attribute?  If it's alright with you all, I can raise a PR for the same.

**Comment by iNikem** [comment]
You are right about sensitive data. At the same time, the same semantic convention that you reference says:

> For Redis, the value provided for db.statement SHOULD correspond to the syntax of the Redis CLI. If, for example, the HMSET command is invoked, "HMSET myhash field1 'Hello' field2 'World'" would be a suitable value for db.statement

Thus ideally we want to include arguments, but probably want to scramble actual values. I am not sure at all how easy this is.

**Comment by RashmiRam** [comment]
Agreed @iNikem. It will be helpful to see the actual CLI syntax. I looked at how other language libraries are handling the same.
Ruby & Python otel instrumentation redis library truncates each actual args beyond certain threshold length. We can keep the threshold length to be very small(say., 10) so that it leaves the args in a jumbled state. I agree that it won't fully obfuscate the sensitive data. At least, this way we can keep the CLI syntax intact & jumble the actual args.

Ref: 
Ruby -> https://github.com/open-telemetry/opentelemetry-ruby/blob/master/instrumentation/redis/lib/opentelemetry/instrumentation/redis/utils.rb
Python -> https://github.com/open-telemetry/opentelemetry-python/blob/master/instrumentation/opentelemetry-instrumentation-redis/src/opentelemetry/instrumentation/redis/util.py

Shall we think of handling this along these lines? What do you say?

**Comment by iNikem** [comment]
Java SDK already provides a functionality to truncate too long attribute values. I think it will be confusing to everybody to implement one more truncation just for some attributes and with completely different purpose.

I would say we need the holistic approach to db queries normalisation to prevent both PII data leaking and having too many artificially different attribute values. There is no point in solving this problem locally for some dbs.

**Comment by RashmiRam** [comment]
Understood @iNikem. Thanks for the explanation. There is this [AUTH command ](https://redis.io/commands/auth)at redis which takes username & password as arguments. Going by this way, **_only Lettuce 5.1_** shows the full command with args where the password will also be shown in the spans 😨.(Lower versions of Lettuce & Jedis shows only commands).   Is it a valid ask to handle this alone at least or Is there a way to handle this through existing configurations?

**Comment by anuraaga** [comment]
Thanks for this callout @RashmiRam. I agree with @iNikem that we probably want a generic solution that applies to all our DB instrumentation. And the main reason the Lettuce 5.1 instrumentation shows the args and not the other ones is it's the newest instrumentation and coincidentally was written after the semantic conventions for `db.statement` was updated to clarify the inclusion of args. We can expect the other ones to follow suit at some point.

However, the `AUTH` command is indeed an example of a well-known command where we can be certain PII is always present. I think we should go ahead and handle it specifically, we should always scrub the args for this command specifically as a good bang for buck lacking any generic scrubbing mechanism. If you can raise a PR for that, that'd be really great!

**Comment by mateuszrzeszutek** [comment]
I think we can close this issue - trimming data in all Redis commands was implemented in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1405 and https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1441 for all instrumented Redis libraries.
