### ISSUE TITLE
Artifacts are published to wrong location

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1171]
E.g. [latest build](https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/3211/workflows/e548c07d-dfad-4cbf-99ff-bdd04f65bb6b/jobs/17524) published javagent-all.jar to 

`https://oss.jfrog.org/oss-snapshot-local/io/opentelemetry/javaagent/opentelemetry-javaagent/0.8.0-SNAPSHOT/opentelemetry-javaagent-0.8.0-SNAPSHOT-all.jar`

This is wrong place to be :)

**Comment by anuraaga** [comment]
Fixed by #1173

**Comment by trask** [comment]
Not a problem if you want to move it, just wanted to mention it was in that location intentionally (#952):

> Also, moved javaagent artifacts to `io.opentelemetry.javaagent` groupId

**Comment by iNikem** [comment]
I wonder why have I approved #952 and then created this PR... Somehow I sense that this confusion is trying to tell us something
