### ISSUE TITLE
ScheduledExecutorService does not transform scheduleAtFixedRate

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#11760]
### Describe the bug

ScheduledExecutorService only transform schedule
<img width="835" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/10825900/8f2fef53-659c-4428-9fb1-ffa78275bbf0">
while spring schedule only transform repeat job 
<img width="730" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/10825900/cbf7bdcb-5792-4f55-bd5b-90c590cf1b8a">

Is it a bug? Or special design?

### Steps to reproduce

ScheduledExecutorService.scheduleAtFixedRate does not generate trace and span

### Expected behavior

ScheduledExecutorService repeat job will generate span

### Actual behavior

fail to create span

### Javaagent or library instrumentation version

1.32.1

### Environment

**JDK**: 11
**OS**: macos

**Comment by xiangtianyu** [comment]
> > Is it a bug? Or special design?
> 
> it is by design. `ScheduledExecutorService.scheduleAtFixedRate` does not currently create spans. Whether it should is also questionable, there is a good chance that it will produce a lot of unwanted spans.

Well, it may create a lot of meaningless spans, but if i want to get these spans, is there any suggestions?

**Comment by laurit** [comment]
> but if i want to get these spans, is there any suggestions?

You could write your own agent [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension)/[custom distro ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/distro) that does what you want. Or you could submit a PR to this project.

**Comment by madhav2302** [comment]
@laurit it would be nice to provide instrumentation on `scheduleAtFixedRate` and `scheduleWithFixedDelay` based on some param. 

We are using context for passing a key as baggage for logging. 
Due to missing propagation on above 2 methods, we need to manually wrap Runnable with `Context.current().wrap(runnable)`. 

What do you think about providing propagation for the methods as input parameter which can be enabled as needed.

**Comment by laurit** [comment]
> [@laurit](https://github.com/laurit) it would be nice to provide instrumentation on `scheduleAtFixedRate` and `scheduleWithFixedDelay` based on some param.
> 
> We are using context for passing a key as baggage for logging. Due to missing propagation on above 2 methods, we need to manually wrap Runnable with `Context.current().wrap(runnable)`.
> 
> What do you think about providing propagation for the methods as input parameter which can be enabled as needed.

Instrumenting these methods is almost always undesirable. I have a hard time coming up with a use case where you'd want to propagate context into long running scheduled activity. If you believe it is useful you are welcome to submit a PR, please include details on the use case where you believe this would be useful.
