### ISSUE TITLE
Add overload taking parent Context to typed tracers

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java-instrumentation#1178]
`io.opentelemetry.javaagent.typed.base.BaseTypedTracer#startSpan` has an overload taking a SpanContext and another one taking a Span as parent. However, there is no overload taking a full Context. Since this is what propagators return, this overload should be added for convenience.

I also recommend reviewing any usages of SpanContext parents, since they should not be necessary anywhere and lose timing accuracy (whenever you start a new span that has no parent span, the start time from System.currentTimeMillis will be used which is at most accurate to 1 ms but can have worse accuracy on some systems; when you start a span with a parent, the parent's MonoticClock which has nanosecond resolution will be used instead, see https://github.com/open-telemetry/opentelemetry-java/blob/c3a893a88ca97c4dcc01e1e0f289eed1ffd3b549/sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java#L290.

I can't think of any reason to use an explicit SpanContext as parent, so you could even consider removing this startSpan overload.

**Comment by mateuszrzeszutek** [comment]
Typed tracers have been removed, closing this issue.
