### ISSUE TITLE
Sampler.shouldSample in io.opentelemetry.http-url-connection  Span The Attributes for the thream.name parameter cannot be obtained. How to filter thread.name 

### ISSUE THREAD

**Issue by freshgeek** [open-telemetry/opentelemetry-java-instrumentation#11796]
### Describe the bug

```
  163: 2024-07-11T08:39:11.964===trace:935082e542052f21f1843df4ec7ecbfe ====span : 59c435ba0877dce6 ===  name: GET , attr -> AttributesMap{data={net.peer.port=8060, net.peer.name=xxxx, http.method=GET, http.url=http://xxxx:8060/notifications/v2?cluster=default&appId=reward_service&ip=172.16.24.250&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A376%7D%5D}, capacity=128, totalAddedValues=4},THREAD_NAME ->null contain ->false

```

### Steps to reproduce

```


  public SamplingResult shouldSample(
      Context parentContext,
      String traceId,
      String name,
      SpanKind spanKind,
      Attributes attributes,
      List<LinkData> parentLinks) {
 
    String format = String.format("%s===trace:%s ====span : %s ===  name: %s , attr -> %s,THREAD_NAME ->%s contain ->%s",
            LocalDateTime.now(),
            traceId,
            Span.fromContext(parentContext).getSpanContext().getSpanId(),
            name,
            attributes.asMap(),
            getAttr(attributes, SemanticAttributes.THREAD_NAME, null),EXCLUDED_THREAD_NAME.contains(getAttr(attributes, SemanticAttributes.THREAD_NAME, null)));
    System.out.println(format);
    if (EXCLUDED_THREAD_NAME.contains(getAttr(attributes, SemanticAttributes.THREAD_NAME, null))) {
      return SamplingResult.create(SamplingDecision.DROP);
    } 

    return  SamplingResult.create(SamplingDecision.RECORD_AND_SAMPLE) ;
  }

```

### Expected behavior

 can get Attributes

### Actual behavior

AttributesMap{data={net.peer.port=8060, net.peer.name=xxxx, http.method=GET, http.url=http://xxxx:8060/notifications/v2?cluster=default&appId=reward_service&ip=172.16.24.250&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A376%7D%5D}, capacity=128, totalAddedValues=4}

### Javaagent or library instrumentation version

1.28.0

### Environment

**JDK**:  jdk8
**OS**:

**Comment by freshgeek** [comment]
#11639

**Comment by laurit** [comment]
Have a look at https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4641 Note that the sampler is called when the span is created by the same thread that created the span so your sampler could call `Thread.currentThread().getName()` and use that for sampling.

**Comment by ZaynJiang** [comment]
Using Thread.currentThread().getName() is not an elegant approach. I want to filter directly based on tags, which makes it more flexible and versatile for users.

**Comment by trask** [comment]
cc @zeitlinger related to discussion last week

**Comment by zeitlinger** [comment]
> cc [@zeitlinger](https://github.com/zeitlinger) related to discussion last week

This was about adding thread name to span - not filtering.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/14144/files#diff-542da2fe8649f0d9a75e16fdae4a7eccd8517664cc1ad671f5e713539442c56aR68
