### ISSUE TITLE
Logback appender must send timestamp in nanoseconds if available

### ISSUE THREAD

**Issue by jjoslet** [open-telemetry/opentelemetry-java-instrumentation#11807]
### Is your feature request related to a problem? Please describe.

The timestamp is exported in milliseconds precision by the `OpenTelemetryAppender` which lead to trouble to sort logs at a central level.

### Describe the solution you'd like

Export timestamps in nanoseconds in the `LoggingEventMapper` using the `Instant` captured by Logback in the `ILoggingEvent`.

**Comment by jjoslet** [comment]
I've done a commit for this and I can make a PR if you want: https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/e0cfdc420de3a2c84efe6c640fd851cc58c243f6

**Comment by laurit** [comment]
A PR would be welcome. You may wish to check whether your handling of nanoseconds in the non instant case is correct. I suspect that you may need to truncate the time in millis to seconds and then add nanos.
