### ISSUE TITLE
Enhance AWS DynamoDB instrumentation with db.* attributes

### ISSUE THREAD

**Issue by kubawach** [open-telemetry/opentelemetry-java-instrumentation#1181]
Current implementation of AWS SDK instrumentation treats all types of requests (S3, SQS, Kinesis, DynamoDB) as network ones, setting net.* and http.* attributes. DynamoDB however is more of a DB kind. Therefore, in order to provide high quality tracing data, DynamoDB instrumentation should be enhanced to set db.* attributes (when appropriate). 

There is, however, one outstanding question - what should be done with network (net.*) and HTTP (http.*) attributes currently set also for DynamoDB requests? Shall we keep adding all of them or leave network only (as the call is done via network communication) ?

**Comment by anuraaga** [comment]
Thanks for bringing this up @kubawach. I think we should indeed also set `db.*` conventions for DynamoDB specifically to satisfy the OTel conventions - I guess we can set `db.name` to a table name for some calls (not batch calls I think though), and set db.operation to the same value as aws.operation. 

We should also set the HTTP attributes for any DB calls that use HTTP protocol, like dynamodb, I think it's for similar reasons as for why we include the network attributes too.

**Comment by iNikem** [comment]
Network attributes are generic, in the sense that spec allows applying them to any spans.

Initially I thought that we should _replace_ http convention with db one here. But the more I think about it, the more I change my opinion in favour of including both (three, if you count net as well).

**Comment by kubawach** [comment]
@anuraaga thanks for your comment. I agree with both db.name and db.operation. I also plan to implement db.statement for relevant requests. 
@iNikem agreed, will preserve existing http.* and net.* attributes.
