### ISSUE TITLE
opentelemetry-api-incubator version should be 1.40.0-alpha in opentelemetry-instrumentation-bom-alpha 2.5.0-alpha to work with opentelemetry-bom 1.40.0

### ISSUE THREAD

**Issue by yangli136** [open-telemetry/opentelemetry-java-instrumentation#11823]
### Describe the bug

opentelemetry-api is 1.40.0, but opentelemetry-api-incubator version is 1.39.0-alpha.

When a Spring Boot application starts, the following exception occurs:

![image](https://github.com/user-attachments/assets/39d2b4d3-914d-4b7e-942d-1f717bfccc05)

### Steps to reproduce

Create a Spring Boot application with the following dependencies:
  
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom</artifactId>
        <version>1.40.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.opentelemetry.instrumentation</groupId>
        <artifactId>opentelemetry-instrumentation-bom-alpha</artifactId>
        <version>2.5.0-alpha</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

### Expected behavior

Application starts successfully.

### Actual behavior

Application failed to start with exception:
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdk]: Factory method 'autoConfiguredOpenTelemetrySdk' threw exception with message: io/opentelemetry/api/incubator/trace/ExtendedTracer
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:177)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/api/incubator/trace/ExtendedTracer
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
...

### Javaagent or library instrumentation version

1.40.0

### Environment

**JDK**:
**OS**:

### Additional context

The following customized Maven dependency configuration fixed the exception problem:
 
  <dependency>
      <groupId>io.opentelemetry.instrumentation</groupId>
      <artifactId>opentelemetry-spring-boot-starter</artifactId>
      <exclusions>
        <exclusion>
          <groupId>io.opentelemetry</groupId>
          <artifactId>opentelemetry-api-incubator</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-api-incubator</artifactId>
      <version>1.40.0-alpha</version>
    </dependency>

**Comment by yangli136** [comment]
there are format issues in two sections above.

**Steps to reproduce**
Create a Spring Boot application with the following dependencies:

![image](https://github.com/user-attachments/assets/0107169f-0051-48ef-80d2-3cadb2f5f620)

Additional context
The following customized Maven dependency configuration fixed the exception problem:

![image](https://github.com/user-attachments/assets/31dba375-44c3-44e6-bf94-0a631cddee3f)

**Comment by trask** [comment]
hi @yangli136!

opentelemetry-instrumentation-bom 2.5.0 targets opentelemety-bom 1.39.0

opentelemetry-instrumentation-bom 2.6.0 will target opentelemety-bom 1.40.0

**Comment by yangli136** [comment]
I see. Thanks!
