### ISSUE TITLE
Suggest adding the tag '-Dotel.resource.attributes' to the indicators

### ISSUE THREAD

**Issue by zhaomingcheng01** [open-telemetry/opentelemetry-java-instrumentation#11870]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/6d279ee3-5b4c-4e5a-aad9-70d8e03ab2ce)
There are no labels for this part as shown in the figure below
![image](https://github.com/user-attachments/assets/fb6dff8d-d815-4809-9623-7ca6e7676813)

### Describe the solution you'd like

Suggest adding the tag '- Dotel.resome.attribles' to the indicators

**Comment by laurit** [comment]
If I understand this correctly the resource attributes that are added to prometheus export are determined with https://github.com/open-telemetry/opentelemetry-java/blob/468b5289564b45b7a07c5caee3972d2038dbc6ca/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/PrometheusHttpServer.java#L66 By default this predicate is null and resource attributes are not added. @jack-berg is this correct? How should it be configured?

**Comment by breedx-splk** [comment]
What is an "indicator" in this context? Some Prometheus thing?

**Comment by jack-berg** [comment]
> @jack-berg is this correct? How should it be configured?

Yes this is correct. This needs to be configured either programmatically with an extension and an [AutoConfigurationCustomizerProvider](https://opentelemetry.io/docs/languages/java/configuration/#autoconfigurationcustomizerprovider) implementation. Its also possible to configure via [declarative configuration](https://opentelemetry.io/docs/languages/java/configuration/#declarative-configuration) as demonstrated here: https://github.com/open-telemetry/opentelemetry-configuration/blob/cc623f7bf6bcf6363ee66f657f1f86cd568bb24f/examples/kitchen-sink.yaml#L96-L108

I think its safe to close this issue.
