### ISSUE TITLE
Should we bump 1.x minor versions when bumping SDK minor versions?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#11881]
Currently we are only bumping 1.x patch versions when bumping SDK minor versions, e.g. https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/11879

@brunobat recently reported a breaking change when updating 1.x patch versions. He didn't recall the exact breakage, but I suspect it may have been in an SDK incubator (alpha) artifact, which is ok to break in minor SDK version bumps, but not great to break in a patch update of Instrumentation (which bumps the minor SDK version in its bom).

**Comment by laurit** [comment]
With current release workflows it is much easier to do patch releases in 1.x series. We would need to resolve the automation issues if we want to bump minor version or instead of monthly 1.x releases switch to release on demand and hope that we don't need to release too often.

**Comment by jonatan-ivanov** [comment]
I think the two should follow the same versioning strategy. It is unexpected to:
- Get minor version upgrades when upgrading patch versions for any artifacts
- Get breaking changes (minor upgrades of `-alpha` artifacts can contain breaking changes) when upgrading patch versions
