### ISSUE TITLE
Kafka Instrumentation: Metrics Disabled Globally When Any Client Closed

### ISSUE THREAD

**Issue by kjschnei001** [open-telemetry/opentelemetry-java-instrumentation#11880]
### Describe the bug

Whenever a single kafka client is closed, kafka metrics instrumentation is disabled globally. In applications that have more than one client, this will stop metrics collection for the still-active clients.

### Steps to reproduce

In an application with opentelemetry kafka instrumentation enabled (either via auto-instrumentation or manual instrumentation). Create multiple kafka clients in a single applications. After both are running, close one of them.

### Expected behavior

Closing one kafka client should not stop metrics collection for all other clients.

### Actual behavior

Closing one kafka client disables metrics collection for all other clients. 

### Javaagent or library instrumentation version

2.6.0-alpha

### Environment

**JDK**: Temurin-17.0.2+8
**OS**: MacOS 14.4.1

### Additional context

This is an example stack trace showing how the [closeAllInstruments()](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e1ae8e375bcc9c37441b221f2eeb0f68d089bc1a/instrumentation/kafka/kafka-clients/kafka-clients-common/library/src/main/java/io/opentelemetry/instrumentation/kafka/internal/OpenTelemetryMetricsReporter.java#L131) gets invoked:

<img width="738" alt="image" src="https://github.com/user-attachments/assets/6fcdfa63-5494-4631-9fbe-cd74857b818d">

which results in the ceasing of all metrics collection, including producers even though in this instance a client was closed:
<img width="1109" alt="image" src="https://github.com/user-attachments/assets/f7b2b674-fbd3-4141-bdc0-c01732cca93e">

**Comment by EvanMerlock** [comment]
https://github.com/EvanMerlock/m/tree/main/bug-repros/otel-java-inst-11880

This is a simple reproducer. It runs a Kafka producer for 1 minute, then spawns 5 consumers which each have a random chance of closing which increases every time they consumes a message. This code also contains a full Prom stack that you can use to observe the data disappearing after the consumers start up.

**Comment by Cirilla-zmh** [comment]
It seems that the scope of instances of `io.opentelemetry.instrumentation.kafka.internal.OpenTelemetryMetricsReporter` was misunderstood by the designer. The instance's scope is the same as that of a Producer or Consumer. However, when any instance is closed, `closeAllInstruments()` is called.
Perhaps adding a field of type `RegisteredObservable` could solve this problem.
