### ISSUE TITLE
JdbcInstrumentationAutoConfiguration incorrectly fires when using "org.springframework.boot:spring-boot-starter-data-redis"

### ISSUE THREAD

**Issue by trajano** [open-telemetry/opentelemetry-java-instrumentation#11913]
### Describe the bug

I have a simple test app that doesn't use Spring Data JPA or anything with JDBC.  Adding the instrumentation fails

### Steps to reproduce

add  the following dependencies on a simple webflux app

org.springframework.boot:spring-boot-starter-webflux
org.springframework.boot:spring-boot-starter-data-redis
org.springframework.session:spring-session-data-redis

along with

 implementation(platform("io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom:2.6.0"))
 implementation("io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter")

### Expected behavior

everything works

### Actual behavior

"java.lang.IllegalStateException: Error processing condition on io.opentelemetry.instrumentation.spring.autoconfigure.internal.instrumentation.jdbc.JdbcInstrumentationAutoConfiguratiom"

### Javaagent or library instrumentation version

2.6.0

### Environment

**JDK**:
**OS**:

**Comment by trajano** [comment]
https://github.com/trajano/simple-auth shows the error

**Comment by trajano** [comment]
Found the error I think you should remove the "platform" support for gradle in the documentation.  That's what I did first, but Spring Boot starter always uses the dependency-management.

**Comment by trask** [comment]
> Found the error I think you should remove the "platform" support for gradle in the documentation. That's what I did first, but Spring Boot starter always uses the dependency-management.

re-opening to see if there's something to improve in the docs

cc @jeanbisutti @zeitlinger
