### ISSUE TITLE
Ktor 3.X support

### ISSUE THREAD

**Issue by FunkyMuse** [open-telemetry/opentelemetry-java-instrumentation#11933]
### Is your feature request related to a problem? Please describe.

At the moment the Ktor 3.X open telemetry is not supported and the 2.0 support just doesn't work with Ktor 3.0

### Describe the solution you'd like

It would be awesome to support Ktor open telemetry with target at ktor 3.X, even if it's in Beta 02 the compatibility with Kotlin 2.0 have already landed

### Describe alternatives you've considered

None, as the migration to something else other than open telemetry doesn't make it feasible for us to do so.

**Comment by trask** [comment]
cc @marychatte

**Comment by FunkyMuse** [comment]
Maybe create a PR if not added by open telemetry

**Comment by acunap** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10873

**Comment by FunkyMuse** [comment]
> #10873 done few months ago but it's not merged yet

why did you delete the PR? :/

**Comment by acunap** [comment]
> > #10873 done few months ago but it's not merged yet
> 
> why did you delete the PR? :/

Tbh I was cleaning my repos and I accidentally deleted it 😆 In any case I don't think it was going to be merged and better to wait for Ktor's official solution.

**Comment by FunkyMuse** [comment]
Ktor 3.0.0 is released

**Comment by steverao** [comment]
> Ktor 3.0.0 is released

Yes, we noticed it. [We'd welcome a contribution for this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/ISSUES.md#contribution-welcome).

**Comment by FunkyMuse** [comment]
> > Ktor 3.0.0 is released
> 
> Yes, we noticed it. [We'd welcome a contribution for this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/ISSUES.md#contribution-welcome).

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12453

**Comment by inakov** [comment]
Hey, guys is there any update on this ticket? Support from open telemetry is the only thing that block us for migrations to ktor 3. Do you have any ideas what have left and when we can expect this?

**Comment by FunkyMuse** [comment]
Support has been released with their latest alpha release, I've already integrated otel and running jaeger in prod.
