### ISSUE TITLE
TRACER or tracer()

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1195]
We currently have a pattern of using a public static final constant for an instrumentation tracer. We could provide a static method instead

Pros

- More inline with JDK which stopped using the pattern of public constants I believe

- Less all-caps yelling in code

Cons

- Annoying to write an accessor in addition to a private constant. When using enum singleton pattern generally requires an inner enum class

- More characters at call site (parens).

While I tend to be more used to accessor method pattern, writing this out not sure it's all that much better but worth a small thought 😅

**Comment by iNikem** [comment]
@anuraaga it seems that there is little interest in this task. Which for me means "do whatever you like" and concludes this "discussion" :) Thus I propose to close this task and if you wish to replace `TRACER` with `tracer()` then go ahead and make a PR. WDYT?

**Comment by anuraaga** [comment]
If it's all it took to do things in otel-java*, I'd just send PRs to rewrite everything :-) I don't know the right way to get consensus on anything in this world TBH - I assume it's just what happens when you're in APAC, something I'm quite used to.

**Comment by trask** [comment]
I don't believe Tracer is deeply immutable, so these fields are not "constants", and should not be all upper case, according to style guide we reference in CONTRIBUTING:

https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names

> I assume it's just what happens when you're in APAC, something I'm quite used to.

@anuraaga can you help me understand this comment better? I had hoped that the two meetings a week at APAC-friendly times would address this problem, but I'm sure it's a more complex issue than just that.

**Comment by anuraaga** [comment]
@trask The APAC timed meetings feel sort of secondary, usually missing key stakeholders making it hard to make decisions from what I've noticed. I wonder if there is in general too much discussion in SIG meetings as opposed to just offline

**Comment by trask** [comment]
> @trask The APAC timed meetings feel sort of secondary, usually missing key stakeholders making it hard to make decisions from what I've noticed. I wonder if there is in general too much discussion in SIG meetings as opposed to just offline

@anuraaga don't the APAC meetings always have quorum (2-3 out of 3 active maintainers) for decision making?

**Comment by anuraaga** [comment]
@trask It's still possible to have a decision blocked later by a non-present member though. Also when it's related to a spec change, there can be additional stakeholder dependencies that are hard to deal with in APAC where the biweekly spec meeting is very much a secondary session.

**Comment by trask** [comment]
> It's still possible to have a decision blocked later by a non-present member though

@anuraaga Is this a real or a theoretical problem? I don't think @iNikem has blocked any of the decisions we have made when he is not present (though for sure he has the right to, as do you for any decision made when you are not present).

**Comment by trask** [comment]
Just trying to better understand the problems you are facing in this repository, so you me and @iNikem can work toward improving the situation

**Comment by anuraaga** [comment]
@trask Thanks! I am definitely conflating issues from the other Java repo - there is a general sense of loneliness being in APAC and working on OTel, but that's unavoidable given the huge skew of the crowd I guess. I don't have any particular AIs for us, but the loneliness will probably continue to hurt my head a bit 😅

**Comment by trask** [comment]
They have an OTel API `Tracer`, which has `TracerSharedState`, which is mutable
