### ISSUE TITLE
Whether labels can be formatted uniformly

### ISSUE THREAD

**Issue by zhaomingcheng01** [open-telemetry/opentelemetry-java-instrumentation#12021]
### Is your feature request related to a problem? Please describe.

At present, there is no uniform specification for link log labels in all middleware. For example, link log labels are _ or. For example, mysql_sql is the same as the client in different languages of a middleware, and do not have inconsistent labels for clients in different languages, such as go_mysql_sql for go and java_mysql_sql for java. There is a unified standard. Easy aggregation when using the prometheus ql query language

### Describe the solution you'd like

There is a uniform tag naming convention, the same middleware tag for clients in different languages, and the same delimiter for the link log profiling tag, such as _ or.

**Comment by zhaomingcheng01** [comment]
It also provides a clear documentation of which middleware has which tags

**Comment by laurit** [comment]
I'm not completely clear on what the ask is here. As far as I understand is that you are pointing out that either attribute keys or values use either `.` or `_` as separator. If that is the case have a look at https://github.com/open-telemetry/semantic-conventions as this is where these attributes are define and also where the guidelines on naming things should be.
