### ISSUE TITLE
semconv-incubating is missing from instrumentation-bom-alpha

### ISSUE THREAD

**Issue by rdicroce** [open-telemetry/opentelemetry-java-instrumentation#12020]
**Describe the bug**
`opentelemetry-semconv-incubating` is missing from `opentelemetry-instrumentation-bom-alpha`.

**Steps to reproduce**
Look at the BOM.

**What did you expect to see?**
`opentelemetry-semconv-incubating` should be in the BOM alongside `opentelemetry-semconv`.

**What did you see instead?**
`opentelemetry-semconv-incubating` is not present.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-instrumentation-bom-alpha`
Version: 2.6.0-alpha
How did you reference these artifacts?
```
			<dependency>
				<groupId>io.opentelemetry.instrumentation</groupId>
				<artifactId>opentelemetry-instrumentation-bom-alpha</artifactId>
				<version>2.6.0-alpha</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
```

**Environment**
Irrelevant.

**Additional context**
None

**Comment by laurit** [comment]
This is a deliberate choice. Our published artifacts don't depend on `opentelemetry-semconv-incubating` to avoid issues when there are breaking changes.

**Comment by rdicroce** [comment]
bom-alpha already contains a bunch of other alpha artifacts that can have breaking changes. Why is semconv-incubating special?

**Comment by trask** [comment]
hi @rdicroce! check out the note about semconv-incubating at https://github.com/open-telemetry/semantic-conventions-java#published-releases

> Libraries can use this for testing, but should make copies of the attributes to avoid possible runtime errors from version conflicts.

**Comment by rdicroce** [comment]
I'm not making a library, I'm making an application. And IMO telling people to copy source code like that is a bad idea. If a developer copies code into their own repo, and then the attribute gets changed/removed, the developer will have no idea. If the developer instead references semconv-incubating, then at least they'll get a compile error to tell them they need to look at something.

**Comment by laurit** [comment]
> I'm not making a library, I'm making an application. And IMO telling people to copy source code like that is a bad idea. If a developer copies code into their own repo, and then the attribute gets changed/removed, the developer will have no idea. If the developer instead references semconv-incubating, then at least they'll get a compile error to tell them they need to look at something.

You are misunderstanding. These guidelines are for library authors in your own application you can do whatever you want to do.

**Comment by SylvainJuge** [comment]
As @laurit said above, there are two distinct use-cases:

If you are publishing a library that will be reused by someone else, then relying on incubating artifact can introduce un-resolvable conflicts for the consumers of this library.
In this case the recommended approach is to duplicate the attributes definitions, but it is still recommended to have the test code that relies on incubating definitions to ensure they still match the incubating attributes. For example with the `span-stacktraces` module, the un-stable `code.stacktrace` attribute is used, and the incubating definitions are only included [for testing](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/span-stacktrace/build.gradle.kts).

If you are building an application, then you have to opt-in for this incubating dependency and you are willing to accept that those will likely break or change in the future.

**Comment by rdicroce** [comment]
I am developing an application, and I accept that things may break. I shouldn't have brought up the point about copying the attributes. That has muddied this discussion. So let me try to get it back on track.

The point of a BOM is to ensure that versioning is aligned across multiple dependencies. Deliberately omitting artifacts from the BOM defeats the purpose of having a BOM. It leads to the inverse possibility of what @SylvainJuge described. `opentelemetry-semconv-incubating` depends on `opentelemetry-semconv`. If someone uses the BOM but then also has to add `opentelemetry-semconv-incubating` separately, then the BOM will override the version of `opentelemetry-semconv`. Depending on what has changed in `opentelemetry-semconv`, this may break `opentelemetry-semconv-incubating`. Thus, I am asking for `opentelemetry-semconv-incubating` to be added to the BOM to prevent this situation and ensure that the versioning of all artifacts stays aligned.

**Comment by trask** [comment]
I think it would be ok to include `opentelemetry-semconv-incubating` in `opentelemetry-instrumentation-bom-alpha`.

People are already opting in to `alpha` artifacts by adding the `opentelemetry-instrumentation-bom-alpha`.

I think we discussed this in recent Java SIG meeting, for some reason I think it may have been raised by @jack-berg?

**Comment by SylvainJuge** [comment]
Another benefit of adding the incubating semconv in the instrumentation BOM for distributions is that we can get the same incubating semconv version as the upstream distribution, whereas for now we have to explicitly take care of this dependency in every distribution.
