### ISSUE TITLE
Gradle caching action isn't nice to GitHub?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1205]
I see this sort of throttling a lot in our builds

```
Error: commitCache failed: ﻿{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace ''.","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}
    at /home/runner/work/_actions/burrunan/gradle-cache-action/v1.4/dist/cache-action-entrypoint.js:15662:11
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/burrunan/gradle-cache-action/v1.4/dist/cache-action-entrypoint.js:15615:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

Presumably such throttling also slows down our builds - perhaps the action is doing too fine-grained requests to GitHub?

**Comment by vlsi** [comment]
:(

The workaround could be `remote-build-cache-proxy-enabled: false` for `gradle-cache-action`.
That would result in saving full `build-cache` folder contents.

There's `save-local-build-cache: false` option as well.

**Comment by anuraaga** [comment]
Thanks for the input! My guess is it's safe to disable the remote cache since we have s3 remote cache anyways (thanks to your great help there too :) ). @iNikem what do you think?

**Comment by vlsi** [comment]
s3 would not work that well for PRs.

I guess one more option might be to try "fetch from S3 first" approach (there's no configuration option for that yet :-/ ).

**Comment by iNikem** [comment]
> s3 would not work that well for PRs since you don't want to enable push to S3 from PR builds.

But PRs will still be able to reuse task's S3 cache from nightly build, right?

**Comment by vlsi** [comment]
>But PRs will still be able to reuse task's S3 cache from nightly build, right?

That's right. It will reuse S3 cache.

**Comment by iNikem** [comment]
Fixed by recent changes
