### ISSUE TITLE
Wrong db info while using shardingsphere 5.x

### ISSUE THREAD

**Issue by 123liuziming** [open-telemetry/opentelemetry-java-instrumentation#12065]
### Describe the bug

similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8109, but our `JdbcIgnoredTypesConfigurer` only support to ignore `org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.` which is not exists in shardingsphere 5.x

### Steps to reproduce

similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8109

### Expected behavior

similar to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8109

### Actual behavior

Get the actual database info

### Javaagent or library instrumentation version

main branch

### Environment

**JDK**:
**OS**:

**Comment by trask** [comment]
Resolved by #12066
