### ISSUE TITLE
Javaagent throwing debug logs in the error when exporting traces

### ISSUE THREAD

**Issue by sarkisjad** [open-telemetry/opentelemetry-java-instrumentation#12063]
### Describe the bug

Kindly find attached the stack trace. As you can see, there are logs that usually either debug logs but they are shown as error logs
[staacktrace.txt](https://github.com/user-attachments/files/16665625/staacktrace.txt)

### Steps to reproduce

Here are the parameters used to enable exporter tracing:

```
-javaagent:opentelemetry-javaagent.jar 
-Dotel.logs.exporter=none"
-Dotel.metrics.exporter=none"
-Dotel.instrumentation.common.default-enabled=false"
-Dotel.java.enabled.resource.providers=my.own.ResourceProvider"
-Dotel.javaagent.logging=application"
-Dotel.javaagent.extensions=my/own/extension.jar"
-Dotel.traces.exporter=otlp"
-Dotel.exporter.otlp.endpoint=http://localhost:8080/"
-Dotel.instrumentation.opentelemetry-api.enabled=true"
-Dotel.instrumentation.http-url-connection.enabled=true"
-Dotel.instrumentation.tomcat.enabled=true"
-Dotel.instrumentation.apache-httpclient.enabled=true"
```

### Expected behavior

These logs should not be in ERROR mode

### Actual behavior

They should be in DEBUG mode

### Javaagent or library instrumentation version

v2.6.0

**Comment by jaydeluca** [comment]
hello @sarkisjad, I am not seeing this behavior when I run the agent. Could you please provide a sample repo that reproduces this problem?

**Comment by laurit** [comment]
By default the java agent writes logs to `System.err`. You are using something that replaces the default `System.err` with a custom implementation that prefixes everything with `2024-08-09 15:02:02 ERROR [Thread-0] console -`. It is possible to configure the agent to log to a file or `System.out` instead. Perhaps that would help you.

**Comment by sarkisjad** [comment]
> By default the java agent writes logs to `System.err`. You are using something that replaces the default `System.err` with a custom implementation that prefixes everything with `2024-08-09 15:02:02 ERROR [Thread-0] console -`. It is possible to configure the agent to log to a file or `System.out` instead. Perhaps that would help you.

Thank you for your response. 
Do you have an idea how to change that custom implementation? 

Regards!

**Comment by laurit** [comment]
Internally the java agent uses slf4j-simple for logging. Have a look at https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html Due to shading the prefix for system properties is `io.opentelemetry.javaagent.slf4j.simpleLogger` instead of `org.slf4j.simpleLogger`

**Comment by sarkisjad** [comment]
Their is something I don't quite understand. The logs I showed you seem to be very verbose. As if I activated `-Dotel.javaagent.debug=true` when all I did was add `-Dotel.javaagent.logging=application`. 
Is that an expected behavior?

**Comment by laurit** [comment]
> As if I activated `-Dotel.javaagent.debug=true` when all I did was add `-Dotel.javaagent.logging=application`.
> Is that an expected behavior?

Oh, I didn't notice that. Have a look at https://opentelemetry.io/docs/zero-code/java/agent/configuration/#java-agent-logging-output 

> The agent will attempt to redirect its own logs to the instrumented application's slf4j logger. This works the best for simple one-jar applications that do not use multiple classloaders; Spring Boot apps are supported as well.

`-Dotel.javaagent.logging=application` means that agent logs will be redirected to your application logs. It will include debug level output from the agent, your should configure your application logger to only output the messages at the desired level. Now for this to work agent relies on instrumentation, but you are running with `-Dotel.instrumentation.common.default-enabled=false` that disables the instrumentation. Also as described in the documentation this works only when your application uses slf4j. If the agent logging is displayed on application shutdown then it comes from https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/98bf18370c2c81f1c76d1031f452b2da52776ff4/javaagent-internal-logging-application/src/main/java/io/opentelemetry/javaagent/logging/application/ApplicationLoggingCustomizer.java#L29

**Comment by sarkisjad** [comment]
So if my application is not using slf4j or an implementation of it, then the agent logs (which are redirected to my app logs) will be thrown to the error stream by default?

**Comment by laurit** [comment]
> So if my application is not using slf4j or an implementation of it, then the agent logs (which are redirected to my app logs) will be thrown to the error stream by default?

Not really. Small amount of logging output is buffered until application logger becomes available for consuming agent logs. If application logger does not become available this buffered output is dumped to stderr on application shutdown.

> And if I want to change the log level, I need to set -Dotel.instrumentation.common.default-enabled to true?

Not really. If you want logging through application logger to work you need to not disable the instrumentation that is responsible for this. To change the level visible in application logs configure your logging framework as you'd usually do.

> Also, you mentioned above that we can configure the agent to log to a file. Do you know how I can do that?

As described above agent uses slf4j-simple for logging. Consult https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html for available system properties. Prefix for system properties is `io.opentelemetry.javaagent.slf4j.simpleLogger` instead of `org.slf4j.simpleLogger`.
