### ISSUE TITLE
Smoke test for Logback MDC instrumentation

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1209]
The logback instrumentation is fragile (#1201) because logback depends on slf4j which we shade during our build, and our normal tests don't currently catch shading issues.

We are hoping to change how we run tests post-GA, so that they run using a real (and shaded) javaagent, which would catch these issues.

For now though, it maybe worth adding a smoke test to make sure this doesn't accidentally break again without us knowing about it.

**Comment by mateuszrzeszutek** [comment]
Can you assign this one to me?
