### ISSUE TITLE
BASE2_EXPONENTIAL_BUCKET_HISTOGRAM

### ISSUE THREAD

**Issue by chameleon82** [open-telemetry/opentelemetry-java-instrumentation#12110]
### Describe the bug

I have configured [base2 exponential histogram](https://opentelemetry.io/docs/specs/otel/metrics/sdk_exporters/otlp/#additional-environment-variable-configuration) when run application with opentelemetry-java-agent

but still see my desired metric [http.server.request.duration](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration) still exported with explicit bucket boundaries. Is it intentional? 

I'm looking to export all histogram metrics as base2exponential metrics

### Steps to reproduce

configure env:
```
OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION=base2_exponential_bucket_histogram
```

or java property

```
-Dotel.exporter.otlp.metrics.default.histogram.aggregation=base2_exponential_bucket_histogram
```

### Expected behavior

All histogram metrics exported with base2 exponential buckets

### Actual behavior

agent configuration didn't affect [http.server.request.duration](https://opentelemetry.io/docs/specs/semconv/http/http-metrics/#metric-httpserverrequestduration) metric

### Javaagent or library instrumentation version

v1.35.0, v1.41.0

### Environment

**JDK**: Temurin 17
**OS**: Ubuntu 20.04

### Additional context

application run with opentelemetry-java-agent

**Comment by laurit** [comment]
I think this happens because the agent configures explicit bucket boundaries for the `http.server.request.duration` histogram. I would try using a metrics view https://github.com/open-telemetry/opentelemetry-java/tree/v1.39.0/sdk-extensions/incubator#view-file-configuration

**Comment by chameleon82** [comment]
My intention is to apply `base2_exponential_bucket_histogram` on all histograms, including `http.server.request.duration` and others with explicit bucket boundaries. 

I would prefer to avoid to create views for this case.

**Comment by trask** [comment]
@jack-berg wdyt? can/should `base2_exponential_bucket_histogram` override explicit buckets? otherwise `base2_exponential_bucket_histogram` doesn't have much effect since the default buckets aren't much recommended anymore

**Comment by chameleon82** [comment]
I've checked by collector and confirm - I can see `exponential/delta` 

I got confused when I have configured logging exporter for it with `OTEL_METRICS_EXPORTER=logging`( same with `console` and `logging-otlp` )

```
[otel.javaagent 2024-08-27 12:35:54:636 +0700] [PeriodicMetricReader-1] INFO io.opentelemetry.exporter.logging.LoggingMetricExporter - metric: 
ImmutableMetricData{
  resource=Resource{
     schemaUrl=https://opentelemetry.io/schemas/1.24.0, 
     ...
  }, 
  instrumentationScopeInfo=InstrumentationScopeInfo{
      name=io.opentelemetry.netty-4.1, 
      version=2.7.0-alpha, 
  }, 
  name=http.server.request.duration, 
  description=Duration of HTTP server requests.,
  type=HISTOGRAM, 
  data=ImmutableHistogramData{
    aggregationTemporality=CUMULATIVE, 
    points=[
      ImmutableHistogramPointData{
        getStartEpochNanos=1724736834590628000, 
        getEpochNanos=1724736954597064000, 
        getAttributes={
           http.request.method="GET", 
           http.response.status_code=200, 
           http.route="/health/ready", 
           network.protocol.version="1.1", 
           url.scheme="http"
        }, 
        getBoundaries=[0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10.0], 
        getCounts=[7, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], 
      }
   ]
 }
...
```

I suspect otlp exporter and loggers have different implementation and aggregation temporality selector is not implemented on loggers. This seems incorrect to me as I don't see same picture as when I use otlp exporter

**Comment by jack-berg** [comment]
> I got confused when I have configured logging exporter for it with OTEL_METRICS_EXPORTER=logging( same with console and logging-otlp )

That's correct - I experienced the same confusion myself! Unfortunately, the `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION` option only applies to the OTLP exporter and there is no equivalent for logging / logging-otlp exporters. We could extend logging / logging-otlp exporters to have programmatic config options to specify the default histogram aggregation, but new env vars would have to be added to the spec.
