### ISSUE TITLE
Allow vendor distribution to provide default configuration

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1213]
Part of #566

As part of Splunk distribution of OpenTelemetry Java instrumentation we want to provide default values for some configuration options. Currently configuration can be provided in 3 ways:

- Env variable
- System property
- Via configuration file

Vendor distro has to provide default value only if none of the above provides it. As `Config` instance cannot be changed (setting reflection aside), the only way vendor can provide defaults now is to check all three of the above and, if value is not found, set e.g. system property. And to be careful to do all that before Config class has a chance to load. This is cumbersome.

Probably the most consistent way to provide better experience is to introduce yet another SPI ( :) ) for additional configuration sources. The order then should be "system properties -> environment -> config file -> SPI -> default values".

**Comment by anuraaga** [comment]
SPI++

**Comment by mateuszrzeszutek** [comment]
Can you assign this ticket to me?

**Comment by jkwatson** [comment]
Is this something that belongs in the core SDK?

**Comment by iNikem** [comment]
I am not sure. With manual instrumentation you can always configure stuff to your liking, no?

**Comment by jkwatson** [comment]
> I am not sure. With manual instrumentation you can always configure stuff to your liking, no?

For sure. And, I'm happy with this starting in the auto-instrumentation project, and later migrating it to the core SDK if it seems to be more generally useful. Just wanted to make sure we'd thought about it. :)

**Comment by iNikem** [comment]
Honestly, I haven't :) But I will tomorrow, when my brain is fresh

**Comment by iNikem** [comment]
At last I had chance to think about it and yes, let us do it in instrumentation repo now.
