### ISSUE TITLE
logback-mdc will print ? instead of the actual class and method name

### ISSUE THREAD

**Issue by jerrylincs** [open-telemetry/opentelemetry-java-instrumentation#12198]
### Describe the bug

My Springboot application  include opentelemetry-logback-mdc-1.0 module。 I modify the logback-spring.xml as 
 
  <appender name="OTEL" class="io.opentelemetry.instrumentation.logback.mdc.v1_0.OpenTelemetryAppender">
    <appender-ref ref="myCONSOLE"/>
  </appender>

Then I find it will print ? instead of the actual class and method name. I find this code in OpenTelemetryAppender.java：
ILoggingEvent wrappedEvent =
        (ILoggingEvent)
            Proxy.newProxyInstance(
                ILoggingEvent.class.getClassLoader(),
                new Class<?>[] {ILoggingEvent.class},
                (proxy, method, args) -> {
                  if ("getMDCPropertyMap".equals(method.getName())) {
                    return eventContextMap;
                  } else if ("getLoggerContextVO".equals(method.getName())) {
                    return vo;
                  }
                  try {
                    return method.invoke(event, args);
                  } catch (InvocationTargetException exception) {
                    throw exception.getCause();
                  }
                });
    // https://github.com/qos-ch/logback/blob/9e833ec858953a2296afdc3292f8542fc08f2a45/logback-classic/src/main/java/ch/qos/logback/classic/net/LoggingEventPreSerializationTransformer.java#L29
    // LoggingEventPreSerializationTransformer accepts only subclasses of LoggingEvent and
    // LoggingEventVO, here we transform our wrapped event into a LoggingEventVO
    return LoggingEventVO.build(wrappedEvent);

The getCallerData method in LoggingEventVO is different from the same method in LoggingEvent. This result in getting '?' rather than  the actual class and method name. 

### Steps to reproduce

just 
 
  <appender name="OTEL" class="io.opentelemetry.instrumentation.logback.mdc.v1_0.OpenTelemetryAppender">
    <appender-ref ref="myCONSOLE"/>
  </appender>

### Expected behavior

print  the actual class and method name

### Actual behavior

print  ?

### Javaagent or library instrumentation version

opentelemetry-logback-mdc-1.0    version 	2.7.0-alpha

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
>  I modify the logback-spring.xml as

You forgot to include how exactly you modified it.

**Comment by jerrylincs** [comment]
> > I modify the logback-spring.xml as
> 
> You forgot to include how exactly you modified it.
just add as readme.md described
  
  <appender name="OTEL" class="io.opentelemetry.instrumentation.logback.mdc.v1_0.OpenTelemetryAppender">
    <appender-ref ref="MyCONSOLE"/>
  </appender>
