### ISSUE TITLE
support trace sub thread

### ISSUE THREAD

**Issue by sheiy** [open-telemetry/opentelemetry-java-instrumentation#12202]
### Is your feature request related to a problem? Please describe.

<img width="1163" alt="image" src="https://github.com/user-attachments/assets/f89d7a9d-252f-4f84-8793-e18c7c971a50">

### Describe the solution you'd like

I want the subthread or submit to the thread pool's task has the same traceid but  spanid is different

**Comment by laurit** [comment]
With agent this works for some standard executor implementations, for others you'll have to do the context propagation manually. If you wish to have some take a look you'll have to provide a minimal sample app that illustrates what you are doing or at least sample code.

**Comment by sheiy** [comment]
<img width="688" alt="image" src="https://github.com/user-attachments/assets/c2d4f098-1f9a-4f9b-98b6-81f06c12ea14">

**Comment by laurit** [comment]
There is already an issue for that, https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2527 You could work around this by wrapping the runnable with https://github.com/open-telemetry/opentelemetry-java/blob/a55e9b6440057fb50db9908ec072086a7a4b3c95/context/src/main/java/io/opentelemetry/context/Context.java#L209 or using one of the standard executors.
