### ISSUE TITLE
AWS  SDK request id is using `aws.requestId` instead of `aws.request_id` defined in semantic conventions

### ISSUE THREAD

**Issue by pingleig** [open-telemetry/opentelemetry-java-instrumentation#12311]
### Describe the bug

In semantic convention registry, the attribute name for request id is [aws.request_id](https://opentelemetry.io/docs/specs/semconv/attributes-registry/aws/#general-aws-attributes) [schema](https://github.com/open-telemetry/semantic-conventions/blob/main/model/aws/registry.yaml#L8), while the SDK generated spans are using `aws.requestId` 

Both v1 and v2 SDK are using `aws.requestId`

- V1 defined the attribute name in [AwsExperimentalAttributes](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/aws-sdk/aws-sdk-1.11/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v1_11/AwsExperimentalAttributes.java#L20) and used in [AwsSdlExperimentalAtributesExtractor](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/aws-sdk/aws-sdk-1.11/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v1_11/AwsSdkExperimentalAttributesExtractor.java#L66)
- V2 hard code the attribute name in [TracingExecutionInterceptor](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blame/main/instrumentation/aws-sdk/aws-sdk-2.2/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v2_2/TracingExecutionInterceptor.java#L365)

Permlinks

v1

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/0c22a8e0c64cddbcb404a6159ee397b765481654/instrumentation/aws-sdk/aws-sdk-1.11/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v1_11/AwsExperimentalAttributes.java#L20

v2

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/0c22a8e0c64cddbcb404a6159ee397b765481654/instrumentation/aws-sdk/aws-sdk-2.2/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v2_2/TracingExecutionInterceptor.java#L365

### Steps to reproduce

N/A the attribute names are defined in code. Though I found this while using Application Signal's SDK on EKS calling S3 https://github.com/aws-observability/aws-otel-java-instrumentation/issues/894

### Expected behavior

 `aws.request_id` in snake_case

### Actual behavior

`aws.requestId` in camelCase

### Javaagent or library instrumentation version

N/A

### Environment

N/A

**Comment by jaydeluca** [comment]
hey @pingleig, thanks for reporting this. We would welcome a contribution for this. Are you interested in contributing it? If not, I can look into it
