### ISSUE TITLE
opentelemetry-javaagent-all.jar is missing from releases

### ISSUE THREAD

**Issue by johnvlittle** [open-telemetry/opentelemetry-java-instrumentation#12338]
### Describe the bug

opentelemetry-javaagent.jar is missing exporters, so cant be used with jaeger etc. It only works with OTLP.

There are many articles how to connect opentel java agent with jaeger, but they all require opentelemetry-javaagent-all.jar.

Articles say this is how to download it:

 curl -LJO https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent-all.jar

But unfortunately, its missing!

Also,  https://opentelemetry.io/docs/languages/java/ is missing a "exporter" tab, all the other languages have an exporter tab which list out where to find them.  This makes finding opentelmetery java exporters (e.g. for jaeger) very difficult.

We need it.

Jaeger apparently supports OTLP, but there exists no information or guide to getting it working with the java agent, so need the exporter.

### Steps to reproduce

 curl -LJO https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent-all.jar

### Expected behavior

downloads opentelemetry-javaagent-all.jar

### Actual behavior

gives 404

### Javaagent or library instrumentation version

latest

### Environment

**JDK**:
**OS**:
n/a

### Additional context

n/a

**Comment by trask** [comment]
hi @johnvlittle! `opentelemetry-javaagent-all` was removed a while ago and all the exporters are now included in `opentelemetry-javaagent` (https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4106)

**Comment by laurit** [comment]
Jaeger has deprecated its own protocol and recommends using OTLP. Jaeger exporter was removed from https://github.com/open-telemetry/opentelemetry-java and also from the agent.

**Comment by nutmix** [comment]
Fair enough, but have spent days trying to get the jaeger to work with OTLP and it just doesnt work.  The old exporter at least is well documented with working exmaples.
