### ISSUE TITLE
How to avoid some traces created by Kafka-connect

### ISSUE THREAD

**Issue by jiten686** [open-telemetry/opentelemetry-java-instrumentation#12366]
### Describe the bug

I have integrate the Kafka-Connect with Openetelemtry java agent but I am seeing too many traces are generated continuously,
How to avoid the theses traces. 

 
![Screenshot 2024-09-30 191352](https://github.com/user-attachments/assets/bbf5f2b2-adf0-40cb-8bf0-54d32da9996d)
![Screenshot 2024-09-30 191608](https://github.com/user-attachments/assets/7ba8e30a-c7e7-43cc-a26e-8de06752af52)

### Steps to reproduce

Use Opentelemetry JavaAgent 2.6.0.
Integrate with kafka-connect

### Expected behavior

Unwanted traces should not generated continuously

### Actual behavior

 So many traces are generated continuously

### Javaagent or library instrumentation version

Opentelemetry JavaAgent 2.6.0.

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
You could disable the mongo instrumentation if you don't want spans from it. Or you could build a sampler that does not sample these spans.

**Comment by jiten686** [comment]
I have set OTEL_INSTRUMENTATION_MONGO_ENABLED = false and now traces are sends continuously for internal db operation. 
Thanks @laurit.
