### ISSUE TITLE
Fix unrolled tests with duplicate test names

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1237]
e.g.

```
./gradlew :instrumentation:netty:netty-4.1:test -PtestLatestDeps=true

...

> Task :instrumentation:netty:netty-4.1:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':instrumentation:netty:netty-4.1:test'.
> Received a failure event for test with unknown id '20.14'.
    Registered test ids: '[:instrumentation:netty:netty-4.1:test, 20.1, 20.2]'
```

similar failure with `netty-4.0`

some other modules seem to work, e.g. `okhttp-3.0`

**Comment by iNikem** [comment]
This issue is not specific for testLatestDep. This happen sporadically when spock test has a data table which, when unrolled, results in several test invocations having the exact same test name.

**Comment by trask** [comment]
Closing, these are addressed as we run across them:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pulls?q=is%3Apr+unroll+is%3Aclosed

not sure how to do anything better.
