### ISSUE TITLE
Context not propagated for autoinstrumented lambda

### ISSUE THREAD

**Issue by cleverchuk** [open-telemetry/opentelemetry-java-instrumentation#12422]
### Describe the bug

When a Lambda that's triggered by API Gateway is auto-instrumented, context is not propagated.

### Steps to reproduce

- Create a Lambda with API Gateway as trigger
- Auto-instrument with Java agent Lambda layer
- Use a HTTP client from an instrumented service to make a http request to the Lambda's `API Gateway` endpoint

### Expected behavior

A trace with both service and Lambda spans.

### Actual behavior

Two traces one for the service and one for the lambda

### Javaagent or library instrumentation version

2.8.0

### Environment

**JDK**: 17
**OS**: Linux

### Additional context

This [line](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/b14f1fe929e7d2369cf67deea162831ec88ef522/instrumentation/aws-lambda/aws-lambda-core-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/awslambdacore/v1_0/AwsLambdaRequestHandlerInstrumentation.java#L61) seems to be the issue because it doesn't extract context and uses empty map instead.

**Comment by cleverchuk** [comment]
@tylerbenson

**Comment by cleverchuk** [comment]
please assign to me

**Comment by laurit** [comment]
Resolved with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12440
