### ISSUE TITLE
span name is not better with Java filter use

### ISSUE THREAD

**Issue by LifaPeng** [open-telemetry/opentelemetry-java-instrumentation#12427]
### Describe the bug

<img width="1047" alt="image" src="https://github.com/user-attachments/assets/84be370d-a30a-4e07-9abf-bec212f17954">

The server receives requests for /test/otle and processes them in a Java filter with `registration.addUrlPatterns("/test/*")`. 

However, due to the initial route being null, the method `HttpServerRoute.isBetterRoute(httpRouteState, route)` always returns true, triggering the subsequent call to `updateSpanName(serverSpan, httpRouteState, route)`, which updates the span name to /test/*.

### Steps to reproduce

The server receives requests for /test/otle and processes them in a Java filter with `registration.addUrlPatterns("/test/*")`. 
The Java filter returns directly without executing `chain.doFilter(request, response)`.

### Expected behavior

In this case, `/test/otle `is longer than `/test/*`, and it is expected to use `/test/otle` as the final span name.

### Actual behavior

now is `/test/*`

### Javaagent or library instrumentation version

2.5.0+

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
> In this case, /test/otle is longer than /test/*, and it is expected to use /test/otle as the final span name.

https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name states that request URI path may not be used for span name because it could have high cardinality. We use the path where servlet or filter that service the request is mapped as this is guaranteed to have low cardinality. If needed you can manually set a better route/span name.

**Comment by LifaPeng** [comment]
When not using a Java filter, the URL seems to be used as the span name. Is there a way to obtain the current span name during the execution of isBetterRoute to compare it with the route? 
Alternatively, how can a better route/span name be set without modifying the program code?

**Comment by trask** [comment]
> Alternatively, how can a better route/span name be set without modifying the program code?

you could write a Java agent extension and wrap the exporter to update the span name based on the span attributes (e.g. using `url.path`)

**Comment by LifaPeng** [comment]
Is there an example or practical documentation that can guide us? Thank you.

**Comment by trask** [comment]
sorry, I should have included the link, check out https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension

**Comment by breedx-splk** [comment]
@LifaPeng will writing an extension then work for you? Thanks.

**Comment by LifaPeng** [comment]
I'll try following the link
