### ISSUE TITLE
Instrumentation for AWS SDK 1.11 not setting db.system for DynamoDB requests

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-java-instrumentation#12493]
### Describe the bug

The [AWS 1.11 requests auto instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/aws-sdk/aws-sdk-1.11) does not seem to be setting the db.system attribute for dynamoDB spans. This is stopping our platform from identifying it properly as a db span.

### Steps to reproduce

Enable javaagent and make request to dynamoDB using AWS 1.11 SDK 

### Expected behavior

db.* attributes to be set on dynamodb spans

### Actual behavior

No db.* attributes set, treated as external service call

### Javaagent or library instrumentation version

io.opentelemetry.aws-sdk-1.11

### Environment

**JDK**:
**OS**:

**Comment by trask** [comment]
hi @akats7!

it looks like AWS SDK 2.2 instrumentation sets a couple of db attributes: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/5cc89173c430b643bc08266547f745410c27f8cc/instrumentation/aws-sdk/aws-sdk-2.2/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v2_2/internal/TracingExecutionInterceptor.java#L330-L336

I think we'd welcome the equivalent change to AWS SDK 1.1 instrumentation if that's possible

**Comment by vasantteja** [comment]
Hello @trask, Can you please assign this to me if this needs a code change?

**Comment by akats7** [comment]
Hi @vasantteja, thanks for offering, we already have a proposed fix, I just wanted to create an issue prior to opening a PR
