### ISSUE TITLE
Custom Instrumentation caused : Cannot find annotation method 'since()' in type 'Deprecated'

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#12503]
### Describe the bug

When i tried to created a custom instrumentation for different springboot version. It will cause this bug:  `/Users/user/.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/6.0.15/bd96acb6a63c8fee3d7412082c27ab164294994f/spring-webmvc-6.0.15.jar(/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.class) warning: Cannot find annotation method 'since()' in type 'Deprecated'`

### Steps to reproduce

1. create a custom instrumentation
2. add dependency `compileOnly("org.springframework.boot:spring-boot-starter-web:3.1.7")` and add this code to advice 
```java
ConfigurableApplicationContext context = (ConfigurableApplicationContext) result;
Map<?, ?> handlerMethods = context.getBean("requestMappingHandlerMapping",
    RequestMappingHandlerMapping.class).getHandlerMethods();
```
3. run gradle assemble

### Expected behavior

build successfully

### Actual behavior

/Users/user/.gradle/caches/modules-2/files-2.1/org.springframework/spring-webmvc/6.0.15/bd96acb6a63c8fee3d7412082c27ab164294994f/spring-webmvc-6.0.15.jar(/org/springframework/web/servlet/mvc/method/annotation/RequestMappingHandlerMapping.class): warning: Cannot find annotation method 'since()' in type 'Deprecated'
error: warnings found and -Werror specified
1 error
1 warning

FAILURE: Build failed with an exception.

### Javaagent or library instrumentation version

1.32.0

### Environment

**JDK**: 17
**OS**: macos

### Additional context

In spring 6.x, `RequestMappingHandlerMapping` used `@Deprecated(since = "6.0")`, "since" is since from jdk9. It seems that i used a class cannot be compiled with jdk8. Is there any suggestion for this?

**Comment by laurit** [comment]
We fail build on compiler warnings. If this behavior does not suite your needs you are welcome to alter it. Usually we work around this issue by changing the jdk given module is compiled with. For example spring 6 requires jdk 17 to run so we can set our instrumentation to also compile with jdk 17.

**Comment by xiangtianyu** [comment]
I used jdk 17 for gradle, how can i change the jdk for specific module

**Comment by laurit** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/1c3a3749b8184c57000fa1ffba9b1b62c1447de7/instrumentation/spring/spring-webmvc/spring-webmvc-6.0/javaagent/build.gradle.kts#L43-L45
