### ISSUE TITLE
opentelemetry-javaagent cause resttemplate error

### ISSUE THREAD

**Issue by pengliaoye** [open-telemetry/opentelemetry-java-instrumentation#12504]
### Describe the bug

Caused by: org.springframework.security.oauth2.server.resource.introspection.OAuth2IntrospectionException: Cannot invoke "io.opentelemetry.context.Context.get(io.opentelemetry.context.ContextKey)" because "context" is null

### Steps to reproduce

1.  when use agent and spring boot starter same time

### Expected behavior

not npe

### Actual behavior

can't get context 

### Javaagent or library instrumentation version

java17,  opentelemetry-javaagent 2.9.0

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
Please provide a minimal application that reproduces your issue along with any necessary instructions.

**Comment by pengliaoye** [comment]
1. clone https://github.com/pengliaoye/demo you can use the repo. 
2. start with latest agent  -javaagent:/Users/nscq-pgy/Downloads/opentelemetry-javaagent.jar 
3. access http://localhost:8080/hello then you console will show error

**Comment by laurit** [comment]
I think this issue happens only when you use both the spring starter and the javaagent.

**Comment by pengliaoye** [comment]
@laurit  are you suggest how to handle this issue. use only agent or only spring starter?

**Comment by trask** [comment]
yeah, you should pick one or the other, it would be nice if they were complementary but not today, see also https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/12381

**Comment by laurit** [comment]
> @laurit are you suggest how to handle this issue. use only agent or only spring starter?

@pengliaoye I suggested this so you could get your application running. Is there a particular reason why you wish to use both the agent and the starter at the same time? That being said I'll try to fix this issue.

**Comment by pengliaoye** [comment]
i need collect custom metrics

**Comment by laurit** [comment]
> i need collect custom metrics

You don't need the starter for that. Just include otel api and use `GlobalOpenTelemetry.get()` to get the `OpenTelemetry` instance configured by the agent.
