### ISSUE TITLE
compatible different command line style for find jar path

### ISSUE THREAD

**Issue by misaya98** [open-telemetry/opentelemetry-java-instrumentation#12545]
### Describe the bug

compatible command like : java -jar -XX:MaxRAM=128m app.jar
The JAR file name does not always come immediately after the -jar command; there may be other JVM parameters in between the two.

by now, if we use the java -jar -XX:MaxRAM=128m app.jar command to start the applicaion. we can not get the real jar name.
we will get the warn log like below:
otel.javaagent 2024-10-29 09:24:19:600 +0000] [main] WARN io.opentelemetry.instrumentation.resources.ManifestResourceProvider - Error reading manifest java.nio.file.NoSuchFileException: -XX:MaxRAM=128m

### Steps to reproduce

start application by  java -jar -XX:MaxRAM=128m app.jar

### Expected behavior

get the real jar name

### Actual behavior

can not get jar name

### Javaagent or library instrumentation version

latest

### Environment

**JDK**: 17
**OS**: redhatLinux

**Comment by misaya98** [comment]
#12544

**Comment by jaydeluca** [comment]
While the change in your PR looks pretty straight forward (although It could use some tests), I'm curious as to why it's needed?

Based on [the oracle documentation](https://docs.oracle.com/en/java/javase/19/docs/specs/man/java.html), the jar file should always immediately follow the `-jar` flag:

> By default, the first argument that isn't an option of the java command is the fully qualified name of the class to be called. **If -jar is specified, then its argument is the name of the JAR file containing class and resource files for the application.**

It seems to me like `java -jar -XX:MaxRAM=128m app.jar` does not follow this convention

**Comment by misaya98** [comment]
> While the change in your PR looks pretty straight forward (although It could use some tests), I'm curious as to why it's needed?
> 
> Based on [the oracle documentation](https://docs.oracle.com/en/java/javase/19/docs/specs/man/java.html), the jar file should always immediately follow the `-jar` flag:
> 
> > By default, the first argument that isn't an option of the java command is the fully qualified name of the class to be called. **If -jar is specified, then its argument is the name of the JAR file containing class and resource files for the application.**
> 
> It seems to me like `java -jar -XX:MaxRAM=128m app.jar` does not follow this convention

but actually  java -jar -XX:MaxRAM=128m app.jar works well. 
so i think we need to compatible with this style.
