### ISSUE TITLE
MDC attributes not captured with spring boot application using log4j.

### ISSUE THREAD

**Issue by nityanandagohain** [open-telemetry/opentelemetry-java-instrumentation#12540]
I am using log4j in my spring boot application. The issue that I am facing is that the MDC attributes are not captured even after adding `otel.instrumentation.log4j-appender.experimental.capture-mdc-attributes=*` . Do I need to configure anything else ?

The other settings like `otel.instrumentation.log4j-appender.experimental-log-attributes` work as as expected.

-----
update: I am able to get mdc attributes if I add them 
```
ThreadContext.put("userId", "myid");
ThreadContext.put("requestId", "reqID");
````

But how do I capture attributes like className / LoggerName ?

**Comment by trask** [comment]
hi @nityanandagohain, are you using the OpenTelemetry Spring Boot starter or the OpenTelemetry Java agent or the OpenTelemetry Log4j Appender artifact?

**Comment by nityanandagohain** [comment]
hi @trask  I am using the otel java agent 


here is the code that I am using to test it https://github.com/nityanandagohain/otel_log4j

this is the run command I am using

```
OTEL_METRICS_EXPORTER=none OTEL_LOGS_EXPORTER=otlp OTEL_EXPORTER_OTLP_ENDPOINT="http://localhost:4317"  OTEL_RESOURCE_ATTRIBUTES=service.name=test java -javaagent:"/Users/nityanandagohain/Downloads/opentelemetry-javaagent.jar" -Dotel.instrumentation.log4j-appender.experimental.capture-marker-attribute=true -Dotel.instrumentation.log4j-appender.experimental.capture-mdc-attributes='*' -jar target/*.jar
```

**Comment by trask** [comment]
> -Dotel.instrumentation.log4j-appender.experimental.capture-mdc-attributes='*'

my first guess would be that it's a shell quoting issue, maybe try

> '-Dotel.instrumentation.log4j-appender.experimental.capture-mdc-attributes=*'

**Comment by laurit** [comment]
> But how do I capture attributes like className / LoggerName ?

Capturing the class/method/line that logged the message is currently not implemented for log4j. It is implemented for logback. Logger name is set as `InstrumentationScope`.

**Comment by nityanandagohain** [comment]
Thanks @trask , the custom mdc attributes were captured but I wanted cass/method/line etc for log4j which doesn't seem to be supported as per @laurit .

Do we have any roadmap if it will be added for log4j ?
Thanks :)

**Comment by trask** [comment]
hi @nityanandagohain, if you can create a new issue targeted at that feature (and closing this issue), we will tag it as ["contribution welcome"](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/ISSUES.md#contribution-welcome).
