### ISSUE TITLE
otel sdk unexpectedly extract log data

### ISSUE THREAD

**Issue by howan36** [open-telemetry/opentelemetry-java-instrumentation#12573]
{
"@timestamp": "2024-11-03T01:19:54.333781834+08:00",
"@Version": "1",
"message": "200 OK GET https://api-dev-mpp.xxxx.cn/api/routes/updatedAt",
"logger_name": "org.zalando.logbook.Logbook",
"thread_name": "reactor-http-epoll-4",
"level": "TRACE",
"level_value": 5000,
"http_request": Object{...},
"http_response": Object{...}
}

the log from my container stdout is like above, but data in grafana loki only has message field content,
like: timestape 200 OK POST https://api-dev-mpp.xxxx.cn/api/routes/updatedAt, others are missing

i am not sure how to change this default extract behaviour of java otel sdk

**Comment by trask** [comment]
are you using logstash? if so, I wonder if #12513 will help...

**Comment by howan36** [comment]
we use logback as logging framework

**Comment by trask** [comment]
can you give an example of how you are logging that ends up outputting the json above?

**Comment by howan36** [comment]
as my understanding, sdk will extract some message fields to attributes like trace_id, thread etc, but field http_request and http_response should be kept.

**Comment by howan36** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <include resource="org/springframework/boot/logging/logback/defaults.xml"/>
    <springProperty scope="context" name="springAppName" source="spring.application.name"/>

    <property name="PATTERN"
              value="%d{yyyy-MM-dd HH:mm:ss.SSS} [trace_id=%X{trace_id:-},span_id=%X{span_id:-}] [%X{x-request-id}] [%thread] [scenario:%X{scenario}] [activityId:%X{activityId}] [partyUid:%X{partyUid}] [extendContext:%X{extendContext}] %-5level %cyan(%logger{64}) - %msg %n"/>

    <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
            <layout class="com.ikea.common.spring.filter.http.CustomPatternLayout">
                <pattern>${PATTERN}</pattern>
            </layout>
        </encoder>
    </appender>

    <appender name="Async" class="ch.qos.logback.classic.AsyncAppender">
        <appender-ref ref="Console"/>
    </appender>

    <root level="INFO">
        <appender-ref ref="Async"/>
    </root>
</configuration>

**Comment by trask** [comment]
what do you pass to the logger, e.g. message, mdc, etc?

**Comment by laurit** [comment]
@howan36 the log output and the configuration you have provided do no match as far as I can tell. Please provide a minimal application that reproduces your issue along with any necessary instructions.

**Comment by howan36** [comment]
we true use logstash markers, and when for that issuer PR will be merged

**Comment by trask** [comment]
I've tagged that PR to automatically close this issue, so you'll be notified when it's merged
