### ISSUE TITLE
Should instrumentation version for instrumentations be changed to something more descriptive?

### ISSUE THREAD

**Issue by jamesylgan** [open-telemetry/opentelemetry-java-instrumentation#1260]
What is the motivation behind including the instrumentation version [here](
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/8ed4ef55c87c8259434dac15531030a2f32667f8/instrumentation/apache-httpclient/apache-httpclient-4.0/src/main/java/io/opentelemetry/instrumentation/auto/apachehttpclient/v4_0/ApacheHttpClientTracer.java#L78)?

Perhaps naively, I feel that providing the version the instrumentation was created for has less value than it could: users will observe the instrumentation version, e.g. `4.0.0` showing up for any versions 4.0.0+, and may mistake that for the library version being impacted by the instrumentation.

Alternatively, would it be better to store instrumentation versions as `4.0.0+` explicitly, so users can know by default that the instrumentation is for version `4.0.0` or above? If there's some reason for it to be `4.0.0` I'd love to read up on how the decision was made. Thanks!

**Comment by trask** [comment]
Yeah, this does seem like it will cause confusion.

There isn't too much reasoning behind the current naming other than it matches the instrumentation module name (in this case `apache-httpclient-4.0`), so people can tell which instrumentation module produced the span.

**Comment by jamesylgan** [comment]
That's sort of what I figured - would definitely propose changing it (pretty simply) from `<instrumentation_version>` to `<instrumentation_version>+`. I think that would help clarify things

**Comment by iNikem** [comment]
E.g. we have instrumentation `jedis-1.4` and `jedis-3.0`. Where effectively first one is for versions 1.4-3.0. Having `1.4+` for it still may be confusing, because it seems to be unbounded.

I think it is better to remove those versions from `InstrumentationName` completely.

**Comment by jamesylgan** [comment]
That may break some things @iNikem :)

It could be split into `InstrumentationVersion` and `InstrumentationName` though

**Comment by trask** [comment]
> That may break some things @iNikem :)

Curious what you are thinking of that may break?

> It could be split into `InstrumentationVersion` and `InstrumentationName` though

I think `InstrumentationVersion` is supposed to be the version of the instrumentation, e.g. `0.8.0`, and get bumped with each new release of the instrumentation.

**Comment by jamesylgan** [comment]
https://github.com/signalfx/splunk-otel-java/blob/main/custom/src/main/java/com/splunk/opentelemetry/InstrumentationLibrarySpanProcessor.java#L44

Some of @iNikem's code

**Comment by iNikem** [comment]
I think there is some misunderstanding :)

Current situation:
```
InstrumentationLibraryInfo.name = io.opentelemetry.auto.apache-httpclient-4.0
InstrumentationLibraryInfo.version = 0.8.0 (version of auto-instrumentation release)
```
I propose to change to
```
InstrumentationLibraryInfo.name = io.opentelemetry.auto.apache-httpclient
InstrumentationLibraryInfo.version = 0.8.0 (version of auto-instrumentation release)
```

Nothing will break :)

**Comment by jamesylgan** [comment]
Sounds good to me!

**Comment by Anisha-28** [comment]
Hi (I am an outreachy applicant) .. can i try this issue .. just need some clarity

**Comment by trask** [comment]
Hey @Anisha-28!

We want to remove the version number from the instrumentation name, e.g. change `"io.opentelemetry.auto.apache-httpclient-4.0"` to `"io.opentelemetry.auto.apache-httpclient"` in `ApacheHttpClientTracer`

```
  @Override
  protected String getInstrumentationName() {
    return "io.opentelemetry.auto.apache-httpclient-4.0";
  }
```

**Comment by vadeg** [comment]
Since there was no movement so far and the ticket has not been assigned I created a PR. 
Sorry @Anisha-28 if I took your ticket.
