### ISSUE TITLE
Agent collection of Java logs issue

### ISSUE THREAD

**Issue by laoeree** [open-telemetry/opentelemetry-java-instrumentation#12613]
### Is your feature request related to a problem? Please describe.

Using an agent to collect Java logs, the thread information in the logs will be lost (presumably due to serialization being discarded). Is there a way to set it not to be discarded
![image](https://github.com/user-attachments/assets/30db0ade-1d92-4276-a2ad-e713bc7685f9)
Actual console log：
![image](https://github.com/user-attachments/assets/a55d15bc-bf23-4816-9074-675c1bc5bd3b)
Collect and export logs to Loki through the agent, only the content after the colon in the actual logs：
![image](https://github.com/user-attachments/assets/471ad973-69a1-4cc8-adf1-d9b735a5cb45)

### Describe the solution you'd like

Is there a way to set it not to be discarded。

**Comment by laurit** [comment]
Have a look at https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/logback/logback-appender-1.0/javaagent/README.md does this help?

**Comment by laoeree** [comment]
> 看看https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/logback/logback-appender-1.0/javaagent/README.md这有帮助吗？
Thank you, but I have used the configuration and found that it is not the parameters I wanted
![image](https://github.com/user-attachments/assets/945f01ce-2d64-4608-9378-0ae04026ca2c)

**Comment by laurit** [comment]
> > 看看[https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/logback/logback-appender-1.0/javaagent/README.md这有帮助吗？](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/logback/logback-appender-1.0/javaagent/README.md%E8%BF%99%E6%9C%89%E5%B8%AE%E5%8A%A9%E5%90%97%EF%BC%9F)
> > Thank you, but I have used the configuration and found that it is not the parameters I wanted

@laoeree care to elaborate what exactly it is that you want?

**Comment by laoeree** [comment]
> > > 看看[https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/logback/logback-appender-1.0/javaagent/README.md这有帮助吗？](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/logback/logback-appender-1.0/javaagent/README.md%E8%BF%99%E6%9C%89%E5%B8%AE%E5%8A%A9%E5%90%97%EF%BC%9F)
> > > 谢谢，但我用过配置，发现不是我想要的参数
> 
> @laoeree请详细说明一下你到底想要什么？

I need the  "[% X {requestId}]"  in the logback configuration in the first screenshot

**Comment by laoeree** [comment]
> > 我需要第一个屏幕截图中 logback 配置中的“[％X {requestId}]”
> 
> 您是否尝试过使用该`otel.instrumentation.logback-appender.experimental.capture-mdc-attributes`选项？
After adding this option, it really works, thank you
