### ISSUE TITLE
Propagators, java agent and spring boot application - traces are gone for some endpoints

### ISSUE THREAD

**Issue by lucian-vanghele** [open-telemetry/opentelemetry-java-instrumentation#12617]
### Describe the bug

We have an API autoinstrumented with javaagent, sending traces to Tempo via otel collector. From upstream we are receiving in our application uber-trace-id so we tried to use the propagators feature. It seems that after adding otel_propagators=tracecontext,jaeger on javaagent all the protected endpoints lost tracing data. We only have traces for unprotected endpoints. Removing the option brings back the tracing.

### Steps to reproduce

- add otel_propagators=tracecontext,jaeger on javaagent 
- restart the service and trigger some calls on different endpoints
- check traces sent to backend

### Expected behavior

traces should still work after adding otel_propagators on all endpoints

### Actual behavior

traces are not produced for protected endpoints. 

### Javaagent or library instrumentation version

javaagent 2.7.0

### Environment

**JDK**: java-17-openjdk
**OS**: RHEL 5.14.0
[SpringBoot]org.springframework:spring-webmvc:jar:6.1.12

**Comment by trask** [comment]
hi @lucian-vanghele, it's really hard to guess what the problem might be. If you aren't able to narrow it down to a minimal repro that we can use to troubleshoot then it will be difficult for us to help you.
