### ISSUE TITLE
 Logback fails to print logs successfully

### ISSUE THREAD

**Issue by pepeshore** [open-telemetry/opentelemetry-java-instrumentation#12615]
### Describe the bug

 Logback fails to print logs successfully when OT Java Agent is attached

### Steps to reproduce

 Provide a custom MessageConverter  and put something new into the mdc map
`
public class MyMDCConverter extends MessageConverter {
    @Override
    public String convert(ILoggingEvent event) {
        event.getMDCPropertyMap().put("key", "value");
        return super.convert(event);
    }
}
`

### Expected behavior

 print logs successfully

### Actual behavior

 print logs failed
 I notice that in `io.opentelemetry.javaagent.instrumentation.logback.mdc.v1_0.LoggingEventInstrumentation.GetMdcAdvice` it replaced the original return value into a  UnionMap which does't support write operation

### Javaagent or library instrumentation version

2.4

### Environment

**JDK**:
**OS**:

**Comment by trask** [comment]
I'd probably support removing `UnionMap` vs extending it further to support write operations. @laurit wdyt?

**Comment by laurit** [comment]
> I'd probably support removing `UnionMap` vs extending it further to support write operations. @laurit wdyt?

I also think that would be the easiest solution.
