### ISSUE TITLE
Pulsar `publish` span can't continue traceID from parent span when using `transaction` producer send message

### ISSUE THREAD

**Issue by coderzc** [open-telemetry/opentelemetry-java-instrumentation#12729]
### Describe the bug

Pulsar `publish` span can't continue traceID from parent span when using transaction producer send message

### Steps to reproduce

```java
    public static void main(String[] args) throws PulsarClientException {
        String serviceUrl = "pulsar://localhost:6650";
        String topic = "my-topic";

        PulsarClient client = PulsarClient.builder()
            .serviceUrl(serviceUrl)
            .enableTransaction(true)
            .build();

        Producer<String> producer = client.newProducer(Schema.STRING)
            .enableBatching(false)
            .topic(topic)
            .create();

        Transaction txn = null;
        Tracer tracer = GlobalOpenTelemetry.getTracer("myapp");
        Span span = tracer.spanBuilder("root span").startSpan();

        try (Scope __ = span.makeCurrent()) {
            txn = client.newTransaction().withTransactionTimeout(10, TimeUnit.SECONDS).build().get();
            producer.newMessage(txn).value("msg1").send();
            txn.commit().get();
        } catch (Exception e) {
            txn.abort().join();
            throw new RuntimeException(e);
        } finally {
            span.end();
        }

        producer.close();
        client.close();
    }
```

### Expected behavior

Pulsar `publish` span can continue traceID from parent span when using transaction producer send message

The following is the trace of don't use transactions to send data:
<img width="1237" alt="image" src="https://github.com/user-attachments/assets/268e8b2f-0bb2-4aa3-9df6-e1424f241607">

### Actual behavior

Pulsar `publish` span can't continue traceID from parent span when using transaction producer send message
When sending data using transactions, the thread ID changed, not sure if it is related to it

<img width="654" alt="image" src="https://github.com/user-attachments/assets/515ba551-6444-43ed-8717-1397ea7042ec">

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/ec46ee16-483f-48d1-bb92-8113ec796af6">

<img width="1330" alt="image" src="https://github.com/user-attachments/assets/f960c3ac-f246-4cbb-8c40-1a77a64a383f">

### Javaagent or library instrumentation version

v1.32.1

### Environment

**JDK**: 17
**OS**:

**Comment by dao-jun** [comment]
`TransactionImpl.registerProducedTopic` will switch the thread, so it will break the trace. I'll try to fix it.
