### ISSUE TITLE
Change TracerCustomizer to OpenTemenetrySdkCustomizer

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1273]
Java agent SPI has the following class. Since the tracer is not the only object exposed by the OTEL API, we should consider changing it to the `OpenTelemetrySdkCustomizer` with `void configure(OpenTelemetrySdk sdk);`

```java
public interface TracerCustomizer {

  /** Callback executed after the initial {@link TracerSdkProvider} has been initialized. */
  void configure(TracerSdkProvider tracerSdkProvider);
}
```

**Comment by pavolloffay** [comment]
Actually the `TracerSdkProvider` has only static accessors so the proposed interface is not doable.

**Comment by trask** [comment]
> Actually the `TracerSdkProvider` has only static accessors so the proposed interface is not doable.

Hey @pavolloffay I'm not following, it seems good to me.

I think it will be even nicer using `TracerSdkManagement` once that is split out from `TracerSdkProvider` in https://github.com/open-telemetry/opentelemetry-java/pull/1723 cc: @jkwatson 👍

**Comment by iNikem** [comment]
@pavolloffay Does current
```
public interface TracerCustomizer {
  void configure(TracerSdkManagement tracerManagement);
}
```
address your problem? Can this issue be closed?

**Comment by pavolloffay** [comment]
Partially, the idea was to have a single customizer SPI for all OTEL core objects.

**Comment by trask** [comment]
Closing, this is all in autoconfigure module now
