### ISSUE TITLE
logback encoder field becomes decoded with otel java instrumentation agent

### ISSUE THREAD

**Issue by howan36** [open-telemetry/opentelemetry-java-instrumentation#12757]
```
    <springProfile name="prod">
        <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
            <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                <layout class="com.ikea.common.spring.filter.http.CustomPatternLayout">
                    <maskPattern>(?:name|firstName|lastName|customerName)\s*(?:=|:)\s*(.+?) .</maskPattern>
                    <maskPattern>(?:address1|customerAddress)\s*(?:=|:)\s*(.+?) .</maskPattern>
                    <maskPattern>\\?"(?:address1|customerAddress)\\?"\s*:\s*\\?"(.+?)\\?"</maskPattern>
                    <maskPattern>\\?"(?:name|firstName|lastName|customerName)\\?"\s*:\s*\\?"(.+?)\\?"</maskPattern>
                    <hashPattern>\\?"(?:mobile|phone|phoneNumber|communicationPhone)\\?"\s*:\s*\\?"([+\d]+)\\?"</hashPattern>
                    <hashPattern>(?:PHONE|phone|phoneNumber|communicationPhone|mobile)\s*(?:=|:)\s*([+\d]+)</hashPattern>
                    <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [trace_id=%X{trace_id} span_id=%X{span_id}] [%p][%c#%M:%L] -> %m%n</pattern>
                </layout>
            </encoder>
        </appender>

        <root level="info">
            <appender-ref ref="CONSOLE"/>
        </root>
    </springProfile>
```
we use the above config to encode some sensitive field, but after received from collector, it becomes decoded

**Comment by howan36** [comment]
<encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">

**Comment by laurit** [comment]
The layout patterns you have configured are for the console appender. Otel appender is not connected to the console appender and does not use this configuration. I believe you can use the collector to apply these patterns to the log data.

**Comment by howan36** [comment]
ok， thanks a lot @laurit ,  besides, if otel log appender could output the log format to json, i found some field s were extracted to attributes labels,  and the log body seems to be text mode

**Comment by howan36** [comment]
for example, 


200 OK GET https://api-dev-mpp.ingka-dt.cn/link-service/api/routes/updatedAt  {"origin":"local","type":"request","correlation":"fdddd","protocol":"HTTP/1.1","remote":"api-devdddddd.cn.cnapp-ddl/61.170.77.230:443","method":"GET","uri":"https://addsd/lidsddsds/api/routes/updatedAt","host":"api-dedsdsdds","path":"/link-service/api/routes/updatedAt","scheme":"https","port":"443","headers":{"accept":["*/*"],"accept-encoding":["gzip"],"apiKey":["dsdssd"],"b3":["f08320df111ab165bbsdsdsddssdc9012e98651ee0-1"],"host":["sddsddssdds"],"traceparent":["00-12e98651ee0-01"],"user-agent":["ReactorNetty/1.1.20"]}} |  
  |

**Comment by howan36** [comment]
for this log, the first row is the original message, and the json is the content i use transform processor to concat from attributes, if they could combine into 1 big json

**Comment by howan36** [comment]
ok thanks lot @laurit , i could look into the logbak appendar later, thanks again.
