### ISSUE TITLE
Want class name & method name in sperate attribute

### ISSUE THREAD

**Issue by tech-ind-02** [open-telemetry/opentelemetry-java-instrumentation#12750]
### Is your feature request related to a problem? Please describe.

NO.

### Describe the solution you'd like

right now in name field we are getting "**Name:** **Classname.methodname** " i want whenever there i class name an method name appear then it should be available as separate attribute.

please let me if we can get this by adding some configuration.

**Comment by trask** [comment]
hi @tech-ind-02! which instrumentation is producing that span name? (I'm wondering if this would be addressed by https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7345)
