### ISSUE TITLE
Implement db.mongodb.collection semantic attribute

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1278]
It is [required by specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md#call-level-attributes-for-specific-technologies).

**Comment by imavroukakis** [comment]
There's a method that seems to do this in `DbMongodbSpan`
```
@Override
public DbMongodbSemanticConvention setDbMongodbCollection(String dbMongodbCollection) {
    delegate.setAttribute("db.mongodb.collection", dbMongodbCollection);
    return this;
}
```

Is this relevant?

**Comment by iNikem** [comment]
Yes and no :) `DbMongoSpan` and other typed spans in that package provide an API for simpler filling semantic conventions. Somebody still has to actually call them. And we currently does not use them still.

This task is about extracting the actual value from Mongo instrumentation and setting it on the span.
