### ISSUE TITLE
Log a clear warning if application uses TracerSdkProvider or MetricSdkProvider

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1279]
We do not instrument `TracerSdkProvider` because it provides methods that we do not interoperate with, e.g. `updateActiveTraceConfig` and `addSpanProcessor`.

So when users use `OpenTelemetrySdk.getTracerProvider()` we don't capture any spans.

Same for `MetricSdkProvider`.

We should probably log a clear warning (just once) if an application uses one of these classes.

If we find that this is an even bigger problem, we could probably find a way to interoperate with the SDK methods we support, and no-op the others.

**Comment by trask** [comment]
Oh! I just saw https://github.com/open-telemetry/opentelemetry-java/pull/1723, which will make this irrelevant! cc: @jkwatson

**Comment by iNikem** [comment]
@trask open-telemetry/opentelemetry-java#1723 is merged, should we close this issue?

**Comment by trask** [comment]
Yes!
