### ISSUE TITLE
Is OTEL_EXPORTER=otlp,prometheus an invalid configuration that we should prevent?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1281]
My understanding is:

* With OTLP metric exporter, we use an `IntervalMetricReader` which will call `collectAllMetrics` every 60 seconds
* With prometheus collector, it will call `collectAllMetrics` any time prometheus hits the url to scrape metrics
* Each time `collectAllMetrics` is called it resets itself, which will lead to conflict between these two approaces

**Comment by trask** [comment]
More concretely, I think that we should only support one of these two configurations:

* A single `MetricProducerCustomizer` + zero `MetricExporterFactory`, or
* Zero `MetricProducerCustomizer` + any number of `MetricExporterFactory` (whose exporters we wrap in a single `IntervalMetricReader`)

**Comment by iNikem** [comment]
As long as `collectAllMetrics` resets data, this is a good proposal.

**Comment by iNikem** [comment]
@trask can we agree that discussion has completed and create an actual issue?

**Comment by trask** [comment]
Yes, I will create. Also, @jkwatson pointed out today that `IntervalMetricReader` currently only accepts a single `MetricExporter`, which makes our story even easier, we can only support a single metric exporter (either pull or push).
