### ISSUE TITLE
Rename buildSrc to muzzle-gradle-plugin

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1283]
If the `buildSrc` contains only the Muzzle gradle plugin we should rename it to `muzzle-gradle-plugin`.

**Comment by iNikem** [comment]
`buildSrc` is a [pre-defined folder name for Gradle](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:build_sources). I think what we actually want to do is #1225

**Comment by pavolloffay** [comment]
+1 then we are stuck with `buildSrc` I am closing this one then.
