### ISSUE TITLE
Ktor: make `spanNameExtractor` configurable

### ISSUE THREAD

**Issue by SIMULATAN** [open-telemetry/opentelemetry-java-instrumentation#12842]
Whilst [the semconv](https://opentelemetry.io/docs/specs/semconv/http/http-spans/#name) doesn't explicitly require the URL to be part of the span name, I would like to see more information than just the request method there.

Thus, I propose to add a simple `setSpanNameExtractor` method to the [`AbstractKtorClientTracingBuilder`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/ktor/ktor-2-common/library/src/main/kotlin/io/opentelemetry/instrumentation/ktor/client/AbstractKtorClientTracingBuilder.kt), similar to what #8255 did. Something like this would do just fine:
```kt
fun setSpanNameExtractor(spanNameExtractor: SpanNameExtractor<in HttpRequestData>) {
	clientBuilder.setSpanNameExtractor { spanNameExtractor }
}
```

#9607 already brought this topic up, but the semconv has changed since then to include the `url.template` if enabled. In my opinion, my proposal would allow users to implement this, should they choose to, whilst preserving the original, non-experimental default.

**Comment by trask** [comment]
we would definitely accept a hook similar to what OkHttpTelemetryBuilder already has: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/c2c5d80f72c1ab7d69dd606348a2d09a99ddd36e/instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/okhttp/v3_0/OkHttpTelemetryBuilder.java#L97-L106

**Comment by laurit** [comment]
Resolved with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12850
