### ISSUE TITLE
Reduce magic of selecting SpanExporterFactory and friends

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1287]
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1253#discussion_r494221024 and https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1262#discussion_r496878453 (and I think it was brought up once before that too 😄)

**Comment by anuraaga** [comment]
My suggestion before was to have a hard-coded map of well-known exporters (what's in spec) and use fully-qualified class name for non-well-known exporters. This is mainly to prevent having collisions of names between two exporters - but maybe UX for a custom exporter like stackdriver isn't very good with it so defining the name as an API seems ok too.

**Comment by iNikem** [comment]
We have to prevent a situation when some external exporter claims to have a name of some built-in one.

**Comment by trask** [comment]
I thought `OTEL_EXPORTER` only applies to built-in exporters?

I was imagining vendor distributions would just have their one exporter hard-coded (no need for `OTEL_EXPORTER`).

And external exporter jar files are specified using `OTEL_EXPORTER_JAR`.

**Comment by iNikem** [comment]
Don't think about 1 exporter, think about 3 exporters: for traces, metrics and (in the future) logs. Vendor can hard-code some of them, external jar can contain some of them and some may be built-in.

**Comment by pavolloffay** [comment]
> I thought OTEL_EXPORTER only applies to built-in exporters?

Is there anything blocking us from loading vendor exporters via this setting? From the user-experience it would be better to keep the consistency and allow loading custom exporters.

**Comment by iNikem** [comment]
The question is: where to load it from? If it is vendor distribution which packed its export in - sure, we should to that. Otherwise - how?

**Comment by trask** [comment]
Does this proposal address the above concerns?
* `OTEL_EXPORTER` only applies to exporters that are bundled into the (otel or vendor) distribution
* add `List<String> getExporterNames()` to `SpanExporterFactory` and `MetricServer`
  * returning `List` e.g. allows OtelSpanExporterFactory to be enabled by both `otel_span` and `otel`

**Comment by iNikem** [comment]
How can we/should we prevent vendor exporter to provide the same exporter name as one of the Otel's built in?

**Comment by trask** [comment]
> How can we/should we prevent vendor exporter to provide the same exporter name as one of the Otel's built in?

Vendor distributions can pretty much do whatever they want, and it's not our responsibility(?)

**Comment by iNikem** [comment]
To make it clear: so you don't see a problem if some vendor provides completely separate exporter which claims it is "otlp_spans"?

Well, less work for us :)

**Comment by pavolloffay** [comment]
> Vendor distributions can pretty much do whatever they want, and it's not our responsibility(?)

+1, it's their responsibility and they might do it to e.g. swap implementations
