### ISSUE TITLE
Spring Scheduled Task TraceGroup name wrong

### ISSUE THREAD

**Issue by varjasz** [open-telemetry/opentelemetry-java-instrumentation#12889]
### Describe the bug

Spring @Scheduled tasks trace group names are the same: 'OutcomeTrackingRunnable.run'.

### Steps to reproduce

With Spring Boot 3.4 és Spring Framework 6.2.0 the @Scheduled tasks trace group names are the same: 'OutcomeTrackingRunnable.run'.
With previous Spring versions the trace group names for @Scheduled methods are: ClassName+methodName.

### Expected behavior

Trace group names for @Scheduled methods should be: ClassName+methodName.

### Actual behavior

@Scheduled tasks trace group names are the same: 'OutcomeTrackingRunnable.run'

### Javaagent or library instrumentation version

java agent 2.10.0

### Environment

**JDK/OS**: eclipse-temurin:21-jre-alpine
**Spring Boot**: 3.4.0
**Spring Framework** 6.2.0

**Comment by steverao** [comment]
The problem has been fixed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12739.
You can build the latest source based on main branch and have a trial again.

**Comment by varjasz** [comment]
I have tested with opentelemetry-javaagent/2.11.0-SNAPSHOT/opentelemetry-javaagent-2.11.0-20241214.104101-89.jar and the trace group names are **OK** again.

Then we wait for the offical 2.11 release :)  
Thanks!
