### ISSUE TITLE
Rename MuzzleGradlePlugin to MuzzleByteBuddyPlugin

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1288]
The current name is misleading, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1270#discussion_r495717382

**Comment by pavolloffay** [comment]
This can be closed the plugin name is `MuzzleCodeGenerationPlugin` https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/ee0e0a96974fac8eba802b400201ff2a5ee9da75/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/muzzle/collector/MuzzleCodeGenerationPlugin.java#L25

**Comment by trask** [comment]
Thanks @pavolloffay
