### ISSUE TITLE
Tracing redis commands (spring-data-redis)

### ISSUE THREAD

**Issue by AmitBarlev** [open-telemetry/opentelemetry-java-instrumentation#12899]
### Is your feature request related to a problem? Please describe.

I've been searching but couldn't find any relevant examples.
Is there an API available to trace commands of ReactiveRedisConnection using OpenTelemetry? I came across [this](https://docs.spring.io/spring-data/redis/reference/observability.html), but I'm unsure how OpenTelemetry fits into this.
My goal is to trace individual commands like GET or SET, rather than using [Repositories](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-data/spring-data-1.8/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/spring/data/v1_8/SpringDataInstrumentationModule.java).
Thanks!

### Describe the solution you'd like

Whenever I utilize the ReactiveRedisConnection or ReactiveRedisTemplate to execute a Redis operation, I aim for that operation to be traced. For instance, if I need to retrieve a value, I would like to have the GET command traced by the end of the process.

### Describe alternatives you've considered

Implementation using AOP

**Comment by steverao** [comment]
> Is there an API available to trace commands of ReactiveRedisConnection using OpenTelemetry?

About API,  you can refer to https://opentelemetry.io/docs/languages/java/api/#api-components
There is a related demo that you can also refer to https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/sdk-usage

**Comment by AmitBarlev** [comment]
> > Is there an API available to trace commands of ReactiveRedisConnection using OpenTelemetry?
> 
> About API, you can refer to https://opentelemetry.io/docs/languages/java/api/#api-components There is a related demo that you can also refer to https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/sdk-usage

Took me a bit of time but I finally found what I was looking for, made an [example](https://github.com/AmitBarlev/SOTL)
