### ISSUE TITLE
Document all exposed SPI

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1290]

**Comment by trask** [comment]
@mateuszrzeszutek do you think we can close this? I think all the SPI are javadoc'd, or do you think we need something more?

**Comment by mateuszrzeszutek** [comment]
Hmm, maybe we could add something like https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/writing-instrumentation-module.md for them? I think we'd need to start with the SDK SPIs though, the javaagent will not add much more over them.

Let's close it -- javadocs should suffice for now, and once the SDK autoconfigure module goes stable we'll think of adding something nice to opentelemetry.io.
