### ISSUE TITLE
Publish the full agent jar to Maven

### ISSUE THREAD

**Issue by atoulme** [open-telemetry/opentelemetry-java-instrumentation#1293]
I would like to use this agent as part of a Gradle application.

I have for now used a workaround by downloading the jar as a Gradle task, and made it available to the dependencies so it gets loaded up.
See https://github.com/hyperledger/besu/pull/1410/files#diff-c197962302397baf3a4cc36463dce5eaR523

**Comment by atoulme** [comment]
It looks like the jar is published to bintray, so I'm using this for now. Any chance to get this on Maven Central?

**Comment by trask** [comment]
Hey @atoulme! We are planning to publish to maven central soon(ish).

**Comment by cemo** [comment]
@trask is there any update on this?

**Comment by anuraaga** [comment]
Hi @cemo - since 0.12.0 we're publishing the JAR to Maven!

https://repo1.maven.org/maven2/io/opentelemetry/javaagent/opentelemetry-javaagent/0.13.0/

Thanks for the patience.
