### ISSUE TITLE
Unable to produce `db.client.operation.duration` metrics

### ISSUE THREAD

**Issue by cyrille-leclerc** [open-telemetry/opentelemetry-java-instrumentation#12972]
### Describe the bug

Unable to produce `db.client.operation.duration` metrics that are supposed to be introduced in opentelemetry-jva-instrumentation [v2.11](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.11.0) through https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12806 .
None of `export OTEL_SEMCONV_STABILITY_OPT_IN=database` and `-Dotel.semconv-stability.opt-in=database` works to enable this metric.

### Steps to reproduce

* Use a demo java jdbc app like https://github.com/cyrille-leclerc/my-shopping-cart/tree/5a8839e7ca376d43097625f176277da294a1f996/frontend (startup command [here](https://github.com/cyrille-leclerc/my-shopping-cart/blob/5a8839e7ca376d43097625f176277da294a1f996/frontend/run-frontend))
* Instrument the application with otel-java-instrumentation v2.11 and send metrics to a backend like Prometheus
* Activate new OTel DB metrics with any of `-Dotel.semconv-stability.opt-in=database` and `export OTEL_SEMCONV_STABILITY_OPT_IN=database`
* Start the application and generate traffic
* Verify that 
   * some DB client spans are produced 
   * the otel instrumentation version is v2.11, for xample looking at the resource attribute `telemetry.distro.version=2.11.0` on the spans  

### Expected behavior

The histogram metric `db.client.operation.duration` is produced.

### Actual behavior

The metric `db.client.operation.duration` is missing.

Other `db.client.*` metrics are available: `db.client.connections.create_time` (histogram in `ms`), `db.client.connections.idle.min` (gauge), `db.client.connections.pending_requests` (gauge), `db.client.connections.use_time` (histogram in `ms`), `db.client.connection.wait_time` (histogram in `ms`)

### Javaagent or library instrumentation version

v2.11.0

### Environment

**JDK**:

OpenJDK Runtime Environment 17.0.13+0

**OS**:
MacOS 15.2

### Additional context

cc @zeitlinger

**Comment by jaydeluca** [comment]
i haven't had a chance to run your reproducer to validate that this fixes it, but I noticed that you are setting the `-Dotel.semconv-stability.opt-in` flag [twice](https://github.com/cyrille-leclerc/my-shopping-cart/blob/5a8839e7ca376d43097625f176277da294a1f996/frontend/run-frontend#L150-L156), once on [line 150](https://github.com/cyrille-leclerc/my-shopping-cart/blob/5a8839e7ca376d43097625f176277da294a1f996/frontend/run-frontend#L150C6-L150C37) and then again on [line 156](https://github.com/cyrille-leclerc/my-shopping-cart/blob/5a8839e7ca376d43097625f176277da294a1f996/frontend/run-frontend#L156), and the one on line 156 doesn't include the `database` opt-in.

**Comment by cyrille-leclerc** [comment]
Great catch @jaydeluca , thank you very much. My config was wrong with an invalid second declaration of `-Dotel.semconv-stability.opt-in`
