### ISSUE TITLE
How to Add HTTP Path as a Dimension to http_client_duration_bucket Metric in OpenTelemetry Java?

### ISSUE THREAD

**Issue by dengkai1991** [open-telemetry/opentelemetry-java-instrumentation#12971]
I want to include the HTTP path (e.g., /api/resource) as a label or dimension in the http_client_duration_bucket metric for outbound HTTP requests. How can I achieve this? Is there a way to customize or add attributes to the metrics generated by the HTTP client instrumentation?

**Comment by laurit** [comment]
I don't think there is an easy way to add just the path. You could use [metric view](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/incubator#view-file-configuration) to include the `url.full` attribute.
