### ISSUE TITLE
Additional tags for cassandra 4

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-java-instrumentation#1298]
Is there any interest in having the db host dc and id, query page size, query consistency level, query idempotence, query speculative execution count, or the query parameter values for bound statements with the option to opt-in/out of that last one?

**Comment by iNikem** [comment]
If, as a Cassandra user, you think this data would benefit you, then certainly :)


> the query parameter values for bound statements with the option to opt-in/out

I am not sure about this. It may be a useful option, but ideally we should be prepared for similar functionality for other databases. It is not just a local change for me.

**Comment by FrankSpitulski** [comment]
Definitely useful. I'll submit a PR for the non query parameter logging changes and maybe a second for the logging if it makes sense.

**Comment by FrankSpitulski** [comment]
I pushed up a PR with the changes excluding the query parameter value tracing. I wasn't able to test against master due to oss.jfrog.org being down, but the code is still pretty close to what I expect will be final, excluding tests. Please let me know what you think @iNikem.

WRT the query parameter value tracing can you go into more detail about what not being a local change means? You're saying it has further reaching effects?

**Comment by trask** [comment]
hey @FrankSpitulski, sorry missed this issue yesterday, commented on your PR https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1314#issuecomment-703134133.

wrt query parameters, this option would ideally apply across all of our database instrumentation (e.g. jdbc, redis, mongo, etc). I think this is what @iNikem means by it not being only a "local change/decision". though I think it would be ok to implement support for this option in Cassandra first, and add backlog issues to support across other databases

**Comment by iNikem** [comment]
> wrt query parameters, this option would ideally apply across all of our database instrumentation (e.g. jdbc, redis, mongo, etc). I think this is what @iNikem means by it not being only a "local change/decision"

Yes, this is what I meant.

**Comment by FrankSpitulski** [comment]
Made issue for the spec https://github.com/open-telemetry/opentelemetry-specification/issues/1058

**Comment by FrankSpitulski** [comment]
So it looks like this isn't going in anytime soon then?

**Comment by trask** [comment]
hey @FrankSpitulski, can you submit a spec PR for the spec issue that you filed?

**Comment by FrankSpitulski** [comment]
done

**Comment by FrankSpitulski** [comment]
How often does the java api regenerate the semantic attributes based on the spec? I got the additional attributes merged in finally. @trask

**Comment by trask** [comment]
🎉 nice work! check out https://github.com/open-telemetry/opentelemetry-java/pull/2144 for how to update spec version and regenerate `SemanticAttributes`

**Comment by FrankSpitulski** [comment]
made a PR @trask https://github.com/open-telemetry/opentelemetry-java/pull/2302
