### ISSUE TITLE
Add context root to the front of the route in the span name

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1299]
Currently if you deploy a war file with context root "test", we will capture a span name similar to

```
GET /controller
```

but I think we should capture

```
GET /test/controller
```

**Comment by trask** [comment]
@iNikem you don't think this is a bug / violation of the span name spec? Context root seems like an important part of the route.

**Comment by iNikem** [comment]
I don't have strong opinion about that. IMO spec is vague about that.

**Comment by trask** [comment]
Found this in the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions):

> If the route does not include the application root, it SHOULD be prepended to the span name.
