### ISSUE TITLE
Allow users to configure a brave based SDK with auto-instrumentation

### ISSUE THREAD

**Issue by bogdandrutu** [open-telemetry/opentelemetry-java-instrumentation#1300]
Once https://github.com/open-telemetry/opentelemetry-java/issues/1735 is done, auto-instrumentation should support configuring the brave "sdk" implementation as one of the possible implementation of our API. Users will be able to choose between our SDK or brave base SDK.

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
