### ISSUE TITLE
Shading of opentelemetry-api fragile

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1303]
Currently, we have many packages hard-coded in our configs for shading opentelemetry-api. If packages are added or renamed, many times our tests will fail mysteriously. This isn't great but it's not the end of the world. However, I worry that it is possible there is a change that requires updating the shading that won't trigger a test failure. It'd be nice if the shading could be done more automatically, perhaps by examining the contents of the API jar.

**Comment by trask** [comment]
> However, I worry that it is possible there is a change that requires updating the shading that won't trigger a test failure

Ya, adding smoke test coverage for the OpenTelemetry API instrumentation would help me sleep better 😂

**Comment by iNikem** [comment]
@anuraaga Did open-telemetry/opentelemetry-java#1892 address this issue?

**Comment by anuraaga** [comment]
Ah yeah!
