### ISSUE TITLE
Instrumentation for Java NIO

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java-instrumentation#1311]
We instrument many frameworks at a higher level, but we don't directly handle NIO.  This might help bridge some gaps in trace propagation.

See here for nice examples: https://www.baeldung.com/java-nio-selector

**Comment by anuraaga** [comment]
@tylerbenson I know with Netty it's possible to use tcnative to directly call epoll, bypassing NIO. Do you think this might limit the impact if we do instrument NIO?

**Comment by trask** [comment]
Based on recent SIG discussions, we are leaning towards avoiding instrumentation of low-level libraries (netty 👀) which have proven troublesome (e.g. request pipelining multiple requests over a single connection).

**Comment by iNikem** [comment]
> Based on recent SIG discussions, we are leaning towards avoiding instrumentation of low-level libraries (netty 👀) which have proven troublesome (e.g. request pipelining multiple requests over a single connection).

I think we don't want to rely on lower lever instrumentations for proper context propagation and span creation. But lower level instrumentations can certainly enrich existing CLIENT spans with interesting details.

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
