### ISSUE TITLE
Extract exporter setup to an artifact, or move to SDK

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1315]
I think using instrumentation without the javaagent is currently too complicated. `OpenTelemetrySdk.addSpanProcessor(BatchSpanProcessor.readFromStuff(OtlpGrpcSpanExporter.readFromStuff` is a mouthful, and additional work for setting up propagators on top often. We have logic in our agent that does this automatically, but I don't see why we can't either

a) Provide a function in an artifact, `OpenTelemetrySdk.setup()`
b) Don't even provide a separate artifact and let initialization happen automatically based on `OTEL_EXPORTER` variable in the SDK, not in the agent

**Comment by trask** [comment]
@anuraaga did u mean to open this in opentelemetry-java?

**Comment by anuraaga** [comment]
I'm not sure :) The code for setting up exporter is currently here. Don't know if it's better for us to extract an artifact here or push it to SDK.

**Comment by iNikem** [comment]
Is open-telemetry/opentelemetry-java#1149 related?

**Comment by anuraaga** [comment]
I think that issue is about allowing configuration, which is only possible with SPI at the moment. This is a bit opposite - to allow the SDK to configure itself as automatically as possible for standard use case.

**Comment by trask** [comment]
I believe this is resolved by SDK's new autoconfigure extension.
