### ISSUE TITLE
Capture all request and response headers

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1316]
We have a requirement to capture all request and response headers. This use case has also come up in different instrumentation libraries in OpenTracing project.

By default the feature should be disabled. There should be also a configuration to specify which headers should be collected e.g. CAPTURE_REQUEST_HEADERS=content-type,foo,bar or all - CAPTURE_REQUEST_HEADERS_ALL=true. The configuration properties are a subject for a change.

I will submit a spec issue to define data semantics for headers. e.g. request.header.foo=value and response.header.foo=value2 

Related issues in this project: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/776 and https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/566#issuecomment-655942298

**Comment by trask** [comment]
Closing, please re-open once there is semantic convention for this.
