### ISSUE TITLE
Capture request and response bodies

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1317]
We have a requirement to capture all request and response bodies. Capturing bodies is more complicated bc it requires wrapping read/write streams - so additional configuration. This feature should be disabled by default with no cost for people who don't want to capture any bodies.

The use case is for business transaction monitoring http://trasier.com/ and security.

I will submit a spec issue to define data semantics for request and response bodies.

EDIT: another issue with wrapping https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1096

**Comment by iNikem** [comment]
Just a friendly warning :) See #726, #1083 and related PRs. We already tried to add wrappers, it ended badly

**Comment by trask** [comment]
Closing, please re-open once there is semantic convention for request/response bodies.
