### ISSUE TITLE
Enable hacktoberfest topic?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1318]
This year there was a lot of spam and they've made hacktoberfest opt-in for repos by adding a topic named hacktoberfest. 

https://hacktoberfest.digitalocean.com/hacktoberfest-update

I think hacktoberfest is in general a nice idea, and would like to enable this, unless we get a lot of spam and may consider disabling it then. Any thoughts?

**Comment by trask** [comment]
I have no objection 👍

**Comment by iNikem** [comment]
I am a little bit cautious about this. In general it is a good idea, but as we approach GA, will it speed us up or slow down?

**Comment by anuraaga** [comment]
I understand the caution. I think as long as we don't get spammed it should be ok if some more PRs come in. On the first sign of spam we disable it - does that sound reasonable?

**Comment by anuraaga** [comment]
Enabled, let's see how it goes!
