### ISSUE TITLE
Change logging exporter from System.out to SLF4J

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1328]
Tracking proposal from @anuraaga https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1313#issuecomment-703035396

Makes sense to me, logging at INFO level, which we enable by default.

**Comment by Anisha-28** [comment]
Hi .. can. i work on this issue 
Would appreciate some clarification please

**Comment by iNikem** [comment]
@Anisha-28  There is [LoggingExporter](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/javaagent-exporters/logging/src/main/java/io/opentelemetry/javaagent/exporters/logging/LoggingExporter.java) which just prints all created spans. Right now it is using `System.out.println`. The goal of this is to replace `System.out` with `org.slf4j.Logger` logger, as many other classes in this repo.

**Comment by iNikem** [comment]
If you wish to take this issue, I can assign it to you.

**Comment by Anisha-28** [comment]
yes @iNikem i will do it .. Thanks for explaining though

**Comment by Anisha-28** [comment]
@iNikem i have committed a change if you can see it .. and let me know if i did it right

**Comment by nitram509** [comment]
@Anisha-28 once you have committed, don't forget to push it too and create a pull request.
(if you just did commit, no one can see it)

Cheers 
Martin
