### ISSUE TITLE
Set net peer for gRPC client

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1338]
When separating out library instrumentation from auto, we removed an auto-specific workaround for setting net peer. Clients should provide the net peer in general, and gRPC does do so with an "ExperimentalApi". Going to dig for ways without that, or to find a way with the existing APIs, before requiring users to pass in the net peer themselves.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1329#discussion_r500031829

**Comment by mateuszrzeszutek** [comment]
`net.peer.*` attributes are now added by `GrpcNetAttributesExtractor` -- `peer.service` was still missing though, will be added in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3357

**Comment by ralphgj** [comment]
Hi, I used agent of v1.10.0 and then I found the grpc client spans don't capture the attributes of `net.peer`. But in this issue, it seems being already resolved.
I use the [grpc-java examples](https://github.com/grpc/grpc-java/tree/master/examples/src/main/java/io/grpc/examples/helloworld) as the demo.

**Comment by trask** [comment]
hi @ralphgj, can you open a new issue for this? thx!

**Comment by ralphgj** [comment]
> hi @ralphgj, can you open a new issue for this? thx!

yeah, I will do it.
