### ISSUE TITLE
Make Config a bit less static

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1345]
The aim of this issue is to make `Config` return wrapped values: `ConfigValue<T>` instead of `T`. Users of this API can store `ConfigValue`s in static final constants as before, but call `ConfigValue#get()` whenever the actual value is needed.
There could be two `ConfigValue<T>` implementations:
* One that has a `private final T` field and is initialized only once, always returning the same value -- used in the agent;
* One that retrieves the value from current config instance (`Config#get()`) each time `ConfigValue#get()` is called -- used in tests.
This way mutating `Config` in tests would be less error-prone (issues like #1306 could be avoided) and probably we could avoid at least some `resetInstrumentation()` calls (maybe all of them).

See:
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1310#pullrequestreview-501679661
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1310#issuecomment-703525178
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1310#issuecomment-703986121

**Comment by trask** [comment]
I think this issue will not be needed after #1643, all tests have been refactored in that PR to not need dynamic config

**Comment by mateuszrzeszutek** [comment]
Let's close this issue after #1643 gets merged then.

**Comment by mateuszrzeszutek** [comment]
Not needed anymore because of #1643, closing.
