### ISSUE TITLE
Publish artifacts to maven central

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#135]
E.g.

io.opentelemetry.auto
* auto-tooling
* auto-bootstrap
* opentelemetry-auto (agent artifact)

io.opentelemetry.auto.instrumentation
* instrumentation-akka-http-10.0
* instrumentation-apache-httpasyncclient-4
* instrumentation-apache-httpclient-4
* instrumentation-aws-java-sdk-1.11.0
* instrumentation-aws-java-sdk-2.2
* instrumentation-cdi-1.2
* instrumentation-couchbase-2.0
* instrumentation-couchbase-2.6
* instrumentation-datastax-cassandra-3
* instrumentation-dropwizard
* instrumentation-dropwizard-dropwizard-views
* instrumentation-elasticsearch
* instrumentation-elasticsearch-rest-5
* instrumentation-elasticsearch-rest-6.4
* instrumentation-elasticsearch-transport-2
* instrumentation-elasticsearch-transport-5
* instrumentation-elasticsearch-transport-5.3
* instrumentation-elasticsearch-transport-6
* instrumentation-glassfish
* instrumentation-google-http-client
* instrumentation-grizzly-2
* instrumentation-grpc-1.5
* instrumentation-hibernate
* instrumentation-hibernate-core-3.3
* instrumentation-hibernate-core-4.0
* instrumentation-hibernate-core-4.3
* instrumentation-http-url-connection
* instrumentation-hystrix-1.4
* instrumentation-java-concurrent
* instrumentation-jax-rs-annotations-1
* instrumentation-jax-rs-annotations-2
* instrumentation-jax-rs-annotations-2-filter-jersey
* instrumentation-jax-rs-annotations-2-filter-resteasy-3.0
* instrumentation-jax-rs-annotations-2-filter-resteasy-3.1
* instrumentation-jax-rs-client-1.1
* instrumentation-jax-rs-client-2.0
* instrumentation-jax-rs-client-2.0-connection-error-handling-jersey
* instrumentation-jax-rs-client-2.0-connection-error-handling-resteasy
* instrumentation-jboss-classloading
* instrumentation-jdbc
* instrumentation-jedis-1.4
* instrumentation-jedis-3.0
* instrumentation-jetty-8
* instrumentation-jms
* instrumentation-jsp-2.3
* instrumentation-kafka-clients-0.11
* instrumentation-kafka-streams-0.11
* instrumentation-lettuce-5
* instrumentation-mongo
* instrumentation-mongo-driver-3.1
* instrumentation-mongo-driver-async-3.3
* instrumentation-netty-4.0
* instrumentation-netty-4.1
* instrumentation-okhttp-3
* instrumentation-osgi-classloading
* instrumentation-play-2.4
* instrumentation-play-2.6
* instrumentation-play-ws-1
* instrumentation-play-ws-2
* instrumentation-play-ws-2.1
* instrumentation-rabbitmq-amqp-2.7
* instrumentation-ratpack-1.4
* instrumentation-reactor-core-3.1
* instrumentation-rmi
* instrumentation-rxjava-1
* instrumentation-servlet
* instrumentation-servlet-request-2
* instrumentation-servlet-request-3
* instrumentation-sparkjava-2.3
* instrumentation-spring-data-1.8
* instrumentation-spring-webflux-5
* instrumentation-spring-webmvc-3.1
* instrumentation-spymemcached-2.12
* instrumentation-tomcat-classloading
* instrumentation-trace-annotation
* instrumentation-twilio
* instrumentation-vertx

Open question about instrumentation groupId:

* Consider lib ("contrib") instrumentation, and instead of io.opentelemetry.auto.instrumentation:
  * io.opentelemetry.instrumentation.auto
  * io.opentelemetry.instrumentation.lib

Open questions about instrumentation artifactIds:

* do we need `instrumentation-` prefix on artifact names?
* maybe keep prefix, but abbreviate, e.g. `instr-`?

**Comment by iNikem** [comment]
Do we really need to publish separate artifacts for each instrumentation?

Also, publishing to `jcenter` is usually much easier than Maven Central.

**Comment by trask** [comment]
The idea behind publishing all of the individual artifacts (#135) is for vendors who want more control/customization when building their distribution.

**Comment by trask** [comment]
Linking in #163, for a few remaining module renames we may want to consider before publishing to maven central

**Comment by iNikem** [comment]
Let us discuss open naming questions on SIG meeting and then I will make remaining renames as well.
