### ISSUE TITLE
Do not register more than one metric exporter

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1353]
See discussion in #1281

The reason for this is that each metric exporter calls `collectAllMetrics` which resets the metrics, and so if you register more than one metric exporter they will each only get partial metrics since the last time the other one called `collectAllMetrics`.

Open question: what to do if more than one metric exporter is specified in `OTEL_EXPORTER`?
* Log warning and don't register any?
* Log warning and register the first one?
* Log warning and give preference to the first metric exporter that isn't `otlp`
  * This would help with what will probably be a common mistake: `OTEL_EXPORTER=otlp,prometheus`
  * `OTEL_EXPORTER=otlp_metric,prometheus` would pick `otlp_metric` in this case

**Comment by iNikem** [comment]
> Log warning and register the first one?

+1

**Comment by anuraaga** [comment]
Env variables have changed so only one can be configured!
