### ISSUE TITLE
Tracking release 0.9.0

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1355]
Creating a tracking issue for release 0.9.0.

When is the release planned for? I can help with smth if it is in my powers :)

**Comment by iNikem** [comment]
We want to release it as soon as [these tasks](https://github.com/open-telemetry/opentelemetry-java-instrumentation/projects/8) are done.

**Comment by malafeev** [comment]
can be closed now
