### ISSUE TITLE
Pass Context explicitly to startSpan

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1360]
I ran into several cases in #1350 where we are putting Context into scope unnecessarily, which could be improved by passing Context as an argument to `startSpan`

Maybe also pass Context into `startScope` at the same time to address #1265

**Comment by trask** [comment]
Any thoughts on whether `Context` should always be the first or last parameter to these Tracer methods?

**Comment by iNikem** [comment]
First

**Comment by anuraaga** [comment]
First sounds good to me too - just for reference, I generally order things that are mutated last if they exist, and have overloads have the same order, otherwise no personal ordering rules in my book.
