### ISSUE TITLE
What's the plan for instrumentation-api module "GA"?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1371]
The `instrumentation-api` module needs a lot of work to be GA quality.

Some options for discussion (using `opentelemetry-grpc` as example of library instrumentation):

* GA `opentelemetry-grpc` and `instrumentation-api` at the same time we GA the javaagent
  * this would be ideal, but will require a lot of work at the same time as we are trying to get the javaagent to GA
* GA `opentelemetry-grpc` at the same time we GA the javaagent, but GA `instrumentation-api` sometime later
  * there's a better chance of us stabilizing API for specific library instrumentations, e.g. `opentelemetry-grpc` in this timeframe, though is a bit awkward to GA `opentelemetry-grpc` while not GA'ing `instrumentation-api` which it depends on
* GA `opentelemetry-grpc` and `instrumentation-api` sometime after we GA the javaagent

Probably the same question should be asked for `javaagent-spi`, `javaagent-api`, etc.

From an artifact versioning perspective, we could release as 1.0 anything that doesn't have a public API surface (e.g. `opentelemetry-javaagent-grpc`), and hold back things that _do_ have a public API surface (e.g. `opentelemetry-grpc`, `instrumentation-api`, `javaagent-api`, `javaagent-spi`) as 0.12 or whatever.

And then as those modules with API surface are ready to GA, they could skip and catch up to whatever the javaagent version is at that time (or they could continue to live independent versions, but I think generally easier to have less version numbers to remember).

**Comment by iNikem** [comment]
Independent versions is certainly a bad idea moving forward. And I don't particularly like piece-wise release as well. I see the benefit of claiming "javaagent has reached 1.0" as soon as possible, but still support the first version: release everything together when it is ready (quite unusual for me, I must say...)

**Comment by iNikem** [comment]
@open-telemetry/java-instrumentation-maintainers Any more opinions or we can close this discussion?

**Comment by anuraaga** [comment]
Having dates to target RC, milestone, GA etc can help with this. Do we have any dates that have been formalized? We can work backwards from that to form a plan for GA.

**Comment by iNikem** [comment]
I think Trask's question was _how_ should we release GA: all at once or piece by piece. My opinion was "all at once". After that we have our Roadmap to guide us, I think.

**Comment by trask** [comment]
Yeah, at the time I thought GA was much sooner, so was exploring options, but with OTel GA pushed out to include metrics, it seems good to target GA for the javaagent and the instrumentation-api at the same time.
