### ISSUE TITLE
Make muzzle generate helperClassNames() method

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1374]
I have an idea for improvement in muzzle & `Instrumenter.Default`: muzzle already collects all references to our internal helper classes when the ByteBuddy plugin executes - and it knows which classes are "our" classes and which ones are external (see `ReferenceCreationPredicate`). I believe that we can make use of this:
* we can gather all helper classes in `ReferenceCreator` and references to other helper classes - just a simple graph, even `Map<String, Set<String>>` would be fine;
* [sort the graph vertices](https://en.wikipedia.org/wiki/Topological_sorting) so that the classes can be injected in the correct order;
* make `MuzzleVisitor` generate one more method that just returns an array of strings (`getMuzzleHelperClassNames`?).

This way we won't have to write `helperClassNames()` manually for most of our instrumentations, since we usually inject classes that are in the conventional packages (i.e. `io.opentelemetry.javaagent.instrumentation.*`). There are two exceptions that I know of that inject `rx.__OpenTelemetryTracingUtil` and a shaded guava class (`KubernetesClientInstrumentation`), but for those we can just leave an `additionalHelperClasses()` method that those instrumentations can override and supply those unusual helpers.
For any other instrumentation the whole helper class injection process will be 100% automatic (same as in "normal Java") and will make using lambda functions viable (since muzzle will pick up the auto-generated `$1` classes by itself).
(Also it will make errors in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1274 disappear - although it's worth noting that the underlying problem does not get fixed this way)

WDYT?

**Comment by iNikem** [comment]
I like it 👍

**Comment by trask** [comment]
👍 I like that idea of stopping at some package name boundary in order to protect against accidentally (and silently) pulling in too much, and using `additionalHelperClasses()` for those exceptional cases

**Comment by anuraaga** [comment]
I remember @trask's idea of something similar to `spotlessApply` to automatically sync the helper class names mainly to prevent the accidental bloating. But if we can do that reliably automatically, that's even better :D

**Comment by pavolloffay** [comment]
What package names will be accepted as helper classes? This might be related to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1395 both issues are important for anybody extending the agent and adding instrumentations. Could we make both of them required for GA?

**Comment by mateuszrzeszutek** [comment]
Right now `InstrumentationClassPredicate` will handle it. But in the future we'll need to expose some SPI like you suggested. This will be necessary if we ever want to use muzzle in vendor distributions: the SPI will need to be present on the classpath both during compilation (so that `ReferenceCollector` sees the custom packages) and during runtime.
