### ISSUE TITLE
Mongo db.name attribute is incorrect

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1376]
Currently Mongo `db.name` is being captured as the `description` of the server, as opposed to the database name that the query is executed against.

**Comment by imavroukakis** [comment]
I can take this on if you'd like.

**Comment by trask** [comment]
that would be awesome 👍

**Comment by imavroukakis** [comment]
I assume that there are no tests that catch this, am I correct? Looking at the existing ones, it looks like `db.name` is set to the correct value

![image](https://user-images.githubusercontent.com/1764981/96367309-fae9b280-1144-11eb-8c4e-32b8ee9535ed.png)

**Comment by imavroukakis** [comment]
Ah whoops, I see it
![image](https://user-images.githubusercontent.com/1764981/96368613-929ecf00-114c-11eb-88bc-1746cb3a1fbc.png)
