### ISSUE TITLE
Embed java-classloader into javaagent-tooling

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1382]
Benefits:

* It's not really an optional instrumentation
* It could then rely on internal api, without having to expose more than needed in `javaagent-api` (e.g. in #1380)

We don't need generated muzzle matcher for this instrumentation, so I _think_ it could just be moved into javaagent-tooling without much hassle (but haven't tried, could be wrong).

We could keep java-classloader-testing module with the `jboss`, `osgi` and `tomcat` class loader testing more or less as is.

**Comment by iNikem** [comment]
If this is a required component for the functioning of the whole agent, then it makes sense.

**Comment by trask** [comment]
It seems like good consensus for this change, turning this from a question into an issue...

**Comment by trask** [comment]
From https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2773#issuecomment-817584256

> Alternatively, we could rename the `classloaders` module into something like `internal` - classloader instrumentation is pretty crucial and the javaagent won't work properly without it.
