### ISSUE TITLE
Instrumentation API jar should not include SDKs

### ISSUE THREAD

**Issue by marcingrzejszczak** [open-telemetry/opentelemetry-java-instrumentation#1385]
When I add instrumentation-api JAR to the classpath I'd assume that I have access only to the code of the instrumentations. That means that if I'm doing tracing and I add instrumentation-api, I'd assume that metrics-sdk JAR doesn't land on my classpath as a transitive dependency. Maybe it would be worth repackage the code in such a way that metrics & tracing are better separated (for example via optional dependencies for tracing / metrics in the api module?)? To achieve this goal I needed to do the following:

```xml
<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-sdk-tracing</artifactId>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-sdk-baggage</artifactId>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry.instrumentation</groupId>
			<artifactId>opentelemetry-instrumentation-api</artifactId>
			<exclusions>
				<exclusion>
					<groupId>io.opentelemetry</groupId>
					<artifactId>*</artifactId>
				</exclusion>
				<exclusion>
					<groupId>io.opentelemetry.instrumentation</groupId>
					<artifactId>*</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
```

That way I explicitly define that I want baggage and tracing, but I don't want metrics. By adding `opentelemetry-instrumentation-api` without exclusions I do get metrics as well.

**Comment by mateuszrzeszutek** [comment]
The latest instrumentation-api version no longer includes any SDK: https://mvnrepository.com/artifact/io.opentelemetry.instrumentation/opentelemetry-instrumentation-api/0.16.1
