### ISSUE TITLE
Lettuce 5.1 instrumentation should log normalised commands as db.statement

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1386]
Currently Lettuce 5.1 instrumentation logs full Redis command as `db.statement`, including all arguments/parameters.
We should normalise commands before storing them in a span -- same way as Lettuce 4.0 and 5.0 (and all other Redis instrumentation in this codebase) do.

**Comment by anuraaga** [comment]
I think the 5.1 is the only one that came after the spec clarified statement to be the same value as the Redis CLI.

https://www.github.com/open-telemetry/opentelemetry-specification/tree/master/specification%2Ftrace%2Fsemantic_conventions%2Fdatabase.md

Does normalizing also satisfy that?

**Comment by mateuszrzeszutek** [comment]
> For Redis, the value provided for db.statement SHOULD correspond to the syntax of the Redis CLI. If, for example, the HMSET command is invoked, "HMSET myhash field1 'Hello' field2 'World'" would be a suitable value for db.statement.

Hmm, that changes everything - I was under the impression that we should drop the arguments of the command/query to avoid capturing sensitive data.
Maybe we can log `db.operation` instead, depending on a configuration value... I need to think about it some more.

Anyway, thanks for bringing this up!

**Comment by mateuszrzeszutek** [comment]
Okay, let me correct myself then: let's just mask the values, i.e. the example `HMSET myhash field1 'Hello' field2 'World'` command from spec would be transformed to `HMSET myhash field1 ? field2 ?` - which is similar to what we're doing with SQL queries.

This can be easily done for Lettuce 5.1, I'm not sure about earlier versions or other libs (Jedis, Redisson, ...) - I'll check other Redis instrumentations and create a similar issue for those that can log the whole statement.
