### ISSUE TITLE
Add OpenTelemetry instrumentation BOM

### ISSUE THREAD

**Issue by asarkar** [open-telemetry/opentelemetry-java-instrumentation#1390]
https://github.com/open-telemetry/opentelemetry-java/issues/1719#issuecomment-708623416

> The BOM in question for this issue is for the API and SDK and extensions, not for the instrumentation repository, which is a different project over here: https://github.com/open-telemetry/opentelemetry-java-instrumentation

**Comment by asarkar** [comment]
@iNikem there is an alpha bom available now, is the `release:after-ga` label still applicable, or should this be needed for GA now?

**Comment by trask** [comment]
I think we can close this, is there anything missing that you need?

**Comment by asarkar** [comment]
I think the ask of this story is met, closing. Thank you.
