### ISSUE TITLE
ClassNotFoundException when trying to use with Armeria 1.0

### ISSUE THREAD

**Issue by smax48** [open-telemetry/opentelemetry-java-instrumentation#1392]
When I start my application that uses Armeria 1.0, I get the following error:
```
java.lang.ClassNotFoundException: io.opentelemetry.instrumentation.auto.armeria.v1_0.ArmeriaServerBuilderInstrumentation$SuppressDecoratorAdvice
```

I am using the latest 0.8.0 version of the agent (opentelemetry-javaagent-all.jar), and it produces some logs initially before throwing that error:
```
[opentelemetry.auto.trace 2020-10-14 22:55:40:857 +0000] [main] INFO io.opentelemetry.javaagent.tooling.TracerInstaller - Installed span exporter: io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter
[opentelemetry.auto.trace 2020-10-14 22:55:40:866 +0000] [main] INFO io.opentelemetry.javaagent.tooling.TracerInstaller - Installed metric exporter: io.opentelemetry.exporters.otlp.OtlpGrpcMetricExporter
[opentelemetry.auto.trace 2020-10-14 22:55:40:874 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 0.8.0
```

Maybe I am missing something in the app configuration?...

**Comment by trask** [comment]
hey @smax48, can you [enable debug logging](https://github.com/open-telemetry/opentelemetry-java-instrumentation#troubleshooting) and post the full log file?

**Comment by smax48** [comment]
Hi @trask, sure - see the attached file.
The very last message is from our app logger, everything else is produced by OT agent

[opentelemetry.l2020-10-15.log](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/5382305/opentelemetry.l2020-10-15.log)

**Comment by trask** [comment]
Oh, interesting, I think this is caused by not inlining the advice (inline = false) at https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/30e75c6d6d1b13b8b08874e5d7bc641fcd9a683f/instrumentation/armeria-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/armeria/v1_0/ArmeriaServerBuilderInstrumentation.java#L58

**Comment by anuraaga** [comment]
I presumably accidentally left that in when debugging something, yeah let's fix it. And I guess add a checkstyle or something to prevent inline = false from merging :)

**Comment by imavroukakis** [comment]
@anuraaga I took a brief look and the checkstyle plugin doesn't seem to be applied, even though `instrumentation:jdbc` has a section excluding source from checkstyle, it's a bit confusing 😆 . Having said that, there is a checkstyle module that should do what you're after, called `ForbidAnnotationElementValue`

It could look something like this
```
<module name="ForbidAnnotationElementValue">
 <property name="annotationName" value="Advice.OnMethodEnter"/>
 <property name="elementName" value="inline"/>
 <property name="forbiddenElementValueRegexp" value="false"/>
</module>
```
