### ISSUE TITLE
Reduce scope of lazily loading under JBoss / custom log manager

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1410]
Instead of lazy loading the entire `TracerInstaller` under JBoss / custom log manager, we should lazy load only

* exporters (which often use Java SSL classes, which [started using java.util.logging in 8u232](https://bugs.openjdk.java.net/browse/JDK-8148188))
* jvm metrics (which use PlatformMBeanServer, which uses java.util.logging)

The advantage of not lazy loading the entire `TracerInstaller`, is to install bytebuddy instrumentation as early as possible, and limit the amount of class retransformation needed (which can lead to degraded performance by not being able to use FieldBackedProvider for state storage).

**Comment by mateuszrzeszutek** [comment]
This was actually fixed some time ago, the only thing that we're lady-loading right now are the runtime metrics.
