### ISSUE TITLE
Play instrumentation tests are not capturing route

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1415]
`PlayServerTest` overrides `expectedServerSpanName`, which shows it's not capturing the route (which `HttpServerTest` is expecting by default):

```
  String expectedServerSpanName(String method, ServerEndpoint endpoint) {
    return "netty.request"
  }
```

It seems that `PlayTracer.updateSpanName()` is not finding `ROUTE_PATTERN` needed to populate the route.

I think it may only be a problem with the tests, as it looks like `PlaySmokeTest` is capturing the route correctly.

**Comment by mcmho** [comment]
@trask   Should I work on this and get my hands dirty with unit testing?

**Comment by trask** [comment]
> @trask Should I work on this and get my hands dirty with unit testing?

@mcmho that would be great!

**Comment by mcmho** [comment]
feel free to assign to me.

**Comment by medicharlachiranjeevi** [comment]
Is this fixed ? . We are using play framework version 2.5 in Prometheus exporter there no route was included in http bucket metrics

**Comment by mateuszrzeszutek** [comment]
Hey @medicharlachiranjeevi ,
No, this has not been fixed yet.

**Comment by medicharlachiranjeevi** [comment]
Thanks for response @mateuszrzeszutek .Is there any alternate way to get those metrics ?

**Comment by trask** [comment]
I think we still need someone to dig into this issue

**Comment by mwy001** [comment]
+1 for this issue. Using the java agent to auto collect play 2.x http metrics, and no http_route label was included in the prometheus result.

**Comment by medicharlachiranjeevi** [comment]
hi, is there any eta on it?

**Comment by mateuszrzeszutek** [comment]
Hey @medicharlachiranjeevi ,
We don't have any ETA on this. Nobody from our core maintainer team is particularly familiar with Play, honestly we're hoping for an external contribution here.

**Comment by gurudatta-carbon** [comment]
@trask 
it works for us with a custom metric (similar to http.server.duration metric with http_route) defined part of play.api.mvc.Filter trait, 
Here I have a hold on RequestHeader object instance.
but it can retrieved from Request object as well,

this is the impl that works for us,

```
              val requestHeader: RequestHeader = req.request
              val handlerDefOpt: Option[HandlerDef] = requestHeader.handlerDef
              handlerDefOpt.map(handlerDef => attr += ("http.route" -> handlerDef.path))
```
req is of type Request.

**Comment by moznion** [comment]
@trask I suppose #7801 fixed this issue. What about closing this issue?
