### ISSUE TITLE
Resteasy client leads to duplicate spanId injections into http headers

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1422]
I have a bug report from the client who sees multiple spanIds injected into outgoing http requests:
```
x-b3-spanid : [7700a7830ef64c36, 7a2b99e5202c3214]
x-b3-traceid :[00000000000000006d776b6577656321,00000000000000006d776b6577656321]
x-b3-sampled : [1, 1]
```

They use Resteasy-jaxrs 3.1.4.Final. By default Resteasy uses Apache Http Client (AHC) under the hood. When I add our `apache-httpclient-4.0` instrumentation as test dependency to `jaxrs-client-2.0`, all Resteasy tests started to fail:

```
17:34:48.058 [Test worker] DEBUG io.opentelemetry.instrumentation.test.InMemoryExporter - >>>1603118088058001959 SPAN START: HTTP GET id=b80393f07d812347 traceid=f88b3a57c349e7ed43385ab3f1383d0f parent=0000000000000000, library=InstrumentationLibraryInfo{name=io.opentelemetry.auto.jaxrs-client-2.0, version=null}
17:34:48.059 [Test worker] DEBUG io.opentelemetry.instrumentation.test.InMemoryExporter - >>>1603118088059001301 SPAN START: HTTP GET id=5ceedbb271029c7a traceid=3eb4fd91c8698af8048ba8b8ed711355 parent=0000000000000000, library=InstrumentationLibraryInfo{name=io.opentelemetry.auto.apache-httpclient-4.0, version=null}
```

The reason for this is two-fold. First, AHC instrumentation does not check if `CLIENT` span already exists and it should not create a new one. Second, even if AHC did that, it would not help, because jaxrs-client instrumentaiton does NOT install itself as the active span for the duration of the request. See `io.opentelemetry.javaagent.instrumentation.jaxrsclient.v2_0.ClientTracingFilter#filter(javax.ws.rs.client.ClientRequestContext)`

**Comment by iNikem** [comment]
Correction, AHC instrumentation DOES check if CLIENT span already exists.

**Comment by umutesen** [comment]
We're experiencing duplicate http spans with Jersey using ApplicationInsights Java Agent. It is our understanding that Application Insights use Open Telemetry internally.

When our Spring Boot API issues a GET request, the following remote dependencies are collected for the call. The only notable difference is `io.opentelemetry.http-url-connection` vs `io.opentelemetry.jaxrs-client-2.0`.

```
instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.http-url-connection, version=null, schemaUrl=null}, name=HTTP GET, kind=CLIENT, startEpochNanos=1645224991573912700, endEpochNanos=1645224991581594500, attributes=AttributesMap{data={net.transport=ip_tcp, net.peer.name=vcpjdbgsmade01.rlg.test, http.status_code=200, http.user_agent=OpenAPI-Generator/1.0/java,
```
Duplicate span exported:
```
instrumentationLibraryInfo=InstrumentationLibraryInfo{name=io.opentelemetry.jaxrs-client-2.0, version=null, schemaUrl=null}, name=HTTP GET, kind=CLIENT, startEpochNanos=1645224991573647600, endEpochNanos=1645224991583595900, attributes=AttributesMap{data={http.response_content_length=105, net.transport=ip_tcp, net.peer.name=vcpjdbgsmade01.rlg.test, http.status_code=200
```


As a side-note, this is how we configure `HttpClient`:

```
final ClientConfig clientConfig = new ClientConfig();
    clientConfig.register(MultiPartFeature.class);
    clientConfig.register(json);
    clientConfig.register(JacksonFeature.class);
    clientConfig.property(HttpUrlConnectorProvider.SET_METHOD_WORKAROUND, true);
    if (debugging) {
      clientConfig.register(new LoggingFeature(java.util.logging.Logger.getLogger(LoggingFeature.DEFAULT_LOGGER_NAME), java.util.logging.Level.INFO, LoggingFeature.Verbosity.PAYLOAD_ANY, 1024*50 /* Log payloads up to 50K */));
      clientConfig.property(LoggingFeature.LOGGING_FEATURE_VERBOSITY, LoggingFeature.Verbosity.PAYLOAD_ANY);
      // Set logger to ALL
      java.util.logging.Logger.getLogger(LoggingFeature.DEFAULT_LOGGER_NAME).setLevel(java.util.logging.Level.ALL);
    }
    performAdditionalClientConfiguration(clientConfig);
    return ClientBuilder.newClient(clientConfig);
```

**Comment by trask** [comment]
hi @umutesen, can you open a new issue for this at https://github.com/microsoft/ApplicationInsights-Java? if you can include the version you are using and a working repro that would be helpful, thx!
