### ISSUE TITLE
Resource context is lost when an application is loaded dynamically (WAR)

### ISSUE THREAD

**Issue by jamal** [open-telemetry/opentelemetry-java-instrumentation#1423]
I'm investigating an issue where I provide a `ResourceProvider` implementation in my service that adds custom attributes (such as `service.name` and `service.version`), but are then not retained in any of the generated traces. This service is being deployed as a WAR, so it is loaded _after_ the initialization of the agent and thus the agent is not able to find this `ResourceProvider`.

Because of how this is designed, the service has its own ClassLoader, so calling `OpenTelemetry.getTraceProvider.get()` does in fact end up in the application class that has those resource attributes set in the shared state. The issue is that, the `ApplicationTracerProvider` wrapper ends up calling the shaded `OpenTelemetry` which only has the context that was visible to the agent during initialization.

It looks like, if we were to either: call the application `OpenTelemetry` or use `applicationOriginalTracerProvider` [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/opentelemetry-api-beta/src/main/java/io/opentelemetry/javaagent/instrumentation/opentelemetryapi/trace/ApplicationTracerProvider.java#L36) we would be able to retain this context.

This would incur an additional bridging conversion. But, I'm wondering if this is would be a solution to this problem? Are there other recommendations?

I've been experimenting with this issue a bit to try to resolve it for my application, so would be happy to move forward with an implementation that makes sense. But, given that I have very little context into why things were implemented this way, would prefer to have a conversation around the topic first.

**Comment by trask** [comment]
Hey @jamal!

So far, the agent only instruments OpenTelemetry API that is brought by user application, and doesn't instrument OpenTelemetry SDK that is brought by user application.

Which means that anything the user application does with the SDK is ignored by the agent, including samplers, span processors, resource providers, etc.

Would `OTEL_RESOURCE_ATTRIBUTES` work for you? Or do you need something more programmatic?

**Comment by jamal** [comment]
That makes sense, and was definitely my findings. I was trying to think of a way to work around the problem but it doesn't seem trivial. 

I have worked around the basic problem by passing the attributes as jvm args as you suggested, but I'd like to be able to do this programmatically in the future to be able to package this into a library that the rest of my team can consume. But it's not a big requirement. 

Are there any goals to support that in the future? I'd be happy to chat more about that and see how we could support such a workflow someday. Thanks for the feedback!

**Comment by trask** [comment]
Current plans include making it easier (and well documented) how to build your own agent "distro" which supports customizing the (embedded) SDK, e.g. samplers, span processors, resource providers.

The downside to that approach is it requires always re-building your distro for each new version.

Another option that could work is to load resource providers from an external jar file, similar to how `OTEL_EXPORTER_JAR` works currently.

**Comment by jamal** [comment]
I think having an agent "distro" would make sense for some of the use cases I want to support, so it would be great to learn more about that.

With regards to the issues I'm facing here, the problem is with regards being able to support multiple applications since we load two WARs for two APIs. I know that your documentation calls out lack of support for this with how the agent is designed today. I'm not sure if this is something that should be supported in the agent or not, but would be great to understand that more. I will have to familiarize myself with the architecture of the agent before I can really dig into this any further.

With regards to a custom exporter, I'll have to investigate this option and see how it works. Besides multiple applications, the other issue I'm dealing with is being able to resolve information after the application is loaded which happens after the agent is initialized. The reason for this is that some of the data that I would want to act on only exists in the classpath of the application.

I understand that this is a complicated problem and may not be directly supported in the agent today. I'm just trying to figure out what could be done to improve that in the future. Thanks!

**Comment by trask** [comment]
Check out the new agent extension mechanism which gives you the full customization capabilities of the OpenTelemetry SDK https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension#introduction

**Comment by trask** [comment]
Closing, let us know if you're still having this issue and we'll re-open.
