### ISSUE TITLE
Should we remove OTEL_EXPORTER_JAR in the future?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1424]
Assuming that building your own Java agent distro with your own exporter is easy / well-documented (which it is not today), do we need to continue supporting `OTEL_EXPORTER_JAR`?

Not proposing that we remove it right away, as I know that New Relic is using this feature for now, but knowing its future will help us make some other decisions, e.g. https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1287#issuecomment-712579515

**Comment by iNikem** [comment]
I think we should. E.g. for situations where some user wants to use vendor distribution but still use external exporter due to specifics of their environment.

**Comment by jasonjkeller** [comment]
@trask What is the general process for building your own Java agent distro with a custom exporter? Would it follow the general pattern established with the [existing default exporters](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/master/javaagent-exporters) but in a separate fork? Or is there an alternative standardized approach that you could point me at? 

We (New Relic) are definitely interested in a custom Java agent distro (and even better if we can help to simplify this project in doing so!) but it is not clear if there is a recommended way to approach this?

If you can provide any suggestions/guidance we would certainly be happy to help drive the documentation efforts and ideally come up with something that makes the process straightforward for all vendors.

**Comment by trask** [comment]
hey @jasonjkeller! we could definitely use help at the very least documenting how to do this.

@anuraaga has an example here
* https://github.com/anuraaga/aws-opentelemetry-java-instrumentation/blob/master/otelagent/build.gradle.kts
* https://github.com/anuraaga/aws-opentelemetry-java-instrumentation/blob/master/awsagentprovider/build.gradle.kts

The general idea is to use the javaagent SPIs and the (shaded) SDK SPIs, and bundle those up into the published otel java agent, and then the otel java agent will use your SPI implementations where you can customize stuff.

Happy to answer more questions about this, this is a significant gap, and several folks have asked for better guidance on this.

**Comment by jasonjkeller** [comment]
Awesome, thanks! I'll dig into the links when I have a chance!

**Comment by iNikem** [comment]
@jasonjkeller One more example is [Splunk distribution](https://github.com/signalfx/splunk-otel-java).

**Comment by iNikem** [comment]
I realised my comment from above is vague :) I think we should continue supporting `OTEL_EXPORTER_JAR` to simplify one of the most common cases for extension.

@trask @anuraaga Can we close this discussion?

**Comment by iNikem** [comment]
Demo repository demonstrating various ways to extend our distribution: https://github.com/iNikem/opentelemetry-java-instrumentation-demo

**Comment by anuraaga** [comment]
I'm good with continuing to support the option :)
