### ISSUE TITLE
Introduce instrumenters (and move away from just tracers)

### ISSUE THREAD

**Issue by as-polyakov** [open-telemetry/opentelemetry-java-instrumentation#1429]
## Problem statement ##
we currently only do tracing in opentelemetry-java-instrumentaiton. We need to do metrics and potentially logs at some stage. For this we need another abstraction - "instrumented" to replace and extend whatever tracer is currently doing

## Proposed solution ##
Introduce Instrumenter instead of tracer, so for example this SpringWebMVC code changes from ([this place](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/spring/spring-webmvc-3.1/library/src/main/java/io/opentelemetry/instrumentation/spring/webmvc/WebMvcTracingFilter.java#L33))
```
public void doFilterInternal(
      HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
      throws ServletException, IOException {
    Span serverSpan = tracer.startSpan(request, request, FILTER_CLASS + "." + FILTER_METHOD);

    try (Scope ignored = tracer.startScope(serverSpan, request)) {
      filterChain.doFilter(request, response);
      tracer.end(serverSpan, response);
    } catch (Throwable t) {
      tracer.endExceptionally(serverSpan, t, response);
      throw t;
    }
  }
```

to
```
public void doFilterInternal(
      HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
      throws ServletException, IOException {
    Context operationCtx = instrumenter.startOperation(request, request, FILTER_CLASS + "." + FILTER_METHOD);

    try (Scope ignored = operationCtx.makeCurrent()) {
      filterChain.doFilter(request, response);
      instrumenter.end(operationCtx, response);
    } catch (Throwable t) {
      instrumenter.endExceptionally(serverSpan, t, response);
      throw t;
    }
  }
```

Idea is that a family of Instrumenter's can provide a unified abstraction for working with spans, metrics and other telemetry as well as set of well defined extension points for users to inject their logic. One specific example could be  - allow for customer hook to parse the request and extract needed stuff into context before instrumentation kicks in ([this code](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/HttpServerTracer.java#L59) is changed):

```
public Context startOperation(
      REQUEST request, CONNECTION connection, String spanName, long startTimestamp) {
    
    Context context = extract(request, getGetter())
    context = onContextCreationHook(context, request)  //<<< this is an extension point

    Span.Builder builder =
        tracer.spanBuilder(spanName).setSpanKind(SERVER).setParent(context);
...
```

**Comment by iNikem** [comment]
This may be an interesting idea to explore. But we certainly will not have a capacity for this before GA.

**Comment by bogdandrutu** [comment]
@parallelstream you mentioned that you may have resources to help with this. It would be good to pick one instrumentation, change it based on the feedback and prove that also fixes #1481

**Comment by parallelstream** [comment]
working on it

**Comment by parallelstream** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1871

**Comment by trask** [comment]
Closing, implementation of new Instrumenter API is being tracked in #2713
