### ISSUE TITLE
Standardize DB query normalizer property names

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1431]
Right now we only have one property for SQL (JDBC): `sql.normalizer.enabled`. How about renaming it to something like `otel.query.normalizer.<db>.enabled`, `otel.<db>.query.normalizer.enabled`? We could use separate config properties for each query normalizer that's used in the agent (enabled by default).

Regarding the `<db>` placeholder: should we use the `DbSystem` name or the query language name (sql, cql, n1ql, ...)? I think it makes more sense to disable per query language, but on the other hand it introduces a new concept/dimension (you have to know which instrumentation/`DbSystem` uses which language).

**Comment by trask** [comment]
Does it work to conform to `otel.instrumentation.<instrumentationid>.*` proposed in #1414?

E.g. `otel.instrumentation.jdbc.query.normalizer.enabled`

**Comment by mateuszrzeszutek** [comment]
Hmm, that sounds good. The only "problem" that I can think of is with Redis, which has multiple instrumentations - but I believe that if for some reason you want to disable sanitization then you probably know which Redis library you're using.
