### ISSUE TITLE
Make opentelemetry-trace-span-key publicly visible

### ISSUE THREAD

**Issue by asarkar** [open-telemetry/opentelemetry-java-instrumentation#1435]
gRPC context keys are compared using referential equality (see https://stackoverflow.com/a/57099181/839733). `TracingContextUtils.CONTEXT_SPAN_KEY` being `private`, it makes impossible to get the span out of the context without reflection hacks.
Please make it `public`, since that doesn't hurt anybody, and makes it possible for the client code to retrieve the span if they want to.

**Comment by anuraaga** [comment]
@asarkar Can't you use `TracingContextUtils.getSpan(Context)` to retrieve the span? Also FYI working on improving the API a bit in https://github.com/open-telemetry/opentelemetry-java/pull/1843

**Comment by asarkar** [comment]
I had missed `TracingContextUtils.getSpan(Context)`, closing this ticket.
