### ISSUE TITLE
Instrumentation names for javaagent vs library instrumentation

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1436]
Should the instrumentation name be the same for both javaagent and library instrumentation?

E.g. `io.opentelemetry.grpc`

Or should they be different?

E.g. `io.opentelemetry.grpc` and `io.opentelemetry.javaagent.grpc`

We have the `telemetry.auto.version` resource attribute, but that will be applied to library instrumentation when running under the javaagent also, so I don't think we will be able to tell whether spans originated from javaagent instrumentation or library instrumentation in this case.

I'm not sure how important this is to know this difference though (and our goal is to suppress library instrumentation in this case #903).

If we want the instrumentation names to be different, one option would be for the javaagent to pass in named tracers when constructing the library tracers.

**Comment by devinsba** [comment]
From a code convention point of view, if you were to use the same packages for both then you could use package private classes and methods where classes need to be accessed from the agent. This also has the benefit of decreasing bytecode size

**Comment by mateuszrzeszutek** [comment]
Should we use the following pattern for all our instrumentation names:
```
io.opentelemetry.{instrumentedLibName}-{instrumentedLibMinVersion}
```
?

**Comment by trask** [comment]
It would be nice to be able to tell the difference between library and javaagent instrumentation when they are both present (to see which one backed off for example).

**Comment by mateuszrzeszutek** [comment]
Won't spans created by javaagent have the `telemetry.auto.version` resource attribute?

Also, we already have a couple of javaagent instrumentations that simply add the library interceptor/listener, the same way as how library instrumentation is supposed to be used. We don't change their instrumentation names, same value as library instrumentation is passed to the `TracerProvider`. If we want to distinguish between javaagent and library instrumentations, shouldn't we change that?

**Comment by anuraaga** [comment]
Yeah I feel as if which code creates the spans is always deterministic - it might be a bit simpler to distinguish them if the names are different but don't think it's worth extra complexity (we can't expose instrumentation name as an option in library instrumentation, so any solution for sharing library instrumentation with javaagent and making the names different seems quite difficult).

**Comment by trask** [comment]
> I feel as if which code creates the spans is always deterministic

I'm not clear what you mean, can you clarify?

**Comment by trask** [comment]
@anuraaga @mateuszrzeszutek and I discussed this in meeting yesterday, summary:
* we can't use `telemetry.auto.version` to differentiate, since javaagent will stamp that on library instrumentation also (since library instrumentation telemetry goes over the bridge and gets sent out by the javaagent)
* being able to differentiate is not a critical issue for now, so makes sense to go with @mateuszrzeszutek proposal above https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1436#issuecomment-864975795, and we can always revisit later
