### ISSUE TITLE
gRPC client spans are missing net.peer.* attributes

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1449]
At least one of `net.peer.ip` or `net.peer.name` is required https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/rpc.md#attributes

**Comment by anuraaga** [comment]
Think this is duplicate of #1338 :)

**Comment by trask** [comment]
I lost that brain cell too 😭
