### ISSUE TITLE
Agent SPI are not usable by application developer

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1463]
SPIs that we expose in `javaagent-spi` module cannot actually be used by an application developer, only by vendor who repackages the whole agent.

The first problem is that this module exposes SDK classes, e.g. `TracerCustomizer` exposes `io.opentelemetry.sdk.trace.TracerSdkManagement`. But module itself does not depend on SDK, so user has to add two modules to their pom/gradle.

Second problem is that `TraceInstaller` searches for them only in bootstrap classloader. So services packaged with application and loaded in user classloader are not found.

**Comment by trask** [comment]
I think a third problem is that we would have to bridge from the user's class loader to the `AgentClassLoader`

**Comment by longXboy** [comment]
hi，any updates？

**Comment by iNikem** [comment]
> hi，any updates here？We happened to have this problem recently。We cannot extend the spi of the agent at the application code layer
> @trask @iNikem

Can you describe your use-case? What are you trying to achieve?

**Comment by iNikem** [comment]
This use-case is now addressed by extensions support: https://github.com/open-telemetry/opentelemetry-java-instrumentation#creating-agent-extensions
