### ISSUE TITLE
Can't import the project

### ISSUE THREAD

**Issue by marcingrzejszczak** [open-telemetry/opentelemetry-java-instrumentation#1465]
I can't see any special instructions on how to import the project, however when I import it to Intellij I get

```
Could not find netty-transport-native-unix-common-4.1.50.Final-linux-x86_64.jar (io.netty:netty-transport-native-unix-common:4.1.50.Final).
```

Should I do something special to import this project?

**Comment by anuraaga** [comment]
I don't think there's anything special, I just opened the folder in IntelliJ. We have a massive amount of dependencies and what I have seen is flakiness that leaves the module corrupted locally and needed to remove that manually from the gradle store. Do you mind trying to remove this one and trying again?

**Comment by anuraaga** [comment]
Of course if you locally don't have any module named that, there is a bug in the configuration we need to squash, but for me it's currently ok.

**Comment by marcingrzejszczak** [comment]
Most likely you have a bug then cause I just imported the project and since I don't have that dep the project failed to import

**Comment by iNikem** [comment]
I have the same problem with the same file when I try to run `muzzle` locally

**Comment by marcingrzejszczak** [comment]
I hacked it around by doing this but that's ridiculous :P

```
cp ~/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.50.Final/netty-transport-native-unix-common-4.1.50.Final.jar ~/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.50.Final/netty-transport-native-unix-common-4.1.50.Final-linux-x86_64.jar
```

**Comment by kubawach** [comment]
FYI - experienced similar issue today. Gradle was unable to resolve one of Finatra's dependency: `Could not find netty-transport-native-epoll-4.1.51.Final-linux-aarch64.jar (io.netty:netty-transport-native-epoll:4.1.51.Final) `
Worked around same way as @marcingrzejszczak (by copying existing jar with different suffix).

**Comment by anuraaga** [comment]
@kubawach Are you using an ARM laptop (Apple M1?)?

**Comment by kubawach** [comment]
@anuraaga plain old x86-64 ;)

**Comment by trask** [comment]
@kubawach are you still seeing this (if you remove the jar you manually copied)?

**Comment by trask** [comment]
Just here to report that I just got this in Intellij too:

```
Could not find netty-transport-native-unix-common-4.1.54.Final-linux-x86_64.jar (io.netty:netty-transport-native-unix-common:4.1.54.Final).
Searched in the following locations:
    file:/C:/Users/trstalna/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.54.Final/netty-transport-native-unix-common-4.1.54.Final-linux-x86_64.jar
```

which is weird, because that artifact exists in maven central:

http://repo1.maven.org/maven2/io/netty/netty-transport-native-unix-common/4.1.54.Final/netty-transport-native-unix-common-4.1.54.Final-linux-x86_64.jar

What worked for me to resolve:

```
rm -rf ~/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.54.Final
```

and refresh the Intellij gradle configuration.

**Comment by kubawach** [comment]
@trask tried to recreate, multiple attempts, no luck (which is good I guess ;) ).

**Comment by trask** [comment]
Closing, based on my experience above, it seems like this is due to local maven repo corruption, not sure we have any control over(?).

If you run into this issue, please try:

```
rm -rf ~/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.54.Final
```

and refresh your Intellij gradle configuration.

If that doesn't resolve the issue, please post your experience and details here, and we will re-open this issue.
