### ISSUE TITLE
Question about external-annotations muzzle

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1490]
We currently have this muzzle which passes

```
muzzle {
  pass {
    group = "io.opentracing.contrib.dropwizard"
    module = "dropwizard-opentracing"
    versions = "[0.2.2,)"
  }
}
```

but if I ad other dependencies, they all seem to fail

```
muzzle {
  pass {
    group = "com.newrelic.agent.java"
    module = "newrelic-api"
    versions = "[5.14.0,)"
  }
  pass {
    group = "io.opentracing.contrib.dropwizard"
    module = "dropwizard-opentracing"
    versions = "[0.2.2,)"
  }
}
```

I figured this would work so wondering if anyone can teach what's going on here :)

**Comment by mateuszrzeszutek** [comment]
It looks like dropwizard `Trace` annotation is hard-coded there just for test/muzzle purposes (`TraceConfigInstrumentation$TracerClassInstrumentation`):

```java
    /** No-arg constructor only used by muzzle and tests. */
    public TracerClassInstrumentation() {
      this("io.opentracing.contrib.dropwizard.Trace", Collections.singleton("noop"));
    }
```

There's even a hack for that specific class in `MuzzleGradlePluginUtil`.

Maybe once https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1274#issuecomment-707860035 is implemented the whole `TraceConfigInstrumentation` will be treated as a single `InstrumentationModule` and it'll make more sense.

**Comment by mateuszrzeszutek** [comment]
I've checked this issue once again, since `InstrumentationModule`s were all merged recently. Now the muzzle check does not fail for the `newrelic-api` dependency - in fact, since this instrumentation does not depend on any 3rd party API it shouldn't ever fail at all.
