### ISSUE TITLE
Enable checkstyle for google style guide

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1514]
We follow Google Java Style Guide (https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/docs/contributing/style-guideline.md), so we should add checkstyle enforcement for the same (e.g. https://checkstyle.sourceforge.io/google_style.html), which will be nice to avoid style nit reviews in PRs.

I'm guessing we may need to relax the base google java checkstyle in a few places due to weirdness that we need to do for bytecode instrumentation.

As a bonus goal, let's try to sync the checkstyle as much as possible between both Java repos.

**Comment by iNikem** [comment]
But spotless already checks for code style and fails PR if violated

**Comment by trask** [comment]
It didn't catch https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1513#discussion_r513743260

(https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used)

**Comment by trask** [comment]
Having checkstyle enabled would also allow us to do other things: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1392#issuecomment-714289045

**Comment by iNikem** [comment]
Ok, convinced 👍

**Comment by trask** [comment]
Closed by #1641, #1656, and #1666
