### ISSUE TITLE
Jdbc instrumentation is not capturing net.peer.name/net.peer.ip/net.peer.port

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1521]
From the [database semantic convention spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/database.md#connection-level-attributes):

> **Additional attribute requirements:** At least one of the following sets of attributes is required:
> 
> * [`net.peer.name`](span-general.md)
> * [`net.peer.ip`](span-general.md)

and net.peer.port is

> Required if using a port other than the default port for this DBMS.

**Comment by pavolloffay** [comment]
Has anybody looked into this?

**Comment by trask** [comment]
Closed by #2739!!
