### ISSUE TITLE
Run agent alongside other java agents - DataDog, AppDynamics, NewRelic...

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1534]
**Is your feature request related to a problem? Please describe.**

I would like to exclude classes from other agents. E.g. custom build of OTEL agent should run well alongside DataDog/AppDynamics/NewRelic agents.  I have noticed that OTEL agent is instrumenting DataDog classes e.g. the Okhttp sender that reports data to the platform.

**Describe the solution you'd like**

Exclude classes e.g. `datadog.*`/`com.newrelic` from being instrumented. The exclusion pattern should be configurable.

**Describe alternatives you've considered**

`OTEL_TRACE_CLASSES_EXCLUDE` didn't work in my case. So I am not sure if this is a bug or a different feature.

```
 OTEL_EXPORTER=jaeger OTEL_TRACE_CLASSES_EXCLUDE="datadog.*"  java -javaagent:${HOME}/projects/opentelemetry/opentelemetry-java-instrumentation/javaagent/build/libs/opentelemetry-javaagent-0.10.0-SNAPSHOT-all.jar -javaagent:${HOME}/tmp/dd-java-agent.jar -jar target/demo-0.0.1-SNAPSHOT.jar 
```

I could see the DD `PUT` to the platform span

![Screenshot of Jaeger UI (1)](https://user-images.githubusercontent.com/5618424/97733214-d47a2e80-1ad7-11eb-8bc2-334a5801e875.jpg)

**Additional context**

The following code disables instrumenting of other agents.

```diff
diff --git a/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/AgentInstaller.java b/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/AgentInstaller.java
index b7ef96a73..021a7a6f7 100644
--- a/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/AgentInstaller.java
+++ b/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/AgentInstaller.java
@@ -23,6 +23,7 @@ import io.opentelemetry.javaagent.tooling.config.ConfigInitializer;
 import io.opentelemetry.javaagent.tooling.context.FieldBackedProvider;
 import io.opentelemetry.sdk.OpenTelemetrySdk;
 import java.lang.instrument.Instrumentation;
+import java.security.ProtectionDomain;
 import java.util.ArrayList;
 import java.util.Arrays;
 import java.util.Collections;
@@ -125,8 +126,30 @@ public class AgentInstaller {
             .with(AgentTooling.locationStrategy())
             // FIXME: we cannot enable it yet due to BB/JVM bug, see
             // https://github.com/raphw/byte-buddy/issues/558
-            // .with(AgentBuilder.LambdaInstrumentationStrategy.ENABLED)
-            .ignore(any(), skipClassLoader());
+            .ignore(
+                new AgentBuilder.RawMatcher() {
+                  @Override
+                  public boolean matches(
+                      TypeDescription typeDescription,
+                      ClassLoader classLoader,
+                      JavaModule module,
+                      Class<?> classBeingRedefined,
+                      ProtectionDomain protectionDomain) {
+                    String[] ignoredNames = {
+                      "io.opentracing",
+                      "com.newrelic",
+                      "datadog",
+                      "com.appdynamics",
+                      "com.singularity.ee.agent"
+                    };
+                    String className =
+                        classLoader == null
+                            ? typeDescription.getTypeName()
+                            : classLoader.getClass().getName();
+                    return matchesIgnoredClassName(ignoredNames, className);
+                  }
+                });
 
     ignoredAgentBuilder =
         ignoredAgentBuilder.or(globalIgnoresMatcher(skipAdditionalLibraryMatcher));
@@ -162,6 +185,16 @@ public class AgentInstaller {
     return agentBuilder.installOn(inst);
   }
 
+  private static boolean matchesIgnoredClassName(String[] ignoredClasses, String className) {
+    for (String ignoredClass : ignoredClasses) {
+      if (className.startsWith(ignoredClass)) {
+        return true;
+      }
+    }
+
+    return false;
+  }
+
   private static Iterable<Instrumenter> orderInstrumenters(Iterable<Instrumenter> instrumenters) {
     List<Instrumenter> orderedInstrumenters = new ArrayList<>();
     instrumenters.forEach(orderedInstrumenters::add);
```

**Comment by iNikem** [comment]
> custom build of OTEL agent should run well alongside DataDog/AppDynamics/NewRelic agents

I don't believe in this statement :) In my experience two bytecode modifying agents should never run together because this leads to unpredictable results.

**Comment by trask** [comment]
we discussed this in a SIG meeting a while back, and DataDog and NewRelic folks mentioned that running side-by-side with other APM java agents is not something they recommend or support, so it was recommended that we do the same, to avoid headaches for ourselves and our users.

`OTEL_TRACE_CLASSES_EXCLUDE` would be good to fix though.

**Comment by pavolloffay** [comment]
Even if we exclude other agent's classes can the JVM for example unpredictably crash? Maybe also
@tylerbenson would know this?

**Comment by tylerbenson** [comment]
We have certainly had competitor agents running along side ours, but results are mixed.  I think the biggest problem is when one agent modifies classes being used internally by the other.  (This can also affect a solitary javaagent and is a big motivation for our changes in the DD repo to avoid using standard/instrumented executors and use a custom one instead.)

It certainly isn't a configuration we encourage, but when possible we have tried to add work arounds to be a nice neighbor.  I'd suggest a similar position here.  If there's an obvious problem, then we should document it and maybe someone (otel or the vendor) can fix it.

**Comment by tylerbenson** [comment]
(To answer your original question, since it's in an isolated classloader, we don't actually shade okhttp in the DD project.  This means that your suggestion to ignore it via package prefix won't actually work. Perhaps you could ignore it by classloader name?)

**Comment by pavolloffay** [comment]
> k. Perhaps you could ignore it by classloader name?)

Isn't it covered in the code? If the type is null it uses the class loader name.

**Comment by trask** [comment]
Closing, this is not something we plan to officially test/support, but we will accept PRs to make it run better alongside other agents.
