### ISSUE TITLE
Smoke tests with Jaeger and Zipkin

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1541]
Our Roadmap says that we want "End-to-end tests with OTLP, Jaeger and Zipkin". Currently only OTLP is implemented, Jaeger and Zipkin should be added.

@anuraaga this means either reverting #1136 or introducing Collector between tests and fake backend. Any suggestions or preferences?

**Comment by anuraaga** [comment]
There isn't any OTLP open source backend so we have a fake backend for it, but we can start Zipkin and Jaeger easily with testcontainers and use their standard query APIs. I guess we don't need to revert nor introduce collector for them right?

**Comment by iNikem** [comment]
Mmmm, I am not sure I want to bring any infrastructure outside of Otel into these tests. But this depends on what we actually mean by that goal on our Roadmap. If it is "we want to be able to export Zipkin to any Zipkin-compliant backend", then probably it is right thing to do...

**Comment by iNikem** [comment]
Wait, we already have Collector in our tests :D

**Comment by trask** [comment]
> Wait, we already have Collector in our tests :D

That was convenient 😄
