### ISSUE TITLE
Configuration debug

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1551]
To simplify runtime debugging we should provide an option to print out all supplied configuration.

**Comment by mateuszrzeszutek** [comment]
Perhaps we should consider adding a JMX bean that does this:

> actually what I think better is an api like jmx api so that when all configurations are merged and overriden, we can dump them out to see with multiple config approach what we get finally.

from #6284

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
