### ISSUE TITLE
End to end tests for propagators

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1561]
As part of our smoke tests we should test context and baggage propagators as well. 

Test controller can call another controller in the same JVM and return propagated context/baggage.

**Comment by anuraaga** [comment]
I test x-ray propagator here maybe something can be copy-paste

https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/smoke-tests/spring-boot/src/main/java/io/awsobservability/instrumentation/smoketests/springboot/AppController.java
