### ISSUE TITLE
Servlet Instrumentation does not cover scenarios like Spark-Jetty due to the missing instrumentation hook at Filter.doFilter()

### ISSUE THREAD

**Issue by singhalprerana** [open-telemetry/opentelemetry-java-instrumentation#1578]
**Is your feature request related to a problem? Please describe.**
Servlet instrumentation currently has hooks at `javax.servlet.FilterChain.doFIlter()` and `javax.servlet.http.HttpServlet.service()`. However, there might be code paths which do not go through either of these hooks -- they might involve `javax.servlet.Filter.doFIlter()` path instead -- for example, Embedded-Jetty-Spark applications.

**Describe the solution you'd like**
Add the servlet instrumentation hook at `javax.servlet.Filter.doFIlter()` too.

**Describe alternatives you've considered**
One alternative is to extend and add instrumentation hook at spark-web specific class (e.g. `spark.http.matching.MatcherFilter`) implementing `javax.servlet.Filter.doFIlter()`. However, there might be other such frameworks too and the entire instrumentation logic is exactly the same as servlet. So unless there is some potential issue which this might cause, a generic instrumentation hook might be a good idea.

**Comment by mateuszrzeszutek** [comment]
There's a `Filter` instrumentation that's turned off by default: https://github.com/open-telemetry/opentelemetry-java-instrumentation#disabled-instrumentations . Have you tried turning it on (`-Dotel.integration.servlet-filter.enabled=true`)?

**Comment by trask** [comment]
I'm not sure why we instrument `FilterChain` instead of `Filter`, sent draft PR #1606 to see what tests break if we change this

**Comment by trask** [comment]
Should be resolved by #1606
