### ISSUE TITLE
Document and enforce naming convention for instrumentation names

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1579]
(The ones passed in `Instrumenter`/`InstrumentationModule` constructor)

Sometimes those names include library versions (e.g. netty), sometimes not (cassandra), sometimes the same instrumentation name is repeated in several modules (sometimes unrelated, e.g. apache-httpclient and java-httpclient have the same name `httpclient`), sometimes it's the name of our module, sometimes it's the name of the library jar. `scala-concurrent` instrumentation is named `java_concurrent`, some Redis clients use `redis` (but not all of them), etc.

**Comment by iNikem** [comment]
We don't have anything formal yet. But you are right, we should have.

That name is used for instrumentation library identification and for enabling/disabling it. So probably it should be the same as Gradle module's name. This address the question of "with of without version": if module is unique for a given library, it does not have a version in its name. If module depends on library version, its name does have version.

**Comment by mateuszrzeszutek** [comment]
That's a good start. What do you think about the following naming rules:

* Instrumentation names should consist of hyphen-separated words, e.g. `instrumented-library`
* Instrumentation names should be the same as the gradle module
  * Except for instrumentations that are optional, disabled by default e.g. `servlet-filter`, `jdbc-datasource`
* library + version can be the secondary/additional instrumentation name.

What do we do about e.g. `redisson-3.0` module though? This is the only Redisson module, but it has version in its name. Should we name the instrumentation `redisson` or `redisson-3.0`?

Similar question about spring: `spring-webmvc-3.1` is the only module for that spring library, what kind of names should it have?

**Comment by trask** [comment]
👍

I would suggest change from:
* library + version can be the secondary/additional instrumentation name

to:
* library without version should be the second/additional instrumentation name if the gradle module name has a version suffix

**Comment by iNikem** [comment]
I think that in any case the main name of the instrumentation library SHOULD NOT contain version. We expect that only one of e.g. lettuce instrumentation modules will be applied to any given runtime instance. And users can expect that they can just use `otel.instrumentation.lettuce.enabled=false` regardless of the version used.

At the same time, if module does have a version in its name, then this SHOULD be the additional name for that instrumentation library.

Other than that, instrumentation name should be as close to module name as possible, ideally identical (minus versions as described above)

**Comment by trask** [comment]
Yes to what @iNikem said 👍

**Comment by iNikem** [comment]
@mateuszrzeszutek Can you provide a summary of this discussion as PR into contributing doc?

**Comment by mateuszrzeszutek** [comment]
I'll change this issue into an enhancement one.

AC:
* describe the naming convention in the contributing doc, preferably with examples;
* add short description in `InstrumentationModule`'s JavaDoc;
* change all instrumentations' names to correct ones.
