### ISSUE TITLE
Remove documentation captured on website from READMEs

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry-java-instrumentation#1580]
For GA there is an ask to capture getting started guides as well as instrumentation and configuration documentation on the website. Given https://github.com/open-telemetry/opentelemetry.io/pull/304, several READMEs need to be either updated or removed.

**Comment by flands** [comment]
I can submit a PR for this.

**Comment by iNikem** [comment]
@trask, @jkwatson  do you remember what was the conclusion of this discussion during maintainers meeting? I think we still prefer to have and own our own documentation.

**Comment by trask** [comment]
I don't mind if we move user docs to the website repo, it's not quite as convenient for us, but I think there are advantages for users.

Mainly though I would like to be consistent with what other repos are doing.

**Comment by trask** [comment]
Closing, I think this is done
