### ISSUE TITLE
Make instrumentations non final

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1582]
**Is your feature request related to a problem? Please describe.**

I would like to extend instrumentations/instrumentation modules to add additional data capture and other functionality e.g. filtering/blocking requests. The instrumentations can be extended right now by writing additional instrumentation with the same matcher but it leads to a lot of code repetition and issues like https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1576 can arise. Also it might be hard to maintain since the upstream instrumentation can change.

The `instrumenter.getOrder` allows us to apply custom instrumentation after the "core" instrumentation. This is used to get current span started in the "core" instrumentation. 

**Describe the solution you'd like**

Make instrumentation classes non `final` so they can be extended, then be able to load only extended instrumentations (avoid double loading). 

**Describe alternatives you've considered**

I can add instrumentation that copies helperclasses and other metadata from the core instrumentation. This can lead to issues like https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1576.

**Additional context**
None.

**Comment by trask** [comment]
Sounds good, I wonder if we can add a checkstyle rule for this to prevent drift/regression over time - linking to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1514#issuecomment-720898335

**Comment by mateuszrzeszutek** [comment]
Should we also make all `TypeInstrumentation`s public and non-final? Because that's where currently `typeMatcher()`s and `transformers()` live.

**Comment by pavolloffay** [comment]
+1
