### ISSUE TITLE
MongoClientTracer. UNSCRUBBED_FIELDS is incomplete

### ISSUE THREAD

**Issue by jyemin** [open-telemetry/opentelemetry-java-instrumentation#1587]
**Describe the bug**
MongoClientTracer. UNSCRUBBED_FIELDS is an incomplete list of commands and fields that need not be scrubbed out.  

**What did you expect to see?**
I didn't expect to see a hard-coded list of commands.   Instead, it would be both safe and more easily maintainable to simply not scrub the first key of each command, as the first key is by definition always the command name, and the value of the command name does not generally contain anything sensitive.

One exception is the "getMore" command: The value of the "getMore" field in that command is the cursor id (not all that sensitive, really).  The collection name is actually the value of the "collection" field.  

Another exception is the "dropUser" command: The value of the "dropUser" field in that command is the name of the user.  User names aren't the most sensitive data, but definitely more so than a lot of the data that _is_ being scrubbed.

**What did you see instead?**
The current list includes only "ordered", "insert", "count", "find",  and "create".  This leaves out important CRUD commands such as "update", "delete", "findAndModify", "aggregate", etc., and includes one non-command-name field  ("ordered") that is not significantly different than many others.

**What version are you using?**
I found this by code inspection of the master branch, not by using the tracer.

**Environment**
N/A

**Additional context**
I'm also not clear why it's necessary to preserve the collection name in the command, given that it's already pulled out into the `SemanticAttributes.DB_MONGODB_COLLECTION` attribute.

**Comment by trask** [comment]
@jyemin thanks for reporting this, really appreciate your expertise here!

**Comment by jyemin** [comment]
No worries.  I have worked with DataDog and AppDynamics in the past to make tracing work well with our drivers, and want to make sure that continues with this project.

I'm going to submit a PR to fix this.  There's a few other issues as well that I'd like to address.  At this stage of development, are you looking for small PRs, each associated with a GH issue, or is a single PR with several fixes ok?

**Comment by iNikem** [comment]
If it is not overwhelmingly large, then single PR is Ok as well.

**Comment by jyemin** [comment]
I just updated the description to include the example of the [dropUser](https://docs.mongodb.com/manual/reference/command/dropUser/index.html) command.  Are we ok not scrubbing user names?

**Comment by trask** [comment]
Our jdbc instrumentation doesn't scrub usernames:

`ALTER USER xyz IDENTIFIED BY 'password'` ==> `ALTER USER xyz IDENTIFIED BY ?`

so I think this is good not to scrub user names here either.

**Comment by trask** [comment]
Closed by #1663
