### ISSUE TITLE
Support non-uber jar releases of mongo-java-driver

### ISSUE THREAD

**Issue by jyemin** [open-telemetry/opentelemetry-java-instrumentation#1588]
**Is your feature request related to a problem? Please describe.**
Starting with the 4.0 release of the MongoDB Java driver, the `mongo-java-driver` uber-jar module is no longer included in the distribution.  I think this will cause problems given that the muzzle configuration for the driver only references `mongo-java-driver`.

Even before 4.0, non-uber jars have also been published, and if I understand correctly anyone using those jars would not get the benefits provided by muzzle (which I don't fully understand).

**Describe the solution you'd like**

Support instrumentation with the non-uber jar modules of the MongoDB Java driver

From 3.7 on, `MongoClientSettings` is included in the `mongodb-driver-core` module.

From 3.9 on, `MongoClientOptions` is included in the `mongodb-driver-legacy` module. 

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by trask** [comment]
Thanks!

Luckily our sibling project just added Mongo driver v4 support https://github.com/DataDog/dd-trace-java/pull/2043, looks like we need to merge that over to this repo.

For some light reading on muzzle that won't answer all of your questions 😄, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/docs/contributing/muzzle.md

**Comment by malafeev** [comment]
@trask I would like to merge Mongo driver v4 support

**Comment by malafeev** [comment]
PR: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2046

**Comment by trask** [comment]
I believe this is closed by #2046
