### ISSUE TITLE
Fix BootstrapPackagesProvider

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1594]
Need to fix `BootstrapPackagesProvider` feature that was (intentionally) broken in PR #1593.

Need to figure out how to reference `BootstrapPackagesProvider` from inside of `ClassLoaderInstrumentation` without breaking restrictive wildfly/jboss modules class loaders.

**Comment by pavolloffay** [comment]
Maybe there are better solutions to this: the agent installer could load the SPI and modify the content of `Constants` class?

**Comment by trask** [comment]
> Maybe there are better solutions to this: the agent installer could load the SPI and modify the content of `Constants` class?

The Constants class is injected into the class loader, so I think is separate class from the Constants class in the AgentClassLoader and won't share static fields.

**Comment by iNikem** [comment]
@pavolloffay Can you tell me how did you work around this issue in hypertrace?

**Comment by pavolloffay** [comment]
as I workaround I have shaded HT classes into `io.opentelemetry.javaagent.shaded` which matches the hardcoded prefix. We still need a proper fix though.

**Comment by pavolloffay** [comment]
thanks @iNikem for the fix ❤️
