### ISSUE TITLE
Improve wildfly smoke test

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1595]
Need to improve the wildfly smoke test so that it would have caught #1591.

**Comment by iNikem** [comment]
What version of WildFly did you use in your manual verification?

**Comment by trask** [comment]
21.0.0.Final

**Comment by iNikem** [comment]
@trask Can you please test this again? I cannot reproduce this issue with WildFly. But I can with GlassFish :)

**Comment by iNikem** [comment]
I took 0.10.0 release which supposed to have this problem and tested wildfly-21.0.0.Final with it and a simple web app. Works without any problems.

**Comment by iNikem** [comment]
A! Now I reproduced it! I needed JSP for that :) pure servlets work just fine

**Comment by trask** [comment]
good find, I wonder if I was using some default app that had JSPs, no idea 😂

**Comment by trask** [comment]
Closed by #1825

**Comment by trask** [comment]
oh, just realized, the test matrix isn't running yet, probably why you didn't close this 😄

**Comment by iNikem** [comment]
Will submit proper test and fix tomorrow
