### ISSUE TITLE
How can I write logs to a file

### ISSUE THREAD

**Issue by xieao** [open-telemetry/opentelemetry-java-instrumentation#1600]
I have a custom exporter, and i used the log like following code：

```
public CompletableResultCode export(Collection<SpanData> collection) {
    Gson gson = new Gson();
    ……
    log.info(gson.toJson(jsonObject)); 
    return CompletableResultCode.ofSuccess();
}
```

but the log show on STDOUT. How can I write the log to a file，how to configure this agent？

**Comment by trask** [comment]
hi @xieao! are you trying to export spans to a file, or send agent debug logging to a file?

**Comment by govine** [comment]
I also think that writing files is the right choice in many scenarios.
So we need another exporter for file writing?

**Comment by yingziisme** [comment]
> hi @xieao! are you trying to export spans to a file, or send agent debug logging to a file?

so how to export spans to a file？

**Comment by trask** [comment]
are you looking for something like this? https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/logging-otlp

we haven't hooked that up to the javaagent yet, primarily because there's no specification for it: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#exporter-selection

**Comment by yingziisme** [comment]
> are you looking for something like this? https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/logging-otlp
> 
> we haven't hooked that up to the javaagent yet, primarily because there's no specification for it: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#exporter-selection

no. how can i config the file path. use java.util.logging.Logger will remapping io.opentelemetry.javaagent.bootstrap.PatchLogger 

i try to use this config below, but it doesn't work

private final Logger javaUtilLogger = Logger.getLogger("TRACING_JAVA_UTIL_LOGGER");
Handler tracingFileHandler = new FileHandler(this.traceLogPath + ".%u.log", this.traceLogSize, this.traceLogCount);
tracingFileHandler.setFormatter(new TracingFormatter());
this.javaUtilLogger.addHandler(tracingFileHandler);
this.javaUtilLogger.setLevel(Level.ALL);

**Comment by trask** [comment]
ah, that's an interesting use case, can you open an issue so we don't lose track of it?

**Comment by mateuszrzeszutek** [comment]
There's already https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3413 -- @yingziisme would implementing that issue fix your problem?

**Comment by trask** [comment]
Closing in favor of #3413
