### ISSUE TITLE
Add support for Reactor Netty HttpClient 1.0

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1602]
https://github.com/reactor/reactor-netty/releases/tag/v1.0.0

Freshly added reactor-netty support (#1601) does not work with 1.0.0

**Comment by malafeev** [comment]
@iNikem could you assign it to me?

**Comment by mateuszrzeszutek** [comment]
Implemented in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2156
