### ISSUE TITLE
Where to get the agent jar?

### ISSUE THREAD

**Issue by holyjak** [open-telemetry/opentelemetry-java-instrumentation#1615]
The README reads:

> Download the [latest version](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent-all.jar).

but that gives 404 and I could not find any JAR on the Releases page. Please be so kind and update the docs. Thank you!

Perhaps point to https://bintray.com/open-telemetry/maven/opentelemetry-java-instrumentation if that is the right place?

**Comment by iNikem** [comment]
Sorry, @holyjak. That link IS the way to get the latest release for the time being, until we are stable enough to start publishing to Maven Central. You just hit the unfortunate window when we had some troubles with our releases :) That link should now work again.
