### ISSUE TITLE
spotlessKotlin shouldn't prevent wildcard import?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1616]
Not a kotlin expert, but FWIU, wildcard imports are relatively standard in kotlin for being the basis of kotlin DSLs, such as coroutines

**Comment by iNikem** [comment]
[Koltin coding conventions](https://kotlinlang.org/docs/reference/coding-conventions.html) do not say anything about this

**Comment by trask** [comment]
I have no objection to allowing wildcard imports in kotlin code

**Comment by trask** [comment]
@anuraaga is it ok to close this since we only have one kotlin file and the [editorconfig issue is now fixed](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2440#issuecomment-787743323) (and we can revisit in the future when we have more kotlin)?
