### ISSUE TITLE
Span propagation seems not to be happening in Kotlin

### ISSUE THREAD

**Issue by holyjak** [open-telemetry/opentelemetry-java-instrumentation#1620]
I have a simple Kotlin server, that accepts a requests, fetches data from an API, an returns those. I run it with the instrumentation agent. I expect that the call will create a span that will wrap the whole interaction, and the span created for the outgoing call will be its descendent. I also expect to be able to create a span manually and for it to appear between the two. Instead, two completely unrelated spans are created. More detailed description with logs available in the reproduction github repo (see below).

**Steps to reproduce**

Clone https://github.com/holyjak/tmp-opentelemetry-instrumentation-kotlin-issue and run it as described in the README.

**What did you expect to see?**

Three spans:

1. netty.request
2. my own "ktor request" as its child
3. the outgoing HTTP GET as a descedent of 1 and 2

**What did you see instead?**

As described above, two unrelated spans.

**What version are you using?**

`v0.10.1`

**Environment**
Compiler: openjdk 11.0.1 2018-10-16
OS: OSX

---
Should I somehow supply my own propagation of `Span.current()`, that is compatible with Kotlin coroutines? (Perhaps leveraging [Kotlin support for ThreadLocal](https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/coroutine-context-and-dispatchers.md#thread-local-data) and the approach [Ktor uses for MDC](https://github.com/ktorio/ktor/blob/master/ktor-server/ktor-server-core/jvm/src/io/ktor/features/CallLogging.kt).) But how would I do that when the agent code is in the agent jar, not visible to my code? I guess I would need to create my own agent jar with the changes?

**Comment by anuraaga** [comment]
@holyjak Thanks for this report - we're currently reviewing the context instrumentation for context in #1617 and #1618. If you can take a look at it, that would be great!

**Comment by anuraaga** [comment]
@holyjak Hey I remembered this issue after so long - can you confirm the fixes we've made since then solved your problem?

**Comment by anuraaga** [comment]
@holyjak Going to go ahead and close this issue, but please reply or file a new one if you're seeing issues still.
