### ISSUE TITLE
Move `tracer()` method from Tracer class to Instrumentation

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1622]
One of the asks from #566 is the ability to add new attributes to spans. These attributes may depend on the same actual objects that Tracers operate on, such as http request or db connection. Thus this cannot be done in `SpanProcessor` and vendor distros should be able to override Tracer implementation.

But atm instrumentations access tracer instance via static method on tracer class:
```
public class JdbcTracer extends DatabaseClientTracer<DBInfo, SqlStatementInfo> {
  private static final JdbcTracer TRACER = new JdbcTracer();

  public static JdbcTracer tracer() {
    return TRACER;
  }
```
This makes overriding impossible. I propose to make `tracer()` an instance method on either instrumentation or advice.

**Comment by trask** [comment]
@iNikem is this same as #778?

**Comment by iNikem** [comment]
I will close this issue as #778 and #1623 probably supersede this one.
