### ISSUE TITLE
MongoClientTracer can report incorrect collection name

### ISSUE THREAD

**Issue by jyemin** [open-telemetry/opentelemetry-java-instrumentation#1625]
**Describe the bug**
MongoClientTracer.collectionName assumes that 

* if the value of the command name field is a string, that string is always a collection name.  But there are administrative commands like [dropUser](https://docs.mongodb.com/manual/reference/command/dropUser/index.html) where this is not the case, and it may confuse users if those strings are reported as collection names.
* that the collection name is always the value of the command name field.  This is true for most commands, but in the case of [getMore](https://docs.mongodb.com/manual/reference/command/getMore/index.html) the collection name is contained in a different field.

**Steps to reproduce**
Found via code inspection

**What did you expect to see?**
I think it would be safer to uses an allowList of commands where we know for sure where the collection name is, rather than risk reporting an incorrect collection name.

**What did you see instead?**
The code assumes that if the value of the command name field is a string, that string is always the name of a collection.

**What version are you using?**
N/A

**Environment**
N/A

**Additional context**
N/A

**Comment by trask** [comment]
Closed by #1662
