### ISSUE TITLE
Run tests and smoke tests against IBM JVM

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1633]
We used to run tests against IBM JVM before #129, would be good to bring this back so we can say we support Java 8+ without adding the qualification that we only support (test against) OpenJDK-based JVMs.

**Comment by anuraaga** [comment]
It seems like both of our techniques for downloading Java, GHA setup-java and Gradle have vendor-specific Java downloading targeted to their next release

https://github.com/actions/setup-java/issues/98
https://github.com/gradle/gradle/issues/14802

While manually downloading is always an option, the simplest is probably to start with only the smoke tests and wait for one of these.

**Comment by iNikem** [comment]
It is very easy now to add to our smoke tests, e.g. for jetty. And we will add that for WebSphere Liberty when that support lands here "soon". Do we want both jdk8 and 11 from IBM or one is enough? Any opinions?

**Comment by trask** [comment]
Both 👍

**Comment by mateuszrzeszutek** [comment]
Implemented in smoke tests a while ago in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2386; there's a separate issue https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3244 about instrumentation tests
