### ISSUE TITLE
Should we create javaagent subdir under each instrumentation?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1638]
Based on a recent PR (#1628), I can see that changing our convention and creating a `javaagent` subdirectory for all instrumentations would have some advantages:

* it wouldn't be confusing for new contributors whether to create it or not, since they will see the `javaagent` directory under all instrumentations
* it makes the spot for people to add `library` instrumentation obvious, and more inviting

The downside of course is an unnecessary directory level for instrumentation that only has `javaagent` module.

wdyt?

**Comment by trask** [comment]
it potentially makes a few other things more consistent, e.g. referencing modules wouldn't depend on whether there's a library instrumentation or not, e.g. when referencing from other modules, or running command-line tasks:

`./gradlew :instrumentation:struts-2.3:javaagent:muzzle`

**Comment by anuraaga** [comment]
Think we should definitely do it :)
