### ISSUE TITLE
Verify importance of changing build directory on CI

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1640]
Currently, we change the build directory on CI only. This means that using `build` in gradle scripts works locally but not on CI. While it's generally considered best practice to use `buildDir`, it's so uncommon to change the build directory that I often forget. But worse is that this makes debugging failures that only happen on CI difficult. I can't think of a reason for us to be separating the build directory like this. But assuming there is a reason, we should apply it locally as well, not just on CI.

**Comment by iNikem** [comment]
Where do we change build directory?

**Comment by anuraaga** [comment]
@iNikem https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/build.gradle#L36

**Comment by iNikem** [comment]
Why the hell do we do that?? I say we should remove this customisation
