### ISSUE TITLE
Publish testing-common

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1644]
In order to allow vendor distribution to unit-test their custom instrumentation we should publish our test infrastructure, at least `testing-common` module.

**Comment by anuraaga** [comment]
Will we force all vendors to use Spock? Ideally not :-)

**Comment by iNikem** [comment]
Don't see anything bad in this :) What do you suggest?

**Comment by anuraaga** [comment]
Ideally we can move as much code into Java classes that don't depend on Spock but just operate on the agent, or our instrumentation APIs, etc, probably by presenting some lifecycle methods (`beforeAgentTest`, etc). Then, it probably (?) wouldn't be hard to call these from any testing framework, spock or junit. Hopefully #1146 will help move even more logic out of our spock lifecycle classes and this may become even simpler. I think it's good to give downstream a choice in test frameworks.
