### ISSUE TITLE
Rename grizzly-client instrumentation to async-http-client

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1658]
It appears to just be instrumentation (and tests) of [AsyncHttpClient](https://github.com/AsyncHttpClient/async-http-client)

Also, I don't think we need to disable it by default (grizzly-server is a different story, and should be disabled by default).

**Comment by iNikem** [comment]
I think there is some confusion here.

https://github.com/AsyncHttpClient/async-http-client uses artifactId `async-http-client` and package name `org.asynchttpclient`
https://github.com/eclipse-ee4j/grizzly-ahc uses artifactId `grizzly-http-client` and package name `com.ning.http.client`.

The instrumentation under review monitors the second one, not the first one.

**Comment by trask** [comment]
`com.ning.http.client` was the package name for AsyncHttpClient prior to version `2.0`
