### ISSUE TITLE
Is there any way in 0.10.1 to access b3 multi propagator?

### ISSUE THREAD

**Issue by jamesylgan** [open-telemetry/opentelemetry-java-instrumentation#1664]
I see #1647 is set to add support in the next release but I am wondering if there is any way in `0.10.1` to access b3 multi header propagation

Thanks!

**Comment by iNikem** [comment]
Unfortunately no :( We aim to make a new release early next week

**Comment by jamesylgan** [comment]
Thanks for the timeline @iNikem!
