### ISSUE TITLE
Extending InstrumentationModules

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1677]
**Is your feature request related to a problem? Please describe.**

I would like to extend instrumentation modules in my custom build of the Java agent. The main motivation is to avoid bugs like https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1274 which the instrumentation modules solve.

Also the custom instrumentations depend on the core so if the core module is not applied due to mismatch the custom instrumentation should not apply either as it for instance uses current span started in the core module.

**Describe the solution you'd like**

A way to add `TypeInstrumentation` to the instrumentation modules in this project.

**Describe alternatives you've considered**

Extending instrumentation modules from this project has a couple of problems currently:
1. the helper classes via `super.helperClasses()` does not work properly if the super class uses `packageName` - it will be the package name of the extended class.
2. the parent class will be discovered and applied by `AgentInstaller` - this is more of a discussion on how it should be filtered out from the final distribution but also unit tests (in the custom instrumentation maven module).

**Additional context**

Related to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1623

**Comment by mateuszrzeszutek** [comment]
Number 1 will be solved by https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1374; after the muzzle improvement is implemented there will be no need for the `packageName` field at all.

I don't have any idea about what to do with number 2 yet.

**Comment by iNikem** [comment]
@pavolloffay @mateuszrzeszutek Can the second problem be solved by custom distro disabling upstream module and then providing new name for its own override? And then extending `typeInstrumentations()`.

To simplify that we may automatically add one more `additionalInstrumentationName` to all our modules, equal to the class name of the module. Then there are much less chance to interfere with client configuration.

**Comment by mateuszrzeszutek** [comment]
> @pavolloffay @mateuszrzeszutek Can the second problem be solved by custom distro disabling upstream module and then providing new name for its own override? And then extending typeInstrumentations().

Yes, it could be done this way. Instead of extending you could use composition, e.g.:
```java
class MyServletModule extends InstrumentationModule {
  private final InstrumentationModule delegate = new OtelServletModule();

  MyServletModule() { super("my-name"); }

  String[] getMuzzleHelperClassNames() {
    return delegate.getMuzzleHelperClassNames();
  }

  List<TypeInstrumentation> typeInstrumentations() {
    // ...
  }
}
```
This way you can name your instrumentation however you want (because actual agent instrumentation modules only have default constructors).

> To simplify that we may automatically add one more additionalInstrumentationName to all our modules, equal to the class name of the module.

That wouldn't work, unfortunately - we can't inject instrumentation classes. I'd recommend the composition approach.

**Comment by pavolloffay** [comment]
re the `return delegate.getMuzzleHelperClassNames();` this method will have to return also helper classes for the new module as the new module might use more helpers applies also for the muzzle matcher.

**Comment by iNikem** [comment]
@pavolloffay Do we need to do anything regarding your initial request? Or the composition idea of @mateuszrzeszutek solves your problem?

**Comment by trask** [comment]
ping @pavolloffay

**Comment by trask** [comment]
@pavolloffay closing, but feel free to re-open (or open new issue) if you think there's more to be done here
