### ISSUE TITLE
Regression in muzzle when switched to instrumentation modules

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#1678]
**Describe the bug**

When switching from Instrumenter to Instrumentation module in custom servlet instrumentation I had to change the muzzle fail gradle configuration - https://github.com/hypertrace/javaagent/pull/123#discussion_r526011640.

**Steps to reproduce**
Try https://github.com/hypertrace/javaagent/pull/123 with the original settings.

**What did you expect to see?**

No changes to the muzzle when switching to instrumentation modules.

**What did you see instead?**

```
> Task :instrumentation:servlet:servlet-2.3:muzzle-AssertFail-javax.servlet-javax.servlet-api-3.0.1 FAILED
...
MUZZLE PASSED Servlet2BodyInstrumentationModule BUT FAILURE WAS EXPECTED
:instrumentation:servlet:servlet-2.3:muzzle-AssertFail-javax.servlet-javax.servlet-api-3.0.1 (Thread[Execution worker for ':' Thread 2,5,main]) completed. Took 0.033 secs.
:instrumentation:servlet:servlet-2.3:muzzle-AssertFail-javax.servlet-javax.servlet-api-3.1.0 (Thread[Execution worker for ':' Thread 2,5,main]) started.
```

**What version are you using?**
0.10.0

**Comment by pavolloffay** [comment]
cc) @mateuszrzeszutek

**Comment by mateuszrzeszutek** [comment]
OK, I think I know why muzzle is failing for tour module: you need to split the classloader matcher between the module and type instrumentation.

This is your original matcher in `TypeInstrumentation` (`InstrumenationModule` does not have one):
```java
    // this is required to make sure servlet 2 instrumentation won't apply to servlet 3
    @Override
    public ElementMatcher<ClassLoader> classLoaderMatcher() {
      // Request/response wrappers are available since servlet 2.3!
      return hasClassesNamed(
              "javax.servlet.http.HttpServlet", "javax.servlet.http.HttpServletRequestWrapper")
          .and(not(hasClassesNamed("javax.servlet.AsyncEvent", "javax.servlet.AsyncListener")));
    }
```

According to `TypeInstrumentation#classLoaderMatcher()` JavaDoc, it's supposed to be only an optimization, it should not be used to select the library version. It should probably look like this:

```java
class ... implements TypeInstrumentation {
  // ...

  @Override
  public ElementMatcher<ClassLoader> classLoaderMatcher() {
    return hasClassesNamed("javax.servlet.http.HttpServlet");
  }
```

You should move the matchers that restrict the library version to `InstrumentationModule`:

```java
class ... extends InstrumentationModule {
  // ...

  // this is required to make sure servlet 2 instrumentation won't apply to servlet 3
  @Override
  public ElementMatcher.Junction<ClassLoader> classLoaderMatcher() {
    // Request/response wrappers are available since servlet 2.3!
    return hasClassesNamed( "javax.servlet.http.HttpServletRequestWrapper")
        .and(not(hasClassesNamed("javax.servlet.AsyncEvent", "javax.servlet.AsyncListener")));
  }
```

I agree that having two classloader matchers is a bit confusing, especially when they serve different purposes, but I think that it could be possible to generate the `TypeInstrumentation` one from the `typeMatcher` in the future - right now the JavaDoc for both methods describes what they're for.

**Comment by trask** [comment]
maybe we can rename `TypeInstrumentation.classLoaderMatcher()` to `classLoaderOptimization()` or similar?

**Comment by mateuszrzeszutek** [comment]
@pavolloffay have you applied suggestion from my previous post? Does it work now?

**Comment by pavolloffay** [comment]
Yes it fixed the issue

**Comment by pavolloffay** [comment]
Thanks @mateuszrzeszutek for looking into it.

**Comment by mateuszrzeszutek** [comment]
> Thanks @mateuszrzeszutek for looking into it.

No problem at all!

I'll rename the `classLoaderMatcher()` as @trask suggested and close this issue.
