### ISSUE TITLE
TracerInstaller overrides custom propagators

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1681]
If some `TracerCustomizer` tries to provide its own propagators via calling `OpenTelemetry.setGlobalPropagators`, then `io.opentelemetry.javaagent.tooling.PropagatorsInitializer#initializePropagators` will override it anyway. At least with default `HttpTraceContext`. This makes it impossible to provide external/custom propagator.

Related to open-telemetry/opentelemetry-java#2022

Setting P1 because it limits the power of vendor distribution, which is P1.

**Comment by jamesylgan** [comment]
Can this be closed with `0.13.0` updates to custom propagation?

**Comment by jkwatson** [comment]
> Can this be closed with `0.13.0` updates to custom propagation?

I believe that this bug has not yet been addressed, so this issue should not be closed.
