### ISSUE TITLE
Dependencies resolution during configuration

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1692]
Recent build scans report a warning "Dependencies were resolved during project configuration". This is a slight problem for CI, because e.g. `setup-muzzle-matrix` step, which should just print project names, takes several minutes.

By adding the following code into top-level `build.gradle` and running `./gradlew instrumentation:listInstrumentations -s` one can find that the culprit is `gradle/instrumentation.gradle` file

```
def afterEvaluation = false
gradle.projectsEvaluated {
  afterEvaluation = true
}

allprojects { project ->
  configurations.all { configuration ->
    configuration.incoming.beforeResolve {
      if (!afterEvaluation) {
        throw new Exception("Configuration $configuration.name of project $project.name is being resolved at configuration time.")
      }
    }
  }
}
```

```
  new ByteBuddyPluginConfigurator(project, sourceSets.main, pluginName, [
    project(':javaagent-tooling').configurations.instrumentationMuzzle.files,
    configurations.runtimeClasspath.files,
    sourceSets.main.output.files
  ]).configure()
```
This code above resolves all dependencies already during task configuration phase.

**Comment by trask** [comment]
Closed by #1715
