### ISSUE TITLE
Rename and document otel.trace.enabled property

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1697]
The property name should match our other property names (#1414), maybe `otel.instrumentation.enabled`?

**Comment by mateuszrzeszutek** [comment]
There already is a `otel.instrumentations.enabled` property (see `InstrumentationModule#defaultEnabled`). Maybe we could rename that one to `otel.instrumentation.defaultEnabled` and `otel.trace.enabled` to `otel.javaagent.enabled`?
