### ISSUE TITLE
Update groovy import order to match default Intellij

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1708]
Since we can't enforce the import order for groovy files, it makes sense to use the default Intellij ordering. Hopefully this should reduce import order drift.

Idea from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1690#issuecomment-730792005

**Comment by mcmho** [comment]
@trask  can I work on this one as a starter?  :-)

**Comment by mcmho** [comment]
On https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/intellij-setup.md, 
do we recommend some particular versions of IntelliJ (2020.3,  2021.2.1)?

**Comment by trask** [comment]
> @trask can I work on this one as a starter? :-)

👍 assigned to you

> @trask, just to make sure, this import update is for all .groovy files, correct?

👍

**Comment by mcmho** [comment]
@trask ,  also what I found is the following is the default IntelliJ 2019.3 and 2021.2.1 setting for .groovy files.   
I just want to make sure this is what we are following correct?   
![image](https://user-images.githubusercontent.com/5099946/131568336-e58b8174-5a80-494d-8e33-e7558853edc5.png)

if so, then this needs to be updated as well - https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/intellij-setup.md

**Comment by trask** [comment]
> I just want to make sure this is what we are following correct?

👍

> if so, then this needs to be updated as well - https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/intellij-setup.md

👍

**Comment by iNikem** [comment]
Closed by #4047
