### ISSUE TITLE
Span resources should contain service, application etc.

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-java-instrumentation#172]
The OpenTelemetry spec calls for a service name, namespace etc. to be sent as part of the resource of a span. Typically, a service would map to the map of a microservice in an application (such as "shopping_cart") while the namespace would map to the name of the overarching application. These names are typically used by monitoring tools to render service graphs etc.

The auto instrumenter currently doesn't populate these values in a meaningful way. We need a way for the user to override these values with e.g. system properties or environment variables in order to provide names that are meaningful in a specific context.

More specifically, we probably need a multi-tiered way of determining these values. Some application frameworks, such as SpringBoot have the notion of an application and a service name. When such a mechanism exists, it should be used. If it doesn't we should fall back to a system property or environment variable.

**Comment by trask** [comment]
Closing, service name can be set via environment variables now for OTLP, Jaeger and Zipkin exporters.
