### ISSUE TITLE
Logging exporter: error in doc

### ISSUE THREAD

**Issue by aelmanaa** [open-telemetry/opentelemetry-java-instrumentation#1727]
Hello

in the source code, the system variable name is "otel.logging.prefix" . While the documentation states "otel.exporter.logging.prefix"

**Comment by trask** [comment]
thanks for reporting this! I think the doc is "correct" and the code should be updated to use `otel.exporter.logging.prefix` 😄

**Comment by trask** [comment]
@aelmanaa I'm curious, are you using this property to remove the default prefix? I'm wondering if no prefix ("") is a better default compared to the current default `Logging Exporter:`.

**Comment by aelmanaa** [comment]
Helle @trask 

I was just playing around to understand opentelemetry. To answer your question: IMHO, indeed it makes sense to put "" and if one would like to parse his log then he can fill in "otel.exporter.logging.prefix" .
Got one question for you please:

are there guidelines on how to write a custom tracer in case a dependency is not supported? 

https://github.com/open-telemetry/opentelemetry-java-instrumentation#supported-java-libraries-and-frameworks

**Comment by trask** [comment]
@aelmanaa great, thx, I agree, sent #1758 to make that change.

> are there guidelines on how to write a custom tracer in case a dependency is not supported?

I'd start with looking at some of the existing instrumentations.

If you can provide some more details, e.g. what library/framework are you wanting to instrument, what kind of telemetry do you want to capture from it, we can try to provide more specific hints where to start.

**Comment by aelmanaa** [comment]
@trask thanks.

Actually we are using [Application insights java library](https://github.com/microsoft/ApplicationInsights-Java)  which uses opentelemetry behind the scenes If I understood correctly.

It works fine with our microservices developed inhouse but we are not able to instrument the API GW , which is [wso2 based](https://wso2.com/) . 
After investigation, we found out that wso2 products use [Apache httpcore-nio](https://docs.wso2.com/display/ESB460/FAQ#FAQ-WhatistheNHTTPtransport?):
`NHTTP transport uses the Apache Http Core NIO library (http://hc.apache.org/httpcomponents-core-ga/httpcore-nio) underneath. This library provides low-level I/O handling and HTTP-level detail handling.`

I've opened an [issue ](https://github.com/microsoft/ApplicationInsights-Java/issues/1344 )in AppInsights github but I fear that they wouldn't support it unless it is supported by opentelemetry first.

**Comment by trask** [comment]
@aelmanaa check out the apache-httpasyncclient-4.0 instrumentation, that is probably the closest instrumentation to what you are looking for, so hopefully will help you get started.
