### ISSUE TITLE
Trace propagation is not working when a client span is created before HttpClient

### ISSUE THREAD

**Issue by jamal** [open-telemetry/opentelemetry-java-instrumentation#1728]
**Describe the bug**
Trace propagation is not working when a client span is created before the `HttpClientTracer` is invoked. This happens with instrumentations that create their own span but using an HTTP Client under the hood, such as the AWS SDK.

From reviewing the logic, this appears to be happening because `HttpClientTracer` is creating an invalid span when it detects a previously created client span in the current context. This span is then passed to the Trace Propagator which bails out when it detects that the span context is invalid. 

**Steps to reproduce**
This is not trivial to reproduce, I am working on a test case to provide in a bit.

The way I found this was by debugging the AWS SDK instrumentation to figure out why X-Ray was not capturing any data. After digging into this for a while, I found that `AwsXRayPropagator` was bailing before injecting the `X-Amzn-Trace-Id` header. But, other HTTP requests where showing this normally. I then realized that this was due to the behavior I explained above.

**What did you expect to see?**
I expected to see trace headers for the configured propagators to be included in these HTTP requests.

**What did you see instead?**
Headers are being passed in the AWS SDK requests for the standard things that the SDK populates, but the trace headers are all missing.

**What version are you using?**
`v0.10.1`

**Environment**
Compiler: OpenJDK 11
Runtime (if different from JDK above): `Oracle JRE 8`

**Comment by jamal** [comment]
After digging into this issue, and my proposal solution a bit more, I found that some test cases were specifically checking against this behavior for the aws-sdk instrumentation.

The source of that is this commit: https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/ca708db5dae1e70a5909f043032bf4878348670f

This brings up a point I had not considered: adding headers to the HTTP request could break signing that some instrumentations rely on (such as the AWS SDK).

That being said, in this scenario, I think we would want to at the very least pass the `X-Amzn-Trace-Id` header with AWS SDK requests as this is the only way to enable the integration with X-Ray.

**Comment by anuraaga** [comment]
Hi @jamal - thanks a lot for the investigation. I had thought we were injecting headers into the request in the AWS SDK instrumentation but I can't find it even in the git history. Indeed, especially because of the signing requirement, it's the AWS SDK instrumentation that needs to propagate, not HTTP client instrumentation. We can do so in the `modifyHttpRequest` callback of `TracingExecutionInterceptor`. Is this a change you can try making? Otherwise happy to take a stab.

**Comment by jamal** [comment]
@anuraaga thank you for the feedback! I'd be happy to update this PR based on your suggestions. But, if it would make more sense for you to take over then let me know and I can hold off and wait :). 

I've been trying to integrate our tracing solution with X-Ray, to get more visibility into workflows that involve SNS/SQS. So, have been fighting a few issues trying to sort that out, heh. 

Thanks so much!

**Comment by anuraaga** [comment]
@jamal Cool let me try to sort it out then. Sorry for the troubles.

Also, I don't know if you noticed but I work at AWS on X-Ray :-) I'd be happy to hear more about what you're working on, since I want to make sure it's a good experience. If that sounds interesting drop me an email at the address on my GitHub profile.

**Comment by jamal** [comment]
Awesome, thank you! I'll follow up by email :)

**Comment by jamal** [comment]
Updated the title to better reflect what is actually happening here. I'm not aware of other instrumentations that are impacted by this besides AWS SDK.

@anuraaga Also, thank you for fixing this in the 2.2 SDK instrumentation. Do you plan on doing the same for the 1.X instrumentation? In my case, we're still using this version of the SDK as this is an older services. We could look into upgrading, but that will be much less trivial for now.

Thanks!

**Comment by anuraaga** [comment]
@jamal I was hoping to punt on the older one until someone asked, but someone asked so soon :P https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1771

**Comment by jamal** [comment]
@anuraaga Haha,sorry! I appreciate all of the help. I'll have to prioritize upgrading to the 2.x SDK one day 😅
