### ISSUE TITLE
@WithSpan annotation doesn't add span to current Trace

### ISSUE THREAD

**Issue by haiau79** [open-telemetry/opentelemetry-java-instrumentation#1748]
Hi, I am using the auto instrumentation jar and it works good when I trace my app through several microservices. It generates 4 spans. I added an internal method to one of my services that just sleeps for a few seconds and annotated the method with @WithSpan and when I ran the trace again, I was expecting to see a 5th span get added (the internal method that was annotated with @WithSpan). However, it generated the same 4 spans and 1 span by itself that was just the internal sleep method. How can I get the span from the internal method to be part of the first trace that had 4 spans? This was all done with the opentelemetry-javaagent-all.jar 0.8.0 version with the -javaagent flag when running the microservices. The only manual instrumentation was the @WithSpan annotation.

I had 3 microservices running, one sent a JMS message, one received the JMS message and made a gRPC call that did a look up in mongodb. Mostly simple, hello world type of services to see how opentelemetry auto instrumentation works.

When I ran the microservices and looked at the Jaeger UI, I initially saw 4 spans in one Trace that perfectly described what I expected to see. Then I added a new internal method into my first microservice that just slept for 3 seconds and annotated the method with @WithSpan like this

@WithSpan
public void sleepForThreeSeconds()

After annotating the method with @WithSpan, I reran the trace again and opened up the Jaeger UI. What I saw in the Jaeger UI was the same 4 spans, and 1 span that described the internal method with the @WithSpan annotation by itself. So two traces, one trace with 4 spans, and one trace with 1 span (the internal method annotated with @WithSpan).

This was done using opentelemetry-javaagent-all.jar 0.8.0.

Windows 10 Enterprise, running Jaeger all in one docker image. All microservices were started using basic command java -javaagent:path/to/opentelemetry-javaagent-all.jar \
     -jar myapp.jar

**Comment by trask** [comment]
hi @haiau79! can you provide a repro that we can use to test/troubleshoot this issue? a simplified version of your first service, where the `@WithSpan` span is not being parented to the request span, would be great, I don't think the issue is related to the other services being involved.

**Comment by haiau79** [comment]
Figured out how to add @WithSpan, I had to add @WithSpan annotation on every method that calls the method I was interested in tracing, and then it added the span to the same trace. Sorry for the late response.
