### ISSUE TITLE
Lazy load servers in tests

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1751]
This may just be a bad bandaid, but just an idea. We often use test class callbacks for creating testing servers, e.g. `@Shared`, `@TestContainer`. Starting up servers in our huge build can fail for various reasons - unfortunately `gradle-retry-plugin` will not support retrying tests for this case. An extreme cludge, but we could workaround this by instead of using class callbacks, use lazy singletons that are actually executed in the test method itself - that should allow `gradle-retry-plugin` to work. If `gradle-retry-plugin` could work for all our tests, we could avoid `invision/retry` which restarts the entire Gradle build, with much more overhead than the individual retry of `gradle-retry-plugin`.

**Comment by iNikem** [comment]
As additional benefit this will make the time to load server more visible, I think

**Comment by trask** [comment]
I haven't seen failures due to this in a while, do you know if anything changed?
