### ISSUE TITLE
Provision to add current span as links to kafka consumer span

### ISSUE THREAD

**Issue by RashmiRam** [open-telemetry/opentelemetry-java-instrumentation#1756]
I am not entirely sure if this issue should be raised here or in Opentelemetry spec project. 

Current Kafka consumer instrumentation creates `consumer` spans from the context extracted from the record headers if this `otel.kafka.client.propagation.enabled` setting is enabled. If this setting is not enabled, `consumer` spans will take the current span as parent. Ref: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/kafka-clients-0.11/src/main/java/io/opentelemetry/javaagent/instrumentation/kafkaclients/KafkaConsumerTracer.java#L49-L55

Looking at the code, I suppose this is the case for other messaging instrumentations like rabbitmq, jms also(except for that setting). 

But, I think it will be really useful if the `consumer` spans have links to current span(if any) through addLink API even when propagation is enabled.

Do you folks think this is a valid ask?

**Comment by iNikem** [comment]
It is certainly a valid ask, but it should be started in the spec first. Take a look at https://github.com/open-telemetry/opentelemetry-specification/issues/1085 as well

**Comment by trask** [comment]
hi @RashmiRam! there's been a lot of changes/improvements/fixes to the messaging spans since this issue was opened, i'm curious what your experience is with the latest javaagent version?

**Comment by RashmiRam** [comment]
Hi @trask The main ask from me is that the configurable option to have the choice of adding current span as links  and producer span as parent to the consumer span and vice versa.

**Comment by trask** [comment]
is this for "receive" consumer spans or "process" consumer spans?

I believe "receive" consumer spans already parent the current span (and link to the message spans, since there can be multiple)

and "process" consumer spans typically don't have a current span (sort of like SERVER spans), though I guess they could, if this is what you are interested in could you explain your setup a bit more about what the current span is in your scenario? thx!

**Comment by trask** [comment]
Closing, let us know if you are still interested in this and we will re-open, thx!
