### ISSUE TITLE
Release 0.11.0

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java-instrumentation#1761]
Issue is created to track status of releasing 0.11.0
@iNikem could you please provide status? Is there a solution to deploy all artifacts? Is there ETA?
@pavolloffay as I remember from last SIG you also proposed some help?

**Comment by iNikem** [comment]
Oi, indeed, we wanted to release early this week, but that slipped us. 

@anuraaga @trask any thoughts on that? Or I can just press release tomorrow morning

**Comment by pavolloffay** [comment]
How did the issue with releasing the agent instrumentations go? Did the migration to artifactory or other release plugin help?

**Comment by iNikem** [comment]
Nothing happened in that regard. I got distracted by employer's work :(

**Comment by trask** [comment]
> @anuraaga @trask any thoughts on that? Or I can just press release tomorrow morning

worth a try 🤞

and when u have time, let us know your thoughts on the path forward / what you think we should try next

I can help do leg work, and @pavolloffay volunteered to help also

**Comment by anuraaga** [comment]
I was also thinking of just hitting the button, but hoping to get a last #1771 into the release :D

**Comment by iNikem** [comment]
@trask @anuraaga #1776

**Comment by anuraaga** [comment]
@malafeev 0.11.0 is in jcenter now - can you give it a shot?

**Comment by malafeev** [comment]
works for me @anuraaga
