### ISSUE TITLE
bytebuddyjava output not deterministic?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#1765]
I noticed bytebuddyjava rerunning basically always causes tests to rerun, even with the same sources. This shouldn't happen as we would expect the output of the task to be deterministic. Even if it's not cached and gets rerun every single time, it should only contribute its own time to the build, not the invalidation of downstream tasks.

**Comment by agoallikmaa** [comment]
It does indeed appear to be the case. When looking at the generated `getMuzzleReferenceMatcher` it seems that the order in which some flags are applied to the matcher builder can be random. One random example:

![diff2](https://user-images.githubusercontent.com/3532037/100256337-5a5d8e00-2f4d-11eb-9bf8-8e1754378c3f.png)

Will dig further.

**Comment by anuraaga** [comment]
@agoallikmaa Nice find - I am suspecting there is a HashMap that needs to be changed to a LinkedHashMap somewhere :)

**Comment by trask** [comment]
oh that's interesting! ya, we use `HashSet` in a bunch of places in muzzle generation
