### ISSUE TITLE
Support more span attributes in the AWS lambda wrapper

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1773]
The aim of this issue is to introduce support for most of the FAAS/cloud attributes defined in the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/faas.md). Currently only `faas.execution` is added to the span.

I think that the following attributes can be added pretty easily:
* `cloud.provider`
* `cloud.region`
* `faas.name`
* `faas.version`
* `faas.id` - this one is interesting, because it's marked as a resource attribute in the spec; in the context of AWS lambda functions ARN is used here and with the current implementation it's impossible to add it as a resource (because it can only be extracted from a lambda `Context` passed as a function parameter; the tracer is initialized before that happens)

Also, I'm planning to file a new spec issue so that the following things can be added (so this story will probably evolve in time):
* execution environment
* account id
* function qualifier

For `APIGatewayProxyRequestEvent`s I believe that we can implement most of the HTTP server spec - not sure about other event types though.

**Comment by anuraaga** [comment]
For resource attributes, it probably makes sense to keep them together with other resource providers instead of instrumentation, so adding `LambdaResource` here - https://github.com/open-telemetry/opentelemetry-java/tree/master/sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource

**Comment by mateuszrzeszutek** [comment]
> I think this is cloud.account.id

Nice! It was absent from the trace semantic conventions doc - I should probably. add it there.

> For resource attributes, it probably makes sense to keep them together with other resource providers instead of instrumentation, so adding LambdaResource here

Yep, that was exactly my intention.

**Comment by mateuszrzeszutek** [comment]
By the way @anuraaga : do you know if it's possible to get the account id from something other than the ARN? My idea was to just extract it from the ARN, but then again it cannot be a resource attribute.

**Comment by mateuszrzeszutek** [comment]
Also, regarding the execution environment: I thought about it and decided to use more generic `process.runtime.*` attributes instead. I'll create an issue & PR in otel-java.
