### ISSUE TITLE
Use sdk-extensions/resources in the agent

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1779]
`OsResource`, `ProcessResource` (and soon `ProcessRuntimeResource`) add some useful attributes, I think that the agent could include those.
Also I think that even if the user included this jar on the classpath the resources would not register because the context classloader for the SDK is the agent classloader, and it can't load external classes.

**Comment by anuraaga** [comment]
I think we should, only reason is probably no one did it yet :)

**Comment by mateuszrzeszutek** [comment]
Got it. Changing this issue to an enhancement
