### ISSUE TITLE
Scopes with invalid spans

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1806]
We have a check in place to prevent nested CLIENT spans:

```
  private Span internalStartSpan(REQUEST request, String name, long startTimeNanos) {
    Context context = Context.current();
    Span clientSpan = context.get(CONTEXT_CLIENT_SPAN_KEY);

    if (clientSpan != null) {
      // We don't want to create two client spans for a given client call, suppress inner spans.
      return Span.getInvalid();
    }
```

But we always call `tracer.startScope()` after `startSpan()` which results in the invalid span returned from the latter being put into the current context by the former. Which does not make sense. After CLIENT span was created it should always be the active span (until it ends of course).

**Comment by mateuszrzeszutek** [comment]
I wonder if we need to start a new scope for an invalid scope at all. Is there any use case where we intentionally want to do that? If not, we can just return noop scope from all `tracer.startScope()` methods if the span is not valid.

**Comment by iNikem** [comment]
I don't think that we should start new scope. So yes, returning `noop` is probably the right thing to do.
