### ISSUE TITLE
Inconsistent constraints between testLatestDep and muzzle

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#1826]
Up until recently we had in `jaxrs-client-2.0-jersey-2.0` a muzzle constraint like this:
```
  pass {
    group = "org.glassfish.jersey.core"
    module = "jersey-client"
    versions = "[2.0,)"
  }
```
and at the same time latest dep was defined as:
`latestDepTestLibrary group: 'org.glassfish.jersey.core', name: 'jersey-client', version: '2.27'`

Which means that we don't expect our tests to work with version later than 2.27 but we still expect muzzle to pass. Does not make sense. Muzzle broke on `3.0.0`, but tests still pass.

**Comment by jaydeluca** [comment]
is this issue still relevant? is there some action that should come of this?

**Comment by trask** [comment]
I'm not sure, reminds me of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/749, I think ok to close it
