### ISSUE TITLE
OTLP Exporter - mTLS does not work

### ISSUE THREAD

**Issue by mat-rumian** [open-telemetry/opentelemetry-java-instrumentation#1829]
**Describe the bug**
In case of **mTLS** usage an error occurs

**Steps to reproduce**
* Auto instrumented java application with OTLP exporter (0.10.1) and `insecure` flag set to `false`
* OpenTelemetry Collector version `0.14.1`
* Security certificates generated by this [script](https://github.com/nddipiazza/grpc-java/blob/master/examples/README.md#generating-self-signed-certificates-for-use-with-grpc)
* OpenTelemetry Collector OTLP receiver configuration: `  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
      http:
        endpoint: 0.0.0.0:55681
  otlp/tls:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55690
        tls_settings:
          cert_file: /etc/ssl/certs/server.crt
          key_file: /etc/ssl/certs/server.pem
  otlp/mtls:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55660
        tls_settings:
          cert_file: /etc/ssl/certs/server.crt
          key_file: /etc/ssl/certs/server.pem
          client_ca_file: /etc/ssl/certs/ca.crt`
* mTLS - client (instrumented application) required imported ca.crt, client.crt and client.pem certificates into docker image, server (collector) required server.crt, server.pem and ca.crt certificates  

**What did you expect to see?**
No errors in case of `mTLS` and spans sent to the collector.

**What did you see instead?**
`service-b    | [opentelemetry.auto.trace 2020-11-25 13:57:09:644 +0000] [grpc-default-worker-ELG-1-2] DEBUG io.grpc.netty.shaded.io.grpc.netty.Utils - Using custom allocator: forceHeapBuffer=false, defaultPreferDirect=true
service-b    | [opentelemetry.auto.trace 2020-11-25 13:57:09:669 +0000] [grpc-default-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine - SSL_read failed with 1: OpenSSL error: 268436498 error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE
service-b    | [opentelemetry.auto.trace 2020-11-25 13:57:09:673 +0000] [grpc-default-worker-ELG-1-3] DEBUG io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler - Ignoring duplicate failure
service-b    | io.grpc.StatusRuntimeException: UNKNOWN: Channel Pipeline: [SslHandler#0, ProtocolNegotiators$ClientTlsHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
service-b    |  at io.grpc.Status.asRuntimeException(Status.java:524)
service-b    |  at io.grpc.netty.shaded.io.grpc.netty.WriteBufferingAndExceptionHandler.exceptionCaught(WriteBufferingAndExceptionHandler.java:90)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:1104)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:827)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
service-b    |  at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
service-b    |  at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
service-b    |  at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
service-b    |  at java.lang.Thread.run(Thread.java:748)
service-b    | Caused by: io.grpc.netty.shaded.io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE
service-b    |  at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
service-b    |  at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
service-b    |  ... 13 more
service-b    | Caused by: javax.net.ssl.SSLHandshakeException: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:1007)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1271)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1225)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1296)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1339)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:205)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1340)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
service-b    |  at io.grpc.netty.shaded.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
service-b    |  ... 15 more`

**What version are you using?**
Java AI 0.10.1
OTelCol 0.14.1

**Environment**
Docker-compose environment. 

**Additional context**
`TLS` works fine. Traces are sent without any problems.

**Comment by anuraaga** [comment]
Hi @mat-rumian - sorry for the long delay on replying. We unfortunately don't have any way of enabling client TLS certificates right now. I have filed https://github.com/open-telemetry/opentelemetry-specification/issues/1363 in the specification for advice on how to define the variables for this. Sorry for the trouble.

**Comment by tmdonalds** [comment]
I experienced a similar behavior. I was trying to connect to an OpenTelemetryCollector from a Quarkus app. I used the javax.net.ssl.keystore, truststore, etc... properties on my Kubernetes Quarkus app. I know mutual tls works because I am able to communicate across Quarkus web applications using https with no problem at all. When I disable tls on the OpenTelemetryCollector, errors ensue. My Quarkus app is unable to reach the OpenTelemetryCollector and the OpenTelemetryCollector responds with `ailed: tls: first record does not look like a TLS handshake"    {"grpc_log": true}. 

Is there any update on this ticket? Are there any examples that show mtls to OpenTelemetryCollector? Thanks

**Comment by tmdonalds** [comment]
@mping-exo The problem I am running into is on the receiver. I have the following receiver config. 

```
    receivers:
      otlp:
        protocols:
          grpc:
            tls:
              ca_file: /etc/pki/ca-trust/ca.crt
              cert_file: /etc/pki/ca-trust/tls.crt
              key_file: /etc/pki/ca-trust/tls.key
```

And I have javax.net.ssl.props setup on my quarkus app but my quarkus application reports the following error. `[io.grp.net.NettyClientHandler] (grpc-nio-worker-ELG-1-1) Network channel is closed`. If I change to `tls: insecure` it works. I am not sure what I am missing. The self signed certificates have been created by cert-manager using the same issuer so both certificates should be trusted.

**Comment by trask** [comment]
mTLS is supported now, see https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-span-metric-and-log-exporters
