### ISSUE TITLE
Instrument Spring Batch

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1842]
The aim of this issue is to introduce a Spring Batch instrumentation into the Java agent.
It is intentionally very vague, as we don't even have a spec for batch jobs right now - it'll be filled with details over time.

**Comment by anuraaga** [comment]
Hi @mateuszrzeszutek - can this issue be closed now?

**Comment by mateuszrzeszutek** [comment]
Let's close it - when job semantic conventions (and/or spring batch specific conventions?) are in the spec we can open another issue for updating this instrumentation.
