### ISSUE TITLE
Question: Does anybody knows if there is any opentracing support for Java HttpClient ?

### ISSUE THREAD

**Issue by ghevge** [open-telemetry/opentelemetry-java-instrumentation#1851]
Does anybody knows if there is any opentracing support for Java HttpClient introduced in Java 11?

https://openjdk.java.net/groups/net/httpclient/intro.html

Thanks

**Comment by trask** [comment]
Hi @ghevge, this sounds like a question for the OpenTracing project

**Comment by iNikem** [comment]
Not related to this repo
