### ISSUE TITLE
Trace config property to indicate that the responsibility of deciding to trace or not is delegated to another component

### ISSUE THREAD

**Issue by dh-ger** [open-telemetry/opentelemetry-java-instrumentation#1865]
**Is your feature request related to a problem? Please describe.**
We are in the process of modernizing a legacy application and splitting out components into microservices.
We run in Kubernetes where we have many different APIs (ours is a spring boot API) and we sit behind an API gateway.
In terms of distributed tracing we use b3-multi propagation, and it is the responsibility of a component at the gateway to set the headers before forwarding to the appropriate service. For our product we chose to set `x-b3-sampled` to 1 for 1% of requests.
We have some other traffic that hits our API (health checks, integration tests etc), that originates from within the cluster that will not have the b3 headers set. What we find in this scenario is that the java-instrumentation will by default trace all of these, when ideally we would like to not trace them at all.
Of course we can control the probability, but this does not really work as desired for this case.

**Describe the solution you'd like**
A flag that would indicate that the instrumentation would operate in `passive` mode and rely on the values set as indicated by the selected propagation method, rather than initiating a trace if the headers are not set.

**Describe alternatives you've considered**
We tried setting the `otel.config.sampler.probability=0`, but this has the effect of not tracing anything, even when the headers are set by the gateway, as a workaround we set this to 0.001 so that only every 1/1000 requests that do not have headers get traced as a temporary workaround.

**Comment by iNikem** [comment]
Do I understand you correctly, that you want an option to run a javaagent in a mode, where it joins already existing trace but will not initiated new ones?

**Comment by dh-ger** [comment]
Yes, this essentially what it boils down to

**Comment by iNikem** [comment]
I think using `Sampler.parentBased(Sampler.alwaysOff())` sampler achieves this, no? The question remains, how do tell this javaagent to use this sampler...

**Comment by dh-ger** [comment]
So I had assumed that the desired behavior would be achieved when setting `otel.config.sampler.probability` to 0. 
However when this is set to 0, then it also does not join existing traces.

It is possible that your suggestion might work, however as you say I have no idea how to configure the javaagent to do this.

**Comment by trask** [comment]
another option is #1060

**Comment by dh-ger** [comment]
Yes, this would definitely solve the issue we have with health checks getting traced

**Comment by trask** [comment]
> I think using `Sampler.parentBased(Sampler.alwaysOff())` sampler achieves this, no? The question remains, how do tell this javaagent to use this sampler...

Closing, this should be possible now using

```
OTEL_TRACES_SAMPLER=parentbased_always_off
```

(https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler)
