### ISSUE TITLE
Instrumentation for RxJava 2

### ISSUE THREAD

**Issue by suman-aella** [open-telemetry/opentelemetry-java-instrumentation#1866]
Are there any plans to support the auto instrumentation for RxJava 2. The current instrumentation for RxJava 1 doesn't support the later major releases because of complete api change in new RxJava versions.

We use RxJava for processing our event data and currently unable to trace the internals.

Is there anyway we can do the trace context propagation in Rxjava and achieve this manually.

I see that we already have support for all rxJava versions in Open Tracing.
https://github.com/opentracing-contrib/java-rxjava/tree/master/opentracing-rxjava-2

Could we have it in the similar lines here.

**Comment by iNikem** [comment]
Current maintainers of this repo most probably will not have enough capacity to address this until after GA. Which means couple of months at least. External PRs are very welcomed :)

**Comment by pavolloffay** [comment]
datadog agent seems to support rxjava2 https://github.com/DataDog/dd-trace-java/tree/master/dd-java-agent/instrumentation/rxjava-2. 

As this agent is based on DD porting it here should be straight forward.

**Comment by piotr-sumo** [comment]
I'd like to contribute to this issue, how can I start?

**Comment by piotr-sumo** [comment]
PR can be found here https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2130

**Comment by piotr-sumo** [comment]
@mateuszrzeszutek @anuraaga could you close this issue?

**Comment by mateuszrzeszutek** [comment]
We have a library instrumentation of RxJava2, but we're still missing the javaagent one - so I think the issue's still valid.

**Comment by piotr-sumo** [comment]
Ok, so I will go back to my PR with javaagent instrumentation and make it ready for merging

**Comment by mateuszrzeszutek** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2130

Thanks @piotr-sumo !
