### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by pvyaka01** [open-telemetry/opentelemetry-java-instrumentation#1880]
What metrics are exposed for Prometheus?
This is all I see:
# HELP processedSpans The number of spans processed by the BatchSpanProcessor. [dropped=true if they were dropped due to high throughput]
# TYPE processedSpans counter
processedSpans{dropped="false",spanProcessorType="BatchSpanProcessor",} 33.0
# HELP queueSize The number of spans queued
# TYPE queueSize gauge
queueSize{spanProcessorType="BatchSpanProcessor",} 0.0

**Comment by trask** [comment]
hi @pvyaka01, the java agent is not producing metrics yet

**Comment by iNikem** [comment]
I am closing this issue as the original question seems to be answered. @pvyaka01 if you have more questions, please start a new discussion in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions

**Comment by devrimdemiroz** [comment]
I started related discussion: https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/2168
