### ISSUE TITLE
Server span handling is inconsistent

### ISSUE THREAD

**Issue by laurit** [open-telemetry/opentelemetry-java-instrumentation#1886]
Servlet integration can only capture requests that pass though a servlet filter or servlet. So on tomcat, which relies on servlet integration, request to paths that are outside of deployed application are not captured. On jetty where integration triggers before request reaches servlet such requests are captured. Similarly on liberty where static content is not served by a servlet, requests to static files are not captured when only servlet-4.0 feature is enabled, but are captured when javaee-8.0 feature is enabled because javaee-8.0 adds a servlet filter to the application. We should add integrations that handle server spans similarly to jetty for other popular app-servers. But in order to do that we should agree on how to name such server spans consistently across integrations.

Servlet integration sets span name to request.getContextPath() + request.getServletPath(). Jetty integration sets span name to HandlerCollection.handle for jetty9 and HandlerList.handle for jetty10. Could anybody elaborate what is the desired value for span name? Should it be changed so that server spans would have a consistent naming?

**Comment by vovencij** [comment]
In general, the solution that is done for Jetty integration doesn't scale to everything else – jetty integration doesn't instrument some specific handler classes that process Servlets, so that servlet integration will fully handle requests to servlets and jetty integration will act as a fallback. Tomcat, for example doesn't have such architecture where it would be possible to not instrument some specific servlet-related classes to separate such cases. More scalable solution would be to allow for servlet handler to just update the name of the server span (which maybe later updated by more specific web-framework integration) in case it is already in the context.

**Comment by iNikem** [comment]
Is my understanding below is correct?

There are HTTP servers, such as Jetty or Undertow, which provide their own framework of "Handlers" to response to incoming http requests. Some of built-in handlers actually implement Servlet API and delegate to some servlets. Current instrumentations either focus solely on Servlet API (e.g. Tomcat) or try to have two disjoint instrumentations: for Servlets and for everything else (e.g. Jetty).

This proposal is to have first class instrumentations for HTTP servers which would create SERVER spans for all intercepted requests, regardless if they later end up in Servlets or not. And our Servlet instrumentations will just update name and set additional attributes to already existing SERVER span. Similar to how e.g. Spring MVC instrumentation does.

If I understood you correctly, then I think this is great idea :)

**Comment by iNikem** [comment]
Regarding SERVER span name: it still should be name of the handling class plus name of the handling method. If we know some more specific information about given requests, e.g. that it is for static content, we may reflect that in the name. And we still have to follow [general rules](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#name).

**Comment by vovencij** [comment]
> And our Servlet instrumentations will just update name and set additional attributes to already existing SERVER span.

Servlet instrumentation would still act as a fallback to create SERVER spans for yet unsupported servlet containers.

**Comment by trask** [comment]
Closing now that we have agreement and have implemented for a few application servers.
