### ISSUE TITLE
Muzzle should add SPI classes defined in helperResourceNames as references

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#1887]
**Is your feature request related to a problem? Please describe.**
Currently muzzle does not look at the injected resource files at all, so when we inject service provider files (like in log4j2 instrumentation) to make helper injection & muzzle validation work we need to add an empty advice class with a `muzzleCheck()` method. This is ugly and the javaagent behavior is non-obvious.

**Describe the solution you'd like**
Muzzle compile time reference collection process could inspect files returned by the `helperResourceNames()` method and if the match one of the following patterns load classes defined in them as references.
* `META-INF/services/.*` - `ServiceLoader` SPI file pattern
* `/software/amazon/awssdk/services/[^/]+/execution.interceptors` - AWS SDK execution interceptors SPI file pattern

**Additional context**
This would prevent situations like https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1876 from happening

**Comment by anuraaga** [comment]
Sorry Amazon didn't use normal SPI - no clue what happened there 😅
