### ISSUE TITLE
Add support for apache dubbo.

### ISSUE THREAD

**Issue by chenmudu** [open-telemetry/opentelemetry-java-instrumentation#1888]
Maybe can do some enhancements to apache dubbo.  Is this feasible?   thanks very much!

**Comment by tydhot** [comment]
@iNikem assign to me plz

**Comment by anuraaga** [comment]
Thanks @tydhot :) If it's possible to start with library instrumentation so we support both agent and non-agent users, that would be great!

**Comment by tydhot** [comment]
@anuraaga Thank you for your advice :)

**Comment by mateuszrzeszutek** [comment]
Implemented in #2108 - closing.
