### ISSUE TITLE
Kafka Polling - Issue with instrumentation

### ISSUE THREAD

**Issue by IraSkyx** [open-telemetry/opentelemetry-java-instrumentation#1890]
@nicolas63 and I are working on integrating Open Telemetry to an existing microservices architecture with nested libraries such as Vertx (and Vertx-Kafka) 3.8, RxJava 2, MongoDB. We chose Jaeger as the Collector/Query UI. 
But we are having struggles finding why our traces at some point of the project are split up. 

**Describe the bug**
When using Vertx and RxJava 2 as separate packages and batch processing Kafka messages we end up with a split trace. Context is therefore probably not propagated because no spans are dropped (according to Jaeger). We're pretty unsure about what's causing this. It doesn't occur when processing messages one-by-one and when we're not using RxJava 2 in addition. 

**Steps to reproduce**

We sat up a project to isolate the problem. It's composed of 3 services communicating through Kafka and HTTP. 
Service 1 produces messages that Service 2 consumes in batch and send HTTP request to Service 3.

1.  Setup Jaeger (ref https://www.jaegertracing.io/docs/1.21/getting-started/)
2.  git clone https://github.com/IraSkyx/kafka-batch-issue
3.  Launch Service 3, then Service 2 and finally Service 1 to push messages
4.  Head towards Jaeger and inspect the trace

**What did you expect to see?**
We expect to see a full trace : Kafka send -> Kafka process -> HTTP Request -> Netty request

**What did you see instead?**
We see a split up Trace instead of just one
![Trace 1](https://github.com/IraSkyx/kafka-batch-issue/blob/master/trace1.png)
![Trace 2](https://github.com/IraSkyx/kafka-batch-issue/blob/master/trace2.png)

**What version are you using?**
Version 0.12.0

**Environment**
Compiler: AdoptOpenJDK jdk-8.0.272.10-openj9
OS : Windows

**Comment by malafeev** [comment]
probably related to #1866

**Comment by IraSkyx** [comment]
Actually not related to rxjava2. We made another branch (https://github.com/IraSkyx/kafka-batch-issue/tree/without-rxjava2), this time without using rxjava2. Same problem occurs.

**Comment by IraSkyx** [comment]
Could anyone take a look at this?

**Comment by trask** [comment]
hi @IraSkyx, can you try to track down where the context is lost by using the OpenTelemetry API to check `Span.current().getSpanContext().getTraceIdAsHexString()` in various places?

**Comment by IraSkyx** [comment]
> hi @IraSkyx, can you try to track down where the context is lost by using the OpenTelemetry API to check `Span.current().getSpanContext().getTraceIdAsHexString()` in various places?

@trask Finally figured it out, polling by design isn't a place where context can be rebuild from kafka headers due to the fact that it's processing N records all linked to N different remote contexts. So we had to use TextMapPropagator.Getter ourselves to extract traceparent-ID from a single record and create one span per record handling so that subsequent call to any intrumented library can use that span to propagate the parent context. 

Any way you could improve instrumentation support for batch kafka processing? 

Below are additions we made to https://github.com/IraSkyx/kafka-batch-issue/blob/master/service2/src/main/java/launcher/Start.java#L69 :

```diff
private static Promise<Void> handleRecord(KafkaConsumerRecord<String, String> rec) {
+        TextMapPropagator.Getter<KafkaConsumerRecord<String, String>> getter =
+                new TextMapPropagator.Getter<KafkaConsumerRecord<String, String>>() {
+                   @Override
+                   public String get(KafkaConsumerRecord<String, String> carrier, String key) {
+                       Map<String, String> extracted = extractHeaders(carrier);
+                        if (extracted.containsKey(key)) {
+                            return extracted.get(key);
+                        }
+                        return null;
+                    }
+
+                    @Override
+                    public Iterable<String> keys(KafkaConsumerRecord<String, String> carrier) {
+                        return carrier.headers().stream().map(h -> h.key()).collect(Collectors.toList());
+                    }
+                };

        Promise promise = Promise.promise();

+        Context extractedContext = OpenTelemetry.getGlobalPropagators().getTextMapPropagator().extract(Context.current(), rec, getter);

+        Span span =
+                OpenTelemetry.getGlobalTracer("io.opentelemetry.javaagent.kafka-clients")
+                        .spanBuilder("POLLING SPAN")
+                        .setSpanKind(Span.Kind.CONSUMER)
+                        .setParent(extractedContext)
+                        .startSpan();

+        try (Scope scope = span.makeCurrent()) {
            Future<Void> futureResult = Start.treatment(rec);
            System.out.println("13 " + Span.current().getSpanContext().getTraceIdAsHexString());
            futureResult.setHandler(ar -> {
                System.out.println("14 " + Span.current().getSpanContext().getTraceIdAsHexString());
                if(ar.succeeded()) {
                    promise.complete();
                }
                else {
                    promise.fail("Error");
                }
            });
+        } catch (Throwable t) {
+            span.setStatus(StatusCode.ERROR, "Change it to your error message");
+        } finally {
+            span.end(); // closing the scope does not end the span, this has to be done manually
+        }

        return promise;
    }
```

**Comment by iNikem** [comment]
@IraSkyx as a quick note, is https://github.com/open-telemetry/opentelemetry-specification/issues/1085 relevant to your problem?

**Comment by IraSkyx** [comment]
@iNikem It's totally related, although in our case it makes sense to have the producer span used as parent in a batch processing but if I correctly understand your proposal, that's not what you state. 

In a batch process, why wouldn't it make sense to use trace-parent-id propagated through message headers instead of the current active span? It'd allow us to analyze problem causes coming from before the initial producer. That'd solve our problem of split traces.

**Comment by previousdeveloper** [comment]
same problem

**Comment by carlosalberto** [comment]
Hey @IraSkyx 

I can't see your example anymore (repo doesn't exist), but it seems you were modifying code that is part of Vertx, i.e. `KKafkaConsumerRecord` in the Vertx API. - in that case, it looks like Vertx-Kafka is the component **without** instrumentation support, hence the problem. Is this the case?

**Comment by IraSkyx** [comment]
Hi @carlosalberto 

I brought the repo back up so you can take a look. You could be right, it could be related to Vertx-Kafka though I am not modifying anything, just using the library. The lack of support for this and the way otel handles the relation between a producer and its consumers could possibly lead to the problem we have.
