### ISSUE TITLE
rocketMq  support

### ISSUE THREAD

**Issue by voidmanun** [open-telemetry/opentelemetry-java-instrumentation#1916]
Maybe can do some enhancements to rocketMq. Is this feasible? thanks very much!

**Comment by addname** [comment]
@iNikem assign to me plz

**Comment by addname** [comment]
[add rocketmq support issue#1916 ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2216)

**Comment by addname** [comment]
[Add instrumentation for rocketmq](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2263)
