### ISSUE TITLE
Disable auto instrumentation for specific library

### ISSUE THREAD

**Issue by navyacs** [open-telemetry/opentelemetry-java-instrumentation#1920]
As per the document specified you can suppress agent instrumentation of specific libraries by using 
-Dotel.instrumentation.[id].enabled=false
   where id is the instrumentation id
I need the id of jdbc library. It would be helpful if anyone can specify where I can get the instrumentation id of jdbc library.

**Comment by mateuszrzeszutek** [comment]
It's just `jdbc` - so you can disable the entire JDBC instrumentation by passing `-Dotel.instrumentation.jdbc.enabled=false`.

**Comment by iNikem** [comment]
Id of the instrumentation can be looked up in the constructor of the corresponding `InstrumentationModule`. E.g. for Jdbc it s https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f82e9107d6eca855426b77775b50bd7337a0743c/instrumentation/jdbc/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jdbc/JdbcInstrumentationModule.java#L18 -> `jdbc`.

Hope this answer your question, @navyacs :)
