### ISSUE TITLE
Tracing sensitive information should be configurable

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-java-instrumentation#193]
There should be a way to limit tracing of e.g. SQL statements, user names etc. A configuration variable-based approach seems like the natural approach. 

Question: Should this also be configurable per instrumentation? E.g. trace statements for JDBC but not for Couchbase?

**Comment by trask** [comment]
Closing, I believe the primary use case around SQL has been addressed, and others can be opened as separate issues as they arise.
