### ISSUE TITLE
GlobalIgnoresMatcher uses the old package name "io.opentelemetry.auto" for ignore matcher

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#1946]
Update GlobalIgnoresMatcher use of old package name `io.opentelemetry.auto.` to new package name `io.opentelemetry.javaagent`.

Unfortunately there are complications:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1919#discussion_r545861543

At the same time, would be good to apply the same filter to `RedefinitionDiscoveryStrategy` (see same discussion above).

**Comment by laurit** [comment]
The easiest fix would be to move aws-lambda tests to a different package. Most of the other tests are in default package. @trask would moving these tests to default package be ok?

**Comment by trask** [comment]
oh yes, that makes sense to me, keeping javaagent tests in the default package, and does follow existing convention 👍

**Comment by anuraaga** [comment]
Ah I didn't know there was a reason to keep tests in the default package. I've been putting my tests in non-default package since sometimes IntelliJ was running the wrong test if two tests were named the same even in different modules. Not sure if it was a fluke or not.

**Comment by anuraaga** [comment]
That being said if #1643 alleviates everything it would be nice to not have hidden restrictions on test locations.

**Comment by trask** [comment]
ya, it would be easy to miss the restriction on test location and get very confusing results

I don't think #1643 will help though with bringing back the global ignore on `io.opentelemetry.javaagent`?

**Comment by anuraaga** [comment]
@trask Ah don't know. I thought that's what this comment meant :)

> As a side note, this may not be needed after #1643, because then we won't be retransforming the whole world anymore during tests, but #1643 needs to land first 😭.

**Comment by mateuszrzeszutek** [comment]
Closed by #2440
