### ISSUE TITLE
Jaeger exporter does not pull sampling strategies from collector

### ISSUE THREAD

**Issue by sambaatteamf1** [open-telemetry/opentelemetry-java-instrumentation#1953]
**Describe the bug**
the tracer config does not allow setting a specific sampler. The sampler is chosen based on the value of otel.config.sampler.probability(See https://github.com/open-telemetry/opentelemetry-java/blob/7c0b45209761443c2dd7f9a659ba6e99aded222b/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/config/TraceConfigBuilder.java#L132)

I want to configure the javaagent to use jaeger remote sampler (https://github.com/open-telemetry/opentelemetry-java/tree/7c0b45209761443c2dd7f9a659ba6e99aded222b/sdk-extensions/jaeger-remote-sampler), so that i can filter traces for health check.

**Steps to reproduce**
1. configure service with agent
2. Define sampling stratgey in jaeger . See https://www.jaegertracing.io/docs/1.21/sampling/
3. Have the setup in the configuration below
service -> collector -> jaeger

**What did you expect to see?**
The agent must filter or sample based on the sampling strategy 

**What did you see instead?**
No filtering or sampling being done 

**What version are you using?**
v0.10.0. This issue should also be reproducible on the latest

**Environment**
Issue is not environment specific

Compiler: AWS Corretto 8
OS: Ubuntu 18.04

**Additional context**
n/a

**Comment by bforbis** [comment]
Hi, is there still a gap here? I'm trying to understand how to use remote sampling and it's not well documented currently.

**Comment by mateuszrzeszutek** [comment]
Hey @bforbis,
You could implement a javaagent [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/README.md) that includes the [jaeger-remote-sampler](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/jaeger-remote-sampler) module - this should allow you to configure jaeger remote sampling.

**Comment by pavolloffay** [comment]
This will be done as part of #4898. 

The sampling strategies are not pulled in the exporter. `JaegerRemoteSampler` is responsible for getting the sampling configuration and executing sampling.

**Comment by pavolloffay** [comment]
I will close this one in favor of #4898. 

thanks for reporting and letting us know about using the Jaeger remote sampler.
