### ISSUE TITLE
add skip urls config for enhancement.

### ISSUE THREAD

**Issue by chenmudu** [open-telemetry/opentelemetry-java-instrumentation#1962]
**Is your feature request related to a problem? Please describe.**
add skip urls config for enhancement.

**Describe the solution you'd like**
Some other URLs should be skipped for servlet enhancement or others, not all.
Although otel-col 's  sampling rules can do this, it is reasonable to intercept here.

Hope my suggestion can be considered, thanks very much!

**Comment by trask** [comment]
Closing, duplicate of #1606

**Comment by iNikem** [comment]
@trask I am not sure I understand how does #1606 solve this problem.

**Comment by trask** [comment]
oops, meant #1060
