### ISSUE TITLE
JMS instrumentation creates spans when no messages are received

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-instrumentation#1989]
It is common for users and frameworks to poll JMS for messages.  Depending on the system, there could be long periods where no messages are received.  Spring `@JmsListener` implementations, for example, poll JMS every second...and if no messages have been sent, the instrumentation still creates jms receive CONSUMER spans every second.  Any invocation of  `MessageConsumer.receive(timeout)` that times out without a message is also in this boat.

This potentially creates a large number of undesirable spans that the user will have to sift through, at worst, and possibly even pay for.  It is expected that spans should not be created if no messages are actually read from JMS.

The simplest way to reproduce this is to wire up a spring jms application that uses `@JmsListener`.  Spring will create a `DefaultMessageListenerContainer.AsyncMessageListenerInvoker` that will poll every second, ultimately ending up in `JmsDestinationAccessor` which calls `MessageConsumer.receive(timeout)` which is [ultimately handled by the JmsMessageConsumerInstrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/jms-1.1/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jms/JmsMessageConsumerInstrumentation.java#L43).

The solution might be as simple as returning early from `ConsumerAdvice.stopSpan()` before the span is created.

**Comment by laurit** [comment]
This also causes flakiness in `SpringListenerJms1Test` where test can receive more consumer spans than expected. Adding a sleep before `expect:` block makes it fail reliably.

**Comment by trask** [comment]
Those polling spans are very noisy. This sounds great.

**Comment by shadabbahadara** [comment]
> ultimately handled by the JmsMessageConsumerInstrumentation

Could you please let me know how do we add support of jms instrumentation in spring boot jms project?

**Comment by mateuszrzeszutek** [comment]
Hey @shadabbahadara ,
What do you mean by the "spring boot jms project"? Are you using the javaagent, or perhaps the spring-boot-autoconfigure library? Can you open a new issue with the details of your setup and the desired state of things?
