### ISSUE TITLE
The Tracer name (instrumentation name) should always uniquely identify the instrumentation module

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#1992]
This is related to PR #1979 and would be a change from the decision made in #1260 . 

It is important when debugging spans to know precisely what instrumentation module created the spans, especially when there are crazy classpaths in play in the end-user's application. For this to work, every instrumentation module should use a unique name for the Tracers that are created. So, when there are multiple versions of the servlet instrumentation, for example, the tracer name should reflect which one is being used.

**Comment by trask** [comment]
This makes sense to me, anything we can do to improve troubleshooting / supportability is a high priority.

**Comment by anuraaga** [comment]
I would explain this issue as the tracer name should reflect the artifact name. Since our artifact names always have a version, our tracer names should too, and is actually basically what the spec defines for the value of instrumentation_library :)

**Comment by iNikem** [comment]
So we are bringing back the old behaviour that some users found confusing and we agreed with them? :) I kinda agree that identification of the instrumentation module is important. And yes, using artifact name seems like the simplest solution. But then we have to address #1260 in some other way.

**Comment by jkwatson** [comment]
> So we are bringing back the old behaviour that some users found confusing and we agreed with them? :) I kinda agree that identification of the instrumentation module is important. And yes, using artifact name seems like the simplest solution. But then we have to address #1260 in some other way.

The confusion was that the instrumentation name didn't specifically identify which versions of the instrumented library were being handled, correct? The proposed change here at least give *some* information, as opposed to what we have now, which is precisely *no* version information.

**Comment by anuraaga** [comment]
I think it's ok to not worry too much about #1260. The field is `InstrumentationLibraryInfo.name` - the fact that a name may have a number in it seems like more of a coincidence.

Adding `InstrumentedLibraryInfo` to the proto would probably be the clearest, not sure anyone has the appetite to add it :)

**Comment by iNikem** [comment]
Fixed by #1979

**Comment by trask** [comment]
re-opening, #1979 resolves this for the servlet instrumentation, I think makes sense to apply this change across all instrumentation
