### ISSUE TITLE
Provide an option for an ultra-lean no-auto-instrumentation agent

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#1994]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but it would be handy to be able to have no auto-instrumentation, but at least have support for manual instrumentation using `@WithSpan` plus normal API interactions.

This could also be used to do some overhead measurement, both startup and runtime.

**Describe the solution you'd like**
Have a way, preferably with a simple command line switch to disable all auto-instrumentation.

**Describe alternatives you've considered**
Just using standard API/SDK usage, but then `@WithSpan` doesn't work.

Thanks!

**Comment by fuleow** [comment]
I am also interested in this feature and was under the impression that you could disable all the auto instrumentation using `-Dotel.instrumentation.default-enabled=false` and selectively enabling some using `-Dotel.instrumentation.<name>.enabled=true`. Is that not the case?

**Comment by jkwatson** [comment]
> I am also interested in this feature and was under the impression that you could disable all the auto instrumentation using `-Dotel.instrumentation.default-enabled=false` and selectively enabling some using `-Dotel.instrumentation.<name>.enabled=true`. Is that not the case?

If this ends up just being a documentation request, then all the better!

**Comment by trask** [comment]
oh ya, I think this is correct:

> `-Dotel.instrumentation.default-enabled=false` and selectively enabling some using `-Dotel.instrumentation.<name>.enabled=true`

would be great if someone can verify and doc here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/docs/suppressing-instrumentation.md

**Comment by jkwatson** [comment]
This combination seems to do what I'm asking for:

```
-Dotel.instrumentation.opentelemetry-annotations.enabled=true -Dotel.instrumentation.default-enabled=false
```
