### ISSUE TITLE
Auto Instrumentation for prometheus

### ISSUE THREAD

**Issue by arnabnandy1706** [open-telemetry/opentelemetry-java-instrumentation#2001]
Hello All,

I am trying to implement Auto instrumentation for a sample java application.

the command I am trying is:
```
java -javaagent:opentelemetry-javaagent-all.jar \
     -Dotel.exporter=prometheus \
     -jar target/*.jar
```

But it gives me below error:
```
[opentelemetry.auto.trace 2021-01-08 11:05:14:339 +0000] [main] WARN io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller - No prometheus span exporter found
[opentelemetry.auto.trace 2021-01-08 11:05:14:349 +0000] [main] INFO io.opentelemetry.javaagent.exporters.prometheus.PrometheusMetricServer - Creating Prometheus exporter on host: '0.0.0.0' and port: '9464'
[opentelemetry.auto.trace 2021-01-08 11:05:14:407 +0000] [main] INFO io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller - Installed metric server: io.opentelemetry.javaagent.exporters.prometheus.PrometheusMetricServer
```

Please help me how I can enable auto instrumentation.

And also let me know if there is any specific documentation present for the prometheus monitoring with opentelemetry where I can find the prometheus queries to monitor the traces and metrics.

Thank you

**Comment by anuraaga** [comment]
Hi @arnabnandy1706 - are you not able to see any metrics on that port? We have a misleading error message there about span exporter but the metric exporter was installed successfully as in the below log line.

That said, our instrumentation is only for tracing right now and until we add metrics instrumentation, the only metrics you would generally see are those for span exporters.

**Comment by arnabnandy1706** [comment]
Hello @anuraaga 

But I dont see any metrics or traces in prometheus. Also I dont see any metrics when I access http://localhost:9464/metrics or http://localhost:9464

**Comment by arnabnandy1706** [comment]
Hello All,

any help on this would be appreciated.

**Comment by anuraaga** [comment]
@arnabnandy1706 Are you using `GlobalMeterProvider` to get a meter and record some metrics? I realized that since you don't have a span exporter, you wouldn't see any span metrics so unless you are recording something, there would just not be any metrics being recorded.

If you are, would it be possible to share some sample code of what you're using for us to check it out?

**Comment by iNikem** [comment]
@arnabnandy1706 is this issue still relevant to you?

**Comment by anuraaga** [comment]
Hi @arnabnandy1706 - going to close this issue for now, if you're still having any problems please feel free to reopen it.
