### ISSUE TITLE
Not cleanly shutting down SDK on JVM exit

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2006]
I haven't looked at the code at all yet but we got this report

```
It actually DID work, but unlike what I assumed, it seems that the traces exporting isn't "flushed" on JVM end, so nothing was logged and I thought it didn't work. An extra Thread.sleep(6000) did it.
```

https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/1945#discussioncomment-268455

Agent users shouldn't need to add `Thread.sleep` to make sure traces get flushed in the end so let's check if we are missing something (possibly a `.join()`)

/cc @tobias-

**Comment by trask** [comment]
done in main by autoconfigure
