### ISSUE TITLE
Armeria decorators should have access to the request `Span`

### ISSUE THREAD

**Issue by tobias-** [open-telemetry/opentelemetry-java-instrumentation#2016]
**Describe the bug**
When I add a decorator, said decorator should have access to a valid span when handling a request.

**Steps to reproduce**
```kotlin
fun main() {
    val sb = Server.builder()
        .decorator { delegate, ctx, req ->
            System.err.println("2 - " + Span.current().spanContext.spanIdAsHexString)
            delegate.serve(ctx, req)
        }
        .serviceUnder("/") { ctx, req ->
            System.err.println("3 - " + Span.current().spanContext.spanIdAsHexString)
            HttpResponse.of(200)
        }
        .decorator { delegate, ctx, req ->
            System.err.println("1 - " + Span.current().spanContext.spanIdAsHexString)
            delegate.serve(ctx, req)
        }
        .port(8081, SessionProtocol.HTTP)
        .reorderDecorators()
        .build().start()
}
```

**What did you expect to see?**
the same id printed three times

**What did you see instead?**
`1` and `2` are invalid, `3` is valid

**What version are you using?**
`3b88bb75ae2e6065424f6b21440e0c63c2e7726f`

**Environment**
Compiler:
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
OS: Ubuntu 20.04

**Additional context**
I believe the problem is that the decorator is inserted right in the `Server.builder()`. It should probably be inserted in the `.build()` instead (although that opens another can of worms if the `.build()` is called multiple times).

**Workaround**
```kotlin
package com.linecorp.armeria.server

import java.util.LinkedList

/** Put the oldest added decorator as first decorator **/
fun ServerBuilder.reorderDecorators(): ServerBuilder {
    val rdsField = VirtualHostBuilder::class.java.getDeclaredField("routeDecoratingServices")
    rdsField.isAccessible = true
    @Suppress("UNCHECKED_CAST")
    val rds = rdsField.get(virtualHostTemplate) as LinkedList<RouteDecoratingService>
    rds.addFirst(rds.removeLast())
    return this
}
```

**Comment by anuraaga** [comment]
Hmm weird - I thought decorators run in order they're added so the opentelemetry decorator would need to be added first, hence adding in `builder`. Will have to dig into what could be happening, thanks for the report.

**Comment by anuraaga** [comment]
By the way, there's a far dumber bug that still needs to be fixed which you're luckily not running into (yet :P) since the example uses `DecoratingServiceFunction` instead of `Function`

https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1670

**Comment by anuraaga** [comment]
Seems like the decoration order changed in 1.3.0. I'll probably change the agent to only support Armeria 1.3+ instead of bothering with a version split for it.

Armeria's still my favorite server framework, but quite a shame to see the semantic version break 😿
