### ISSUE TITLE
Agent does not log its version anymore when starting 

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#2023]
It's a minor thing but I find it really useful - it's easy to know which version is used when you're investigating an issue in a system that you do not have direct access to.

Anyway, the problem is that `OpenTelemetryInstaller#logVersionInfo()` is no longer called from anywhere after latest changes.

**Comment by anuraaga** [comment]
Heh yeah noticed this in some bug report log statements, it's highly useful!
