### ISSUE TITLE
Remove TRACE_ANNOTATED_METHODS_EXCLUDE?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2032]
TRACE_ANNOTATED_METHODS_EXCLUDE excludes specific WithSpan methods. But it seems like it could be overkill when we have OTEL_JAVAAGENT_EXCLUDE_CLASSES already. Less configuration options to reason about.

**Comment by trask** [comment]
I believe this feature was introduced in #344, so will be good to hear from @iNikem and @johnbley

**Comment by iNikem** [comment]
Imagine situation similar to some of our smoke test: Spring MVC controller with a private method annotated with `WithSpan`. You may want to silence `WithSpan` but still have Spring MVC integration working.

Thus I think that both of these options should live.

**Comment by anuraaga** [comment]
@iNikem I was thinking the class could be excluded, which would still allow spring MVC integration to continue, just not for that controller. The thinking is that per-method just seems like extreme granularity - maybe it's worth it though.

**Comment by iNikem** [comment]
But I do want to have Spring MVC spans for that controller :) Just not `WithSpan` spans.

**Comment by iNikem** [comment]
@anuraaga are you convinced to close this issue?

**Comment by anuraaga** [comment]
Yeah
