### ISSUE TITLE
Guard some smoke tests behind CI flag?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2058]
When developing, especially for infrastructure work like updating dependencies, it's nice to run `./gradlew check` to make sure everything is fine. But currently smoke tests take 15+min on Mac (presumably Docker is much slower on Mac than on CI), and actually fail with a timeout for me. I guess many of the tests are sort of "for good measure", I'm thinking the many app servers. Does it make sense to slice them out to only run on CI?

**Comment by trask** [comment]
Makes sense to me, maybe all smoke tests, just to make it easy to doc/explain, instead of slicing out only some of them.

I don't think it's too surprising to have to opt in to running smoke tests.

**Comment by anuraaga** [comment]
Yeah `SpringBootSmokeTest` used to be my standard to make sure the actual agent works properly. Now that normal tests do that, indeed just disabling default smoke tests entirely is probably fine too.
