### ISSUE TITLE
Add smoke test for otel.exporter.jar

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2076]
I believe we don't currently have any testing of otel.exporter.jar.

**Comment by karthikinamanamelluri** [comment]
@anuraaga Any idea if this is broken? 
I am trying to use newrelic exporter using otel.exporter.jar by passing below property, but it is not working
-Dotel.exporter.jar=opentelemetry-exporters-newrelic-auto-0.9.0.jar

**Comment by trask** [comment]
hi @karthikinamanamelluri! I would recommend pinging the NewRelic folks for help with this

**Comment by trask** [comment]
Closing, this has been replaced by `otel.javaagent.experimental.extensions`, which has nice smoke tests under `examples/extension`
