### ISSUE TITLE
Compatibility with whitebox instrumentation

### ISSUE THREAD

**Issue by yurishkuro** [open-telemetry/opentelemetry-java-instrumentation#211]
This is more of a strategy question. In opentracing-java-specialagent, the approach was to use auto-instrumentation only as a bridge between existing whitebox (explicit) instrumentation, by auto-wiring it into the application via byte-code instrumentation (BCI). However, when I look at `instrumentation` module here, it does not seem to be usable as standalone whitebox instrumentation, only as part of BCI. Is my understanding correct? If so, what was the reasoning for doing it this way?

**Comment by yurishkuro** [comment]
cc @tedsuo

**Comment by william-tran** [comment]
I think this is a result of this project's origins: https://github.com/DataDog/dd-trace-java/tree/master/dd-java-agent. What I really like about https://github.com/opentracing-contrib/java-specialagent is its plugin framework. The lack of plug-ability in the dd java agent was a problem and I would not want to see that persist in this new project.  

For example, I found an issue with DD's gRPC instrumentation: https://github.com/DataDog/dd-trace-java/issues/1120. I provided a PR in November 2019 to fix it, and it was merged in January. This same issue did exist in grpc opentracing support, but this was fixed way back in 2017:  https://github.com/grpc-ecosystem/grpc-opentracing/issues/15. I was not able to even build a patched version of the dd java agent on my build infra, so I was stuck with informing my users to disable the gRPC auto-instrumentation and add the community maintained whitebox instrumentation to their services manually. 

Continuing this architecture places too high a maintenance burden on the maintainers of this project, and make this far too difficult to extend for your own needs. This is why I've chosen to use specialagent instead. If I find a problem in a community contributed integration, I can easily swap it out for my own fixed version. I can write my own rules that instrument my own domain concepts.  cc @safris

**Comment by trask** [comment]
Hi @yurishkuro, @william-tran!

Providing both auto and "contrib" (non-auto/whitebox/explicit) instrumentation based on the same codebase and validated with the same tests is a high priority (see the sparsely documented #45).

@william-tran We don't have a specific issue tracking the ability to bring-your-own auto instrumentation, but it's definitely something we've discussed in the weekly SIG meetings and is something everyone agrees on.

**Comment by trask** [comment]
Closing this now, good progress is being made on these topics in several other issues and PRs.
