### ISSUE TITLE
Rework Rpc*Tracer

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2132]
Currently we have very boring RpcServerTracer / RpcClientTracer classes. As we found in #2108 we need to give them some features.

One special thing about RPC may be that in many cases, server and client are literal mirror images. So it will often be preferable if we can use just one class for both instead of two like in that PR.

**Comment by mateuszrzeszutek** [comment]
I guess we now have `RpcAttributesExtractor` and `RpcSpanNameExtractor`, we don't need the tracer anymore.
