### ISSUE TITLE
Instrumentation for Apache HttpClient5

### ISSUE THREAD

**Issue by tafli** [open-telemetry/opentelemetry-java-instrumentation#2157]
It seems that only Apache HttpClient 2/4 are supported right now. Are there any plans for supporting v5?

My project is using Apache HttpClient5 and I wanted to use the auto instrumentation for it.

**Comment by anuraaga** [comment]
Fixed in #2254

**Comment by anuragagarwal561994** [comment]
@anuraaga the current instrumentation provides the metrics for classic httpclient5 instrumentation, do we have a plan to also provide the instrumentation for the http async client.

I can help contribute, but will need a little guidance for the same.

**Comment by trask** [comment]
hi @anuragagarwal561994! I would recommend opening a new issue for this. I don't believe anyone is working on httpclient5 async instrumentation, that would be a great addition if you want to contribute!
