### ISSUE TITLE
Gaps in trace or just a slow VM

### ISSUE THREAD

**Issue by eriklagerholm** [open-telemetry/opentelemetry-java-instrumentation#2183]
Not sure if a bug or something in our setup. It could well be that the instrumentation is all fine and it's our code that behaves this way. Let me know if this isn't the place for such a question and I'll remove it. 

**Describe the bug**
We're seeing gaps in our traces using the auto instrumentation as well as `@WithSpan` annotations. We're not sure if the gaps are due to issues with the tracing, or if the gaps indicate waiting/blocking in the JVM.

![image](https://user-images.githubusercontent.com/7983352/106860475-b9b1ea00-66c4-11eb-896b-fe2b01e08d60.png)

**Steps to reproduce**
Not sure how to provide that, this might be very specific to our application, whose setup is quite intricate. See additional context.

**What did you expect to see?**
We expect to see no gaps in the trace. We expect to see all spans accounted for in the visualisation. (And maybe they actually are).

**What did you see instead?**
We see a top level trace, that takes say 40s. Then we have a large number of small, very fast spans. Then a gap for several seconds, and then a large number of small spans again before the top level trace finishes.

**What version are you using?**
0.15.0

**Environment**
Compiler: Kotlin 1.4.20
OS: Alpine Linux on Docker
Runtime (if different from JDK above): Java11

**Additional context**
We run a graphql API using Spring Boot and JPA. We have a bunch of external services that we call using gRPC. I realize that graphql isn't auto-instrumented, so we have added spans manually in some places.

**Comment by anuraaga** [comment]
Hi @eriklagerholm - are you using any sort of asynchronous pattern here, `CompletableFuture`, kotlin coroutines, etc? That might explain that so many spans are microseconds long - I'm assuming Firebase isn't quite that fast :P

**Comment by eriklagerholm** [comment]
Thanks for the reply @anuraaga ! Yes, there are `CompletableFutures` involved for some calls. We use data loaders to cache graphQL objects. 

But actually for Firebase that call is hitting our own DB through JPA. So that might be as fast as is reported. And most of the calls in the trace are actually synchronous as far as I know.

**Comment by anuraaga** [comment]
Do any of the methods with withspan return CompletableFuture? Those currently would not measure time until completion, only time until return. There is WIP to get that working.

The trace does look strange unless you are doing tens of ms of brute work in your auth filter, or there is a huge full gc there. Which I guess is possible. But I'm wondering if one of the spans is ending before the request is actually completed if annotating an async method.

**Comment by anuraaga** [comment]
Ah by the way are you missing any spans for client calls you'd expect? Maybe the middle gap is just uninstrumented code that should have more spans

**Comment by richardstartin** [comment]
@anuraaga we radically overhauled async context propagation at Datadog last autumn, it may be worth taking a look at our java-concurrent module in its current state because this refactoring completely eliminated this kind of problem.

**Comment by eriklagerholm** [comment]
> Do any of the methods with withspan return CompletableFuture? Those currently would not measure time until completion, only time until return. There is WIP to get that working.

I think most of the calls are to JPA repositories, and those are not returning futures as far as I know.

> The trace does look strange unless you are doing tens of ms of brute work in your auth filter, or there is a huge full gc there. Which I guess is possible. But I'm wondering if one of the spans is ending before the request is actually completed if annotating an async method.

I've looked at the possibility of the GC pausing the machine. We do seem to have such issues. Not Full GC but Major GC run every 10-15 minutes. I'm going to keep digging and see if there is also uninstrumented code that may be producing the gap as well.

**Comment by trask** [comment]
hey @eriklagerholm, it might be interesting to look at a JFR capture (with `settings=profile`) from the same time period. If you can post it here I can see if anything pops out.

**Comment by eriklagerholm** [comment]
Thank you, I will try to get a JFR. I'll post here when done. Might need some tweak to our containerization to get it going.

**Comment by eriklagerholm** [comment]
I've just realized that there is a whole heap of `CompletableFutures` involved in the above trace. This is due to the graphQL execution model. So our strongest theory for these gaps is currently that uninstrumented code.

**Comment by trask** [comment]
hey @eriklagerholm I'm also curious about @anuraaga's question above:

> are you missing any spans for client calls you'd expect?

If you are missing spans for client calls, then that points to the javaagent not propagating context properly to those call points. Though in this case, those client calls should still be getting captured, they just won't be correlated/included in the transaction flow screenshot above.

If you aren't missing spans for client calls, then the JFR profile would be interesting.

**Comment by trask** [comment]
Closing, but please let us know if you are still having this issue and we will re-open.

**Comment by eriklagerholm** [comment]
Hi! Sounds good. For posterity: we went with a different telemetry provider and thus are not having this problem anymore.
