### ISSUE TITLE
Custom Resource info

### ISSUE THREAD

**Issue by Lovnx** [open-telemetry/opentelemetry-java-instrumentation#2189]
**Is your feature request related to a problem? Please describe.**
this agent tool sends trace info to Jaeger, expand one span like that:
![image](https://user-images.githubusercontent.com/26428832/106844584-e1fd1100-66e3-11eb-9bbb-87bed198fd76.png)
 but I do not need one of info, such as `process.runtime.description`, How to remove it?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by anuraaga** [comment]
Hi @Lovnx - are you able to use the opentelemetry collector? It can be configured to receive in OTLP from the java agent and export to Jaeger

https://github.com/open-telemetry/opentelemetry-collector

Then you can use the attributes processor for tweaking attributes

https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/attributesprocessor

We don't currently have a good way of filtering individual attributes with just the agent. There is a flag to disable complete resource namespaces though, for example, you can disable all the `process` fields with `-Dotel.java.disabled.resource_providers=io.opentelemetry.sdk.extension.resources.ProcessResource`.

**Comment by Lovnx** [comment]
cp that, appreciate your reply :+1:
