### ISSUE TITLE
When specify  exporter-jar by -Dotel.exporter.jar, the OtlpGrpcSpanExporter and OtlpGrpcMetricExporter are also installed

### ISSUE THREAD

**Issue by lshangq** [open-telemetry/opentelemetry-java-instrumentation#2193]
**Describe the bug**
When specify  exporter-jar by -Dotel.exporter.jar, the OtlpGrpcSpanExporter and OtlpGrpcMetricExporter are also installed. 

logs as below
[grpc-default-executor-2] WARN io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter - Failed to export spans. Error message: UNAVAILABLE: io exception
[grpc-default-executor-1] WARN io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics

**Steps to reproduce**
java -javaagent:path/to/opentelemetry-javaagent-all.jar \
     -Dotel.exporter.jar=path/to/external-exporter.jar \
     -jar myapp.jar

**What did you expect to see?**
When specify  exporter-jar by -Dotel.exporter.jar, the default exporter includes OtlpGrpcSpanExporter and OtlpGrpcMetricExporter are not installed except for explict specification.

**What did you see instead?**
When specify  exporter-jar by -Dotel.exporter.jar, the OtlpGrpcSpanExporter and OtlpGrpcMetricExporter are also installed. 
**What version are you using?**
v0.15.0

**Environment**
openjdk version "1.8.0_202
OS: centos7.3

**Additional context**

**Comment by anuraaga** [comment]
This is definitely a change in behavior we should fix. In the meantime you may want to disable the default exporters with `OTEL_TRACE_EXPORTER=none` and `OTEL_METRICS_EXPORTER=none`

**Comment by lshangq** [comment]
Thanks, will it be fixed before release 1.0.0

**Comment by trask** [comment]
Closing, as we are moving from `otel.exporter.jar` to `otel.javaagent.extensions` in #2442, where this will be possible by providing a custom property source, e.g.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/25dd2cf194117bde5d50a9eef30bf4937071a40d/testing/agent-exporter/src/main/java/io/opentelemetry/javaagent/testing/exporter/AgentTestingExporterPropertySource.java#L13-L22
