### ISSUE TITLE
gradlew idea fails with "Could not find org.scala-sbt:compiler-bridge_2.8:1.3.5"

### ISSUE THREAD

**Issue by quijote** [open-telemetry/opentelemetry-java-instrumentation#2195]
I pulled latest master and got the following error when executing `gradlew idea`

    Execution failed for task ':ideaProject'.
    > Could not resolve all files for configuration ':instrumentation:scala-executors:javaagent:detachedConfiguration2'.
       > Could not find org.scala-sbt:compiler-bridge_2.8:1.3.5.
        Searched in the following locations:
        - file:/home/markus/.m2/repository/org/scala-sbt/compiler-bridge_2.8/1.3.5/compiler-bridge_2.8-1.3.5.pom
        - https://repo.maven.apache.org/maven2/org/scala-sbt/compiler-bridge_2.8/1.3.5/compiler-bridge_2.8-1.3.5.pom
        - https://jcenter.bintray.com/org/scala-sbt/compiler-bridge_2.8/1.3.5/compiler-bridge_2.8-1.3.5.pom
        - https://repo.typesafe.com/typesafe/releases/org/scala-sbt/compiler-bridge_2.8/1.3.5/compiler-bridge_2.8-1.3.5.pom
        Required by:
            project :instrumentation:scala-executors:javaagent

I think the issue is that this was removed here: https://dl.bintray.com/typesafe/maven-releases/org/

**Comment by mping** [comment]
Same here

**Comment by trask** [comment]
Closing, I suspect this was resolved by #2783, please let us know if you still see this and we will re-open.
