### ISSUE TITLE
Does this agent support dynamic attach to JVM?

### ISSUE THREAD

**Issue by Lovnx** [open-telemetry/opentelemetry-java-instrumentation#2198]
**Is your feature request related to a problem? Please describe.**
Can u show me a sample, if the agent file is agent.jar.
with `java -Xbootclasspath`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by trask** [comment]
hi @Lovnx, it does not, there's some relevant discussion in #1932 if you are interested

**Comment by trask** [comment]
Closing, dynamic attach is not something we plan to officially test/support.
