### ISSUE TITLE
Smoke tests on Windows

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#2201]
We have smoke tests for different application services, such as WildFly or Tomcat. Currently they run only on Ubuntu Linux. Is there an interest in having those tests run on Windows as well? If yes, and if https://github.com/open-telemetry/community/issues/629 means that we actually can do that, then I can contribute them.

**Comment by trask** [comment]
Yes, this would be great 👍

**Comment by iNikem** [comment]
Closed by #2617
