### ISSUE TITLE
MethodInstrumentationModule not working

### ISSUE THREAD

**Issue by markfink-splunk** [open-telemetry/opentelemetry-java-instrumentation#2211]
**Describe the bug**
Trying to trace methods with -Dotel.instrumentation.methods.include=hipstershop.AdService[GetAds,getRandomAds].  Not getting spans on the methods.  Debug log shows it is applying the methods instrumentation, but no spans for those methods.

**Steps to reproduce**
I'm just adding otel.instrumentation.methods.include per above, which appears to be what is expected.  Is there anything wrong with it or anything else to be set?  I am not otherwise adding anything to the source -- which is to say, I am not adding @WithSpan to the methods.  My understanding is that otel.instrumentation.methods.include should substitute for that.

**What did you expect to see?**
I expect to see spans for those methods.

**What did you see instead?**
I get traces that contain a single span from the grpc instrumentation, but nothing for those methods.

**What version are you using?**
0.15.0

**Environment**
Resource labels:
     -> environment: STRING(hipster_shop)
     -> os.description: STRING(Linux 4.19.121-linuxkit)
     -> os.type: STRING(LINUX)
     -> process.command_line: STRING(/usr/local/openjdk-8/jre:bin:java -javaagent:/app/build/install/hipstershop/lib/opentelemetry-javaagent-all.jar -Dotel.javaagent.debug=true -Dotel.instrumentation.methods.include=hipstershop.AdService[GetAds,getRandomAds] -agentpath:/opt/cprof/profiler_java_agent.so=-cprof_service=adserviceclient,-cprof_service_version=1.0.0)
     -> process.executable.path: STRING(/usr/local/openjdk-8/jre:bin:java)
     -> process.pid: INT(1)
     -> process.runtime.description: STRING(Oracle Corporation OpenJDK 64-Bit Server VM 25.282-b08)
     -> process.runtime.name: STRING(OpenJDK Runtime Environment)
     -> process.runtime.version: STRING(1.8.0_282-b08)
     -> service.name: STRING(adservice)
     -> telemetry.auto.version: STRING(0.15.0)
     -> telemetry.sdk.language: STRING(java)
     -> telemetry.sdk.name: STRING(opentelemetry)
     -> telemetry.sdk.version: STRING(0.15.0)

**Comment by iNikem** [comment]
@markfink-splunk When I look at [AdService class](https://github.com/GoogleCloudPlatform/microservices-demo/blob/fee184176f8f545edda71b53ff69a8380f20be23/src/adservice/src/main/java/hipstershop/AdService.java) then I see that methods `GetAds` and `getRandomAds` are defined not in class `AdService`, but in inner class `AdServiceImpl`. If you change your config to `-Dotel.instrumentation.methods.include=hipstershop.AdServiceImpl[GetAds,getRandomAds]`, does it help?

If not, can you share the full debug log?

**Comment by markfink-splunk** [comment]
@iNikem So...getAds is part of inner class AdServiceImpl.  getRandomAds is not part of that; that is part of AdService.  I am not sure how I missed getAds.  Plus I had a capital G on it.  I must've been blurry eyed yesterday!  I apologize for that.

However, this has led to an observation that, it may not be a bug exactly, but it may be something you want to look at:

I ended up with this as a working config:
`-Dotel.instrumentation.methods.include=hipstershop.AdService\$AdServiceImpl[getAds];hipstershop.AdService[getRandomAds]
`
That creates a span for both getAds and getRandomAds.

What is interesting is that yesterday, I had this:
`-Dotel.instrumentation.methods.include=hipstershop.AdService[GetAds,getRandomAds]
`
And this fails completely.  Intuitively, I should have gotten a span for getRandomAds, and then GetAds should simply fail.  Instead, both fail.

In any case, the "working config" up above is indeed working.

Lastly, can I recommend we add a note about otel.instrumentation.methods.include on the main README?  I can add a PR for that.

**Comment by PeterF778** [comment]
Is there anything to do for this ticket?

**Comment by trask** [comment]
> Lastly, can I recommend we add a note about otel.instrumentation.methods.include on the main README? I can add a PR for that.

@markfink-splunk check out https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/#creating-spans-around-methods-with-otelinstrumentationmethodsinclude. if there's anything additional you'd like to see there, a PR to https://github.com/open-telemetry/opentelemetry.io would be great

**Comment by ryadav-collab** [comment]
Hi Team,

I am facing similar issue, methods were not getting shown up in otlp logs  ( trying auto instrumentation ).
Used below flag along with 
output looks as below without method details
============================
Span #7
    Trace ID       : 25605110614ccd12b8d36435378c0c
    Parent ID      :
    ID             : 500f7ba49157f2
    Name           : INSERT INTO ERRORS
    Kind           : SPAN_KIND_CLIENT
    Start time     : 2022-10-03 15:13:45.84 +0000 UTC
    End time       : 2022-10-03 15:13:46.2299066 +0000 UTC
    Status code    : STATUS_CODE_UNSET
    Status message :
Attributes:
     -> db.user: STRING(scott)
     -> net.peer.port: INT(1221)
     -> db.connection_string: STRING(myhost:thin://mydb:1221)
     -> net.peer.name: STRING(myhost)
     -> db.system: STRING(mysystem)
     -> db.statement: STRING(insert into test values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?))
     -> db.sql.table: STRING(test)
     -> thread.id: INT(73)
     -> db.operation: STRING(INSERT)
     -> db.name: STRING(mydb)
     -> thread.name: STRING(Executor task launch worker for task 0)
        {"kind": "exporter", "data_type": "traces", "name": "logging"}
2022-10-03T20:43:47.897+0530    info    MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 22}
2022-10-03T20:43:47.897+0530    info    ResourceMetrics #0
Resource SchemaURL:
Resource attributes:
     -> service.name: STRING(otel-collector)
     -> service.instance.id: STRING(localhost:8888)
     -> net.host.port: STRING(8888)
     -> http.scheme: STRING(http)


Properties used while running my app.
=====
java -javaagent:opentelemetry-javaagent.jar   -Dotel.traces.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.logs.exporter=otlp  -Dotel.instrumentation.methods.include=myclass1[applyFunction]"  myapp.jar


otlp exporter i run as below using config yaml file.

=======

cmd => .\otelcol.exe  --config=file:./otel.config.yaml

otel.config.yaml
===========
extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679



receivers:
  otlp:
    protocols:
      grpc:
      http:

  opencensus:
      
  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['localhost:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  batch:

exporters:
  logging: 
    logLevel: debug

service:

  pipelines:

    traces:
      receivers: [otlp, opencensus, jaeger, zipkin]
      processors: [batch]
      exporters: [logging]

    metrics:
      receivers: [otlp, opencensus, prometheus]
      processors: [batch]
      exporters: [logging]

  extensions: [health_check, pprof, zpages]
