### ISSUE TITLE
Fix ProcessMetrics Implementation

### ISSUE THREAD

**Issue by brunnert** [open-telemetry/opentelemetry-java-instrumentation#2231]
I have recently tried to collect metrics for a Java application using Oshi and the ProcessMetrics Implementation provided here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/oshi/library/src/main/java/io/opentelemetry/instrumentation/oshi/ProcessMetrics.java

I think the current state of the implementation should be improved as follows:

- The "runtime.java.memory" metric should be collected using a longValueObserverBuilder instead of using  a longUpDownSumObserverBuilder as the memory value returned by Oshi here is a snapshot of the current memory consumption value and not a sum of the total memory demand
- The "runtime.java.cpu_time" should be collected using a doubleSumObserverBuilder instead of using a doubleValueObserver as the values returned by the Oshi library are sums
- The conversion from milliseconds to seconds seems to be wrong, instead of multiplying by 1000 to get from ms to s, the value needs to be divided by 1000 or multiplied by 0.001

Here is a modified version of the relevant code pieces:

    //Modified original code to use a longValueObserverBuilder
    meter
        .longValueObserverBuilder("runtime.java.memory")
        .setDescription("Runtime Java memory")
        .setUnit("bytes")
        .setUpdater(
            r -> {
              processInfo.updateAttributes();
              r.observe(processInfo.getResidentSetSize(), Labels.of(TYPE_LABEL_KEY, "rss"));
              r.observe(processInfo.getVirtualSize(), Labels.of(TYPE_LABEL_KEY, "vms"));
            })
        .build();

    //Modified original code to use a doubleSum Observer
    meter
        .doubleSumObserverBuilder("runtime.java.cpu_time")
        .setDescription("Runtime Java CPU time")
        .setUnit("seconds")
        .setUpdater(
            r -> {
              processInfo.updateAttributes();
              // getUserTime() returns the number of milliseconds the process has executed in user mode.
              r.observe(processInfo.getUserTime()  * 0.001 /*convert to s*/, Labels.of(TYPE_LABEL_KEY, "user"));
              // getKernelTime() returns the number of milliseconds the process has executed in kernel/system mode.
              r.observe(processInfo.getKernelTime()  * 0.001 /*convert to s*/, Labels.of(TYPE_LABEL_KEY, "system"));
            })
        .build();`

**Comment by iNikem** [comment]
1000ms = 1s, thus to get from ms to s you have to divide by 1000, not to multiply.

**Comment by trask** [comment]
@brunnert can you try with the latest javaagent release and let us know if you are still seeing any of these issues?
