### ISSUE TITLE
http-url-connection instrumentation creates on error spans without http.status_code attribute

### ISSUE THREAD

**Issue by rkondrashov** [open-telemetry/opentelemetry-java-instrumentation#2244]
**Describe the bug**

Spans for HTTP calls made with _HttpURLConnection_ or a client like _RestTemplate_ from Spring Boot, which uses it, have no `http.status_code` attribute on errors with response status 4xx and 5xx. If a response has status 1xx, 2xx or 3xx the attribute is present.

| **Status 1xx, 2xx and 3xx**          | **Status 4xx and 5xx**               |
| -------------------------------------------- | ----------------------------------------- |
| ![http-status-200](https://user-images.githubusercontent.com/12693997/107496739-fb91d300-6b91-11eb-92f3-0df4e7d1ef45.png) | ![http-status-500](https://user-images.githubusercontent.com/12693997/107496855-2419cd00-6b92-11eb-8e4e-bd916d6ec161.png) |

**Steps to reproduce**

I've created a sample project to reproduce this issue at [https://github.com/rkondrashov/opentelemetry-span-without-status](https://github.com/rkondrashov/opentelemetry-span-without-status).

1. Build the project with `mvn clean package`.
2. Start the service, httpbin and jaeger using `docker-compose up -d` and wait until all components are started.
3. Call `./calls.sh` script to perform some HTTP calls to the service.
4. Take a look at traces in jaeger UI - [http://localhost:16686](http://localhost:16686).
5. Stop all components using `docker-compose down`.

Alternatively the service could be started without docker:

1. Build the project with `mvn -Dexec.skip clean package`.
2. Start the service:
```bash
java -javaagent:path/to/opentelemetry-javaagent-all.jar \
       -Dotel.traces.exporter=logging \
       -Dotel.metrics.exporter=none \
       -jar target/opentelemetry-span-without-status-1.0.0.jar \
       --httpbin.uri=https://httpbin.org/status
```
3. Call `./calls.sh` script to perform some HTTP calls to the service. 

**What did you expect to see?**

Spans on error with response status 4xx or 5xx have the `http.status_code` attribute.

**What did you see instead?**

The attribute `http.status_code` in spans on error with response status 4xx or 5xx missing.

**What version are you using?**

v0.16.0

**Environment**
Compiler: AdoptOpenJDK 11.0.9
OS: Mint 20.1

**Additional context**

The same issue with java agent v0.13.x, v0.14.x and v0.15.x.

**Comment by breedx-splk** [comment]
I think I have reproduced this.  Please assign to me to fix.

**Comment by breedx-splk** [comment]
@rkondrashov once a snapshot gets published with this fix, it would be awesome if you could circle back and confirm that it works for you now.  Thanks again for reporting this...pretty huge IMO.  😄

**Comment by rkondrashov** [comment]
I've built the agent from the main branch and retested, the issue is fixed now, thanks a lot!
