### ISSUE TITLE
Proposed testing-common improvements and refactorings

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#2248]
* Reuse AssertJ-based assertions from [the SDK testing module](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk/testing/src/main/java/io/opentelemetry/sdk/testing/assertj). This probably requires adding a bit of functionality to the SDK assertions first (there probably are some asserts that we have here and they're missing from the SDK testing module). Ideally in this repo we should only have thin Groovy wrappers over the SDK testing assertions.
* Migrate as many test utilities from Groovy to Java (e.g. `TraceUtils`)
* ~~Refactor `InMemoryExporter`: it's not really an exporter, it only provides the `waitForTraces()` method. We should add a shortcut method to `InstrumentationSpecification`/`InstrumentationExtension` classes so that direct calls to `waitForTraces()` are eliminated.~~ This is already done
* Package structure:
  * `io.opentelemetry.testing` should be the general base package for all testing classes and utilities
  * All spock-related Groovy code should be in the package `io.opentelemetry.testing.spock` (base classes, assertion wrappers)
  * Javaagent bridging should be in the package `io.opentelemetry.testing.javaagent`

**Comment by jaydeluca** [comment]
I believe pretty much all the items in this issue are completed

**Comment by trask** [comment]
Closing, this has been done as part of #7195.
