### ISSUE TITLE
Nested `@WithSpan`  are not honored with  `version: 0.16.0` as in `version: 0.15.0`

### ISSUE THREAD

**Issue by mnadeem** [open-telemetry/opentelemetry-java-instrumentation#2257]
**Describe the bug**
opentelemetry-javaagent - version: 0.16.0 does not honor nested `@withSpan`

As can be seen here `version: 0.15.0` clearly honors nested  `@withSpan`

 opentelemetry-javaagent - version: 0.15.0
![image](https://user-images.githubusercontent.com/476145/107734101-9d482a00-6d22-11eb-9596-a3e75a78729d.png)

Same code does not work for `0.16.0`
opentelemetry-javaagent - version: 0.16.0
![image](https://user-images.githubusercontent.com/476145/107734255-f748ef80-6d22-11eb-9035-befeedefe5e1.png)

**Steps to reproduce**
Follow the steps as documented [here](https://reachmnadeem.wordpress.com/2021/02/10/instrumenting-spring-boot-application-for-opentelemetry-traces-over-grafana-tempo-jaeger/)

**What did you expect to see?**
Nested `@WithSpan` should be honored with  `version: 0.16.0`

**What did you see instead?**
Nested `@WithSpan`  are not honored with  `version: 0.16.0` as in `version: 0.15.0`

**What version are you using?**
(e.g., ``version: 0.16.0`)

**Environment**
````
C:\Program Files\Java\jdk1.8.0_261\jre;bin;java.exe -javaagent:agent/opentelemetry-javaagent-all-0.16.0.jar -Dotel.traces.exporter=jaeger -Dotel.exporter.jaeger.endpoint=localhost:14250 -Dotel.resource.attributes=service.name=spring-boot-instrumentation -Dotel.javaagent.debug=false -Dotel.metrics.exporter=none -Dfile.encoding=UTF-8
````
OS (if different from OS compiled on): Windows 10 and in Openshift

**Additional context**

**Comment by trask** [comment]
hi @mnadeem! Have you updated your `opentelemetry-extension-annotations` to 0.16.0? Prior to version 1.0, the version of the javaagent and the version of the API/annotations need to be in sync.

**Comment by mnadeem** [comment]
Yup,

FYI : I am using bom

![image](https://user-images.githubusercontent.com/476145/107865587-fda7aa80-6e8d-11eb-9914-6898e1c59701.png)

**Comment by mnadeem** [comment]
You can refer https://github.com/mnadeem/boot-opentelemetry-tempo  to easily replicate the problem by changing the agent jar and pom dependencies.

**Comment by anuraaga** [comment]
Hi @mnadeem - I checked out https://github.com/mnadeem/boot-opentelemetry-tempo and couldn't find any issue. You can see my modifications here

https://github.com/anuraaga/boot-opentelemetry-tempo/tree/0.16.0

The spans all seem to be parented correctly. Are you seeing a problem?

![image](https://user-images.githubusercontent.com/198344/108033392-4a020e80-7077-11eb-9608-2de540d5e714.png)

**Comment by mnadeem** [comment]
Thanks @anuraaga 

Hmm, interesting.. let me double check.

**Comment by mnadeem** [comment]
Thanks a bundle @anuraaga 

Things look good to me as well, not sure what was the issue

![image](https://user-images.githubusercontent.com/476145/108233180-86159c00-7169-11eb-889e-ef67ed841c29.png)
