### ISSUE TITLE
"Typed Spans" is confusingly named

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java-instrumentation#229]
(following up on https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/195)

Typed spans as originally described in https://github.com/open-telemetry/oteps/pull/25 and now proposed in https://github.com/open-telemetry/opentelemetry-java/pull/964 are a concept that tries to make sure at compile time that semantic conventions are followed / make it easy for the user / instrumentation-writer to follow semantic conventions.

What this SIG currently calls typed spans seems to be actually a framework for instrumentation writers that attempts to make it easy for them / force them to properly think about processing the right inputs at the right time.

I think both the instrumentation framework and the semantic convention helpers are useful concepts, but IMHO the term "typed spans" is already occupied with the latter.

**Comment by Oberon00** [comment]
Further prior art: https://github.com/danielkhan/opencensus-node-typed-span-sample/blob/master/src/HTTPClientSpan.ts, https://github.com/census-instrumentation/opencensus-specs/issues/257

**Comment by thisthat** [comment]
I think this can be achieved with the #195 proposal.
For instance, an HTTP client can set its Semantic Attributes when starting the span (in addition to inject the context).

https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/cecabe522af64aef4ca03b9225d303645b3ff77e/agent-tooling/src/main/java/io/opentelemetry/auto/typed/client/http/HttpClientTypedTracer.java#L27-L31

**Comment by Oberon00** [comment]
Sure it can. But it does so using the plain Span API, nothing is typed in that aspect. Am I missing something?

**Comment by thisthat** [comment]
My comment was to stress that the two things can coexists and are not mutually exclusive

**Comment by Oberon00** [comment]
Yeah, I agree. See also my gitter comment: https://gitter.im/open-telemetry/opentelemetry-auto-instr-java?at=5e6a6e6c80cc7b7924be1c2f

**Comment by trask** [comment]
Hi @Oberon00! Would it be possible for you to join the auto-instrumentation SIG meeting on Thu 3/26 @ 9am Pacific Time to discuss?

When we reviewed the two proposals in last week's SIG meeting with @tylerbenson and @thisthat, these were the only differences that we identified:

| #195 | https://github.com/open-telemetry/opentelemetry-java/pull/964 |
| --- | --- |
| TypedTracer | SpanBuilderWrapper |
| Inject/Extract | user implemented |
| DelegatingSpan | getRaw() to access underlying span |
| end(response) | end(statusCode) |

(somewhat disorganized meeting notes [here](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw))

But it seems like you are seeing a more fundamental difference, that I would very much like to understand, in case there's any way for us to still combine efforts on this.

Thanks,
Trask

**Comment by Oberon00** [comment]
The typed Spans by @thisthat have the single purpose of making it easy to follow semantic conventions, i.e. setting the right set of attributes with the right value types. Does the instrumentation framework in this repo fulfill the that purpose too?

**Comment by Oberon00** [comment]
To repeat myself from gitter (https://gitter.im/open-telemetry/opentelemetry-auto-instr-java?at=5e6a6e6c80cc7b7924be1c2f): I don't think the two approaches are alternatives at all. I think the ones implementing derived classes for the base classes provided with the instrumentation framework can use the typed spans by @thisthat in their implementation.
```java
  @Override
  protected SampleHttpClientTypedSpan onRequest(Request r) {
    httpClientSpan.setUserAgent(r.getHeader("User-Agent")); // Using @thisthat's typed span.
   // instead of: delegate.setAttribute("http.user_agent", r.getHeader("User-Agent"));
   // ...
    return this;
  }
```

**Comment by trask** [comment]
Hey! I think I understand now!

So https://github.com/open-telemetry/opentelemetry-java/pull/964 is all about the attribute setter methods?

And the goal is to only have one of these "typed spans" per semantic convention. And they are not designed for subclassing. E.g. one `final` class for http client spans, one `final` class for http server spans, one `final` class for database spans, etc?

**Comment by Oberon00** [comment]
Exactly! It's about providing kind of a "reduced" interface to setAttribute/the SpanBuilder that encourages (but does not force) you to follow semantic conventions.

**Comment by trask** [comment]
👍

I'm thinking we can just refer to the span hierarchy in #195 as "Spans". I'm not sure we need a special name for them.

We can just refer to them as `HttpClientSpan`, `HttpServerSpan`, `ApacheHttpClientSpan`, etc...

If we do need a name for them, maybe we could call them "Instrumentation Spans", since the goal is for these to live under `io.opentelemetry.instrumentation` and be used by both auto- and contrib- instrumentation.

**Comment by iNikem** [comment]
I propose to close this issue. We have moved on from the time when it was filed.

#502 proposes _typed spans_ in their original form: classes with setter corresponding to semantic convention. This repo has already for some time used new _typed tracers_: classes that allow instrumentation writes to set right attributes at the right time. So I think @Oberon00 concern is actually resolved.

**Comment by trask** [comment]
Closing.

@Oberon00, @thisthat please feel free to comment here, we are happy to re-open and continue discussing.
