### ISSUE TITLE
Document best practises for using classloader matchers in agent instrumentations

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#2332]
[Our docs](docs/contributing/writing-instrumentation.md) do a pretty good job explaining how to write new instrumentations. But they miss at least one piece of advice: when, how and why to use `InstrumentationModule.classLoaderMatcher` and `TypeInstrumentation#classLoaderOptimization` methods.

**Comment by mateuszrzeszutek** [comment]
This is now documented in https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/writing-instrumentation-module.md
We can probably close this issue.
