### ISSUE TITLE
HttpClientTest.test https request checks wrong net.peer.ip

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2344]
HttpClientTest.test https request makes a request to `https://www.google.com/`. But the `net.peer.ip` check still compares to `127.0.0.1` which google.com naturally isn't.

**Comment by laurit** [comment]
Most http client instrumentations don't set `net.peer.ip`, the ones that do (netty, vertx) don't run this test. When this test is enable in `Netty41ClientTest` it fails `net.peer.ip` assertion.

**Comment by anuraaga** [comment]
Yup noticed in #2345 since we set it there too.
