### ISSUE TITLE
Complete Observability Stack Realtime example

### ISSUE THREAD

**Issue by mnadeem** [open-telemetry/opentelemetry-java-instrumentation#2354]
**Is your feature request related to a problem? Please describe.**
Real World project demonstrating Complete Observability Stack utilizing Prometheus, Loki (For distribute logging), Tempo ( Distribute tracing, this basically uses Jaeger : OpenTelemetry Auto / manual Instrumentation), Grafana for  Java/spring applications involving multiple microservices with DB interactions

**Describe the solution you'd like**
Spring Boot Java Applications : https://github.com/mnadeem/boot-opentelemetry-tempo

**Describe alternatives you've considered**
N/A

**Additional context**
With just docker-compose up things would work out of the box.

Further the java version has support for both 0.15 and 0.16 ot (There is a minor difference in both)

![image](https://user-images.githubusercontent.com/476145/108576627-48209f80-7344-11eb-8938-b8387624822d.png)

**Comment by iNikem** [comment]
@mnadeem Sorry, I am somewhat confused about what exactly do you ask for? :) If you already have an example application which demonstrates Otel usage with those technologies, what do you ask of us? :)

**Comment by mnadeem** [comment]
Hi @iNikem,

I have integrated complete observability solution utilizing opentelemetry (0.15 and 0.16) with real time examples, it would be helpful for the community get started with very minimal efforts, if we could refer this project in Opetelemetry getting stated / Helps .

Any thoughts on this.

**Comment by trask** [comment]
hey @mnadeem! I don't know where the best place is to reference this from. There are a couple existing places I'm aware of, though maybe not the best fit:
* https://github.com/open-telemetry/community/blob/main/ADOPTERS.md
* https://opentelemetry.io/registry/

cc: @tedsuo @austinlparker in case they have ideas

**Comment by austinlparker** [comment]
If you'd like to write a short tutorial to add as a post on the website, that'd be great @mnadeem

**Comment by mnadeem** [comment]
Perfect, I would Love to do that.

Please let me know the process,  @austinlparker

**Comment by austinlparker** [comment]
You could perhaps add a new page to the Java docs (https://github.com/open-telemetry/opentelemetry.io/tree/main/content/en/docs/java) that included a link to your repository?

**Comment by austinlparker** [comment]
Probably best to open an issue/PR over in the website repo so we get out of the java maintainers hair ;)

**Comment by mnadeem** [comment]
Perfect makes sense

**Comment by mnadeem** [comment]
Created pull request https://github.com/open-telemetry/opentelemetry.io/pull/425

**Comment by iNikem** [comment]
Closing this issue as it was addressed by PR in community repo
