### ISSUE TITLE
Not mapped requests should be instrumented as HTTP {method}

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2355]
Currently our HttpServerTest verifies that the span name for a not found request is the request path. As the request was not actually mapped, there is no route to match it against so this can only be achieved with a high cardinality name using the path directly. I think we usually want to use the method for such cases.

This should only apply to unmapped requests - if a handler accepted it and returned 404 explicitly (e.g. a request with a path param for an Id that didn't exist in the db) it should still use the route.

**Comment by trask** [comment]
Closed by #2814, in particular: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2814/files#diff-8128e5f0fe92bd31fde0b66ee0dcaf4cd4770405849e774a7c6e5552006f39ceL43-L45
