### ISSUE TITLE
Question:How to set the version number of the Java agent artifact package built from the source code

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java-instrumentation#2362]
I have updated the code to the latest version, but the version number of the package built from the source code is still the previous version, such as 0.15, but now it should be 0.18. I haven't found the configuration place. Where is the version number determined?

**Comment by trask** [comment]
hey @tydhot, the version is picked up dynamically based on the latest tag, try `git fetch upstream --tags` and see if that helps

**Comment by tydhot** [comment]
@trask I understand it, thanks a lot!
