### ISSUE TITLE
Log4j instrumentation hijacks the user's logger

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-instrumentation#2403]
**Describe the bug**

The users logger does not function correctly when the log4j instrumentation is in place.  Adding `-Dotel.instrumentation.log4j.enabled=false` JVM arg to disable the instrumentation allows the users log4j logger to operate again...but breaks any chance of using MDC.

**Steps to reproduce**
Add an application dependency on log4j-core 2.13.2.  Build a method like this:

```
    @WithSpan("so-many-socks")
    private void doSomething() {
        Span span = Span.current();
        span.setAttribute("foo", "bar");
        logger.info("This is a test");
    }
```

**What did you expect to see?**
The `This is a test` string should be logged.  In my case, I was logging to both a file and the console.

**What did you see instead?**
The message is not logged, neither to the file nor to the console.

**What version are you using?**
Tried with latest (0.17.0) but also tried with 0.14.0 (same results).

**Environment**
Compiler: n/a (downloaded the agent from github)
OS: OSX
Runtime (if different from JDK above): adopt openjdk 11

**Comment by anuraaga** [comment]
Thanks @breedx-splk - I was able to reproduce this, and incidentally it doesn't not repro on 2.13.3. Will see if there's a way to work around it in our instrumentation or we should attempt to muzzle up to that version.

**Comment by anuraaga** [comment]
Oh - yeah it seems to be just a flatout bug - looking at the code it seems to at least affect `AsyncLogger`. But this is weird since I could get it to crash on my smoke test which is just a normal logger seemingly similar to the javaagent test which should have been using 2.13.2 this entire time. Hrm

**Comment by anuraaga** [comment]
@breedx-splk can you share your log4j2.xml by the way? I still can't figure out why the integration test doesn't trigger it, perhaps a log4j2 can provide a hint on why there'd be a difference.

**Comment by anuraaga** [comment]
Geez - log4j disables an optimized path, which had the bug, when it finds servlet on the classpath

https://github.com/apache/logging-log4j2/blob/913e87d7747aa8d90b7bd3236c4dca2e3307336a/log4j-api/src/main/java/org/apache/logging/log4j/util/Constants.java#L40

Out test classpath has jetty on the classpath, hence the integration tests didn't hit this. So glad log4j was on grpc and not spring boot vs the other way around or would have never repro'd...

**Comment by breedx-splk** [comment]
> @breedx-splk can you share your log4j2.xml by the way? I still can't figure out why the integration test doesn't trigger it, perhaps a log4j2 can provide a hint on why there'd be a difference. Don't want to add smoke tests for every log4j version 😅

Oh sure.  I was using `log4j2.properties` that was configured to log the MDC format to both rolling files and to the console.

```
status = error
dest = err
name = PropertiesConfig

property.filename = build/testapp.log

filter.threshold.type = ThresholdFilter
filter.threshold.level = debug

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} - %logger{36} - trace_id=%X{trace_id} span_id=%X{span_id} trace_flags=%X{trace_flags} - %msg %n
#appender.console.filter.threshold.type = ThresholdFilter
#appender.console.filter.threshold.level = debug

appender.rolling.type = RollingFile
appender.rolling.name = RollingFile
appender.rolling.fileName = ${filename}
appender.rolling.filePattern = build/testapp-%d{MM-dd-yy-HH-mm-ss}-%i.log.gz
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} - %logger{36} - trace_id=%X{trace_id} span_id=%X{span_id} trace_flags=%X{trace_flags} - %msg %n
appender.rolling.policies.type = Policies
appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling.policies.time.interval = 200
appender.rolling.policies.time.modulate = true
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size=100MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 5

logger.rolling.name = com.splunk.testapp
logger.rolling.level = debug
logger.rolling.additivity = true
logger.rolling.appenderRef.rolling.ref = RollingFile

rootLogger.level = debug
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT
```

Thanks for looking into it!!
