### ISSUE TITLE
why the opentelemetry-javaagent-all.jar not published in maven central

### ISSUE THREAD

**Issue by onespacer** [open-telemetry/opentelemetry-java-instrumentation#2404]
^^ as topic says, why could the jar opentelemetry-javaagent-all.jar not found in maven central? Is there a way to add the agent jar as a dependency in the project?

**Comment by anuraaga** [comment]
Hi @onespacer - the JAR is available at Maven Central here

https://repo1.maven.org/maven2/io/opentelemetry/javaagent/opentelemetry-javaagent/0.17.0/

Does it not work for you?
