### ISSUE TITLE
AWS SDK V1 instrumentation doesn't apply if SQS isn't on the classpath

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2408]
AWS SDK v1 is highly modular so it's common for users to only have a subset of the services on the classpath. Unfortunately, muzzle currently blocks the whole instrumentation

```
[opentelemetry.auto.trace 2021-02-25 08:03:29:958 +0000] [main] WARN muzzleMatcher - Instrumentation skipped, mismatched references were found: aws-sdk -- io.opentelemetry.javaagent.instrumentation.awssdk.v1_11.AwsSdkInstrumentationModule on org.springframework.boot.loader.LaunchedURLClassLoader@70d63e05
[opentelemetry.auto.trace 2021-02-25 08:03:29:959 +0000] [main] WARN muzzleMatcher - -- io.opentelemetry.javaagent.instrumentation.awssdk.v1_11.TracingRequestHandler:86 Missing class com.amazonaws.services.sqs.model.ReceiveMessageResult
[opentelemetry.auto.trace 2021-02-25 08:03:29:959 +0000] [main] WARN muzzleMatcher - -- io.opentelemetry.javaagent.instrumentation.awssdk.v1_11.TracingRequestHandler:51 Missing class com.amazonaws.services.sqs.model.SendMessageRequest
[opentelemetry.auto.trace 2021-02-25 08:03:29:959 +0000] [main] WARN muzzleMatcher - -- io.opentelemetry.javaagent.instrumentation.awssdk.v1_11.TracingRequestHandler:57 Missing class com.amazonaws.services.sqs.model.ReceiveMessageRequest
[opentelemetry.auto.trace 2021-02-25 08:03:29:959 +0000] [main] WARN muzzleMatcher - -- io.opentelemetry.javaagent.instrumentation.awssdk.v1_11.TracingRequestHandler:88 Missing class com.amazonaws.services.sqs.model.Message
```

I think someone might have suggested we have separate instrumentation module for SQS and I incorrectly thought it'd be ok to have it together 😅

**Comment by anuraaga** [comment]
Though I wonder why `muzzle` task didn't fail, muzzle is only include `-core`.

**Comment by kubawach** [comment]
Yeah, my initial proposal was to have a separate module (https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2093/files). Second proposal was to access SQS code in a dynamic way (https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2114#discussion_r564472190) but @mateuszrzeszutek figured out that the required dependency (SQS sdk) is already there. So the question is - why the muzzle fails, but only in runtime? :D

**Comment by anuraaga** [comment]
Ah - yeah I guess `since we aim to instrument the latter one ` isn't so true, we aim to instrument usage of AWS SDK Java, even if users depend on core + services rather than full thing.

Is it easy to restore the dynamic code?

Also, we should go ahead and split up test-sets for each type of service I think, or at least have just one test set dedicated to a simpler classpath, so we would have failed a unit test with this issue. Though it's not quite as important if we understand why muzzle didn't fail at compile time here.

**Comment by mateuszrzeszutek** [comment]
> So the question is - why the muzzle fails, but only in runtime? :D

This might provide the answer for that: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/buildSrc/src/main/groovy/MuzzlePlugin.groovy#L181

`MuzzlePlugin` takes everything that's available as compile/runtime dependency to run the muzzle checks.

> Ah - yeah I guess `since we aim to instrument the latter one` isn't so true, we aim to instrument usage of AWS SDK Java, even if users depend on core + services rather than full thing.

I've somehow missed the `-core` suffix 🤦‍♂️ 😅

**Comment by kubawach** [comment]
> 
> Is it easy to restore the dynamic code?
> 
Yep, quite easy (esp that we still have the original code ;) )

**Comment by anuraaga** [comment]
@kubawach I started with getting the test to fail here

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2421

Do you have the code you used for the dynamic dispatch? I couldn't find it in the PR (note to all, avoid force-push as much as possible :D) so hoping you have it locally for easy insertion.

**Comment by kubawach** [comment]
@anuraaga unfortunately I have not, besides the excerpt from the review: ```    Method withAttributeNames = request.getClass().getMethod("withAttributeNames", String[].class);
    MethodHandles.publicLookup()
        .unreflect(withAttributeNames)
        .invokeWithArguments(request, attribute);
```
After the discussion in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2114 I deemed dynamic approach a dead end, thus force push of "the proper way".

**Comment by trask** [comment]
we always squash merge to the main branch, so no need to clean up commit history in PRs 👍
