### ISSUE TITLE
Manual Instrumentation with javaagent jar can not use

### ISSUE THREAD

**Issue by alokmajumder** [open-telemetry/opentelemetry-java-instrumentation#2410]
You can not use javaagent jar along with manual instrumentation to change parameter like endpoint. I was trying to change the endpoint which i achieved by following code:

Cause: Using manual instrumentation along with javaagent to point to collector endpoint.
Solution: javaagent jar can not be used to pass runtime parameters when you are doing manual instrumentation.

Code snippet:

static OpenTelemetry initOpenTelemetry() {
OtlpGrpcSpanExporter spanExporter =
OtlpGrpcSpanExporter.builder().setEndpoint("http://A.B.C.D:55680").setTimeout(2, TimeUnit.SECONDS).build();
BatchSpanProcessor spanProcessor =
BatchSpanProcessor.builder(spanExporter)
.setScheduleDelay(100, TimeUnit.MILLISECONDS)
.build();

SdkTracerProvider tracerProvider =
        SdkTracerProvider.builder()
                .addSpanProcessor(spanProcessor)
                .setResource(Resource.getDefault())
                .build();
OpenTelemetrySdk openTelemetrySdk =
        OpenTelemetrySdk.builder().setTracerProvider(tracerProvider).buildAndRegisterGlobal();

Runtime.getRuntime().addShutdownHook(new Thread(tracerProvider::close));

return openTelemetrySdk;

**Comment by anuraaga** [comment]
Hi @alokmajumder - is your goal to manually instrument code, for example by calling `Tracer.spanBuilder().startSpan()`? In that case, you can use the agent's globally provided API - `GlobalOpenTelemetry.getTracer("app").spanBuilder()`.

If you actually want to configure the agent programatically, we do not have plans to support this to ensure the safety of the agent with respect to different applications. Is there anything in the configuration that doesn't work for you?

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/agent-config.md

**Comment by trask** [comment]
Closing, but please let us know if you are still having this issue and we will re-open.
