### ISSUE TITLE
Allow environment variables to override predefined agent configuration

### ISSUE THREAD

**Issue by cmuelhau** [open-telemetry/opentelemetry-java-instrumentation#2422]
*Background*
When packaging JVM applications in docker images, it would be very convenient to be able to preconfigure the opentelemetry-agent and then allow overrides via environment variables. E.g. entrypoint could like this:
`java -javaagent:/opentelemetry-javaagent-all.jar -Dotel.metrics.exporter=none -Dotel.traces.exporter=none`
and in the respective environment one could set configs as needed:
`OTEL_TRACES_EXPORTER=logging`

**Describe the solution you'd like**
Let environment variables have precedence over system properties (which I realize this has been discussed before)
*OR*
Allow preconfiguration via parameters for the `javaagent`, which then can be overridden via system properties and env variables, where system properties still have precedence. (On a side note, Spring Boot external configs allow this pattern by having lesser precedence options, i.e. the application.properties)

**Describe alternatives you've considered**
Our current solution is to attach the agent via entrypoint (without system properties) and using Dockerfile's `ENV` instruction to preconfigure via env variables. This though seems like a violation of the least astonishment principle.

**Comment by iNikem** [comment]
I am against changing the precedence order. But using javaagent parameters certainly seems sensible. We should consider this.

**Comment by mateuszrzeszutek** [comment]
We still support passing a .properties configuration file via the `otel.javaagent.config` system property (or `OTEL_JAVAAGENT_CONFIG` env var) which has lower precedence than both env var and system property configuration. You can try putting your configuration in a file

```properties
otel.metrics.exporter = none
otel.traces.exporter = none
```

and passing path to it as system property: `-Dotel.javaagent.config=/path/to/config.properties`.

(On a side note: we should document this...)

**Comment by cmuelhau** [comment]
> We still support passing a .properties configuration file via the `otel.javaagent.config` system property (or `OTEL_JAVAAGENT_CONFIG` env var) which has lower precedence than both env var and system property configuration. You can try putting your configuration in a file
> 
> ```ini
> otel.metrics.exporter = none
> otel.traces.exporter = none
> ```
> 
> and passing path to it as system property: `-Dotel.javaagent.config=/path/to/config.properties`.
> 
> (On a side note: we should document this...)

Thanks for your suggestions, the configuration file sounds like a decent solution to me.
