### ISSUE TITLE
Review https://opentelemetry.io/docs/java/

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#2428]
Java documentation on OpenTelemetry public site is outdated. It should be reviewed and updated.

**Comment by mateuszrzeszutek** [comment]
Also, once we update it we should make sure that it won't go out of sync with documentation in this repo. Should we require adding a link to PR in the opentelemetry.io repo for all documentation PRs?

**Comment by trask** [comment]
My personal preference would be for us to maintain all user facing docs in the opentelemetry.io repo, and only there.

**Comment by trask** [comment]
Closing, the Java documentation on opentelemetry.io has been reviewed and updated.
