### ISSUE TITLE
Gradle is not re-running some tests that it should

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#2432]
In PR #2425, the gradle build passed, but we found out later (in #2431) that there were some tests (`hibernate-3.3`, `hibernate-4.0`, `hibernate-4.3`, `spring-data-1.8`, `vertx-reactive-3.5`, and `scala-executors`) which were broken by the change, but which gradle did not re-run in that PR.

**Comment by trask** [comment]
Another example, in #2488, the gradle build passed, but it didn't run `apache-camel-2.20`, which we discovered later were broken by that PR: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2486/commits/25d764416cacdd795c929f34e3571786354bc68e

**Comment by anuraaga** [comment]
Probably fixed by #2504
