### ISSUE TITLE
MQ Boundaries are not crossed, Redis call and MQ consumer not auto instrumented 

### ISSUE THREAD

**Issue by mnadeem** [open-telemetry/opentelemetry-java-instrumentation#2436]
**Describe the bug**

**Three things**

1) MQ (Rabbit MQ) calls are not crossing the component boundary as as in rest calls (Trace Ids are getting changed)

![image](https://user-images.githubusercontent.com/476145/109412537-95e57980-79ce-11eb-8248-a5418ff961d9.png)

2) Redis calls are not instrumented

![image](https://user-images.githubusercontent.com/476145/109413368-07272b80-79d3-11eb-86d4-fb028bd571c4.png)

3) RabbitMQ Consumer is not auto instrumented, I had to use  `@WithSpan`

![image](https://user-images.githubusercontent.com/476145/109414113-29bb4380-79d7-11eb-9312-82486f6066f4.png)

**Steps to reproduce**

https://github.com/mnadeem/boot-opentelemetry-tempo ==> look for **complex** branches, same behavior is across the branches.

````
mvn clean package docker:build
````
and then

````
docker-compose up
````

![image](https://user-images.githubusercontent.com/476145/109413416-481f4000-79d3-11eb-906c-bf66a6e70259.png)

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc) : 0.15.0, 0.16.0 and 0.17.0

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6") : Oracle jdk 8
OS: (e.g., "Ubuntu 20.04") : Widows 10
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): OS is same as that of compiled one, Widows 10

**Additional context**

**Comment by mnadeem** [comment]
Note: Redis is instrumented with Lettuce 5 and not with 6

**Comment by mnadeem** [comment]
For rabbitMQ consumer I doing the following way as a work around for the time being

https://github.com/mnadeem/boot-opentelemetry-tempo/blob/0.15.0_complex/boot-otel-tempo-mq-consumer/src/main/java/io/opentelemetry/example/flight/messaging/FlightMQConsumer.java#L38

**Comment by mnadeem** [comment]
I see that,  RabbitMQ Client , 2.7+ is supported

And I am using 5.9

![image](https://user-images.githubusercontent.com/476145/109539600-8443c500-7ae7-11eb-8ec1-ba48778dc41c.png)

From RabbitMQ producer everything is okay, span created, parent tracer passed.

Consumer receiving it as well.

![image](https://user-images.githubusercontent.com/476145/109539742-ab01fb80-7ae7-11eb-8280-5ebd0b99e76a.png)

However at the consumer side, parent context is not considered and new span is not created.

**Comment by mateuszrzeszutek** [comment]
Hi @mnadeem ,
Can you create a separate enhancement issue for implementing Lettuce 6 instrumentation?

**Comment by mnadeem** [comment]
@mateuszrzeszutek 

In this ticket we are talking about rabbitmq and not redis

not sure if I am missing anything

**Comment by mateuszrzeszutek** [comment]
Oh, you mentioned that "Redis calls are not instrumented" so I thought that you wanted to have Lettuce 6 instrumented as well

**Comment by mnadeem** [comment]
Apologies, missed it

**Comment by mnadeem** [comment]
Created a separate enhancement request for Lettuce, 

What needs to be done for RabbitMQ ?

**Comment by mateuszrzeszutek** [comment]
It needs to be fixed -- this most certainly looks like a bug. Whatever spring uses for `@RabbitListerer`-annotated methods is probably not instrumented.
