### ISSUE TITLE
Allow agent to be extended with custom propagation

### ISSUE THREAD

**Issue by nestorsokil** [open-telemetry/opentelemetry-java-instrumentation#2437]
**Is your feature request related to a problem? Please describe.**
https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/2429

**Describe the solution you'd like**
There should be a way to supply custom propagator either through opentelemetry-api or just putting a jar on classpath.

**Describe alternatives you've considered**
For me there is an alternative, but it's too specific to the use case.

**Comment by trask** [comment]
this use case should be possible once #2442 is implemented

**Comment by trask** [comment]
#2442 is done, please see https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension#introduction
