### ISSUE TITLE
@WithSpan and customTextMapPropagator

### ISSUE THREAD

**Issue by mnadeem** [open-telemetry/opentelemetry-java-instrumentation#2438]
**Describe the bug**

This is related to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2436 

@WithSpan could be more robust if there is a way to specify custom Propagator to extract parent trace.

![image](https://user-images.githubusercontent.com/476145/109419945-fb992c00-79f5-11eb-85be-a38d1c84199f.png)

Even though there is parent trace a new trace is created.

![image](https://user-images.githubusercontent.com/476145/109419972-1cfa1800-79f6-11eb-990e-e0165de342f6.png)

This limits the use of @WithSpan, if a library is not instrumented. And we would be forced to create span the hard way.

**Steps to reproduce**
use this project : https://github.com/mnadeem/boot-opentelemetry-tempo

**What did you expect to see?**

A easy and custom way for @WithSpan  to extract parent trace, if a library is not instrumented.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by trask** [comment]
cc @zeitlinger @jack-berg related to SIG discussion about https://github.com/open-telemetry/opentelemetry-java-contrib/pull/759 and a convenience API for interacting with propagators

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
