### ISSUE TITLE
Consolidate otel.exporter.jar and otel.initializer.jar into single feature otel.javaagent.extensions?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#2442]
`otel.javaagent.extensions` could be a single jar file, a list of jar files, or a folder with jar files

It would behave same as `otel.initializer.jar` where those jar files just get added to `AgentClassLoader` (or even better follow @jsuereth's proposal of loading them in a mostly-isolated child of `AgentClassLoader`).

And all of the normal autoconfigure SPIs can be used to add exporters, span processors, propagators.

I like the runtime shading of the existing `ExporterClassLoader`, but would probably vote to do away with it due to startup overhead, and make sure we document how to shade properly using both gradle and maven.

**Comment by trask** [comment]
Adding note here about benefits of runtime shading: https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/2570#discussioncomment-492019

**Comment by trask** [comment]
Also note that as part of this we will drop `io.opentelemetry.javaagent.tooling.exporter.SpanExporterFactory`, and only support `io.opentelemetry.sdk.autoconfigure.spi.ConfigurableSpanExporterProvider` from `io.opentelemetry:opentelemetry-sdk-extension-autoconfigure`

**Comment by tobias-** [comment]
Nit: They're `otel.javaagent.experimental.exporter.jar` and `otel.javaagent.experimental.initializer.jar`

**Comment by sumitm-iiit** [comment]
@trask : I was trying out "otel.javaagent.experimental.initializer.jar" system property. It seems to work when i provide the path of the exact jar file. But when i provide the path of a folder that contains multiple jars, it does not seem to load those jars. Is that something expected as based on your description above it seems its expected to work with folders containing multiple jars as well.

**Comment by trask** [comment]
> when i provide the path of a folder that contains multiple jars, it does not seem to load those jars

ya, this has not been implemented yet, but is planned

**Comment by sumitm-iiit** [comment]
@trask : Any idea by when it would be implemented.

**Comment by iNikem** [comment]
> @trask : Any idea by when it would be implemented.

During the June

**Comment by trask** [comment]
this is done! please see https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension#introduction

**Comment by sumitm-iiit** [comment]
@trask : Thanks for notifying.
