### ISSUE TITLE
Rename configuration properties otel.instrumentation.* to match package naming convention

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#2444]
The package naming in this repo is all good (don't want you to worry that I'm opening that can of worms 😄):
* `io.opentelemetry.javaagent` - javaagent
* `io.opentelemetry.javaagent.instrumentation` - javaagent instrumentation
* `io.opentelemetry.instrumentation` - library instrumentation

Should we follow similar naming for configuration properties:
* `otel.javaagent.*` - javaagent properties
* `otel.javaagent.instrumentation.*` - javaagent instrumentation properties
* `otel.instrumentation.*` - library instrumentation properties (if we even need any? e.g. library instrumentation could possibly be programmatic config only)

The things that would need to be renamed if we want to make this change are:

* `otel.instrumentation.default-enabled` --> `otel.javaagent.instrumentation.default-enabled`
* `otel.instrumentation.[id].enabled` --> `otel.javaagent.instrumentation.[id].enabled`
* `otel.instrumentation.[id].*` --> `otel.javaagent.instrumentation.[id].*` (instrumentation-specific properties)
* `otel.instrumentation.db-statement-sanitizer.enabled` --> `otel.javaagent.db-statement-sanitizer.enabled` (or maybe `otel.javaagent.instrumentation.db-statement-sanitizer.enabled`, but that looks like `otel.javaagent.instrumentation.[id].enabled`)

**Comment by anuraaga** [comment]
> otel.instrumentation.* - library instrumentation properties (if we even need any? e.g. library instrumentation could possibly be programmatic config only)

Think long term we don't want any properties read in library instrumentation, programmatic makes sense. In which case the current names seem ok.

**Comment by mateuszrzeszutek** [comment]
> `otel.instrumentation.db-statement-sanitizer.enabled` --> `otel.javaagent.db-statement-sanitizer.enabled` (or maybe `otel.javaagent.instrumentation.db-statement-sanitizer.enabled`, but that looks like `otel.javaagent.instrumentation.[id].enabled`)

Hmm, don't we want to move all the sanitization classes to instrumentation-api?

Anyway, I think that I like the current names: you don't have to think if it's javaagent or library instrumentation, the naming is hierarchical and logical: otel > instrumentation > library > enabled

**Comment by trask** [comment]
I think we have agreement now on the following:

* `otel.javaagent.*` - javaagent properties
* `otel.instrumentation.common.*` - common properties that are used across multiple instrumentations, e.g. `otel.instrumentation.common.peer-service-mapping` and `otel.instrumentation.common.db-statement-sanitizer.enabled`
* `otel.instrumentation.[id].*` - instrumentation specific properties
* library instrumentation will only support programmatic configuration (so no property names involved)

**Comment by trask** [comment]
Closed by #2457 and #2486
