### ISSUE TITLE
Does tracer name in spring-boot-autoconfigure need to be configurable?

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#2469]
`SpringWebMvcServerTracer` is one of the few classes left that still use the deprecated `BaseTracer(Tracer)` constructor. It turns out that it's used by the spring-boot-autoconfigure library instrumentation that actually constructs a `Tracer` with a custom instrumentation name and uses the constructor to pass it.
Is this custom instrumentation name functionality necessary? Can we remove it and pass `OpenTelemetry` instead of a `Tracer`?

**Comment by trask** [comment]
👍 on removing it and passing `OpenTelemetry`
