### ISSUE TITLE
closeScopeAndEndSpan execute by 'hasNext()'

### ISSUE THREAD

**Issue by ReiZ-X** [open-telemetry/opentelemetry-java-instrumentation#2475]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/9f3dfdbc5147979ff152b1c1e75e1263c31ea11d/instrumentation/kafka-clients-0.11/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/kafkaclients/TracingIterator.java#L38

where loop iterator, only want process N items(iterator has more than N items), closeScopeAndEndSpan will not execute for the last item

**Comment by ReiZ-X** [comment]
'break' offen appear in loop. also lead to unclosed span.

**Comment by trask** [comment]
Consolidating into #1947
