### ISSUE TITLE
Fix spring-boot-autoconfigure configuration and rename properties

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#2481]
Current spring-boot-autoconfigure configuration naming scheme is very different from what we use in SDK/javaagent: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md#configuration-properties

Everything starts with `opentelemetry.trace.*`, some properties (like `opentelemetry.trace.exporters.jaeger.servicename`) do not exist anymore, there's even no way to configure the Resource.

We should use the same property names that we use in SDK or javaagent, e.g.:
* `otel.traces.*` for tracer config;
* `otel.instrumentation.<name>.enabled` to enable manual instrumentations (`@WithSpan` advice, HTTP clients, etc);
* And add `otel.resource.attributes` support so that `service.name` is properly set.

**Comment by trask** [comment]
there's also been some discussion in the past of transferring ownership of spring boot autoconfiguration to the spring cloud sleuth team / repo

**Comment by zeitlinger** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/10292
