### ISSUE TITLE
is there a reason for support for multiple exporters removed?

### ISSUE THREAD

**Issue by onespacer** [open-telemetry/opentelemetry-java-instrumentation#2484]
^^ as title says. How do I configure multiple exporters jar?

**Comment by trask** [comment]
hi @onespacer! can you describe your use case, and whether using the otel collector is an option for you?

**Comment by onespacer** [comment]
I want to export traces to couple of customized backends ex. kafka and splunk. I have created custom exporter jars for those. Couldn't see an option to export them together.

**Comment by trask** [comment]
makes sense, stay tuned for #2442 (or if you want to go exploring undocumented stuff, check out the current `otel.initializer.jar`)

**Comment by trask** [comment]
hey @onespacer, `otel.initializer.jar` allows you to add stuff into the agent class loader, so you can add your own [SdkTracerProviderConfigurer](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/SdkTracerProviderConfigurer.java), and (as many) span processors to the `SdkTracerProviderBuilder`

**Comment by trask** [comment]
this is possible now using the new extension mechanism, please see https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension, and let us know if you run into any issues
