### ISSUE TITLE
Quarkus Netty broken traces on Kubernetes

### ISSUE THREAD

**Issue by previousdeveloper** [open-telemetry/opentelemetry-java-instrumentation#2493]
**Describe the bug**
 I am working on integrating Open Telemetry to an existing microservices architecture with nested libraries such as Kafka, couchbase, netty.  There are some problems with tracing data. For one HTTP request, netty creates separated two traces. I think that is a context pass problem. 

**What did you expect to see?**
For one request one trace.

**What did you see instead?**
For one request two separate traces.

**What version are you using?**
  Opentelemetry agent version `v0.17.0`

**Environment**
OS: Linux 4.4.0-197 
Container platform: Kubernetes
Java version: 1.8.0_265-b01

**Additional context**
![alt text](https://i.ibb.co/R3mbnr2/Screen-Shot-2021-03-04-at-14-36-02.png)
![alt text](https://i.ibb.co/0QQr9T4/Screen-Shot-2021-03-04-at-14-36-12.png) 
![alt text](https://i.ibb.co/BnhPpDh/Screen-Shot-2021-03-04-at-14-36-35.png)

**Comment by previousdeveloper** [comment]
same with agent 1.0.0 version fyi

**Comment by iNikem** [comment]
@previousdeveloper Do you have a small example application that demonstrate these problems?
