### ISSUE TITLE
AWS-SDK: Re-use of Request object leads to AWSTraceHeader repeatedly added as attribute

### ISSUE THREAD

**Issue by jamal** [open-telemetry/opentelemetry-java-instrumentation#2495]
**Describe the bug**
Re-using the `ReceiveMessageRequest` object leads to the `AWSTraceHeader` attribute being added multiple times. Doing this in a loop will eventually cause the request to fail with `413 Request Entity Too Large`. 

I was not sure if this should be reported as a bug, since this is an odd pattern. But, it is something we had in legacy code. I realized, if it can happen to us then it may be something that affects someone else in the future too.

**Steps to reproduce**
Example showing the issue:
```
ReceiveMessageRequest req = new ReceiveMessageRequest();
req.setQueueUrl(queueUrl);

while (true)
{
    ReceiveMessageResult receiveResult = sqsClient.receiveMessage(receiveMessageRequest);
}
```

**What version are you using?**
v0.17.0

Example log showing the issue:
```
DEBUG com.amazonaws.request - Sending Request: POST https://sqs.us-east-1.amazonaws.com /154463222472/queue-name Parameters: ({"Action":["ReceiveMessage"],"Version":["2012-11-05"],"AttributeName.1":["AWSTraceHeader"],"AttributeName.2":["AWSTraceHeader"],"AttributeName.3":["AWSTraceHeader"],"AttributeName.4":["AWSTraceHeader"],"AttributeName.5":["AWSTraceHeader"],"AttributeName.6":["AWSTraceHeader"],"AttributeName.7":["AWSTraceHeader"],"AttributeName.8":["AWSTraceHeader"],"AttributeName.9":["AWSTraceHeader"],"AttributeName.10":["AWSTraceHeader"],"AttributeName.11":["AWSTraceHeader"],"AttributeName.12":["AWSTraceHeader"],"AttributeName.13":["AWSTraceHeader"],"AttributeName.14":["AWSTraceHeader"], ...
```

**Comment by anuraaga** [comment]
Seems like a bug to me :) Sent #2509 to fix
