### ISSUE TITLE
Request for OTel support in AWS Java SDK v1.x 

### ISSUE THREAD

**Issue by zaheershaik** [open-telemetry/opentelemetry-java-instrumentation#2502]
We are trying to manually instrument our API calls to DyanamoDB and SQS, but noticed that there is no  OTel support for AWS Java SDK 1.x version, unlike [2.x versions like this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/aws-sdk/aws-sdk-2.2/library). It is not an easy task to migrate all the older versions of DDB calls from 1.x to 2.x version. It'd really help to have support for this older version of SDK.

**Comment by anuraaga** [comment]
Hi @zaheershaik - this is definitely on our radar, I've started to prepare for it with #2508
