### ISSUE TITLE
why not support java nio

### ISSUE THREAD

**Issue by LUAgam** [open-telemetry/opentelemetry-java-instrumentation#2505]
i want to use open-telemetry on a system that implements network switching based on java nio? Is it supported now? If you don’t support it, what are the feasible solutions?

**Comment by trask** [comment]
Closing as duplicate of #1311.

@LUAgam [manual instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/manual-instrumentation.md) is a decent option for now
