### ISSUE TITLE
smoke-tests sometimes timeout on CI

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2506]
For example in this build

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2477/checks?check_run_id=2036537351
https://scans.gradle.com/s/2aerhndneiwwy

```
Execution failed for task ':smoke-tests:test'.
> Timeout has been exceeded
```

I think we need to either raise the timeout or parallelize the smoke tests.

**Comment by iNikem** [comment]
I believe it is fixed by #2622
