### ISSUE TITLE
Supporting r2dbc 

### ISSUE THREAD

**Issue by Volodymyr-Maiboroda-Imprivata** [open-telemetry/opentelemetry-java-instrumentation#2515]
It's good to have OpenTelemetry auto-instrumentation for r2dbc to be able to use it for a fully reactive stack.

**Comment by darcydai** [comment]
I am working on this.  I will open a pull request recently  @trask

**Comment by mp911de** [comment]
FWIW, https://github.com/r2dbc/r2dbc-proxy contains a proper infrastructure to intercept R2DBC calls.

**Comment by aniljaiswal** [comment]
Any progress on this?

**Comment by 62mkv** [comment]
Hi, should this be re-opened? In particular, suggested way to initialize the listener for Spring applications does not seem to work - `ConnectionFactoryInitializer` does not do anything to a `ConnectionFactory`. So, what the suggested sample [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/r2dbc-1.0/library#usage) does is just creating a Proxy and "dropping it". It's listeners are never activated. 

Is it possible to provide a working example of Spring Boot integration for R2DBC queries?

**Comment by 62mkv** [comment]
this is a configuration class that worked for me: 

```
@Configuration
public class TracingConfiguration {

    @Bean
    ConnectionFactory connectionFactory(R2dbcProperties properties) {
        var openTelemetry = GlobalOpenTelemetry.get();
        var factoryOptions = ConnectionFactoryOptions.parse(properties.getUrl())
                                                     .mutate()
                                                     .option(ConnectionFactoryOptions.USER, properties.getUsername())
                                                     .option(ConnectionFactoryOptions.PASSWORD, properties.getPassword())
                                                     .build();

        return wrapWithProxyFactory(openTelemetry, ConnectionFactories.get(factoryOptions), factoryOptions);
    }

    private ConnectionFactory wrapWithProxyFactory(OpenTelemetry openTelemetry, ConnectionFactory originalFactory, ConnectionFactoryOptions factoryOptions) {
        return R2dbcTelemetry
                   .create(openTelemetry)
                   .wrapConnectionFactory(originalFactory, factoryOptions);
    }
}
```

by the way, the provided listener only traces the query duration.. the "reference" implementation does much more, in particular, connection obtaining: https://github.com/ttddyy/r2dbc-proxy-examples/blob/master/listener-example/src/main/java/io/r2dbc/examples/TracingExecutionListener.java

**Comment by 62mkv** [comment]
opened an issue #8438
