### ISSUE TITLE
Instrumentation for Couchbase Client 3.x

### ISSUE THREAD

**Issue by previousdeveloper** [open-telemetry/opentelemetry-java-instrumentation#2520]
Opentelemetry agent works with Couchbase client(2.x) well. Do you have a plan to support 3.x client?

Thanks

**Comment by anuraaga** [comment]
Hi @previousdeveloper - it looks like couchbase 3.0 includes OpenTelemetry integration so it should be fairly simple to add it to the agent. We can probably get it in relatively soon.

**Comment by sachinpatilm** [comment]
Requires support for couchbase client version 3.1+
for [Database Client Spans] [Database Client Metrics]

(https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md), (https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-metrics.md)
