### ISSUE TITLE
Span.currentSpan() returns a span whose Trace's id is 0 instead of the actual current trace's id

### ISSUE THREAD

**Issue by Johnny850807** [open-telemetry/opentelemetry-java-instrumentation#2543]
**Describe the bug**

I am using Open-Telemetry with Spring boot to perform **auto-instrumentation with some manual Spans**.

I expect the auto-instrumentation will help me start and end up a Span around the method.
But then I found `Span.current()` returns a span whose trace's id is 00000000000000000000000000000000, instead of the one being traced.

From the log, it prints:
`2021-03-10 08:03:26 - com.example.demo.UserController - Current span's trace id: 00000000000000000000000000000000. traceID=fbf79fa9ab94d2383f07ae4a3f5b7f6e`

The log is correctly injected with the correct `traceID` but the one from `Span.current()` doesn't hold the same trace.

My java code is as follows:
```java
@PostMapping("/signUp")
public User signUp(@RequestBody User user) {
    Span span = Span.current();
    log.info("Current span's trace id: {}.", span.getSpanContext().getTraceId());
    return signUp.execute(user);
}
```

What's wrong? What did I miss?  Thanks.

### Furthermore
`@WithSpan` doesn't work either

With the following code. The Sign-In flow should be traced as `UserController -> SignIn -> CrudRepository`
```java
@Slf4j
@Component
@AllArgsConstructor
public class SignIn {
    private final UserRepository userRepository;
    @WithSpan
    public User execute(String email, String password) {
        return userRepository.findFirstByEmailAndPassword(email, password)
                .orElseThrow();
    }
}
```
But it turns out to be:
![image](https://user-images.githubusercontent.com/23109467/110600116-8b8d6180-81be-11eb-9598-970b91e0f2ac.png)

The `SignUp.execute` method is still not included in the trace.

**Steps to reproduce**
You can reproduce the bug from [this simple project setup](https://github.com/Johnny850807/Spring-Boot-Minimum-Effort-Observability-with-Open-Telemetry/tree/reproduce-bug-span-current)

With the commands to run the program:
```
./mvnw package -DskipTests
docker-compose up
```
Then
`curl -X POST -H 'Content-Type: application/json' -d '{"name":"name","email": "email", "password":"p"}' http://localhost:8080/api/users/signUp`

**What did you expect to see?**

I expect the log will print `2021-03-10 08:03:26 - com.example.demo.UserController - Current span's trace id: fbf79fa9ab94d2383f07ae4a3f5b7f6e. traceID=fbf79fa9ab94d2383f07ae4a3f5b7f6e`

**What did you see instead?**

`2021-03-10 08:03:26 - com.example.demo.UserController - Current span's trace id: 00000000000000000000000000000000. traceID=fbf79fa9ab94d2383f07ae4a3f5b7f6e`

**What version are you using?**

opentelemetry-api: 1.0.0
opentelemetry-extension-annotations: 1.0.0
opentelemetry-javaagent:  0.14.0
org.springframework.boot: 2.4.3

**Environment**

Compiler/Runtime: AdoptOpenJDK 11.0.9
OS: macOS 10.15.5

**Comment by Johnny850807** [comment]
> Hi @Johnny850807 - agent 0.14.0 is only compatible with API 0.14.0. Can you upgrade to the 1.0.0 agent?

I have upgraded to [1.0.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.0.0), then the log shows

`Current span's trace id: 9cd6540a942fe4b5389c1ce6fb586757. traceID= `
with the same code 
`log.info("Current span's trace id: {}.", span.getSpanContext().getTraceId());`

Now the Open-Telemetry API is compatible with the agent **but log injection failed**. 
The bug can be reproduced [here](https://github.com/Johnny850807/Spring-Boot-Minimum-Effort-Observability-with-Open-Telemetry/tree/reproduce-bug-span-current).

**Comment by trask** [comment]
hey @Johnny850807, we changed the MDC attribute name recently, can you try with `%X{trace_id}`?

**Comment by Johnny850807** [comment]
@trask Now that's it! ` Current span's trace id: 74ce346c649bd24f2164cecd9d6156e0. traceID=74ce346c649bd24f2164cecd9d6156e0`

Thanks.

**Comment by yatamraghu7** [comment]
Hi @trask 
This might be a old thread but what if we are using mvn dependency approach but not the agent approach.
We are also getting the same issue when we use  Span currentSpan = Span.current();
PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}}
Can you please tell us what can we change to achieve the same result here.
Thanks

**Comment by yatamraghu7** [comment]
@trask  we are using below opentelemetry bom
<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.opentelemetry.instrumentation</groupId>
				<artifactId>opentelemetry-instrumentation-bom</artifactId>
				<version>2.6.0</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
Thanks
