### ISSUE TITLE
Muzzle should fail at compile time if it fails at runtime

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2554]
Currently, muzzle may fail at runtime even if the compile time check succeeds, for example if instrumentation refers to plugin classes in the AWS SDK. This seems to be a bug in muzzle - the `muzzle` extension declaration only specifies `aws-core` as an artifact, but it seems to also take in instrumentation's `compileClasspath` and can pass some checks that might fail in production. I think we should respect the `muzzle` declaration only for checks, not using the compile classpath - if extra dependencies are needed, they can be added to the muzzle block too, it's how to have a more robust check.

**Comment by mateuszrzeszutek** [comment]
Adding compile deps to the classloader in MuzzlePlugin is definitely weird - why would you want to do that? Especially when there's even an `extraDependency` flag in the muzzle directive configuration, which seems *perfect* for including additional deps in the muzzle task classpath.

**Comment by jaydeluca** [comment]
is this still a problem or did #2599 address it?
