### ISSUE TITLE
:instrumentation:rocketmq-client-4.8:library:test is flaky

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#2586]
It sporadically fails during PRs and fails 2 times out of 4 when trying to run locally

**Comment by trask** [comment]
cc: @addname

**Comment by iNikem** [comment]
Some more problems with those tests:

- They never shutdown resources started in `BaseConf` and in `IntegrationTestBase`, such as broker, name server, producer and consumer
- They never clean up the files they created, `BaseConf.deleteTempDir()` is never called
- `RocketMqClientTest` uses deprecated methods. Is it expected? Should end-users do the same?

**Comment by addname** [comment]
My local run has been successful, let me solve this issue

**Comment by trask** [comment]
thx @addname!

if you are not able to repro locally, try reverting #2595 and open a PR against main branch in your own repo in order to trigger GitHub Actions CI (doing this in your own repo will allow you to re-run CI a couple of times if needed)

if you have trouble reproducing this way let us know!

**Comment by mateuszrzeszutek** [comment]
I've noticed that only the `test rocketmq produce and batch consume` test case fails randomly (most of the time): the consumer spans never appear. Maybe this'll be a hint for you.

**Comment by addname** [comment]
thanks @trask @mateuszrzeszutek 

Rocketmq client (producer/consumer) can only use hooks through `getDefaultMQProducerImpl()` and `getDefaultMQPushConsumerImpl()`. Rocketmq client marks `getDefaultMQProducerImpl()` and `getDefaultMQPushConsumerImpl()` as @Deprecated, but the current version does not provide alternative methods. If a later version provides a recommended method, I will update it.

The test class of rocketmq clinet uses hooks in the same way.
https://github.com/apache/rocketmq/blob/master/client/src/test/java/org/apache/rocketmq/client/producer/DefaultMQProducerTest.java
