### ISSUE TITLE
HttpHeadersInjectAdapter should use 'setHeader' instead of 'addHeader'?

### ISSUE THREAD

**Issue by lshangq** [open-telemetry/opentelemetry-java-instrumentation#2594]
**Describe the bug**
If reuse http request, traceparent header will be more and more when use apache-httpclient4.x and 5.x

![image](https://user-images.githubusercontent.com/2337707/111585962-15f74600-87fb-11eb-8e9c-1238eba7319f.png)

**What version are you using?**
v1.0.1

**Comment by iNikem** [comment]
@lshangq Can you please provide a demo or reproducible test case? It generally should be a bug in our instrumentation if we try to inject span context into an outgoing request more that once. But your case seems to differ. Would like to understand it more.
