### ISSUE TITLE
Jaeger Showing 2 Traces With Same MessageId 

### ISSUE THREAD

**Issue by carlyn12** [open-telemetry/opentelemetry-java-instrumentation#2598]
Describe the bug
I have two simple spring boot apps that communicate over jms and implement
opentelemetry auto tracing with jaeger. When sending the traces to my local jaeger instance, I see two different traces showing where one is correctly showing both spans end-to-end and the other appears to be a duplicate that has the same messageId as the consumer.

**UPDATE: this behavior is only occurring when I have Dotel.resource.attributes=service.name property set to the same thing in both the consumer and producer

To Reproduce

built both apps with maven
start jaeger-all-in-one docker container
run the applications with the following command:
-Dotel.metrics.exporter=none \
-Dotel.exporter.jaeger.endpoint="http://localhost:14250" \
-Dotel.resource.attributes=service.name="OTLJmsAuto" \
-Dotel.traces.sampler="always_on" \
-Dotel.instrumentation.jms.enabled=true \
-Dapplication.home=./ \
-Dapplication.name=producer \
-javaagent:./opentelemetry-javaagent-all.jar \
-jar ./target/producer-0.0.1-SNAPSHOT.jar
navigate to http://localhost:16686/search and see two different traces showing(see screenshots)
Expected behavior
Only the top trace should show which includes two spans(producer and consumer).
![Producer](https://user-images.githubusercontent.com/80895904/111659778-e25cf180-87e3-11eb-83b9-653c8a4b309a.png)
![Consumer](https://user-images.githubusercontent.com/80895904/111659779-e25cf180-87e3-11eb-99a9-83725600c082.png)
![Process](https://user-images.githubusercontent.com/80895904/111659781-e25cf180-87e3-11eb-86a4-80afb32c57bb.png)
![SearchPage](https://user-images.githubusercontent.com/80895904/111659783-e25cf180-87e3-11eb-9bc6-6a88b310c94d.png)
![Receive](https://user-images.githubusercontent.com/80895904/111659784-e25cf180-87e3-11eb-843e-b405771325f7.png)

Version (please complete the following information):

OS: Linux
Jaeger version: 1.22
What troubleshooting steps did you try?
Tried upgrading dependency versions as well as using the latest version of opentelemetry-javaagent-all.jar. Tried with debug mode.

**Comment by trask** [comment]
hi @carlyn12!

So, currently this is expected. There's a test that shows this same behavior that you describe:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jms-1.1/javaagent/src/jms2Test/groovy/SpringListenerJms2Test.groovy#L28-L36

We are not sure ourselves though what is the correct behavior here:

https://github.com/open-telemetry/opentelemetry-specification/issues/1085

**Comment by trask** [comment]
Closing, this is now configurable using 

```
-Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=false
```

to disable the receive span
