### ISSUE TITLE
Alternative to RepaintManager

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2638]
I've always been bugged by the Java applet type of thing that pops up during our build and finally found (at least one of ) the test that does it.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/executors/javaagent/src/test/groovy/ModuleInjectionTest.groovy#L20

Does anyone know of a lighter-weight class with the same module properties?

**Comment by mateuszrzeszutek** [comment]
🤯 

If it's just a module and a runnable we need, can't we create one in our test sources?

**Comment by laurit** [comment]
Running with`-Djava.awt.headless=true` seems to fix it. Could also try `System.setProperty("java.awt.headless", "true")` in the test class.

**Comment by trask** [comment]
@anuraaga is this closed by #2677?

**Comment by anuraaga** [comment]
I think I've seen a window popup since that change when running `./gradlew check` though could be misremembering. But since RepaintManager is fixed at least this issue is ok, will file again if I notice it again.
