### ISSUE TITLE
Fix Akka context propagation

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2639]
With strict context checking in place, I think we can finally dig into akka and fix context propagation. It's not trivial, likely because it seems Scala can suspend within `Runnable.run`, meaning we're not allowed to decorate scala runnables with context propagation. Currently it seems that propagation does rely on doing so though but we can probably figure something out.

This approach removes context leaks but also causes missing context sometimes. It is likely the PromiseCompletingRunnable that is most important out of these, but without excluding it, context can also be leaked. It's likely we need to ignore all Scala classes from instrumentation and use ExecutionContext similar to what we do for Kotlin.

```
    // Long running task which decorates other tasks. We should probably be using ExecutionContext
    // for propagation in Scala but in the meantime this is not needed along with other concurrent
    // instrumentation and causes context leaks.
    if (taskClass.getName().equals("akka.util.SerializedSuspendableExecutionContext")) {
      return false;
    }

    // Wrapper of tasks for dispatch - the wrapped task should have context already and this doesn't
    // need it. It's not obvious why this simple wrapper (not long running task) could leak context.
    // One hypothesis is Scala can rewrite any code to introduce suspend / resume, including the
    // standard Runnable.run. If so, then this check should be generalized to exclude all Scala
    // classes because it is never safe to make context active in a code that has a chance to
    // suspend.
    if (taskClass.getName().equals("akka.dispatch.TaskInvocation")) {
      return false;
    }

    // See above.
    if (taskClass.getName().equals("scala.concurrent.impl.Future$PromiseCompletingRunnable")) {
      return false;
    }
```

**Comment by trask** [comment]
I think we can close now since the tests are passing with `otel.javaagent.testing.fail-on-context-leak=true`
