### ISSUE TITLE
Add a possibility for suppressing `process.command_line` tag for java agent 

### ISSUE THREAD

**Issue by ozoz03** [open-telemetry/opentelemetry-java-instrumentation#2643]
**Is your feature request related to a problem? Please describe.**
The tag can contain sensitive data like JDBC connection string

**Describe the solution you'd like**
Add a suppression similar to this:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/suppressing-instrumentation.md#suppressing-specific-agent-instrumentation
```
-Dotel.instrumentation.process.command_line.enabled=false  
```

**Comment by iNikem** [comment]
You already can use OpenTelemetry Collector to drop unwanted tags. Will that solve your use-case?

**Comment by ozoz03** [comment]
@iNikem 
for security reasons, we would not like to send any sensitive data through network.

**Comment by mateuszrzeszutek** [comment]
Perhaps we should make `ProcessResource` opt-in, not opt-out?
DB query sanitization is enabled by default to avoid sending sensitive data, it would make sense to choose the "secure by default" behavior for process resource attributes too.

**Comment by ozoz03** [comment]
> You already can use OpenTelemetry Collector to drop unwanted tags. Will that solve your use-case?

The collector does not work as well
https://github.com/open-telemetry/opentelemetry-collector/issues/2830

**Comment by anuraaga** [comment]
Hi @ozoz03 - for the collector you need to use resourceprocessor, not attributesprocessor. You can also opt-out of the `process.` attributes with `-Dotel.java.disabled.resource.providers=io.opentelemetry.sdk.extension.resources.ProcessResourceProvider`.

@mateuszrzeszutek Not too sure on opt-in vs opt-out - I think OTels philosophy is generally to send as much data as possible, and deal with it in the collector. I think it's a bit too unclear what should be opt-in vs opt-out as far as resource attributes go, though it's something we'd want to discuss on the spec, not Java-only.

**Comment by ozoz03** [comment]
Fixed by using 
`-Dotel.java.disabled.resource.providers=io.opentelemetry.sdk.extension.resources.ProcessResourceProvider`
Thank you, guys.

**Comment by JianAnzx** [comment]
Hey guys. Tested in Otel agent version 1.20.2
 `-Dotel.java.disabled.resource.providers=io.opentelemetry.sdk.extension.resources.ProcessResourceProvider` doesn't work for me. Then if I replace it by 
`-Dotel.java.disabled.resource.providers=io.opentelemetry.instrumentation.resources.ProcessResourceProvider`
it starts to remove this process.command_line. It seems caused by this [change](https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/aeac3618167af4d1c475546f9f9189e480212c5d#diff-f5bb3facfd0a51c45d6c7f64050321d3e4d83734aa4c07dc61fbc1e5f92ef1e9)

**Comment by krishnaexplore** [comment]
How to disable **net.host.name** label on http_server_duration_milliseconds_count

**Comment by trask** [comment]
hi @krishnaexplore, can you open a new issue for your question? thx
