### ISSUE TITLE
Add documentation around logging

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-instrumentation#2655]
It would be nice to have a short/clear example of how to configure the agent's logging mechanism and log output. Examples should include:

* How to write the agent logs to a file.
* How to separate the agent logs from the stdout/err blending with application logs.

**Comment by breedx-splk** [comment]
That's great, @Tavh thanks for helping out!

**Comment by trask** [comment]
sure!

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
