### ISSUE TITLE
Muzzle can generate InstrumentationModule#contextStore()

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#2678]
**Is your feature request related to a problem? Please describe.**
This is another muzzle improvement that can be done to make javaagent instrumentation contributor's life a bit easier: it is possible to collect all class pairs by detecting `InstrumentationContext.get()` calls in the `ReferenceCollector` when it traverses all advice & helper classes.

**Comment by anuraaga** [comment]
Just wondering, does this mean running muzzles in custom instrumentation is a requirement when using context store? Previously, missing muzzle might cause some unsafety, but IIUC now it lost a feature. If so, I guess it's a big regression until https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2778

**Comment by mateuszrzeszutek** [comment]
You can implement `getMuzzleContextStoreClasses()` by yourself (just rename your `contextStore()` method), in the runtime it still works the same.

**Comment by anuraaga** [comment]
@mateuszrzeszutek Ah great, thanks!
