### ISSUE TITLE
If I install another bytebuddy agent, the afterByteBuddyAgent() method would be called twice

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java-instrumentation#2679]
I had install another bytebuddy agent in my program, and I found the the method afterByteBuddyAgent() in class io.opentelemetry.instrumentation.javaagent.runtimemetrics.RuntimeMetricsInstaller would be called twice. I think it would be a metric with same name without the label added by otel agent to be exported.

**Comment by trask** [comment]
hi @tydhot! there have been several changes since this, are you still able to reproduce this issue? and if so, could you post your repro to help with investigation? thx!

**Comment by trask** [comment]
Closing, but please let us know if you are still seeing this issue and we will re-open, thx!
