### ISSUE TITLE
Connection refused issue with OTLP

### ISSUE THREAD

**Issue by spencer-bos** [open-telemetry/opentelemetry-java-instrumentation#2684]
Every time that I try and start my springboot application with the OTEL Java agent for automatic instrumentation I receive a connection refused error with both traces and metrics. If I use the jaeger exported I do not see this issue. But when I do both I get the error.
```
[opentelemetry.auto.trace 2021-03-31 20:08:32:318 +0000] [grpc-default-executor-1] WARN io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics
opentelemetry-app-a_1  | io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
opentelemetry-app-a_1  | 	at io.grpc.Status.asRuntimeException(Status.java:533)
opentelemetry-app-a_1  | 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
opentelemetry-app-a_1  | 	at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:464)
opentelemetry-app-a_1  | 	at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:428)
opentelemetry-app-a_1  | 	at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:461)
opentelemetry-app-a_1  | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
opentelemetry-app-a_1  | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
opentelemetry-app-a_1  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
opentelemetry-app-a_1  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
opentelemetry-app-a_1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
opentelemetry-app-a_1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
opentelemetry-app-a_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
opentelemetry-app-a_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
opentelemetry-app-a_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
opentelemetry-app-a_1  | Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /127.0.0.1:4317
opentelemetry-app-a_1  | Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
opentelemetry-app-a_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
```

My configuration files have been attached
[configfiles.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/6239269/configfiles.zip)

I was hoping to get some help to understand why I am unable to get metrics and traces out of my java auto instrumented code.

**Comment by iNikem** [comment]
> Connection refused: /127.0.0.1:4317

What is your javaagent configuration? It seems that agent tries to send metrics to localhost, but Collector runs inside separate Docker container. Try setting `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable to `http://otel-agent:4317` maybe?

**Comment by spencer-bos** [comment]
`opentelemetry-app-a_1  | [opentelemetry.auto.trace 2021-04-01 13:42:50:109 +0000] [grpc-default-executor-1] WARN io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics
opentelemetry-app-a_1  | io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
opentelemetry-app-a_1  | 	at io.grpc.Status.asRuntimeException(Status.java:533)
opentelemetry-app-a_1  | 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:533)
opentelemetry-app-a_1  | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
opentelemetry-app-a_1  | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
opentelemetry-app-a_1  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
opentelemetry-app-a_1  | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
opentelemetry-app-a_1  | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
opentelemetry-app-a_1  | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
opentelemetry-app-a_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
opentelemetry-app-a_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
opentelemetry-app-a_1  | 	at java.base/java.lang.Thread.run(Unknown Source)
opentelemetry-app-a_1  | Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: otel-agent/172.18.0.6:4317
opentelemetry-app-a_1  | Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.unix.Errors.throwConnectException(Errors.java:124)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:243)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:672)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:649)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
opentelemetry-app-a_1  | 	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
`
When changing to otel-agent:4317 I now get the above error.
Also I have attached the javaagent configuration.
[Archive.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/6243957/Archive.zip)

**Comment by iNikem** [comment]
Well, it still seems that you have more a networking problem in your Docker setup than actual problem in javaagent. Maybe the [Collector Slack channel](https://cloud-native.slack.com/archives/C01N6P7KR6W ) can help you

**Comment by bogdandrutu** [comment]
@iNikem thanks for pointing this to our channel :)

We do have a metrics demo app https://github.com/open-telemetry/opentelemetry-collector/tree/main/examples/demo that works, and the things that we do differently is that in the agent-config for otlp we don't set an "endpoint: localhost:4317", but we let that empty since is default (if you want to set it I think you need to use "0.0.0.0:4317").

On the app we use as the address `otel-agent:4317` as @iNikem pointed.

**Comment by iNikem** [comment]
A! Indeed, @spencer-bos here is your problem:
```
receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: "localhost:4317"
```

This configuration of yours listens for 4317 port only on `localhost`. But you want to connect to this port from another container, not via `localhost`. Default configuration uses `0.0.0.0:4317`, which means "listen on all network interfaces" thus allowing to accept incoming connections from other hosts/containers.

**Comment by spencer-bos** [comment]
I have tried using both `localhost` and `0.0.0.0` with no change in the result. I have tried changing the ports from the default values and still no change. The weird part is that I am able to test and otlp with other languages like go. But for Java I always get this error.

**Comment by trask** [comment]
@spencer-bos did you ever get this working? if not, if you can post a full repro that would be most helpful

**Comment by laurit** [comment]
Please reopen if this is still an issue.
