### ISSUE TITLE
Update list of instrumentation IDs

### ISSUE THREAD

**Issue by kubawach** [open-telemetry/opentelemetry-java-instrumentation#2701]
**Is your feature request related to a problem? Please describe.**

List of instrumentation IDs (https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/suppressing-instrumentation.md) should be populated.

**Comment by mateuszrzeszutek** [comment]
Duplicate of #2256

**Comment by kubawach** [comment]
Searched for a duplicate before submitting, didn't find, used wrong tokens for search :D
