### ISSUE TITLE
Netty instrumentation causes memory leak and more

### ISSUE THREAD

**Issue by raptium** [open-telemetry/opentelemetry-java-instrumentation#2705]
**Describe the bug**
`io.netty.channel.ChannelFuture#addListener()` is transformed to wrap the input listener with a helper class.
However the `removeListener()` `removeListeners()` counterparts are never transformed. Once a listener is added to the future, it can never be removed. This may cause memory leak and even logical incorrectness.

**Steps to reproduce**
```java
import io.netty.channel.embedded.EmbeddedChannel;
import io.netty.util.concurrent.Future;
import io.netty.util.concurrent.GenericFutureListener;

public class NettyChannelFutureDemo {
    public static void main(String[] args) {
        EmbeddedChannel channel = new EmbeddedChannel();
        for (int i = 0; i < 100; i++) {
            GenericFutureListener<Future<Object>> listener = future -> {
                System.out.println("channel closed");
            };
            channel.closeFuture().addListener(listener);
            channel.closeFuture().removeListener(listener); // not removed if netty instrumentation is on
        }
        try {
            channel.close().await();
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```

**What did you expect to see?**
`channel closed` should never be printed since listeners are removed before the future completes.

**What did you see instead?**
`channel closed` is printed 100 times.

**What version are you using?**
`v1.0.1`

**Environment**
Compiler: AdoptOpenJDK 11.0.10
OS: Microsoft Windows 10

**Additional context**
N/A

**Comment by dkulig** [comment]
Hi, can I get some sort of an ETA when this will be released?

**Comment by iNikem** [comment]
We plan to release new version of the agent during the next several days.

**Comment by dkulig** [comment]
@iNikem thanks for the update. I can see that [v1.2.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.2.0) has been released however this guy seems to not be included in the Bug fixes. Does that mean it will be included in the next release?

**Comment by mateuszrzeszutek** [comment]
Oh, the fix is there, but the note does not say anything about memleak explicitly:

> * Netty 4.1 listeners could not be removed by application (#2851)

**Comment by dkulig** [comment]
thanks @mateuszrzeszutek
