### ISSUE TITLE
JDBCConnectionUrlParser exception thrown

### ISSUE THREAD

**Issue by montyz** [open-telemetry/opentelemetry-java-instrumentation#2741]
**Describe the bug**
For the jdbc url `jdbc:mysql:replication://lark-aurora-prod.cluster-cmowtuugqgqn.us-west-2.rds.amazonaws.com:3306,lark-aurora-prod.cluster-ro-cmowtuugqgqn.us-west-2.rds.amazonaws.com:3306/lark?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8` I'm seeing an exception thrown while parsing

![image](https://user-images.githubusercontent.com/738286/113788519-f4022c80-96f1-11eb-9915-c087518da0dc.png)

Also since parsing can be relatively expensive, it seems that maybe caching the actual info used for metrics would help performance? But obviously not needed to fix this issue.

**Steps to reproduce**
Hopefully running the test with the above url as input will surface the error.

**What did you expect to see?**
Should be no exception. 

**What did you see instead?**
Substring exception thrown.

**What version are you using?**
1.0.1

**Comment by mateuszrzeszutek** [comment]
I run a simple test case:

```groovy
  def "test"() {
    when:
    def url = "jdbc:mysql:replication://lark-aurora-prod.cluster-cmowtuugqgqn.us-west-2.rds.amazonaws.com:3306,lark-aurora-prod.cluster-ro-cmowtuugqgqn.us-west-2.rds.amazonaws.com:3306/lark?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8"
    def dbInfo = parse(url, null)

    then:
    dbInfo != null
    println dbInfo
  }
```

and it passed, it printed out

```
DbInfo{system=mysql, subtype=replication, shortUrl=mysql:replication://lark-aurora-prod.cluster-cmowtuugqgqn.us-west-2.rds.amazonaws.com:3306, user=null, name=null, db=lark, host=lark-aurora-prod.cluster-cmowtuugqgqn.us-west-2.rds.amazonaws.com, port=3306}
```

Can you share the full stacktrace, with line numbers? Maybe that'll help with pinpointing this issue.

**Comment by iNikem** [comment]
@montyz Can you share the full stacktrace with us, with line numbers?

**Comment by montyz** [comment]
Unfortunately I haven't been able to get a stacktrace. The exception is
caught somewhere before I would get it to log it. I tried to debug into it
locally but wasn't able to set a breakpoint that worked, somehow even
though I have the jar, since it's really running in the agent it doesn't
seem to work.

**Comment by laurit** [comment]
@montyz Did you try setting an exception breakpoint for `StringIndexOutOfBoundsException`? Adding a breakpoint in the constructor of `StringIndexOutOfBoundsException` should also work.

**Comment by montyz** [comment]
Locally I cannot reproduce it. I even set a breakpoint in `JdbcConnectionUrlParser.parse` and set the input value to what it should be in my production environment, but that still did not trigger the exception. I only observed it in a profile of my prod env, but that doesn't actually show line numbers so I can't get a proper stack trace.

I can't think of any way I could get a proper stack trace on my production system, so I'll close this. Thanks for looking!

**Comment by trask** [comment]
hey @montyz, are you able to enable agent debug logging on a system where this repros?

https://github.com/open-telemetry/opentelemetry-java-instrumentation#troubleshooting

if so, this exception should get logged here:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/79d5789d1d24a2d122c3b850895a0e4138aeb927/instrumentation/jdbc/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jdbc/JdbcConnectionUrlParser.java#L845

**Comment by montyz** [comment]
I tried that locally and in my sandbox in the cloud, but do not see any messages there, so it seems it is only triggered in my production environment, where it's not so easy to test.

**Comment by trask** [comment]
hey @montyz, any chance you can add the JVM arg below to your production env, to log the exception in that class and capture the stack trace?

```
-Dio.opentelemetry.javaagent.slf4j.simpleLogger.log.io.opentelemetry.javaagent.instrumentation.jdbc.JdbcConnectionUrlParser=debug
```
