### ISSUE TITLE
Broken trace in Kotlin services

### ISSUE THREAD

**Issue by sleeping-barber** [open-telemetry/opentelemetry-java-instrumentation#2746]
**Describe the bug**
Hey team,
we successfully auto-instrumented most of our backend services via the `javaagent` in version `1.0.1` and want to decorate our traces with domain specific data.

We discovered that the traces we receive between two services (I will call them `origin` and `target` service) are broken. With broken I mean that a single transaction, a call from `origin` to `target`, is not displayed in our analyse backend as one trace but as two traces.

**Detail information about `origin`**

- Written in `Spring Boot`
- Uses a generated client to call `target` via the `armeria` framework in version `1.3.0`

**Detail information about `origin`**
- Written in `Ktor`

**Steps to reproduce**
We tried to reproduce this behaviour by writing two services from scratch using `Spring Boot` and using Coroutines but this example just showed us working traces. This is why we believe there must be a misusage of `opentelemetry` at some point.

Reading through the open issues we discovered that `makeCurrent` is illegal in Kotlin code and we fixed this in the `origin` service but still the trace is broken.

Please bear with me, but I am not a Kotlin developer and learning this concepts from scratch (e.g. Coroutines).

**What did you expect to see?**
We expected one trace from starting from the `origin` service to the `target` service.

**What did you see instead?**
We see one trace created in the `origin` service and immidiialtey stopping within this context. Another trace is created which is starting also in the `origin` service but is calling the `target` service.

Searching for our added metadata (we add in both services some data) leads just to one of those traces not an aggregated trace, which leads to our conclusion that the trace is broken.

**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OpenTelemetry

**Additional context**
Both services are using concurrent code and I will provide some pseudo code here on how we are calling the `target` service  from the `origin` service. Maybe there is just on quirk which is messing up the trace.

**Orgin Service**

**Comment by kjschnei001** [comment]
What was the outcome of this problem?

**Comment by trask** [comment]
hey @kjschnei001, this was closed as a duplicate of #2748
