### ISSUE TITLE
Broken trace in Kotlin services

### ISSUE THREAD

**Issue by sleeping-barber** [open-telemetry/opentelemetry-java-instrumentation#2748]
**Describe the bug**
Hey team,
we successfully auto-instrumented most of our backend services via the `javaagent` in version `1.0.1` and want to decorate our traces with domain specific data.

We discovered that the traces we receive between two services (I will call them `origin` and `target` service) are broken. With broken I mean that a single transaction, a call from `origin` to `target`, is not displayed in our analyse backend as one trace but as two traces.

**Detail information about `origin`**

- Written in `Spring Boot`
- Uses a generated client to call `target` via the `armeria` framework in version `1.3.0`

**Detail information about `origin`**
- Written in `Ktor`

**Steps to reproduce**
We tried to reproduce this behaviour by writing two services from scratch using `Spring Boot` and using Coroutines but this example just showed us working traces. This is why we believe there must be a misusage of `opentelemetry` at some point.

Reading through the open issues we discovered that `makeCurrent` is illegal in Kotlin code and we fixed this in the `origin` service but still the trace is broken.

Please bear with me, but I am not a Kotlin developer and learning this concepts from scratch (e.g. Coroutines).

**What did you expect to see?**
We expected one trace from starting from the `origin` service to the `target` service.

**What did you see instead?**
We see one trace created in the `origin` service and immidiialtey stopping within this context. Another trace is created which is starting also in the `origin` service but is calling the `target` service.

Searching for our added metadata (we add in both services some data) leads just to one of those traces not an aggregated trace, which leads to our conclusion that the trace is broken.

**What version are you using?**
OTEL `1.0.1`
OTEL Exporter `0.8.0`

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OpenTelemetry

**Additional context**
Both services are using concurrent code and I will provide some pseudo code here on how we are calling the `target` service  from the `origin` service. Maybe there is just on quirk which is messing up the trace.

**Origin Service**

The call from the `origin` service to `target` service is done in a `suspend` function and we wrapped the span closing call for better readability like this:

```
suspend fun pseudoCode() {
    GlobalOpenTelemetry.getTracer("$NAME_OF_SERVICE")
        .spanBuilder(spanName)
        .setParent(Context.current().with(parentSpan))
        .startSpan()
    return span.coWrap {
        // do work
       callTargetService().also {
           span.setAttribute("metadata.origin", $VALUE)
    }
}
suspend inline fun <T> Span.coWrap(crossinline block: suspend () -> T): T {
    return withContext(this.asContextElement()) {
        try {
            block()
        } finally {
            end()
        }
    }
}
```

The call to the `target` service is using `armeria` generated client code (I see also the usage of ` CompletableFuture` here).

**Target Service**

The `target` service has a `Thrift` handler for serving those request and here we are using the `runBlocking` feature of Coroutines:

```
    override fun acceptRequest(request: Request): Request = runBlocking {

            val response = doWork()
```

It seems that the `doWork` function is still using the forbidden `makeCurrent` but this isn't a Coroutine anymore or is it? The code looks like this:

```
    operator fun doWork(): Response {
        val acceptInitialOfferSpan = newSpan(spanName = "AcceptInitialOffer")

        acceptInitialOfferSpan.makeCurrent().use {
            val span = Span.current()

            return commandDispatcher.validateAndHandle(
                    // Return some data
                ).also {
                    span.setAttribute("metadata.target", $VALUE)
                    span.end()
                }
            ).firstEvent()
        }
    }
```

I can see the usage of `makeCurrent` and also we are not using the `GlobalOpenTelemetry.getTracer` here.

Any help is much appreciated,
Thanks!

**Comment by necrolyte2** [comment]
I believe we also see this issue where we have quite a few SpringBoot applications that are wrapped with v1.0.1 agent and work fine, however, the one service that calls them is written in Kotlin(using Coroutines). We are seeing that the coroutines are creating separate traces for each http call instead of propagating the context to those dependent services.

**Comment by sleeping-barber** [comment]
@necrolyte2 thanks for sharing your experience here too. I found this PR https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1618 which should actually fix this. So I thought this is only happening when manual instrumentation is used but if I got your observation correctly even the auto instrumentation is broken.

Today I tried to use the `WithSpan` annotation on the call from service `origin` and suddenly the whole span was gone. Digging through my Analyse Backend I found it again but this time the decorated metadata wasn't injected anymore.

**Comment by trask** [comment]
hey @sleeping-barber @necrolyte2! can you create a github repository with a complete repro and steps that we can use to debug the issue? kotlin + context propagation issues are tricky and we really appreciate the help!

**Comment by thundering-herd** [comment]
@trask I will try to implement a repository which can reproduce this problem.

In the meantime here the current traces we see, keep im mind das service `origin` is calling the service `target` all running in Coroutines.

**Trace of origin, 2021-04-09T07:38:21.562Z**
![Screenshot 2021-04-09 at 10 01 53](https://user-images.githubusercontent.com/79836315/114149371-204cc180-991b-11eb-9a79-8e8094c28069.png)

**Trace of target 2021-04-09T07:38:21.706Z**
![Screenshot 2021-04-09 at 10 03 05](https://user-images.githubusercontent.com/79836315/114149447-33f82800-991b-11eb-9392-33bbcae5ca1f.png)

The timestamp is close to identical, could it be we somehow created a new trace by accident?

**Comment by sleeping-barber** [comment]
@trask I will try to implement a repository which can reproduce this problem.

In the meantime here the current traces we see, keep im mind das service `origin` is calling the service `target` all running in Coroutines.

**Trace of origin, 2021-04-09T07:38:21.562Z**
![Screenshot 2021-04-09 at 10 01 53](https://user-images.githubusercontent.com/10873365/114155730-18dce680-9922-11eb-9d92-0ba3eef316e5.png)


**Trace of target 2021-04-09T07:38:21.706Z**
![Screenshot 2021-04-09 at 10 03 05](https://user-images.githubusercontent.com/10873365/114155748-1f6b5e00-9922-11eb-811a-e78eb0396f48.png)


The timestamp is close to identical, could it be we somehow created a new trace by accident?

**Comment by thundering-herd** [comment]
I mentioned we are using `armeria` for the client code generation and I just recognized that the second trace form the `target` service is created in the thread pool of `armeria-common-worker-epoll-2-2` I will take this insight also into account, maybe `armeria` is not getting the span context and is creating it's own trace in the `origin` service.

**Comment by anuraaga** [comment]
@thundering-herd Thanks for the insight! Also we still need to implement a context bridge with Armeria which may or may not help here. First I need to finish the grpc one when I get less swamped but it will be similar and allow using Armeria propagation patterns to handle OTel context too.

**Comment by thundering-herd** [comment]
Hey @anuraaga 
I would like to offer my help here. What can be done to help you looking for the root cause?

**Comment by trask** [comment]
hey @thundering-herd, minimal repros are always super helpful.

see if you can narrow it down to something reproducible using kotlin only (no armeria), or something reproducible using armeria only (no kotlin), or if it's only reproducible when using both(!)

**Comment by sleeping-barber** [comment]
> @thundering-herd Thanks for the insight! Also we still need to implement a context bridge with Armeria which may or may not help here. First I need to finish the grpc one when I get less swamped but it will be similar and allow using Armeria propagation patterns to handle OTel context too.

@anuraaga Maybe we found a way to reproduce this behaviour easily. We are using async call via the generated `armeria` clients. Switching back to sync calls and the traces are correct. Maybe the event loop is simply using one thread(?) and so our approach to use `ThreadLocal` is simply not working.

I will provide a repository when I am sure I found the root cause for this.

**Comment by trask** [comment]
@sleeping-barber are you still seeing this issue in the latest javaagent version? are you able to provide a repro that we can use to troubleshoot? thx!
