### ISSUE TITLE
Library instrumentation should read its version from a file, not from the jar manifest

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#2761]
Library instrumentation will often get shaded into other jars, and the manifest information will get lost. In that case, the version number of the instrumentation will not end up correct...it will end up being populated with the version of the jar that it is shaded/fat-jarred into. For example, this happens when okhttp3 library instrumentation is used in an Android application.

It would be more robust for library instrumentation to include a resource file that contains the version number, rather than relying on the jar manifest.

**Comment by mateuszrzeszutek** [comment]
I think that we should do the same for the javaagent itself: right now we use jar manifest's `Implementation-Version` everywhere, but that's always (probably) overwritten in the vendor distros with their own version.
We should put the javaagent version into a resource file and not depend on `Implementation-Version` anymore.

**Comment by anuraaga** [comment]
I think for agent it's ok - I very much want to overwrite that version number so ours is the one that's reported in `telemetry`.
