### ISSUE TITLE
opentelemetry-spring-boot-autoconfigure module is not setting up any propagators

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#2771]
When the opentelemetry-spring-boot-autoconfigure module builds the `OpenTelemetrySdk` in `OpenTelemetryAutoConfiguration`, it doesn't call `setPropagators`, so no propagators are set up and no context propagation takes place.

Related to #2624 (though in that issue the javaagent is also being used, so things are a bit different there).

**Comment by liaozhenlin** [comment]
Is it lost META-INF when create the jar package with gradle? When I unzip the jar package,there is not a certain file like "spring.factories".

**Comment by Enkelian** [comment]
To reiterate, the point of this issue is to simply call `setPropagators` with some propagator (maybe `W3CTraceContextPropagator`) while setting up `OpenTelemetrySdk` builder. 

If my understanding is correct, I'd be glad to take care of that issue as my first contribution to the project.
