### ISSUE TITLE
Reactor javaagent instrumentation tests pass even with advice code commented out

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#2777]
**Describe the bug**
When you remove the `TracingOperator.registerOnEachOperator()` call from the `ReactorHooksAdvice` class all javaagent tests still pass - most likely the executor instrumentation covers all test cases, similar as with rxjava2: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2672

**Comment by Tavh** [comment]
@mateuszrzeszutek 
Is this still relevant? I don't see a class called 'ReactorHooksAdvice' and every call to 
tracingOperator.registerOnEachOperator() seems to be inside a test class

**Comment by mateuszrzeszutek** [comment]
I believe it's called `HooksInstrumentation$ResetOnEachOperatorAdvice` now. I commented it out and reran the tests, they're failing (as they should) - I think we can mark this issue as closed.
