### ISSUE TITLE
Extract the muzzle codegen gradle plugin

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#2778]
**Is your feature request related to a problem? Please describe.**
The aim of this issue is to extract a gradle plugin that'll contain the muzzle compile-time code generation functionality (i.e. the byte buddy plugin). It should be possible to use the new gradle plugin in external instrumentations. The new plugin should be published independently from the main project.

**Comment by iNikem** [comment]
Done.
