### ISSUE TITLE
Service suppression for gRPC

### ISSUE THREAD

**Issue by johnerikhalse** [open-telemetry/opentelemetry-java-instrumentation#2806]
**Is your feature request related to a problem? Please describe.**
While it is possible to suppress traces based on classes and methods, I couldn't find a way to suppress traces from specific gRPC services.

I have services implementing an API which I want traces from, but in addition I have a health checker service which adds a lot of spans which in this context is noise.

**Describe the solution you'd like**
I would like to have a way to configure which services should or should not be traced. One way of doing this could be to suppress spans based on span name. This way it would not only apply to gRPC services. For example one might wan't some important db calls to be traced while suppressing others.

From a users perspective options similar to the properties for include/exclude of @WithSpan, but accepting wildcards, would be ideal. I don't know what impact this might have on performance though.

**Comment by trask** [comment]
Hey @johnerikhalse! I think you are looking for this feature: #1060, which hasn't been implemented yet.

**Comment by johnerikhalse** [comment]
I think you are right. Closing this issue.
