### ISSUE TITLE
Muzzle incorrectly constructs field references

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#2823]
**Describe the bug**
I've noticed that in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2819 muzzle should have prevented the instrumentation from being applied, but it didn't: a `NoSuchFieldError` was thrown instead.

When you print out the muzzle references you can see that it incorrectly assigns the `qs` field to our helper class:

```
  io.opentelemetry.instrumentation.rxjava2.TracingObserver extends<io.reactivex.internal.observers.BasicFuseableObserver>
    Field: PRIVATE_OR_HIGHER NON_STATIC FieldRef:qsio/reactivex/internal/fuseable/QueueDisposable
  io.reactivex.internal.observers.BasicFuseableObserver
    Source: io.opentelemetry.instrumentation.rxjava2.TracingObserver:0
    Source: io.opentelemetry.instrumentation.rxjava2.TracingObserver:39
    Method: NON_STATIC PROTECTED_OR_HIGHER <init>(Lio/reactivex/Observer;)V
```

And the `BasicFuseableObserver` which actually owns this field only has a reference to its constructor. We don't check field access in our helper classes, so muzzle fails to recognize a mismatch in the runtime.

**What did you expect to see?**
Muzzle should assign the field to the class that actually defines it.

**Comment by laurit** [comment]
For field access `this.qs` compiler generates bytecode where field owner is the type of `this` even when the field is in super class. This behaviour is the same for methods and static fields, owner is whatever the type is that access is performed on, actual field owner is resolved during runtime.
Are you suggesting that we somehow try to figure out the actual owner of field/method?
