### ISSUE TITLE
Make tracecontext injection configurable

### ISSUE THREAD

**Issue by pavolloffay** [open-telemetry/opentelemetry-java-instrumentation#2859]
**Is your feature request related to a problem? Please describe.**

AWS-SDK instrumentation (SQS) fails with the javaagent because  tracecontext injection increases the maximum number of allowed attributes.

Exception:
```
exception: com.amazonaws.services.sqs.model.AmazonSQSException: Number of message attributes [11] exceeds the allowed maximum [10]. (Service: AmazonSQS; Status Code: 400; Error Code: InvalidParameterValue; Request ID: f45340f7-defa-5e44-9f6f-180da314297f)
```

Another use-case what we have seen from the field is that some server-side applications expect an exact set of headers. 

**Describe the solution you'd like**

I want to disable tracecontext injection per instrumentation. E.g. disable injection of tracecontext in okhttp client instrumentation. The okhttpclient would still create spans but it would not inject any context into outbound requests. 

**Describe alternatives you've considered**

Entirely disable instrumentation, however, I still want to receive telemetry data from that inst. so it is not a feasible solution for me.

**Additional context**

None.

**Comment by anuraaga** [comment]
For the case of aws sdk specifically I think this may be a bug in SQS. Will try to follow up on that.

Being able to disable instrumentation per client would be useful and is a big reason we allow customizing OpenTelemetry on a per-client level - per instrumentation seems not so intuitive. One okhttp client could talk to a server with b3 and another with w3c. Per client customization is currently very hard in the agent and why we have the fairly obtuse net peer mapping.

If we need to work around the SQS bug temporarily, I guess we can check the number of attributes on the message and not propagate if it's already at the limit.

**Comment by pavolloffay** [comment]
I did tests locally with SQS and the newest AWS SDK. The SDK does not count `X-Amzn-Trace-Id` into the total number of attributes. Maybe the issue is present in the older AWS SDK version. I will follow up on this.


> Being able to disable instrumentation per client would be useful and is a big reason we allow customizing OpenTelemetry on a per-client level with library instrumentation - per instrumentation seems not so intuitive. One okhttp client could talk to a server with b3 and another with w3c. Per client customization is currently very hard in the agent and why we have the fairly obtuse net peer mapping. So I'm not really in favor of a per instrumentation knob for this.

My thinking was that this could follow similar approach to `otel.instrumentation.<inst-name>.enabled=false` but just disable inject. From your comment it seems that the setting could be based on host (e.g. do not inject for this host), I like this but I would have concerns about keeping the config in sync with dynamic environments.

**Comment by trask** [comment]
hey @pavolloffay, doing some issue triage, is this still an issue for you? thx
