### ISSUE TITLE
Please make opentelemetry-exporter-otlp-common open

### ISSUE THREAD

**Issue by endink** [open-telemetry/opentelemetry-java-instrumentation#2864]
This feature will allows us to use existing code, especially "SpanAdapter", use to serialize Span as a transport data structure for custom export or collector.

for example :
how to use kafka collectors in java ? 

golang kafka collector is ready,

if SpanAdapter is open, It's very easy to implement !

**Comment by trask** [comment]
hey @endink! I suspect you meant to open this in https://github.com/open-telemetry/opentelemetry-java where the `opentelemetry-exporter-otlp-common` module lives?

**Comment by endink** [comment]
Yeap! I would like to be able to use existing code to serialize the "SpanData" , but the classes (ResourceAdapter/SpanAdapter) that in exporter-otlp-common used for otlp serialization is not public, because they're in an internal package.

BTW, forgive me for my bad English

**Comment by endink** [comment]
Sorry, the latest version of SpanAdapter class is already public, the version I'm using is internal
