### ISSUE TITLE
Improve instrumentation folder structure doc to mention multi-version structure

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#2891]
See problem encountered: https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/2884#discussioncomment-672991

We should add doc to cover this: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/writing-instrumentation.md#folder-structure

**Comment by SivaTharun** [comment]
@trask i would like to contribute to open-telemetry repository, can i work on this issue. i hope all the required details are being  mentioned in #2884

**Comment by trask** [comment]
hey @SivaTharun! go ahead, and feel free to send a draft PR with questions if you are uncertain of some details
