### ISSUE TITLE
Release stable version of opentelemetry-instrumentation-api

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#2892]
This is a tracking issue for releasing stable version of the `opentelemetry-instrumentation-api` artifact.

Will post updates from time to time on this issue for anyone who wants to watch/follow it.

You may also be interested in following #2713 which is the current major work in progress towards this goal.

In the meantime, if you require a stable artifact, we recommend using `opentelemetry-api` directly, or shading `opentelemetry-instrumentation-api`.

**Comment by trask** [comment]
I realized, another gate on a stable release of the opentelemetry-instrumentation-api is a stable release of the semantic conventions

**Comment by trask** [comment]
Something else to consider is whether to wait for otel-wide spec of "instrumentation api" (discussion at https://github.com/open-telemetry/oteps/pull/165)

**Comment by iNikem** [comment]
Or just have all attributes extractor in a separate unstable module

**Comment by iNikem** [comment]
But anyway I totally support the idea of somehow making possible to declare stable a subset of a module

**Comment by mateuszrzeszutek** [comment]
> Or just have all attributes extractor in a separate unstable module

We've already introduced `@UnstableApi` for metrics API, the semantic conventions situations is kind of similar to that.
But yeah, a separate module would be fine too.

**Comment by ThomasVitale** [comment]
Is it correct to follow the backlog in https://github.com/open-telemetry/opentelemetry-java-instrumentation/projects/10#card-70538476 to know what tasks are left to do before opentelemetry-instrumentation-api can go GA?

**Comment by iNikem** [comment]
@ThomasVitale yes

**Comment by trask** [comment]
for those watching this issue, we are planning for the next release of the opentelemetry-instrumentation-api (1.17.0) to be a Release Candidate
