### ISSUE TITLE
auto instrumentation design

### ISSUE THREAD

**Issue by onespacer** [open-telemetry/opentelemetry-java-instrumentation#2922]
Is there any sequence diagram or component diagram that helps connecting all the components under this repo? I want to know how all library intrumentation:tracers are initialized and included in the classpath.

@trask

**Comment by onespacer** [comment]
@trask ^^

**Comment by trask** [comment]
@onespacer check out [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/CONTRIBUTING.md), in particular "Writing instrumentation", "Understanding the javaagent components" and "Understanding Muzzle"

**Comment by onespacer** [comment]
Thank you. One quick question about muzzle. muzzle.md has this line "compile time it collects references to the third-party symbols and used helper classes". Does it mean compile time of an agent?

**Comment by trask** [comment]
Closing, please let us know if you have any further questions!
