### ISSUE TITLE
Capture argument value

### ISSUE THREAD

**Issue by agardnerIT** [open-telemetry/opentelemetry-java-instrumentation#2944]
Given that I've instrumented Tomcat with the -jar file. How would I capture an argument value from custom code?

How would I capture the value of `iValue` below and report it to my backend?

```
private void doThis(int iValue) {}
```

I'm currently instrumenting with:

```
-Dotel.instrumentation.methods.include=mypackage.IndexServlet[doThis]
```

**Comment by jkwatson** [comment]
You can do this programmatically by doing:

```
Span.current().setAttribute(intKey, iValue);
```

Where `intKey` is a pre-allocated instance of `AttributeKey<Long>`.

**Comment by agardnerIT** [comment]
Thanks, that worked :)
