### ISSUE TITLE
Publish snapshots on main build

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2951]
Snapshots are often helpful in debugging issues and it's easy to say try a snapshot after a commit goes green. But I think currently we only publish nightly which means coordination between (possible) fixes and verification. I think it's fine to publish snapshots in main build, or at least try and stop if we see too much flakiness.

**Comment by anuraaga** [comment]
If we do so, we should remove the publishing from nightly build since it would be redundant.

**Comment by iNikem** [comment]
If you want to test isolated fix/commit, can you use jitpack for this? It seems wasteful to me to publish snapshots on every PR merge.

**Comment by trask** [comment]
> It seems wasteful to me to publish snapshots on every PR merge.

we are averaging ~5 PRs a day, so this doesn't seem soooo bad, I'm in favor of faster feedback / easier coordination for users being able to try out SNAPSHOT releases

**Comment by anuraaga** [comment]
Yeah I think we have few enough commits that it's ok. Another reason to do it on main build is because we do expect failures for nightly build, like last night, due to latest dep tests. So it's not a reliable source of snapshots. Jitpack is a bit annoying for normal libraries, for an agent I'm not even too sure how it works.
