### ISSUE TITLE
How to disable traces from specific classes 

### ISSUE THREAD

**Issue by harshasrimal** [open-telemetry/opentelemetry-java-instrumentation#2980]
Hi, 
Currently we are doing a distributed tracing project. We are using the pet clinic spring boot app.
 https://github.com/spring-projects/spring-petclinic
The traces are monitoring from Jaeger. Now we require  this application to **stop** the traces which are coming from the from specific class ( eg:-ownercontroller class). We followed your documentation but we were unable to disable the traces. Appreciate if you could kindly assist on this.

**Comment by breedx-splk** [comment]
Hi @harshasrimal .  Can you please link to do the docs that you followed and explain exactly what you attempted that did not work?

Are you using the opentelemetry collector?  There is also the capability to [exclude spans in the collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/README.md#includeexclude-spans).

**Comment by harshasrimal** [comment]
thanks @breedx-splk  for the quick reply,we are  followed this document
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/suppressing-instrumentation.md,

yes, we are ussing open telemetry collector
we are use to this command start **open telemetry agent** and **pet clinic app**

java -javaagent:opentelemetry-javaagent-all.jar \
-Dotel.traces.exporter=otlp \
-Dotel.exporter.otlp.endpoint=http://localhost:4317 \
-Dotel.otlp.span.timeout=4000 \
-Dotel.resource.attributes=service.name=pet-clinic \
-Dotel.javaagent.exclude.classes=ownercontroller \
-jar target/spring-petclinic-2.4.5.jar

app profely work but all traces are comming jaeger,
we want disable traces from ownercontroler class,pleace explain how to resole this issue

**Comment by breedx-splk** [comment]
@harshasrimal I think you are close.  

First thing I notice is that you have misspelled the system property.  You have `-Dotel.javaagent.exclude.classes` but I think it should be `-Dotel.javaagent.exclude-classes` (note the hyphen and not dot).

Second, the full class name with package should be specified with the correct casing, so I suspect that `ownercontroller` is also misspelled.  You probably want something more like:

`-Dotel.javaagent.exclude-classes=com.something.OwnerController`

Let us know if that helps.

**Comment by mateuszrzeszutek** [comment]
Also, `otel.javaagent.exclude-classes` will only disable spans that would normally be started in that one particular class (or classes, if you provide a list) - if you need to exclude the whole HTTP request from tracing (a healthcheck endpoint for example) then we do not currently offer such functionality. There's https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1060 that describes this feature (still not implemented 😞 ).

**Comment by harshasrimal** [comment]
@breedx-splk  **ownwer controler class trases are visible,**

we are tried to this command 
 java -javaagent:opentelemetry-javaagent-all.jar \
 -Dotel.traces.exporter=otlp \
 -Dotel.exporter.otlp.endpoint=http://localhost:4317 \
 -Dotel.otlp.span.timeout=4000 \
 -Dotel.resource.attributes=service.name=pet-clinic \
 **-Dotel.javaagent.exclude-classes=org.springframework.samples.petclinic.owner.OwnerController \**
 -jar target/spring-petclinic-2.4.5.jar

app work but owner controler class trases are visible
![2021-05-14_11-53](https://user-images.githubusercontent.com/75670395/118230328-1e8e9480-b4ab-11eb-9139-e71a29b11a02.png)

**Comment by breedx-splk** [comment]
Well yeah, like @mateuszrzeszutek said, if the span is starting above that class (like in the servlet layer, for example) then this approach will not work.

**Comment by harshasrimal** [comment]
Hi @breedx-splk 
Since this approach does not work if the span is starting above that class, we tried by adding all the packages of this application under "-Dotel.javaagent.exclude-classes".

 However still I can see the spans in the Jaeger UI

 Below is the command I used to run the demo application [1].

 java -javaagent:opentelemetry-javaagent-all.jar  -Dotel.traces.exporter=otlp  -Dotel.exporter.otlp.endpoint=http://localhost:4317  -Dotel.otlp.span.timeout=4000  -Dotel.resource.attributes=service.name=pet-clinic -Dotel.javaagent.exclude-classes="org.springframework.samples.petclinic.PetClinicApplication,org.springframework.samples.petclinic.model.*,org.springframework.samples.petclinic.owner.*,org.springframework.samples.petclinic.system.*,org.springframework.samples.petclinic.vet.*,org.springframework.samples.petclinic.visit.*" -jar target/spring-petclinic-2.4.5.jar 

 

[1] https://github.com/spring-projects/spring-petclinic.git

**Comment by mateuszrzeszutek** [comment]
Hey @harshasrimal,

Unfortunately the `otel.javaagent.exclude-classes` option will not work in your case: the SERVER spans are produced somewhere in the server layer (any classes that extend `javax.servlet.Servlet` or `javax.servlet.Filter`), they're not being created in the petclinic application code, but somewhere in one of its dependencies. That's why excluding the whole petclinic application package will not suppress those spans.
If your aim is to disable a particular route/URL pattern from tracing, then it is currently not implemented (see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1060) and there is no good way to do that.

**Comment by harshasrimal** [comment]
@mateuszrzeszutek thank you,

**Comment by trask** [comment]
Closing, it seems the underlying issue is tracked in #1060. @harshasrimal let us know if this is not the case, thx!
