### ISSUE TITLE
javaagent:test task not rerun after change to javaagent tooling

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#2981]
#2912 introduced a change in behavior that should have required an update to `ShadowPackageRenamingTest` (#2982) but `javaagent:test` seems to have not run, or not run with the new version, due to build cache. The test passed on CI and failed only with significant Gradle changes invalidating the cache (#2973) or using `./gradlew :javaagent:test --rerun-tasks` locally on the main branch

**Comment by trask** [comment]
Closing, I believe this was resolved by #3269 (with outstanding todo tracked in #3500)
