### ISSUE TITLE
opentelemetry-instrumentation-bom-alpha/1.2.0-alpha lists io.opentelemetry:opentelemetry-bom twice (sort of)

### ISSUE THREAD

**Issue by asarkar** [open-telemetry/opentelemetry-java-instrumentation#3002]
[opentelemetry-instrumentation-bom-alpha:1.2.0-alpha](https://search.maven.org/artifact/io.opentelemetry.instrumentation/opentelemetry-instrumentation-bom-alpha/1.2.0-alpha/pom) has conflicting listings of `io.opentelemetry:opentelemetry-bom` and `io.opentelemetry:opentelemetry-bom-alpha`.
```
<dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom</artifactId>
        <version>1.2.0</version>
        <type>pom</type>
        <scope>import</scope>
</dependency>
<dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom-alpha</artifactId>
        <version>1.2.0-alpha</version>
        <type>pom</type>
        <scope>import</scope>
</dependency>
```

**Comment by anuraaga** [comment]
Hi @asarkar these declarations seem correct. Are you seeing a problem?

**Comment by asarkar** [comment]
@anuraaga For some reason, the otel instrumentation bom applied via spring boot Gradle dependency management plugin isn’t working for me (artifacts without versions aren’t resolved), so I was looking to specify the otel version directly. Two different versions of the (almost) same bom looks very odd to me.

**Comment by anuraaga** [comment]
@asarkar One is to manage artifacts that have been released as stable, mainly tracing, and the other manages ones that are not, namely metrics. As we do want to provide metrics from instrumentation even during its incubation we add the alpha bom as well. Once metrics become stable we will remove the alpha bom from here.

**Comment by anuraaga** [comment]
As a side note, you may want to try adding a `platform` dependency on our bom (and even spring-boot-dependencies bom). Gradle has had good support for importing boms natively for a while now so I'd consider the dependencies plugin deprecated.

**Comment by asarkar** [comment]
The Gradle `platform` dependency and dependency management plugin aren’t exactly compatible, they end up creating duplicate `dependencyManagement` blocks. Gradle still doesn’t have a way to override versions from imported bom, so dependency management plugin is still useful.

**Comment by asarkar** [comment]
> One is to manage artifacts that have been released as stable, mainly tracing, and the other manages ones that are not, namely metrics. 

I've not compared the boms, but if they've common artifacts, the latter would override the former causing unexpected results.

**Comment by anuraaga** [comment]
The alpha bom only manages alpha artifacts

https://github.com/open-telemetry/opentelemetry-java/blob/main/bom-alpha/build.gradle.kts#L22

**Comment by asarkar** [comment]
I compared the BOMs and as far as I could tell, there's no common artifacts. I should've done this before opening the ticket, sorry about the confusion.
