### ISSUE TITLE
Expose JVM runtime metrics 

### ISSUE THREAD

**Issue by secustor** [open-telemetry/opentelemetry-java-instrumentation#302]
It seems like the OpenTelemetry SDK for Java is already exposing runtime metrics, but these are yet not exposed using the OTLP exporter.

https://github.com/open-telemetry/opentelemetry-java/tree/master/contrib/runtime_metrics/src/main/java/io/opentelemetry/contrib/metrics/runtime

**Comment by breedx-splk** [comment]
The `runtime-metrics` linked to by the original requestor have been removed/deprecated (see [#2119](https://github.com/open-telemetry/opentelemetry-java/pull/2119) and [#2226](https://github.com/open-telemetry/opentelemetry-java/pull/2226)).

I think that we should either close this one or rewrite it to more clearly describe what is expected/wanted.

**Comment by mateuszrzeszutek** [comment]
This package is now a library instrumentation in this repo, so maybe we should use it in javaagent?

**Comment by mateuszrzeszutek** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2311
