### ISSUE TITLE
Enhancing root span for Spring users

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3025]
I think currently for Spring users, the root span is created by Tomcat instrumentation, not servlet or Spring. Is this true? Does this mean it's not possible to add attributes to the root span?

Context: https://github.com/aws-observability/aws-otel-java-instrumentation/issues/57

**Comment by mateuszrzeszutek** [comment]
Once we implement https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1726 they could use `ServerSpan.fromContext()` to add attributes to the root span.

**Comment by trask** [comment]
It may also be worth exploring this issue in the spec in case the "server span" concept is something that we should add to the OTel API somehow.

**Comment by trask** [comment]
@anuraaga I didn't follow how this issue is specific to the root span being created by Tomcat instrumentation?

**Comment by anuraaga** [comment]
I'm not sure if standard extension points provided by servlet and Spring can be used to operate on a span created by Tomcat Instrumentation. They might be able to just didn't check it. A span created by servlet we'd know servlet API can be used to augment.

**Comment by trask** [comment]
Ah, yes, there shouldn't be any difference whether the `SERVER` span was created by Tomcat instrumentation or Servlet instrumentation.

I was thinking the issue was about reaching up over the controller `INTERNAL` span to get the `SERVER` span.

**Comment by anuraaga** [comment]
> I was thinking the issue was about reaching up over the controller INTERNAL span to get the SERVER span.

Yeah I think that's my main worry - if the root span is Servlet than a servlet filter won't have any INTERNAL spans in the way, if it's spring controller, than Spring API doesn't. It's not as clear for Tomcat (though I do suspect servlet filter should work).

**Comment by trask** [comment]
👍 There shouldn't any difference if it's Tomcat or Servlet instrumentation creating the `SERVER` span. With Tomcat, we just start the `SERVER` span a bit earlier, and end it a bit later.

**Comment by trask** [comment]
@anuraaga can we close as tracked by #1726?
