### ISSUE TITLE
Download latest version link broken with latest release version.

### ISSUE THREAD

**Issue by moosilauke18-reify** [open-telemetry/opentelemetry-java-instrumentation#3028]
**Describe the bug**
Latest release now uses an asset that includes version number in jar. `opentelemetry-javaagent-all.jar` -> `opentelemetry-javaagent-1.2.0-all.jar`. [The link](https://github.com/open-telemetry/opentelemetry-java-instrumentation#getting-started) in the readme `Download the latest version.` now fails.

**Steps to reproduce**
Click the link in Readme.

**What did you expect to see?**
To download jar.

**What did you see instead?**
404 page

**Comment by iNikem** [comment]
@moosilauke18-reify thank you for the report. The link is now fixed.
