### ISSUE TITLE
Replace upload-release-asset GHA

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#3029]
[This GitHub Action](https://github.com/actions/upload-release-asset) is not maintained anymore and we have to replace it with some other

**Comment by anuraaga** [comment]
Does it need to be replaced if it works? :) I've wondered about the security tradeoff of using unmaintained, but GitHub official action vs random third party action.

**Comment by iNikem** [comment]
Apparently it does not work :) #3028

**Comment by trask** [comment]
#3028 was caused by #2995 and my forgetfulness
