### ISSUE TITLE
Does java instrumentation has any plan about collecting log in javaagent

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java-instrumentation#3030]
To be honest, I'm curious about that.

**Comment by trask** [comment]
hey @tydhot! once the OpenTelemetry logging spec / API / exporter are ready we are definitely planning to collect logs in the javaagent.

**Comment by tydhot** [comment]
@trask I got it! thank you!

**Comment by iNikem** [comment]
Question got answered
