### ISSUE TITLE
DataSourceInstrumentationModule's mainInstrumentationName maybe have something wrong

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java-instrumentation#3072]
**Describe the bug**
Today I update the latest code and assemble it. I found my app's instrument failed and the log is like:
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/27889201/119293952-01fe1380-bc86-11eb-8251-52494a6deb44.png">

I found maybe is that code has something wrong.
<img width="826" alt="image" src="https://user-images.githubusercontent.com/27889201/119294009-1cd08800-bc86-11eb-9710-7084042e0933.png">
And I changed the mainInstrumentationName name to 'datasource' and assemble again. The problem is solved.
<img width="779" alt="image" src="https://user-images.githubusercontent.com/27889201/119294088-3ffb3780-bc86-11eb-8608-989a070d832a.png">

**Comment by mateuszrzeszutek** [comment]
That's really strange - the instrumentation name is just a string that isn't really that significant, pretty much the only thing it's used for is enabling/disabling instrumentation.
Maybe it's the reassembling the project that mattered here? Can you switch back to the old version and try to reassemble again?

**Comment by tydhot** [comment]
@mateuszrzeszutek I have renamed it to 'jdbc-datasource' and assemble it. The problem reproduced again. I changed it back to 'datasource'  and it it worked again. I tried three times. Maybe I should try old version and try it? And maybe if I figure out  why the JdbcDataSourceInstrumentationModule would be loaded in log, it will be solved.

**Comment by laurit** [comment]
We don't have a class named `JdbcDataSourceInstrumentationModule` any more. It was renamed to `DataSourceInstrumentationModule` in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3008. Perhaps agent is getting misbuilt for you for some reason? In agent jar check `inst/META-INF/services/io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule` does it contain the renamed module? If so try clean build with `--no-build-cache`.

**Comment by tydhot** [comment]
@laurit Yes. I think 99% is the build cache. Thanks ! @laurit @mateuszrzeszutek
