### ISSUE TITLE
Prometheus exporter not sending HTTP INBOUND request details

### ISSUE THREAD

**Issue by itsprakash84** [open-telemetry/opentelemetry-java-instrumentation#3078]
**Describe the bug**
Prometheus exporter not sending HTTP INBOUND request details
When any spring boot app enables Prometheus, we can see "http_server_requests_seconds_count" will track all inbound traffic request count. but where as if we are using Prometheus exporter it is not exporting.

**Steps to reproduce**

**Agent:**
ENV OTEL_AGENT_JAR_FILE=opentelemetry-javaagent-all.jar
Version 1.0.0

**Configured the below System properties in java opts:**
ENV JAVA_OPTS "${JAVA_OPTS} \
  -Dotel.exporter.jaeger.endpoint=http://tempo:14250 \
  -Dotel.metrics.exporter=prometheus \
  -Dotel.exporter.prometheus.port=9464	\
  -Dotel.exporter.prometheus.host=0.0.0.0 \
  -Dotel.instrumentation.runtime-metrics.enabled=true \
  -Dotel.resource.attributes="service.name=${APP_NAME}" \
  -Dotel.javaagent.debug=false \
  -javaagent:${APP_HOME}/${OTEL_AGENT_JAR_FILE}"

**Docker compose:**
prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - "9464:9090"

**Prometheus yaml**

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9464']
  - job_name: 'app name'
    static_configs:
    - targets: ['app name:8080']

Dependencies:
    <properties>
          <opentelemetry.version>1.0.0</opentelemetry.version>
    </properties>
    <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-api</artifactId>
    </dependency>
    <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-extension-annotations</artifactId>
    </dependency>
</dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.opentelemetry</groupId>
                <artifactId>opentelemetry-bom</artifactId>
                <version>${opentelemetry.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

**What did you expect to see?**
I am seeing other metrics, which is not that useful because we need to track what application performing. 

**What did you see instead?**
I want to all metrics related to application inbound and outbound traffic along with all memory ,system metric.

**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)
1.0.0
**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

openjdk:8-jdk-alpine
ubuntu

**Additional context**
General Spring boot app will have the below entries.
# HELP http_server_requests_seconds  
# TYPE http_server_requests_seconds summary
http_server_requests_seconds_count{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/info",} 1.0
http_server_requests_seconds_sum{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/info",} 0.0584291
http_server_requests_seconds_count{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/metrics",} 6.0
http_server_requests_seconds_sum{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/metrics",} 1.8313241
http_server_requests_seconds_count{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/prometheus",} 1.0
http_server_requests_seconds_sum{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/prometheus",} 0.2046346
http_server_requests_seconds_count{exception="None",method="GET",outcome="CLIENT_ERROR",status="404",uri="/**",} 2.0
http_server_requests_seconds_sum{exception="None",method="GET",outcome="CLIENT_ERROR",status="404",uri="/**",} 0.2330394
# HELP http_server_requests_seconds_max  
# TYPE http_server_requests_seconds_max gauge
http_server_requests_seconds_max{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/info",} 0.0584291
http_server_requests_seconds_max{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/metrics",} 1.6181338
http_server_requests_seconds_max{exception="None",method="GET",outcome="SUCCESS",status="200",uri="/prometheus",} 0.2046346
http_server_requests_seconds_max{exception="None",method="GET",outcome="CLIENT_ERROR",status="404",uri="/**",} 0.189229

**I am looking for  this kind of metrics using opentelemetry**

**Comment by mateuszrzeszutek** [comment]
Hey @itsprakash84,

We haven't implemented the HTTP server metrics yet - it's not incorrect that you're not seeing them, they're not being produced by the javaagent right now. 
Also, once we implement the HTTP server metrics they will differ from the spring boot ones; you can see how they'll look like in the [OpenTelemetry HTTP metrics semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md) spec page.

**Comment by itsprakash84** [comment]
Thank you @mateuszrzeszutek  for responding to my query.

Generally metric means HTTP(Inbound/outbound traffic details), System(CPU,Threads) and JVM and tomcat.

As per you API version 1.0.0 is not supporting any of these metrics.

Then what is the benefit of the current metric which are exported via opentelemetry, please help me in understanding.

**Comment by trask** [comment]
hi @itsprakash84! you can learn more about the OpenTelemetry metrics roadmap here: https://medium.com/opentelemetry/opentelemetry-metrics-roadmap-f4276fd070cf

**Comment by trask** [comment]
Closing, HTTP server metrics are available in the latest 1.6.0 release.
