### ISSUE TITLE
Should we be capturing db.connection_string for Redis?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3080]
I noticed that some redis instrumentation captures `db.connection_string`:

* redisson-3.0
* jedis-1.4
* jedis-3.0
* lettuce-5.1

and some does not:

* lettuce-4.0
* lettuce-5.0
* rediscala-1.8

Where we are capturing it, we are just concatenate host and port (which we capture in `net.peer.*` attributes already) to construct a synthetic connection string (as opposed to capturing some concept of connection string from redis itself).

fwiw, the [redis example in the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#redis) has `not set` for the `db.connection_string` value.

(also fwiw, my initial vote goes toward removing it)

**Comment by mateuszrzeszutek** [comment]
`db.connection_string` probably makes the most sense for JDBC, where it can contain database name, properties, etc. If we have to produce a host:port string by ourselves it's probably better to remove it altogether.
