### ISSUE TITLE
Measure memory impact of the instrumentation

### ISSUE THREAD

**Issue by pmm-sumo** [open-telemetry/opentelemetry-java-instrumentation#312]
It would be great to understand what's the impact of having auto-instr agent on memory consumption. There are two ways this can be approached:

1) Do synthetic test using `jmh` with a memory profiler (e.g. by extending the `benchmark` module)

2) Leverage a sample app (such as PetClinic) - run it inside a container and measure the memory usage

**Comment by trask** [comment]
These both sound great!

I'm thinking `jmh` tests would be good for measuring our effect on memory allocations (memory churn), while PetClinic-type app would be good for measuring our effect on heap size.

**Comment by iNikem** [comment]
Implemented by https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/workflows/nightly-benchmark-overhead.yml
