### ISSUE TITLE
Should ReactorAsyncSpanEndStrategy end the span on cancellation?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3152]
Similar to #3150

cc: @HaloFour

**Comment by HaloFour** [comment]
Oo, good question.  I honestly thought that was picked up by `doOnError` but it apparently isn't.  Should be an easy fix, and likely applies to the RxJava implementations as well.  Question is would a cancelled subscription be considered a successful or failed span?

**Comment by HaloFour** [comment]
See: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3153

**Comment by trask** [comment]
Closed by #3153. Thanks @HaloFour!
