### ISSUE TITLE
Rename FooTracing to FooInstrumentation or FooInstrumenter

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3156]
Now that it's not just tracing we need to rename our library instrumentations. Which name is better? I lean towards `FooInstrumentation` since users don't interact with `Instrumenter`.

**Comment by anuraaga** [comment]
It was sort of nice how we didn't have overlap with naming in the javaagent modules though, where we use `FooInstrumentation` as a `TypeInstrumentation`

**Comment by mateuszrzeszutek** [comment]
> Will be effectively implemented by #2713

Hm, I don't think it will - this issue is about deciding whether to rename the library instrumentation classes e.g. `OkHttpTracing` to `OkHttpInstrumentation`/`OkHttpTelemetry`. It's not directly connected to #2713 (we'd have to rename already existing library classes too)
