### ISSUE TITLE
Option to propagate b3 multi-headers without automatic instrumentation

### ISSUE THREAD

**Issue by Arunkumarlnr** [open-telemetry/opentelemetry-java-instrumentation#3172]
I am using istio as my service mesh. Since istio automatically generates trace and span ids, I don't want opentelemetry java agent to do automatic instrumentation. But I want it to propagate b3 multi-headers.

Is there any configuration just to enable b3 multi-header propagation without instrumentation?

**Comment by trask** [comment]
hi @Arunkumarlnr, I wonder if this configuration might be what you're looking for?

```
OTEL_PROPAGATORS=b3multi
OTEL_TRACES_SAMPLER=always_off
```
