### ISSUE TITLE
otel.metrics.exporter=none does not suppress sending of metrics

### ISSUE THREAD

**Issue by CeeBeeCee** [open-telemetry/opentelemetry-java-instrumentation#3183]
Our OTel collector is not configured to receive metrics yet and we would like the OTel Java agent to not send metrics. We added a property **otel.metrics.exporter** set to **'none**' but we continue to see this error ::

_`[opentelemetry.auto.trace 2021-06-01 01:01:26:968 -0400] [grpc-default-executor-2] ERROR io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics. Server is UNAVAILABLE. Make sure your collector is running and reachable from this network.UNAVAILABLE: io exception`_

We're running v1.2.0 of the java agent. 

Based on this [documentation](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-both-span-and-metric-exporters), 'none' should have suppressed metrics:

_otel.metrics.exporter : The exporter to be used for metrics. Default is otlp. **none** means no autoconfigured exporter._

Here are java opts ::

```
JAVA_OPTS="-javaagent:/target/opentelemetry-javaagent-1.2.0-all.jar
-Dotel.resource.attributes=service.name=myapp
-Dotel.traces.exporter=otlp
-Dotel.metrics.exporter=none
-Dotel.exporter.otlp.endpoint=http://otelcollector"
```

**Comment by jkwatson** [comment]
From looking at the code in the SDK's autoconfigure module, this should definitely be working. Very strange. I'll try to reproduce this later today.

**Comment by CeeBeeCee** [comment]
Thanks John. This used to work a few versions ago. Not sure what changed. I'm flummoxed too.

**Comment by jkwatson** [comment]
This works for me with the 1.2.0 agent.

**Comment by CeeBeeCee** [comment]
Hmm. I dont know what I'm missing. Did you use the env var OTEL_METRICS_EXPORTER or the property otel.metrics.exporter?
Can you post your command line so that I can compare?

**Comment by jkwatson** [comment]
These are my jvm args:  
`-javaagent:otel/opentelemetry-javaagent-all-1.2.0.jar -Dotel.metrics.exporter=none -Dotel.imr.export.interval=5000`

**Comment by CeeBeeCee** [comment]
Then there must be something going on in my docker image. I'll do some more troubleshooting on my side. Closing the issue for now. Thanks John!
