### ISSUE TITLE
Need to map HTTP and gRPC status codes to Span.setStatus()

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#326]
See

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#status

and

https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/rpc.md#status

**Comment by jkwatson** [comment]
Seems like a good chance to do an audit of those mappings and make sure they make sense, as well. Not sure if anyone has actually used them yet.  ;)

**Comment by iNikem** [comment]
If this task is about implementing the straightforward mapping described in spec doc, then I can take it. I don't quite understand what did @jkwatson mean by `audit` though :)

**Comment by trask** [comment]
all yours 😄

**Comment by jkwatson** [comment]
I was just suggesting that if we run across a status that doesn't map well, that would be important feedback for the specs.

**Comment by trask** [comment]
Hoping we can close this soon if span status goes away https://github.com/open-telemetry/oteps/pull/123#issuecomment-656910549

**Comment by anuraaga** [comment]
Technically we could probably close anyways I added that mapping a while ago I think.

**Comment by trask** [comment]
Then closing!
