### ISSUE TITLE
Javaagent interferes with custom log manager on J9 Java 8 JVM

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3322]
Reported in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3316#issuecomment-861568334.

Also need to review the comment below for accuracy:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/c7ac235614b0a1c4bb8431041dab9a8efda9779e/javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/OpenTelemetryAgent.java#L86-L91

**Comment by trask** [comment]
hey @Oberon00! we deleted the problematic comment that you initially report (and the code that went along with it 😁), but we are unsure if we should close this, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3395#issuecomment-867514497. Is there anything you think we should test before closing this issue? thx!

**Comment by Oberon00** [comment]
I posted how to reproduce the issue in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3316#issue-670334046. In the comment you link it was mentioned that Adopt J9 9 was not available, but even though I did not test it, I would assume that the issue is also reproducible on Adopt J9 8.

**Comment by Oberon00** [comment]
Deleting the mentioned code will not fix the issue, as that code was most likely not even invoked. I assume the ManagementFactory is invoked from some ResourceProvider, such as the ProcessResourceProvide, as mentioned here https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3316#issuecomment-861514129

That being said, I do not personally really care about this bug/limitation, so if you want to accept it as-is, I will not complain.
