### ISSUE TITLE
Review RabbitMQ instrumentation's semantic conventions usage

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#3337]
RabbitMQ does not seem to implement messaging semantic conventions correctly, e.g. it uses `testTopic -> testTopic send` instead of `testTopic send` as span names.

**Additional context**
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3295#discussion_r652381304

**Comment by RashmiRam** [comment]
The Producer span names are also not complying with semantic conventions. 

Producer Span names are getting generated as `["<exchange> -> <routing key> send"]` as per this code [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/rabbitmq-2.7/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/rabbitmq/RabbitTracer.java#L120). Cardinality of the routing key can be huge based on individual's use cases. 

[Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#span-name) also says that it should be `<message.destination> <operation name>`. message.destination for RabbitMQ producer span is exchange name only. 

Shouldn't this just be `"<exchange>  send"` similar to how Kafka instrument works?

**Comment by RashmiRam** [comment]
@mateuszrzeszutek If it's alright, Shall I raise a PR to fix this one?

**Comment by mateuszrzeszutek** [comment]
Sure, that'd be great help!
