### ISSUE TITLE
Disable file watching on CI

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3345]
Saw this in a build

`Gradle was unable to watch the file system for changes. The inotify watches limit is too low.`

We probably don't need watching on CI anyways and can't control this limit.

**Comment by trask** [comment]
related: https://discuss.gradle.org/t/watching-the-file-system-at-ci/37241/5

**Comment by iNikem** [comment]
>  it is okay to leave the feature enabled even in this case: there should be no downsides, and we are also planning to enable it by default in Gradle 7.0 anyway

Should we ignore the warning then and close this task?

**Comment by anuraaga** [comment]
I should have linked to the build but probably hit the rerun-all-jobs button. I doubt I would have filed an issue though if it didn't fail the build (not just a warning)
