### ISSUE TITLE
javaagent use Prometheus export requestdata

### ISSUE THREAD

**Issue by EricGreen239** [open-telemetry/opentelemetry-java-instrumentation#3353]
i use javaagent start my app，add vm arguements:
-javaagent:/Users/ericgreen/opentelemetry-javaagent-all.jar 
-Dotel.resource.attributes=service.name=Member 
-Dotel.traces.exporter=jaeger 
-Dotel.exporter.jaeger.endpoint=http://10.223.100.57:14250 
-Dotel.metrics.exporter=prometheus 
-Dotel.exporter.prometheus.port=9093 
-Dotel.exporter.prometheus.host=127.0.0.1

use prometheus as metrics export, but prometheus only collect jvm's metrics, like this:

HELP processedSpans The number of spans processed by the BatchSpanProcessor. [dropped=true if they were dropped due to high throughput]
TYPE processedSpans counter
processedSpans_total{dropped="false",spanProcessorType="BatchSpanProcessor",} 214.0
HELP queueSize The number of spans queued
TYPE queueSize gauge
queueSize{spanProcessorType="BatchSpanProcessor",} 0.0
HELP runtime_jvm_memory_pool Bytes of a given JVM memory pool.
TYPE runtime_jvm_memory_pool gauge
runtime_jvm_memory_pool{pool="Compressed Class Space",type="committed",} 9437184.0
runtime_jvm_memory_pool{pool="Code Cache",type="used",} 2.4160896E7
runtime_jvm_memory_pool{pool="PS Survivor Space",type="max",} 1.9922944E7
runtime_jvm_memory_pool{pool="PS Eden Space",type="committed",} 3.31874304E8
runtime_jvm_memory_pool{pool="Metaspace",type="committed",} 7.1565312E7
runtime_jvm_memory_pool{pool="PS Old Gen",type="used",} 2.390336E7
runtime_jvm_memory_pool{pool="PS Eden Space",type="max",} 1.3893632E9
runtime_jvm_memory_pool{pool="Compressed Class Space",type="used",} 8778816.0
runtime_jvm_memory_pool{pool="PS Eden Space",type="used",} 6.38046E7
runtime_jvm_memory_pool{pool="Compressed Class Space",type="max",} 1.073741824E9
runtime_jvm_memory_pool{pool="PS Survivor Space",type="committed",} 1.9922944E7
runtime_jvm_memory_pool{pool="PS Survivor Space",type="used",} 1.9908792E7
runtime_jvm_memory_pool{pool="PS Old Gen",type="max",} 2.863661056E9
runtime_jvm_memory_pool{pool="Code Cache",type="max",} 2.5165824E8
runtime_jvm_memory_pool{pool="Code Cache",type="committed",} 2.4313856E7
runtime_jvm_memory_pool{pool="Metaspace",type="used",} 6.8346688E7
runtime_jvm_memory_pool{pool="PS Old Gen",type="committed",} 2.4641536E8
HELP runtime_jvm_memory_area Bytes of a given JVM memory area.
TYPE runtime_jvm_memory_area gauge
runtime_jvm_memory_area{area="non_heap",type="committed",} 1.05316352E8
runtime_jvm_memory_area{area="heap",type="committed",} 5.98212608E8
runtime_jvm_memory_area{area="heap",type="max",} 3.817865216E9
runtime_jvm_memory_area{area="non_heap",type="used",} 1.012864E8
runtime_jvm_memory_area{area="heap",type="used",} 1.07616752E8
HELP runtime_jvm_gc_count The number of collections that have occurred for a given JVM garbage collector.
TYPE runtime_jvm_gc_count counter
runtime_jvm_gc_count_total{gc="PS Scavenge",} 12.0
runtime_jvm_gc_count_total{gc="PS MarkSweep",} 3.0
HELP runtime_jvm_gc_time Time spent in a given JVM garbage collector in milliseconds.
TYPE runtime_jvm_gc_time counter
runtime_jvm_gc_time_total{gc="PS Scavenge",} 118.0
runtime_jvm_gc_time_total{gc="PS MarkSweep",} 186.0

There is no excuse to request relevant monitoring data, such as interface QPS, corresponding time, etc. Is it not supported by javaagent to export these data?

**Comment by jkwatson** [comment]
Hello @EricGreen239 . At the moment, the instrumentation has not be written to collect request metrics yet. This will happen in the future, but for now, you only get manually recorded metrics and jvm information.

**Comment by EricGreen239** [comment]
> Hello @EricGreen239 . At the moment, the instrumentation has not be written to collect request metrics yet. This will happen in the future, but for now, you only get manually recorded metrics and jvm information.

 Now If I need to request relevant metrics, can i only capture data through the native opentelemetry SDK and report it to Prometheus?

**Comment by jkwatson** [comment]
When using the agent, you should be able to manually record metrics by using the GlobalMeterProvider to get access to a Meter for recording metrics.

**Comment by EricGreen239** [comment]
> When using the agent, you should be able to manually record metrics by using the GlobalMeterProvider to get access to a Meter for recording metrics.

Thanks for your reply. I understand that it should extend the filter in JavaAgent to record metrics through the GlobalMeterProvider. Can you tell me how to extend the filter of JavaAgent? Or you can give me an example. Thanks again

**Comment by jkwatson** [comment]
> > When using the agent, you should be able to manually record metrics by using the GlobalMeterProvider to get access to a Meter for recording metrics.
> 
> Thanks for your reply. I understand that it should extend the filter in JavaAgent to record metrics through the GlobalMeterProvider. Can you tell me how to extend the filter of JavaAgent? Or you can give me an example. Thanks again

I don't understand the question. what do you mean by "how to extend the filter of the JavaAgent"?

**Comment by EricGreen239** [comment]
> > > When using the agent, you should be able to manually record metrics by using the GlobalMeterProvider to get access to a Meter for recording metrics.
> > 
> > 
> > Thanks for your reply. I understand that it should extend the filter in JavaAgent to record metrics through the GlobalMeterProvider. Can you tell me how to extend the filter of JavaAgent? Or you can give me an example. Thanks again
> 
> I don't understand the question. what do you mean by "how to extend the filter of the JavaAgent"?

So I would like to extend the JavaAgent to collect Recording Metrics based on the GlobalMeterProvider. Is that possible now?

**Comment by jkwatson** [comment]
> So I would like to extend the JavaAgent to collect Recording Metrics based on the GlobalMeterProvider. Is that possible now?

Is your goal to enhance the existing instrumentation to include metrics, or are you interested in manually instrumenting your code to add metrics?

If you just want to manually instrument your code, you can just get a handle to the GlobalMeterProvider and it should interoperate with the SDK that is installed in the agent.

If you want to enhance the existing agent instrumentation, then I'll defer to the maintainers on this project as to the best way to start down that path.

**Comment by EricGreen239** [comment]
> > So I would like to extend the JavaAgent to collect Recording Metrics based on the GlobalMeterProvider. Is that possible now?
> 
> Is your goal to enhance the existing instrumentation to include metrics, or are you interested in manually instrumenting your code to add metrics?
> 
> If you just want to manually instrument your code, you can just get a handle to the GlobalMeterProvider and it should interoperate with the SDK that is installed in the agent.
> 
> If you want to enhance the existing agent instrumentation, then I'll defer to the maintainers on this project as to the best way to start down that path.

hi @jkwatson, OpenTelemetry's JavaAgent is pretty good, but I'd like to add some of my own features to the existing agent instrumentation, like request metrics data. Can you tell me how opentelemetry-javaagent-all.jar is packaged? What is its source project?

**Comment by jkwatson** [comment]
@EricGreen239 This is the source project. Adding instrumentation is definitely non-trivial, but I think there are some pretty good docs in this repository. I think that @anuraaga has added some metrics to the armeria instrumentation, but I'll defer to the maintainers on this project, as I am not an instrumentation expert.

**Comment by EricGreen239** [comment]
@jkwatson Thank you for your patient reply. I will continue to study the source code of instrumentation, and look forward to trying to add some customized services. Thanks again
