### ISSUE TITLE
ClassCastException when using opentelemetry SDK with auto agent

### ISSUE THREAD

**Issue by patsonluk** [open-telemetry/opentelemetry-java-instrumentation#336]
I am experimenting the OT auto agent with OT SDK. My use case is rather simple:

- A simple java job that triggers some HTTP client calls to some services
- Since my java job itself would not be instrumented by the auto-agent, I added dependency to opentelemetry-sdk to start the scope and span
- Since the http client calls are made within the scope, they should get picked up by the auto agent

However, in the beginning of the code, when I tried to obtain the tracer from SDK
```
public static void main(String[] args) throws InterruptedException {
        // Get the tracer
        TracerSdkProvider tracerProvider = OpenTelemetrySdk.getTracerProvider();
...
```

Exception is triggered : 
```
Exception in thread "main" java.lang.ClassCastException: class io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.UnshadedTracerProvider cannot be cast to class io.opentelemetry.sdk.trace.TracerSdkProvider (io.opentelemetry.auto.instrumentation.opentelemetryapi.trace.UnshadedTracerProvider and io.opentelemetry.sdk.trace.TracerSdkProvider are in unnamed module of loader 'app')
```

I am wondering if my usage is legit as in #10 ? Or have I misused the auto agent/sdk? 

Many thanks in advance!

**Comment by trask** [comment]
Hi @patsonluk! Yeah, this is an issue with the current implementation of our bridge that we need to address.

In the meantime, if you use only OpenTelemetry API (and not the SDK), it should work, e.g.

```
TracerProvider tracerProvider = OpenTelemetry.getTracerProvider();
```

**Comment by trask** [comment]
Just documenting that someone else ran into this recently, definitely not a one-off problem: https://gitter.im/open-telemetry/opentelemetry-java-instrumentation?at=5f10ce93ff29b77732087fb3

**Comment by anuraaga** [comment]
@trask Do you think there is any implementation work to do here? On the gitter thread, it sounds like the requester may not have understood that configuring the sampler for the agent would also configure the sampling for their own spans. Not sure what else to do here other than documentation.
