### ISSUE TITLE
Make logger variable name consistent

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3364]
Looks like we currently have LOG, log, logger throughout the codebase. We should make them consistent, suggest `logger`

**Comment by iNikem** [comment]
I prefer shorter names, so suggesting `log` :)

**Comment by trask** [comment]
I'm good with either

**Comment by donbeave** [comment]
Maybe the uppercase `LOG` as it always `private static final`?

**Comment by trask** [comment]
`LOG` doesn't follow [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names), which we (try to) follow in the repo
