### ISSUE TITLE
service-map index NOT getting populated.

### ISSUE THREAD

**Issue by shyam1975** [open-telemetry/opentelemetry-java-instrumentation#3402]
We are using data prepper to process spans from opentelemetry java instrumented application.

So, the flow can be summarized as follows :-
Java Application -> Java Agent-> Otel Collector -> Data Prepper.

We noticed that the following index is never getting populated by Data Prepper when we run the Java Application
otel-v1-apm-service-map

Can you suggest what we need to do to populate the above index?

**Environment**
Compiler: java version "1.8.0_251"
OS: Ubuntu 20.04

**Comment by mateuszrzeszutek** [comment]
Hey @shyam1975 ,
I'm not sure what do you mean by index; the string `otel-v1-apm-service-map` also does not appear in this repo.
Are you sure this is the correct place to report this problem?

**Comment by shyam1975** [comment]
@mateuszrzeszutek , thanks for your feedback. Based on your guidance I think I will reach out to the data prepper team. You may close this issue on your side.

**Comment by mateuszrzeszutek** [comment]
Sure, closing it down then.
Please don't hesitate to open another issue if you find anything wrong or suspicious with the instrumentation.
