### ISSUE TITLE
CloudFoundry buildpack support

### ISSUE THREAD

**Issue by Akshay-Thakare** [open-telemetry/opentelemetry-java-instrumentation#3404]
**Describe the solution you'd like**
Addition of opentelemetry-javaagent  to cloud foundry [java-buildpack](https://github.com/cloudfoundry/java-buildpack) similar to other solutions like dynatarce, datadog, etc.

**Describe alternatives you've considered**
Currently we are explicitly defining the `-javaagent` property in our apps manifest, 
but everytime the opentelemetry-javaagent version is bumped in our pom file all mainfest files need an update.

**Comment by trask** [comment]
@tylerbenson is this done now, e.g. by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9243?

**Comment by tylerbenson** [comment]
The repository is done but there's still an open PR on the buildpack repo to add support.
