### ISSUE TITLE
Cant connect spans on client and service side of RPC connection using opentelemetry-armeria-1.3

### ISSUE THREAD

**Issue by sfc-gh-dschumann** [open-telemetry/opentelemetry-java-instrumentation#3406]
**Describe the bug**
I am using this dependency:

https://search.maven.org/artifact/io.opentelemetry.instrumentation/opentelemetry-armeria-1.3/0.16.0/jar

To decorate my armeria `ClientBuilder` and `ServerBuilder` with the `ArmeriaTracing.newClientDecorator()` and `ArmeriaTracing.newServiceDecorator()`

This has worked well as I can see spans coming in.
But I can't seem to find where the trace ID is extracted on the service side. I.e. I cannot create spans on service side with the trace ID of the client side.
Is that intentional or am I missing something?

I also found a `// TODO(anuraaga): Restore` in `TracingServerInterceptor.java`. Could this feature still be missing?

**Steps to reproduce**

Try to connect a span on service with a span on client side via RPC.

**What did you expect to see?**

I expected spans on client and server side to share the same tracing ID

**What did you see instead?**

They did not share the same tracing ID

**What version are you using?**
1.2.0

**Environment**
Likely not relevant

**Comment by anuraaga** [comment]
Hi @sfc-gh-dschumann - we extract trace ID here through the instrumentation API

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/armeria-1.3/library/src/main/java/io/opentelemetry/instrumentation/armeria/v1_3/OpenTelemetryService.java#L33

We have some unit tests verifying that the client ID is extracted correctly so it should be working in general.

I couldn't find that TODO, which file is that from?

For the `OpenTelemetry` you pass into `ArmeriaTracing.create`, did you set context propagators, e.g. to W3CTraceContextPropagator? By default it doesn't do any propagation.

**Comment by sfc-gh-dschumann** [comment]
I don't think I set a context propagator. How do I do that? Is there any documentation on this? Can I add some documentation if it isn't there?

**Comment by anuraaga** [comment]
I think the closest documentation we have initializes the SDK with the propagator here

https://opentelemetry.io/docs/java/manual_instrumentation/#set-up

**Comment by sfc-gh-dschumann** [comment]
Thanks for the quick response. I checked and see Spans being propagated through the `W3CTraceContextProvider`s extract and inject methods.

Curiously the spans that our tracing client receives have the correct span IDs, but the trace IDs are different. As if they got overwritten somewhere...

**Comment by trask** [comment]
hi @sfc-gh-dschumann, any chance you can provide a repro? that would help us to understand the issue better

**Comment by trask** [comment]
Closing, but please let us know if you are still facing the issue and we'll re-open it!
