### ISSUE TITLE
Rename build files to build.gradle

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3408]
I'd like to propose renaming our build files to the standard Gradle default. After working on the repo and probably the most on Gradle files, I've found no real benefit in navigating among build scripts (IDE brings up the folder names too when jumping around) by having the names but have some trouble with copy-pasting files. I believe last year I checked `github.com/gradle/gradle` and they did actually use the non-default file names in that repo, but now they seem to have changed

https://github.com/gradle/gradle/tree/master/subprojects

This is probably for consistency with the general Gradle ecosystem and I feel following the pattern of gradle/gradle is a good one for us. This logic is a bit massive for what we get of it IMO

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/settings.gradle#L319

**Comment by anuraaga** [comment]
I'll make the change if there's agreement.

**Comment by iNikem** [comment]
So how exactly can I now find/open a specific build file? E.g. we have latest dep test failing for a rabbit module and I want to open the build file for that module.

**Comment by anuraaga** [comment]
I usually use Intellij shift-shift and enter the name of the project which surfaces the folder. Github works similar too when I use the file navigator.
