### ISSUE TITLE
How to instrument a class that injected by HelperInjector?

### ISSUE THREAD

**Issue by zmapleshine** [open-telemetry/opentelemetry-java-instrumentation#3415]
**Describe the bug**

I am trying to define a class , that reads the configuration from the remote configuration center and initializes some static property fields when app run with javaagent.

This class is loaded into the client code using ``HelperInjector`` via the ``AppClassLoader``.

Obviously, the property field is not initialized in the client code, but it has been initialized in agent side.(init by AgentClassloader)

So I define a Instrumentation that intercepts method such as "getConfig()" and returns the configuration information back to the client code.

But the intercepting didn't seem to work, and I noticed that ``HelperInjector`` ended up calling ``defineClass``. Wouldn't that trigger the transform method?

**What did you expect to see?**
I want to use ``HelperInjector`` to still trigger the ``transform`` method.

**What did you see instead?**

The instrumentation defined for the injected class does not work.

**What version are you using?**

v1.2.0

**Environment**

Compiler: JDK 11.0.11
OS: Win10 21H1 / MacOS

**Comment by zmapleshine** [comment]
@mateuszrzeszutek

**Comment by zmapleshine** [comment]
When ``ClassLoader`` invoking native method ：
```java
static native Class<?> defineClass1(ClassLoader loader, String name, byte[] b, int off, int len,
                                        ProtectionDomain pd, String source);
```

the class load hook will be invoke in ``klassFactory.cpp``
```c++
JvmtiExport::post_class_file_load_hook(class_name,
                                           class_loader,
                                           protection_domain,
                                           &ptr,
                                           &end_ptr,
                                           &cached_class_file);
````

This hook will invoke ``transform`` method that located on the InstrumentationImpl class:
```java
// WARNING: the native code knows the name & signature of this method
    private byte[]
    transform(  Module              module,
                ClassLoader         loader,
                String              classname,
                Class<?>            classBeingRedefined,
                ProtectionDomain    protectionDomain,
                byte[]              classfileBuffer,
                boolean             isRetransformer)
...
```

This did not work out as expected.

**Comment by laurit** [comment]
Class transformations are not re-entrant. Meaning that if a class is loaded by a class file transformer while transforming then that class will not be passed to the transformer. You are probably better off passing the final version of bytes to defineClass. If you wish you can try calling defineClass from a new thread, that should get you around reentrancy restriction.

**Comment by zmapleshine** [comment]
> Class transformations are not re-entrant. Meaning that if a class is loaded by a class file transformer while transforming then that class will not be passed to the transformer. You are probably better off passing the final version of bytes to defineClass. If you wish you can try calling defineClass from a new thread, that should get you around reentrancy restriction.

I'm trying to look up this limitation in the JVM source code, and I think it should be in the following logic?
```C++
bool JvmtiExport::post_class_file_load_hook(Symbol* h_name,
                                            Handle class_loader,
                                            Handle h_protection_domain,
                                            unsigned char **data_ptr,
                                            unsigned char **end_ptr,
                                            JvmtiCachedClassFileData **cache_ptr) {
  if (JvmtiEnv::get_phase() < JVMTI_PHASE_PRIMORDIAL) {
    return false;
  }

  JvmtiClassFileLoadHookPoster poster(h_name, class_loader,
                                      h_protection_domain,
                                      data_ptr, end_ptr,
                                      cache_ptr);
  poster.post();
  return poster.has_been_modified();
}

...

 void post_to_env(JvmtiEnv* env, bool caching_needed) {
    if (env->phase() == JVMTI_PHASE_PRIMORDIAL && !env->early_class_hook_env()) {
      return;
    }
...
}
```


Okay, this means that the ``HelperInjector`` cannot trigger the transform action .However, I notice that the INSTANCE field of the ``Config`` class injected into the user's classloader that is already initialized in the ``AgentClassLoader`` phase.

But when a class is injected into the user's classloader via HelperInjector, the field needs to be reinitialized, which is a bit confusing...

Is there another way to initialize the field initial value of the class injected into the user's classloader  ? Using a new thread to execute defineClass may bring  some potential pitfalls...

**Comment by laurit** [comment]
I believe what you want to look at is `transformClassFile` in  https://github.com/openjdk/jdk/blob/master/src/java.instrument/share/native/libinstrument/JPLISAgent.c
Class in `AgentClassLoader` and the one injected by `HelperInjector` are different classes, they just have the same name. You could use `HelperInjector` to inject a class with same name to multiple class loaders, all of them would be different classes. Perhaps it is easier to understand when you consider that you have multiple war files each containing the same common library, each of the applications has its own copy of the common library classes that don't interact with each other.
If you want to use the same class everywhere then instead of using `HelperInjector` you should add it in the agent root so that the class would be loaded by boot loader. You may need to add the package of your class to bootstrap package prefixes to ensure it is visible on class loaders that don't delegate all requests to boot loader.

**Comment by zmapleshine** [comment]
> I believe what you want to look at is `transformClassFile` in https://github.com/openjdk/jdk/blob/master/src/java.instrument/share/native/libinstrument/JPLISAgent.c
> Class in `AgentClassLoader` and the one injected by `HelperInjector` are different classes, they just have the same name. You could use `HelperInjector` to inject a class with same name to multiple class loaders, all of them would be different classes. Perhaps it is easier to understand when you consider that you have multiple war files each containing the same common library, each of the applications has its own copy of the common library classes that don't interact with each other.
> If you want to use the same class everywhere then instead of using `HelperInjector` you should add it in the agent root so that the class would be loaded by boot loader. You may need to add the package of your class to bootstrap package prefixes to ensure it is visible on class loaders that don't delegate all requests to boot loader.

I think I found a solution in the project, but there seems to be a problem.

I found a instrumentation named ``ClassLoaderInstrumentation`` in [https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/internal/internal-class-loader/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/internal/classloader/ClassLoaderInstrumentation.java](url)
 
I use ``BootstrapPackagesProvider``  to declare prefix so that the bootstrap classloader can load it .
But this instrumentation can't executed when a class loaded by ``AgentClassLoader``, so I checked the matching conditions:
```java
public class ClassLoaderInstrumentation implements TypeInstrumentation {

  @Override
  public ElementMatcher<TypeDescription> typeMatcher() {
    // just an optimization to exclude common class loaders that are known to delegate to the
    // bootstrap loader (or happen to _be_ the bootstrap loader)
    return namedNoneOf(
            "java.lang.ClassLoader",
            "com.ibm.oti.vm.BootstrapClassLoader",
            "io.opentelemetry.javaagent.instrumentation.api.AgentClassLoader")
        .and(extendsClass(named("java.lang.ClassLoader")));
  }
...
```

The condition  seems to be wrong ? (In fact,``AgentClassLoader``is located in package ``io.opentelemetry.javaagent.bootstrap``,see   [https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/bootstrap](url)   ) 

So I wrote a custom instrumentation to replace it, setting the matching condition to the following:

```java
    @Override
    public ElementMatcher<TypeDescription> typeMatcher() {
        // just an optimization to exclude common class loaders that are known to delegate to the
        // bootstrap loader (or happen to _be_ the bootstrap loader)
        return named("io.opentelemetry.javaagent.bootstrap.AgentClassLoader");
    }
```

 Add a print statement in advice code:

```java
 public static class LoadClassAdvice {
        @Advice.OnMethodEnter(skipOn = Advice.OnNonDefaultValue.class)
        public static Class<?> onEnter(@Advice.Argument(0) String name) {
            System.out.println("Pre deletage " + name);
...
```

but the instrumentation still doesn't work.

**Comment by zmapleshine** [comment]
In fact, because of ``GlobalIgnoresMatcher``, classes loaded by the AgentClassLoader will never be transformed and there will be ignored.

```java
    if (name.startsWith("io.opentelemetry.javaagent.")) {
      // FIXME: We should remove this once
      // https://github.com/raphw/byte-buddy/issues/558 is fixed
      if (name.equals("io.opentelemetry.javaagent.instrumentation.api.concurrent.RunnableWrapper")
          || name.equals(
              "io.opentelemetry.javaagent.instrumentation.api.concurrent.CallableWrapper")) {
        return false;
      }
      return true;
    }
```

However, I have defined an custom ignore matcher(``IgnoreMatcherProvider``) by SPI that attempts to allow classes transform ( class loaded by ``AgentClassLoader``.),  and then  "intern-class-loader" instrumentation will work.

But, the ``AgenClassLoader`` breaks the "parent delegation" model. The classes that almost need to be loaded by the ``AgentClassLoader``  cannot be loaded by bootstrap ClassLoader .

So this instrumentation's motivation is confused. Maybe just to make sure as much as possible that some classes are loaded using the boot class loader?

**Comment by mateuszrzeszutek** [comment]
Hey @zmapleshine,

Let's go back a bit to your use case, maybe we'll find some other solution.

> I am trying to define a class , that reads the configuration from the remote configuration center and initializes some static property fields when app run with javaagent.

Does your code use the [`Config`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/config/Config.java) class? If so, you might find the [`PropertySource`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/spi/config/PropertySource.java) useful. `PropertySource`s and config initialization are executed in the agent classloader, but the global `Config` instance is kept in the bootstrap CL.

> This class is loaded into the client code using `HelperInjector` via the `AppClassLoader`.
> 
> Obviously, the property field is not initialized in the client code, but it has been initialized in agent side.(init by AgentClassloader)

In such cases we usually keep a global variable in a bootstrap class (see [`InstrumentedTaskClasses`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-api/src/main/java/io/opentelemetry/javaagent/instrumentation/api/internal/InstrumentedTaskClasses.java#L47) for example), but the initialization code happens in the agent ([`AgentInstaller`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/AgentInstaller.java#L182)). This way the global var is usable by all instrumentations.

Would it be possible for you to provide a more detailed explanation of your use case, an example perhaps?
Also, are you developing a custom javaagent distro? Or an extension jar?

**Comment by zmapleshine** [comment]
> Hey @zmapleshine,
> 
> Let's go back a bit to your use case, maybe we'll find some other solution.
> 
> > I am trying to define a class , that reads the configuration from the remote configuration center and initializes some static property fields when app run with javaagent.
> 
> Does your code use the [`Config`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/config/Config.java) class? If so, you might find the [`PropertySource`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/spi/config/PropertySource.java) useful. `PropertySource`s and config initialization are executed in the agent classloader, but the global `Config` instance is kept in the bootstrap CL.
> 
> > This class is loaded into the client code using `HelperInjector` via the `AppClassLoader`.
> > Obviously, the property field is not initialized in the client code, but it has been initialized in agent side.(init by AgentClassloader)
> 
> In such cases we usually keep a global variable in a bootstrap class (see [`InstrumentedTaskClasses`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-api/src/main/java/io/opentelemetry/javaagent/instrumentation/api/internal/InstrumentedTaskClasses.java#L47) for example), but the initialization code happens in the agent ([`AgentInstaller`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/AgentInstaller.java#L182)). This way the global var is usable by all instrumentations.
> 
> Would it be possible for you to provide a more detailed explanation of your use case, an example perhaps?
> Also, are you developing a custom javaagent distro? Or an extension jar?

Yeah, I am developing a custom agent distro.

I have looked at the ``Config`` class and have used ``PropertySource`` to load the custom configuration items.

My idea is that each module, such as "Trace" and "Metrics"...  has its own set of domain-specific configurations, so that each module has its own configuration class and is no longer in contact with the ``Config`` class.

Therefore, in order for these modules to dynamically determine their behavior in the user's CL based on their configuration classes  , it now seems necessary to move the configuration class of these modules to the "javaagent-bootstrap" module so that the bootstrap CL can load them?

**Comment by mateuszrzeszutek** [comment]
> My idea is that each module, such as "Trace" and "Metrics"... has its own set of domain-specific configurations, so that each module has its own configuration class and is no longer in contact with the `Config` class.
> 
> Therefore, in order for these modules to dynamically determine their behavior in the user's CL based on their configuration classes , it now seems necessary to move the configuration class of these modules to the "javaagent-bootstrap" module so that the bootstrap CL can load them?

I see. In that case keeping those domain-specific config classes in the bootstrap CL seems like a good idea. You want those domain config classes to be updated periodically, did I understood that correctly? If so, I guess you could start a thread (or a scheduled task) in the agent CL to get the latest config values and update global instances in the bootstrap CL.

**Comment by zmapleshine** [comment]
> I see. In that case keeping those domain-specific config classes in the bootstrap CL seems like a good idea. You want those domain config classes to be updated periodically, did I understood that correctly? If so, I guess you could start a thread (or a scheduled task) in the agent CL to get the latest config values and update global instances in the bootstrap CL.

Your idea seems to be good, I think I can start a scheduled task to help me do this. Thanks !  : )

**Comment by zmapleshine** [comment]
As for the label of this issue, I do not think it is a "bug", please help to modify it, thank you.
