### ISSUE TITLE
Testing artifact published instead of individual instrumentations jars

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#3422]
If you take a look at the latest published snapshot for e.g. [Apache Camel instrumentation](https://oss.sonatype.org/#nexus-search;gav~io.opentelemetry.javaagent.instrumentation~opentelemetry-javaagent-apache-camel-2.20~~~~kw,versionexpand), you will see that only jar file with extra classifier "-all" is published. And it contains a lot more than jar classes from the corresponding module.

What actually happens is that shadow jar produced by `otel.javaagent-testing` convention is published instead of the actual module jar file. That shadow jar contains extra runtime dependencies of the instrumentation tests for that module.

**Comment by mateuszrzeszutek** [comment]
Fixed by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3493
