### ISSUE TITLE
TraceID compatible with existing systems

### ISSUE THREAD

**Issue by EricGreen239** [open-telemetry/opentelemetry-java-instrumentation#3423]
Our system previously generated traceID itself, which is used by the logging system to view the logs of the same request. Is OpenTelemetry's javaagent compatible with our existing TraceID? Similar to determining if there is a traceId in the request, use the existing traceId instead of generating a new one by javaagent.

**Comment by iNikem** [comment]
This project produces traceId as dictated by [OpenTelemetry Specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spancontext). Thus the answer to your question is most probably "No", unless your generated traceId followed the same rules.

You can try to use [IdGenerator](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/IdGenerator.java) to provide other means of generating or reusing traceIds.

**Comment by EricGreen239** [comment]
thanks
