### ISSUE TITLE
Support for the Micronaut framework?

### ISSUE THREAD

**Issue by bixu** [open-telemetry/opentelemetry-java-instrumentation#3424]
Hi all, has there been consideration of adding support for the Micronaut "cloud-native" framework?

**Comment by mateuszrzeszutek** [comment]
Hey @bixu ,
We probably won't have the capacity to implement this ourselves, but we'll gladly accept external contributions.

**Comment by donbeave** [comment]
Hello, @bixu!

I'm working on `micronaut-opentelemetry` module, which uses some libraries from `opentelemetry-java-instrumentation` project. That's why I'm implementing OpenTelemetry JDBC instrumentation library: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3367, which will allow to use it in GraalVM images.

Please follow this issue regarding the official OpenTelemetry module in Micronaut 3.0: https://github.com/micronaut-projects/micronaut-core/issues/5138.

**Comment by jkwatson** [comment]
> @tkhoiwal the most interesting part of Micronaut is the ability to build the app with GraalVM native image feature. For such use case java agent will not work, that's why I have started to working on `micronaut-opentelemetry` module: https://github.com/expatiat/micronaut-opentelemetry

Just peeked at that repo for a brief moment and it looks like you have duplicated instrumentation for grpc. Any reason why not to just use the grpc library instrumentation maintainer here as a dependency?

**Comment by donbeave** [comment]
The main idea for `micronaut-opentelemetry` is to reuse as much as possible from https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation, that's one of the reasons why I have implemented JDBC instrumentation library: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3367.

**Comment by jkwatson** [comment]
> @jkwatson hm, actually I'm using `io.opentelemetry.instrumentation:opentelemetry-grpc-1.6`. If you check the server and client tracing both using this library:

oh, my apologies, I saw the packages and made assumptions. You're just providing micronaut configuration. 👍🏽

**Comment by tkhoiwal** [comment]
> @tkhoiwal the most interesting part of Micronaut is the ability to build the app with GraalVM native image feature. For such use case java agent will not work, that's why I have started to working on `micronaut-opentelemetry` module: https://github.com/expatiat/micronaut-opentelemetry

Thanks @donbeave for details of the usecase.

**Comment by donbeave** [comment]
Micronaut has added OpenTelemetry support in its `micronaut-tracing` module, it's available as a SNAPSHOT build for now: https://github.com/micronaut-projects/micronaut-tracing/pull/65#issuecomment-1138686717

**Comment by mateuszrzeszutek** [comment]
This one is already done: https://micronaut-projects.github.io/micronaut-tracing/latest/guide/#opentelemetry
