### ISSUE TITLE
Trace ID was not passed correctly in dubbo scenario

### ISSUE THREAD

**Issue by zmapleshine** [open-telemetry/opentelemetry-java-instrumentation#3427]
**Describe the bug**
Trace ID was not passed correctly in dubbo.

**Steps to reproduce**

Start four services（named consumer,service1,service2,provider） that  use Dubbo 2.7.x
Their invocation relationship is as follows：
  
consumer -> service1 -> service2 -> provider.

"consumer service" use dubbo client to invoke the dubbo interface provided by the "service1 service",
and "service1 service" use dubbo client to invoke the dubbo interface provided by the"service2 service",
and "service2 service" use dubbo client to invoke the dubbo interface provided by the "provider service".

**What did you expect to see?**

Trace passes correctly between service invocations.

**What did you see instead?**

Use the Jaeger trace analysis tool to check, found that the "service2 service" span, "provider service" span is also under the "consumer service",like this:

![image](https://user-images.githubusercontent.com/12667610/123757384-82044280-d8f0-11eb-8089-60fba8a1da0d.png)

**What version are you using?**

1.3.1,1.2.0

**Environment**

Compiler: jdk11

OS: MacOS

I seem to have found the root cause of the problem. How can I help fix this problem?

**Comment by mateuszrzeszutek** [comment]
Hey @zmapleshine,

> I seem to have found the root cause of the problem. How can I help fix this problem?

An example that reproduces this issue would be very valuable for us - if you can send us a link to the repo with the setup that you've outlined in the post above that would be great. You can also submit a PR that fixes this issue.
Thanks!

**Comment by zmapleshine** [comment]
> An example that reproduces this issue would be very valuable for us - if you can send us a link to the repo with the setup that you've outlined in the post above that would be great. 

I built a test project to help us test this problem well. 
[https://github.com/zmapleshine/dubbo-invocation-example](url)
The PR that fixes this issue #3442
