### ISSUE TITLE
Remove kafka-streams-0.11 latestDepTest limits

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#3451]
**Describe the bug**
Looks like we're limiting `kafka-streams` version to `2.3+`: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/kafka-streams-0.11/javaagent/build.gradle.kts#L33
It turns out the instrumentation had an issue for 2.6 (#3436), and our latest dep tests completely did not detect that.

When I tried bumping the version the groovy compile task was failing on a missing `KafkaEmbedded` class. We should remove the `KafkaEmbedded` junit rule and use [Kafka testcontainers](https://www.testcontainers.org/modules/kafka/) instead.

**Comment by tylerbenson** [comment]
You can see an alternate fix in my PR here: https://github.com/DataDog/dd-trace-java/pull/2951
(This replaces `KafkaEmbedded` with `EmbeddedKafkaBroker` instead of switching to testcontainers. Not opposed to switching to testcontainers, this was just an easier fix for me.)

**Comment by laurit** [comment]
Resolved in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3803
