### ISSUE TITLE
How to set attribute current span when using httpclient springboot with auto instrumentation

### ISSUE THREAD

**Issue by previousdeveloper** [open-telemetry/opentelemetry-java-instrumentation#3465]
**Describe the bug**
I want to set attribute current span when using resttemplate in springboot but i use auto instrumentation i can't access to http span directly.

**Steps to reproduce**
```yaml
    public String opentelemetryRestService(String url) {
        Span.current().setAttribute("x-operation2", "ops2");
        String body = restTemplate.getForEntity(url, String.class).getBody();
        Span.current().setAttribute("x-operation", "ops1");
        logger.info("Request success to url: " + url);
        return body;
    }
````
**What did you expect to see?**
I want to see the current HTTP span with a new attribute.

**What did you see instead?**
I can't see it.

**What version are you using?**
 `1.2.0`

**Additional context**
I couldn't see here
![Image](https://i.ibb.co/jbBtZmf/Screen-Shot-2021-07-01-at-11-03-30.png)

It seems here
![Image](https://i.ibb.co/QphBRBC/Screen-Shot-2021-07-01-at-11-03-41.png)

**Comment by laurit** [comment]
If you do it this way you'll end up adding attributes to parent of http client span because http client span is created inside `restTemplate.getForEntity` and has already completed (no longer current) when that call exits. You could set the attribute in a `SpanProcessor`.

**Comment by previousdeveloper** [comment]
Thank you for your quick answer.  That's right. How to set unique attributes in a SpanProcessor. All Operations are unique from each other and I need to give some generic point application developer. I think you mean 
```java
public class DemoSpanProcessor implements SpanProcessor {

  @Override
  public void onStart(Context parentContext, ReadWriteSpan span) {
    /*
    The sole purpose of this attribute is to introduce runtime dependency on some external libraries.
    We need this to demonstrate how extensions can use them.
     */
    span.setAttribute("custom", "demo");
  }
```

**Comment by laurit** [comment]
In `SpanProcessor.onStart` you have access to `Context` which you could use to pass the value of the attribute you want to set.

**Comment by trask** [comment]
Closing, but please let us know if you are still facing this issue and we will re-open!
