### ISSUE TITLE
Do we have feature auto-instrumentation for metrics or plan for it?

### ISSUE THREAD

**Issue by haingo-kenshjn** [open-telemetry/opentelemetry-java-instrumentation#3476]
Hi team,

The current auto-instrumentation for tracing look awesome. Do we have feature auto-instrumentation for metrics or plan for it?
Appreciate if you could kindly assist on this.

Thanks,
Hai Ngo,

**Comment by iNikem** [comment]
When Metric API and SDK start stabilising we certainly are going to consider what metric we can collect automatically. All ideas are welcomed!
