### ISSUE TITLE
Akka http server span names are always `akka.request`

### ISSUE THREAD

**Issue by mattypb** [open-telemetry/opentelemetry-java-instrumentation#3478]
**Describe the bug**
I've added the Open Telemetry java instrumentation to a Scala Akka service. Traces are created when the service's api's are hit, but no matter which api is hit they all have a span name of `akka.request`.

Looking at the Akka http server instrumentation, this is appears to be the current expected behaviour - [AkkaHttpServerInstrumentationTest](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/akka-http-10.0/javaagent/src/test/groovy/AkkaHttpServerInstrumentationTest.groovy#L24). However some other java instrumentations use the api path as the span name, for example Tomcat 7.0 - [TomcatHandlerTest](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/tomcat/tomcat-7.0/javaagent/src/test/groovy/io/opentelemetry/javaagent/instrumentation/tomcat/v7_0/TomcatHandlerTest.groovy#L35-L40).

Why does the Akka server instrumentation have `akka.request` hard coded for the span name instead of using the api path? Will this change in the future?

**What did you expect to see?**
Hitting an api on my service, e.g. `GET /v1/{user}`, would generate a trace with span name `/v1/{user}`

**What did you see instead?**
Span name of `akka.request`

**What version are you using?**
1.3.0

**Environment**
Scala: 2.13.5
Akka-Http: 10.2.4
Compiler: AdoptOpenJDK 11.0.10
OS: Mac 10.15.7
Runtime (if different from JDK above): Oracle  11.0.11+9-LTS-194
OS (if different from OS compiled on): RHEL 7.1

**Comment by nibhuran** [comment]
@mattypb , @trask Can I take a crack at this issue.

**Comment by trask** [comment]
> Can I take a crack at this issue.

sure!

**Comment by mcmho** [comment]
@trask, I am looking into this a bit.  Does it make sense to add a SpanNameExtractor for this case and pass it to the Instrumenter?

**Comment by trask** [comment]
> @trask, I am looking into this a bit. Does it make sense to add a SpanNameExtractor for this case and pass it to the Instrumenter?

yes, that makes sense 👍

**Comment by mcmho** [comment]
@trask, @mateuszrzeszutek,   I see that there are many span name extractors having null implementation for route().   
```
  @Override
  @Nullable
  protected String route(Request request) {
    return null;
  }
```

I realized that it is hard to get the right span name with low cardinality with just the Request object. 
Do you have any advice on that?  
  

In our company's product, we provide configuration where customers can specify their own custom rule to name a span.  
or we provide a default... say for example, the servlet  or http case, we use the first two segments of the URI. 
so an uri like this one:  http://localhost:11001/foo/bar/baz?id=66
the span name would be /foo/bar 

I am wondering if that would be sufficient.   On the other hand, I understand that 
the second segment can potentially be an id.  in that case, we will end up with high cardinality.   

Does it make sense to parse the second segment skip it if it is a purely digit?

**Comment by mcmho** [comment]
Thanks @trask!   I did look into the Route concept.  As far as I understand, Route is the static configuration logic rather the runtime request route.  It seems to be used for constructing a mapping to route request to the handling logic.   i.e:  https://developer.lightbend.com/guides/akka-http-quickstart-java/http-server.html
I can't find a way to get Route from HttpRequest. 

My approach is to inspect the path in the request and come up with a span name with low cardinality.

**Comment by trask** [comment]
> My approach is to inspect the path in the request and come up with a span name with low cardinality.

limiting the path to two segments doesn't guarantee low-cardinality, which is a requirement for span name

**Comment by mcmho** [comment]
@trask ,   I understand that the second segment can potentially be an id. in that case, we will end up with a span name that has high cardinality.

Does it make sense to parse the second segment skip it if it is a purely digit?

**Comment by trask** [comment]
I think that if we can't capture the real akka route that we should probably stick to capturing just `HTTP {method}` in the akka instrumentation itself

**Comment by mcmho** [comment]
Okay, I will do HTTP GET,  HTTP POST, ... etc for now.  

Wouldn't it be great if we can allow some sort of customization rules in the collector to post process span names, 
such that users can name their span  say /foo/10,  /foo/11,  as /foo
or /bar/111,  /bar/123 as /bar.

**Comment by mcmho** [comment]
@trask,    what about doing something like this:
/foo/10, /foo/11,  become /foo/{id}
/bar/111, /bar/123  become /bar/{id}

Or do you just want to stick with  HTTP {method}?

**Comment by trask** [comment]
> @trask, what about doing something like this: /foo/10, /foo/11, become /foo/{id} /bar/111, /bar/123 become /bar/{id}

this is hard to do reliably, as not all parameterized path elements have to be numeric (e.g. guid, username, ...)

i think this would be a useful feature to build out separately as a span processor that can apply to all spans, and users can opt into it, and can customize it to their needs. we probably don't have a rich enough configuration model to support this in the agent yet, but in the meantime this could be added in contrib and configured programmatically similar to [RuleBasedRoutingSampler](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/samplers/src/main/java/io/opentelemetry/contrib/samplers/RuleBasedRoutingSampler.java)

**Comment by mcmho** [comment]
Okay, sure @trask.   We'll stick with HTTP {method} for this ticket.

And let me take a look at RuleBaseRoutingSampler and create a separate ticket for it.
