### ISSUE TITLE
Spring WebMVC spanName is contant

### ISSUE THREAD

**Issue by gquintana** [open-telemetry/opentelemetry-java-instrumentation#3479]
**Is your feature request related to a problem? Please describe.**
`WebMvcTracingFilter` always set spanName as `WebMVCTracingFilter.doFilterInternal` no matter what the HTTP endpoint is.

See the code https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-webmvc-3.1/library/src/main/java/io/opentelemetry/instrumentation/spring/webmvc/WebMvcTracingFilter.java#L33

**Describe the solution you'd like**
I would expect the `spanName` (which is then called `operationName` in Jaeger) which always contains the same value `WebMVCTracingFilter.doFilterInternal` to have distinct values for example `GET /foo`, `POST /bar` to be able to tell them appart  in  the Jaeger UI.

The HTTP method, path, status, etc. could also be added to the Span tags.

**Describe alternatives you've considered**
I tried adding an annotation `@WithSpan("http-get-foo")` it creates an internal span which is better that nothing. But still the WebMVCTracingFilter span is useless.

**Comment by iNikem** [comment]
Do you use javaagent or just library instrumentation that you referenced?

**Comment by gquintana** [comment]
@iNikem Just the libraries `opentelemetry-spring-starter` and `opentelemetry-exporter-jaeger`

**Comment by mateuszrzeszutek** [comment]
We could try implementing the following idea: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4258#discussion_r720087815
By implementing the `ApplicationListener<ContextRefreshedEvent>` and retrieving the `DispatcherServlet` from the context (and using a bit of reflection) we should be able to retrieve the set of handler mappings needed to determine `http.route`.

**Comment by ZawadaZSE** [comment]
Hey,

I'd be also interested in getting this done. Spans named with current library implementation are not easily browsable in jaeger.

**Comment by reactivejson** [comment]
We're also interested to have this functionality for better tracing visibility.
