### ISSUE TITLE
Spring Boot Starter service-name is constant 

### ISSUE THREAD

**Issue by gquintana** [open-telemetry/opentelemetry-java-instrumentation#3480]
**Is your feature request related to a problem? Please describe.**
I added the `opentelemetry-spring-starter` and `opentelemetry-exporter-jaeger` to 2 Spring Boot applications. The OpenTelemetry instrumentation always set `serviceName` as `unknown_service:java`. I am not able to tell which span belongs to which application.

These values are the default ones https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/common/src/main/java/io/opentelemetry/sdk/resources/Resource.java#L50

**Describe the solution you'd like**
Use Spring Boot `application.name` setting as service name

**Describe alternatives you've considered**
Be able to override from from `application.properties` file with something like `otel.resource.attributes=service.name=myapp-backend`. This would be the equivalent of `-Dotel.resource.attributes=service.name=myapp-backend` when running as a Java agent. Or even better  `otel.resource.attributes.service.name=myapp-backend`

**Comment by AlexWang-CN** [comment]
I have the same problem

**Comment by jkwatson** [comment]
it might be nice to support a pattern-based resource configuration in the application.properties like this:

```
otel.resource.attributes.environment=dev
otel.resource.attributes.xyz=foo
```

**Comment by aschugunov** [comment]
Are there any updates, plans?

**Comment by oceanstars** [comment]
```yaml
otel:
  springboot:
    resource:
      attributes:
        service.name: my_service_name
```

This configuration in "application. yaml" is valid for setting service name.
