### ISSUE TITLE
Sleuth-Otel Autoconfigure fails to provide tracing with Logback's appenders.

### ISSUE THREAD

**Issue by anunpn** [open-telemetry/opentelemetry-java-instrumentation#3485]
### Discussed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/3482

<div type='discussions-op-text'>

<sup>Originally posted by **anunpn** July  2, 2021</sup>
Hi All, 
I am using sleuth with otel for a spring boot application. The traceID and spanIDs are logged when there is no "appender" section in my logback.xml or when logback.xml is not in classpath. With "appender" in logback, the tracing information is gone. PFB the relevant section of my pom.xml

org.springframework.bootspring-boot-starter-parent--> 2.4.6

<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            
            <version>2020.0.3</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-otel-dependencies</artifactId>
            
            <version>1.0.0-M8</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>

    </dependency>
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-starter-sleuth</artifactId>
        <exclusions>
            
            <exclusion>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-sleuth-brave</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
    
    <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-sleuth-otel-autoconfigure</artifactId>
    </dependency>

</dependencies>

Please let me know what I am missing here.</div>

**Comment by jkwatson** [comment]
Can you post your logback.xml as well?

**Comment by anunpn** [comment]
> Can you post your logback.xml as well?

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} trace_id=%X{trace_id} span_id=%X{span_id} trace_flags=%X{trace_flags} %msg%n</pattern>
    </encoder>
  </appender>

 
  <appender name="OTEL" class="io.opentelemetry.instrumentation.logback.v1_0.OpenTelemetryAppender">
    <appender-ref ref="CONSOLE"/>
  </appender>
 
 <root level="INFO">
    <appender-ref ref="CONSOLE" />
  </root>
</configuration>

**Comment by anunpn** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} trace_id=%X{trace_id} span_id=%X{span_id} trace_flags=%X{trace_flags} %msg%n</pattern>
    </encoder>
  </appender>

  
  <appender name="OTEL" class="io.opentelemetry.instrumentation.logback.v1_0.OpenTelemetryAppender">
    <appender-ref ref="CONSOLE"/>
  </appender>
 
 <root level="INFO">
    <appender-ref ref="CONSOLE" />
  </root>
</configuration>`

**Comment by anunpn** [comment]
<img width="949" alt="Screenshot 2021-07-04 at 6 32 10 PM" src="https://user-images.githubusercontent.com/12458033/124386085-2a057b80-dcf6-11eb-909a-c482f2ace369.png">
@jkwatson

**Comment by mateuszrzeszutek** [comment]
Hey @anunpn ,

Are you using the OTel javaagent together with spring-sleuth?
Also, I can see that you're using the `opentelemetry-logback-1.0` library instrumentation - which version are you using?

**Comment by trask** [comment]
Closing, but please let us know if you are still facing this issue and we will re-open!
