### ISSUE TITLE
Rename javaagent-api artifact to javaagent-instrumentation-api

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3488]
I don't remember where, but I believe this was proposed by @mateuszrzeszutek, and I think is a good idea, in order to help with the confusion between

* javaagent-extension-api
* javaagent-advice-api ("runtime" api used by advice, lives in bootstrap class loader)

EDIT see discussion below preferring `javaagent-instrumentation-api` over `javaagent-advice-api`

**Comment by iNikem** [comment]
Not sure that every reader will immediately understand what "advice" are we talking about 🤔

**Comment by trask** [comment]
Some alternatives to `javaagent-advice-api`:
* javaagent-bootstrap-api
* javaagent-runtime-api
* javaagent-instrumentation-api

**Comment by iNikem** [comment]
I like `javaagent-runtime-api` if we think that this is better than current `javaagent-api`. Or may be this is indeed `javaagent-instrumentation-api`...

**Comment by mateuszrzeszutek** [comment]
Hmm, I'm leaning towards `javaagent-instrumentation-api` - these classes are supposed to be used inside javaagent instrumentations after all.
I don't think that the information that these classes will be loaded by the bootstrap CL is something that needs to appear in the module name; and I'm not sure what does "runtime" refer to. `javaagent-instrumentation-api` seems to be the best out of these  options
