### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/instrumentation/api/caching/Cache after switch to use the latest snapshot

### ISSUE THREAD

**Issue by donbeave** [open-telemetry/opentelemetry-java-instrumentation#3498]
**Describe the bug**
I started to get an error `Caused by: java.lang.NoClassDefFoundError: io/opentelemetry/instrumentation/api/caching/Cache` after switching to use snapshot version of `opentelemetry-java-instrumentation` from Sonatype. It works well with the forked version, where I have implemented JDBC instrumentation: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3367.
Originally I thought about the problem with the dependencies, but found that my application already includes all required libraries and I even can see instrumentation-caching library in the Gradle report:

```
|    +--- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api:1.4.0-alpha-SNAPSHOT
|    |    +--- io.opentelemetry:opentelemetry-api-metrics:1.3.0-alpha (*)
|    |    +--- org.slf4j:slf4j-api:1.7.30
|    |    +--- io.opentelemetry.instrumentation:opentelemetry-instrumentation-api-caching:1.4.0-alpha-SNAPSHOT
```

But for some unknown reason classes from this dependency are not included in the classpath or not visible. I found that the problem started from this commit: https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/d53e62b4dcd2ffcce9b7fee0ea8f4539b7b55e53. And everything works perfectly with the previous commit: https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/47c8a9bfa56d77934df75ba1aaff2d47992db783. Probably @anuraaga you can help to find the reason why.

I have tried to compare Maven pom files for this dependency and looks like the previous version doesn't have `<packaging>pom</packaging>` attribute:

1) old pom version:

![old](https://user-images.githubusercontent.com/139017/124496198-b34aaa00-ddeb-11eb-81f2-e0a4667dab50.png)

2) new pom version:

![new](https://user-images.githubusercontent.com/139017/124496238-bf366c00-ddeb-11eb-9688-7c492b360044.png)

But seems it's probably not the reason why it's failed.

The problem only actually for this particular package, I have tried to resolve classes from `opentelemetry-instrumentation-api`, it works.

**Steps to reproduce**

I have added a project to reproduce this error: https://github.com/donbeave/opentelemetry-java-instrumentation-cache-class-not-found-error

Please check the CI build log: https://github.com/donbeave/opentelemetry-java-instrumentation-cache-class-not-found-error/runs/2991829149

The `test1` task is a success because it's using a class from the `opentelemetry-instrumentation-api` library, but `test2` task failed because it's using a class from the `opentelemetry-instrumentation-api-caching` library.

But if uncomment `mavenLocal()` in `build.gradle.kts` files and publish to Maven local this commit: https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/47c8a9bfa56d77934df75ba1aaff2d47992db783, everything will compile successfully.

**What version are you using?**
`1.4.0-alpha-SNAPSHOT`

**Comment by trask** [comment]
hey @donbeave! I ran into similar problem, check out #3471, we've been struggling with gradle shadow configuration, I'm going to update that PR today to follow @anuraaga's new shadow pattern from https://github.com/open-telemetry/opentelemetry-java/pull/3371
