### ISSUE TITLE
Fix deprecated features in Gradle build scripts

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#351]
Current gradle build scripts use a lot of deprecated features, that are expected to stop working in gradle's next major version. We should fix them.

**Comment by iNikem** [comment]
I have tried to do this and failed :) I am not sure this is very good candidate for `good firs issue`. It requires the understanding of generated gradle tasks. And choosing between `api` and `implementation` may require understanding the purpose of gradle submodules. Which is not documented at.

**Comment by trask** [comment]
Thanks for giving it a shot, and for your assessment! I will remove the `good first issue` tag.

**Comment by trask** [comment]
Mostly done, see #643, #653, #659, and some other earlier PRs too.

@iNikem @anuraaga do you want to keep this open? Once we remove all deprecated features, can we enable some kind of flag to fail the build if any creep back?

**Comment by iNikem** [comment]
Yes and yes

**Comment by vovencij** [comment]
Some are fixed here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2085 

At the moment of writing I think there is only one Gradle deprecation warning left.
