### ISSUE TITLE
Should library instrumentation support environment variable configuration?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3560]
In particular, should they support `OTEL_INSTRUMENTATION_COMMON_PEER_SERVICE_MAPPING`?

This issue was raised by @jkwatson in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3538#discussion_r668212804, and @tedsuo mentioned in today's spec meeting that the prior experience in OpenTracing was that operators wanted these kinds of knobs for library instrumentation.

Another configuration option that we may want to similarly consider (though doesn't even exist in auto-instrumentation yet) is what http status codes to map to error.

As @jkwatson mentions, these things may not be well-understood by the developer when they hook up the library instrumentation, and so it may fall on the operator to configure.

**Comment by jkwatson** [comment]
I think I'd prefer some clearly documented programmatic configuration, rather than based on an env var.

**Comment by anuraaga** [comment]
The mapping from peer name to peer service is frustrating enough to maintain, just haven't come up with a better solution for agent. A documented programmatic configuration is indeed going to be much better for this knob.

**Comment by trask** [comment]
I misunderstood @jkwatson's prior comments, it doesn't sound like there is any disagreement on the path forward for now, so will close this.
