### ISSUE TITLE
How do I build opentelemetry-java-instrumentation with Maven

### ISSUE THREAD

**Issue by EricGreen239** [open-telemetry/opentelemetry-java-instrumentation#3564]
I have been using Maven for project management before and have never come into contact with Gradle. Can the source code of Openelemetry - Java - Instrumentation be built with Maven? This can reduce the learning cost and make it easier to start.

**Comment by iNikem** [comment]
Very unlikely to happen. We have no intention to switch our build system and even if somebody wishes to contribute such work having two build system at once brings only pain and very little benefit.
