### ISSUE TITLE
`NoopContextStorageProvider` side-effect

### ISSUE THREAD

**Issue by Enkelian** [open-telemetry/opentelemetry-java-instrumentation#3566]
Adding gradle dependency on `io.opentelemetry:opentelemetry-extension-noop-api` in `javaagent-tooling` module (refer to #3539)  results in an unwanted side-effect - `NoopContextStorageProvider` gets picked up by SPI and is used instead of the default provider in every agent configuration.

Currently, this problem is solved by using `System.setProperty("io.opentelemetry.context.contextStorageProvider", "default")` in `OpentelemetryInstaller`. This line should be reconsidered once noop API provides sufficient configuration.

**Comment by mateuszrzeszutek** [comment]
@anuraaga or @jkwatson can you move this issue to opentelemetry-java?

Also, quoting my idea:

> `NoopContextStorageProvider` is an SPI implementation that automatically gets picked up whenever it's on classpath - that makes perfect sense when you use the library in your app, but for the agent it looks like an unintented effect.
> Just thinking out loud: maybe something like `otel.java.disabled.context.storage.providers`?

**Comment by jkwatson** [comment]
> @anuraaga or @jkwatson can you move this issue to opentelemetry-java?
> 
> Also, quoting my idea:
> 
> > `NoopContextStorageProvider` is an SPI implementation that automatically gets picked up whenever it's on classpath - that makes perfect sense when you use the library in your app, but for the agent it looks like an unintented effect.
> > Just thinking out loud: maybe something like `otel.java.disabled.context.storage.providers`?

I'm not sure why the current system property isn't sufficient for this? I don't think you'd ever want to specify more than one storage provider, or include more than one in your SPI classpath, so it seems strange to not just have the existing system property to specifically pick out the one you want.

**Comment by trask** [comment]
@laurit @Enkelian thanks for delving into this! we discussed (at length 😭) in SIG yesterday and agreed that current system property approach is a reasonable compromise
