### ISSUE TITLE
opentelemetry-exporter-jaeger not found on classpath.

### ISSUE THREAD

**Issue by chengtangzheng2021** [open-telemetry/opentelemetry-java-instrumentation#3577]
**Describe the bug**

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
Jaeger gRPC Exporter enabled but opentelemetry-exporter-jaeger not found on classpath. Make sure to add it as a dependency to enable this feature.
	at io.opentelemetry.sdk.autoconfigure.ClasspathUtil.checkClassExists(ClasspathUtil.java:15)

**What version and what artifacts are you using?**
javaagent 1.3

**Environment**
java 8

**Additional context**

**Comment by laurit** [comment]
Please reopen if switching to `-all` version of javaagent did not help.
