### ISSUE TITLE
Gradle plugin naming

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3596]
Should we rename these gradle plugins to be consistent with how we separate artifacts between `io.opentelemetry.instrumentation` and `io.opentelemetry.javaagent`? e.g.

* `io.opentelemetry.instrumentation.javaagent-codegen.gradle.kts` -> `io.opentelemetry.javaagent.codegen.gradle.kts`
* `io.opentelemetry.instrumentation.javaagent-instrumentation.gradle.kts` -> `io.opentelemetry.javaagent.instrumentation.gradle.kts`
* `io.opentelemetry.instrumentation.javaagent-shadowing.gradle.kts` -> `io.opentelemetry.javaagent.shadowing.gradle.kts`
* `io.opentelemetry.instrumentation.javaagent-testing.gradle.kts` -> `io.opentelemetry.javaagent.testing.gradle.kts`
* `io.opentelemetry.instrumentation.library-instrumentation.gradle.kts` -> `io.opentelemetry.instrumentation.gradle.kts` or `io.opentelemetry.instrumentation.library.gradle.kts`(?)
* `io.opentelemetry.instrumentation.muzzle-check.gradle.kts` -> `io.opentelemetry.javaagent.muzzle-check.gradle.kts`

Or should we keep the above as-is and just "consistently" put all gradle plugins under `io.opentelemetry.instrumentation`? (and so revert #3592)

**Comment by iNikem** [comment]
@trask Can this be closed after today SIG meeting?

**Comment by trask** [comment]
👍

For other, we decided to put all gradle plugins under the `io.opentelemetry.instrumentation` namespace, primarily because there are only two main gradle plugins, and we like these names for them:
* io.opentelemetry.instrumentation.library-instrumentation.gradle
* io.opentelemetry.instrumentation.javaagent-instrumentation.gradle
