### ISSUE TITLE
Failed to export metrics to Jaeger  with IO exception when using v1.3.1

### ISSUE THREAD

**Issue by nikitsenka** [open-telemetry/opentelemetry-java-instrumentation#3601]
**Describe the bug**
Failed to export metrics to Jaeger  with IO exception when using v1.3.1

**Steps to reproduce**
Please use example on my GitHub https://github.com/nikitsenka/opentelemetry-jaeger-example

**What did you expect to see?**
I expect to see the same behaviour as with version 0.14.0. Trace info successfully sent to Jaeger

**What did you see instead?**
Error in logs and no trace info in Jaeger
```
opentelemetry-app-a_1  | [otel.javaagent 2021-07-16 11:35:23:365 +0000] [grpc-default-executor-2] ERROR io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter - Failed to export metrics. Server is UNAVAILABLE. Make sure your collector is running and reachable from this network.UNAVAILABLE: io exception
```

**What version are you using?**
all versions starting from 0.15.0 to 1.3.1 have the issue

**Environment**
Compiler: OpenJDK Runtime Environment Zulu14.29+23-CA (build 14.0.2+12)
OS: Darwin APRZJGH6D5D58F 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64
Runtime (if different from JDK above): openjdk:11-jre

**Comment by laurit** [comment]
See https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md
System properties used to configure exporters were changed a while ago.

**Comment by laurit** [comment]
Please reopen if changing system properties didn't help.

**Comment by BondarenkoIlya** [comment]
I have exactly the same problem. @nikitsenka 's example looks valid

**Comment by iNikem** [comment]
@BondarenkoIlya Example uses `otel.exporter`: https://github.com/nikitsenka/opentelemetry-jaeger-example/blob/e3548a694169bb749d98f77643d92840b6db3815/Dockerfile#L5

The correct property name is `otel.metrics.exporter`: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#exporters

**Comment by nikitsenka** [comment]
Updated properties, but unfortunately it doesn't help
https://github.com/nikitsenka/opentelemetry-jaeger-example/commit/6a189fc32d3a1ecaf2e5f32d7881bfb46dbdd70e

**Comment by iNikem** [comment]
> Updated properties, but unfortunately it doesn't help
> [nikitsenka/opentelemetry-jaeger-example@6a189fc](https://github.com/nikitsenka/opentelemetry-jaeger-example/commit/6a189fc32d3a1ecaf2e5f32d7881bfb46dbdd70e)

You want to export metrics, right? So please use `otel.metrics.exporter` instead of `otel.traces.exporter`

**Comment by nikitsenka** [comment]
Actually I need traces, sorry for the misspelling

**Comment by iNikem** [comment]
If you need tracers, then `Failed to export metrics` warning is irrelevant to you, right? Do you have metrics receiver configured? If not, put `otel.metrics.exporter=none`.

**Comment by nikitsenka** [comment]
Unfortunately it doesn't help, I still can't get traces collected in Jaeger

**Comment by iNikem** [comment]
Are there any other relevant logs? The one in the original description is about metrics and is irrelevant for your traces problem.

**Comment by iNikem** [comment]
I tried to run your example. It gave me the error which explains exactly what is wrong:

```
ERROR io.opentelemetry.javaagent.OpenTelemetryAgent
opentelemetry-app-a_1  | java.lang.reflect.InvocationTargetException
opentelemetry-app-a_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
opentelemetry-app-a_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
opentelemetry-app-a_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
opentelemetry-app-a_1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
opentelemetry-app-a_1  | 	at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:40)
opentelemetry-app-a_1  | 	at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:56)
opentelemetry-app-a_1  | 	at io.opentelemetry.javaagent.OpenTelemetryAgent.premain(OpenTelemetryAgent.java:50)
opentelemetry-app-a_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
opentelemetry-app-a_1  | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
opentelemetry-app-a_1  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
opentelemetry-app-a_1  | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
opentelemetry-app-a_1  | 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
opentelemetry-app-a_1  | 	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
opentelemetry-app-a_1  | Caused by: java.lang.IllegalArgumentException: Invalid endpoint, must start with http:// or https://: jaeger:14250
opentelemetry-app-a_1  | 	at io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder.setEndpoint(JaegerGrpcSpanExporterBuilder.java:57)
opentelemetry-app-a_1  | 	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureJaeger(SpanExporterConfiguration.java:115)
opentelemetry-app-a_1  | 	at io.opentelemetry.sdk.autoconfigure.SpanExporterConfiguration.configureExporter(SpanExporterConfiguration.java:45)
opentelemetry-app-a_1  | 	at io.opentelemetry.sdk.autoconfigure.TracerProviderConfiguration.configureTracerProvider(TracerProviderConfiguration.java:51)
opentelemetry-app-a_1  | 	at io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.initialize(OpenTelemetrySdkAutoConfiguration.java:47)
opentelemetry-app-a_1  | 	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.installAgentTracer(OpenTelemetryInstaller.java:39)
opentelemetry-app-a_1  | 	at io.opentelemetry.javaagent.tooling.OpenTelemetryInstaller.beforeAgent(OpenTelemetryInstaller.java:26)
opentelemetry-app-a_1  | 	at io.opentelemetry.javaagent.tooling.AgentInstaller.runBeforeAgentListeners(AgentInstaller.java:171)
opentelemetry-app-a_1  | 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:114)
opentelemetry-app-a_1  | 	at io.opentelemetry.javaagent.tooling.AgentInstaller.installBytebuddyAgent(AgentInstaller.java:97)
```

After changing it to `-Dotel.exporter.jaeger.endpoint=http://jaeger:14250`, I got traces into Jaeger.

**Comment by nikitsenka** [comment]
Yes it works now, thank you
