### ISSUE TITLE
Rename or move jws-1.1 module

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3609]
Looking at published artifacts, this one seems confusing:

```
opentelemetry-javaagent-jaxws-2.0/
opentelemetry-javaagent-jaxws-2.0-axis2-1.6/
opentelemetry-javaagent-jaxws-2.0-cxf-3.0/
opentelemetry-javaagent-jaxws-2.0-metro-2.2/
opentelemetry-javaagent-jws-1.1/
```

but in our repository structure it's under `jaxws` folder:

```
jaxws/
  jaxws-2.0/
  jaxws-2.0-axis2-1.6/
  jaxws-2.0-cxf-3.0/
  jaxws-2.0-metro-2.2/
  jws-1.1/
```

I think we should either:
* Rename `jws-1.1` to `jaxws-jws-api-1.1`, or
* Move `jws-1.1` to top-level as `jws-api-1.1` (outside of `jaxws` folder)

Based on my googling, it seems that `jws-api` is not technically part of `jaxws`, but is used by `jaxws`, so it's confusing, but seems maybe more technically correct for it to be its own top-level instrumentation directory.

cc: @vovencij

**Comment by laurit** [comment]
I believe that `jws` can be viewed as a part of `jax-ws`. Nobody talks about `jws` webservices, it is always `jax-ws`. Afaik  `jws` annotations are not used outside of `jax-ws`. https://github.com/eclipse-ee4j/jws-api also states that This project is part of Jakarta XML Web Services project. I'd keep it under `jaxws`, renaming to `jaxws-jws-api-1.1` is fine.

**Comment by vovencij** [comment]
I also support just renaming the to `jaxws-jws-api-1.1`. As far as I understand `jws` is just a set of annotations, which happen to be used only by `jax-ws`.
