### ISSUE TITLE
:instrumentation:vaadin-14.2:javaagent:spotlessKotlin very slow

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3622]
I know @iNikem added an exclude for kotlin spotless but seems it might still need some tweaking since we'd expect spotlessKotlin to be very fast on vaadin project.

**Comment by laurit** [comment]
In `otel.spotless-conventions.gradle.kts` removing `"build/**"` from `targetExclude` seems to fix this.
