### ISSUE TITLE
Unable to use composite build

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#3626]
Currently it is impossible to include this repo into a composite build from another project. The reason is that this project's modules declare e.g. the following name in its metadata: `io.opentelemetry.javaagent:javaagent:1.4.0-SNAPSHOT`. But during publishing we add `opentelemetry-` prefix to artifact name and so a dependant project will declare its dependency upon `io.opentelemetry.javaagent:opentelemetry-javaagent`.

Thus during composite build gradle tries to find `opentelemetry-javaagent` artifact from this project and fails.

**Comment by anuraaga** [comment]
I feel as if tweaking the names how we do it isn't so weird. Should we file an issue in gradle repo?

Though either way the workaround for the old Gradle issue could still be a blocker...

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/buildSrc/src/main/kotlin/otel.java-conventions.gradle.kts#L266

**Comment by iNikem** [comment]
I mean, changing artifact name just for publishing does seem weird to me :D

**Comment by Oberon00** [comment]
This is more of an issue of opentelemetry-java, right? Since it isn't friendly to gradle's composite build feature with its many limitations: https://docs.gradle.org/current/userguide/composite_builds.html#current_limitations_and_future_work

**Comment by iNikem** [comment]
@Oberon00 we have absolutely the same issue in this very repo, e.g. when trying to build `gradle-plugins` or `extensions` projects, which are independent from the main one.

**Comment by Oberon00** [comment]
I'm playing around with building the examples in otel-java with the main project as included build: https://github.com/open-telemetry/opentelemetry-java/pull/3603

**Comment by Oberon00** [comment]
PR open-telemetry/opentelemetry-java#3653 was now merged and generates code snippets with the required gradle dependency substitutions for the included build.
