### ISSUE TITLE
Gradle deprecated configurations used

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#3638]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e937d85188a3d1609a325dc4b22d6dade3e4b5b0/buildSrc/src/main/kotlin/io.opentelemetry.instrumentation.base.gradle.kts#L11

This lines results in the following deprecation warnings:

```
The compileClasspath configuration has been deprecated for dependency declaration. | 203 usages |  
The runtimeClasspath configuration has been deprecated for dependency declaration. | 203 usages |  
The testCompileClasspath configuration has been deprecated for dependency declaration. | 203 usages |  
The testRuntimeClasspath configuration has been deprecated for dependency declaration. | 203 usages |
```

**Comment by trask** [comment]
I'm not seeing these deprecated warnings anymore. I opened #6220 to track enabling `org.gradle.warning.mode=fail` to prevent introducing new deprecated warnings.
