### ISSUE TITLE
OpenJDK 64-Bit Server VM warning

### ISSUE THREAD

**Issue by HashemTaheriSonos** [open-telemetry/opentelemetry-java-instrumentation#3658]
**Describe the bug**
Running the java agent 1.3.1 with scala code, I’m receiving quite a several lines of this warning at the first, which idk what does it mean exactly, currently spans are getting created but the parent id for each of them is null, hence everything is seprated from each other and wondering if this is causing sth strange.
```

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap
classpath has been appended 

```

**What version are you using?**
1.3.1

**Comment by iNikem** [comment]
This warning is unrelated to your spans problem. It is related to Class Data Sharing in JVM.

**Comment by HashemTaheriSonos** [comment]
Thanks for your response, I see... because it's quite weird at the moment as all my spans Parent ID is null. will try to digging more to find out the reason.

**Comment by laurit** [comment]
Closing this issue, feel free to open a new one when you are ready to provide a sample app that reproduces your issue or describe your issue in sufficient detail for others to be able to reproduce it.
