### ISSUE TITLE
OkHttp library instrumentation does not pass concurrency test

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3671]
OkHttp javaagent instrumentation was fixed in #3669 by instrumenting the internal `okhttp3.Dispatcher.enqueue()` method, but OkHttp library instrumentation still does not pass the concurrency test.

**Comment by laurit** [comment]
Resolved in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3812
