### ISSUE TITLE
Support for SQS based on AWS SDK v2 

### ISSUE THREAD

**Issue by HashemTaheriSonos** [open-telemetry/opentelemetry-java-instrumentation#3684]
**Is your feature request related to a problem? Please describe.**
Currently, if we use AWS SDK v1 to set up SQS and push or receive msg from it, we can have complete flow representation in the Cloudwatch ServiceLens map, I mean when it represents the services relation, it shows that the service is connected to an SQS, and also shows the connection to the receiver side of it and the service which is retrieving the msg from the sqs.

However, if we use AWS SDK v2, with the same scenario, it just shows that the service is connected to an SQS, but the receiver part is NOT connected to it. so they are separated. Hence the flow get broken and the spans are not linked togheter anymore.

**Describe the solution you'd like**
Having the full flow connection between the service which is sending a msg to the sqs and the one receiving from it, like what's happening by using aws sdk v1. 

This is kind of feature which has been implemented in the case of [AWS SDK V1](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/5cbade4f429d3c4e7ea18308244defe1a83fa296/instrumentation/aws-sdk/aws-sdk-1.11/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v1_11/TracingRequestHandler.java) instrumentation, but not in [AWS SDK V2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/5cbade4f429d3c4e7ea18308244defe1a83fa296/instrumentation/aws-sdk/aws-sdk-2.2/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v2_2/TracingExecutionInterceptor.java).

**Comment by anuraaga** [comment]
@kubawach Do you happen to be able to help with this? :-)

**Comment by yayfeng** [comment]
Any update on this issue? I have had the same problem while using SDK V2.
