### ISSUE TITLE
Remove unnecessary URL construction

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3699]
Constructing URL objects is a bit costly (in addition to memory, it does a lot of validation), and we construct them in various http server and http client instrumentations, generally in order to populate `http.url` attribute. This could probably be optimized by adding some kind of "uri builder" to our api that can be used instead.

**Comment by anuraaga** [comment]
I think the intent of the semantic conventions is to only return a URL if we have a URL, or otherwise return the parts, target, host, etc. Though not sure if this just makes it too confusing when writing instrumentation.
