### ISSUE TITLE
Have friendlier export config

### ISSUE THREAD

**Issue by johnbley** [open-telemetry/opentelemetry-java-instrumentation#370]
Right now to do export you need to download/find the exporter jar and then configure it like
`-Dota.exporter.jar=path/to/opentelemetry-auto-exporters-jaeger-<version>.jar `.  While still keeping the ability to create a custom jar with a custom SpanExporter{Factory}, we could embed the code for our supported exporters into our fat jar, and allow more convenient shorthand config like `-Dota.exporter=jeager`.

**Comment by trask** [comment]
My only concern is jar file size.

`opentelemetry-auto.jar` is 8.5mb

`opentelemetry-auto-exporters-jaeger.jar` and `opentelemetry-auto-exporters-otlp.jar` are 14mb each (though a ton of overlap with each other if they are using the same grpc versions)

Maybe we could have different agent downloads that come pre-bundled with a specific exporter?

**Comment by johnbley** [comment]
Perhaps with the help of some collector folks we could pick a "winner" and have it embedded in auto and enabled by default, with the option to download the other jar(s) and configure as now?  Code size, cpu overhead, GC thrash, static RAM  usage, etc. could be part of that conversation/tradeoff in choosing a default.

**Comment by flands** [comment]
Default for all projects should be OTLP -- the goal being to enable an OOTB experience that just works.

**Comment by flands** [comment]
I realize I should have provided more information for context -- if you assume the Otel Agent is deployed then by having OTLP enabled by default and configured to send to localhost then OOTB data will be collected.

**Comment by trask** [comment]
How about publishing different artifacts that have the different exporters embedded?

* opentelemetry-auto-otlp.jar
* opentelemetry-auto-jaeger.jar
* opentelemetry-auto-zipkin.jar
* opentelemetry-auto-logging.jar

Or maybe distribute a zip with the following contents:

   * opentelemetry-auto.jar
   * exporters/
     * opentelemetry-auto-exporters-otlp.jar
     * opentelemetry-auto-exporters-jaeger.jar
     * opentelemetry-auto-exporters-zipkin.jar
     * opentelemetry-auto-exporters-logging.jar

defaulting to otlp, and users could delete exporters that aren't needed.

**Comment by johnbley** [comment]
I really really like that the current install is "just one jar file" and not an install directory.  What if the default otlp is in the base jar (we can look at various ways to reduce its footprint) and the other exporters are separately downloadable release artifacts?

**Comment by trask** [comment]
How about:

* opentelemetry-auto.jar (single jar with otlp exporter)
* opentelemetry-auto-jaeger.jar (single jar with jaeger exporter)
* opentelemetry-auto-zipkin.jar (single jar with zipkin exporter)
* opentelemetry-auto-no-exporter.jar (single jar with no exporter)

to preserve the 1-jar file simplicity across the supported exporters?

**Comment by carlosalberto** [comment]
Btw @trask it would be nice to have `opentelemetry-auto` out there in Maven so vendors can create their own fat-jar with their own (bundled) exporter. Not urgent, but handy way down the road ;)

**Comment by trask** [comment]
@carlosalberto, good point, I created https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/384 to track that.

**Comment by trask** [comment]
I forgot about prometheus, which potentially adds a separate dimension. Bundling them all together into a single jar is sounding better 😆.

**Comment by iNikem** [comment]
I agree with @flands that OOTB experience should be around Otel stack. For everything: traces, metrics and logs in future. Which essentially devaluate the idea of `opentelemetry-auto-zipkin.jar` etc. I propose to publish the following artifacts from auto-instr:

- opentelemetry-auto.jar (single jar with otlp exporter)
- opentelemetry-all.jar (single jar with ALL exporters, may be very convenient during POCs and tinkering phases)
- separate jar per traces/metrics/logs exporter.

**Comment by trask** [comment]
I'm curious how much larger the `all` artifact would be compared to the `auto` artifact in this case? (given how much dependency overlap the otlp and jaeger exporters have)

If it's not that much larger, maybe we just bundle everything into opentelemetry-auto.jar? (coming back to @johnbley's original proposal)

**Comment by iNikem** [comment]
In addition to my proposal above and answering the request from @carlosalberto :

- opentelemetry-auto-no-exporter.jar (single jar with no exporter)

In total 3 jars for agent (default/otlp, all, nothing) plus jar per exporter (without agent)

**Comment by iNikem** [comment]
Agent jar together with otlp, jaeger and logging exporters is 21M
