### ISSUE TITLE
Unable to access current Span from item Reader, Writer, Processor classes

### ISSUE THREAD

**Issue by jamesylgan** [open-telemetry/opentelemetry-java-instrumentation#3709]
**Describe the bug**
Unable to access current Span from item Reader, Writer, Processor classes, as well as any BeforeJob, AfterJob, BeforeStep, etc methods. Instead, I can only ever find `DefaultSpan`

**Steps to reproduce**
Try to call `Span.current()` from any of the aforementioned areas of a Batch application.

**What did you expect to see?**
A valid span

**What did you see instead?**
Default Span (0000000000000000)

**What version are you using?**
v1.4.0

**Comment by trask** [comment]
hi @jamesylgan! can you provide a repro that can be used to investigate this issue?

**Comment by jamesylgan** [comment]
Hi @trask - this is happening with an extremely barebones Spring Batch app (with one other JobExecutionListener with no `getOrder` method)

**Comment by mateuszrzeszutek** [comment]
I've added some tests that verify that `Span.current()` returns the actual spring batch span, not the invalid one: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3721

I suppose the problem may lie with your application: can you share what version of the agent, the OpenTelemetry API (used by the app), what custom settings you're using?

**Comment by jamesylgan** [comment]
Resolved - this was happening with 1.0.0 of the API and 1.4.0 of the Java Agent
