### ISSUE TITLE
why opentelemetry-javaagent-all.jar lack logging-otlp exporter support?

### ISSUE THREAD

**Issue by mijingling** [open-telemetry/opentelemetry-java-instrumentation#3783]
**Describe the bug**
why opentelemetry-javaagent-all.jar lack logging-otlp exporter support?
Release 1.4.1 javaagent jar has logging, otlp ,bug lack logging-otlp

how could i  use logging-otlp exporter?

thanks

**Comment by iNikem** [comment]
Thanks for noticing. We will try to include this in our next release.

**Comment by mijingling** [comment]
@iNikem thank for answer
i need this exporter very urgent, i want to wrapper logging-otlp exporter by myself, 
i am trying to rebuild the javaagent-all.jar by gradle 

now i had rebuilded the javaagent 1.4.1, but i dont know how to change code to  to wrapper logging-otlp exporter

1. about -D param：i has copy logging auoconfigure file to logging-otlp

opentelemetry-java-instrumentation-1.4.1\instrumentation\spring\spring-boot-autoconfigure\src\main\java\io\opentelemetry\instrumentation\spring\autoconfigure\exporters\logging-otlp

but rebuild report error: io.opentelmetry.exporter.logging.otlp no exit !!!
logging-otlp source code just in sdk why rebuild could not found !!!

could you give some hotfix suggest (include code & gradle config) ? thanks a lot

**Comment by iNikem** [comment]
Please take a look at https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension and especially at https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/ad5f1ef53184c4f4983b6cf6dbddd5985245655b/examples/extension/src/main/java/com/example/javaagent/DemoSdkTracerProviderConfigurer.java#L28
