### ISSUE TITLE
Publish opentelemetry-auto jar to maven central

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#384]
This is a less ambitious version of #135 😄.

See https://github.com/open-telemetry/opentelemetry-auto-instr-java/issues/370#issuecomment-624223374.

I think there's some discussion we need to resolve in #370 first though.

**Comment by iNikem** [comment]
Why do we need to publish anything other than opentelemetry-auto jar and exporter jars? And, probably, fat jar `auto+exporters` to help with #370

**Comment by iNikem** [comment]
We also have to publish snapshot builds

**Comment by iNikem** [comment]
I propose to publish this to Artifactory OSS/Bintray first, as this is much easier from administrative side of things. We then can easily push jars to Maven Central from Bintray. I have direct contact with JFrog, so I can take this task. But probably I will need some help with governance and such regarding e.g. Bintray account.

**Comment by trask** [comment]
@iNikem that would be great! Assigning to you :smile:. Let's chat with @carlosalberto about what we can learn / leverage from his experience doing this in opentelemetry-java (https://github.com/open-telemetry/opentelemetry-java/blob/master/RELEASING.md).

**Comment by iNikem** [comment]
Do we need separate release branch right now, while we are still in 0.X range?
