### ISSUE TITLE
OpenTelemetry should not fail on context reloads

### ISSUE THREAD

**Issue by frommeyerc** [open-telemetry/opentelemetry-java-instrumentation#3841]
**Describe the bug**
When using the spring-autoconfiguration integration and restarting the spring context (e.g. user spring-dev-tools) the new context fails to start. the reason is that the open-tracing integration tries to create and register a new version of the opentracing sdk. As this is build as enforced singleton an exception is thrown.

Interestingly there is a method called `#resetForTest()` that actually nulls the static field holding the _globalOpenTelemetry_.

**Steps to reproduce**
* Add the spring autoconfiguration to a spring-boot project
* Configure the spring-dev-tools
* Start the server
* Change code to trigger a hot reload
* Observe issue.

**What did you expect to see?**
I expected the context to come up again without issue.

**What did you see instead?**
The context failing with a BeanInstatiationException

**What version are you using?**
1.4.1-alpha

**Environment**
Compiler: Eclipse Java 11
OS: "Ubuntu 20.04"

**Comment by jkwatson** [comment]
Interesting. I suspect that the spring integration shouldn't be setting the global at all.

**Comment by anuraaga** [comment]
I'm not too familiar with how the reload works but am reading this

https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html#using-boot-devtools-customizing-classload

It seems to imply that only projects open in the IDE are loaded in the restart classloader. Since we'd expect our library to be included as a build dependency, it should be in the base classloader. Any idea why the Otel configuration is restarted or an approach to prevent it?

**Comment by trask** [comment]
@frommeyerc can you provide a repro for this issue that we can use to investigate?

**Comment by frommeyerc** [comment]
I should be able to compile s.th. in a couple of days.

**Comment by frommeyerc** [comment]
I created a repository here: https://github.com/frommeyerc/otel-demo/tree/master/opentelemetry-refresh
The simple Spring-Boot application does nothing but exposing a hello world http endpoint. If started with
```
mvn spring-boot:run
```
from the command line it will start on port 8080. If you modify the code it will automatically try to reload the context and fail with an exception.

**Comment by iNikem** [comment]
Fixed by #4051
