### ISSUE TITLE
Values not reported for runtime metrics

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#3846]
It seems that with javaagent 1.4, runtime metrics may not be reporting values.

https://github.com/aws-observability/aws-otel-java-instrumentation/issues/71#issuecomment-899286133

With 1.5, the world is being rewritten, so we shouldn't really try to fix that problem but will want to confirm that it is fixed with 1.5.

**Comment by laurit** [comment]
Could this be same as https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3568?

**Comment by anuraaga** [comment]
@laurit Ah thanks for the tip I think it is
