### ISSUE TITLE
Add Prometheus auto-exporter

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#385]
This involves a couple of hurdles

* We currently only support push-based metrics exporters
* We currently only support a single exporter jar, so how does someone use jaeger + prometheus?
  * EDIT: see https://github.com/open-telemetry/opentelemetry-specification/issues/710

**Comment by trask** [comment]
Dropping from `p1` to `p3` to match prioritization of auto-collected metrics

**Comment by pavolloffay** [comment]
> We currently only support push-based metrics exporters

p8s support pushing metrics https://github.com/prometheus/client_java#exporting-to-a-pushgateway. Do we want to go this route or expose p8s metrics on some port? 

> We currently only support a single exporter jar, so how does someone use jaeger + prometheus?
> EDIT: see open-telemetry/opentelemetry-specification#710

I guess this is already solved right? With https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1242 I was able to use `otlp,jaeger` to export traces.

**Comment by pavolloffay** [comment]
I have created an issue for this https://github.com/open-telemetry/opentelemetry-java/issues/1687

**Comment by bogdandrutu** [comment]
Prometheus people always recommend to use the pull model.

**Comment by trask** [comment]
> > We currently only support push-based metrics exporters
> 
> p8s support pushing metrics https://github.com/prometheus/client_java#exporting-to-a-pushgateway. Do we want to go this route or expose p8s metrics on some port?

Based on @bogdandrutu's comment, let's expose on a port, would be great to add env var(s) to a new "Prometheus Exporter" section in the spec after https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/sdk-environment-variables.md#zipkin-exporter.

Maybe something like `OTEL_EXPORTER_PROMETHEUS_BIND_PORT`(?) with no default, and `OTEL_EXPORTER_PROMETHEUS_BIND_ADDRESS`(?) with default `0.0.0.0`, just in case someone wants to lock it down further.

And then we can internally use: https://github.com/prometheus/client_java/blob/master/simpleclient_httpserver/src/main/java/io/prometheus/client/exporter/HTTPServer.java

> > We currently only support a single exporter jar, so how does someone use jaeger + prometheus?
> > EDIT: see [open-telemetry/opentelemetry-specification#710](https://github.com/open-telemetry/opentelemetry-specification/issues/710)
> 
> I guess this is already solved right? With #1242 I was able to use `otlp,jaeger` to export traces.

👍

**Comment by pavolloffay** [comment]
PR for the spec https://github.com/open-telemetry/opentelemetry-specification/pull/1021
