### ISSUE TITLE
Sporadic build failure / openj9 jvm crash

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3896]
I've seen this twice now.

```
0x3e9700j9bcu(j9vm).128    *   ** ASSERTION FAILED ** at ../../../../../openj9/runtime/bcutil/dynload.c:398: ((0 ))
```

For (a bit) more detail, see the [console-log.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/7026457/console-log.txt)

**Comment by laurit** [comment]
Assertion in same file and line is mentioned in https://github.com/eclipse-openj9/openj9/issues/11040 Based on just this assertion it is probably impossible to tell what exactly is the problem. Perhaps we could somehow also archive the javadump files? javacore.xxx.txt should be the human readable one. Or if we can't get the javadump files then perhaps we could add `-Xdump:console` to jvm args when running on openj9, hopefully whatever it dumps to console contains a bit more info.

**Comment by anuraaga** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/3458356291?check_suite_focus=true

**Comment by laurit** [comment]
Reported to openj9 https://github.com/eclipse-openj9/openj9/issues/13414
