### ISSUE TITLE
opentelemetry-javaagent 1.5.0 published with packaging "pom" instead of "jar"

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3900]
~And `opentelemetry-agent-for-testing` too.~ `opentelemetry-agent-for-testing` was fixed in #3899

**Comment by iNikem** [comment]
@trask @mateuszrzeszutek we are supposed to have an extension test which verifies this. Did not it work?

**Comment by mateuszrzeszutek** [comment]
I'm guessing it didn't - the way the javaagent was built has changed some time ago (and the publishing issue was introduced at that time) and extension tests didn't fail on that at all.
