### ISSUE TITLE
app using codehaus.plexus  failed to generate bean with java instrumentation

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java-instrumentation#3926]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/27889201/130615343-7031a642-bc17-49c5-88e5-bdbe09af0a1f.png">
And here is the class file:  https://github.com/dianping/cat/blob/d8033c988b825f35fc06c20660f4aed927e43465/cat-client/src/main/java/com/dianping/cat/message/io/TcpSocketSender.java

It is the config file: https://github.com/dianping/cat/blob/d8033c988b825f35fc06c20660f4aed927e43465/cat-client/src/main/resources/META-INF/plexus/components.xml.
I am little confused why there will be a field named"__opentelemetryContext$java$lang$Runnable" in the log, maybe I should add "-Dotel.javaagent.experimental.field-injection.enabled=false"?
btw, without java instrumentation the app is ok.

**Comment by mateuszrzeszutek** [comment]
Yep, those fields are added by the `FieldBackedProvider`. Setting `"otel.javaagent.experimental.field-injection.enabled"` to false should help, it's worth testing that.
I'm not familiar at all with the codehaus-plexus plugin/software - but is it okay that it tries to map transient fields? All those fields added by the javaagent are marked as transient.

**Comment by trask** [comment]
@tydhot it would be great if you could test once #3928 is merged and the SNAPSHOT build is published, to see if that helps

**Comment by laurit** [comment]
@trask  as far as I can tell #3928 won't help for this :( Though I have an idea how to make this work.
