### ISSUE TITLE
Make opentelemetry-javaagent "all" artifact the default artifact

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#3959]
And introduce a "slim" artifact that has no exporters (same as what is now the default artifact).

Some notes from Aug 12 SIG meeting:

* The “-all” jar will be confusing once we move some of the instrumentation to contrib
  * Then it will not really be “all” (will likely have a separate javaagent released from contrib that has everything, similar to otel collector)
* The “-all” jar has already been a source of confusion
* For a while the default had exporters anyways

and see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3900#issuecomment-906096077

**Comment by iNikem** [comment]
Still think that we need a name for "just agent" (maybe with internal instrumentations to guarantee that all extensions will actually work)

**Comment by trask** [comment]
> Still think that we need a name for "just agent" (maybe with internal instrumentations to guarantee that all extensions will actually work)

can you itemize use case(s) for this "just agent"? maybe that will help us come up with a good name for it

**Comment by iNikem** [comment]
> > Still think that we need a name for "just agent" (maybe with internal instrumentations to guarantee that all extensions will actually work)
> 
> can you itemize use case(s) for this "just agent"? maybe that will help us come up with a good name for it

I just remembered my idea of its name: `-core`
