### ISSUE TITLE
Add the agent version to the tracer name/version

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#404]
Currently, the tracers are acquired with a name, but not a version. It would be very useful to have the agent version included as well. This could be used to identify the version of the agent when looking at spans, making doing customer support easier. We wouldn't need to ask the customer for what version of the agent they were running, but just look at the data directly.

**Comment by iNikem** [comment]
@jkwatson where do you want see those names and versions?
