### ISSUE TITLE
It seemed that there is a memory leak in spring cloud gateway.(instrumentation version release.1.4.0)

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java-instrumentation#4040]
I run spring cloud gateway with java instrumentation and the heap size increases overtime and  oom finally.
<img width="508" alt="image" src="https://user-images.githubusercontent.com/27889201/131657957-706014b9-5f43-453a-9b16-0d3394593f2c.png">
I dump it and found there is 402k TracingSubscriber and there is 30k RecordEventsReadableSpan. Maybe the info can help?
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/27889201/131658461-413f3bc7-3cba-4d84-9158-c12bb535ebfb.png">

**Comment by tydhot** [comment]
<img width="901" alt="image" src="https://user-images.githubusercontent.com/27889201/131703229-97baa3d2-077c-43c4-8899-70d53c0e0f6d.png">
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/27889201/131703280-e66cda15-6d60-4213-a0b6-365482a017b3.png">
According to gc root, I think the num of the channelHandler from FieldBackedProvider seemed a little big.

**Comment by mateuszrzeszutek** [comment]
It's just my suspicion, but in `AbstractNettyChannelPipelineInstrumentation` we're not instrumenting `ChannelPipeline`'s `removeFirst()`, `removeLast()` and `replace()` methods. If somebody used those methods for removing/replacing handlers that were added with instrumented `add...()` our own handlers would probably not get removed.

**Comment by mateuszrzeszutek** [comment]
@tydhot If you're able to reproduce that issue, please try turning off the `netty` instrumentation and check if it helps.

**Comment by tydhot** [comment]
@mateuszrzeszutek hi, I have turned off the Netty instrumentation like below:
<img width="602" alt="image" src="https://user-images.githubusercontent.com/27889201/131794139-c0031362-f62f-4dae-b4e6-18b762a5039d.png">
This is the heap size turn off nett:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/27889201/131794265-1b1f6e01-b279-4986-a62f-ca9e304b3a8d.png">
This is the original control group corresponding to turning off netty：
<img width="770" alt="image" src="https://user-images.githubusercontent.com/27889201/131794379-385347d2-6d35-4491-8034-5f1e6ff5efd0.png">
I think it is worked.

**Comment by mateuszrzeszutek** [comment]
> Maybe you're talking about the cause of memory leak.

Yeah, I just wrote down the results of my quick investigation. Anyway, since turning off the `netty` instrumentation helped there's a good chance that the memleak is caused by what I've described in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4040#issuecomment-910431343

**Comment by tydhot** [comment]
> Yeah, I just wrote down the results of my quick investigation. Anyway, since turning off the `netty` instrumentation helped there's a good chance that the memleak is caused by what I've described in [#4040 (comment)](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4040#issuecomment-910431343)

yes, and I changed the code like this:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/27889201/132180356-26276cd0-485f-4bbd-b1f1-8fdc5f25303d.png">
I did the pressure test again. It looks like it's solved. But this is not an elegant approach, so I look forward to a better solution.
