### ISSUE TITLE
agent configuration OTEL_EXPERIMENTAL_EXPORTER_OTLP_PROTOCOL=http/protobuf still export via grpc

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-java-instrumentation#4048]
**Describe the bug**
I am trying to run the agent and export traces over otlp to http/protobuf receiver. According to [the documentation](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-both-span-and-metric-exporters), setting an environment variable `OTEL_EXPERIMENTAL_EXPORTER_OTLP_PROTOCOL` to `http/protobuf` should do it, but when applied the agent still try to export spans via grpc. I get the following error in the log:

```
[otel.javaagent 2021-09-02 15:46:00:523 +0300] [grpc-default-executor-1] WARN io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter - Failed to export spans. Error message: INTERNAL: http2 exception
```

**Steps to reproduce**
cloned a simple spring app [from here](https://github.com/in28minutes/spring-boot-examples), cd into `spring-boot-2-rest-service-basic`, run `mvn package` and then run the application with the agent instrumentation:

```
OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4318 OTEL_EXPERIMENTAL_EXPORTER_OTLP_PROTOCOL=http/protobuf java -javaagent:opentelemetry-javaagent-all.jar -jar target/spring-boot-2-rest-service-basic-0.0.1-SNAPSHOT.jar
```

On a different terminal, run collector which accepts otlp traces only on HTTP endpoint (no grpc).

The following error is printed to log:
```
[otel.javaagent 2021-09-02 15:46:00:523 +0300] [grpc-default-executor-1] WARN io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter - Failed to export spans. Error message: INTERNAL: http2 exception
```

**What did you expect to see?**
Expected the agent to export to the HTTP endpoint and not try to export with grpc, as the documentation specify.

**What did you see instead?**
Error from `OtlpGrpcSpanExporter`, which means that the `OTEL_EXPERIMENTAL_EXPORTER_OTLP_PROTOCOL=http/protobuf` config option was not used.

**What version are you using?**
```
java -jar opentelemetry-javaagent-all.jar -v          
1.5.3
```

**Environment**
```
➜  spring-boot-2-rest-service-basic git:(master) java --version
openjdk 14.0.1 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

➜  spring-boot-2-rest-service-basic git:(master) uname -v
Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64
```

**Comment by blumamir** [comment]
tried also with `-Dotel.experimental.exporter.otlp.protocol=http/protobuf` and it still uses grpc for otlp export

**Comment by jkwatson** [comment]
Hi @blumamir . Unfortunately, this hasn't actually been released yet. The docs got updated before we released the code. This support is coming in the next version (1.6.0) which should be released in a week or so.

**Comment by blumamir** [comment]
> Hi @blumamir . Unfortunately, this hasn't actually been released yet. The docs got updated before we released the code. This support is coming in the next version (1.6.0) which should be released in a week or so.

I see, makes sense :)
Thanks
