### ISSUE TITLE
IgnoredTypesConfigurer SPI does not work due to package shading

### ISSUE THREAD

**Issue by edwardxia** [open-telemetry/opentelemetry-java-instrumentation#4049]
```
Caused by: java.lang.AbstractMethodError: Receiver class MyIgnoredTypesConfigurer does not define or inherit an implementation of the resolved method 'abstract void configure(io.opentelemetry.javaagent.shaded.instrumentation.api.config.Config, io.opentelemetry.javaagent.extension.ignore.IgnoredTypesBuilder)' of interface io.opentelemetry.javaagent.extension.ignore.IgnoredTypesConfigurer.
```

My class implement the SPI interface and takes `io.opentelemetry.instrumentation.api.config.Config` as argument, but when this is loaded from agent it is expecting the shaded class `io.opentelemetry.javaagent.shaded.instrumentation.api.config.Config`, causing it to break.

**Comment by edwardxia** [comment]
Adding a package relocation rule in my project fixed this. However, other things like custom exporter provider spi etc. do not need package relocation to work.

**Comment by mateuszrzeszutek** [comment]
Hey @edwardxia ,
What's your use case - are you developing a custom [distro](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/distro) or an [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension)? You shouldn't need to relocate anything in the case of implementing a custom extension.

**Comment by edwardxia** [comment]
Extension loaded by `-Dotel.javaagent.extensions`. My understanding is that I shouldn't need to relocate, thus I think it is a bug.

**Comment by edwardxia** [comment]
```
import com.google.auto.service.AutoService;
import io.opentelemetry.instrumentation.api.config.Config;
import io.opentelemetry.javaagent.extension.ignore.IgnoredTypesBuilder;
import io.opentelemetry.javaagent.extension.ignore.IgnoredTypesConfigurer;

@AutoService(IgnoredTypesConfigurer.class)
public class FabanIgnoredTypesConfigurer implements IgnoredTypesConfigurer {
    @Override
    public void configure(Config config, IgnoredTypesBuilder builder) {
        builder.allowClass("com.sun.faban.");
    }

    @Override
    public int order() {
        return 1;
    }
}
```
