### ISSUE TITLE
Diagrams are not readable in dark mode. 

### ISSUE THREAD

**Issue by meSunnySrivastava** [open-telemetry/opentelemetry-java-instrumentation#4050]
**Describe the bug**
Initialization-sequence and classloader state diagrams at "Understanding the javaagent components" are not readable in dark mode.

**Steps to reproduce**
change your github theme to dark mode and visit
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/javaagent-jar-components.md

**What did you expect to see?**
The diagrams should be readable 

**What did you see instead?**
Diagrams are not readable because their colour is black

**What version are you using?**
Not applicable

**Environment**
Not applicable

**Additional context**
The diagrams should look something like they look in my branch here. 

https://github.com/meSunnySrivastava/opentelemetry-java-instrumentation/blob/betterDiagrams/docs/contributing/javaagent-jar-components.md

Please let me know if I should create a PR for this or how to contribute. 

Thanks

**Comment by trask** [comment]
> Please let me know if I should create a PR for this or how to contribute.

@meSunnySrivastava that would be wonderful, please send PR, if you have questions feel free to ask here or in this repo's [slack channel](https://cloud-native.slack.com/archives/C0150QF88FL)

**Comment by laurit** [comment]
Resolved in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4072
