### ISSUE TITLE
Netty ChannelPipeline#removeLast() removes instrumentation handler

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#4056]
**Describe the bug**
Our instrumentation `ChannelHandler`s are always inserted after the original one. That means if someone calls `ChannelPipeline#removeLast()` it'll remove our handler, but leave the original HTTP client/server one in the pipeline.

**What did you expect to see?**
Probably we should always remove both handlers (the original HTTP one & the instrumentation one) at a time?

**Additional context**
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4053#discussion_r703149578

**Comment by tydhot** [comment]
maybe we should check the handler type when `removeLast` is called. If the handler type is ourhandler, we should call `removeLast` again to remove the handler user actually want.
