### ISSUE TITLE
How to instrument “apache-httpclient-4.0” that  package name was changed

### ISSUE THREAD

**Issue by Bpmm9012** [open-telemetry/opentelemetry-java-instrumentation#4073]
one of my SDK use apache-httpclient-4.0 as httpclient,To avoid SDK's user application dependency conflicts,I have used jarjar maven plugin to change package name, Prefix was added to the original package name.（）
thus the com.xxx.org.apache.http.client could not be instrumented,Is there a way to solve this problem?

**Comment by trask** [comment]
hi @Bpmm9012! I haven't tried this, but you may be able to build an [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension#introduction), and have that extension shade the [opentelemetry-javaagent-apache-httpclient-4.0](https://search.maven.org/search?q=a:opentelemetry-javaagent-apache-httpclient-4.0).

I suspect this question will come up again, so if you try this out, let us know if you run into any issues/successes.

**Comment by Bpmm9012** [comment]
hi @trask !, I have transplanted the code to extension in a simple way before, but the helper class wasn't loaded(only xxxInstrumentationModule.class and xxxInstrumentation.class  succeed loaded)，probably the "muzzle" plugin(method used to load helper class is generated by it automatically) wasn't add.
I'm trying to fix this problem and will sync progress.

**Comment by trask** [comment]
can you try with the maven-shade-plugin instead of jarjar maven plugin? I have heard that jarjar may not relocate strings, which would be important for the instrumentation

**Comment by trask** [comment]
Closing, let us know if you are still facing this issue and we'll re-open.
