### ISSUE TITLE
Capture redis key accessed in lettuce autoinstrumentation

### ISSUE THREAD

**Issue by dneray** [open-telemetry/opentelemetry-java-instrumentation#408]
When lettuce is used to access redis, the trace just shows the type of operation but it doesn't show specifics.

I am wondering if it would be possible to include the relevant redis key as an attribute.

**Comment by iNikem** [comment]
My understanding is that this would require the understanding of all Redis commands. To detect those where some useful data can be extracted.

**Comment by dustinneray** [comment]
I have discovered that the lettuce client has its own notion of tracing that provides this information. For my use case, I have written a set of simple bridge classes that implement the lettuce interface. It take the data provided from lettuce and uses them to construct opentelemtery spans.

It provides the key and some more information about the spans (i.e. how long the encoding takes). I would be happy to contribute this back to the autoinstrumentation library if it's desirable but this feels like a slightly different approach than what has been used to perform autoinstrumentation of other libraries.

**Comment by dneray** [comment]
I have discovered that the lettuce client has its own notion of tracing that provides this information. For my use case, I have written a set of simple bridge classes that implement the lettuce interface. It take the data provided from lettuce and uses them to construct opentelemtery spans.

It provides the key and some more information about the spans (i.e. how long the encoding takes). I would be happy to contribute this back to the autoinstrumentation library if it's desirable but this feels like a slightly different approach than what has been used to perform autoinstrumentation of other libraries.

**Comment by trask** [comment]
Hi @dneray, I'm very interested to see what you've done, and to see if it might be applicable here. Are you able to share the code you've written? thx!

**Comment by trask** [comment]
Also there's some discussion of semantic conventions around redis keys here: https://github.com/open-telemetry/opentelemetry-specification/pull/575

**Comment by dneray** [comment]
So this is what I have so far, it's just set as the tracing instance on the lettuce client resources. With both lettuce autoinstrumentation and this enabled what I get is a child span under every redis call that looks like a duplicate except that it includes the key and some other information. 

I have only tested this on the reactive client but one interesting thing that I've noticed is that the current autoinstrumented trace starts as soon as the call to lettuce is made whereas this trace only starts after it enters the netty nio loop.

```
import java.net.SocketAddress;
import java.util.ArrayList;
import java.util.List;

import io.grpc.Context;
import io.lettuce.core.tracing.TraceContext;
import io.lettuce.core.tracing.TraceContextProvider;
import io.lettuce.core.tracing.Tracer;
import io.lettuce.core.tracing.TracerProvider;
import io.lettuce.core.tracing.Tracing;
import io.opentelemetry.OpenTelemetry;
import io.opentelemetry.context.Scope;
import io.opentelemetry.trace.Span;

public class RedisTracingAdapter implements Tracing
{
    private static final TracerProviderRedisAdapter TRACER_PROVIDER_REDIS_ADAPTER_INSTANCE = new TracerProviderRedisAdapter();

    @Override
    public TracerProvider getTracerProvider()
    {
        return TRACER_PROVIDER_REDIS_ADAPTER_INSTANCE;
    }

    @Override
    public TraceContextProvider initialTraceContextProvider()
    {
        return new TraceContextProviderRedisAdapter();
    }

    @Override
    public boolean isEnabled()
    {
        return true;
    }

    @Override
    public boolean includeCommandArgsInSpanTags()
    {
        return true;
    }

    @Override
    public Endpoint createEndpoint(SocketAddress socketAddress)
    {
        return null;
    }

    public static class TraceContextProviderRedisAdapter implements TraceContextProvider
    {

        @Override
        public TraceContext getTraceContext()
        {
            return new TraceContextRedisAdapter();
        }
    }

    public static class TraceContextRedisAdapter implements TraceContext
    {
        private final Context context;

        TraceContextRedisAdapter()
        {
            this.context = Context.current();
        }

        public Context getContext()
        {
            return context;
        }
    }

    public static class TracerProviderRedisAdapter implements io.lettuce.core.tracing.TracerProvider
    {

        @Override
        public Tracer getTracer()
        {
            return new TracerRedisAdapter();
        }
    }

    public static class TracerRedisAdapter extends Tracer
    {

        @Override
        public SpanRedisAdapter nextSpan()
        {
            return new SpanRedisAdapter();
        }

        @Override
        public Span nextSpan(TraceContext traceContext)
        {
            return new SpanRedisAdapter(traceContext);
        }
    }

    public static class SpanRedisAdapter extends Tracer.Span
    {
        List<String> events = new ArrayList<>();

        private Span.Builder spanBuilder;
        private final Context context;
        private Span span;
        private String name;

        private Scope scope = null;

        public SpanRedisAdapter(TraceContext traceContext)
        {
            super();
            if (!(traceContext instanceof TraceContextRedisAdapter))
            {
                throw new RuntimeException("Invalid type given: " + traceContext);
            }
            this.spanBuilder = OpenTelemetry.getTracerProvider().get("com.trace.adapter.redis")
                .spanBuilder("RedisTracingAdapter");

            this.context = ((TraceContextRedisAdapter)traceContext).getContext();
            this.span = null;
        }

        public SpanRedisAdapter()
        {
            super();
            this.spanBuilder = OpenTelemetry.getTracerProvider().get("com.trace.adapter.redis")
                .spanBuilder("RedisTracingAdapter");
            this.context = null;
        }

        @Override
        public Tracer.Span start()
        {
            span = spanBuilder.startSpan();
            if (context != null)
            {
                // Cannot support passing context between threads so ignoring the context here for now
            }
            events.forEach(event -> span.addEvent(event));
            if (name != null)
            {
                span.updateName(name);
            }
            spanBuilder = null;
            return this;
        }

        @Override
        public Tracer.Span name(String name)
        {
            if (span == null)
            {
                this.name = name;
            }
            else
            {
                span.updateName(name);
            }
            return this;
        }

        @Override
        public Tracer.Span annotate(String value)
        {
            if (span == null)
            {
                events.add(value);
            }
            else
            {
                span.addEvent(value);
            }
            return this;
        }

        @Override
        public Tracer.Span tag(String key, String value)
        {
            if (span == null)
            {
                spanBuilder.setAttribute(key, value);
            }
            else
            {
                span.setAttribute(key, value);
            }
            return this;
        }

        @Override
        public Tracer.Span error(Throwable throwable)
        {
            tag("exception.class", throwable.getClass()
                .getName());
            tag("exception.msg", throwable.getMessage());
            return null;
        }

        @Override
        public Tracer.Span remoteEndpoint(Endpoint endpoint)
        {
            return this;
        }

        @Override
        public void finish()
        {
            if (span != null)
            {
                span.end();
            }
        }
    }
}
```

**Comment by trask** [comment]
@dneray thanks! It's nice to use a library's built-in tracing abilities like this when possible.

@devinsba I'd love to know what you think.

It looks like the lettuce `Tracing` interface wasn't introduced until `5.1.0`, so we might need to keep around the existing `lettuce-5.0` instrumentation to support `5.0.x` versions, but could potentially introduce `lettuce-5.1` instrumentation based on this.

**Comment by anuraaga** [comment]
Just happened to add lettuce tracing to my OpenTelemetry playground app and had the same thought that it'd be great to be using the native tracing support. @dneray would you be interested in sending a PR with your instrumentation? If not, I'm happy to take it over, though would start by copying pasting all that nice code.
