### ISSUE TITLE
Simpler solution for library instrumentation to benefit from InstrumentationContext when used in agent

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4081]
If we had an instrumentation-api something like:

```
public AssociatingCache {
  public static <Q extends K, K, C> Cache<Q, C> get(Class<K> keyClass, Class<C> contextClass) {
    return Cache.newBuilder().setWeakKeys().build();
  }
}
```

then the agent could replace the implementation of that method at runtime with

```
InstrumentationContext.get(keyClass, contextClass).asCache()
```

and I think that would make it easier to migrate things to library instrumentation while not losing the benefit of InstrumentationContext when used in agent.

(see [JdbcData.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/4c64f70f94e5e5f4e80e3ff263ef7a477962d460/instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcData.java#L26-L39) for the current solution to using InstrumentationContext from library instrumentation when it is used in agent)

**Comment by mateuszrzeszutek** [comment]
We'd probably have to do sth like
```
if (contextStoreSupplier == null) {
  return Cache.newBuilder().setWeakKeys().build();
}
return contextStoreSupplier.get(keyClass, contextClass);
```
With the `contextStoreSupplier` being set by the agent.
