### ISSUE TITLE
Apply spotless configuration to standalone projects

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4104]
There are some standalone projects in this repository which are not benefitting from our standard spotless gradle configuration:
* benchmark-overhead
* examples/distro
* examples/extension
* gradle-plugins

**Comment by anuraaga** [comment]
It's probably a good time to publish a plugin with java-conventions from the SDK repo will try it out.

**Comment by trask** [comment]
Even though we aren't publishing / sharing the java-convention, spotless is being applied (independently) to these other modules now
