### ISSUE TITLE
Propagate headers from Spring Web/WebFlux to gRPC Client with Auto-Instrumentation

### ISSUE THREAD

**Issue by murphye** [open-telemetry/opentelemetry-java-instrumentation#4175]
**Is your feature request related to a problem? Please describe.**

Please see this Java class:
https://github.com/murphye/spring-boot-reactive-grpc-istio/blob/main/greet-webflux-grpc-client/src/main/java/io/solo/greet/GreetWebfluxGrpcClientApplication.java#L52

This Spring Boot application listens for a request on HTTP and then makes a gRPC client request in response to that HTTP request.

In testing, I am not seeing headers being propagated from the incoming GET request to the outgoing POST gRPC client request. This results in separate trace ids.

**Describe the solution you'd like**

Instrument propagating headers from Spring to gRPC.

**Describe alternatives you've considered**

Manually copying headers?

**Other**

Not related, but I am using Istio's Envoy sidecar to export the traces. This is how I am running the application with the agent.

`ENTRYPOINT ["java","-javaagent:opentelemetry-javaagent-all.jar","-Dotel.propagators=b3,b3multi","-Dotel.traces.exporter=none","-jar","app.jar"]`

**Comment by murphye** [comment]
Are there any alternatives here that I could implement?

**Comment by murphye** [comment]
Looking at this more with logging enabled, this is what I am seeing (matching trace_id)

```
2021-09-21 04:38:11 - i.s.g.GreetWebfluxGrpcClientApplication - Will try to greet eric ... trace_id=f55237655fc2123d4496badce4b3f17e span_id=0ac8ca4688f948dd trace_flags=01 
```

```
2021-09-21 04:38:12 - i.s.hello.HelloGrpcServerApplication - Hello eric trace_id=f55237655fc2123d4496badce4b3f17e span_id=b28ddcbbe5388ffa trace_flags=01 
```

It appears that maybe the headers are being propagated correctly after all? 

I need to dig deeper. Closing this for now.

**Comment by danhngo-lx** [comment]
Hi @murphye, I'm in a very similar situation like yours. Can you share a bit about the exact problem and solution you had?
