### ISSUE TITLE
Occasionally get connection timeout exception occur in HTTP requests

### ISSUE THREAD

**Issue by GlowingRuby** [open-telemetry/opentelemetry-java-instrumentation#4188]
**Describe the bug**

Deadlocks were found through thread dump, and the thread stacks were

![image](https://user-images.githubusercontent.com/26060287/134326540-e6b15e67-595c-40bc-99b1-bd43bb4adfef.png)
![image](https://user-images.githubusercontent.com/26060287/134326675-d0a32b11-3c9d-4315-ad6a-8c6769e45bc5.png)

In sharding-jdbc-1.5.4.1, called com.dangdang.ddframe.rdb.sharding.jdbc.core.connection.ShardingConnection#getMetaData, If there is no cached connection(because of druid connection pool logic), the metadata is obtained after the connection is created. Then the mysql driver call com.mysql.jdbc.ConnectionImpl#loadServerVariables When creating a connection to execute SQL, Triggered the io.opentelemetry.instrumentation.jdbc.internal.JdbcUtils#extractDbInfo method, but the lock has already been acquired by the thread executing the HTTP request, and the thread executing the HTTP request is waiting for the connection to be created, A deadlock has been created.

**What version are you using?**
v1.4.1

**Comment by trask** [comment]
@GlowingRuby thanks for reporting this!! I've sent a PR to address it #4191

**Comment by GlowingRuby** [comment]
> @GlowingRuby thanks for reporting this!! I've sent a PR to address it #4191

You're welcome~ 
Do we need to consider whether deadlock can also occur with other uses of WeakLockFreeCache?

**Comment by trask** [comment]
> Do we need to consider whether deadlock can also occur with other uses of WeakLockFreeCache?

that's an excellent question, I've opened #4192 to track and get others' feedback. I did do a cursory review of other calls to `computeIfAbsent()` and didn't see any other glaring callbacks to application code, but it's definitely worth a more detailed review.
