### ISSUE TITLE
Consider if Cache.computeIfAbsent should provide atomicity

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4192]
See #4188

Given the problems that the lock can cause, it may be better to opt-in (somehow) if you really need atomicity.

note: this also applies `FieldBackedProvider.putIfAbsent(Object key, Supplier<Object> contextFactory)` which backs `ContextStore.asCache()`

**Comment by GlowingRuby** [comment]
I think opt-in would be better, and the performance would be better without locking.

**Comment by anuraaga** [comment]
A method named `computeIfAbsent` definitely needs to be atomic like ConcurrentHashMap is or it would be too confusing naming wise.

Possible deadlock with that method on concurrent maps is a "feature" of Java I don't know if we get much from for example providing a different named method, while it's generally easy to write safe code with java sometimes we just have to be careful I guess.

**Comment by iNikem** [comment]
> A method named `computeIfAbsent` definitely needs to be atomic like ConcurrentHashMap is or it would be too confusing naming wise.

I actually am not sure about this. Method `computeIfAbsent` is defined on `java.util.Map` and it does NOT guarantee atomicity: 

> The default implementation makes no guarantees about synchronization or atomicity properties of this method. Any implementation providing atomicity guarantees must override this method and document its concurrency properties. In particular, all implementations of subinterface java.util.concurrent.ConcurrentMap must document whether the mapping function is applied once atomically only if the value is not present.

**Comment by iNikem** [comment]
Second, what do we mean by "atomicity" here? That computing function will be called if and only if there were no previous value and it is guaranteed that if mapping function was called then `computeIfAbsent` will return the result of that mapping function? Why do we need such guarantee?

**Comment by anuraaga** [comment]
> I actually am not sure about this. Method computeIfAbsent is defined on java.util.Map and it does NOT guarantee atomicity:

In practice, I would expect our caches to work concurrently, so it would be quite surprising to me if `computeIfAbsent` didn't follow the behavior of `ConcurrentMap`. Basically I'd expect to be able to drop in replace a `ConcurrentHashMap` with one of the caches and have similar semantics, it seems to keep things simplest.

> Why do we need such guarantee?

Yeah just to match ConcurrentHashMap

https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#computeIfAbsent-K-java.util.function.Function-

It's not required, but somehow I expect more bugs from diverging from that and causing a problematic recompute vs deadlock by not being consistent with more the more commonly used JDK class.

**Comment by iNikem** [comment]
What are possible problem with recompute which are more severe that deadlock? For some reason I always assumed mapping function to be pure

**Comment by anuraaga** [comment]
> is your concern with how to communicate clearly that it is not atomic so that others don't misuse it?

The concern is the latte, though I didn't verify in detail whether we need it or not. Those examples you provide are what I had in mind. The easiest solution to communication is to just call the method a different name :)
