### ISSUE TITLE
Remove AgentExtension from public API

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#4219]
Unless there is a valid use-case where somebody already uses this extension point, I propose to remove it from the public extension API prior to declaring it stable. It will decrease public surface and makes maintainers life easier.

/cc @pavolloffay Do you still use this extension point? Can you remind us of your use-case?

**Comment by pavolloffay** [comment]
This API is not used in the Hypertrace javaagent.
