### ISSUE TITLE
Is it safe to exclude the okhttp dependency?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4240]
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4106#discussion_r718163126 and https://github.com/open-telemetry/opentelemetry-java/pull/3678

(would apply to both the slim and default artifacts)

**Comment by anuraaga** [comment]
Because the ManagedChannel can't be customized when using the agent, I think the chance is good it can be. But it's hacky and less savings than this which seems better https://github.com/open-telemetry/opentelemetry-java/pull/3684. So don't think we should try excluding.
