### ISSUE TITLE
One too many caffeines

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4251]
Looking at the javaagent jar, it looks like we have 3 caffeines, when I think we are only expecting 2:

```
io/opentelemetry/javaagent/shaded/instrumentation/api/internal/shaded/caffeine
io/opentelemetry/javaagent/shaded/instrumentation/api/internal/shaded/caffeine2
io/opentelemetry/javaagent/shaded/instrumentation/api/internal/shaded/caffeine3
```

**Comment by laurit** [comment]
Latest snapshot at https://oss.sonatype.org/content/repositories/snapshots/io/opentelemetry/javaagent/opentelemetry-javaagent/1.7.0-SNAPSHOT/ doesn't seem to have it. I had it locally but it went away after a clean build. @trask could you check whether cleaning fixes this for you too.

**Comment by trask** [comment]
@laurit 👍
