### ISSUE TITLE
Consider removing VirtualField.computeIfNull()

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4268]
Carrying PR discussion forward from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4262#discussion_r720273948.

The atomicity guarantee for `VirtualField.computeIfNull` requires a lock, which has led to problems (#4188).

Just dropping the atomicity guarantee is an option, but it could be confusing to have a method that looks like it provides atomicity signature-wise, but really doesn't (https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4192#issuecomment-925558692).

And if it doesn't provide atomicity anyways, usage of `computeIfNull` can be replaced by calls to `get` and `set`.

**Comment by mateuszrzeszutek** [comment]
I've started working on that and removed almost all usages of `computeIfNull` - the only one left is `ExecutorAdviceHelper#attachContextToTask()` - I think it may actually be needed here; it ensures (atomically) that a `PropagatedContext` is always present, and the `PropagatedContext` class actually manages the state/context.

I think we can remove the `PropagatedContext` class together with the `computeIfNull` method if we simply provide a `compareAndSet` method on the `VirtualField` (using an `AtomicReferenceFieldUpdater` in the generated implementation)
