### ISSUE TITLE
Add GraphQL Java Instrumentation

### ISSUE THREAD

**Issue by jord1e** [open-telemetry/opentelemetry-java-instrumentation#4270]
**Is your feature request related to a problem? Please describe.**
[GraphQL Java](https://github.com/graphql-java/graphql-java)  is an essential library for building GraphQL API’s in Java and Kotlin (and other JVM languages, of course).

It powers the following projects:
- [**Spring GraphQL** (experimental)](https://spring.io/projects/spring-graphql)
- [DGS framework by Netflix](https://github.com/Netflix/dgs-framework)
- [graphql-kotlin by Expedia](https://github.com/ExpediaGroup/graphql-kotlin)

The library needs proper observability.

**Describe the solution you'd like**
Javaagent and [native instrumentation](https://www.graphql-java.com/documentation/v17/instrumentation/) added to OpenTelemetry.
Instrumentation is already present for JavaScript and Ruby, [go instrumentation has been proposed](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1046)

Considering the fact that [no semantic conventions have yet to be adopted](https://github.com/open-telemetry/opentelemetry-specification/issues/1670), I propose we reuse the span names/events used by the NodeJS OpenTelemetry instrumentation. 

**Describe alternatives you've considered**
N/A

**Additional context**
I would be prepared to create a pull request to add **javaagent** instrumentation, please let me know if this is acceptable.
This will probably take some time. I expect to have time beginning next month.
Considering [that java-instrumentation-contrib guidelines aren’t yet clear](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3505) I will create the PR in this repository.

**Comment by anuraaga** [comment]
Thanks @jord1e - this seems like important instrumentation and I think this repo is appropriate. A PR would be greatly appreciated - but please start with what we call library instrumentation which would implement that Instrumentation hook. Especially when the library provides the hook, we prioritize using it, since javaagent then just auto-registers the library instrumentation. Would that be ok for you?

**Comment by jord1e** [comment]
I will look into it somewhere this week or next week and come back with a formal proposal.
