### ISSUE TITLE
Custom API is not getting instrumented by using @WithSpan annotation

### ISSUE THREAD

**Issue by aniruddhahanchate** [open-telemetry/opentelemetry-java-instrumentation#4307]
**Describe the bug**
@WithSpan is not instrumenting the API when added to an API.

**Steps to reproduce**
1. I am using java agent version 1.6.2 and added the agent as -javaagent to my application. 
2. It instrumented the application.
3. Exported the traces to zipkin and I could see it.
4. I added opentelemetry-api.jar and opentelemetry-extension-annotations.jar of version 1.6.0. And added @WithSpan to custom API's. 
5. The trace is getting created but **I don't see custom API in the trace though.**
6. But when I added -Dotel.instrumentation.methods.include to include some of my custom api's to instrument. I can see the custom api's in trace.

**What did you expect to see?**
When I add @WithSpan to API, I should see the custom API in the trace.

**What did you see instead?**
Although I am using 1.6.2 version of SDK with dependent jars opentelemetry-api.jar (1.6.0) and opentelemetry-extension-annotations.jar (1.6.0). And added @WithSpan to custom API, I don't see custom API in trace

**What version are you using?**
opentelemetry-javaagent-all 1.6.2
opentelemetry-extension-annotations 1.6.0
opentelemetry-api 1.6.0

**Environment**
It is reproducible in all environments

**Additional context**

**Comment by mateuszrzeszutek** [comment]
Hey @aniruddhahanchate ,
Can you post an example of how you're using it? Or a small repro application that'll help us locating the issue.

**Comment by trask** [comment]
Closing, but let us know if you are still having the issue and we will re-open.
