### ISSUE TITLE
Move io.opentelemetry.instrumentation.api.servlet to servlet-common

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#4317]
`io.opentelemetry.instrumentation.api.servlet` package from `instrumentation-api` module is used only by servlets and some methods from it are used only from `servlet-common` module. We can move that package closer to its usage and hide those methods from general public, who should not be concerned with them.

Thoughts? I can do it if get enough support.

**Comment by laurit** [comment]
Wouldn't it make sense to split api into public and internal. Internal api could contain classes that are not ready to be used outside the agent like `ServerSpanNaming` which wouldn't work without bridging context key. Or we could move internal apis under `javaagent-bootstrap`.
