### ISSUE TITLE
Java 8u31 and earlier crash with Java agent

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4326]
See error below, and full [hs_err_pid.log](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/7307234/hs_err_pid6796.log) attached.

I suspect it is this JDK bug: https://bugs.openjdk.java.net/browse/JDK-8044737

Related #4196

At this point I'm wondering if it's best to just log and disable the java agent if we detect 8u31 or earlier.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00000000037a7d54, pid=6796, tid=9208
#
# JRE version: OpenJDK Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
# Java VM: OpenJDK 64-Bit Server VM (25.31-b07 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# J 807 C2 io.opentelemetry.javaagent.extension.matcher.ClassLoaderHasClassesNamedMatcher.matches(Ljava/lang/Object;)Z (9 bytes) @ 0x00000000037a7d54 [0x00000000037a7d00+0x54]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# [hs_err_pid6796.log](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/7307233/hs_err_pid6796.log)
Compiled method (c1)    3898  968       2       io.opentelemetry.javaagent.extension.matcher.ClassLoaderHasClassesNamedMatcher$$Lambda$81/1998103567::get$Lambda (9 bytes)
 total in heap  [0x00000000037f60d0,0x00000000037f6430] = 864
 relocation     [0x00000000037f61f0,0x00000000037f6218] = 40
 main code      [0x00000000037f6220,0x00000000037f6320] = 256
 stub code      [0x00000000037f6320,0x00000000037f63b0] = 144
 oops           [0x00000000037f63b0,0x00000000037f63b8] = 8
 metadata       [0x00000000037f63b8,0x00000000037f63d0] = 24
 scopes data    [0x00000000037f63d0,0x00000000037f63e8] = 24
 scopes pcs     [0x00000000037f63e8,0x00000000037f6428] = 64
 dependencies   [0x00000000037f6428,0x00000000037f6430] = 8
#
# If you would like to submit a bug report, please visit:
#   http://www.azulsystems.com/support/
#
```

**Comment by laurit** [comment]
https://bugs.openjdk.java.net/browse/JDK-8044737 isn't the correct bug as it is a javac bug.
I'd say this has the same cause as https://bugs.openjdk.java.net/browse/JDK-8041920 although the dump looks a bit different. Basically what that bug says is that when you use a lambda or anything that initializes `java.lang.invoke.CallSite` or possibly some other java.lang.invoke classes inside javaagent premain lambdas will breaks when they get jit compiled. This crash does not happen with `-Xint` or `-XX:CompileCommand=exclude,java/lang/invoke/LambdaForm$*.invoke*`.
Even when we remove lambda usage from `ClassLoaderHasClassesNamedMatcher` it will still crash when a lambda gets compiled. I don't think we can realistically track down and get rid of all the lambdas that could be used before premain completes unless we retrotranslate, which I doubt anybody really wants to do. An alternative hack that could circumvent this would be to make agent premain retransform `LauncherHelper.checkAndLoadMain` https://github.com/openjdk/jdk8u/blob/41667c086f755ebbb5dde6ae2609e6d550b5d71f/jdk/src/share/classes/sun/launcher/LauncherHelper.java#L581 and insert a callback there that would really start the agent. This way we could have a small piece of code that we can make sure doesn't use lambdas that sets up the hook and rest of the agent startup could remain as is. Though as our bytecode library classes are in `inst/` it would still require quite a bit of gymnastics to make it work.
Not supporting early 1.8 versions is definitely the easy way out.

**Comment by iNikem** [comment]
Here is the warning that we used to have in Plumbr
```
*******************************************************************************************************
* There is a known issue with Java versions 1.8.0 - 1.8.0_31 where using Java agents                  *
* together with code that uses dynamic invocation (such as lambdas or dynamic languages)              *
* may cause segmentation faults. If these are not used in your application, your JVM may be safe,     *
* but for production sites we do not recommend using Plumbr with Java 8 versions older than 1.8.0_40. *
* To make sure this problem will not occur, either:                                                   *
*   a) Upgrade your Java version to 1.8.0_40 or newer                                                 *
*   b) If upgrading Java version is not possible, turn off JIT compilation for java.lang.invoke       *
* package by specifying -XX:CompileCommand=exclude,java/lang/invoke/ in your JVM startup script.      *
*******************************************************************************************************
```

**Comment by anuraaga** [comment]
@iNikem Just to confirm did the plumbr agent support java pre-8?

I do remember the old versions of Java where javac wouldn't even compile my lambda... While it sounds like this may be different from the javac issue I'd prefer to avoid wording about disabling JIT and just have the message focus on upgrading. I don't think in this age we should be putting effort into integration tests for a specific JVM flag on such an old JRE. I have a feeling it could be different for an agent that supports java 7. Since we only support java 8, only working on a functional java 8 (40+) seems ok.
