### ISSUE TITLE
Inconsistent handling of peer port in http client instrumentation

### ISSUE THREAD

**Issue by laurit** [open-telemetry/opentelemetry-java-instrumentation#4329]
Some http clients that extract peer info from URL/URI such as https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/63a2383905da81229f6e9984d7079c2fd9b6b53d/instrumentation/java-http-client/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpclient/JdkHttpNetAttributesExtractor.java#L42 set port based on the default used by protocol while others don't https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/63a2383905da81229f6e9984d7079c2fd9b6b53d/instrumentation/http-url-connection/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/httpurlconnection/HttpUrlNetAttributesExtractor.java#L27 this one will report `net.peer.port=-1`.

**Comment by mcmho** [comment]
@laurit,   how do you think we can standardize them?  is it a bug?  if so, i can take a crack at it.

**Comment by laurit** [comment]
@mcmho Feel free to give it a try. To track down instrumentations that set port to `-1` see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/5e1e0c26423d408bfa26068c17eef0443b054607/testing-common/src/main/java/io/opentelemetry/instrumentation/testing/junit/http/AbstractHttpClientTest.java#L905-L907

**Comment by anchalpuri20** [comment]
@laurit is this issue still exists, since the said files are not present anymore in the project.

**Comment by laurit** [comment]
@anchalpuri20 I believe it is still present, those files were renamed from extractor -> getter
