### ISSUE TITLE
Instrumenter instrumentation version and schema url

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java-instrumentation#4333]
I was browsing `Instrumenter` code and noticed that the the instrumentation version passed when obtaining the tracer is `Instrumentation.VERSION`. See code [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/Instrumenter.java#L85).

My understanding is that the goal is to have folks instrument their libraries with `Instrumenter`, in which case it will be incorrect to include the version of the artifact that contains `Instrumenter`. We'll want callers to specify the version of the library they're instrumenting, right?

Also noticed:
- No version is passed when [obtaining a meter provider](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/InstrumenterBuilder.java#L69). We'll probably want to be consistent.
- No optional is available for specifying the schema url in the tracer or meter. And what should the schema url be anyway? The `Instrumenter` provides tools to make it easier to follow the semantic conventions, but someone could use it and still violate them. 

Just wanted to call these out so we can sort out the desired behavior.

**Comment by laurit** [comment]
version added in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4611
> My understanding is that the goal is to have folks instrument their libraries with `Instrumenter`, in which case it will be incorrect to include the version of the artifact that contains `Instrumenter`. We'll want callers to specify the version of the library they're instrumenting, right?

It should be the version of instrumentation library not the version of instrumented library
