### ISSUE TITLE
Allow adding custom conditions to `Instrumenter#shouldStart()`

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#4389]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to embed some additional conditions into the `Instrumenter#shouldStart()` method. There are several instrumentations that have additional checks (netty-4.1 client, jaxrs-1.1, cxf, ...)

**Describe the solution you'd like**
We could add an additional interface that accepts `(REQUEST, Context)` and returns a boolean - and add a new configuration knob for it to the `InstrumenterBuilder`.

**Describe alternatives you've considered**
Leave the code in those instrumentations as it is.

**Additional context**
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4381#discussion_r728818659

**Comment by trask** [comment]
Closing, I think this has been addressed by span suppression mechanism.
