### ISSUE TITLE
Rename all `newBuilder()` method to `builder()`

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#4392]
**Is your feature request related to a problem? Please describe.**
I've noticed that the API & SDK uses the `builder()` name for the method that returns a new object builder. E.g. `Attributes#builder()`, `Baggage#builder()`, `OpenTelemetrySdk#builder()`. We should strive for consistency and do the same thing in all public APIs:
* `Instrumenter#newBuilder()` -> `Instrumenter#builder()`
* `...Tracing#newBuilder()` -> `...Tracing#builder()`

**Comment by iNikem** [comment]
Closed by #4407
