### ISSUE TITLE
JMS 2 tracing

### ISSUE THREAD

**Issue by xificurC** [open-telemetry/opentelemetry-java-instrumentation#4397]
**Is your feature request related to a problem? Please describe.**
Spring JMS uses JMS 2 and we'd like to get traces from it

**Describe the solution you'd like**
Add instrumentation for JMS 2

**Describe alternatives you've considered**
Spring Sleuth has tracing, but only for Brave. I didn't find any way to convert those to otel traces.

**Comment by laurit** [comment]
We already have some jms2 tests that produce traces. Could you elaborate why existing instrumentation does not work for you. A small sample application that reproduces the issue would be extremely helpful.

**Comment by xificurC** [comment]
Thanks for the prompt response. We didn't try generating traces, the name "jms-1.1" seemed to imply 2 is not supported. We'll try it out next week and let you know.

**Comment by trask** [comment]
hi @xificurC, you can see list of supported libraries and versions here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks
