### ISSUE TITLE
HttpServerTracer endExceptionally sets status code 500

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java-instrumentation#4401]
**Describe the bug**
As the title says, [HttpServerTracer#endExceptionally](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/HttpServerTracer.java#L137-L138) sets the status code to 500 if the response is null. This is potentially incorrect, since it assumes that if an exception is thrown and the instrumentation point is unable to access a `response`, that the library being instrumented will return a 500 status code. If the library does something different, then the status code we're associated with traces in wrong. 

The `Instrumenter` behavior is different. If `response` is null, it doesn't set any status code at all. This behavioral difference between the API can cause test failures when converting instrumentation from `*Tracer` to `Instrumenter`, as discussed [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4359#discussion_r727309237).

The behavior of the `Instrumenter` seems more correct than `HttpServerTracer`. If so we'll want to update the test cases that assert `500` status code to be more accommodating.

**Comment by trask** [comment]
> Even better, let us finish our migration to the `Instrumenters` :)

I think we still need to decide on behavior here. For servlets, currently we make an "educated prediction" (https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4359#discussion_r729705886). This has the downside of possibly being wrong, which definitely isn't great. On the other hand, in practice it's usually right, and not flagging the request as an error when it is an error also definitely isn't great.

**Comment by mateuszrzeszutek** [comment]
> I remember that servlet spec requires to set 500 status in this case, no?

It seems so:

>       // if response is not committed and there is a throwable set status to 500 /
>      // INTERNAL_SERVER_ERROR, due to servlet spec
>      // https://javaee.github.io/servlet-spec/downloads/servlet-4.0/servlet-4_0_FINAL.pdf:
>      // "If a servlet generates an error that is not handled by the error page mechanism as
>      // described above, the container must ensure to send a response with status 500."

WDYT about making `statusCode` accept both response and error?

```java
  protected abstract Integer statusCode(REQUEST request, @Nullable RESPONSE response, @Nullable Throwable error);
```

This way it'll be possible to properly instrument frameworks that communicate the status code via thrown exceptions (if there're any)

**Comment by laurit** [comment]
> > I remember that servlet spec requires to set 500 status in this case, no?
> 
> It seems so:
> 
> > ```
> >   // if response is not committed and there is a throwable set status to 500 /
> >  // INTERNAL_SERVER_ERROR, due to servlet spec
> >  // https://javaee.github.io/servlet-spec/downloads/servlet-4.0/servlet-4_0_FINAL.pdf:
> >  // "If a servlet generates an error that is not handled by the error page mechanism as
> >  // described above, the container must ensure to send a response with status 500."
> > ```
Actually servlet instrumentation can also set wrong status as it runs before error page mechanism which can change the status from `500` to something else.

**Comment by mateuszrzeszutek** [comment]
I think we can close this issue: `HttpServerTracer` does not exist anymore, and the HTTP attributes extractors do not set status code if the response was not received.
