### ISSUE TITLE
`http.route` attribue

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#442]
[Semantic convention for HTTP server spans](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions) defines attribute `http.route`: 

> The matched route (path template). E.g. "/users/:userID".

Currently instrumentations don't create this attribute. I think we should, but I am not quite sure which span should have this attribute. In case of a typical Java web application the first span created will usually come from generic middleware, such as Servlets or similar. It has no notion of route yet, just the full URL. Then, when request processing reaches actual web framework, such as Spring or jax-rs, second span will be created (potentially with `kind=INTERNAL`). At this point instrumentation can get used route information from the framework. 

Where this attribute should now go? To parent span of kind SERVER (which has all other http attributes like `http.url` and `http.method`) or to a current span of kind INTERNAL, which has no other `http` attributes?

**Comment by trask** [comment]
I believe it should go on the `SERVER` span.

We already have instrumentation to capture the route as part of the `SERVER` span name ([to conform with the _current_ span name guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#name)), so I think this would be added in the same places in the code, calling now `span.setAttribute("http.route", ...)` in addition to `span.updateName(...)`.

**Comment by iNikem** [comment]
@tylerbenson said during last Java SIG meeting that he really dislikes this inter-instrumentation communication, when we modify already existing spans. And I tend to agree with him. If we continue to do this, we HAVE to do that in more explicit and transparent way. Which I don't know yet :)

Can we always be sure that SERVER span is still present when we create child spans? Can it happen that in some async processing server span will be already sent out to collector?

**Comment by iNikem** [comment]
Also, modifying existing spans goes against e.g. #388. Also https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#span says:
> It is highly discouraged to update the name of a Span after its creation. Span name is often used to group, filter and identify the logical groups of spans. And often, filtering logic will be implemented before the Span creation for performance reasons. Thus the name update may interfere with this logic.

**Comment by trask** [comment]
The primary reason that `updateName()` exists is to handle this example, where you don't know the route when the `SERVER` span starts, and so initially you set the span name to something generic (like in #428), and then later when you know the route, you call `updateName()` on the `SERVER` span to set the span name to the route.

(also, see https://github.com/open-telemetry/opentelemetry-specification/issues/468 which is proposing to remove that warning about updating the name of a Span)

**Comment by iNikem** [comment]
Ok, I see your point. But in this case I think we still need much clearer and more explicit way for any span to find parent/root span. Current approach is too well hidden and non-obvious.

**Comment by trask** [comment]
Nice, #465 will also solve this 👍

**Comment by sirianni** [comment]
The absence of the `http.route` label is one of the things blocking us from migrating off of https://github.com/DataDog/dd-trace-java to this library.  According to Datadog, the `http.route` label is used to categorize endpoints for the APM UI.

**Comment by mateuszrzeszutek** [comment]
A couple of TODOs from #5086:
- [ ] Move and rename `ServerSpanNaming`
- [ ] Use `http.route` in `HttpServerMetrics`
- [ ] Consider extracting the route from `Context` in `HttpServerAttributesExtractor#onEnd()` - that'd require adding `Context` to the parameter list though
- [ ] Use `ServerSpanNaming` (or whatever it's renamed to) in spark instrumentation
- [ ] Use `ServerSpanNaming` (or whatever it's renamed to) in vertx-web instrumentation
- [ ] Refactor `HttpServerTest` and get rid of `extraAttributes()`
- [ ] Expected server span name for null route should probably be `HTTP GET`, not `getContextPath() + "/*"` (`HttpServerTest`)
