### ISSUE TITLE
Using http tracing exporter

### ISSUE THREAD

**Issue by stanosamek** [open-telemetry/opentelemetry-java-instrumentation#4441]
Hi,

I have problem with configuring agent to sending traces via http and not with grpc. I'm using version 1.7.0.

This is the command which I'm starting the application with parameters;

/opt/app/java/jdk/bin/java -javaagent:opentelemetry-javaagent-all.jar '-Dotel.resource.attributes=service.name=foo -Dotel.exporter.otlp.endpoint=https://opentelemetry-collector.apps.os23v02.bar.slsp.sk/v1/traces -Dotel.traces.exporter=otlp -Dotel.metrics.exporter=none -Dotel.exporter.otlp.traces.protocol=http/json' -jar example.jar

This is error message which I'm receiving.

[otel.javaagent 2021-10-20 11:47:44:169 +0200] [BatchSpanProcessor_WorkerThread-1] ERROR io.opentelemetry.exporter.otlp.internal.grpc.DefaultGrpcExporter - Failed to export spans. Server is UNAVAILABLE. Make sure your collector is running and reachable from this network. Full error message:UNAVAILABLE: io exception

Why is the agent sending traces via grpc and not through http protocol? 

Thank you

**Comment by iNikem** [comment]
First of all, please try without ' marks around system properties.

**Comment by stanosamek** [comment]
I'm so sorry about my mistake. It was problem with ' marks like you wrote.

**Comment by AkselAllas** [comment]
`-Dotel.exporter.otlp.traces.protocol=http/json` doesnt work anymore

It needs to be `-Dotel.exporter.otlp.traces.protocol=http/protobuf` now 🤔
