### ISSUE TITLE
Remove HttpStatusConverter

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-instrumentation#4447]
In #4403, it was brought up that the `HttpStatusConverter` is a more legacy interface from the tracing api. The tracing api has not fully been removed, but we are getting close. Once that happens, we think we want to remove `HttpStatusConverter`.

Even with the tracers removed, this will be a bit tricky due to a few items:

* Some tests rely on it
* `HttpUrlConnectionInstrumentation` still uses it
*  #4403 introduces a dependency on it from `HttpSpanStatusExtractor`. We think this can be mitigated by splitting `HttpSpanStatusExtractor` into `HttpServerSpanStatusExtractor` and `HttpClientSpanStatusExtractor` and inlining what's in `HttpStatusConverter` (perhaps exposing it thru a static method for use as a utility).

**Comment by mateuszrzeszutek** [comment]
Looks like this was done in #5268
