### ISSUE TITLE
Android regression in okhttp instrumentation in 1.7.0

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#4452]
**Describe the bug**
It appears that the okhttp3 instrumentation released in v1.7.0 contains a usage of java's `MethodHandle` which is not supported on Android before API level 'O' (API level 26). 

**Steps to reproduce**
Do an android app build using the v1.7.0-alpha version of the okhttp3 instrumentation. Example build failure is here: https://github.com/signalfx/splunk-otel-android/pull/176

**What did you expect to see?**
The build to succeed, and the Android gradle plugin is able to generate Android bytecode.

**What did you see instead?**
```
ERROR:/Users/jwatson/.gradle/caches/modules-2/files-2.1/io.opentelemetry.instrumentation/opentelemetry-instrumentation-api/1.7.0-alpha/d5e265ff68ba58266a61ef62730e142e32635a3f/opentelemetry-instrumentation-api-1.7.0-alpha.jar: D8: com.android.tools.r8.internal.n1: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
```

**What version are you using?**
v1.7.0-alpha

**Environment**
Android Gradle Plugin version 7.0.3, targetting Android API level 21.

**Additional context**
N/A

**Comment by laurit** [comment]
Fixed in 1.9.0
