### ISSUE TITLE
Instrumentation support for Netty based Async Http Client (AHC)

### ISSUE THREAD

**Issue by ksameersrk** [open-telemetry/opentelemetry-java-instrumentation#446]
I see that currently there is no support for the [Netty based Async Http Client (AHC)](https://github.com/AsyncHttpClient/async-http-client). Not sure if this was tried earlier or it is not possible to support it. Anyways, I would love to take a stab at it. Please let me know your opinion. Thanks.

**Comment by trask** [comment]
Hi @ksameersrk!

Interestingly, we have instrumentation for `play.shaded.ahc.org.asynchttpclient.AsyncHttpClient` (see [BasePlayWSClientInstrumentation.java](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/instrumentation/play-ws/play-ws-common/src/main/java/io/opentelemetry/auto/instrumentation/playws/BasePlayWSClientInstrumentation.java#L34)), but you're right, no vanilla AHC.

I'd say definitely, go for it, and ping us either here or on the gitter channel if you need any help: https://gitter.im/open-telemetry/opentelemetry-auto-instr-java

**Comment by ksameersrk** [comment]
Sure, that is great @trask ! I will look into [BasePlayWSClientInstrumentation](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/instrumentation/play-ws/play-ws-common/src/main/java/io/opentelemetry/auto/instrumentation/playws/BasePlayWSClientInstrumentation.java#L34). Thanks for the info.

**Comment by trask** [comment]
Closing, I noticed the netty instrumentation tests use AsyncHttpClient to verify the netty instrumentation 👍
