### ISSUE TITLE
JaxRS instrumentation not capturing `http.route` attribute

### ISSUE THREAD

**Issue by sirianni** [open-telemetry/opentelemetry-java-instrumentation#4494]
**Describe the bug**
The `http.route` attribute is not populated in JaxRS (jersey) spans.

**Steps to reproduce**
Run any jersey/jax-rs "hello world" app. 

**What did you expect to see?**
A span with `http.route` attribute set.

**What did you see instead?**
The span did not have the `http.route` attribute set.

**What version are you using?**
1.7.0

**Additional context**
I don't see a Jaxrs implementation of a HttpServerAttributesExtractor.  Seems odd that the JaxRS/Jersey instrumentation is not aligned with all of the other server-side REST frameworks.

**Comment by sirianni** [comment]
Related discussion https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4556#issuecomment-957240496

**Comment by mateuszrzeszutek** [comment]
Fixed by #5086
