### ISSUE TITLE
Share code and tests with contrib instrumentation

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#45]
Some things we could probably share with contrib instrumentation:

* The decorator hierarchy
* HttpTextFormat Getters and Setters
* OkHttp3 interceptor
* MongoDB listener
* tests!

**Comment by trask** [comment]
Linking in #195
Linking in https://github.com/open-telemetry/opentelemetry-java/pull/964

**Comment by anuraaga** [comment]
If there's agreement on the direction for this issue, I could help do some moving. Perhaps I could start by moving the decorators into `opentelemetry-java`?

**Comment by trask** [comment]
Hi @anuraaga, help on this would be great!

I think it will be easier to share code and tests between auto and manual instrumentation if they are in the same repo, at least short-term while we are figuring out how to share.

Have a look at #195. I think the first step is to take one of the simpler instrumentations, and extract out the generic bits using that model.

You'll end up with 3 modules: one module with the generic parts, one module with the manual instrumentation, and (the existing) module with the auto-instrumentation that now depends on the module with the generic parts.

We definitely want to share tests between manual and auto-instrumentation as well, so that's another challenge to work through with this first instrumentation.

**Comment by trask** [comment]
Closing this now, good progress is being made on this in several other issues and PRs. And this issue has outlived its usefulness.
