### ISSUE TITLE
Create a "bot" user in Bintray

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#452]
We need an account in Bintray in [OpenTelemetry organisation](https://bintray.com/open-telemetry) to publish our artefacts. Ideally we could use the same user to publish artefacts from `opentelemetry-java` repo as well. And it should not be some personal account, I think, but a dedicated one.

Depending on Bintray's pricing/capabilities, other languages can publish their artefacts there as well, using the same shared bot user.

**Comment by carlosalberto** [comment]
I was digging into this and a Bintray account needs to be backed up by either a Google account or a Github profile (the second one in turn requires an email). Sonatype account also requires an email.

With that in mind I see two options:

1) We keep the user specific deployment (as it is done in many OSS projects). This is what we do at this moment, but we would need to add more maintainers (Trask, etc).
2) We create a Google Account (opentelemetry-java@gmail.com?) to create the Bintray/Sonatype accounts and use that from now on for all our Java projects.

@bogdandrutu any point against going for 2) ?

**Comment by iNikem** [comment]
If we can use the same Bintray organisation, OpenTelemetry, for publishing artefacts from other languages as well, then having language-specific user is probably not a very good idea.

**Comment by bogdandrutu** [comment]
We added all the maintainers for instrumentation and java repos to the betray account.
