### ISSUE TITLE
Automatically append baggage entries to span attributes

### ISSUE THREAD

**Issue by stanosamek** [open-telemetry/opentelemetry-java-instrumentation#4520]
Hi,

like we were discussing about adding configuration for adding baggage entries as span attributes to every span in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/4518 or https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/4351. It would be great to have some configuration for turning on or off adding baggage entries to spans.  

Currently we are not able to propagate baggage entries. Except for creating custom extension.

Actually we are not able to create some analytical solution without these baggage entries.

Thank you

**Comment by MALPI** [comment]
hey @trask,

I'm slightly confused. Is the feature of baggage item propagation in general available or not. The two discussions referenced are contradicting each other?

Best

**Comment by trask** [comment]
Baggage is automatically propagated, but is not automatically attached as span attributes when exporting

**Comment by MALPI** [comment]
Thanks for confirming. If you can give me a hint in which direction I should search, I would give it a try to implement.

**Comment by cuichenli** [comment]
just out of curious, should this be done on the sdk side or the instrumentation side?

**Comment by mateuszrzeszutek** [comment]
OpenTelemetry SDK only includes [specced components](https://github.com/open-telemetry/opentelemetry-java/blob/main/CONTRIBUTING.md#project-scope). This feature (appending baggage as span attributes) probably fits either this repo or contrib more (contrib seems to be a somewhat more suitable place now that I think of it; cause it's not an instrumentation).
