### ISSUE TITLE
Why two manual instrumentation pages?

### ISSUE THREAD

**Issue by chalin** [open-telemetry/opentelemetry-java-instrumentation#4524]
We currently have _two_ **manual instrumentation** pages?

- This one published on the website, https://opentelemetry.io/docs/instrumentation/java/manual_instrumentation/
- https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/manual-instrumentation.md

Can these be consolidated?

/cc @austinlparker

**Comment by chalin** [comment]
@cartermp WDYT?

/cc @trask

**Comment by cartermp** [comment]
This one looks like it's primarily about using the annotations package instead of the APIs directly. It's pretty neat and I think should be documented in the docs, but it'd be good to learn what Java SIG folks think of this package and how to recommend using it.

**Comment by trask** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/manual-instrumentation.md is targeted at javaagent users who want to add a bit of additional manual instrumentation on top of what the javaagent already collects.

The annotation API requires using the javaagent (or, with some restrictions, [opentelemetry-spring-boot-autoconfigure](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring/spring-boot-autoconfigure#opentelemetry-spring-auto-configuration)), so maybe make this a child of the "Automatic" page?

**Comment by cartermp** [comment]
@trask awesome to know, thank you. I think your suggest makes the most sense.

**Comment by cartermp** [comment]
@chalin this can be closed
