### ISSUE TITLE
HTTP server duration metrics per connection instead of accumulative 

### ISSUE THREAD

**Issue by harel-e** [open-telemetry/opentelemetry-java-instrumentation#4525]
**Describe the bug**

http.server.duration metrics contains net.peer.* attributes
This leads to histogram per connection, instead of accumulative one (or one per host)
Beyond the fact that such histogram is not useful, the metrics exporter kept adding histogram for every client connection that the application made. I quickly got to hundreds of histograms in a sample application.

**Steps to reproduce**

auto-Instrument java code that makes http requests (I used RestTemplate) 

**What did you expect to see?**

I expect to see one histogram http_server_duration_count for all client connections (or optionally one per http_host destination)

**What did you see instead?**

I saw histogram buckets per connection

[metrics.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/7427362/metrics.txt)

**Prometheus exporter example**

http_server_duration_count{http_flavor="1.0",http_host="localhost:8080",http_method="GET",http_scheme="http",http_
server_name="localhost",http_status_code="200",net_peer_ip="0:0:0:0:0:0:0:1",net_peer_name="localhost",net_peer_port="54566",} 1.0
http_server_duration_sum{http_flavor="1.0",http_host="localhost:8080",http_method="GET",http_scheme="http",http_server_name="localhost",http_status_code="200",net_peer_ip="0:0:0:0:0:0:0:1",net_peer_name="localhost",net_peer_port="54566",} 1145.918858
http_server_duration_bucket{http_flavor="1.0",http_host="localhost:8080",http_method="GET",http_scheme="http",http_server_name="localhost",http_status_code="200",net_peer_ip="0:0:0:0:0:0:0:1",net_peer_name="localhost",net_peer_port="54566",le="5.0",} 0.0
... more buckets

http_server_duration_count{http_flavor="1.0",http_host="localhost:8080",http_method="GET",http_scheme="http",http_server_name="localhost",http_status_code="200",net_peer_ip="0:0:0:0:0:0:0:1",net_peer_name="localhost",net_peer_port="54582",} 1.0
... more buckets

http_server_duration_count{http_flavor="1.0",http_host="localhost:8080",http_method="GET",http_scheme="http",http_server_name="localhost",http_status_code="200",net_peer_ip="0:0:0:0:0:0:0:1",net_peer_name="localhost",net_peer_port="54567",} 1.0

**What version are you using?**

1.7.0

**Environment**

JDK : OpenJDK 64-Bit Server VM Temurin-11.0.12+7
OS: MacOS 11.6

**Additional context**

I understand the value of these attributes with tracing, but not with metrics.

**Comment by trask** [comment]
cc: @jsuereth

**Comment by jsuereth** [comment]
PTAL at https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4556 and weight in

**Comment by mateuszrzeszutek** [comment]
`net.peer.*` attributes are no longer used in HTTP server metrics - fixed by #4556
