### ISSUE TITLE
Remove caffeine from instrumentation-api to make it work on Android

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#4532]
**Is your feature request related to a problem? Please describe.**
Caffeine doesn't work on Android, using it will break library instrumentations (like okhttp3) that are supposed to be used on Android.
Animalsniffer detects a lot of classes in caffeine2 that are not present in android: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4505

**Describe the solution you'd like**
The current idea to solve this issue is to vendor in https://github.com/ben-manes/concurrentlinkedhashmap and move caffeine 2 & 3 to agent bootstrap -- so that when the javaagent is used the optimal cache implementation is chosen.

**Comment by iNikem** [comment]
> The current idea to solve this issue is to vendor in https://github.com/ben-manes/concurrentlinkedhashmap and move caffeine 2 & 3 to agent bootstrap -- so that when the javaagent is used the optimal cache implementation is chosen.

But that cache does not support weak keys, is it ok for us? @anuraaga ?

**Comment by anuraaga** [comment]
@iNikem I think the idea was to not use bounded caches with weak keys anymore, so always use the WeakLockFree map. Do we have any bounded ones where removing the bound seems like it would cause a problem?

**Comment by iNikem** [comment]
Now I am even more confused :D This ticket says to use concurrentlinkedhashmap, you are saying to use existing WeakLockFree, meeting notes from the last week say use concurrentlinkedhashmap or cache2k.

If we move Caffeine behind SPI, what will be our default cache implementation for library instrumentations? Can we get that consensus? :)

**Comment by anuraaga** [comment]
Think we might have missed it from the notes, but I think wanted to split the entrypoint into two

- One for bounded caches without weak keys
- One for weak keys without a bound

Always use WeakLockFree for latter, use either ConcurrentLinkedHashMap (or maybe cache2k) or Caffeine based on an SPI for former.

I guess the default for library instrumentation bounded cache would be ConcurrentLinkedHashMap since including is a bit simpler than excluding.

**Comment by iNikem** [comment]
So we want 3 cache implementations??

**Comment by mateuszrzeszutek** [comment]
I think we want two types of cache:
1. An unbounded weak-keyed cache
2. A bounded, strong keys & values cache

So 2 different interfaces/APIs basically.
Weaklockfree would be the only implementation for cache type 1., while ConcurrentLinkedHashMap/cache2k/caffeine would be implementations of type 2.

**Comment by mateuszrzeszutek** [comment]
Implemented in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4667
