### ISSUE TITLE
java agent with prometheus

### ISSUE THREAD

**Issue by somayaj** [open-telemetry/opentelemetry-java-instrumentation#4551]
Started promethus ui/collector on port 9090. no changes to the defaults.The agent jar also has been added to a sample spring app jar, downloaded with just webmvc from spring initialzer. The agent starts up as expected with the following command line, 
java -javaagent:../../opentelemetry-javaagent-all.jar -jar demo-0.0.1-SNAPSHOT.jar -Dotel.exporter=prometheus

logs: OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2021-10-30 18:48:08:375 -0500] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.7.1

When I hit an HTTP endpoint I should see that trace in the application trace but I see an error log as the below, 
[grpc-default-executor-1] ERROR io.opentelemetry.exporter.otlp.internal.grpc.DefaultGrpcExporter - Failed to export spans. Server is UNAVAILABLE. Make sure your collector is running and reachable from this network. Full error message:UNAVAILABLE: io exception

I assume I'm missing some Prometheus configuration here? Please advise, 

Thanks, 
Asha

**Comment by somayaj** [comment]
Update: Same error with zipkin. all default settings.

**Comment by harel-e** [comment]
@somayaj - The command line parameters that you provided are not valid. The agent defaulted to use OTLP exporter.
 If you want to export just metrics to prometheus, use 

-Dotel.metrics.exporter=prometheus
-Dotel.traces.exporter=none

See config reference at: [OpenTelemetry SDK Autoconfigure](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-both-span-and-metric-exporters)

**Comment by somayaj** [comment]
Hi Efraim, I used the http://localhost:9411/api/v2/spans http endpoint that
it defaults to for zipkin with these
command line:

java -javaagent:../../opentelemetry-javaagent-all.jar -jar
demo-0.0.1-SNAPSHOT.jar -Dotel.traces.exporter=zipkin
-Dotel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans
-Dotl.traces.exporter=none

error log:

[otel.javaagent 2021-10-31 14:10:13:370 -0500] [grpc-default-executor-1]
ERROR io.opentelemetry.exporter.otlp.internal.grpc.DefaultGrpcExporter -
Failed to export spans. Server is UNAVAILABLE. Make sure your collector is
running and reachable from this network. Full error message:UNAVAILABLE: io
exception

**Comment by iNikem** [comment]
`-Dotl.traces.exporter=none` - you missed a letter here: `-Dotel.traces.exporter=none`.

Your error clearly says that it failed to export **spans**. Prometheus accepts metrics, not spans. As you don't have any receiver for spans (such as Collector) agent understandably fails to export them. Setting traces exporter to `none`, as was recommended above, will solve your problem.
