### ISSUE TITLE
How to test auto-instrumented code

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4560]
Creating an issue from this discussion because this sounds like a great use-case for the project to support in the future.

### Discussed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/4550

<div type='discussions-op-text'>

<sup>Originally posted by **rkennedy-mode** October 29, 2021</sup>
We've created an OpenTelemetry extension for JUnit 5, which allows us to capture logged spans. We utilize this to add some additional checking to verify that we're generating the spans we expect with proper parenting. We also run the auto-instrumentation agent in production, which causes some issues for the tests, which we don't run with the agent.

I'm curious if there's any recommendations here regarding running test with/without the agent or some other way to ensure that tests have something approaching what we'll see in production. In particular, we have a fair bit of asynchronous code that jumps across CompletableFuture/ExecutorService type boundaries that we want to make sure are generating spans with the proper parents.</div>

**Comment by trask** [comment]
hi @rkennedy-mode! I think this is a great use-case for the project to support. We have some nice infra for running the javaagent during tests for this repository and checking the resulting spans. It seems that this could be extended/useful for this use case. We are currently working toward stabilizing the Instrumenter API for external usage, but have started thinking about tackling the same for the testing infra after that.

**Comment by aivinog1** [comment]
Hello @trask! I have a similar question in Stackoverflow, maybe I can help to implement this? I have thoughts about moving the custom memory exporter from the `agent-for-testing` module inside the main agent and just adding the in-memory exporting mode (like `oltp`, `jaeger`, etc.). And add some testing module that allows to register/deregister this agent in the test's JVM with this mode and APIs to verify exporter's logic.

**Comment by aivinog1** [comment]
Or I think if there are difficulties with sharing the data in memory between tests and the agent we could implement some sort of file exporter and export the data in the temp folder in the tests and read it from this directory afterward 🤔

**Comment by trask** [comment]
@aivinog1 check out https://github.com/open-telemetry/opentelemetry-java-docs/issues/42 for a nice alternative

**Comment by aivinog1** [comment]
> @aivinog1 check out [open-telemetry/opentelemetry-java-docs#42](https://github.com/open-telemetry/opentelemetry-java-docs/issues/42) for a nice alternative

Thanks, actually this is a good idea 👍

**Comment by trask** [comment]
Closing, I think https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/telemetry-testing is a good minimal testing example
