### ISSUE TITLE
Builder setter naming

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4564]
I noticed that our builders (and other places) don't use `set` prefix on setters. I like this, but it is different from the SDK convention (e.g. [SpanBuilder](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/trace/SpanBuilder.java)). Should we sync to the SDK convention, or forge our own way?

(while I prefer the convention we are using, I personally have slightly higher preference for not using a different convention in this repo from the SDK)

**Comment by anuraaga** [comment]
@trask Do you mind linking to a problematic builder? I tried jumping through about 6 of them but couldn't find any missing `set`.

**Comment by trask** [comment]
ah, maybe I just got unlucky, OkHttpTracingBuilder is the one I pulled up

**Comment by trask** [comment]
Closing, @mateuszrzeszutek explained in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4691#issuecomment-981566042

> My intention was to always use a verb in builder methods: `addThing()`, `setThing()`, `removeThing()`, `enableThing()`, ...
I think that the SDK repo (and instrumentation repo too) has adhered to the same convention, although maybe it wasn't explicitly stated anywhere.
With that in mind, `captureHttpHeaders()` is a valid builder method name - even though it doesn't contain `set`/`add` it still has a verb.
