### ISSUE TITLE
WithSpan annotation does not work with inheritance

### ISSUE THREAD

**Issue by hanikesn** [open-telemetry/opentelemetry-java-instrumentation#4565]
**Describe the bug**
Declaring `@WithSpan` on an interface does not propagate to subclasses.

**What did you expect to see?**
I think the general expectation is that @WithSpan works with inheritance as well.

**What version are you using?**
1.7.0

**Additional context**
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/12ec0fa481905528b5c6e8ed3faec072e6810872/instrumentation/opentelemetry-annotations-1.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/otelannotations/WithSpanInstrumentation.java#L50-L59

Uses `isAnnotatedWith`, but `inheritsAnnotation` seems to be appropiate here.

**Comment by trask** [comment]
hi @hanikesn! is this different from #4561?

**Comment by hanikesn** [comment]
@trask Sorry, I totally missed that I already opened a ticket on this
