### ISSUE TITLE
Mongo instrumentation can double-track work

### ISSUE THREAD

**Issue by jeffalder** [open-telemetry/opentelemetry-java-instrumentation#457]
My interpretation of the Mongo instrumentation is that when `build()` is called on a given instance of `com.mongodb.MongoClientSettings$Builder`, a new instance of `TracingCommandListener` is added via `builder.addCommandListener`, and then the remainder of the `build()` method is called.

A problem will likely arise if `build()` is called _multiple times_ on the _same instance_ of the `Builder`. For instance, imagine a DI scenario where a `Builder` is provided, then the consumer calls `build()`. In that case, the _second_ instance of the `MongoClientSettings` will have _two_ `TracingCommandListener` instances, tracking all work twice.

The same problem can happen if the user creates an instrumented `MongoClientSettings` instance, calls `builder(settings)`, and then calls `build()` on the second builder. This is because the command listeners, including the injected listener, are copied to the new builder.

The core of the issue is that `build()` doesn't normally mutate the instance on which it was called, but the instrumented `build()` now does mutate the instance.

**Comment by RashmiRam** [comment]
@trask  We could check if `TracingCommandListener` is already part of `commandListeners` property of the builder instance. We can add only if it is not in the `List<CommandListeners>` So that we can avoid doing the tracking multiple times.

If you think this is the right approach, I can send a PR for the same. Would that be alright?

**Comment by jeffalder** [comment]
@RashmiRam I'm not Trask, but I think that's good. The field on the builder is private. I don't know this agent, so I'm not clear if it's able to write code that accesses private fields ... seems like it should be able to.

**Comment by trask** [comment]
@RashmiRam yes, sounds great, assigning this issue to you 👍
