### ISSUE TITLE
Mongo listener belongs in instrumentation-core

### ISSUE THREAD

**Issue by jeffalder** [open-telemetry/opentelemetry-java-instrumentation#458]
`instrumentation-core` appears to have libraries that can be added by the user without the agent. The mongo [TracingCommandListener](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/mongo/mongo-common/src/main/java/io/opentelemetry/auto/instrumentation/mongo/TracingCommandListener.java) meets that criterion and probably belongs in `instrumentation-core`.

**Comment by trask** [comment]
In case anyone is interested in picking this up, please see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/CONTRIBUTING.md#writing-instrumentation

**Comment by mateuszrzeszutek** [comment]
Closed by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2789
