### ISSUE TITLE
trace not propagated between kafka producer and consumer since 1.6.0

### ISSUE THREAD

**Issue by vasyly71** [open-telemetry/opentelemetry-java-instrumentation#4582]
Here is what i have:

- Component_1 receives http request and  publishes it in kafka topic - "request topic" using regular kafka client.
- Component_2 uses kafka streams , reads message from "request topic", transforms it and puts it to "transformed topic"

Both components were instrumented with java instrumentation agent 1.5.3 and everything worked just fine - same trace id was propagated between components and i could see spans from component 1 and 2 in jaeger within same trace.

**What did you expect to see?**
After i upgraded to latest instrumentation (it was 1.7.0) i expected to see same as before - spans from different components within the same trace initiated by Component_1.
 
**What did you see instead?**
Component_2 created its own trace and jaeger did not show the whole  execution chain as before - every comoponent has its own trace.

**What version are you using?**
Everything was working as expected in V1.5.3
Broken in V1.7.0 and 1.6.0

**Environment**
Components running in AWS EKS, 
Docker images based on ubi8.4
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

**Comment by trask** [comment]
hi @vasyly71! can you check if you are having same issue as #4509 and if same workaround works for you?

**Comment by vasyly71** [comment]
@trask Thank you very much, 
it worked in 1.7.1 - closing
