### ISSUE TITLE
Add `inject` method to `Instrumenter`

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#4589]
I think we should add `inject` method to `Instrumenter`. My problem with current approach is that it is very easy to end up using different instances of `OpenTelemetry` .

_Originally posted by @iNikem in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4579#discussion_r742594393_

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
