### ISSUE TITLE
Feature Request: annotation for method timing metrics

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#4590]
**Is your feature request related to a problem? Please describe.**
Not all methods are appropriate for having spans generated for them (especially very high volume methods in an otherwise relatively low-volume request path). It would be very useful to be able to generate method-timing metrics for methods like this.

**Describe the solution you'd like**
Analogous to `@WithSpan`, something like `@Timed` at the method level. 

**Describe alternatives you've considered**
Manually creating metrics would of course work, but is much more boilerplate code, especially in the absence of a top-level Timer instrument.

**Open Questions**
Does each of these generate a new Instrument? Or use a common instrument, and add an attribute for the method name?

**Comment by trask** [comment]
Closing in favor of #7030
