### ISSUE TITLE
SqlSanitizer removes double-quoted "delimited" table and field names

### ISSUE THREAD

**Issue by dboreham** [open-telemetry/opentelemetry-java-instrumentation#4593]
## Background
SQL, as defined by [SQL92](http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt) and as implemented by the popular relational database servers, defines a syntax for identifier names (including the names of tables and fields) that is somewhat bizarre by modern standards. Identifiers specified in the regular way are subject to implementation-dependent case folding. For example:
`select * from foo` in Oracle is interpreted as `select * from FOO` while `select * from FOO` in PostgreSQL is interpreted as `select * from foo'.

SQL92 defines a double-quoted _delimited_ _identifier_ syntax the purpose of which is to override any case folding applied to identifiers. For example `select * from "Foo"` is interpreted as `select * from Foo`, preserving the mixed case name.

This is the only use of double quotes allowed in SQL92. String literals are delimited with single quotes like: `select * from foo where bar = 'baz'` and string literals delimited with double quotes constitute a syntax error.

Popular practice is to avoid the use of mixed case in database schema identifiers in order to avoid the need to use delimited identifiers. However, its use is not prohibited. It turns out that some ORMs do not support automatic case folding between camel-case application code identifiers and database table and field names. Therefore deployments using mixed-case database identifiers exist, and as a result all the queries executed against those databases feature double-quoted identifiers. Queries in these systems look like:
```
select "userId" from "adminUsers" where "lastName" = 'jones'
```

## The Problem
OpenTelemetry's database statement sanitizer function, the purpose of which is to remove potentially sensitive information from logged query data, removes delimited identifiers. The result is that the example query above is captured as:
```
select ? from ? where ? = ?
```
This is not the desired outcome because insufficient query information is captured to be practically useful. Operators of such a system would like instead to see:
```
select "userId" from "adminUsers" where "lastName" =  ?
```
The desired behavior can be achieved by sanitizing only single-quoted strings, rather than both single and double-quoted strings.

## The Exception to the Rule
It turns out that some relatively popular databases do not adhere to SQL92, and in particular: 1) do not support the delimited identifier syntax while 2) featuring modern conventions regarding identifier case (mixed case is allowed and preserved), and crucially 3) allow both single and double-quotes as string literal delimiters. The known list of such databases is : [CouchDB](http://couchdb.apache.org/) (see [this doc](https://docs.couchbase.com/server/current/analytics/3_query.html#Vs_SQL-92
) for details). CouchDB allows queries like:
```
select * from Foo where Bar = "baz"
```
OpenTelemetry currently sanitizes this to:
```
select * from Foo where Bar = ?
```
but if a "SQL92 compliant" sanitizer as discussed above were used, it would produce:
```
select * from Foo where Bar = "baz"
```
This means that different sanitization behavior is needed depending on whether a SQL92 database or a CouchDB-type database is used. It isn't possible to use the same sanitizer for both and also preserve visibility for SQL92 delimited identifiers.

### Delimited identifier (double quotes)
```
         <delimited identifier> ::=
              <double quote> <delimited identifier body> <double quote>
```
### String literal (single quotes)
```
         <character string literal> ::=
              [ <introducer><character set specification> ]
              <quote> [ <character representation>... ] <quote>
                [ { <separator>... <quote> [ <character representation>... ] <quote> }... ]

```

**Comment by trask** [comment]
cc @johnbley as original author of sql scrubbing just in case any advice
