### ISSUE TITLE
Hardcoded Tracer version in Instrumenter

### ISSUE THREAD

**Issue by radcortez** [open-telemetry/opentelemetry-java-instrumentation#4599]
**Is your feature request related to a problem? Please describe.**
In https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/d314d76fce9400976d1dfb8c326ab3d9394991d4/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/Instrumenter.java#L84-L85

The `Instrumenter` constructor has a hardcoded version to retrieve the `Tracer`. While this works fine for instrumentation libraries inside the project, it forces external libraries to use the same hardcoded version if you want to retrieve the same `Tracer` used by your `Instrumenter`.

**Describe the solution you'd like**
Have the `Tracer` version be part of the `InstrumenterBuilder` so it can be set by a consumer. If not set in the builder it defaults to the current behavior (use the OTel version).

**Describe alternatives you've considered**
None.

**Additional context**
I'm happy to provide a PR if this is an acceptable change.

**Comment by trask** [comment]
@radcortez sounds good, PR would be great 👍

**Comment by iNikem** [comment]
Wait, what is the use-case for external retrieval of the Tracer with exact same `InstrumentationLibrary` values? Why is this important? I would expect that any external 3rd party code will use their own Tracer, providing _their_ instrumentation library name and version.

**Comment by radcortez** [comment]
> I would expect that any external 3rd party code will use their own Tracer, providing _their_ instrumentation library name and version.

Correct, but currently, a 3rd party code is not able to set the version because it is not available to be set in the `InstrumenterBulder` and it will default to the current OTel SDK version. So your spans show something like:

```properties
otel.library.name="third.party.library" 
otel.library.version="1.7.0" #fixed with OTel SDK version
```

Unless I'm missing something, I believe there is no way to set your own version for the `Instrumenter`.

**Comment by iNikem** [comment]
A, now I see. Makes sense.
