### ISSUE TITLE
how can i export trace to a file

### ISSUE THREAD

**Issue by yingziisme** [open-telemetry/opentelemetry-java-instrumentation#4621]
use java.util.logging.Logger will remapping io.opentelemetry.javaagent.bootstrap.PatchLogger

i try to use this config below, but it doesn't work

private final Logger javaUtilLogger = Logger.getLogger("TRACING_JAVA_UTIL_LOGGER");
Handler tracingFileHandler = new FileHandler(this.traceLogPath + ".%u.log", this.traceLogSize, this.traceLogCount);
tracingFileHandler.setFormatter(new TracingFormatter());
this.javaUtilLogger.addHandler(tracingFileHandler);
this.javaUtilLogger.setLevel(Level.ALL);

**Comment by zmapleshine** [comment]
Hey @yingziisme , I think you would like to customize the log output of the agent. The issue related to this is still under discussion, please refer to #3413

At present we use SimpleLogger, its configuration is located in ``io.opentelemetry.javaagent.tooling.LoggingConfigurer``,  if you want to use SimpleLogger output trace information to a file, you can:

1. Configure the traces  exporter format to logging:
```property
otel.traces.exporter=logging
```
2.  Set up the system property "io.opentelemetry.javaagent.slf4j.simpleLogger.logFile" in ``LoggingConfigurer`` class.

If you simply want to define log output for trace infomation, try removing SimpleLogger log lib and using a more powerful log library such as logback.

**Comment by yingziisme** [comment]
> 



> Hey @yingziisme , I think you would like to customize the log output of the agent. The issue related to this is still under discussion, please refer to #3413
> 
> At present we use SimpleLogger, its configuration is located in `io.opentelemetry.javaagent.tooling.LoggingConfigurer`, if you want to use SimpleLogger output trace information to a file, you can:
> 
> 1. Configure the traces  exporter format to logging:
> 
> ```
> otel.traces.exporter=logging
> ```
> 
> 2. Set up the system property "io.opentelemetry.javaagent.slf4j.simpleLogger.logFile" in `LoggingConfigurer` class.
> 
> If you simply want to define log output for trace infomation, try removing SimpleLogger log lib and using a more powerful log library such as logback.



> Hey @yingziisme , I think you would like to customize the log output of the agent. The issue related to this is still under discussion, please refer to #3413
> 
> At present we use SimpleLogger, its configuration is located in `io.opentelemetry.javaagent.tooling.LoggingConfigurer`, if you want to use SimpleLogger output trace information to a file, you can:
> 
> 1. Configure the traces  exporter format to logging:
> 
> ```
> otel.traces.exporter=logging
> ```
> 
> 2. Set up the system property "io.opentelemetry.javaagent.slf4j.simpleLogger.logFile" in `LoggingConfigurer` class.
> 
> If you simply want to define log output for trace infomation, try removing SimpleLogger log lib and using a more powerful log library such as logback.

> Hey @yingziisme , I think you would like to customize the log output of the agent. The issue related to this is still under discussion, please refer to #3413
> 
> At present we use SimpleLogger, its configuration is located in `io.opentelemetry.javaagent.tooling.LoggingConfigurer`, if you want to use SimpleLogger output trace information to a file, you can:
> 
> 1. Configure the traces  exporter format to logging:
> 
> ```
> otel.traces.exporter=logging
> ```
> 
> 2. Set up the system property "io.opentelemetry.javaagent.slf4j.simpleLogger.logFile" in `LoggingConfigurer` class.
> 
> If you simply want to define log output for trace infomation, try removing SimpleLogger log lib and using a more powerful log library such as logback.

how can i remove SimpleLogger log lib  ？ need build source code？
only use otel.traces.exporter=logging can export trace to file? 
i just want to use costom exporter

**Comment by laurit** [comment]
Feel free to reopen if you have more questions.
