### ISSUE TITLE
Kotlin coroutines + Java Http Client + otel agent generating memory leak

### ISSUE THREAD

**Issue by brunojcm** [open-telemetry/opentelemetry-java-instrumentation#4629]
**Describe the bug**
I'm currently using the Java Http Client thorugh the ktor client (I think ktor is irrelevant here, any coroutines code would cause the same problem), and when the otel java agent is installed, I have a memory leak.

**Steps to reproduce**
1. Create a Ktor client like this:
```
val client = HttpClient(Java.create())
val r = client.get("$baseUrl/any/endpoint")
```
2. Run multiple http calls using the client

**What did you expect to see?**
Many http request calls with no memory leak.

**What did you see instead?**
Many `JobImpl` instances leak:
<img width="1526" alt="image" src="https://user-images.githubusercontent.com/251695/141166468-a5bb9906-7be2-4b74-9f7a-4b843b4e4fc2.png">

GC Root goes all the way back to the first job created:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/251695/141166535-5691b7a9-fac0-4296-b2f7-770c334e1a3b.png">
<img width="892" alt="image" src="https://user-images.githubusercontent.com/251695/141166561-06352977-8b07-40ec-89ba-b4154e42ad5c.png">

**What version are you using?**
`opentelemetry-javaagent-all-1.7.2`

**Environment**
Compiler: Temurin 11.0.13
OS: macOS

**Additional context**

Weirdly enough, even though the object leaking seems to be related to coroutines (`JobImp`), if I add `-Dotel.instrumentation.java-http-client.enabled=false` to my startup command, the leak stops.

I also tried various combinations of `-Dotel.instrumentation.executor.enabled=false` and `-Dotel.instrumentation.kotlinx-coroutines.enabled=false`, no luck, the trigger for the issue seems to be `java-http-client` instrumentation.

**Comment by brunojcm** [comment]
I just tested the Ktor client with with the `ktor-client-apache` and the `ktor-client-cio` engines, none of those causes the memory leak. `ktor-client-apache` even uses Apache Http, which is also intrumented, but for some reason that does not trigger the bug.

**Comment by brunojcm** [comment]
I just realized Apache and CIO clients are not generating spans (CIO is expected, but I thought Apache should be instrumented), so maybe that's why we don't see the memory leak when those are used.

**Comment by laurit** [comment]
A small sample app that reproduces the issue would help a lot.

**Comment by brunojcm** [comment]
I'll try to work on that this week.

**Comment by brunojcm** [comment]
repro is at https://github.com/brunojcm/kotlin-jvm-sandbox/tree/otel-javahttpclient-memory-leak, let me know if you need anything else!

**Comment by brunojcm** [comment]
Any ideas on where to start looking?

**Comment by brunojcm** [comment]
Nice work, thanks for looking at that so quick :) Looking forward for a new release containing this PR, let me know if I can help in any way.
