### ISSUE TITLE
Spring/Hibernate - Spans out of order

### ISSUE THREAD

**Issue by JBodkin-LH** [open-telemetry/opentelemetry-java-instrumentation#4633]
**Describe the bug**
By default, Spring enables `spring.jpa.open-in-view` which creates a Hibernate session for every request. When this property is enabled, we're seeing SELECT statements being attached to the Hibernate session span instead of the Spring WebMVC span.

**What did you expect to see?**
The spans in the following order:
1) Session
2) OurSpringRestController.ourMethod
...
8) OurSpringDataRepository.findAllByLocale
9) SELECT some model
10) SELECT some table
11) OurSpringDataRepository.findAll
12) SELECT some model
13) SELECT some table

**What did you see instead?**
The spans in the following order:
1) Session
2) SELECT some model
3) SELECT some table
4) SELECT some model
5) SELECT some table
6) OurSpringRestController.ourMethod
...
12) OurSpringDataRepository.findAllByLocale
13) OurSpringDataRepository.findAll

**What version are you using?**
v1.7.2

**Environment**
Compiler: AdoptOpenJDK 11.0.10-hotspot
OS: Docker - marketplace.gcr.io/google/centos7:latest
Runtime (if different from JDK above): AdoptOpenJDK 11.0.10-hotspot
OS (if different from OS compiled on): Docker - marketplace.gcr.io/google/centos7:latest

**Additional context**
![image](https://user-images.githubusercontent.com/26540533/141357745-a1aa0c81-f326-4dec-abdf-5408e62e08c4.png)

**Comment by trask** [comment]
hi @JBodkin-LH! I think #4538 probably addresses this, can you try out the latest snapshot build? https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/CONTRIBUTING.md#snapshot-builds

**Comment by JBodkin-LH** [comment]
Yes, it does address the issue. Is there a way of tracking when the next release is that includes this commit?

**Comment by mateuszrzeszutek** [comment]
> Yes, it does address the issue. Is there a way of tracking when the next release is that includes this commit?

The 1.9.0 release will include that fix; it will most likely happen at the end of next week.
