### ISSUE TITLE
Kafka Springboot Auto Instrumentation

### ISSUE THREAD

**Issue by urwah1996** [open-telemetry/opentelemetry-java-instrumentation#4636]
Hi!
We are using opentelemetry spring boot autoconfigure sdk to bring tracing to our microservices. We have included the sdk as a dependency. As of now it is instrumenting http calls and rest template client calls to downstream services.
We are using Kafka messaging heavily in our microservices. I came across [open telemetry instrumentation for kafka clients](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/kafka-clients/kafka-clients-2.6/library). This instrumentation will require manually wrapping the kafka consumers and producers with TracingConsumer and TracingProducer respectively. 

I wanted to know if it is in the pipeline to autoconfigure TracingProducer and TracingConsumer during spring boot application startup. Just like spring cloud sleuth has post processors for [producer](https://github.com/spring-cloud/spring-cloud-sleuth/blob/main/spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/instrument/messaging/TraceProducerPostProcessor.java) and [consumer](https://github.com/spring-cloud/spring-cloud-sleuth/blob/main/spring-cloud-sleuth-brave/src/main/java/org/springframework/cloud/sleuth/brave/instrument/messaging/TraceConsumerPostProcessor.java)

Any kind of help or direction would be really appreciated! 
Thanks :)

**Comment by mateuszrzeszutek** [comment]
Spring-kafka has the [`RecordInterceptor`](https://docs.spring.io/spring-kafka/api/org/springframework/kafka/listener/RecordInterceptor.html) and [`BatchInterceptor`](https://docs.spring.io/spring-kafka/api/org/springframework/kafka/listener/BatchInterceptor.html) interfaces that I believe would provide better instrumentation than the plain kafka-clients one (and we already have a spring-kafka javaagent instrumentation that uses `BatchInterceptor`; perhaps it could be refactored to a library+javaagent instrumentation).
I don't think we have this in the pipeline, but any help with that would be very much appreciated.
