### ISSUE TITLE
Don't create spans for HttpUrlConnection requests from agent classloader

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#4642]
I have a feeling there isn't a good solution to this but would be nice if there were. Because HttpUrlConnection is in bootstrap classloader, requests made from the agent classloader, such as a remote sampler, end up getting traced. Ideally this didn't happen and otherwise requires workarounds like adding the sampler's requests into that remote sampler configuration itself.

**Comment by laurit** [comment]
While I believe it is possible to figure out whether call was made from agent class loader with `StackWalker` or `SecurityManager.getClassContext` I'm not convinced that it is a reasonable thing to do. How would we use it, find a class at some fixed offset like `sun.reflect.Reflection.getCallerClass(int)` used to do, or scan the whole call stack?
Perhaps it would make more sense to find an alternative way. For example if such usages of HttpUrlConnection happen only from one of the agent threads then perhaps we could make all agent threads be in one group and when current thread is in that group automatically suppress spans. Or we could add something around the usage of HttpUrlConnection in our code that suppresses the spans. If I remember correctly then besides HttpUrlConnection executor instrumentation has also had issues where context is propagated into agent thread somehow.

**Comment by iNikem** [comment]
I like the idea of agent's thread group

**Comment by anuraaga** [comment]
While I think this is an interesting topic, I was able to workaround it for the x-ray sampler case specifically

https://github.com/open-telemetry/opentelemetry-java-contrib/pull/135
