### ISSUE TITLE
Add Http4SpanDecorator to apache-camel-2.20 instrumetation

### ISSUE THREAD

**Issue by osherv** [open-telemetry/opentelemetry-java-instrumentation#4644]
Today, the handling for http4 requests is the default HttpSpanDecorator.
In this behavior, the captured http.url could be "http4:/url" which is incorrect.

I'd like to add a new Http4SpanDecorator that inherits from HttpSpanDecorator and overrides HttpSpanDecorator::getHttpUrl
and will return the real URL.

I already have the module decorator that could fix that, pls assign this issue to me and i'll open pr :)
Thanks.

**Comment by mateuszrzeszutek** [comment]
Please go ahead, I've assigned you.
Thanks!

**Comment by laurit** [comment]
Resolved with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4650
