### ISSUE TITLE
Serialisation exception for ScheduledEvent

### ISSUE THREAD

**Issue by acm19** [open-telemetry/opentelemetry-java-instrumentation#4645]
**Describe the bug**
When instrumenting a Lambda triggered by `ScheduledEvent` a parsing exception is produced:

```
at io.opentelemetry.instrumentation.awslambda.v1_0.TracingRequestHandler.handleRequest(TracingRequestHandler.java:89)
Caused by: java.lang.IllegalArgumentException: Unrecognized field "version" (class com.amazonaws.services.lambda.runtime.events.ScheduledEvent), not marked as ignorable (8 known properties: "detail", "region", "resources", "detailType", "account", "source", "time", "id"])
```

**Steps to reproduce**
Create a lambda triggered by a `ScheduledEvent` and instrument it using OpenTelemetry following this tutorial: https://aws-otel.github.io/docs/getting-started/lambda/lambda-java.

**What did you expect to see?**
I expect no exception.

**What did you see instead?**
The lambda failed with an exception.

**What version are you using?**
v1.7.0

**Environment**
Java 11 Corretto running in AWS Lambda.

**Additional context**
I think a good way to fix the problem would be to ignore unknown properties by this object mapper: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/6063a16f54453c9c0cff8b754e492b142d091c45/instrumentation/aws-lambda-1.0/library/src/main/java/io/opentelemetry/instrumentation/awslambda/v1_0/TracingRequestWrapperBase.java#L22. I'm happy to create a PR if that would speed up having it fixed.

**Comment by laurit** [comment]
@acm19 a pr would be appreciated.

**Comment by acm19** [comment]
@laurit https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4724
