### ISSUE TITLE
How Embed extensions used in jdk8 ?

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-java-instrumentation#4659]
Embed extensions in the OpenTelemetry Agent (opentelemetry-java-instrumentation\examples\extension\build\libs\opentelemetry-javaagent.jar ) can only used in jdk 11+ version. How can I build it,then I can use in jdk8 project. 
![image](https://user-images.githubusercontent.com/11512994/142159865-0a660ebc-6101-4ca9-83ea-3ed0ba2b857e.png)

When I change gradle `options.release.set(8)`  or jdk version to build agent,it fail:
![image](https://user-images.githubusercontent.com/11512994/142160070-a2b3b370-e7be-4952-b86d-5ce4b974326d.png)
 Please help me ,thank you.

**Comment by trask** [comment]
hi @chenjazz, thanks for reporting this!

I think it would be better for the examples to target Java 8 for maximum compatibility (and as a good test to ensure extensions are supported on Java 8). I have sent a PR to update them #4665.

**Comment by laurit** [comment]
@chenjazz currently when you set `options.release.set(8)` you'll still need to build with jdk 11

**Comment by chenjazz** [comment]
@trask @laurit Thank you 👍

**Comment by trask** [comment]
@chenjazz is your issue resolved now?
