### ISSUE TITLE
Remote debugging the Java agent

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4672]
Due to shading, breakpoints don't work in the `instrumentation-api` and the various library instrumentations that are reused/injected by the javaagent.

Wondering if anyone has tips/ideas for this?

**Comment by trask** [comment]
commenting out this line worked:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f788d84e35442afdd10c7b600b36861fdf9d3663/conventions/src/main/kotlin/io.opentelemetry.instrumentation.javaagent-shadowing.gradle.kts#L18-L19

we could consider publishing a `-debug`(?) artifact that's unshaded. not sure how common an issue this is, but I've run into it a couple of times lately when debugging repros

**Comment by anuraaga** [comment]
#482? :)

**Comment by trask** [comment]
> #482? :)

I _thought_ we had something related, but couldn't find it 👍

I don't have any problems with the `.classdata`, do you still have that issue?

**Comment by anuraaga** [comment]
I think I just assumed the classdata in addition to shadowing caused problems but I may have assumed wrong - I never actually tried anything that works.
