### ISSUE TITLE
http metrics exemplar not available

### ISSUE THREAD

**Issue by yangtaoran** [open-telemetry/opentelemetry-java-instrumentation#4698]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v1.7.2/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpClientMetrics.java#L77, here I find http client duration invoke record() did't passed the context parameter. howerver, in that time the returned result of Context.current() is invalid, the exemplar cannot recoord traceId and spanId. so whice version can resolve this bug?

**Comment by laurit** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4616

**Comment by yangtaoran** [comment]
thank you.
