### ISSUE TITLE
Tighten up the restrictions on what New Relic classes shouldn't be instrumented.

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#472]
Currently, everything in `com.newrelic` gets excluded from instrumentation, which unfortunately means we (New Relic) can't use the OTel agent to instrument most of our own code.

If we tighten up the restriction to be just these packages:
`com.newrelic.agent` 
`com.newrelic.weave` 
`com.newrelic.bootstrap`
`com.newrelic.trace`
`com.newrelic.api`

that would probably be more correct, in that we would still not instrument the NR agent code, but we could still instrument our own non-agent code.

**Comment by jeffalder** [comment]
This is not 100% true, sadly. The Infinite Tracing code in 5.12.1 has a number of classes in the base `com.newrelic` package.

**Comment by jkwatson** [comment]
> This is not 100% true, sadly. The Infinite Tracing code in 5.12.1 has a number of classes in the base `com.newrelic` package.

Hmm. Do you have an alternative suggestion? Maybe we should move those classes into a sub-package that could be excluded?

**Comment by trask** [comment]
Maybe we don't need the newrelic package exclusion at all? I'm guessing that exclusion was done originally so that the two agents could potentially run side-by-side, but not sure that's a use case we need to support.

**Comment by jkwatson** [comment]
I'd be all in favor of removing it for now; I don't think any of us really want to support a dual-agent mode if we can possible avoid it.

**Comment by jkwatson** [comment]
resolved by #525
