### ISSUE TITLE
Update testcontainer version in remaining modules

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4737]
From https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4727#pullrequestreview-817610728

> There is also a testcontainers dependency in benchmark-e2e/build.gradle.kts, benchmark-overhead/build.gradle.kts, examples/distro/smoke-tests/build.gradle and examples/extension/build.gradle

**Comment by iNikem** [comment]
Already fixed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4727/commits/7df326c57293dfceabbc68f1421cf36ecd7daff3

**Comment by trask** [comment]
oops, I blame monday morning 😭
