### ISSUE TITLE
When implement RPC metrics

### ISSUE THREAD

**Issue by yangtaoran** [open-telemetry/opentelemetry-java-instrumentation#4747]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/rpc.md, here, I find the specification had definded the RPC metrics, but the java-instrumentation not implement it.
So, I hope we can discuss the feature that how to complete it.

**Comment by trask** [comment]
hi @yangtaoran! if you are interested in implementing this, a good starting place is to check out how [HttpServerMetrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpServerMetrics.java) and [HttpClientMetrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpClientMetrics.java) are implemented.

**Comment by yangtaoran** [comment]
done #4838
