### ISSUE TITLE
Publish a debug jar without the classdata obfuscation

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#482]
I noticed that I can't debug classes in the agent in IntelliJ because it doesn't recognize the files named `.classdata`. Let me know if there's a way that I'm missing :) But if not, it would be helpful to have a `-debug` jar or something that has normal `.class` files I believe that would allow the debugger to work.

**Comment by devinsba** [comment]
Adding `disableShadowRelocate=true` to your `~/.gradle/gradle.properties` should disable the renaming

**Comment by anuraaga** [comment]
Hmm, I'm not sure but that seems like it would disable shading, but not the file renaming? I don't see the flag used here

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/java-agent/java-agent.gradle#L15

But assuming a flag does exist or is created, that requires building locally which takes a long time for this monolith so publishing such a build to download would be great :)

**Comment by FrankSpitulski** [comment]
Just tried disableShadowRelocate=true, it does not appear to restore the .classdata files to .class.

**Comment by pavolloffay** [comment]
@anuraaga I am able to use breakpoint in the instrumentation classes e.g. `Servlet3HttpServerTracer`  by running `java -javaagent:opentelemetry-javaagent-<version>-all.jar -jar -agentlib:jdwp="transport=dt_socket,server=y,suspend=y,address=5000" app.jar`

**Comment by jbaris** [comment]
Hi @pavolloffay 
Where the -all.jar comes from?

Thanks in advance

**Comment by mateuszrzeszutek** [comment]
We used to publish an `opentelemetry-javaaget-all.jar` on release - we've renamed it to `opentelemetry-javaagent.jar` later on because it was confusing.
