### ISSUE TITLE
OTEL_JAVAAGENT_DEBUG enables okhttp debug

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#4821]
I'm surprised by this since I thought we only enable debug logging for io.opentelemetry, but I noticed that when enabling debug logging there is a lot of spam from okhttp like this

```
app_1        | [otel.javaagent 2021-12-07 04:39:19:400 +0000] [OkHttp http://otel:4317/...] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10002 scheduled after   0 µs: OkHttp ConnectionPool
app_1        | [otel.javaagent 2021-12-07 04:39:19:400 +0000] [OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10002 starting              : OkHttp ConnectionPool
app_1        | [otel.javaagent 2021-12-07 04:39:19:400 +0000] [OkHttp ConnectionPool] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10002 run again after 300 s : OkHttp ConnectionPool
```

**Comment by laurit** [comment]
I though that it was done deliberately, enabling debug also enables debug for all bundled libraries. For loggers that are too chatty set log level to info https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/LoggingConfigurer.java

**Comment by trask** [comment]
> For loggers that are too chatty set log level to info https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/LoggingConfigurer.java

Here's the updated location now:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/2ebf4134f915a9caffee713eceaaa696a4093077/javaagent-internal-logging-simple/src/main/java/io/opentelemetry/javaagent/logging/simple/Slf4jSimpleLoggingCustomizer.java#L39-L42

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.

**Comment by laurit** [comment]
`okhttp3.internal.concurrent.TaskRunner` was excluded from debug logs in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9814
