### ISSUE TITLE
Java Agent flag for fast-failure

### ISSUE THREAD

**Issue by Asafb26** [open-telemetry/opentelemetry-java-instrumentation#4829]
### Discussed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/4610
Adding this feature will ensure a proper initiated OT system on the host machine, in case it is running.
I see many scenarios based on OT which assumes it running on the machine. adding an option to crash the app on OT error would be great.

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
