### ISSUE TITLE
Update integration tests from Java 15 to Java 17

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4830]
Now that #4266 is done, this might(?) be possible...

**Comment by anuraaga** [comment]
Tried this and found that Groovy 4 will finally be the version to support Java 17, if not Groovy 5 to keep up the pattern of broken promises... 

https://issues.apache.org/jira/browse/GROOVY-10137
https://issues.apache.org/jira/browse/GROOVY-10138

**Comment by trask** [comment]
Resolved by #5598
