### ISSUE TITLE
Add checksum to verify the integrity of the downloaded javaagent

### ISSUE THREAD

**Issue by Cavvar** [open-telemetry/opentelemetry-java-instrumentation#4844]
**Is your feature request related to a problem? Please describe.**
https://github.com/github/feedback/discussions/8535
Because of the discussion mentioned here, the download of the opentelemetry-javaagent was erronous. This resulted in the following error during the startup of an application:
```
Error opening zip file or JAR manifest missing : /.../opentelemetry-javaagent-all.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```
**Describe the solution you'd like**
Add a checksum in the release assets that can be used to identify the integrity of the download

**Describe alternatives you've considered**
Open for alternatives

**Comment by trask** [comment]
hey @Cavvar, the javaagent is also published to maven central, which automatically generates checksums, check out https://repo1.maven.org/maven2/io/opentelemetry/javaagent/opentelemetry-javaagent/1.9.1/

**Comment by Cavvar** [comment]
Hey @trask. Thank for the info! This definitly helped! I'll close the issue.
