### ISSUE TITLE
Memory & connection leak in reactor-netty instrumentation

### ISSUE THREAD

**Issue by raptium** [open-telemetry/opentelemetry-java-instrumentation#4862]
**Describe the bug**
When using `WebClient` in Spring WebFlux, a `SimpleDequePool` is created on every HTTP request and never gets disposed.

**Steps to reproduce**
1. Included `spring-boot-starter-webflux` as a dependency
2. Create a `org.springframework.web.reactive.function.client.WebClient`
3. Use this client to send some HTTP requests

**What did you expect to see?**
1. Sending requests with one WebClient should create only one connection pool and reuse connection if possible.

**What did you see instead?**
1. Lots of `SimpleDequePool` live in heap and lots of TCP connections are established. None of these will get disposed after GC.
2. Server gets OOM or reaches limit of num of FD eventually.

**What version are you using?**
`1.9.1`

**Environment**
Compiler: openjdk 1.8.0_312
OS: macOS 12.0.1

**Additional context**
- `PooledConnectionProvider` use `PooledConnectionProvider.PoolKey` as key for its internal channelPools (ConcurrentHashMap).
- Hashcode of `PooledConnectionProvider.PoolKey` is computed with `pipelineKey` and other fields.
- `pipelineKey` is assigned with `TransportConfig.channelHash()`
- `channelHash()` is computed with `observer` and other fields.
- `observer` is a different instance of `HttpResponseReceiverInstrumenter.EndOperation` on each HTTP request and it may cause `PooledConnectionProvider` to create a new pool every time

**Comment by sh777** [comment]
Hi, this is quite a critical issue in current release. I wonder when will we be able to release the fix?

**Comment by trask** [comment]
1.10.0 is targeted for end of next week. This issue does meet our [patch release policy](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/RELEASING.md#patch-release) if you need it sooner.

**Comment by sh777** [comment]
Hi @trask, thanks a lot! We indeed need it urgently. We really appreciate if we could have a patch for it.

**Comment by trask** [comment]
@sh777 1.9.2 is released with this fix
