### ISSUE TITLE
Muzzle check plugin fails on extension example project

### ISSUE THREAD

**Issue by rkolesnev** [open-telemetry/opentelemetry-java-instrumentation#4871]
**Describe the bug**
printMuzzleReferences goal fails on the provided extension example - with error 
`Execution failed for task ':printMuzzleReferences'. `
`> java.lang.ClassNotFoundException: io.opentelemetry.javaagent.tooling.muzzle.ReferencesPrinter`

**Steps to reproduce**
`cd examples/extension`
` ./gradlew printMuzzleReferences`

**What did you expect to see?**
Expect muzzle-check plugin to print muzzle references

**What did you see instead?**

`Execution failed for task ':printMuzzleReferences'.`
`> java.lang.ClassNotFoundException: io.opentelemetry.javaagent.tooling.muzzle.ReferencesPrinter`

**What version are you using?**
Tried on multiple branches - v1.7.1 v1.7.2 v1.7.x v1.9.0 v1.9.1 v1.9.x 
- note for 1.7 branches had to change dependency to non-snapshot version of otel.

**Environment**
Compiler:  AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) 
OS: macOS 11.5.2 

**Additional context**
I am trying to build an extension for open telemetry instrumentation - but documentation is a little scarse and included example is not very stable lately.

**Comment by trask** [comment]
@rkolesnev thanks for reporting this! I have sent a PR #4875 to fix. Try adding these lines locally for now to get it to build: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4875/files#diff-87cd317db29d163b21c3c5ea9e599af70db4553e555a00e3f472e25520c78678

**Comment by rkolesnev** [comment]
@trask cool - that has fixed it on 1.7.2 as well as main. 
Thank you for quick response and fix.
