### ISSUE TITLE
Add runtime metrics for buffer pools

### ISSUE THREAD

**Issue by mikelaspina** [open-telemetry/opentelemetry-java-instrumentation#4876]
I'd like to have runtime metrics for buffer pool utilization similar to the existing [metrics for memory pools](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/MemoryPools.java). Data can be gathered from [BufferPoolMXBean](https://docs.oracle.com/en/java/javase/11/docs/api/java.management/java/lang/management/BufferPoolMXBean.html) Something like the following. 

```
runtime.jvm.buffer.pool {type="used",pool="direct"}
runtime.jvm.buffer.pool {type="max",pool="direct"}
runtime.jvm.buffer.pool {type="used",pool="mapped"}
runtime.jvm.buffer.pool {type="max",pool="mapped"}
runtime.jvm.buffer.count {pool="direct"}
runtime.jvm.buffer.count {pool="mapped"}
```

**Comment by cuichenli** [comment]
Hey @mikelaspina , I would like to work on this and had a look on how to make it. But I am a little bit confused on what to be watched. 

From the BufferPoolMXBean document, we can only get the pool name, count, and memory. While in your example, you still have the `type` attributes. 

So I'm wondering how can we get this `type` value or it was a mistake? Thanks!

**Comment by mikelaspina** [comment]
I mapped `BufferPoolMXBean.getMemoryUsed()` to `type=used` and `BufferPoolMxBean.getTotalCapacity()` to `type=max`. But, in the spirit of #5718, my request should be revised to use separate metrics. Something like `process.runtime.jvm.buffer.usage` and `process.runtime.jvm.buffer.max`?
