### ISSUE TITLE
memory leak exists?

### ISSUE THREAD

**Issue by 844067874** [open-telemetry/opentelemetry-java-instrumentation#4882]
**Describe the bug**
memory leak exists?
![image](https://user-images.githubusercontent.com/11434590/145743740-b90cf6af-1d80-4d1d-86e7-25f5c88503c2.png)

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by trask** [comment]
hi @844067874, this looks similar to #3514. what version of the Javaagent are you using?

**Comment by trask** [comment]
Closing, I suspect this is the same as #3514. @844067874 let us know if you are still seeing this issue on the latest javaagent version. thx!
