### ISSUE TITLE
Unable to print trace id and span id for undertow non-blocking IO server 

### ISSUE THREAD

**Issue by lokeshcse6** [open-telemetry/opentelemetry-java-instrumentation#4897]
**Describe the bug**
When using dispatch API the traceid and span is are not generated in log file, without dispatch its able to generate

**Steps to reproduce**

public HttpHandler healthCheck() {
			return exchange -> {
			exchange.dispatch(() -> {
				logger.info("inside demo health...");
				exchange.setStatusCode(StatusCodes.OK);
				exchange.getResponseHeaders().put(Headers.CONTENT_TYPE, "application/json");
				exchange.getResponseSender().send(HEALTH_RESPONSE);
				logger.info("inside exchange");
			});
		};
	}
	

**What did you expect to see?**
In the below log trace_id and span_id should be printed
{"DateTime":"20211214T11:08:36.443Z","PID":"PID_IS_UNDEFINED","Class":"c.g.d.DemoController","Level":" INFO","Thread":"XNIO-1 task-1","Message":"inside demo helath...","TimeTaken":"","trace_id":"ab7687fskf465444545eab","span_id":"afe768ghc89","trace_flags":"01"}

**What did you see instead?**
A clear and concise description of what you saw instead.

{"DateTime":"20211214T11:08:36.443Z","PID":"PID_IS_UNDEFINED","Class":"c.g.d.DemoController","Level":" INFO","Thread":"XNIO-1 task-1","Message":"inside demo helath...","TimeTaken":"","trace_id":"","span_id":"","trace_flags":""}

**What version are you using?**
opentelemetry-javaagent:1.7.2

**Environment**
Compiler: oracle Jdk1.8
OS: windows/linux

**Additional context**
None

**Comment by mateuszrzeszutek** [comment]
Hey @lokeshcse6 ,
What logger API (and which version) are you using?

**Comment by lokeshcse6** [comment]
> 



> Hey @lokeshcse6 , What logger API (and which version) are you using?

logback with slf4j (1.7.30)
