### ISSUE TITLE
Use Gradle build cache

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#490]
It takes a lot of time to build instrumentation project. But the majority of that time is spent building and testing tons of individual instrumentations. As developers often make changes to a specific instrumentation, there is no sense in building all other, unrelated, instrumentations. [Gradle build cache](https://docs.gradle.org/current/userguide/build_cache.html) can help a lot here. One easy way to start using it is via [this plugin](https://github.com/myniva/gradle-s3-build-cache)

**Comment by anuraaga** [comment]
@iNikem It will be quite nice if we can speed up the build using S3

AWS has a system for providing promotional credits to open source projects
https://aws.amazon.com/blogs/opensource/aws-promotional-credits-open-source-projects/

We're currently wondering whether CNCF's credits can be used to fund an S3 build cache. @alolita has been involved in these efforts to support OSS projects and will help check on whether that's possible. We're interested in making this happen one way or another :)

**Comment by anuraaga** [comment]
Filed #546 since I do notice the build rerunning itself for limited changes - I guess it blocks this issue since without solving that, Gradle build cache won't help since it'll be the same sort of cache miss. At some point will try running some build scans, we may want to enable them for the CI build too.

**Comment by iNikem** [comment]
CI does use build scans already. You can see links to them from the CI console e.g. for all testXXX jobs.

**Comment by anuraaga** [comment]
Oops I should have looked at the actual logs, saw the big SKIP_BUILDSCAN in the config 😅
