### ISSUE TITLE
Vulnerability in transitive dependency fasterxml-jackson-databind

### ISSUE THREAD

**Issue by tnaroska** [open-telemetry/opentelemetry-java-instrumentation#4924]
**Describe the bug**
opentelemetry-javaagent.jar v1.9.1 got flagged by our vulnerability scanner for inclusion of gav://com.fasterxml.jackson.core:jackson-databind:2.12.3

> Summary: FasterXML jackson-databind node/NodeSerialization.java NodeSerialization::readExternal() Function JDK Serialization Memory Exhaustion DoS
> Sevirity: High
> Issue ID: XRAY-191477
> Fixed Versions: 2.12.6, 2.13.1, 2.14.0

Please upgrade the dependency to at least 2.12.6.

**What did you expect to see?**
No vulnerabilities being reported for opentelemetry agent jar.

**What version are you using?**
1.9.1

**Comment by tnaroska** [comment]
fasterxml issue for reference:
https://github.com/FasterXML/jackson-databind/issues/3328

**Comment by trask** [comment]
thanks @tnaroska, I checked and this is already fixed in `main` (by https://github.com/open-telemetry/opentelemetry-java/pull/3950 and #4866)

**Comment by tnaroska** [comment]
Hi @trask thanks for checking. I didn't look that deeply but at the very least the 2.12.3 version is still mentioned here:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/dependencyManagement/build.gradle.kts#L34

**Comment by trask** [comment]
ya, we still pull in `jackson-core`, just not `jackson-bind` anymore. but will update that dependency version anyways #4934

**Comment by trask** [comment]
I believe this is resolved now. @tnaroska let us know if you still see any issue. thx!

**Comment by trask** [comment]
@tnaroska thx! I've opened #5203 to track the license file issues
