### ISSUE TITLE
disable("SystemOut") in errorprone

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#4926]
Since #4825, I'm constantly battling with this during development / troubleshooting.

I agree with not breaking gradle cache, so that leaves the option of disabling this rule unconditionally (both local and CI).

Or any other ideas?

**Comment by iNikem** [comment]
You can add `disableErrorProne` to your `~/.gradle/gradle.properties` :)

**Comment by mateuszrzeszutek** [comment]
But that disables everything -- the other checks are fine, it's the sysout one that's super annoying during development.

**Comment by anuraaga** [comment]
The bigger issue we discussed is that it would still be nice to take advantage of the remote build cache, which that would go back to invalidating I guess.

One workaround we thought of is removing the error prone check and adding it to checkstyle. Disabling that locally wouldn't affect build caching
