### ISSUE TITLE
InstrumentationModule#classLoaderMatcher use "not(hasClassesNamed(...))"

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-java-instrumentation#4949]
**Describe the bug**
First use:
```
  @Override
  public ElementMatcher.Junction<ClassLoader> classLoaderMatcher() {
    System.out.println("restlight-1.0 classLoaderMatcher");
    return hasClassesNamed(
        "esa.restlight.starter.ConfigurableRestlight",
        "esa.restlight.core.Restlight"
    ).and(not(hasClassesNamed("esa.restlight.spring.SpringHandlerMethodMappingInitializer")
    )).and(not(hasClassesNamed("esa.restlight.server.schedule.RequestTaskHook"))) ;
  }
```
Second:
 ```
  @Override
  public ElementMatcher.Junction<ClassLoader> classLoaderMatcher() {
    return hasClassesNamed(
        "esa.restlight.starter.ConfigurableRestlight",
        "esa.restlight.core.Restlight"
    ).and(not(hasClassesNamed("esa.restlight.spring.SpringHandlerMethodMappingInitializer",
        "esa.restlight.server.schedule.RequestTaskHook")
    ));
  }
```
Above code produce different results. Is it a bug?

**What version are you using?**
1.9.1

**Comment by mateuszrzeszutek** [comment]
Hey @chenjazz ,

`hasClassesNamed("esa.restlight.spring.SpringHandlerMethodMappingInitializer", "esa.restlight.server.schedule.RequestTaskHook")` means that both classes have to be available on a particular classloader; the negation of that is "none of them or one of them, but not both at once".
`not(hasClassesNamed("esa.restlight.spring.SpringHandlerMethodMappingInitializer")).and(not(hasClassesNamed("esa.restlight.server.schedule.RequestTaskHook")))` means "none of these classes can be available".

**Comment by chenjazz** [comment]
@mateuszrzeszutek I hava understand already.Thank you very much.

**Comment by mateuszrzeszutek** [comment]
Glad to have been of help!
I'll close this issue for now - please reopen it or open another one if you have any more questions.
