### ISSUE TITLE
muzzleMatcher mismatch problem

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#4958]
I want to apply nacos service discovery in my agent without import nacos sdk in my service sdk, so i tried this code
```
public class NacosInstrumentation implements TypeInstrumentation {
  @Override
  public ElementMatcher<TypeDescription> typeMatcher() {
    return named("org.springframework.boot.SpringApplication");
  }

  @Override
  public void transform(TypeTransformer transformer) {
    transformer.applyAdviceToMethod(
        named("run").and(takesArgument(0, Class[].class)), NacosInstrumentation.class.getName() + "$AddListenerAdvice");
  }

  public static class AddListenerAdvice {

    @Advice.OnMethodEnter(suppress = Throwable.class)
    public static void addListenerEnter() {

      System.out.println("nEnter");
    }

    @Advice.OnMethodExit(onThrowable = Throwable.class, suppress = Throwable.class)
    public static void addListenerExit(@Advice.Return() ConfigurableApplicationContext context) {
      Environment env = context.getEnvironment();
      String name = env.getProperty("nacos.name");
      String url = env.getProperty("nacos.url");
      String port = env.getProperty("server.port");

      System.out.println(name);
      System.out.println(url);
      System.out.println(port);

      NamingService namingService;
      try {
        namingService = new NacosNamingService(url);
        namingService.registerInstance(name, "127.0.0.1", Integer.parseInt(port == null ? "8080" : port));
      } catch (NacosException e) {
        System.out.println(e.getErrMsg());
      }

      System.out.println("nExit");
    }
  }
}
```
but it didn't work by the following warning
```
[otel.javaagent 2021-12-21 09:43:47:277 +0800] [main] WARN muzzleMatcher - Instrumentation skipped, mismatched references were found: nacos [class io.opentelemetry.javaagent.instrumentation.demo.NacosInstrumentationModule] on jdk.internal.loader.ClassLoaders$AppClassLoader@1f89ab83
[otel.javaagent 2021-12-21 09:43:47:294 +0800] [main] WARN muzzleMatcher - -- io.opentelemetry.javaagent.instrumentation.demo.NacosInstrumentation$AddListenerAdvice:99 Missing class com.alibaba.nacos.client.naming.NacosNamingService
[otel.javaagent 2021-12-21 09:43:47:295 +0800] [main] WARN muzzleMatcher - -- io.opentelemetry.javaagent.instrumentation.demo.NacosInstrumentation$AddListenerAdvice:102 Missing class com.alibaba.nacos.api.exception.NacosException
[otel.javaagent 2021-12-21 09:43:47:295 +0800] [main] WARN muzzleMatcher - -- io.opentelemetry.javaagent.instrumentation.demo.NacosInstrumentation$AddListenerAdvice:100 Missing class com.alibaba.nacos.api.naming.NamingService
```
Is there anybody give me a possible solution?

**Comment by iNikem** [comment]
If you use nacos classes during your application runtime, you have to have those classes in the runtime somehow. If you don't want to add those classes (nacos SDK) into application classpath, then you can use [extension mechanism](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension) to package them together with your instrumentation as an agent extension/module.

**Comment by xiangtianyu** [comment]
I tried to write an instrumentation in the directory opentelemetry-java-instrumentation/instrumentation,and packaged with the whole project as an agent.jar.When i run with java -javaagent:opentelemetry-javaagent-1.10.0-SNAPSHOT.jar -Dotel.javaagent.debug=true -jar service.jar,it failed.I think what i did is just "package them together with your instrumentation as an agent extension/module".where did I go wrong?

**Comment by laurit** [comment]
If these classes are not present in your application, but are present inside your extension then you need to override `InstrumentationModule.isHelperClass` in your instrumentation module to return true for these classes. Only helper classes are injected into application class loader.

**Comment by xiangtianyu** [comment]
I've tried `isHelperClass`, but nacos has too many dependencies. So when i set all dependencies in `isHelperClass`, it reported `Method too large: io/opentelemetry/javaagent/instrumentation/demo/NacosInstrumentationModule.getMuzzleReferences ()Ljava/util/Map;` SAD

**Comment by trask** [comment]
hi @xiangtianyu, typically helper classes are designed for injecting just a handful of classes into the application to assist with the instrumentation. if you need to provide a huge number of "helper" classes, you may want to shade and bundle the dependencies into a "bootstrap" module where they will be available to the instrumentation

**Comment by trask** [comment]
Closing, but let us know if you are still having this question and we will re-open.

**Comment by XiaoWeiKIN** [comment]
hi @trask , How to add dependencies (numerous helper classes) to the bootstrap module? can  you provide a simple example,thanks.
