### ISSUE TITLE
jvm metrics definition and implemention

### ISSUE THREAD

**Issue by yangtaoran** [open-telemetry/opentelemetry-java-instrumentation#4988]
I find https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics implement some runtime metrics, I want to know where define them and others runtime metrics will implement, like Prometheus jvm metrics https://github.com/prometheus/client_java/tree/master/simpleclient_hotspot/src/main/java/io/prometheus/client/hotspot.

**Comment by trask** [comment]
hi @yangtaoran! I'm not sure, but maybe you are looking for https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions where the metrics are spec'd, can you clarify? thx

**Comment by trask** [comment]
oh, I think your question is similar to what the JVM Metrics group is working on, establishing what JVM runtime metrics we should be capturing (and names/dimensions/etc).

check out this work-in-progress: https://docs.google.com/spreadsheets/d/1pkbx4o4ci-CejB-LZ3mXAjnvvwRP7jSEct9DpCun7Jw, the tabs across the bottom show different existing systems that we are attempting to unify

**Comment by yangtaoran** [comment]
> the tabs across the bottom show different existing systems that we are attempting to unify

Yes,this is what I want to konw. So,there is no uniform standard of opentelemetry jvm metrics. Is my understanding right?

**Comment by trask** [comment]
> > the tabs across the bottom show different existing systems that we are attempting to unify
> 
> Yes,this is what I want to konw. So,there is no uniform standard of opentelemetry jvm metrics. Is my understanding right?

correct, not yet, this is work-in-progress 👍

**Comment by mateuszrzeszutek** [comment]
We've implemented the following JVM metrics: https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/runtime-environment-metrics/#jvm-metrics

@yangtaoran if there's anything you're missing, please reopen this issue or open a new one.
