### ISSUE TITLE
Spring RMI instrumentation

### ISSUE THREAD

**Issue by Samudraneel24** [open-telemetry/opentelemetry-java-instrumentation#4999]
The existing Java RMI instrumentation doesn't work for applications based on Spring RMI.
I have implemented separate `javaagent` instrumentation for Spring RMI and would be happy to contribute it, if it belongs to the auto instrumentation agent.

**Comment by iNikem** [comment]
Sure, all PRs are welcomed :)

**Comment by Samudraneel24** [comment]
Resolved in #5033
