### ISSUE TITLE
Document otel.instrumentation.external-annotations.include

### ISSUE THREAD

**Issue by theletterf** [open-telemetry/opentelemetry-java-instrumentation#5000]
While documenting instrumentations' settings in #4981, @iNikem commented that we should better document the following property: 

```
| System property 	| Type 	| Default 	| Description 	|
|-----------------	|------	|---------	|-------------	|
| `otel.instrumentation.external-annotations.include` | String	| Default annotations | Configuration for trace annotations, in the form of a pattern that matches `'package.Annotation$Name;*'`.
```

Link to the relevant comment: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4981#discussion_r777327466

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
