### ISSUE TITLE
Restructure Spring documentation

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5002]
`instrumentation/spring/README.md` is all about non-javaagent usage, and could probably be structured better.

it has three parts:
* [Manual Instrumentation with Java SDK](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring#manual-instrumentation-with-java-sdk)
* [Manual Instrumentation using Handlers and Filters](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring#manual-instrumentation-using-handlers-and-filters)
* [Auto Instrumentation using Spring Starters](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring#auto-instrumentation-using-spring-starters)

the first two parts aren't specific to any of the instrumentation modules in this repo, and just describe manually instrumenting Spring using OpenTelemetry SDK directly. These two sections may not belong in this repo at all.

the third part could then be moved to `instrumentation/spring/starters`

the only thing left in `instrumentation/spring/README.md` (for now) would be the settings section (and maybe a link to the starters doc).

**Comment by pizzaz93** [comment]
The first two sections would belong in [https://github.com/open-telemetry/opentelemetry-java-docs](https://github.com/open-telemetry/opentelemetry-java-docs) or [https://opentelemetry.io/docs/instrumentation/java/manual(https://opentelemetry.io/docs/instrumentation/java/manual/) ?

The third section would be integrated into the starter sub folders or a general readme on that page?

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
