### ISSUE TITLE
how do JVM metrics add service name and instance lable

### ISSUE THREAD

**Issue by XiaoWeiKIN** [open-telemetry/opentelemetry-java-instrumentation#5006]
I find that the JVM metrics does not have service name and instance lable. How do I differentiate metrics for that instance, or is there somewhere I can configure it？

**Comment by yangtaoran** [comment]
As far as I know, the agent runtimemetrics cannot add custom label. If you use Prometheus server to scrap metrics, you can config the Prometheus static_config labels to add global custom label.

**Comment by XiaoWeiKIN** [comment]
If runtimemetrics does not have instance lable, I'm not going to be able to tell which instance metrcis it is.

**Comment by yangtaoran** [comment]
https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/SdkMeterProviderBuilder.java#L56
Here,the SdkMeterProviderBuilder provide set resource method.
So,you can implment the spi https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/metrics/SdkMeterProviderConfigurer.java#L17 to set resource,the resource contain instance attribute.

**Comment by trask** [comment]
Closing, I think this is being tracked now in the SDK repo: https://github.com/open-telemetry/opentelemetry-java/issues/4552
