### ISSUE TITLE
Support slf4j MDC auto-instrumentation

### ISSUE THREAD

**Issue by XSAM** [open-telemetry/opentelemetry-java-instrumentation#5013]
**Is your feature request related to a problem? Please describe.**
We are using `slf4j` for logging. [Logger MDC auto-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/7c58220d65913386cee8fb2bf7eb6910752aac13/docs/logger-mdc-instrumentation.md) does not support `slf4j` yet.

**Describe the solution you'd like**
Support `slf4j` MDC auto-instrumentation.

**Comment by anuraaga** [comment]
Hi @XSAM - we automatically instrument logback and log4j for MDC, do you use a different logging backend?

**Comment by XSAM** [comment]
Thank you. @anuraaga 

We use [Quarkus](https://quarkus.io/guides/logging), and it uses [jboss-logmanager](https://github.com/jboss-logging/jboss-logmanager) as its only logging backend, which we cannot change.

IIUC, if we can automatically instrument a logging interface like `slf4j`, we do not have to support every logging backend. Since `slf4j` already has binding/adaptor libs for logging backend like `log4j`.

**Comment by kushal-ti** [comment]
@anuraaga i'd like to add to this, i'm using logback through sl4j, but the MDC context is not being injected with the traceId and spanId.

i have the following toy code (taken from https://github.com/williewheeler/otel-demo)
```
    @GetMapping("/flights")
    public CollectionModel<Flight> getFlights() {
        log.info("Received GET /flights");
        return flightService.getFlights();
    }
```
with the following pattern in logging configuration 
```
logging:
  level: "INFO"
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg trace_id=%X{trace_id} span_id=%X{span_id} trace_flags=%X{trace_flags} %n"
```

but the logs generated by this do not have trace_id or span_id being injected. the logs just say 

2022-03-23 09:32:51 - c.w.d.otel.api.web.FlightController - GET /flights trace_id= span_id= trace_flags=

**Comment by trask** [comment]
hi @kushal-ti, what version of the javaagent are you using? the version in that repository is ~2 years old

**Comment by kushal-ti** [comment]
You're right, upgrading the javaagent worked. Thanks you !

**Comment by trask** [comment]
this should be supported in 1.13.1 (via both logback and jboss-logmanager)
