### ISSUE TITLE
Parent service name should be in current span.

### ISSUE THREAD

**Issue by vinitaaher** [open-telemetry/opentelemetry-java-instrumentation#5039]
Hi All,
I did open telemetry instrumentation for java . But currently we get only parent span id in current span instead name of the parent service. We need parent service name as well so that currently we are traversing huge number of span to get the parent service name along with child service name. But if number of span increase like 80,00,000 then performance is worst. So it willl be best if we get parent service name or either any easy way to conclude parent service name like  time when the whole trace will be finished some thing kind of like that.

**Comment by trask** [comment]
hi @vinitaaher, this sounds like a good use case for baggage. you can attach your parent service name to baggage, and then write a SpanProcessor to read it from baggage on each span and attach it as a span attribute. if you're using the javaagent and want to write a SpanProcessor, you'll need to build a javaagent extension, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension#introduction

**Comment by vinitaaher** [comment]
Thank You @trask for your response. will it work consistently? Because every time modifying span is not feasible when using java agent. Is there any other way?

**Comment by trask** [comment]
> Because every time modifying span is not feasible when using java agent

can you expand on this, I'm not sure I am following, thx

**Comment by trask** [comment]
Closing, let us know if you are still facing this issue and can provide more details and we'll re-open, thx!
