### ISSUE TITLE
lettuce-5.0 tests run only on java 8

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#504]
If you look at a build, for example here

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1291/workflows/6aa5dcc9-cad7-49fa-8415-f3757838a2fe/jobs/10525/steps

you'll notice `lettuce-5.0:test` is `SKIPPED`, unlike others

```
> Task :instrumentation:jedis:jedis-1.4:test
> Task :instrumentation:lettuce:lettuce-5.0:compileTestGroovy UP-TO-DATE
> Task :instrumentation:lettuce:lettuce-5.0:processTestResources NO-SOURCE
> Task :instrumentation:lettuce:lettuce-5.0:testClasses UP-TO-DATE
> Task :instrumentation:lettuce:lettuce-5.0:test SKIPPED
> Task :instrumentation:log4j:log4j-1.1:compileTestJava NO-SOURCE
> Task :instrumentation:log4j:log4j-1.1:compileTestGroovy UP-TO-DATE
> Task :instrumentation:log4j:log4j-1.1:processTestResources
> Task :instrumentation:log4j:log4j-1.1:testClasses
> Task :instrumentation:jedis:jedis-3.0:test
```

Locally, I see this

```
> Task :instrumentation:lettuce:lettuce-5.0:test SKIPPED
Skipping task ':instrumentation:lettuce:lettuce-5.0:test' as task onlyIf is false.
:instrumentation:lettuce:lettuce-5.0:test (Thread[Execution worker for ':' Thread 6,5,main]) completed. Took 0.0 secs.
```

Digged the Gradle configs some but couldn't find why this would happen.

As a trackback, also asked on Gitter about this issue but filing to make sure it's not lost - https://gitter.im/open-telemetry/opentelemetry-java-instrumentation?at=5ee34e3e7c64f31f11577744

**Comment by iNikem** [comment]
lettuce-5 module is configured to run only on java8 and it does run with java8: https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1291/workflows/6aa5dcc9-cad7-49fa-8415-f3757838a2fe/jobs/10528

Your link points to test job on java11, which indeed skips that module

**Comment by anuraaga** [comment]
Oops - that's the `maxJavaVersionForTests` it looked like a source compatibility thing and I ignored it :( Makes sense.

Does it make sense to remove the max version? For reference, I didn't even notice this since I use JDK 11 for development. Makes it a tiny bit harder for a contributor if they run into JDK version causing tests to be skipped ;)

**Comment by iNikem** [comment]
I don't know any reasons why it shouldn't run on later java version. Lettuce documentation certainly does not forbid it. You can try running it on 11 and if it works, feel free to remove that constraint.
