### ISSUE TITLE
Remove http.target from metric attributes to control cardinality

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5047]
From @anuraaga's https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4930#issuecomment-1007233945:

> For 1.10 we should go ahead and remove HTTP_TARGET from all metrics and live with it being gone until providing view configuration to javaagent users.
>
> https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/25550e0a633a8c5186e1a517cb67d42a3f1a5772/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/TemporaryMetricsView.java#L98-L101

@jsuereth I know you had wanted `http.target` as a fallback since we aren't capturing `http.route` consistently yet, and metrics aren't nearly as useful without any route-like dimension. @mateuszrzeszutek has started the work on capturing `http.route` (#4852) but that work may not be finished in time for 1.10.0, so we need to make a decision on what to do in 1.10.0 release (and hopefully we'll have real solution, with `http.route`, in the next month or so).

**Comment by mateuszrzeszutek** [comment]
> @mateuszrzeszutek has started the work on capturing `http.route` (#4852) but that work may not be finished in time for 1.10.0

Yep, I might not be able to finish that this week (most likely not) - the micrometer work took a lot of time to finish. Should we just remove `http.target` for the time being? And/or add a property that allows including it as an attribute?
