### ISSUE TITLE
Add smoke test for logging signal

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5048]
Now that we are updated to SDK 1.10.0, and have logging exporter autoconfiguration (https://github.com/open-telemetry/opentelemetry-java/pull/4015), we should add smoke test for logging signal to make sure that it's all working together.

**Comment by breedx-splk** [comment]
I can take this.

**Comment by breedx-splk** [comment]
Just to make sure we're on the same page @trask  -- is our expectation right now that we should be able to just set `OTEL_LOGS_EXPORTER=otlp` and any app that does logging with log4j or logback should start exporting logs? Is there an additional step of hooking up a specific exporter?

Do we think we can get away with (re)using one of the existing smoke test app images? It looks like `grpc` uses log4j and `play` uses logback...

**Comment by trask** [comment]
> is our expectation right now that we should be able to just set `OTEL_LOGS_EXPORTER=otlp` and any app that does logging with log4j or logback should start exporting logs?

yes, I think (hope) so 👍

> Do we think we can get away with (re)using one of the existing smoke test app images? It looks like `grpc` uses log4j and `play` uses logback...

I think the spring-boot smoke test is a good catch-all. We only need a smoke test for one of the logging instrumentations (just to make sure the signal hookup is working, the instrumentation-specific tests should cover the rest).

**Comment by breedx-splk** [comment]
> I think the spring-boot smoke test is a good catch-all. We only need a smoke test for one of the logging instrumentations (just to make sure the signal hookup is working, the instrumentation-specific tests should cover the rest).

Yup, and spring-boot smoke test is the one I used first but didn't get logs out. 🤔 

I'll keep after it.
