### ISSUE TITLE
Jedis and Redisson instrumentation recording duration equals 0

### ISSUE THREAD

**Issue by ralphgj** [open-telemetry/opentelemetry-java-instrumentation#5061]
**Describe the bug**
The duration of spans created by jedis or redisson instrumentation equals 0, it seems incorrectly.
![image](https://user-images.githubusercontent.com/7887053/148730721-38c34859-7cd7-49a2-967e-b01f6829f4db.png)

**Steps to reproduce**
Use the latest agent and observe the spans created by jedis or redisson instrumentation

**What did you expect to see?**
Jedis or redisson instrumentation recording duration with the actual value.

**What did you see instead?**
Jedis or redisson instrumentation recording duration with 0.

**What version are you using?**
v1.9.1

**Comment by laurit** [comment]
I wasn't able to reproduce this with test in this repository. Both redisson and jedis seem to report a non-zero duration.

**Comment by ralphgj** [comment]
> They both do not capture the whole execution though: Jedis instrumentations have a comment that explicitly says that only sending the request is instrumented, processing/getting the response is not; and it looks like the instrumented Redisson method returns a netty `ChannelFuture` that we completely ignore and finish the span on return, not when the future completes. So I guess that a zero duration is quite possible with both of these.

Thank you for your reply, I read the code and that you said above should be the root cause. So would you have some plan or proposals to resolve this problem?

**Comment by mateuszrzeszutek** [comment]
> Thank you for your reply, I read the code and that you said above should be the root cause. So would you have some plan or proposals to resolve this problem?

Redisson was quite simple to fix, I've fixed it here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5061

And I just noticed that you've implemented the fix for jedis, that's great, thanks! Looks like that should cover the whole issue.

**Comment by ralphgj** [comment]
> > Thank you for your reply, I read the code and that you said above should be the root cause. So would you have some plan or proposals to resolve this problem?
> 
> Redisson was quite simple to fix, I've fixed it here: #5073
> 
> And I just noticed that you've implemented the fix for jedis, that's great, thanks! Looks like that should cover the whole issue.

Yes, thank you for your help.

**Comment by trask** [comment]
thx for reporting this @ralphgj!

I believe this is closed now by #5073 and #5256
