### ISSUE TITLE
Minimum Java version

### ISSUE THREAD

**Issue by alanmcg** [open-telemetry/opentelemetry-java-instrumentation#5064]
I would like to implement telemetry for an incredibly old application I'm unfortunately forced to support, it is compiled with and runs on java6, unfortunately there are some significant features that stop it from running on more modern java versions.
Does this java instrumentation run on java6 or is there an old release that might have support? I tried searching releases and issues but couldn't find any deprecation notice. Just one issue where someone mentioned that ["we supported java6" ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4326#issuecomment-938731143)

**Comment by breedx-splk** [comment]
Hi @alanmcg. The instrumentation only supports java 8+.
There is [some rationale over here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/ea7588cd158ec14beb0cd418d30dc6ac24de5dd7/docs/java-7-rationale.md) about why the choice was made to not support java 7 (which really means supporting 8+).

Java 6 really is a bit of a liability at this point.

**Comment by trask** [comment]
hey @alanmcg, you could look at Zipkin/Jaeger Java client libraries which support Java 6, and you can point those at the OpenTelemetry Collector if you need to bridge them in to the OTel world
