### ISSUE TITLE
Confirm adding thread details by default

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#5069]
Was taking a look at #4641 and while thinking about it wanted to confirm the decision to add thread details by default in the javaagent. `Thread.currentThread` is a "relatively expensive method" so I wonder if it's too much to be called for every single span by default. I originally added the property to disable in #3464 but can't remember if we ever discussed whether opt-in or opt-out is actually better so figured it'd be worth to doublecheck.

**Comment by laurit** [comment]
My intuition on this is the opposite, I'd assume that calling `Thread.currentThread` is almost free. Perhaps the belief that it is expensive comes from it being a native method. But nowadays `Thread.currentThread` is intrinsified so calling it doesn't have the cost of calling native method. Look at a recent patch that adds interpreter intrinsic for `Thread.currentThread` on amd64 https://github.com/openjdk/jdk/commit/f7309060ded0edb1e614663572f876d83b77c28e If I interpret it correctly vm keeps reference to current thread (c++ object) in a register, java thread object is a field in that c++ object.
I didn't try to benchmark it.

**Comment by anuraaga** [comment]
Thanks @laurit for the pointers. For reference, I found the JIT for it which has been around for much longer

https://github.com/openjdk/jdk/blob/jdk-17+35/src/hotspot/share/opto/library_call.cpp#L866

Ran some benchmarks on Java 17 and could confirm there is no difference in performance with the call to `currentThread` there, nice
