### ISSUE TITLE
Propagate the whole context instead of only the current span

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#507]
There are lots of places where we propagate the current span to another thread.

I think we need to change all of these to propagate the whole context instead.

E.g. https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/503#discussion_r439701517

**Comment by iNikem** [comment]
@trask do you have any suggestions how can I find these "lots of places"?

**Comment by trask** [comment]
look for calls to `Span.Builder.setParent(Span)` (there aren't too many of these)

and look for calls to `TracingContextUtils.currentContextWith(Span)` (unfortunately there are lots of these that are not relevant to this issue, not sure how to filter these better)

**Comment by iNikem** [comment]
@trask I propose to close this issue now. If there are more places left, they can be addressed on an ongoing basis

**Comment by trask** [comment]
👍
