### ISSUE TITLE
Spring kafka instrumentation creates separate producer and consumer traces.

### ISSUE THREAD

**Issue by hardik-fareye** [open-telemetry/opentelemetry-java-instrumentation#5074]
**Is your feature request related to a problem? Please describe.**
In my use case, a single client request from an API controller sends some data to a Kafka topic. Then a batch consumer consumes those events, applies some processing, and stores the data into a DB. I want to trace the flow of a particular client request (from start to end) in a single trace.

I am using **spring-kafka** instrumentation for tracing the requests. The current implementation is creating separate traces for the producer and consumer spans. The root span in consumer trace does have a link to the producer trace, but it would be better for my use case if both producer and consumer traces obtain a single trace ID.

**Describe the solution you'd like**
Is it possible to encapsulate the consumer trace into its corresponding producer event trace? Please create a config/option to do so. 
I am aware of the batch processing spec provided in [https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving) but it seems to be valid only if multiple entries are made by a single produce event.

**Describe alternatives you've considered**
I tried to set the `otel.instrumentation.common.experimental.suppress-messaging-receive-spans` flag to true, but still, the producer and consumer traces are occurring seperately.

**Comment by trask** [comment]
hi @hardik-fareye!

> The root span in consumer trace does have a link to the producer trace

this is surprising to me, I thought that links would not be added when using `otel.instrumentation.common.experimental.suppress-messaging-receive-spans=true`:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/39d20b5fbc79ab38b7ce685fd5f2610e961ba1e6/instrumentation/kafka/kafka-clients/kafka-clients-common/library/src/main/java/io/opentelemetry/instrumentation/kafka/internal/KafkaInstrumenterFactory.java#L101-L106

**Comment by mateuszrzeszutek** [comment]
> I am aware of the batch processing spec provided in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving but it seems to be valid only if multiple entries are made by a single produce event.

That link actually describes a situation when multiple messages generated by multiple produce events are consumed in a single batch - which is exactly what happens in the spring-kafka batch scenario.
You've mentioned a "batch consumer", can I assume that your service receives the messages in batch? Can you post the listener code/interface?

If it's a batch consumer then unfortunately it's pretty much impossible for producer and consumer spans to be in the same trace -- since a batch consumer receives multiple messages it is not possible to determine which one should be the parent of the consumer span. We're adding span links as a "best effort" method of preserving the connection between producer& consumer spans/traces.

**Comment by hardik-fareye** [comment]
Hello @trask  
> this is surprising to me, I thought that links would not be added when using `otel.instrumentation.common.experimental.suppress-messaging-receive-spans=true`:

When this was added, I had the reference of the producer trace in the root span of the consumer. Link to the screenshot: https://drive.google.com/file/d/1NXbq8CggnvrNyGN4ZwUoy6AITa7scx3Z/view?usp=sharing

When this attribute was not used, I was able to see 2 links: a link to a separate consume trace and the producer trace also.

Hi @mateuszrzeszutek,
> You've mentioned a "batch consumer", can I assume that your service receives the messages in batch? Can you post the listener code/interface?

Yes, the service receives the message in batch. Attaching a code of one of the listeners.

```
@KafkaListener(containerFactory = "reverseConnectorKafkaListenerContainerFactory", topicPattern = "#{'${app.environment}'}" + "_" + KafkaConstants.KAFKA_TOPIC_PROCESS_REVERSE_CONNECTOR,  groupId = KafkaConstants.GROUP_ID_CONFIG)
    public void listen(List<ConsumerRecord<Long, String>> requestRecords, Acknowledgment acknowledgment) {
        if (!CollectionUtils.isEmpty(requestRecords)) {
            requestRecords.forEach(requestRecord -> {

             // Some operations here

            });
        }
        acknowledgment.acknowledge();
    }
```

**Comment by trask** [comment]
> When this attribute was not used, I was able to see 2 links: a link to a separate consume trace and the producer trace also.

thanks, this makes sense.

I believe @mateuszrzeszutek's [comment ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5074#issuecomment-1011152079) above best explains the situation:

> If it's a batch consumer then unfortunately it's pretty much impossible for producer and consumer spans to be in the same trace -- since a batch consumer receives multiple messages it is not possible to determine which one should be the parent of the consumer span. We're adding span links as a "best effort" method of preserving the connection between producer& consumer spans/traces.

**Comment by hardik-fareye** [comment]
@trask
I understood the point.
Just one last query. Is it possible to add links of consumer traces in the corresponding producer trace also?

**Comment by mateuszrzeszutek** [comment]
> Is it possible to add links of consumer traces in the corresponding producer trace also?

So that you have links in both directions, right? Unfortunately I'm afraid that won't be possible, for several reasons: the producer may be already done by the time the consumer picks up the message; and it would require passing the consumer traceId&spanId back to the producer, which is also not possible in Kafka.

**Comment by hardik-fareye** [comment]
Okay @mateuszrzeszutek 
Thanks

**Comment by sukrit007wawa** [comment]
Just ran into this issue with https://docs.spring.io/spring-kafka/api/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.html . I this case, we are not batching it,  but OTel aut instrumentation is generating seprate trace if for consumer

**Comment by mateuszrzeszutek** [comment]
It looks like `ReplyingKafkaTemplate` actually implements `BatchMessageListener`: https://github.com/spring-projects/spring-kafka/blob/main/spring-kafka/src/main/java/org/springframework/kafka/requestreply/ReplyingKafkaTemplate.java#L72
It probably receives messages in batch internally, even though its `sendAndReceive()` methods do not reflect that.

**Comment by sukrit007wawa** [comment]
@mateuszrzeszutek  That makes sense.   Thanks.
