### ISSUE TITLE
Improve library instrumentation docs/quickstart for kafka

### ISSUE THREAD

**Issue by breedx-splk** [open-telemetry/opentelemetry-java-instrumentation#5078]
**Is your feature request related to a problem? Please describe.**

A user that wants to use the [kafka library instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/kafka/kafka-clients) will have a hard time finding guidance. [Other library instrumentations](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/1d453debe34c816cb584ccf1a7dea022de1f11de/docs/standalone-library-instrumentation.md) have [pretty good documentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/1d453debe34c816cb584ccf1a7dea022de1f11de/instrumentation/jdbc/library#quickstart) with example code, but kafka-clients library instrumentation is currently missing the same level of detail.

**Describe the solution you'd like**
Add kafka to the list of library instrumentations and provide a helpful README(s) for the kafka library instrumentation.

**Describe alternatives you've considered**
Users can just read the instrumentation code and try to piece it together, but having a quickstart we be even better.

**Additional context**
Original context comes from an opentelemetry user deploying code into AWS KDA (managed kafka) where autoinstrumentation is not easily used. Their primary use case is trace context propagation.

**Comment by ppatierno** [comment]
@breedx-splk @mateuszrzeszutek if you like I can open a PR about this with the content I set up for one of my repositories where I am playing around with OpenTelemetry with Kafka. See this [README.md](https://github.com/ppatierno/kafka-opentelemetry/blob/main/README.md).

**Comment by mateuszrzeszutek** [comment]
Hey @ppatierno ,
That'd be awesome, thanks! 
One small note: we would probably replace the "setting up the SDK" section with a link to the [opentelemetry.io docs](https://opentelemetry.io/docs/instrumentation/java/manual), to avoid duplicating the documentation.

**Comment by ppatierno** [comment]
@mateuszrzeszutek yeah I could use a link to the official doc but it would miss the first lines of code about setting the right attribute for the service name and the resource which I needed to make it working on my side. Any ideas/suggestions?

**Comment by mateuszrzeszutek** [comment]
Hmm, when it comes to the javaagent, there already is a bit of information about [setting the attributes](https://opentelemetry.io/docs/instrumentation/java/automatic/#configuring-the-agent).

The manual instrumentation page does not mention it at all - I believe it should mention at least the service name, since it's a very important attribute. We should probably add it to the docs (which would be out of scope for this issue, we'd need a new one in https://github.com/open-telemetry/opentelemetry.io)

**Comment by ppatierno** [comment]
@mateuszrzeszutek good point! I opened this issue https://github.com/open-telemetry/opentelemetry.io/issues/1582 and I could work on it as well.

**Comment by breedx-splk** [comment]
I think we're good. Thanks @ppatierno and reviewers!
