### ISSUE TITLE
Combine javaagent and "standalone" supported libraries tables

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5109]
Merge this list https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/standalone-library-instrumentation.md#standalone-library-instrumentation into this table: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks

try out columns to note that javaagent / library instrumentation is supported

and also an additional column to (very briefly) describe the instrumentation, especially in confusing cases like logging frameworks

**Comment by pizzaz93** [comment]
- [ ] Merge Tables
- [ ] Column for java agent or library instrumentation being supported
- [ ] Column for brief instrumentation overview

**Comment by trask** [comment]
This is done
