### ISSUE TITLE
More stable selection of exporter to use

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#511]
Isn't it quite normal to use the fully qualified class name when selecting an SPI implementation? SDK currently uses the approach too. It's guaranteed to be unique based on the nature of a Java classpath, while a name provided by a method has chances of collision which seems like something we don't want to deal with.

Having a hard-coded mapping from a short name to the fully qualified name for well-known implementations in the agent like otlp, logging, jaeger and zipkin seems like it could also provide the simpler UX without the risk of conflicting names from random exporters on the classpath.

_Originally posted by @anuraaga in https://github.com/open-telemetry/opentelemetry-java/issues/1332#issuecomment-643584471_

**Comment by iNikem** [comment]
I like both options from the comment above:

- Select exporter by fully classified name of its factory
- Have hard-coded mapping of short names to factories

I probably would favour the second option, it is more user-friendly.

**Comment by trask** [comment]
👍 to the user-friendly option

**Comment by anuraaga** [comment]
To clarify, I didn't mean to necessarily have two options :) We can accept both a fully qualified name (will be useful for people shading their own agent binary with a potentially custom exporter) and the short one to have and eat the cake

**Comment by anuraaga** [comment]
While talking about classifiers had a new thought. Instead of a set of short names, we don't really need any short names. How about automatically activating an exporter based on the presence of the endpoint flag, like `ota.otlp.endpoint`, `ota.zipkin.endpoint`? Currently we only load one exporter but it'd actually be sort of nice if we could just go ahead and enable all the exporters that users set the endpoint for.

**Comment by trask** [comment]
> Instead of a set of short names, we don't really need any short names. How about automatically activating an exporter based on the presence of the endpoint flag, like `ota.otlp.endpoint`, `ota.zipkin.endpoint`? Currently we only load one exporter but it'd actually be sort of nice if we could just go ahead and enable all the exporters that users set the endpoint for.

I like this proposal.

Also, it addresses this part of #385:

> We currently only support a single exporter jar, so how does someone use jaeger + prometheus?

**Comment by iNikem** [comment]
And #496

**Comment by trask** [comment]
Does it make sense to close this issue and move the proposal over to #496?

**Comment by trask** [comment]
Closing, moved above proposal over to #496
