### ISSUE TITLE
Autoclose TracerProvider in Spring-Boot Application

### ISSUE THREAD

**Issue by frommeyerc** [open-telemetry/opentelemetry-java-instrumentation#5124]
**Is your feature request related to a problem? Please describe.**
According to `SdkTracerProvider#close()` JavaDoc this method should be called before the application is shut down in order to make sure all spans are reported. With the current spring-boot autoconfig this is not the case.

**Describe the solution you'd like**
While the current autoconfiguration create the `SdkTracerProvider` as a POJO baked into the `OpenTelemetry` `@Bean` it should become a `@Bean` in it's own right. This will allow the Spring-Context to call it's `#close()` method when the Context is destroyed.

**Describe alternatives you've considered**
As there seam to be no other `@Bean`s that would do the shutdown instead I didn't see another option.

I'm already preparing a PR for this change.

**Comment by trask** [comment]
Closed by #5125
