### ISSUE TITLE
Akka HTTP bindFlow leads to non working http tracing

### ISSUE THREAD

**Issue by makssobolevs** [open-telemetry/opentelemetry-java-instrumentation#5137]
**Description**
When Akka HTTP server is created via `Http().newServerAt("localhost", 8080).bindFlow(...)` tracing doesn't work.
[ServerBuilder#bindFlow](https://doc.akka.io/api/akka-http/current/akka/http/scaladsl/ServerBuilder.html#bindFlow(handlerFlow:akka.stream.scaladsl.Flow[akka.http.scaladsl.model.HttpRequest,akka.http.scaladsl.model.HttpResponse,_]):scala.concurrent.Future[akka.http.scaladsl.Http.ServerBinding])

**Steps to reproduce**
App.scala
```scala
object App {
  val testRoute: Route =
    pathPrefix("test") {
      get {
        complete(HttpResponse(StatusCodes.OK))
      }
    }

  def main(args: Array[String]): Unit = {
    implicit val system = ActorSystem("Test")
    implicit val ec = system.dispatcher

    Http()
      .newServerAt("localhost", 8080)
      .bindFlow(testRoute)
  }
}
```
Example project can be used: https://github.com/makssobolevs/akka-open-telemetry-test
curl -v http://localhost:8080/test

**Would expect to see**
`
[otel.javaagent 2022-01-15 16:43:21:043 +0300] [Test-akka.actor.default-dispatcher-8] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'akka.request' : 74ca4c186762a998ef416fd184f9e463 5ae09c56f79725a0 SERVER [tracer: io.opentelemetry.akka-http-10.0:1.9.2] AttributesMap{data={thread.name=Test-akka.actor.default-dispatcher-8, http.method=GET, http.scheme=http, http.host=localhost:8080, thread.id=22, http.target=/test, http.user_agent=curl/7.80.0, http.flavor=1.1, http.status_code=200}, capacity=128, totalAddedValues=9}`

**Actual result**
No span in logs

**Version**
opentelemetry-javaagent 1.9.2
Akka 2.6.14
Akka HTTP 10.2.4
Scala 2.13.5
OpenJDK 11.0.13

**Additional context**
There is the same issue with New Relic agent https://github.com/newrelic/newrelic-java-agent/issues/189.
ServerBuilder#bind which works fine can be used so it's probably not a big issue.

**Comment by rahuldimri** [comment]
Are we still working on this issue? Can I work on this ?

**Comment by mateuszrzeszutek** [comment]
Hey @rahuldimri ,
I think nobody's currently working on this issue. Should I assign it to you?

**Comment by rahuldimri** [comment]
Yes please, I want to give a try !!

**Comment by rahuldimri** [comment]
@mateuszrzeszutek thanks for assigning this to me. I can see there are couple of PR request got closed and were part of this issue. Just wanted to check, do we need to continue working on this request.

**Comment by zackman0010** [comment]
@rahuldimri Our current draft PR will actually correct this issue, we're just still having to wait on our company to sign the Corporate CLA. I've been assured it's still being worked on and is close to completion.

**Comment by rahuldimri** [comment]
Sure no problem take you time.

**Comment by mateuszrzeszutek** [comment]
> @rahuldimri Our current draft PR will actually correct this issue, we're just still having to wait on our company to sign the Corporate CLA. I've been assured they're still working on getting it signed and that it should be completed soon.

Oh, thanks for the info! I missed the fact that your PR is still open, sorry for that 🙏 

@rahuldimri I'll remove your assignment from this issue -- sorry for the confusion!
