### ISSUE TITLE
Create http server in some situation

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#5149]
I have a special situation that i want to refresh the config in my agent. My plan is to start http server in agent, and create a callback request. When the config is modified outside, it will call the callback request to do something in my agent.

Is there any convenient way to solve this problem?

**Comment by trask** [comment]
hi @xiangtianyu, which parts of the configuration are you wanting to update at runtime?

**Comment by xiangtianyu** [comment]
Some custom configs i defined in my instrumentation

**Comment by trask** [comment]
since these are your own configs in your own instrumentation, you could create your own configuration holder and update/read from that

**Comment by xiangtianyu** [comment]
So it means i should create http server by myself and there's no spi or any other solution？

**Comment by mateuszrzeszutek** [comment]
Hey @xiangtianyu ,
No, we currently don't support reloading/changing configuration at all; you have to implement it yourself.

**Comment by xiangtianyu** [comment]
I see. Thanks!

**Comment by laurit** [comment]
Please reopen if you have more questions.
