### ISSUE TITLE
aws-sdk instrumentation is missing the RPC attributes from specification

### ISSUE THREAD

**Issue by blumamir** [open-telemetry/opentelemetry-java-instrumentation#5159]
**Describe the bug**
According to the [spec for Semantic conventions for AWS SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/instrumentation/aws-sdk.md#semantic-conventions-for-aws-sdk), the following attributes are expected for aws-sdk spans: `rpc.method`, `rpc.service`, `rpc.system`.

**Steps to reproduce**
Just run the instrumentation, or browse the code.

**What did you expect to see?**
I expected these attributes to be published by the aws-sdk 1.11 and aws-sdk 2.2 instrumentation according to the spec.

**What did you see instead?**
These attributes are published under different, non-spec attributes which are available only in experimental mode: `aws.operation` and `aws.service`

**What version are you using?**
latest `1.10.0`

**Additional context**
I want to suggest renaming these attributes so they are spec-compliant and to always report them (not only when `otel.instrumentation.aws-sdk.experimental-span-attributes` is true).
If it makes sense, I can work on PR to do that.

**Comment by anuraaga** [comment]
Thanks @blumamir! The collector has been updated to support the `rpc.*` attributes so it's safe to change our instrumentation to replace the non-spec attributes with spec attributes. If you're able to help with a PR that'd be great

**Comment by blumamir** [comment]
Hi @anuraaga , Thanks for taking a look.
I would like to work on it, can you please assign it to me?
