### ISSUE TITLE
Maven surefire configuration

### ISSUE THREAD

**Issue by delanym** [open-telemetry/opentelemetry-java-instrumentation#5177]
I tried adding the agent to my unit tests via the surefire plugin, but there are no spans created. Is this just because my unit tests have nothing of interest to the agent, or because I've not configured it correctly?

``` xml
    <profile>
      <id>trace</id>
      <build>
        <pluginManagement>
          <plugins>
            <plugin>
              <artifactId>maven-surefire-plugin</artifactId>
              <configuration>
                <argLine>-javaagent:${build.root}/target/opentelemetry-javaagent-${dep.opentelemetry-javaagent}.jar</argLine>
              </configuration>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <artifactId>maven-dependency-plugin</artifactId>
            <inherited>false</inherited>
            <executions>
              <execution>
                <id>copy-telemetry-agent</id>
                <goals>
                  <goal>copy</goal>
                </goals>
                <phase>initialize</phase>
                <configuration>
                  <artifactItems>
                    <artifactItem>
                      <groupId>io.opentelemetry.javaagent</groupId>
                      <artifactId>opentelemetry-javaagent</artifactId>
                      <version>${dep.opentelemetry-javaagent}</version>
                      <outputDirectory>${project.build.directory}</outputDirectory>
                    </artifactItem>
                  </artifactItems>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
```

My goal is to have the test output and the stack exception of the failure showing up in the span / visible in Jaeger. At the moment I just get Maven's MojoFailureException (via [the Maven extension](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/maven-extension)) eg
`at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:271)`

**Comment by mateuszrzeszutek** [comment]
Hi @delanym ,

> Is this just because my unit tests have nothing of interest to the agent, or because I've not configured it correctly?

Could be both -- but if you're getting spans from the maven extension then your configuration is most likely okay. The javaagent does not instrument testing frameworks, take a look at our [list of supported libraries](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md) - are you using any of these in your tests?

**Comment by delanym** [comment]
@mateuszrzeszutek yes we're using some of those libraries.

I get this message at the start of the tests
```
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ businesscommon ---             
[INFO]                                                                                                 
[INFO] -------------------------------------------------------                      
[INFO]  T E S T S                                                                                      
[INFO] -------------------------------------------------------
[ERROR] [otel.javaagent 2022-01-20 08:33:25:928 +0200] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.9.1
```

The tests complete successfully. I added `-Dotel.javaagent.debug=true` but it doesn't affect the output.
I added -X and this here are the preceding lines:

```
[DEBUG] Forking command line: /bin/sh -c cd /git/tep22x/tools_businesscommon && /usr/lib/jvm/zulu-fx-8-amd64/jre/bin/java -javaagent:/git/tep22x/target/opentelemetry-javaagent-1.9.1.jar -jar /git/tep22x/too
ls_businesscommon/target/surefire/surefirebooter7219022644785607350.jar /git/tep22x/tools_businesscommon/target/surefire 2022-01-20T08-40-35_548-jvmRun1 surefire7456318789518312389tmp surefire_0766122312856
4791572tmp                                                                                                                                                                                                    
[DEBUG] Fork Channel [1] connected to the client.                                                                                                                                                             
[ERROR] [otel.javaagent 2022-01-20 08:40:36:002 +0200] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.9.1
```

**Comment by mateuszrzeszutek** [comment]
Hm, does the agent output get captured by surefire? Perhaps you'll find more information in the test report files.

Also, you're using environment variables for configuration, right? Can you print out contents of `System.getenv()` somewhere in your test and verify that surefire does not modify/remove variables from parent maven process?

**Comment by delanym** [comment]
@mateuszrzeszutek I don't know what the agent output looks like because Ive never seen it, but that error reported by Maven only outputs once for the plugin execution. Surefire however captures the output for each test. I checked the first test that ran and the output is as normal.

Can you point me to an open source repository on github with this working?

**Comment by delanym** [comment]
@mateuszrzeszutek I see the error I was getting above happens on the latest surefire-plugin, but not 2.22.0

In any case, you can run the ./ot script on the opentelemetry branch at https://github.com/delanym/maven that uses the old surefire plugin version. I still dont see any spans getting produced.

**Comment by delanym** [comment]
@mateuszrzeszutek did you try it out?

In maven-surefire 3.0.0-M6 i don't get any OT output past these 2 lines
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[otel.javaagent 2022-04-25 14:59:46:568 +0200] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.13.0
```

but with 2.22.2 I get
`[otel.javaagent 2022-04-25 15:09:04:593 +0200] [OkHttp http://localhost:4317/...] ERROR io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter - Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317`
and another line for metrics.

It doesn't matter if I try suppress okhttp with `-Dotel.instrumentation.okhttp.enabled=false` or all autoconfig with `-Dotel.instrumentation.common.default-enabled=false -Dotel.instrumentation.opentelemetry-api.enabled=true -Dotel.instrumentation.opentelemetry-annotations.enabled=true`

As long as I'm on 2.22.2 it gives me that output.

**Comment by trask** [comment]
hi @delanym, is this still an issue for you?

**Comment by johnpoth** [comment]
I think this is because unit tests are likely to use the`io.opentelemetry.sdk.testing.exporter.InMemorySpanExporter`. Is there a way to configure the Java Agent to export Spans to it ? @trask

**Comment by trask** [comment]
I think this is the easiest way to test spans exported by the Java agent: https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/telemetry-testing

**Comment by johnpoth** [comment]
Thank you so much for your response! Ah so there is no `InMemoryExporter` of some sort for the Java agent then. I guess this will be more of an integration test. Thanks again!
