### ISSUE TITLE
Datadog Exporter giving 404

### ISSUE THREAD

**Issue by sandeep-jain** [open-telemetry/opentelemetry-java-instrumentation#5181]
**Describe the bug**
I am using Java Library Agent for automatic instrumentation of Java code . as mentioned in the the page https://github.com/open-telemetry/opentelemetry-java-instrumentation

**Steps to reproduce**
1.  deploy Collector on Azure Linux app service ith following configurations 
  

**docker compose.yaml** 
`version: "3"
services:
  
  datadog:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - otmpoc:/etc/otel/
    ports:
      - "4317:55681"   # pprof extension   `

**config.yaml**
`receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 10s

exporters:
  datadog/api:
    hostname: ##########
    env: dev
    service: otmpoc
    version: v1

    tags:
      - otmpoc:v1

    api:
      key: #################
      site: datadoghq.eu

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [datadog/api]`

**docker command which azure app service started** 
docker run -d -p 5808:55681 --name  datadog_0_d7059e19 -e WEBSITE_CORS_ALLOWED_ORIGINS=* -e WEBSITE_CORS_SUPPORT_CREDENTIALS=False -e WEBSITE_PROACTIVE_AUTOHEAL_ENABLED=true -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITES_PORT=4317 -e WEBSITE_SITE_NAME=XXXXXXXX -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=XXXXXXXX.azurewebsites.net -e WEBSITE_INSTANCE_ID=XXXXXXXXX -e HTTP_LOGGING_ENABLED=1 otel/opentelemetry-collector-contrib:latest

2.  Create a Java application and start with the following command 
 java -javaagent:opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=XXX-test-java -Dotel.traces.exporter=otlp -Dotel.exporter.otlp.traces.endpoint=http://<azureappserivcce>-Dotel.javaagent.debug=true  -jar spring.mvc-0.0.1-SNAPSHOT.jar

**What did you expect to see?**
When I hit an API in Java App service   I expect to  see the traces in Datadog 

**What did you see instead?**
but Java app service giving this error : 

[otel.javaagent 2022-01-20 13:08:39:949 +0530] [OkHttp https://XXXXXXXX.azurewebsites.net/...] WARN io.opentelemetry.exporter.otlp.internal.grpc.OkHttpGrpcExporter - Failed to export spans. Server responded with HTTP status code 404. Error message: 
[otel.javaagent 2022-01-20 13:08:39:949 +0530] [BatchSpanProcessor_WorkerThread-1] DEBUG io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker - Exporter failed
[otel.javaagent 2022-01-20 13:08:44:952 +0530] [OkHttp https://XXXXXXXX.azurewebsites.net/...] DEBUG okhttp3.internal.http2.Http2 - >> 0x00000005    56 HEADERS       END_HEADERS
[otel.javaagent 2022-01-20 13:08:44:953 +0530] [OkHttp https://XXXXXXXX.azurewebsites.net/...] DEBUG okhttp3.internal.http2.Http2 - >> 0x00000005  9613 DATA          END_STREAM
[otel.javaagent 2022-01-20 13:08:45:319 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000005     4 WINDOW_UPDATE 
[otel.javaagent 2022-01-20 13:08:45:319 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000000     4 WINDOW_UPDATE 
[otel.javaagent 2022-01-20 13:08:45:319 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000005     4 WINDOW_UPDATE 
[otel.javaagent 2022-01-20 13:08:45:320 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000000     4 WINDOW_UPDATE 
[otel.javaagent 2022-01-20 13:08:45:320 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000005     4 WINDOW_UPDATE 
[otel.javaagent 2022-01-20 13:08:45:320 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000000     4 WINDOW_UPDATE 
[otel.javaagent 2022-01-20 13:08:45:320 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000005     4 WINDOW_UPDATE 
[otel.javaagent 2022-01-20 13:08:45:320 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000000     4 WINDOW_UPDATE 
[otel.javaagent 2022-01-20 13:08:45:320 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000000     4 WINDOW_UPDATE 
[otel.javaagent 2022-01-20 13:08:45:321 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000005    28 HEADERS       END_HEADERS
[otel.javaagent 2022-01-20 13:08:45:321 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000005    19 DATA          
[otel.javaagent 2022-01-20 13:08:45:321 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - << 0x00000005     0 DATA          END_STREAM
[otel.javaagent 2022-01-20 13:08:45:321 +0530] [OkHttp https://XXXXXXXX.azurewebsites.net/...] WARN io.opentelemetry.exporter.otlp.internal.grpc.OkHttpGrpcExporter - Failed to export spans. Server responded with HTTP status code 404. Error message: 
[otel.javaagent 2022-01-20 13:08:45:321 +0530] [BatchSpanProcessor_WorkerThread-1] DEBUG io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker - Exporter failed
[otel.javaagent 2022-01-20 13:10:49:018 +0530] [OkHttp XXXXXXXX.azurewebsites.net] DEBUG okhttp3.internal.http2.Http2 - >> 0x00000000     8 GOAWAY        

**What version are you using?**
1. Java Agent :  opentelemetry-javaagent - version: 1.9.1
2. Collector Docker Image : 
https://hub.docker.com/layers/otel/opentelemetry-collector-contrib/latest/images/sha256-d34519458388e55a3fce38a33e6bc424267c1f432927c09e932ba45f7575bd84?context=explore

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by trask** [comment]
hi @sandeep-jain! can you give us some details why you think this is a javaagent issue?

**Comment by laurit** [comment]
Please reopen when you are ready to provide addition details
