### ISSUE TITLE
Clean up license file inconsistencies

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5203]
From @tnaroska's https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4924#issuecomment-1017081874

> While looking through the jar contents I found some other inconsistencies that you might want to fix:
> 1. in the jar under `META-INF/licenses` there is still license information for jackson core and databind _1.12.3_
> 2. `META-INF/licenses/licenses.md` also mentions core and databind _1.12.3_
> 3. the actual version included seems to be jackson core _1.12.1_ as seen in `inst/META-INF/maven/com.fasterxml.jackson.core/jackson-core/pom.properties`
>
> The license files seem to be copied from here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/licenses
> The versions referenced in there are completely unrelated to dependency management in gradle files.
>
> For keeping track of dependencies it would sure be good to clean these inconsistencies.

**Comment by mateuszrzeszutek** [comment]
How about creating a nightly build that'll run the `generateLicenseReport` task and post a PR if there are any differences compared to the main branch?

**Comment by trask** [comment]
Closed by #6399
