### ISSUE TITLE
Monitor Ear/war files that deploy on jboss

### ISSUE THREAD

**Issue by mehrdad2000** [open-telemetry/opentelemetry-java-instrumentation#5206]
Hi
I have ear/war file that deploy on jboss.
Is it possible to monitor these app with opentelemetry? How?

Any idea?
Thanks

**Comment by mateuszrzeszutek** [comment]
Hey @mehrdad2000 ,
Yes, it's certainly possible - you need to add the javaagent to JBoss `JAVA_OPTS`. E.g.
```sh
JAVA_OPTS="$JAVA_OPTS -javaagent:/path/to/opentelemetry-javaagent.jar"
```
The agent will instrument all applications deployed on your server.

**Comment by mehrdad2000** [comment]
I’ve done this, and now open a port tcp port on splunk server. But otel not send anything. Did i miss something?

**Comment by mateuszrzeszutek** [comment]
I have absolutely no idea what https://github.com/TeaTips/SplunkJavaAgent is; and it looks seriously outdated (and it's not a splunk project; it's not in the splunk GH org) - I doubt that it'll work at all.

If you're using the Splunk OTel distro (splunk-otel-java), please take a look at these docs: https://github.com/signalfx/splunk-otel-java/blob/main/docs/server-instructions.md#jboss-eap--wildfly (they'll work with a vanilla OTel javaagent too) -- they describer how to attach the javaagent to the JBoss application server.

**Comment by mehrdad2000** [comment]
Is it possible to use this agent on enterprise splunk instead of Splunk apm?

**Comment by mateuszrzeszutek** [comment]
Hey @mehrdad2000 ,
No, I don't think so. Please contact your Splunk sales representative, they should know how to set up Splunk enterprise in your environment.

**Comment by mehrdad2000** [comment]
Ok let me explain more, on splunk i listen to this port 9966, and create index that name “otel”
now is it possible to configure otel  ip/port/index to send data to my splunk server?
Thanks

**Comment by laurit** [comment]
Pease reopen if you have more questions
