### ISSUE TITLE
Can we load the java-agent in a different way?

### ISSUE THREAD

**Issue by tclass** [open-telemetry/opentelemetry-java-instrumentation#5247]
**Is your feature request related to a problem? Please describe.**
downloading a jar file and hooking it up into the classpath is not the natural way of running java applications for me. I understand that this path was chosen but I was interested if there would be more integrated solutions or ideas on how to get there now or in the future.

**Describe the solution you'd like**
I would like to just use gradle/maven to handle everything for me or a different automatic way. 

**Describe alternatives you've considered**
Looking for ideas here

**Additional context**
I would like to get an idea if other people have the same problem and if there might be ideas in the future to do it in a different way.

**Comment by mateuszrzeszutek** [comment]
Hey @tclass ,
Please take a look at the [`runtime-attach`](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/runtime-attach) project in the contrib repo. Unfortunately it completely lacks any sort of documentation; but its usage is not that complicated: you have to add the agent to the classpath and call [`RuntimeAttach#attachJavaagentToCurrentJVM()`](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/runtime-attach/src/main/java/io/opentelemetry/contrib/attach/RuntimeAttach.java#L14) as the first thing in your `main()` function.
CC @iNikem

**Comment by iNikem** [comment]
As we now have a confirmed customer successfully using runtime attach, we will properly document its usages and constraints.

**Comment by iNikem** [comment]
https://github.com/open-telemetry/opentelemetry-java-contrib/issues/217

**Comment by dzou** [comment]
Did you find this solution was viable for you? I also find downloading a JAR and hooking up into classpath weird. I get the "first thing in main method" -- does this method work with web frameworks like spring boot, micronaut, etc?

**Comment by trask** [comment]
hi @dzou! check out https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/runtime-attach
