### ISSUE TITLE
Add recommendation on a smaller test suite to run before submitting a PR

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#526]
It takes a long time to run all of the tests locally.

It would be nice to add a recommendation to CONTRIBUTING.md on a smaller test suite to run before submitting a PR, and note that it's not a worry if CI uncovers any additional failured, just to look out for that (and a note about sporadic failures too).

See https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/479#discussion_r436474191 and https://gitter.im/open-telemetry/opentelemetry-java-instrumentation?at=5ee7c165035dfa12612172d4

**Comment by iNikem** [comment]
I would really love to try #490 first. It may, in theory, reduce build times significantly for us.

**Comment by breedx-splk** [comment]
Now this it's December, what do we think of this one?  Since #490 sped up build times, do we still want to do this, or call it good?

**Comment by iNikem** [comment]
I am in favor of closing this. We still have an open problem that local test runs cannot use remote cache, but that should not keep this task open.

**Comment by trask** [comment]
Sounds good
