### ISSUE TITLE
Cross test javaagent instrumentation against other instrumentations targeted at the same library?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5261]
E.g. netty-3.8 instrumentation is tested with netty-4.0 and netty-4.1 instrumentations applied.

Should we apply this pattern to all instrumentations with multiple versions, or decide that the muzzle range checks are all we need and abandon this practice?

**Comment by iNikem** [comment]
I already expressed my opinion, that we should test with the whole agent, not partial agents prepared specifically for a given module :)

**Comment by mateuszrzeszutek** [comment]
> I already expressed my opinion, that we should test with the whole agent, not partial agents prepared specifically for a given module :)

That indeed sounds like a good idea; especially in light of our recent Armeria vs. Netty discussion 😄 
And if we ever need to test a particular instrumentation in isolation, we can create a test suite/set that disables unwanted instrumentations.

**Comment by trask** [comment]
> we should test with the whole agent, not partial agents prepared specifically for a given module

this sounds good to me, any thoughts how to implement?

**Comment by iNikem** [comment]
> > we should test with the whole agent, not partial agents prepared specifically for a given module
> 
> this sounds good to me, any thoughts how to implement?

`io.opentelemetry.instrumentation.javaagent-testing.gradle.kts` uses a minimal `agent-for-testing` and adds module-specific extension. It may depend on the full javaagent instead.

**Comment by iNikem** [comment]
@anuraaga was against this idea in the past because allegedly building the full agent will take too much time.

**Comment by trask** [comment]
sounds worth giving it a try and seeing what the perf impact is

**Comment by trask** [comment]
Closing, I think we are doing this now.
