### ISSUE TITLE
javaagent causes big heap on high load for Netty instrumentation 

### ISSUE THREAD

**Issue by ozoz03** [open-telemetry/opentelemetry-java-instrumentation#5265]
**Javaagent produces a critical heap increase for Netty instrumentation on our prod env (heap grows persistently over days and is not cleaned up by GC).** 
We was able to reproduce the issue by a [test app with artillery load](https://github.com/ozoz03/netty-otel-memory-leak). 

<img width="858" alt="Item-0_and_Item-1_and_Item-0_and_Item-0" src="https://user-images.githubusercontent.com/7068169/151535736-62840710-ca51-483c-ae79-68bd1c4e2e8d.png">

**Looks like cache that contains `FutureListenerWrappers` is not properly maintained by GC:**
<img width="1076" alt="Eclipse_Memory_Analyzer" src="https://user-images.githubusercontent.com/7068169/151538039-b916f213-ffa9-4da4-8e26-547addf47321.png">

**Steps to reproduce**
Here are steps to reproduce: https://github.com/ozoz03/netty-otel-memory-leak/blob/master/README.md

**What version are you using?**
`v1.10.0`

**Environment**
Compiler: openjdk version "11.0.11" 2021-04-20 LTS
OS: macOS 11.6.2, Alpine Linux 3.12.8

**Comment by iNikem** [comment]
How large heap do you use in your production?

**Comment by ozoz03** [comment]
@iNikem 6g

**Comment by ozoz03** [comment]
@iNikem 6g

**Comment by laurit** [comment]
@ozoz03 If possible could you verify whether the issue you observed is resolved in nightly build https://oss.sonatype.org/content/repositories/snapshots/io/opentelemetry/javaagent/opentelemetry-javaagent/1.11.0-SNAPSHOT/

**Comment by ozoz03** [comment]
@laurit thank you a lot.
going to test the build.
will be back in 2-3 days.

**Comment by ozoz03** [comment]
@laurit hey, sorry for the delay.
 
from what we could see in our graphs the memory leak was still in place with the new snapshot version.
but we believe we found the root cause for the issue and proposed the fix in [this PR](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5316)
