### ISSUE TITLE
Is it compatible with JDK8

### ISSUE THREAD

**Issue by gangxie112** [open-telemetry/opentelemetry-java-instrumentation#5278]
Do we have full test with JDK8 about the compatibility? If not, do we have any way to build it with JDK8? Most the product env use old jdk, it's not easy to upgrade all of them in a short time. We need consider the compatibility.

**Comment by anuraaga** [comment]
Hi @gangxie112 - we require newer JDKs to build artifacts but the built artifact supports Java 8+. All of our tests run with Java 8, 11, and newer to confirm compatibility.
