### ISSUE TITLE
Use standard exporter configuration from OpenTelemetry Java SDK

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#531]
And remove duplicate auto-instrumentation configuration, e.g.

change:

```
    final String jaegerEndpoint = config.getString(JAEGER_ENDPOINT, DEFAULT_JAEGER_ENDPOINT);
    final String serviceName = config.getString(JAEGER_SERVICE_NAME, DEFAULT_JAEGER_SERVICE_NAME);
    JaegerGrpcSpanExporter.newBuilder()
        .setServiceName(serviceName)
        .setChannel(ManagedChannelBuilder.forTarget(jaegerEndpoint).usePlaintext().build())
        .build();
```

to:

```
    JaegerGrpcSpanExporter.newBuilder()
        .readEnvironmentVariables()
        .readSystemProperties()
        .build()
```

Applies to all `SpanExporterFactory` and `MetricExporterFactory` implementations.

**Comment by malafeev** [comment]
please assign to me :)

**Comment by malafeev** [comment]
@iNikem @trask we also need this for Jaeger and Zipkin, but first of all it should be supported by opentelemetry-java.
Should we create separate issues?

**Comment by iNikem** [comment]
A, please forgive my haste :) Reopened.

Are there corresponding issues in otel-java?

**Comment by malafeev** [comment]
I didn't find issues in `otel-java` for Jaeger and Zipkin.
but because `otel-java` part is not done we cannot release it in 0.6.0.

**Comment by trask** [comment]
Hey @malafeev, `ZipkinSpanExporter.Builder` looks like it supports standard config in otel-java 0.6.0, so we can do:

```
    ZipkinSpanExporter.newBuilder()
        .readEnvironmentVariables()
        .readSystemProperties()
        .build();
```

And it looks like `JaegerGrpcSpanExporter.Builder` also supports standard config in otel-java 0.6.0. It's not using the same `read...()` API, but we can do:

```
    JaegerGrpcSpanExporter.Builder.fromEnv().build();
```

I will open issue in otel-java about using the same `read...()` API for `JaegerGrpcSpanExporter.Builder`, but we can go ahead and use the existing API for now.

**Comment by malafeev** [comment]
yeah, and all exporters use own property names .

**Comment by trask** [comment]
Ah, yes, that's ok, it looks like that's the direction things are going in https://github.com/open-telemetry/opentelemetry-specification/pull/666/files
