### ISSUE TITLE
Question: align 0.x monthly release versions with Java SDK project (at least until GA)?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#532]
Right now Java SDK releases 0.5 on the first monday of the month, and a week or two later we release Instrumentation 0.4 that is based on SDK 0.5.

While we are in this monthly beta release mode, I don't see a reason not to sync these version numbers (we release Instrumentation 0.5 that is based on SDK 0.5), and it could help with confusion, e.g. from gitter:

> we seem to be 2 version behind. Otel-java repo now publishes 0.6.0-SNAPSHOT and we still 0.4.0-SNAPSHOT

Thoughts?

**Comment by jkwatson** [comment]
I think will reduce some confusion, so 👍

**Comment by trask** [comment]
Should we release a `0.5.0` version soon to align earlier than the `0.6.0` version, and document that interop with manual instrumentation only works with the corresponding version OpenTelemetry API `0.5.0`?

See doc here: https://github.com/open-telemetry/opentelemetry-java-instrumentation#manually-instrumenting

See motivating issue here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/538#issuecomment-645525866

**Comment by iNikem** [comment]
We may, but I don't have strong preferences.

**Comment by iNikem** [comment]
@trask I think we have this question answered: our next release will be 0.6.0 and every release after that will align with otel-java version. As no actual work has to be done here any more, should we close this issue?
