### ISSUE TITLE
Muzzle bytecode runtime logs could be warnings, at least for tests

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#534]
I found that when writing new instrumentation, getting the unit test to be instrumented at all requires a few struggles with the muzzle

```
14:29:16.770 [Test worker] DEBUG io.opentelemetry.auto.tooling.Instrumenter$Default - Instrumentation muzzled: [lettuce, lettuce-5, lettuce-5.2] -- io.opentelemetry.auto.instrumentation.lettuce.v5_2.LettuceClientResourcesInstrumentation on jdk.internal.loader.ClassLoaders$AppClassLoader@55054057
14:29:16.770 [Test worker] DEBUG io.opentelemetry.auto.tooling.Instrumenter$Default - -- io.opentelemetry.auto.instrumentation.lettuce.v5_2.OpenTelemetryTracing$OpenTelemetrySpan:274 io.opentelemetry.auto.instrumentation.lettuce.v5_2.OpenTelemetryTracing$OpenTelemetryEndpoint#portI requires flag PACKAGE_OR_HIGHER found 20
14:29:16.770 [Test worker] DEBUG io.opentelemetry.auto.tooling.Instrumenter$Default - -- io.opentelemetry.auto.instrumentation.lettuce.v5_2.OpenTelemetryTracing$OpenTelemetrySpan:273 io.opentelemetry.auto.instrumentation.lettuce.v5_2.OpenTelemetryTracing$OpenTelemetryEndpoint#ipjava/lang/String requires flag PACKAGE_OR_HIGHER found 20
14:29:16.770 [Test worker] DEBUG io.opentelemetry.auto.tooling.Instrumenter$Default - -- io.opentelemetry.auto.instrumentation.lettuce.v5_2.OpenTelemetryTracing$OpenTelemetryEndpoint:98 io.opentelemetry.auto.instrumentation.lettuce.v5_2.OpenTelemetryTracing$OpenTelemetryEndpoint#namejava/lang/String requires flag PACKAGE_OR_HIGHER found 20
```

The visibility requirements of the business logic isn't so clear to me, but that's less of an issue than that I think these are always an indication of programming bugs in instrumentation but it's very hard to find them among a lot of debug output. So could probably log them higher. If not for normal code, at least having higher level logging of these when running tests in this repo would be nice.

**Comment by iNikem** [comment]
@anuraaga the title suggests that you want to _decrease_ log level from ERROR to WARNING. But actually you want to _increase_ it from DEBUG to WARNING, right?

**Comment by anuraaga** [comment]
Yup sorry didn't mean error in the logging sense but in the instrumentation code is broken sense :)

**Comment by trask** [comment]
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1121#discussion_r482686479
