### ISSUE TITLE
Context propagation in Spring Kafka seems not to be working

### ISSUE THREAD

**Issue by frankkoornstra** [open-telemetry/opentelemetry-java-instrumentation#5340]
**Describe the bug**

When using Agent v1.10.1, Spring Boot (with Spring Kafka) 2.6.3 and running a consumer/producer like the following snippet, the parent trace is not propagated:

```kotlin
@KafkaListener(id = "input-to-intermediary", topics = arrayOf("input"))
@SendTo("intermediary")
fun fastListen(message: Message<String>): Message<String> {
    Thread.sleep(Random.nextLong(10, 200))
    val newMessage = MessageBuilder.withPayload(message.payload).build()
    return newMessage
}
```

I'm sure I'm overlooking something or using Spring Kafka in an unexpected way but I'm stuck on this for 2 days now so let's see :grimacing: 

**Steps to reproduce**

I created a [replicator](https://github.com/frankkoornstra/java-instrumentation-replicator)

**What did you expect to see?**

When a request comes in through the web, routed through multiple Kafka topics and eventually put in the database, I expect to see them all in a single trace in Zipkin/Jaeger (both in the replicator) so I can follow a single request through multiple services (consumers/producers)

**What did you see instead?**

All the steps (web GET request, all consumer/producer pairs) are individual traces (with proper spans included in them, so that works). Also, you can see that each Kafka message does have a proper `traceparent` header, which also gets in through the consumer (when you set a breakpoint in the consumer) but it doesn't seem to be propagated to the produced message.

**What version are you using?**

Kotlin 1.6.10
Agent v1.10.0 (also tried it with 1.9.2)
Spring Boot (with Spring Kafka) 2.6.3

**Environment**

Compiler: AdoptOpenJDK 16
OS: Fedora 34 (5.14.13-200.fc34.x86_64)

**Comment by laurit** [comment]
@frankkoornstra firstly see this discussion https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/4509 Does adding `-Dotel.instrumentation.common.experimental.suppress-messaging-receive-spans=true` help?
