### ISSUE TITLE
Expose trace id in HTTP header with Spring Web

### ISSUE THREAD

**Issue by frankkoornstra** [open-telemetry/opentelemetry-java-instrumentation#5353]
**Is your feature request related to a problem? Please describe.**
Using Spring Web, the trace id is not visible to the client initializing the request. When debugging a performance issue in a high traffic environment, it is hard to find back that one specific slow request in all the traces.

**Describe the solution you'd like**
Add a flag in the agent to expose the trace id in a header in the returned HTTP response.

**Describe alternatives you've considered**
The only other way to find back the trace is basically looking at IP or User Agent but that still does not identify the specif request, just limits the pool.

**Comment by trask** [comment]
hi @frankkoornstra, can you have the client start the trace and send `traceparent` to the server?

**Comment by frankkoornstra** [comment]
I guess you could but that means spreading that knowledge, not being able to easily initiate a request with curl, all kinds of extra things you don't really want just to get to trace id.

**Comment by mateuszrzeszutek** [comment]
Resolved in #7990 - it requires a custom `HttpServerResponseCustomizer` implementation via an extension though.
