### ISSUE TITLE
Capture `net.host.name` and `net.host.port` for SERVER spans?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5375]
I think we should probably at least capture `net.host.name` and `net.host.port` when there's no `http.host` (i.e. HTTP 1.0) in order to satisfy:

> **Additional attribute requirements:** At least one of the following sets of attributes is required:
>
> * `http.scheme`, `http.host`, `http.target`
> * `http.scheme`, `http.server_name`, [`net.host.port`](span-general.md), `http.target`
> * `http.scheme`, [`net.host.name`](span-general.md), [`net.host.port`](span-general.md), `http.target`
> * `http.url`

I'm guessing we would add these to `NetServerAttributesGetter`(?)

And then the question is, should we:

* somehow make capturing `net.host.name` and `net.host.port` conditional on absence of `http.host`, or
* always capture `net.host.name` and `net.host.port`

**Comment by mateuszrzeszutek** [comment]
I think it's been implemented already in one of my HTTP semconv PRs.
