### ISSUE TITLE
Consider changing the default for suppress-messaging-receive-spans to true

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5385]
Capturing receive spans and having consumer spans parent the receive span instead of parenting the producer span has been confusing for users since most(?) backends do not support links well yet and so it appears that distributed tracing is broken.

User reported issues that were resolved by setting this flag: #4509 #4582 #4783 #4854 #5340

cc @pyohannes

**Comment by anuraaga** [comment]
A couple more
https://github.com/aws-observability/aws-otel-java-instrumentation/issues/153
https://github.com/aws-observability/aws-otel-java-instrumentation/issues/155
and 2+ internal tickets
