### ISSUE TITLE
“WARN muzzleMatcher -  Missing method char#clone()Ljava/lang/Object;”

### ISSUE THREAD

**Issue by udaysrinivasan** [open-telemetry/opentelemetry-java-instrumentation#5397]
**Describe the bug**

I added a call to java.lang.Object.clone method in an Advice method it fails muzzle check and instrumentation doesn't get installed. 

**Steps to reproduce**

I have the following lines 

      char[] HC = "0123456789ABCDEF".toCharArray();
      char[] HC2 = HC.clone();

in  @Advice.OnMethodEnter(suppress = Throwable.class) method ( I tried adding in jdbc instrumentation)

I am getting the following error 

[otel.javaagent 2022-02-17 20:16:09:250 -0800] [main] WARN muzzleMatcher - Instrumentation skipped, mismatched references were found: jdbc [class io.opentelemetry.javaagent.instrumentation.acante.jdbc.AcanteJdbcInstrumentationModule] on jdk.internal.loader.ClassLoaders$AppClassLoader@251a69d7

[otel.javaagent 2022-02-17 20:16:09:251 -0800] [main] WARN muzzleMatcher - -- io.opentelemetry.javaagent.instrumentation.acante.jdbc.RowInsrumentation$RowAdvice:72 Missing method char#clone()Ljava/lang/Object;

As a result the instrumentation install fails. 

**What version are you using?**
opentelemetry-javaagent-1.12.0-SNAPSHOT.jar 

**Environment**
Compiler: openjdk 17 - (I have tried 13 as well)
OS: macos

**Comment by udaysrinivasan** [comment]
Thanks for fixing this. It works now for agents in opentelemetry-java-instrumentation/instrumentation. However I hit the muzzle failure when it is loaded as an extension agent using -Dotel.javaagent.extensions option. Without those two lines agent works fine.

**Comment by trask** [comment]
copying @laurit's response on slack:

> [https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/46418d59[…]11277af42bce7779932e754ed5388d5/examples/extension/build.gradle](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/46418d59111277af42bce7779932e754ed5388d5/examples/extension/build.gradle#L16) Make sure that these 2 muzzle plugins used in your build are set to a version that contains the fix
