### ISSUE TITLE
Kafka Requests using the same traceID for multiple requests

### ISSUE THREAD

**Issue by muneeb-dar** [open-telemetry/opentelemetry-java-instrumentation#5400]
**Describe the bug**
When producing a new kafka request request to a topic for another microservice to consume the traceID generated is same for all requests are same. All consumers are then shown under a single trace such that duration of a request amounts to 800 secs(of course that is not correct as we the actual time is in ms for each request). 
On my local setup using Jaeger it is working fine but in kubernetes deployment using grafana tempo the issue is coming.

**Steps to reproduce**
Use Java-instrumentation in any service using kafka. Send multiple requests one after another and all requests have same traceID.

**What did you expect to see?**
For each request from producer and its subsequent consumption we have a unique traceID.

**What did you see instead?**
All requests have the same traceID

**What version are you using?**
1.11.0

**Environment**
Compiler: openjdk:8-jdk
OS: K8s

**Additional context**

**Comment by muneeb-dar** [comment]
On my local setup using Jaeger it is working fine but in kubernetes deployment using grafana tempo the issue is coming.

**Comment by muneeb-dar** [comment]
I changed the otel propagators and for different configurations (tracecontext,b3,b3multi,baggage) I am getting the visible change in how traceids are propagated but none of them work as expected. What should be the configuration of otel propagators?

**Comment by trask** [comment]
hi @muneeb-dar1 this may be solved by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5826, it sounds similar to the issues linked in that PR

**Comment by trask** [comment]
Closing, but let us know if the issue persists after updating to 1.13.1 and will re-open, thx!
