### ISSUE TITLE
Setting Service Name from Spring Boot application properties

### ISSUE THREAD

**Issue by mkrzywanski** [open-telemetry/opentelemetry-java-instrumentation#5414]
**Is your feature request related to a problem? Please describe.**
I would like to set service name from Spring Boot properties so that when the spans are sent to Jaeger the service name matches the actual spring boot service name and is not `unknown`. As far as I can see Spring Boot autoconfiguration in `spring-boot-autoconfigure` module does not give any opportunity to set `ResourceAttributes.SERVICE_NAME`. If it is possbile to set it somehow with current implementation I would be glad to know the way. If not I would be happy to maybe contribute it.

**Comment by aschugunov** [comment]
hey @mkrzywanski it looks similar to [3480](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3480)
I made PR too with a bit of the same idea

**Comment by mateuszrzeszutek** [comment]
Implemented in #5359
