### ISSUE TITLE
How to implement the service interface topology?

### ISSUE THREAD

**Issue by qiansheng91** [open-telemetry/opentelemetry-java-instrumentation#5416]
Hi  guys:

I want to implement the service interface topology by using OT,  For example:

1) **Span[/a]**(kind: server)  ---->  **Span[b]**(kind: internal)
2) **Span[b]**(kind: internal)  ---->  **Span[c]**(kind: client)
3) **Span[c]**(kind: client)  ---->  **Span[/d]**(kind: server)

The Topology should look like this:

```
/a  ---->  /d
```

And I think that the fastest way I've found to do this is to pass the upstream service name to the downstream.  Is there any suggestion for me to implement this?

**Comment by qiansheng91** [comment]
Anyone updates?

**Comment by trask** [comment]
hi @qiansheng91! sorry, I don't understand your question, can you elaborate a bit more?
