### ISSUE TITLE
Installing a metric exporter from an external jar fails when using the auto-instrumentation auto-all jar for the agent.

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#542]
I get this message when trying to install:
```
WARN io.opentelemetry.auto.tooling.TracerInstaller - Exporter JAR defines more than one
```
and it proceeds to load the OTLP exporter.

Note 1: this works fine for a SpanExporter. 
Note 2: it works if I don't use the opentelemetry-auto-all.jar, but instead just use the opentelemetry-auto.jar version.

**Comment by trask** [comment]
I suspect we need to add a similar condition for `MetricExporterFactory` here:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v0.4.0/agent-tooling/src/main/java/io/opentelemetry/auto/tooling/ExporterClassLoader.java#L68-L73

**Comment by iNikem** [comment]
@jkwatson Do I understand you correctly, that you used `-all.jar` and then tried to load metric export from the external jar?

**Comment by jkwatson** [comment]
> @jkwatson Do I understand you correctly, that you used `-all.jar` and then tried to load metric export from the external jar?

Yes, sorry. I realize reading this that that wasn't 100% clear.

**Comment by iNikem** [comment]
@jkwatson what jar have you provided to the agent? I am currently unable to reproduce your problem:

```
java -Dota.exporter.jar=/Users/nsalnikovtarnovski/Downloads/opentelemetry-exporters-prometheus-0.5.0-20200602.184318-82.jar -javaagent:java-agent/build/libs/opentelemetry-auto-0.5.0-SNAPSHOT-all.jar -version 
[opentelemetry.auto.trace 2020-06-23 18:20:25:932 +0300] [main] WARN io.opentelemetry.auto.tooling.TracerInstaller - No span exporter found in /Users/nsalnikovtarnovski/Downloads/opentelemetry-exporters-prometheus-0.5.0-20200602.184318-82.jar
[opentelemetry.auto.trace 2020-06-23 18:20:25:932 +0300] [main] WARN io.opentelemetry.auto.tooling.TracerInstaller - No valid exporter found. Tracing will run but spans are dropped
[opentelemetry.auto.trace 2020-06-23 18:20:26:119 +0300] [main] INFO io.opentelemetry.auto.tooling.TracerInstaller - Installed metric exporter: io.opentelemetry.exporters.otlp.OtlpGrpcMetricExporter
[opentelemetry.auto.trace 2020-06-23 18:20:26:121 +0300] [main] INFO io.opentelemetry.auto.tooling.VersionLogger - opentelemetry-auto - version: 0.5.0-SNAPSHOT~9dcb079aa
```

As my external jar has only metric exporter, I find the above behaviour expected until #496 is fixed.

**Comment by jkwatson** [comment]
Try this one here:  https://repo1.maven.org/maven2/com/newrelic/telemetry/opentelemetry-exporters-newrelic-auto/0.5.1/opentelemetry-exporters-newrelic-auto-0.5.1.jar
