### ISSUE TITLE
Need to Authenticate Java application with Opentelemetry with a proxy in between

### ISSUE THREAD

**Issue by umarkhan17** [open-telemetry/opentelemetry-java-instrumentation#5431]
I am trying authenticate every request that is sent to opentelemetry standalone collector from agent collector. I have a kong proxy(similar to nginx) installed and a keycloak authentication server. I need to pass custom headers along with token to proxy. Please suggest on how will i achieve that.

**Comment by trask** [comment]
hi @umarkhan17, does `OTEL_EXPORTER_OTLP_HEADERS` address your need?

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-span-metric-and-log-exporters

**Comment by umarkhan17** [comment]
I have found a way to authenticate, now i am trying to add "otel.javaagent.configuration-file" environment variable and adding a yaml configuration file.

My dockerfile looks like : 
ENV JAVA_OPTS "${JAVA_OPTS} \
   -Dapplication.name=${APP_NAME} \
   -Dapplication.home=${APP_HOME} \
   -Dotel.javaagent.configuration-file=/app/bin/agent-config.yaml
   -javaagent:${APP_HOME}/opentelemetry-javaagent-all.jar"

My configuration file : agent-config.yaml looks like this :
extensions:
  oauth2client:
    client_id: agent
    client_secret: <secret>
    token_url: http://some-url2.com/auth/realms/opentelemetry/protocol/openid-connect/token

exporters:
  zipkin:
    endpoint: http://some-url.com/zipkin/api/v2/spans
#    tls:
#      ca_file: /app/bin/ca.crt
    auth:
      authenticator: oauth2client

service:
  name: some-service
  extensions: [oauth2client]
  pipelines:
    traces/agent:
      receivers: []
      processors: []
      exporters: [zipkin]

I have already figured out a way to enable Authentication on my collector end, i need to enable authentication at Java agent side. But somehow My application is not loading configurations from the file. What am i doing wrong?

**Comment by umarkhan17** [comment]
Thanks @mateuszrzeszutek,

But how do i specify OAuth2Client (or these Authentication) configuration for javaagent?

**Comment by mateuszrzeszutek** [comment]
The `OTEL_EXPORTER_OTLP_HEADERS` environment variable (or the `otel.exporter.otlp.headers` system property) can be used to add custom HTTP headers to the requests sent by the OTLP exporter -- I suppose you could pass the oauth token there directly.
The agent does not currently support obtaining an oauth token, but I suppose you could implement [an extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/README.md) that adds your own exporter (using an [SPI](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/traces/ConfigurableSpanExporterProvider.java)) that gets the token and then delegates to the OTLP exporter.

**Comment by trask** [comment]
> What will happen if i run agent as a sidecar in Kubernetes VS when i run it as a javaagent?

hi @umarkhan17, the javaagent can only be run in-process, inside of the JVM that it is monitoring

**Comment by umarkhan17** [comment]
I meant when i run "Agent Collector as sidecar" vs java agent inside JVM

**Comment by umarkhan17** [comment]
Can you provide me with reference where i can implement Extension that will enable authentication for Javaagent. As of now i cannot find a reference and it is been asked in multiple issues and specification. if you could provide on tutorial or reference it would be of great help.

**Comment by mateuszrzeszutek** [comment]
The [extension example](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/) I posted earlier contains a project that you can just copy and remove all unnecessary bits. The [`DemoSdkTracerProviderConfigurer`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/src/main/java/com/example/javaagent/DemoSdkTracerProviderConfigurer.java#L34) class from that example projects sets up a custom `SpanExporter`, I think you could start from that.
I don't have any experience with any Java OAuth library, so I can't really help you with that - but I believe you should able to find an example somewhere and paste it into the extension code.

**Comment by trask** [comment]
Closing, let us know if you are still having issues and we will re-open.
