### ISSUE TITLE
(re-)Consider using PR title convention to generate release notes

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5438]
Currently it's a manual process to weed through which PRs should be included in the release notes and which ones should not.

It's not terribly time-consuming (though automating would be nice from that perspective too), but primarily my concern here is that the manual process can easily lead to missed entries like #5437.

**Comment by anuraaga** [comment]
I'm generally slightly negative on PR title conventions as they can be hard for contributors to grok. If they're highly valuable then it could be OK, but my main concern would be it could still not provide enough of a hint for us to add notes like in #5446

**Comment by mateuszrzeszutek** [comment]
Maintainers could edit the PR title before merging it -- it would put some more work on us, but on the other hand, somebody has to do this work anyway when compiling the release notes.

**Comment by trask** [comment]
Closing, release process seems ok for now, can revisit in future if anyone wants
