### ISSUE TITLE
Send Data To Two Zipkin Exporter 

### ISSUE THREAD

**Issue by Rutik333** [open-telemetry/opentelemetry-java-instrumentation#5463]
Need feature to send Opentelemetry  generated Traces Data to two zipkin endpoints
**java -javaagent:opentelemetry-javaagent-all.jar -Dotel.resource.attributes=service.name=pet1 -Dotel.traces.exporter=zipkin -Dotel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans -  -jar spring-petclinic-2.5.0-SNAPSHOT.jar**
I use this command to run my application now i want to send traces to another endpoint also can we do that?

Dotel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans -------------actual
Dotel.exporter.zipkin.endpoint=http://localhost:9411/api/v2/spans,http://localhost:9412/api/v2/spans ------------Expected

**Comment by laurit** [comment]
Send your traces to [opentelemetry collector](https://github.com/open-telemetry/opentelemetry-collector) and configure it to send to multiple endpoints.

**Comment by laurit** [comment]
Feel free to reopen if you have further questions.
