### ISSUE TITLE
Agent instrumentation naming table contains outdated entries

### ISSUE THREAD

**Issue by Stephan202** [open-telemetry/opentelemetry-java-instrumentation#5465]
After noticing that `-Dotel.instrumentation.logback.enabled=false` no longer caused trace IDs to be omitted from our logs, I found that the associated integration was [renamed](https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/ea359e61fb07538fe85f533cee519aaef6c10061#diff-7ce4d79ae425533b15c63fbfef20189034f26a93cdf36d98f38d89afbc83665eL16-R18) from `logback` to `logback-mdc`. It appears that the [documentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e058fa78103344b94795328d1d1cb41ee5dc67c3/docs/suppressing-instrumentation.md) should be updated accordingly. Based on the following (very...) hacky script it appears that a few other entries in that table may also be outdated:

```sh
#!/usr/bin/env bash

set -e -u -o pipefail

comm -3 \
  <(  
    sed -n '/----------------------/,${p;/^$/q}' \
        docs/suppressing-instrumentation.md \
      | sed '1d;$d' \
      | cut -d '|' -f 3 \
      | tr -d ' ' \
      | sort -u
  ) \
  <(  
    git ls-files '*Module.java' \
      | xargs grep super \
      | grep -oP '(?<=super\(")[^"]+' \
      | sort -u
  )
```

Executed against revision e058fa78103344b94795328d1d1cb41ee5dc67c3, this script outputs:
```
	context-test-instrumentation
eclipse-osgi
	internal-class-loader
	internal-eclipse-osgi
	internal-lambda
	internal-reflection
	internal-url-class-loader
	java-util-logging
jersey
kafka
	kafka-clients
	kafka-streams
log4j
	log4j-appender
	log4j-context-data
	log4j-mdc
logback
	logback-appender
	logback-mdc
	micrometer
	mongo-async
	opentelemetry-api-1.10
	opentelemetry-api-1.4
	redisson
	restlet
	rxjava2
rxjava2,rxjava3
	rxjava3
	rxjava3.1.1
	servlet-demo
spring-batch
	spring-rmi
	test-instrumentation
vertx
	vertx-client
	vertx-rx-java
	vertx-web
```

**Comment by trask** [comment]
thanks @Stephan202! I've sent #5472 to update
