### ISSUE TITLE
Remove as many maxJavaVersionForTest = 8 as possible

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#547]
As far as I know, the build requires Java 9+ for use of the `--release` flag which is great. But it means that any test with `maxJavaVersionForTest = 8` does not run locally and increases back-and-forth with CI. I can't imagine much use case for limiting the test to Java 8 since I guess our instrumentation is supposed to work on all versions of Java 8+ anyways, so we should probably find and remove these, unless there actually is a specific reason to for a particular project.

One example is this
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/spring-webflux-5.0/spring-webflux-5.0.gradle#L4

I am going to remove it in #540 because the presence of that flag made it impossible to verify the change locally.

**Comment by iNikem** [comment]
You do know that you can run tests locally on any java version, right ? :) `./gradlew testJava8`, as described in CONTRIBUTING.md

**Comment by anuraaga** [comment]
Nope I skimmed ;) I guess that means it's not impossible but it is tedious, I don't there is a one click way to run a test using those tests in IntelliJ, the options I get are `test` and `testLatestDep`. So still recommend removing this flag to make things simpler.

**Comment by trask** [comment]
Linking #552, which is for removing `maxJavaVersionForTest = 8` from Cassandra instrumentation

**Comment by trask** [comment]
Closing.

Play doesn't support Java 11 until 2.6.12

Glassfish (used in `glassfish-testing`) doesn't support Java 11

The rest are now tracked separately in #552, #1005, #1006 and #1007.
