### ISSUE TITLE
Exception transforming javaagent class

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#5499]
While debugging a customer issue, I found this debug logging. Is this expected / harmless?

```
[otel.javaagent 2022-03-03 20:08:36:330 +0000] [AD Thread Pool-Global1] DEBUG io.opentelemetry.javaagent.tooling.AgentInstaller$TransformLoggingListener - Failed to handle io.opentelemetry.javaagent.instrumentation.servlet.AsyncRunnableWrapper for transformation on classloader java.net.URLClassLoader@2f4e40d7
net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for io.opentelemetry.javaagent.instrumentation.servlet.ServletHelper
```

**Comment by mateuszrzeszutek** [comment]
Hmm, why would `AsyncRunnableWrapper` even get transformed? It's an injected helper class, I thought we were explicitly skipping these.

**Comment by anuraaga** [comment]
@mateuszrzeszutek Exactly why this line stood out more than other type description errors :)

**Comment by laurit** [comment]
@anuraaga could you add stack trace. Maybe seeing where this class is defined from helps to understand why this happens.  As far as I know we don't explicitly exclude injected classes from transformation but rely on classes defined while transforming a class not triggering a nested transform.
