### ISSUE TITLE
Run Cassandra instrumentation tests on all Java versions (not only Java 8)

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#552]
Currently, during the Cassandra instrumentation tests, Cassandra itself is run embedded in the JVM via Cassandra Unit, which limits us to using Java 8 for those instrumentation tests.

Instead, it would be nice to run Cassandra in a container, which would then allow us to test Cassandra instrumentation against all Java versions.

Being able to run external containers would probably be useful for other instrumentation tests as well (e.g. Mongo, Elasticsearch, Couchbase, Redis), instead of the ad-hoc wrappers that are used for each one today.

**Comment by iNikem** [comment]
Unless there is a very good reason for doing otherwise, I prefer using Testcontainers instead of externally runs containers.

**Comment by trask** [comment]
Testcontainers requires Java 8+ ☹️.

What do you think about abandoning Java 7 for instrumentation tests, and only validating Java 7 compatibility via (more limited) smoke tests (#298)?

**Comment by devinsba** [comment]
If someone gets this working I'd be so happy to upstream this change into the DD code base. I gave it a short try one afternoon but haven't had the time otherwise

**Comment by iNikem** [comment]
> Testcontainers requires Java 8+ ☹️.
> 
> What do you think about abandoning Java 7 for instrumentation tests, and only validating Java 7 compatibility via (more limited) smoke tests (#298)?

Otel-java has done that. It is very tempting, especially for a person thinking that we should drop java 7 compatibility completely :)

**Comment by trask** [comment]
I added the topic to this week's [meeting agenda](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw)

**Comment by mateuszrzeszutek** [comment]
Done in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1427
