### ISSUE TITLE
How to exclude opentelemetry.proto.collector.metrics.v1.MetricsService/Export Span

### ISSUE THREAD

**Issue by qiansheng91** [open-telemetry/opentelemetry-java-instrumentation#5538]
Hi All:

My Application uses the OTel Metric export metric to the Prometheus. I found lots of `opentelemetry.proto.collector.metrics.v1.MetricsService/Export` Span in trace list when using Opentelemetry java Instrumentation.  

I read the code and found that the GRPC instrumentation uses the GRPC interceptor to intercept all grpc services(including OpenTelemetry Metric GRPC export services). Is there any suggestion to exclude the span?

Regards

Xin

**Comment by trask** [comment]
hi @qiansheng91! have you maybe configured both the SDK and the javaagent? can you tell us more about your setup, or provide a repro that we can look at?

**Comment by qiansheng91** [comment]
@trask  Thanks for your response, And Here is [demo](https://github.com/qiansheng91/metric-demo) repo.  and here is the [metric example code](https://github.com/qiansheng91/metric-demo/blob/main/src/main/java/com/alibaba/sls/demo/ot/controller/OTELMetricsClient.java#L52)

**Comment by qiansheng91** [comment]
Get!, Thanks very much!!
