### ISSUE TITLE
KafkaTracing - call makeCurrent() on a new Context created in buildAndFinishSpan()

### ISSUE THREAD

**Issue by hansut** [open-telemetry/opentelemetry-java-instrumentation#5539]
**Is your feature request related to a problem? Please describe.**
Context created in method KafkaTracing:buildAndFinishSpan() could be made "current". With current solution, if there is a custom aspect used in application that creates span for all method calls (to be able to trace method execution in Jaeger), that aspect is not able to create child spans for the span created in KafkaTracing:buildAndFinishSpan() method.

**Describe the solution you'd like**
There is a "Context current" created on line 135 of KafkaTracing class. On the next line, a method makeCurrent() could be called on it. TracingServerInterceptor for gRPC does the same thing.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by trask** [comment]
hi @hansut, we wouldn't want to make the context "current" if we weren't sure we were going to close it (since it's bound to a thread local, so can then leak to other places), that's why the typical usage is

try (Scope ignored = context.makeCurrent()) {
   ... do stuff
}

**Comment by hansut** [comment]
hi @trask, thank you. And would it be possible to update the implementation to do it like you wrote?

**Comment by hansut** [comment]
Sorry, now I see it is not possible to implement with Kafka interceptors.

**Comment by doppleware** [comment]
Hi @trask I noticed that another instrumentation library: `io.opentelemetry.spring-kafka` does set the current context so that if you instrument method calls under the consumer they correctly get attached to them same trace. Is there a way to follow a similar strategy here?
