### ISSUE TITLE
Need to have a standard extension for javaagent that will send client credentials to Auth server and get the Bearer token and then send the bearer token to every request to an external standalone collector or any backends(Jaeger/Prometheus).

### ISSUE THREAD

**Issue by umarkhan17** [open-telemetry/opentelemetry-java-instrumentation#5544]
I need to implement Authentication of Java application that is sending traces of application to collector. i want every request to be Authenticated via Bearer token. I need to pass those token in "otel.exporter.otlp.headers". I need to implement an Extension for that. Requesting for a tutorial or a standard Readymade extension in Extensions demo project.

**Comment by mateuszrzeszutek** [comment]
I don't think we'll ever have an "OpenTelemetry standard javaagent extension" doing that - extensions are, by definition, a mechanism of adding custom logic to the pre-built javaagent. If you need a standardized mechanism, the spec issue https://github.com/open-telemetry/opentelemetry-specification/issues/1344 needs to be resolved first - and then implemented in the Java SDK.
