### ISSUE TITLE
Are there any plans to release a standalone instrumentation library for ktor?

### ISSUE THREAD

**Issue by winor30** [open-telemetry/opentelemetry-java-instrumentation#5565]
In our project, we use ktor primarily for server-side applications.
If possible, do you have any plans to release a standalone library for ktor?

https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/ktor-1.0/library

**Comment by trask** [comment]
hi @winor30! this is released at https://search.maven.org/search?q=g:io.opentelemetry.instrumentation%20a:opentelemetry-ktor-1.0, is that what you are looking for, or something else?

**Comment by winor30** [comment]
@trask 
yes! This is what I was looking for.
thank you so much!
