### ISSUE TITLE
khttp client instrumentation missing user agent

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#557]
I couldn't find how to extract user agent for a khttp client request. Assume it's available somewhere but not just by examining the request, will require some investigation and possible circumventing our normal request decorators.

Reference https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/540#pullrequestreview-434999059

**Comment by trask** [comment]
Given that this is a lesser popular library, and this is not the most critical feature, I propose we just document this limitation in `khttp-0.1/README.md` and then close this.

**Comment by iNikem** [comment]
It would be nice to have some way to communicate "we closed this issue because we don't have bandwidth to address it, but we will gladly accept PRs for it" :)

**Comment by anuraaga** [comment]
I agree (I think? :) ) with @iNikem that we probably shouldn't close issues in such case or they won't be visible for potential new contributors. Can we just add a backlog label along with help wanted?

**Comment by iNikem** [comment]
Maybe this IS "help wanted"?
