### ISSUE TITLE
Kafka autoinstrumentation trace propagator doesn't work and creates new Trace ID

### ISSUE THREAD

**Issue by rashid4lyf** [open-telemetry/opentelemetry-java-instrumentation#5576]
Hi, we seem to have an issue with Kafka auto instrumentation on versions after 1.5.2. We have tried the flag: `-Dotel.instrumentation.common.experimental.suppress-messaging-receive-spans=true` in versions 1.6.0 < 1.12.0 with no luck. 

The scenario is as follows: 

`Application A` that accepts an HTTP Post and sends this data onto a Kafka Topic ( `Topic A` ) . `Application B` reads from `Topic A` and produces onto `Topic B`. The trace context is lost and a new trace is created. These spans fail to show up properly in the New Relic provider. 

I turned on logging exporter to see if the TraceID remains the same between the two applications and found that in `Application B` the first TraceID matches the previous application but all subsequent messages have a new TraceID and do not match the previous. This pretty much rules out a possible issue with the New Relic provider.

Logs have been attached from the collector which shows the difference in TraceIDs in version 1.12.0 compared to 1.5.2.

** Version **
Version broken: 1.6.0 onwards
Working version: Up to 1.5.2

** Environment **
AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.8+10
OS: Linux 5.4.176-91.338.amzn2.x86_64
Runtime: AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.8+10

Spring Kafka is used
Spring Boot Version: 2.5.6

[wh-kafka-standard-consumer-producer-8f96c95-khhfs_opentelemetry_1_5_2.log](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/8246744/wh-kafka-standard-consumer-producer-8f96c95-khhfs_opentelemetry_1_5_2.log)
[wh-kafka-standard-producer-6798f849f4-888nr_opentelemetry_1_5_2.log](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/8246745/wh-kafka-standard-producer-6798f849f4-888nr_opentelemetry_1_5_2.log)
[wh-kafka-standard-producer-6798f849f4-2l2lt_open_telemetry_1_12_0.log](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/8246746/wh-kafka-standard-producer-6798f849f4-2l2lt_open_telemetry_1_12_0.log)
[wh-kafka-standard-consumer-producer-8f96c95-pfqds_opentelemetry_1_12_0.log](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/8246747/wh-kafka-standard-consumer-producer-8f96c95-pfqds_opentelemetry_1_12_0.log)

**Comment by trask** [comment]
hi @rashid4lyf! this is a tricky issue to guess about, is there any chance you can provide a minimal repro that we can use to investigate the issue?

**Comment by andrewglass3** [comment]
We have also noticed this occurring - good post @rashid4lyf

**Comment by rashid4lyf** [comment]
> hi @rashid4lyf! this is a tricky issue to guess about, is there any chance you can provide a minimal repro that we can use to investigate the issue?

@trask Sure, this will be uploaded in the next 1-2 days and will link back to this issue. It is worth noting that we observe this issue when using the Kafka batch processor

**Comment by laurit** [comment]
Feel free to reopen when you are ready to provide a sample application that reproduces the issue.
