### ISSUE TITLE
Propagate trace headers on Apache HttpAsyncClient redirects

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#559]
Currently this only works when using W3C context propagator.

See TODO marker in ApacheHttpClientRedirectInstrumentation.

**Comment by piotr-sumo** [comment]
@trask is this issue still valid? I've checked `io.opentelemetry.javaagent.instrumentation.apachehttpasyncclient.ApacheHttpAsyncClientInstrumentation` and there are no TODO markers.
I'd like to contribute and fix this.

**Comment by trask** [comment]
thx @piotr-sumo, looks like this was resolved indirectly by #1894
