### ISSUE TITLE
Consolidate src/main/java8 and src/main/java9 into src/main/java

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#560]
After #390, I think we can now consolidate src/main/java8 and src/main/java9 into single src/main/java.

For background: these source folders used to be separate and compiled with different target Java versions, so that instrumentation classes themselves would always be Java 7 compatible.

But now we wrap loading of the instrumentation classes themselves with try / catch `UnsupportedClassVersionError`, and the classes in for a given instrumentation are compiled with a single target Java version.

**Comment by iNikem** [comment]
Closed by #617
