### ISSUE TITLE
Release 1.12.1 Artifact contains version  ex:opentelemetry-javaagent-1.12.1.jar  instead of opentelemetry-javaagent.jar

### ISSUE THREAD

**Issue by raphaelcolomine-onespan** [open-telemetry/opentelemetry-java-instrumentation#5616]
**Describe the bug**
latest download url don't work anymore 
https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar => https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.12.1/opentelemetry-javaagent.jar 
return 404.

**Steps to reproduce**
wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar 
or click on download link on the readme.

**What did you expect to see?**
jar file content

**What did you see instead?**
404 response 

**What version are you using?**
latest / 1.12.1 

**Environment**
N/A

**Additional context**

**Comment by trask** [comment]
thx for reporting this! I've fixed this now

**Comment by raphaelcolomine-onespan** [comment]
Thanks, all good now.
