### ISSUE TITLE
Add support for apache shenyu

### ISSUE THREAD

**Issue by HessTina-YuI** [open-telemetry/opentelemetry-java-instrumentation#5629]
Would it be possible to add support for [Apache ShenYu](https://github.com/apache/incubator-shenyu).

**Comment by JooKS-me** [comment]
If the folks in the otel community find it suitable, we are very glad to contribute this feature :)

**Comment by trask** [comment]
sure! check out [Writing instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/writing-instrumentation.md) and [Write an InstrumentationModule step by step](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/writing-instrumentation-module.md) if you haven't seen them already

**Comment by trask** [comment]
Closing, this seems to be resolved by #11260.
