### ISSUE TITLE
OTLP Exporter customization

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java-instrumentation#564]
Next required configuration options are missing:
- setDeadlineMs
- useTransportSecurity instead of usePlaintext
- insert values into `Metadata headers` (in `ClientInterceptor`)

**Comment by malafeev** [comment]
please assign issue to me

**Comment by trask** [comment]
Hi @malafeev! Can you look at adding this configuration directly to the OTLP exporter? E.g. it already supports `OTEL_OTLP_SPAN_TIMEOUT` which maps to `deadlineMs`.

And check out #531, where we still need to transition this project over to the new(-ish) standard exporter configuration.

**Comment by malafeev** [comment]
waiting for release of opentelemetry-java with merged https://github.com/open-telemetry/opentelemetry-java/pull/1373
although it can be fixed as part of #531

**Comment by trask** [comment]
this should be unblocked now that #662 is merged 👍
