### ISSUE TITLE
Guava context propagation inconsistent

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#5669]
I found a long standing issue in our Guava instrumentation while migrating the tests to Java. It would be good to fix it at some point, filing this issue to make sure it's not lost.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5668/files#diff-55479c0a94ebcbe26f05f65bc14b219f91ca28524179359df6ff702bbeacc40cR186

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.

and it's still tracked via TODO:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f30601d3e4dab399b43f2974c89639ab1598bf6a/instrumentation/guava-10.0/javaagent/src/test/java/io/opentelemetry/javaagent/instrumentation/guava/v10_0/ListenableFutureTest.java#L186-L187
