### ISSUE TITLE
Release 1.12.1 disappeared?

### ISSUE THREAD

**Issue by edwardxia** [open-telemetry/opentelemetry-java-instrumentation#5675]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.12.1

Tag was created 6 days ago, and I remember seeing a GitHub release for it. Now 1.12.1 is no longer showing in GitHub release, and nor the CHANGELOG mentions it.

What is happening with 1.12.1? Should I revert back to 1.12.0?

**Comment by trask** [comment]
@edwardxia thanks for reporting this!

will look into how it went missing, and will get it back!!!

interestingly, I still see the tag there: https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.12.1

**Comment by trask** [comment]
I re-created the release (same tag, and same opentelemetry-javaagent.jar attachment, pulled from maven central): https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.12.1

I will open a community issue to ask the org admins to check the audit log to see if there's any indication what happened.
