### ISSUE TITLE
Replace google-java-format Gradle plugin with spotless

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#568]
We use spotless plugin for automatically adding license header to files. As it also can apply google java format, there is no need to use 2 plugins. We can drop the latter.

**Comment by devinsba** [comment]
:+1: this should come over in the 0.56 merge I would expect: https://github.com/DataDog/dd-trace-java/pull/1619

**Comment by anuraaga** [comment]
Hehe yeah I've been hitting this a lot lately.

**Comment by iNikem** [comment]
Fixed by #583
