### ISSUE TITLE
Not clear that agent users must not initialize the SDK

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#5682]
I think we've had a few reported issues because of an agent user initializing the SDK. We probably don't discourage this enough. We can probably

- Document as soon as we mention an agent artifact the ones that should not be present with it. Notably if we just list the two compatible artifacts, -api and -annotations, we can probably prevent others from being used

- Add instrumentation in the agent to log a very scary warning when the SDK is built

- Move annotations into -api? More of a strawmans but I think ideally either it is in -api, assuming a non-agent solution to using them will come some day, or acknowledge we won't do this in v1 and just move it to `.javaagent` Maven namespace to make more obvious that the annotations are 1:1 with javaagent, it would be more obvious for users I think

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
