### ISSUE TITLE
Run CI check in parallel with build

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#570]
From what I understand, the CI runs tests after building the agent jars so it can be built once with JDK11 and used to run tests on many JVMs. I guess this isn't necessary for check - does it make sense to run check in parallel with build for slightly faster turnaround time?

**Comment by iNikem** [comment]
It does not decrease total CI time, because check is quite fast compared to tests and muzzle.

**Comment by trask** [comment]
I think @anuraaga means quick feedback in the (all too common :joy:) case that we submit PRs that fail `check`

**Comment by anuraaga** [comment]
Yup!

**Comment by iNikem** [comment]
Got it. Makes sense now.
