### ISSUE TITLE
Document suppress-controller-spans and suppress-view-spans

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5701]
Probably makes sense here: https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#suppressing-specific-auto-instrumentation

otel.instrumentation.common.experimental.suppress-controller-spans

otel.instrumentation.common.experimental.suppress-view-spans

**Comment by mateuszrzeszutek** [comment]
Implemented in https://github.com/open-telemetry/opentelemetry.io/pull/1249
