### ISSUE TITLE
Tracing a message across Azure Service Bus with Opentelemetry and Jaeger, receiver service trace is not getting collected

### ISSUE THREAD

**Issue by xuyuji9000** [open-telemetry/opentelemetry-java-instrumentation#5702]
**Describe the bug**
I'm trying to trace a message across Azure Service Bus. 

I'm using Jaeger as backend to store the traces. 

I'm using `opentelemetry-javaagent`as the tool to collect and send traces from service to Jaeger backend.

Jaeger is able to pick up the `sender` service traces, but not able to pick up `receiver` service traces.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4877346/160561097-b714a6cb-1730-4706-933a-792aa52b4427.png">

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
`receiver` service's traces can not collected by Jaeger backend, and able to be correlated with `sender` service traces.

**What did you see instead?**
I can only see `sender` service traces in Jaeger, and `receiver` service traces are not there.
If I `kubectl log` into the `receiver` service pod, I'm able to find the trace id has been propagated to `receiver` service.

**What version are you using?**

- `opentelemetry-javaagent`: v1.12.0 

**Environment**
AKS(Azure Kubernetes Service): v1.21.9
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**
If `sender` service is directly depend on `receiver` service, without going through Azure Service Bus.
`receiver` service's trace is able to be collected into Jaeger backend.

**Comment by trask** [comment]
hi @xuyuji9000! this is probably the same issue as https://github.com/Azure/azure-sdk-for-java/issues/26269, can you see if the workaround that @lmolkova describes there works for you?

**Comment by xuyuji9000** [comment]
One solution I'm thinking right now.

Is to change the automatic tracing of `receiver` service to manual instrumentation.

Considering the `receiver` service is getting triggered in a different way comparing with `sender` service. 

While `sender` service is triggered through HTTP request, `receiver` service is subscribed to an Azure Service Bus topic. This might be the reason why `opentelemetry-javaagent` is not able to pick up the trace from the `receiver` service and send it to `Jaeger` backend.

**Comment by xuyuji9000** [comment]
@trask Thank you so much for pointing me at this direction.

The the [issue](https://github.com/Azure/azure-sdk-for-java/issues/26269#issuecomment-1031803250) you referred me to.
Confirmed my hypothesis the `receiver` service of Azure Service Bus topic is automatically instrumented.

This is very helpful information.

**Comment by trask** [comment]
Closing as this issue is tracked in Azure SDK repo at https://github.com/Azure/azure-sdk-for-java/issues/26269#issuecomment-1031803250
