### ISSUE TITLE
Kafka Batch Consumer Instrumentation behaviour changes with environment.

### ISSUE THREAD

**Issue by hardik-fareye** [open-telemetry/opentelemetry-java-instrumentation#5713]
**Description of bug**
I am using the OTEL java instrumentation agent for instrumenting asynchronous Kafka consume operations. We are using batch consumers and we are doing that using "spring-kafka-2.7" dependency.

According to the OTEL documentation: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving, There will be links to the producer trace in the consumer trace. This behavior is working fine while I am testing on my local machine.

When I am deploying the OTEL java-agent to a Kubernetes environment, the consumer trace is not getting created. Instead, all the consumer spans are getting inserted in producer trace only. **Upon investigating, below are the findings**:

1. I added logs in the instrumentation code of spring-kafka-2.7 batch consumer. In that, I found that the "process" spans for the batch consumers are getting suppressed because of the below function.
Function link: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/32c3f450390a734b3185402276950bba84fc16e0/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/SuppressIfSameSpanKeyStrategy.java#L31

2. Now, to investigate further, I tried to find out what parentContext I am receiving in the ConsumerRecords. In both environments it was NULL.

3. Then in the code mentioned in below link:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/32c3f450390a734b3185402276950bba84fc16e0/instrumentation/spring/spring-kafka-2.7/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/spring/kafka/InstrumentedBatchInterceptor.java#L49

If the received context is null, we use Context.current().  **This current context value was empty when I was testing in the local machine but it was holding the complete trace context of the Producer trace in the Kubernetes environment.** So, it was clear that the instrumentation was behaving differently in K8s environment because Context.current() holds the producer trace which suppresses the "process" span in the consumer.

Can I get some help in determining why Context.current() was different in different environments? And also why this check was implemented?

Also, in case of non-batch consumers, all the consumer traces are getting appended in one single trace which is very strange. But, in that case also, the "process" span is missing from the trace.

**Steps to reproduce**
Deploy Kafka out of the k8s cluster and run your batch consumer inside the k8s cluster. It is getting reproduced for me in that case.

**What did you expect to see?**
- Different producer and consumer traces in the case of the batch consumer.
- Different traces in the case of non-batch consumers also.

**What did you see instead?**
- In the case of batch consumers, producer, and consumer spans are coming in 1 trace only.
- In the case of non-batch consumers, multiple consumer traces are getting clubbed in one trace ID.

**What version are you using?**
v1.12.0
Also, tried to make a jar file from the master branch, the same result then also.

**Environment**
Compiler: Application running on Java 8, OTEL library compiled on JDK 11.0.14.1
OS: Ubuntu 20.04

**Comment by trask** [comment]
hi @hardik-fareye! I don't have any ideas off-hand, can you post a complete runnable repro to a github repository that we can look at?

**Comment by hardik-fareye** [comment]
Hello @trask 
This issue seems to be already fixed in version v1.13.1.
I think #5826 Is responsible for fixing this.

Thanks
