### ISSUE TITLE
Enable span suppression by type (SpanKey) by default

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#5735]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3691 introduced the more flexible, "by type" span suppression - it is still turned off by default ([code](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/InstrumenterBuilder.java#L41)), even though the spec allows nested CLIENT/PRODUCER span kinds ([link](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind)).
Should we turn this behavior on by default? Recently there's been some progress on the instrumentation-api stability front, and we have to decide what we're going to do with this feature if we want to release a stable version. Personally, I believe that this should be on by default - since it very much makes sense to emit multiple spans of the same kind if they describe different aspects (conventions) of an operation.

**Comment by trask** [comment]
I support enabling it by default.

cc @lmolkova
