### ISSUE TITLE
Hide bridge aspect in context bridge toString

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#5742]
Currently we just print out all the contents of our bridged context, including implementation details like the otel-context. It probably makes sense to just print out the "resolved context" so that adding the javaagent has a same Context.toString as without the javaagent (with the expection of extra fields possibly added to the context by instrumentation itself though).

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
