### ISSUE TITLE
async cancellation should use same attribute name

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#5765]
Currently the attribute name when canceling an async return value via `WithSpan` encodes the instrumentation name as well

`guava.canceled`
`reactor.canceled`

I would expect them all to be the same. Though it's true that because the async end strategy is not the instrumentation name (which is otelannotations), it would lose that information.

**Comment by trask** [comment]
some ideas:

* `future.canceled`
* `promise.canceled`
* `async.canceled`

I don't love `async.canceled` because `async` has such a broad meaning. I think my vote currently would go toward `promise.canceled`.

**Comment by trask** [comment]
Closing, these attributes are now opt-in under an experimental flag, can revisit later if anyone has renewed interest.
