### ISSUE TITLE
Reactor WithSpan changes return type of method

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#5766]
Currently, reactor WithSpan will call `flatMap` in a way that changes the return type of a method. It means this code works without agent but not with agent

```java
@WithSpan
Flux<String> foo() {
  return UnicastProcessor.create();
}

main() {
  Flux<String> bar = foo();
  ((UnicastProcessor) bar).onNext("bear");
}
```

It breaks the "agent never crashes the app" contract though perhaps this is unavoidable and the user code is quite questionable. Well, I did randomly run into such crashing when writing unit tests for our agent so maybe I'm a questionable user :-) But outside of that maybe we just need to live with it, but reporting to check

**Comment by trask** [comment]
> It breaks the "agent never crashes the app" contract

this is an interesting case, I'd assume someone adding `@WithSpan` to their code has tested it with the agent, which helps mitigate the "agent never crashes the app" but certainly doesn't absolve us completely.

I'd leave this open, if someone has ideas for how to avoid changing the type, we would definitely be interested.

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
