### ISSUE TITLE
Review RequestDispatcherAdvice

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#579]
It is quite confusing at the moment.

First, it seems to do something similar to `Servlet3Advice` rescoping check, but in very different way. Have to check if they can be unified.

Second, it replaces `CONTEXT_ATTRIBUTE` in the current request. This seems to beat the original purpose of that attribute: to server as a marker that this request is already being taken care of. And/or to hold `SERVER` span.

**Comment by trask** [comment]
@iNikem RequestDispatcherAdvice looks much better [now](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/87950d1d3286bc58cd3c665db52b2b4465942842/instrumentation/servlet/servlet-javax-common/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/servlet/javax/dispatcher/RequestDispatcherAdvice.java#L19) compared to [when you opened this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/2bcd35a251d70809bc213ac6c871f7079a34121b/instrumentation/servlet/servlet-common/src/main/java/io/opentelemetry/auto/instrumentation/servlet/dispatcher/RequestDispatcherInstrumentation.java#L88), can this be closed?

**Comment by iNikem** [comment]
> @iNikem RequestDispatcherAdvice looks much better [now](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/87950d1d3286bc58cd3c665db52b2b4465942842/instrumentation/servlet/servlet-javax-common/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/servlet/javax/dispatcher/RequestDispatcherAdvice.java#L19) compared to [when you opened this](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/2bcd35a251d70809bc213ac6c871f7079a34121b/instrumentation/servlet/servlet-common/src/main/java/io/opentelemetry/auto/instrumentation/servlet/dispatcher/RequestDispatcherInstrumentation.java#L88), can this be closed?

I don't think so. It still does some funny business with `CONTEXT_ATTRIBUTE`

**Comment by trask** [comment]
> I don't think so. It still does some funny business with `CONTEXT_ATTRIBUTE`

ya, true, tried to make some progress on this in #2724, but still left a couple of TODOs in the code to come back to (will leave this issue open until those are addressed)
