### ISSUE TITLE
[Question] How do we use the ConfigPropertySource SPI?

### ISSUE THREAD

**Issue by dzou** [open-telemetry/opentelemetry-java-instrumentation#5794]
Are there any special steps we need to take to use the [ConfigPropertySource](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/extension/config/ConfigPropertySource.java) SPI? I'm not sure I understand it correctly, I just implemented the `ConfigPropertySource` class in my project with the `@AutoService` annotation, but the properties don't seem to get picked up by OpenTelemetry agent when the app is run?

Can someone share what are the steps a user takes to use ConfigPropertySource?

```
import com.google.auto.service.AutoService;
import io.opentelemetry.javaagent.extension.config.ConfigPropertySource;
import java.util.Map;

@AutoService(ConfigPropertySource.class)
public class TracingConfigPropertySource implements ConfigPropertySource {

  @Override
  public Map<String, String> getProperties() {
    return Map.of(
        "otel.javaagent.debug", "true",
        "otel.traces.exporter", "jaeger",
        "otel.service.name", "example-service"
    );
  }
}
```

**Comment by mateuszrzeszutek** [comment]
Hey @dzou ,
You'll need to put your `ConfigPropertySource` in a separate [extension jar](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension). Currently, the agent is able to load SPI implementations placed in the application code; they must be loaded separately via the extension mechanism.
The extension example project contains a sample [`ConfigPropertySource`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/extension/src/main/java/com/example/javaagent/DemoPropertySource.java) implementation, you can start by copying the extension project and removing everything but the demo property source class.

**Comment by dzou** [comment]
Thanks!

**Comment by atamanroman** [comment]
Hey @mateuszrzeszutek,

> [...] Currently, the agent is able to load SPI implementations placed in the application code; they must be loaded separately via the extension mechanism. [...]

You mean "the agent is *not* able to load SPI implementations placed in the application code", right?

That's what I'm concluding from the source code and documentation, but it's not written out anywhere.

**Comment by mateuszrzeszutek** [comment]
> You mean "the agent is _not_ able to load SPI implementations placed in the application code", right?
> 
> That's what I'm concluding from the source code and documentation, but it's not written out anywhere.

Yes, sorry, that was a typo 🙈 

The agent only loads the SPI implementations from its own jar and the extension jars. Loading SPI implementations from the application itself is **not** currently supported.
