### ISSUE TITLE
Agent now tries to check that it is the class that's registered in the manifest

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#580]
With the downstream merge, there is now a check that the main class declared in the manifest is the agent class

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/java-agent/src/main/java/io/opentelemetry/auto/bootstrap/AgentBootstrap.java#L182

This seems to prevent the use case of redistributing the agent where we delegate to that `AgentBootstrap` but have our own class as the entry point

https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/blob/both-otel-and-xray/otelagent/build.gradle.kts#L48

Do we need this check? Should we move the business logic from `AgentBootstrap` to a different entrypoint for shaded agents and `AgentBootstrap` only does the check before calling it?

Also, as you can see from the above link, the check seems wrong anyways, I was easily able to work around the issue by setting `Main-Class`, which isn't the agent class ;)

**Comment by iNikem** [comment]
That check is made to prevent _accidental_ inclusion of instrumentation agent into end-user's application's fat jar. It is totally OK IMO if purposeful repackaging can easy silence that check :)

**Comment by anuraaga** [comment]
Ah ok I get it now - it's probably why main class was even set in the first place. Then I think it's fine it's easy to deal with for repackagers.

**Comment by trask** [comment]
Re-opening to see if we can come up with a better solution than hardcoding a strange `Main-Class` in `META-INF/MANIFEST.MF`.

**Comment by iNikem** [comment]
Closed by #3302
