### ISSUE TITLE
OpenJ9 base image too big

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#5815]
The openj9 smoke test images are about 1.8GB. This means anyone that needs to debug openj9 locally will have some troubles having to wait for such a huge download, assuming it doesn't blow up their network bill. Indeed, even GitHub actions can have a blown up bill, as sometimes the pull gets heavily throttled causing the build to fail

https://github.com/open-telemetry/opentelemetry-java-instrumentation/runs/6000832881?check_suite_focus=true

Is there a smaller OpenJ9 image? If not official, it is probably worth us to create one to not have such a huge image.

**Comment by laurit** [comment]
It isn't really downloading openj9 but our gradle build cache.

**Comment by anuraaga** [comment]
Oops - I guess I found the OpenJ9 image to be a bit big when pulling it and coincidentally this was also openj9. Looks like nothing we can do.
