### ISSUE TITLE
Adding Hikari Metrics 

### ISSUE THREAD

**Issue by shreya22-1998** [open-telemetry/opentelemetry-java-instrumentation#5860]
hikaricp_connections_usage_seconds
hikaricp_connections_usage_seconds_max
hikaricp_connections
hikaricp_connections_min
hikaricp_connections_acquire_seconds
hikaricp_connections_acquire_seconds_max
hikaricp_connections_creation_seconds_max
hikaricp_connections_creation_seconds
hikaricp_connections_active
hikaricp_connections_idle
hikaricp_connections_max
hikaricp_connections_timeout_total

Is open-telemetry planning to add instrumentation for hikari metrics?

**Comment by trask** [comment]
yes! we are working on spec'ing database connection pool metrics currently in https://github.com/open-telemetry/opentelemetry-specification/pull/2273
