### ISSUE TITLE
Run on k8s failed but successed on VM. 

### ISSUE THREAD

**Issue by Jungle666** [open-telemetry/opentelemetry-java-instrumentation#5876]
Run on k8s failed but successed on VM.

run commad:
java -javaagent:/usr/local/agent/opentelemetry-javaagent.jar -Dotel.exporter.otlp.endpoint=http://:4317 -Dotel.resource.attributes=tps.tenant.id=___apm,service.name=demo -Dotel.javaagent.extensions=/usr/local/agent/ -Dotel.metrics.exporter=none -Dotel.traces.sampler=parentbased_traceidratio -Dotel.traces.sampler.arg=1 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/demo.jar

error info:
Failed to find Premain-Class manifest attribute in /usr/local/agent/opentelemetry-javaagent.jar
Error occurred during initialization of VM
agent library failed to init: instrument

**Comment by trask** [comment]
hi @Jungle666! often this is caused by the file not really being at `/usr/local/agent/opentelemetry-javaagent.jar`, or the process not having permissions to that location, or a corrupt file (try re-downloading to be sure)

**Comment by Jungle666** [comment]
> hi @Jungle666! often this error is caused by the file not really being at `/usr/local/agent/opentelemetry-javaagent.jar`, or the process not having permissions to that location, or a corrupt file (try re-downloading to be sure)

i guass version 1.13.0 has such bug，case 1.9.0 works fine.

**Comment by Jungle666** [comment]
> 

the lastest  version 1.13.0 works fine now
