### ISSUE TITLE
How do I provide local debugging

### ISSUE THREAD

**Issue by chenkaiyin1201** [open-telemetry/opentelemetry-java-instrumentation#5880]
For example: There is confusion in closing code

**Comment by mateuszrzeszutek** [comment]
Hey @chenkaiyin1201 ,
I'm not sure what you mean by that, can you elaborate? Or provide an example of how you'd expect the agent to behave.

**Comment by chenkaiyin1201** [comment]
Hi  @mateuszrzeszutek 
When I introduced the whole OpentElemetry as a module into my project, I found it difficult to deal with various environmental issues.
So I try to introduce the javaagent when a libraries for debugging, but such as I want to debug RocketMqConsumerInstrumenter, jar package code is confused, I didn't also the way to debug the corresponding files.
So, is there a documentation that helps with debugging, or is there a documentation that helps us quickly set up a debuggable environment locall.

Thanks.

**Comment by mateuszrzeszutek** [comment]
Take a look at the following doc: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/debugging.md

Debugging the javaagent code is somewhat limited, but as long as it's not advice class code you should be able to debug it.

**Comment by laurit** [comment]
Feel free to reopen if you have more questions.
