### ISSUE TITLE
Version 1.13.0 Migration notes typo?

### ISSUE THREAD

**Issue by kelystor** [open-telemetry/opentelemetry-java-instrumentation#5893]
[https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases)

Version 1.13.0 release `Migration notes` Section：

> otel.instrumentation.netty.ssl-telemetry.enabled -> otel.instrumentation.netty.ssl-telemetry.enabled

this configuration property haven't been renamed, they are the same.

**Comment by mateuszrzeszutek** [comment]
Hey @kelystor 
Thanks for noticing this! It was supposed to be about the `otel.instrumentation.reactor-netty.always-create-connect-span` property. I fixed the v1.13.0 release notes.

**Comment by kelystor** [comment]
`CHANGELOG.md` in repository also has the same error

**Comment by mateuszrzeszutek** [comment]
Thanks!
