### ISSUE TITLE
Example showing -all HTTP headers passed via request. Showing current naming conventions for the default headers. 

### ISSUE THREAD

**Issue by msonali12** [open-telemetry/opentelemetry-java-instrumentation#5897]
**Is your feature request related to a problem? Please describe.**
Problem statement : Would like to know details of all default https headers passed via request. 
Specially for SpanContext. (naming conventions for spanid, traceid,traceflag and tracetate)

**Describe the solution you'd like**
An example - may be printing all default headers as part of logs.

**Describe alternatives you've considered**
Gone through the semantics convention documentation (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md),
 but could not find anything related to conventions for the headers passed for spancontext. 

**Additional context**
Seen an example for openteleemtry-python. (https://opentelemetry-python-yusuket.readthedocs.io/en/latest/examples/http/README.html)
Requesting similar one for java

**Comment by trask** [comment]
> Seen an example for openteleemtry-python. (https://opentelemetry-python-yusuket.readthedocs.io/en/latest/examples/http/README.html)
Requesting similar one for java

hi @msonali12! I think in the Java world, this would be similar to running the spring petclinic sample app + otel javaagent + [otel logging exporters](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#logging-exporter), can you try that and see if that gets you the info you are looking for?

**Comment by laurit** [comment]
Feel free to reopen if you have more questions.
