### ISSUE TITLE
redisson sentinel client failed to start with redisson instrumentation

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/opentelemetry-java-instrumentation#5925]
<img width="670" alt="图片" src="https://user-images.githubusercontent.com/27889201/164895652-b3666d82-b20a-4304-a638-4589bbde6409.png">
redisson client with the javaagent failed to execut the `ping` command to the sentinel client. I add the args `-Dotel.instrumentation.redisson.enabled=false` and it is ok.

In fact, there are problems between redisson client and sentinel server, but it wiil only failed to init with the redisson instrumentation.
<img width="862" alt="图片" src="https://user-images.githubusercontent.com/27889201/164895828-0667b642-8b15-4a95-88f9-543ad729cb5c.png">

I checked the code and thought that this line of code may have caused DNS lookup and timeout of the Ping request that should have been quick and successful

**Comment by tydhot** [comment]
<img width="648" alt="图片" src="https://user-images.githubusercontent.com/27889201/164896211-a5389947-f690-451a-91d1-ed1d613948b4.png">


In addition, according to the log, there is an interval of 6 seconds between the successful server of the first Ping and the failure of startup

**Comment by tydhot** [comment]
@laurit yes i think u are right. I think  `peerName` is too  dangerous when dns look up happen.

**Comment by trask** [comment]
hi @tydhot, just wanted to confirm my understanding, you are connecting to redis via an IP address, and the instrumentation is doing a reverse lookup on that IP address?

@laurit is your https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/5305#discussion_r799359788 the way forward here?

**Comment by trask** [comment]
@tydhot any luck tracking this down?

**Comment by tydhot** [comment]
@trask @laurit sry 4 relpay late. The problem does not exist after redis is restored. At present, there is no condition to reproduce the problem. Incidentally, this problem occurred in 1.9.0.

**Comment by laurit** [comment]
Thanks. This was probably fixed in `1.11.0`.
