### ISSUE TITLE
AgentTracerProviderConfigurer#loggingExporterIsNotAlreadyConfigured

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-java-instrumentation#5927]
```java
  private static boolean loggingExporterIsNotAlreadyConfigured() {
    return !Config.get().getString("otel.traces.exporter", "").equalsIgnoreCase("logging");
  }
```
Mybe `otel.traces.exporter` has serveral values,like `otel.traces.exporter=otlp,logging`

**Comment by wallezhang** [comment]
I think it should use `getSet()` method instead of `getString()` method and use `contains()` method to determine whether the logging exporter has been configured.

**Comment by trask** [comment]
hi @chenjazz @wallezhang! I thought that `otel.traces.exporter` doesn't support multiple values?

**Comment by wallezhang** [comment]
> hi @chenjazz @wallezhang! I thought that `otel.traces.exporter` doesn't support multiple values?

According to this document: https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#exporters

The configuration support multiple values that separated by commas.
