### ISSUE TITLE
Remove HttpClientTest.READ_TIMEOUT_MS

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#593]
Having a small-ish value for `HttpClientTest.CONNECT_TIMEOUT_MS` is helpful to keep the connection error tests from taking a long time (the tests that attempt to connect to `http://www.google.com:81`) .

But I'm not seeing why we need to override the default readTimeout everywhere with `HttpClientTest.READ_TIMEOUT_MS`.

**Comment by malafeev** [comment]
based on submitted PR looks like removing makes tests more unstable.

**Comment by malafeev** [comment]
can be closed.

**Comment by iNikem** [comment]
@malafeev just in case you don't know it yet: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
