### ISSUE TITLE
Question: Create an extension to generate spans for a new instrumentation module 

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-java-instrumentation#5938]
Hi all, 

I've been trying to create a javaagent extension to generate new spans for methods of a specific interface. I created a new instrumentation module and was able to generate the additional spans by building it with the javaagent but when I try to build the same instrumentation module as an extension and pass the extension to the agent, I do not get the additional spans.

My question is, is it possible to build a net new instrumentation module as an extension? I have been able to augment existing spans for supported frameworks with my extension but the instrumentation for the additional methods does not work.

**Comment by trask** [comment]
hi @akats7! the example extension has some net new instrumentation: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension/src/main/java/com/example/javaagent/instrumentation

**Comment by akats7** [comment]
hi @trask, thanks for the quick reply! I saw the example before and looks like the demo instrumentation is not creating any additional spans, I guess that's essentially what I want to confirm, I should be able to generate additional spans by using an extension the same way I was able to by adding an instrumentation module to the agent itself.

**Comment by mateuszrzeszutek** [comment]
Hey @akats7,
Can you try running the agent in the debug mode (`-Dotel.javaagent.debug=true`) and posting the logs here? Maybe there's something that's stopping your instrumentation from being applied.

**Comment by laurit** [comment]
Feel free to reopen when you are ready to provide additional details.
