### ISSUE TITLE
Adding Attribute(service.name) in all the populated metrics

### ISSUE THREAD

**Issue by Shivanireddie** [open-telemetry/opentelemetry-java-instrumentation#5939]
we are unable to get service.name in all the populated metrics.
requires service name because we need to know which service is populating the metrics like below example

jvm_threads_states_threads{**application="simple-demo-app2**",state="new",} 0.0
jvm_memory_used_bytes{**application="simple-demo-app2**",area="nonheap",id="Compressed Class Space",} 6672984.0

**Comment by mateuszrzeszutek** [comment]
Hey @Shivanireddie ,
You're using the Prometheus exporter, is that correct?

**Comment by Shivanireddie** [comment]
Yes, we are using  Prometheus exporter

**Comment by mateuszrzeszutek** [comment]
Looks like this is intended behavior, according to [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#resource-attributes-1):

> resource attributes SHOULD be converted to the ["target" info](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#supporting-target-metadata-in-both-push-based-and-pull-based-systems) metric family; otherwise, they MUST be dropped, and MUST NOT be attached as labels to other metric families

@open-telemetry/java-approvers can you take a look at this issue? (and move it over to the SDK repo)

**Comment by mateuszrzeszutek** [comment]
There's the "target" info metric though, which we're not doing in Java SDK right now. I'm not sure how that would help though.
