### ISSUE TITLE
Kafka-metrics

### ISSUE THREAD

**Issue by Shivanireddie** [open-telemetry/opentelemetry-java-instrumentation#5941]
.
can we expect to have kafka metrics
1. kafka_producer_message_count
2. kafka_consumer_message_count

**Comment by mateuszrzeszutek** [comment]
Hey @Shivanireddie ,
We will implement consumer/producer metrics once the semantic conventions for them are specified in the [OpenTelemetry specification](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions).
Before that happens you can probably use the [JMX metrics gatherer](https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/jmx-metrics) project from the contrib repo -- and if you're using the OTel collector, take a look at the [JMX receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/jmxreceiver) too (it uses the aforementioned gatherer inside).

**Comment by jack-berg** [comment]
I'm actively working on implementing metric instrumentation for the kafka publisher and consumer [semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/instrumentation/kafka.md).

**Comment by elizabetht** [comment]
@jack-berg The link for Kafka semantic convention is broken in your comment above. Could you link the correct semantic convention?

**Comment by trask** [comment]
hi @elizabetht, here you go: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/messaging/kafka.md
