### ISSUE TITLE
Javaagent breaking application that is using IronJacamar

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#5946]
Sequence of events:

Using `org.jboss.ironjacamar:ironjacamar-jdbc:1.4.6.Final`,

* Javaagent jdbc instrumentation calls `getClientInfo()` on `org.jboss.jca.adapters.jdbc.WrappedConnection`
* `WrappedConnection` calls `getClientInfo()` on underlying connection
* Underlying connection throws `UnsupportedOperationException`
* `WrappedConnection` catches this exception and calls
  * `checkException(Throwable)`, which calls
  * `BaseWrapperManagedConnection.connectionError(Throwable)`, which calls
  * `BaseWrapperManagedConnection.broadcastConnectionError(Throwable)`, which calls
  * `AbstractConnectionListener.connectionErrorOccurred`, which calls a couple of ominous sounding things:
    * `unregisterConnections()`
    * `haltCatchFire()`

and then the application breaks, I'm assuming because the connection has been marked as essentially dead.

This seems like poor behavior on the part of IronJacamar, but this behavior seems unchanged even in the latest versions.

A couple of options:

* Never call `getClientInfo()` on `org.jboss.jca.adapters.jdbc.WrappedConnection`
* Introduce a configuration setting to never call `getClientInfo()`

Any other ideas, or preferences between these? I'm leaning towards a hard-coded deny list of Connection implementations that we know have "bad" behavior (it may grow).

**Comment by mateuszrzeszutek** [comment]
> I'm leaning towards a hard-coded deny list of Connection implementations that we know have "bad" behavior (it may grow).

👍 

We've encountered this issue previously (#5012 and Apache Calcite) -- I think that excluding known wrapper/broken implementations is probably the least intrusive option, i.e. we won't have to keep a list of all working JDBC driver implementations in our code.

**Comment by trask** [comment]
> #5012

oh! thanks for connecting the dots, I totally forgot about this

we can still do that in the future, but I will send a PR with the less-intrusive deny-list for now to resolve this current issue
