### ISSUE TITLE
Run benchmark from CI once a week

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#595]
Run both `coldstart` and `runtime` benchmark from:

https://github.com/trask/agent-benchmarking

These spin up a number of Azure App Service VMs and report average and median in order to get a more stable result than you can get on a single cloud machine.

On each VM, the tests alternate enabling/disabling the agent, capturing the overhead that enabling the agent incurs.

**Comment by iNikem** [comment]
Are you sure about running this on every merge? My concern is the cost :) May be run once a week?

**Comment by trask** [comment]
Agree, will plan to start with once a week. Then we can run the benchmark for longer across more machines and get a more stable result.

**Comment by anuraaga** [comment]
Should we start by exporting to a collector within GitHub actions itself? Just spam the spring-boot smoke test container? I don't know if the numbers are reliable or not, but it seems like an easier start than provisioning cloud.

**Comment by anuraaga** [comment]
For reference, I've written this benchmark with testcontainers before for Zipkin, it's basically awk + zipkin + backend + prometheus. https://github.com/openzipkin/zipkin/blob/master/benchmarks/src/test/java/zipkin2/server/ServerIntegratedBenchmark.java

**Comment by trask** [comment]
cc: @breedx-splk ready made issue 😁

**Comment by iNikem** [comment]
We now have https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/workflows/nightly-benchmark-overhead.yml, should we close this issue @trask ?
