### ISSUE TITLE
Rename "tags" to "attributes"

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#598]
Span "tags" is leftover terminology from OpenTracing, we should update to use OpenTelemetry terminology span "attributes".

**Comment by anuraaga** [comment]
To confirm, I think this means replacing code that uses `SpanTags` with `SemanticAttributes`?

**Comment by trask** [comment]
I had only been thinking of renaming stuff, e.g.

* SpanAssert.tags() → SpanAssert.attributes()
  * (this will change tons of places, all of the `tags { ... }` in tests)
* io.opentelemetry.auto.instrumentation.api.Tags → io.opentelemetry.auto.instrumentation.api.Attributes

But totally, no point in renaming `io.opentelemetry.auto.instrumentation.api.Tags`, when we should just delete it and use `SemanticAttributes` instead 👍

**Comment by iNikem** [comment]
Not all Tags, and even more so MoreTags, come from semantic conventions

**Comment by trask** [comment]
It looks like all of `io.opentelemetry.auto.instrumentation.api.Tags` can be replaced by `SemanticAttributes`.

In `MoreTags`, it looks like these particular attributes can be replaced with `SemanticAttributes`:
* `net.peer.name`
* `net.peer.ip`
* `net.peer.port`
* `rpc.service`

and we can rename `MoreTags` to `MoreAttributes` for now until we decide what to do with non-standard attributes.

**Comment by malafeev** [comment]
It's a huge task.
Replacing `io.opentelemetry.auto.instrumentation.api.Tags` by `SemanticAttributes` will be manual.

E.g. convert `Tags.HTTP_URL` to `SemanticAttributes.HTTP_URL`:
```
span.setAttribute(Tags.HTTP_URL, urlBuilder.toString());
```
should be replaced by
```
SemanticAttributes.HTTP_URL.set(span, urlBuilder.toString());
```
etc.

a lot of manual work. 
I think task should be splitted.

**Comment by malafeev** [comment]
I can do one by one renaming, please assign to me if OK.
