### ISSUE TITLE
Should we drop Java 7 support?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#599]
The NewRelic team pointed us to [their blog](https://blog.newrelic.com/technology/state-of-java/), published in March 2020, that shows only 2.5% of Java applications sending data to them are running Java 7.

Plus, I would guess that many applications on Java 7 are just in maintenance mode at this point (and so not tinkering with application monitoring).

Plus, the blog numbers were published in March, and we won't be GA for a few months still, and that percentage is only declining.

Some advantages of dropping Java 7:
* Simplify gradle build/test infrastructure
* Use testcontainers for instrumentation tests (see #552)
* Use Java 8 features
  * Default methods
  * Lambdas

I think we'd want approval on this change from at least AWS (@anuraaga), DataDog (@tylerbenson), Lightstep (@carlosalberto), Microsoft (@trask) and Splunk (@iNikem).

**Comment by anuraaga** [comment]
My main concern is Android, I'm not sure how to interpret their support for Java 8

https://developer.android.com/studio/write/java8-support?hl=el

It seems that the latest Gradle plugin supports a lot, but not all, of Java 8 APIs. Don't know how easy it is for users of the old plugin to upgrade, or how common it would be us to accidentally use a Java 8 API that isn't covered by their translation layer.

I don't see a problem with targeting Java 8 for the agent, since agents can't be used on Android anyways, but the core instrumentation libraries that we've started to separate out should work on Android anywhere the library supports Android.

**Comment by trask** [comment]
This is a good point about Android.

We should probably target Java 7 for some manual instrumentation that is relevant to Android, e.g.
* OkHttp
* gRPC

It might be helpful to get some guidance from the Google team about Android support. @mtwo, @SergeyKanzhelev can you recommend a contact for us to discuss with?

**Comment by trask** [comment]
Decision made in SIG call today to drop Java 7 support except for OkHttp and gRPC manual instrumentation.

We haven't separated out OkHttp and gRPC manual instrumentation yet, but the decision to support Java 7 for those in the future does mean that we still need to target Java 7 for the `auto-bootstrap` module (at least until we split out something like `instrumentation-runtime-api` module from `auto-bootstrap`, which would be the only part that needs to stay on Java 7, see #597 for more about this discussion).

**Comment by trask** [comment]
Oh yes, and if we find out there is other manual instrumentation that is important to the Android ecosystem, we can always transition that specific manual instrumentation back to Java 7 support.

**Comment by trask** [comment]
Closing this discussion, and tracking the resulting action item in #714

**Comment by huntc** [comment]
> My main concern is Android, I'm not sure how to interpret their support for Java 8

I understand that having Android support is nice, but how essential is it for this particular project? Might it be more appropriate to develop an entirely new Kotlin based project and leverage its native capabilities e.g. coroutines etc?
