### ISSUE TITLE
how to custom endpoint in springboot?

### ISSUE THREAD

**Issue by Jungle666** [open-telemetry/opentelemetry-java-instrumentation#5995]
we use jsonrpc in springboot, we put method in params, then we got endpoint like 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/9640834/167243974-8268c57e-c9ae-414b-b8a0-fadcf71bfe00.png">

how to add method to endpoint path.(replace method )

**Comment by trask** [comment]
hi @Jungle666! I'm not quite following, can you explain in a bit more detail, what is `method`, what exactly are you seeing? and what are you expecting/wanting to see? thx

**Comment by Jungle666** [comment]
we use jsonrpc. https://www.jsonrpc.org/specification
in springmvc we usually post http request like
http://localhost/app/api/callMethod
{
    "param1":"",
    "param2":""
     ...      
}

however in jsonrpc,we do like :
http://localhost/app/api
{
  "jsonrpc":"2.0",
   "method":"callMethod",
   "params":{
    "param1":"",
    "param2":""
     ...      
    }
}

then we got endpoint like:
/app/api/ 
without method

**Comment by Jungle666** [comment]
> 

sorry ,i do have no right to access it.

**Comment by Jungle666** [comment]
@trask hello,could you please offer me more?

**Comment by trask** [comment]
Closing, but please let us know if you are still having this issue and we will re-open.
