### ISSUE TITLE
Some Instrumentation API thoughts

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#6014]
* `VirtualField` - maybe move to `util` package, just to avoid a single class package?
* `RequestListener` and `RequestMetrics` - maybe rename to `OperationListener` and `OperationMetrics`?
  * The terms Request/Response I think are good when used to mean the request object / response object, but I think "Request" in these names is used more generally to mean the "request-response-loop".
* `SpanStatusExtractor` - I was thinking maybe we should rename to `StatusExtractor` because I suspect there will be a semantic convention for capturing status on metrics as well (https://github.com/open-telemetry/opentelemetry-specification/issues/2419#issuecomment-1081923604), but `StatusCode` enum is under `io.opentelemetry.api.trace`, so the future is not so clear, and maybe we should stay as-is, and we can always add a common `StatusExtractor` in the future if we want.
* `SpanLinksExtractor.fromUpstreamRequest()` - maybe rename to `fromTextMapPropagator()` and pass in `TextMapPropagator` instead of `ContextPropagators`? This would also make it future-proof if/when "Binary" Propagator is introduced.
* `TimeExtractor` - maybe slim it down to just `StartTimeExtractor`? this would satisfy all of our use cases, and make it clearer that overriding end time doesn't really work for metrics anyways

**Comment by mateuszrzeszutek** [comment]
> * `VirtualField` - maybe move to `util` package, just to avoid a single class package?

Hmm, I always thought of `VirtualField` as of a pretty essential class, not just another random utility class. But it's true, we won't ever add anything else to that `field` package, might as well move it somewhere else.

> * `RequestListener` and `RequestMetrics` - maybe rename to `OperationListener` and `OperationMetrics`?

👍 

> * `SpanStatusExtractor` - I was thinking maybe we should rename to `StatusExtractor` because I suspect there will be a semantic convention for capturing status on metrics as well

I think that might be only true for RPC metrics, e.g. HTTP has status code. And the `StatusCode` is span-only after all.

> * `SpanLinksExtractor.fromUpstreamRequest()` - maybe rename to `fromTextMapPropagator()` and pass in `TextMapPropagator` instead of `ContextPropagators`?

👍 

> * `TimeExtractor` - maybe slim it down to just `StartTimeExtractor`? this would satisfy all of our use cases, and make it clearer that overriding end time doesn't really work for metrics anyways

Hmm, I think the Armeria instrumentation used to report custom start & end times; it seems we've removed that with the migration to Instrumenter API. Also, that might be just me, but getting start and end timestamp from different clocks kind of doesn't seem right to me 😅
