### ISSUE TITLE
JDBC automatic instrumentation not showing all query spans

### ISSUE THREAD

**Issue by reify-marcio-faria** [open-telemetry/opentelemetry-java-instrumentation#6036]
We are using the jdbc automatic instrumentation, and have noticed that the otel javaagent isn’t reporting spans that are shorter than about 150us, mostly, because in other parts of our system we got spans of 20us. Hence, it's only a piece of observational evidence, so we are still trying to figure out if it's a bug, something expected but undocumented, or if there is some way to configure it.

Does anyone have any guesses/knowledge of where to look?

**Comment by reify-marcio-faria** [comment]
One of my suspects was that some sort of cache of prepared statements could be involved with such behavior but we cannot prove this hypothesis, so we are blind. Any help with it could be valuable. We are sending it to Datadog via the DD exporter.

**Comment by trask** [comment]
hi @reify-marcio-faria! is the same SQL query executed from the same code sometimes captured and sometimes not captured? what tool are you using to see that it is really being executed against your database as opposed to getting returned from some internal data/query cache and not hitting the database?

**Comment by trask** [comment]
> I'm trying to figure out if there is some configuration to handle this

if you are emitting a query to your database, it should be getting captured

let us know what you find out, we would most likely need a minimal repro in order to troubleshoot the issue from our side

**Comment by reify-marcio-faria** [comment]
Hey @trask, I have dug a little on that problem and find that what we have here is a sort of 👻 span, a db span that hasn't any query statement. This first one:

```
[worker-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'my_app_service_db' : 43324796ed58d4f35506bbad41712896 2d94e78f23850046 CLIENT [tracer: io.opentelemetry.jdbc:1.14.0-alpha] AttributesMap{data={db.name=my_app_service_db, net.peer.port=5432, thread.name=worker-1, db.user=my_app, db.connection_string=postgresql://localhost:5432, net.peer.name=localhost, db.system=postgresql, db.statement=, thread.id=69}, capacity=128, totalAddedValues=9}
```

It shows only the database name, after that we have all other regular spans:

```
[worker-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'HikariDataSource.getConnection' : 28b3a40891bf36f691c41c9d3b4a89d2 5fdd1318db114720 INTERNAL [tracer: io.opentelemetry.jdbc:1.14.0-alpha] AttributesMap{data={thread.name=worker-1, code.namespace=com.zaxxer.hikari.HikariDataSource, code.function=getConnection, thread.id=72}, capacity=128, totalAddedValues=4}
[worker-1] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'SELECT my_app_service_db' : 28b3a40891bf36f691c41c9d3b4a89d2 3b8f4e20710dde83 CLIENT [tracer: io.opentelemetry.jdbc:1.14.0-alpha] AttributesMap{data={db.operation=SELECT, db.name=my_app_service_db, net.peer.port=5432, thread.name=worker-1, db.user=my_app, db.connection_string=postgresql://localhost:5432, net.peer.name=localhost, db.system=postgresql, db.statement=SELECT ?, thread.id=72}, capacity=128, totalAddedValues=10}
```

Interesting that the SQL executes only one query, as expected:

```
| 2022-05-21 00:32:21.533 UTC [41] LOG:  execute S_2: SELECT 1
```

We use Clojure here, so I can create a minimum reproducible repository with a docker compose configuration if it helps.

**Comment by trask** [comment]
👍 repros are super helpful, thx

**Comment by reify-marcio-faria** [comment]
We are using both, the Datadog Agent and the Opentelemetry Agent, and it looks like [they don't work very well when used together](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1534).

We are conducting more investigations.

**Comment by trask** [comment]
ya, we don't recommend (or test or support) running multiple "tracing" javaagents at the same time. DataDog has an OpenTelemetry collector exporter that you can use if you want to pipe telemetry to multiple backends.

**Comment by trask** [comment]
@reify-marcio-faria are you still having this issue, or is it ok to close? thx!

**Comment by mateuszrzeszutek** [comment]
Ping @reify-marcio-faria
