### ISSUE TITLE
A few more module naming suggestions before publishing

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#605]
* `opentelemetry-aws-sdk-2.2-core` ➡️ `opentelemetry-aws-sdk-2.2`
* `vertx` ➡️ `vertx-3.0`
* `vertx-reactive` ➡️ `vertx-reactive-3.5`
* `opentelemetry-auto-trace-annotation` ➡️ `opentelemetry-auto-annotations`
* split `elasticsearch-common` into `elasticsearch-rest-common` and `elasticsearch-transport-common`

**Comment by iNikem** [comment]
What should we do with `instrumentation-core` folder? Probably the most sensible thing is to rename it to `instrumentations` and move current content of `instrumentation` folder into `instrumentations/auto`

**Comment by anuraaga** [comment]
That seems like a simple change to make, but what do you think about long term? I was thinking we might end up with structure like

```
instrumentations
  aws-sdk
    auto
    core
    testing
```

If this seems like a good long term, maybe should just go straight for it.

**Comment by iNikem** [comment]
Not sure about `core`, but this "pivoting" of folder structure seems interesting. I wonder how different `common` modules will pay out.
