### ISSUE TITLE
Actual class names of spring boot application are wrapped by  `SpringSchedulingRunnablewrapper`

### ISSUE THREAD

**Issue by vasireddy99** [open-telemetry/opentelemetry-java-instrumentation#6103]
**Describe the bug**
When using OTEL with Spring boot app, spring boot admin console wraps all actual classes with `io.opentelemetry.javaagent.instrumentation.spring.scheduling.SpringSchedulingRunnablewrapper`.

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/41936996/170635191-e7e0d748-d162-487c-b3b0-c3874e56dddd.png">

**What did you expect to see?**
It is expected to to see the actual classes and not to have the above wrapper as shown in the image.

**What version are you using?**
 v1.14.0

**Comment by breedx-splk** [comment]
> [...]we could try wrapping it at some later point, perhaps when any of the schedule methods are called on `org.springframework.scheduling.TaskScheduler`?

If that list in the screenshot is created within the schedule methods, though, the same problem would exist right?

**Comment by laurit** [comment]
> > [...]we could try wrapping it at some later point, perhaps when any of the schedule methods are called on `org.springframework.scheduling.TaskScheduler`?
> 
> If that list in the screenshot is created within the schedule methods, though, the same problem would exist right?

Yes, but I find it unlikely that it is filled there.
