### ISSUE TITLE
AWS SDK instrumentation support for XRay `SegmentNotFoundException` when request manages its own threadPool

### ISSUE THREAD

**Issue by Zhenye-Na** [open-telemetry/opentelemetry-java-instrumentation#6104]
**Describe the bug**

Existing raised tickets that related to this issue

- https://github.com/aws/aws-xray-sdk-java/issues/313
- https://github.com/aws/aws-sdk-java/issues/1572
- https://github.com/aws/aws-sdk-java-v2/issues/3217

> I would recommend you open this feature request in the [OpenTelemetry Java](https://github.com/open-telemetry/opentelemetry-java-instrumentation) repo as well since they have an AWS SDK instrumentation that could be extended to support this.

Encouraged to open this issue so that AWS Team could follow up

**What version are you using?**

Not directly depdend on this library, but I assume AWS XRay has the dependency on this library

**Environment**
OS: Amazon Linux 2
Runtime (if different from JDK above): Corretto JDK 8

**Comment by trask** [comment]
hi @Zhenye-Na, can you let us know if there's anything that (still) needs to be done in this repository? thx
