### ISSUE TITLE
Auto-instrumentation of logging

### ISSUE THREAD

**Issue by devops-42** [open-telemetry/opentelemetry-java-instrumentation#6110]
Hi,

is it possible, without additional forwards (like fluentbit or others), to send application logs via auto-instrumentation to an OTel collector?

Thanks for your help!

**Comment by wallezhang** [comment]
See this dependency: opentelemetry-exporter-otlp-logs, and configure logs exporter. 

auto-configuration document:
https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#otlp-exporter-span-metric-and-log-exporters

**Comment by devops-42** [comment]
Hi @wallezhang,

have set the `OTEL_LOGS_EXPORTER` property, works now. Thanks for your help!
