### ISSUE TITLE
Document for multiple java agent extension

### ISSUE THREAD

**Issue by Roiocam** [open-telemetry/opentelemetry-java-instrumentation#6132]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

i'm using more than one java agent for my application, include community and my own agent jar.

In order not to introduce multiple dependencies like `ByteBuddy` or `ASM`, I upgrade my agent to OTEL extension.

My intuition is based on Java agent parameters

My intuition is to refer to the parameter configuration of javaagent, separated two jar by `,` , But none of them work.

So i check the source of this project. For `io.opentelemetry.javaagent.tooling.ExtensionClassLoader`, which loads agent jars, there is internal logic to handle multiple agent jars, But there is no documentation on this, at least not that I could find.

I was more than willing to contribute, so I submitted documentation describing this capability

**Describe the solution you'd like**

push an MR

**Describe alternatives you've considered**

Please let me know if the documentation exists and close this issue

**Additional context**

**Comment by laurit** [comment]
Resolved with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6133
