### ISSUE TITLE
Debug log error

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#6139]
Recently when i heard this project add some new features and do some improves, i merged the latest commit to my project. And then i find my log cannot output as usual.It can only output info logs!!!
I spent some time to find solutions, i found that when i add this arg "-Dio.opentelemetry.javaagent.slf4j.simpleLogger.defaultLogLevel=DEBUG" to VM option, it can output debug log normally.
I debug the code and find DefaultLoggingCustomizer has do the init,but it seems not work in corrent way. What happens about it ?

this is my args before "-javaagent:opentelemetry-javaagent.jar  -Dotel.metrics.exporter=prometheus -Dotel.exporter.prometheus.port=9464 -Dotel.exporter.prometheus.host=0.0.0.0 -Dotel.instrumentation.runtime-metrics.experimental-metrics.enabled=true -Dotel.javaagent.debug=true"

**Comment by laurit** [comment]
Resolved in https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.15.0

**Comment by xiangtianyu** [comment]
I've merge this version and reviews the bugfix commit. It can work, but i can't understand why? The code seems similarly. Could you give me some info about it ?

**Comment by xiangtianyu** [comment]
> The commit that fixes it is [9c2e508](https://github.com/open-telemetry/opentelemetry-java-instrumentation/commit/9c2e508e205902f0a5302ae821dbd34d6d0b93fa) Basically the problem is in initilization order, logging should not be used before default log level is set. `SafeServiceLoader` initializes a logger which caused the issue.

Thanks for your answer! It really resolve my doubts!
