### ISSUE TITLE
OTel Javaagent debug log missing statements

### ISSUE THREAD

**Issue by ryandens** [open-telemetry/opentelemetry-java-instrumentation#6148]
**Describe the bug**
Hi, I noticed when starting to use OTel Javaagent 1.14.0 that some information was no longer being printed in the debug log. Notable things missing included debug logs from :
- `io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder` which printed out effective configuration
- `InstrumentationLoader` which printed instrumentation modules loaded via SPI 
- `AgentInstaller$TransformLoggingListener` which prints out information about classes transformed by instrumentation modules

**Steps to reproduce**
- clone https://github.com/ryandens/otel-grpc-context, a convenient reproducer project i already had setup
- run `./gradlew -p app run` with JDK 11. This task is configured to enable OTel debug logs (see [here](https://github.com/ryandens/otel-grpc-context/blob/main/app/build.gradle.kts#L63))
- See that very little debug information is outputted (logging span exporter outputs is all i noticed)
- Downgrade OTel to 1.13.1 to demonstrate that this worked previously. To downgrade, uncomment [app/build.gradle.kts#L23](https://github.com/ryandens/otel-grpc-context/blob/main/app/build.gradle.kts#L23) and comment out [app/build.gradle.kts#L24](https://github.com/ryandens/otel-grpc-context/blob/main/app/build.gradle.kts#L24)

**What did you expect to see?**
I expected to see debug logs from `AutoConfiguredOpenTelemetrySdkBuilder`, `InstrumentationLoader` and `AgentInstaller$TransformLoggingListener`

**What did you see instead?**
Only debug logs from the `LoggingSpanExporter`

**What version are you using?**
1.14.0

**Environment**
Compiler: 11.0.15 (Eclipse Adoptium 11.0.15+10)
OS: Mac OS X 10.15.7 x86_64
Runtime (if different from JDK above): same
OS (if different from OS compiled on): same

**Additional context**
I wasn't sure if this was an intended change. I looked through the release notes and didn't see anything immediately obvious, so apologies if this is working as intended!

**Comment by laurit** [comment]
It is a know bug that has already been fixed. You can still enable debug logging with `-Dio.opentelemetry.javaagent.slf4j.simpleLogger.defaultLogLevel=DEBUG`

**Comment by ryandens** [comment]
Thank you!
