### ISSUE TITLE
Make artefacts from "depends-on-otel-java-snapshot" branch available for download

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#616]
Just a strawman's idea, don't feel too strongly about it.

I usually work on code for the OTel collector by targeting an agent instrumented app at it and seeing how things show up. Recently, there was a breaking change in OTLP proto, so until that propagates through SDK and agent, the agent can't be used with the master collector, which is where I'd do development. Until it does, I'm praying that I can keep the base of my changes to the commit before this breaking change happened without merge conflicts.

Until GA, any thoughts on providing an exporter artifact that points to snapshot protos? It's probably pretty complicated, so maybe not worth it, but wanted to throw it out there.

**Comment by trask** [comment]
have you seen the `depends-on-otel-java-snapshot` branch? https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/depends-on-otel-java-snapshot

the idea is we can do development work on that branch to keep up to date with otel-java snapshot

we have a nightly builds running on that branch: https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation?branch=depends-on-otel-java-snapshot

it looks like that build is only running tests, but if we had it run the `build` job, you could download artifacts from CircleCI, e.g. https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1624/workflows/ae64d8cf-d97a-47d9-a602-2fdc11a15b95/jobs/12660/artifacts

**Comment by anuraaga** [comment]
Ah didn't notice that branch! Yeah it seems like if it ran build that'd be good enough for this issue. Don't think it has to go to maven

**Comment by iNikem** [comment]
@anuraaga do I understand it correctly, that after the discussion above this issue really means building actual artifacts from `depends-on-otel-java-snapshot` branch during nightly builds?

**Comment by anuraaga** [comment]
Yup think that's right

**Comment by trask** [comment]
@anuraaga can we close close this now in favor of #728?

**Comment by anuraaga** [comment]
Yup
