### ISSUE TITLE
Not same SpanContext in try catch block

### ISSUE THREAD

**Issue by Eivense** [open-telemetry/opentelemetry-java-instrumentation#6186]
**Describe the bug**
I get the spanId with `Span.current().getSpanContext().getSpanId()` it log `95e031a5f0bd04e5`
but the spanId with  `span.getSpanContext().getSpanId()` it log `8da75a79d9288b71`
`95e031a5f0bd04e5` is the parent span spanId
And logback MDC also log the spandId with `95e031a5f0bd04e5 `
![image](https://user-images.githubusercontent.com/15178326/174219484-d1097323-f8a0-49f7-b91a-688212d12935.png)

After i debug the code i found two different SpanConext with two different spanId
![image](https://user-images.githubusercontent.com/15178326/174219883-6fc4d345-0828-4146-85ac-144412981c87.png)

**Steps to reproduce**
Here is my code
```
private int span() {
        int value = random.nextInt(200);
        Span span = tracer.spanBuilder("Span").startSpan();
        try (Scope scope = span.makeCurrent()) {
            log.info("span with random:{}", value);
            throw new RuntimeException("aaaa");
        }catch (Throwable throwable){
            log.info("current,spanId:{}",Span.current().getSpanContext().getSpanId());
            log.info("span,spanId:{}",span.getSpanContext().getSpanId());
            log.error(throwable.getMessage());
            span.setStatus(StatusCode.ERROR, throwable.getMessage());
            span.recordException(throwable);
        }
        finally {
            span.end();
        }
        return value;
    }
```
**What did you expect to see?**
same SpanContext in the try catch block

**What did you see instead?**
different SpanContext with different spanid

**What version are you using?**
java agent 1.14.0

**Environment**
springboot 2.7.0

**Comment by laurit** [comment]
This is how try with resource works, see https://docs.oracle.com/javase/specs/jls/se8/html/jls-14.html#jls-14.20.3.2 If you'd like different behaviour then don't use try with resources or stick a try catch block inside try with resources.
