### ISSUE TITLE
Examine possibility of starting all spans after routing decision

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#6188]
Currently, `http.route` or a derived span name cannot be used in sampling. This does seem quite limiting as route would probably be a useful, if not the most useful, attribute to sample on.

https://github.com/open-telemetry/opentelemetry-java/pull/4498#issuecomment-1159030378

We did put a lot of effort into `RouteHolder`, etc, but I wonder if we ever considered starting spans only after route is known, or alternatively having a `StartTimeHolder` to keep the current timings but still create the span after routing. Or perhaps we just keep a `SpanBuilder` in context until the route is ready.

**Comment by trask** [comment]
do we know if this is mostly a Java instrumentation problem, or if the popular web frameworks in other languages also suffer this problem (routing decision occurring in a different component / disconnected from the request start)?

one downside to holding the span start is that we would lose correlation with any logs which occur between request start and routing decision (I've seen people enable logging in their web framework and expect those logs to be correlated).

**Comment by mateuszrzeszutek** [comment]
> one downside to holding the span start is that we would lose correlation with any logs which occur between request start and routing decision (I've seen people enable logging in their web framework and expect those logs to be correlated).

Potentially, it's more than just logs: e.g. there could be some custom servlet `Filter` code that needs to be traced before Spring controller gets matched. Or, in case of JAX-RS, you might have nested controller annotations and only want to choose the last one (but obviously you don't know which one is the last before the request ends).

**Comment by trask** [comment]
potentially related: https://github.com/open-telemetry/opentelemetry-specification/pull/3678#discussion_r1340405088

> Jaeger supports a way to defer a sampling decision until the first child span starts, which means some AddLinks could be considered before the sampling decision

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
