### ISSUE TITLE
Need help in collecting server metrics - Disk/CPU

### ISSUE THREAD

**Issue by Godwinmoses93** [open-telemetry/opentelemetry-java-instrumentation#6197]
Hi All,

I am new to open-telemtry, I am trying to collect a Linux machines metrics such as CPU/Disk/Memory to displace in cloudwatch.
I have installed open-telemetry collector in my Linux AWS instance and tried to run the docker container provided in the example. I was able to see application metrics pulled in, someone please help me how to collect the Infrastructure metrics, if there is any example config.yaml that would be helpful. Thanks in advance.

**Comment by trask** [comment]
hi @Godwinmoses93! I'd suggest posting in https://github.com/open-telemetry/opentelemetry-collector for help with collector configuration.

**Comment by Godwinmoses93** [comment]
@trask Is there any option to Chat in github, Because I am new to this as well. I am trying to collect metric details using AWS managed open-telemetry, kindly suggest if I can do it with open-telemetry collector or any other open-telemetry version I need to use ?

**Comment by trask** [comment]
you can join the Slack channels, check out https://github.com/open-telemetry/community#discussions and https://github.com/open-telemetry/community#special-interest-groups (for specific channels like #opentelemetry-collector)
