### ISSUE TITLE
Restructure instrumentation "-common" modules before publishing?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#621]
We have the following instrumentation "-common" modules:

* elasticsearch-rest-common
  * no dependency on bytecode
* elasticsearch-transport-common
  * no dependency on bytecode
* hibernate-common
  * has dependency on `ContextStore`
* mongo-common
  * no dependency on bytecode
* play-ws-common
  * has bytecode instrumentation
* servlet-common
  * no dependency on bytecode

The ones that do not depend on bytecode will (eventually) be moved outside of the `io.opentelemetry.instrumentation.auto` groupId, so they can be used/shared by manual instrumentation.

I'm guessing these will still manual instrumentation "-common" modules that are reused by manual instrumentation targeting different library versions.

I think it's ok if we publish these instrumentation "-common" modules under `io.opentelemetry.instrumentation.auto` for now, and move them out as we build out the corresponding manual instrumentation.

**Comment by iNikem** [comment]
@trask I am not sure I understand what exactly do you propose to do in this issue :)

**Comment by trask** [comment]
Yeah, it's not clear is it.

I think I started writing it thinking to propose that we move the `-common` modules that don't have bytecode dependencies over to `instrumentation-core` early so that they wouldn't be published unnecessarily under the `io.opentelemetry.instrumentation.auto` groupId.

But then it seems talked myself out of it by the end 😭.

I'm good to close this.
