### ISSUE TITLE
A feature to enable tracing from main itself

### ISSUE THREAD

**Issue by kushal-ti** [open-telemetry/opentelemetry-java-instrumentation#6237]
**Is your feature request related to a problem? Please describe.**
Normally, tracing starts in a web server, running some kind of framework like spring, tracing starts from an incoming or outgoing request (either http request or a database call, etc). 
I have an application which periodically schedules multiple containers of the same console app, all of whom push their logs to the same sink. I need a way to separate out the logs by which container produced them.
Instrumenting the logs with an individual trace/span id will accomplish this, but for that i need the agent to start instrumenting from the main of the application.

**Describe the solution you'd like**
Auto instrumentation of agent starts in the beginning of the main method 

**Describe alternatives you've considered**
I know i can just add manual instrumentation in the code with the otel SDK, but that's an alternative i'd like to avoid if possible. It's a legacy project and making changes to the dependencies might break things in unexpected ways.

**Comment by kushal-ti** [comment]
I should also note that, i specifically want trace ids because each console app also makes some outbound HTTP requests to other services, and i would like it if the trace id that is generated and propagated in that outbound request could also be observed in the console app logs.

**Comment by trask** [comment]
hi @kushal-ti! is adding `@WithSpan` annotation to your main method an option?

**Comment by trask** [comment]
linking in duplicate https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/6238

**Comment by mateuszrzeszutek** [comment]
Alternatively, you can use the [`otel.instrumentation.methods.include`](https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/#creating-spans-around-methods-with-otelinstrumentationmethodsinclude) configuration property to add a span without any code changes.
