### ISSUE TITLE
Unable to build on M1 Mac

### ISSUE THREAD

**Issue by zackman0010** [open-telemetry/opentelemetry-java-instrumentation#6242]
The ./gradlew assemble command fails when running on an M1 Mac.
```
Execution failed for task ':instrumentation:grpc-1.6:testing:generateProto'.
> Could not resolve all files for configuration ':instrumentation:grpc-1.6:testing:protobufToolsLocator_protoc'.
   > Could not find protoc-3.3.0-osx-aarch_64.exe (com.google.protobuf:protoc:3.3.0).
```
I did some digging, and it appears that `protoc` does not support the `osx-aarch_64` architecture until version `3.17.3`. We don't use gRPC or Protobuf in our development, so I didn't know if just updating the compiler version [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/conventions/src/main/kotlin/otel.protobuf-conventions.gradle.kts#L12) would be a breaking change.

EDIT: Same issue also exists with the other artifact in the same [file](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/conventions/src/main/kotlin/otel.protobuf-conventions.gradle.kts#L16), `protoc-gen-grpc-java`. Current version is `1.6.0`, does not support M1 Mac until `1.42.1`. I'm much more certain this one is a breaking change, so I'm not sure how to proceed from there.

**Comment by trask** [comment]
hi @zackman0010! `protoc-gen-grpc-java` is only used by the grpc instrumentation testing module, so would not be a breaking change (from API perspective at least), feel free to send PR with the update and we'll see if CI complains 😄

**Comment by zackman0010** [comment]
I went ahead and created a PR #6244 to show what versions I had to edit to get a successful compile. I only edited the gRPC version in the testing environment, the library and instrumentation environments remain on 1.6.

**Comment by zackman0010** [comment]
I would, but unfortunately any PR I submit is going to get stuck in the same CLA limbo as my existing PR.

**Comment by XSAM** [comment]
Got a similar error:

```
* What went wrong:
Execution failed for task ':instrumentation:grpc-1.6:testing:generateProto'.
> Could not resolve all files for configuration ':instrumentation:grpc-1.6:testing:protobufToolsLocator_grpc'.
   > Could not find protoc-gen-grpc-java-1.6.0-osx-aarch_64.exe (io.grpc:protoc-gen-grpc-java:1.6.0).
     Searched in the following locations:
         https://repo.maven.apache.org/maven2/io/grpc/protoc-gen-grpc-java/1.6.0/protoc-gen-grpc-java-1.6.0-osx-aarch_64.exe
```
