### ISSUE TITLE
Move WithSpan annotation to this repository

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#6245]
As discussed in SIG meetings and in https://github.com/open-telemetry/opentelemetry-java/pull/4260.

What do you think of:

* `opentelemetry-instrumentation-annotations`
* Rename `opentelemetry-instrumentation-api-annotation-support` to `opentelemetry-instrumentation-annotations-support`

Another option is to keep the `-api` in the names:

* `opentelemetry-instrumentation-api-annotations`
* Keep current name of `opentelemetry-instrumentation-api-annotation-support`

**Comment by mateuszrzeszutek** [comment]
> What do you think of:
> 
> * `opentelemetry-instrumentation-annotations`
> * Rename `opentelemetry-instrumentation-api-annotation-support` to `opentelemetry-instrumentation-annotations-support`

👍

**Comment by trask** [comment]
Steps:

- [ ] Move the annotations to this repo
- [ ] Rename `opentelemetry-instrumentation-api-annotation-support` to `opentelemetry-instrumentation-annotations-support`
- [ ] Add support in auto-instrumentation for the new package names (while maintaining support for the old package names)

**Comment by mateuszrzeszutek** [comment]
Done a while ago
