### ISSUE TITLE
What to do with instrumentation-api Config

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#6250]
follow-up from https://github.com/open-telemetry/opentelemetry-java/issues/4563#issuecomment-1171884624

some options
* only allow programmatic configuration in library instrumentation for now, and move `Config` to javaagent-extension-api
* keep `Config` in instrumentation-api as-is
* move `Config` to an internal package

(+ maybe renaming `Config` to `InstrumentationConfig` to help clarify it's only used for instrumentation configuration and not for sdk configuration)

**Comment by mateuszrzeszutek** [comment]
> * only allow programmatic configuration in library instrumentation for now, and move `Config` to javaagent-extension-api

That would be my preferred solution (maybe even combined with making `InstrumentationConfig` internal) if weren't for the fact that we're still using `Config` internally in the instrumenter API: like [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/SpanSuppressionStrategy.java#L79) or [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/SupportabilityMetrics.java#L39).
Maybe we could replace these internal usages with a very simple `getSysPropOrEnvVar` internal utility method in `instrumentation-api`? With the exception of the suppression strategy, all other config options are debugging utilities, and I think we don't really need to care about the SPI or file config for these.

**Comment by anuragagarwal561994** [comment]
@trask how to use and get the configurations within extension InstrumentationModule?

**Comment by mateuszrzeszutek** [comment]
You can use [`InstrumentationConfig`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/bootstrap/internal/InstrumentationConfig.java) -- it offers roughly the same functionality as `Config`, but it's only available in the javaagent instrumentations. It's still in an internal package, so we cannot commit to its stability, but I believe that accessing the configuration in javaagent instrumentations will always be a necessary feature, so I don't think it's ever going away -- we probably might rename it at some point in the future (although we have no such plans right now).

**Comment by anuragagarwal561994** [comment]
Yes I thought for the same. Just because it had internal packaging I thought if it would be right to use the same.
