### ISSUE TITLE
Need the support of concurrent queue

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#6276]
Concurrent queue such as BlockingQueue, ConcurrentLinkedQueue will cause thread switch, and trace will not spread in correct way. I think we may need an new instrumentation to solve this?

**Comment by mateuszrzeszutek** [comment]
Hey @xiangtianyu ,
I think this is a good case for manual instrumentation. Java `BlockingQueue` only offers polling API, and correctly passing context through polling is pretty much impossible. Our kafka-clients consumer instrumentation is the proof of that: it even has slightly better API than a plain `BlockingQueue`, but we've still had numerous issues about context leaks and broken propagation, to the extent that we've decided to additionally instrument higher-level consumer libraries, like spring-kafka or vertx-kafka.
Passing context correctly to a polling consumer requires accurate knowledge of how the queue is used within the instrumented application; and the javaagent has no way of knowing that.

Try adding the current context to the passed message:

```java
class MessageWithContext<T> {
  T message;
  Context context;
}

queue.offer(new MessageWithContext<>(message, Context.current());
```

and then manually make it current in the place that takes it off the queue:

```java
var messageWithContext = queue.poll();
try (Scope scope = messageWithContext.context.makeCurrent()) {
  // do actual processing on messageWithContext.message
}
```
