### ISSUE TITLE
Detailed metrics about JVM Threads

### ISSUE THREAD

**Issue by shreya22-1998** [open-telemetry/opentelemetry-java-instrumentation#6279]
jvm_threads_daemon_threads
jvm_threads_states_threads
jvm_threads_peak_threads
jvm_threads_live_threads

along with thread count can we have above detailed metrics about JVM Threads.

**Comment by mateuszrzeszutek** [comment]
`jvm_threads_daemon_threads` and `jvm_threads_live_threads` are already implemented [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/Threads.java) as `process.runtime.jvm.threads.count` with a boolean `daemon` attribute.
 We're not planning to implement `jvm_threads_states_threads`, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7636 for the reason why.
`jvm_threads_peak_threads` could be easily computed using your observability backend by doing sth like `max(process.runtime.jvm.threads.count)`
