### ISSUE TITLE
Add JVM Buffer, JVM GC Metrics

### ISSUE THREAD

**Issue by shreya22-1998** [open-telemetry/opentelemetry-java-instrumentation#6280]
jvm_buffer_memory_used
jvm_buffer_total_capacity
jvm_buffer_count

jvm_gc_memory_promoted
jvm_gc_memory_allocated
jvm_gc_live_data_size
jvm_gc_max_data_size
jvm_gc_overhead

**Comment by Samudraneel24** [comment]
Can I have this issue assigned to me? Thanks.

**Comment by Samudraneel24** [comment]
Oh, I had missed this PR. My main intention was to work on adding more GC metrics using the GC notification events, and looks like this PR already addresses that.

**Comment by mateuszrzeszutek** [comment]
Both the [buffer pool](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/BufferPools.java) and [GC](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/GarbageCollector.java) metrics were implemented; closing.
