### ISSUE TITLE
Apply net.peer.name, net.peer.ip and peer.service consistently

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#629]
It looks like there are ~10 places that set `net.peer.name` and `net.peer.ip`.

It would be good if we can funnel all of those through a central method to make sure that we:
* Don't set `net.peer.name` if it's the same as `net.peer.ip`
* Apply `peer.service` mapping

**Comment by heyams** [comment]
Please assign this task to me.
