### ISSUE TITLE
How to get parentSpanContext from agent span?

### ISSUE THREAD

**Issue by sharajava** [open-telemetry/opentelemetry-java-instrumentation#6290]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I use OTel agent propagating span context between applications. 
I NEED to get caller's spanId on server side. 
I CAN get current span when request from caller comes in by 

`Span span = Span.current();`

There is a parentSpanContext in agent span. The parentSpanContext is just what I need, but I CAN NOT get it by API.

![image](https://user-images.githubusercontent.com/4413362/177949286-417a7b78-41a8-42fe-93f0-b3a052949b95.png)

**Describe the solution you'd like**

I NEED a way to get the parentSpanContext. Or, any other way? Thanks.

**Describe alternatives you've considered**

**Additional context**

**Comment by laurit** [comment]
As far as I can tell you are trying to get access to the remote span id. It might be easier to extract it from the request. If you are using servlets then you could try something like
```java
          Context remoteContext = GlobalOpenTelemetry.get().getPropagators().getTextMapPropagator().extract(Context.root(), request,
              new TextMapGetter<HttpServletRequest>() {
                @Override
                public Iterable<String> keys(HttpServletRequest carrier) {
                  return Collections.list(carrier.getHeaderNames());
                }

                @Nullable
                @Override
                public String get(@Nullable HttpServletRequest carrier, String key) {
                  return carrier.getHeader(key);
                }
              });
          String spanId = Span.fromContext(remoteContext).getSpanContext().getSpanId();
```

**Comment by sharajava** [comment]
THANKS!

I was just wondering that how spans be linked by tracing logs. For example, I got tracing logs by -Dotel.traces.exporter=logging through OTel agent:

![image](https://user-images.githubusercontent.com/4413362/177979642-fadd1b54-a180-4c84-9bbc-2ec7a612c234.png)

Collecting such logs, how could I known 'test'(5be1612d8f1420a4) is called by 'verify'(b0291326b6553b12)?

I was trying to print parent spanId into logs to link them like this:

![image](https://user-images.githubusercontent.com/4413362/177980848-c99cd6b0-edda-45f1-855e-bca33aaab440.png)

Maybe I have some misunderstanding on this. If I don't need to link span manually, I think I don't need to get parent span either. 

It's nice to get some guide from you. Thanks!

**Comment by laurit** [comment]
You could write your own version of logging span exporter. Exporters operate on [SpanData](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/data/SpanData.java) that exposes parent span context.

**Comment by laurit** [comment]
Feel free to reopen if you have more questions.
