### ISSUE TITLE
Collect RabbitMQ message headers

### ISSUE THREAD

**Issue by drewhammond** [open-telemetry/opentelemetry-java-instrumentation#6293]
**Is your feature request related to a problem? Please describe.**

We store valuable identifiers in RabbitMQ (AMQP 0-9-1) message headers. In Elastic APM, these headers are collected as attributes in spans, but in OpenTelemetry they are not.

**Describe the solution you'd like**

We'd like the ability to toggle the collection of these message headers so that they can be included in spans. As a nice-to-have, we'd like the list of collected headers to be configurable.

**Describe alternatives you've considered**
We have not found an attractive alternative with only using automatic instrumentation.

**Comment by mateuszrzeszutek** [comment]
Looks really similar to: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5238
I guess it could be implemented as a generic messaging headers-extracting-thing (perhaps similar to how we're extracting HTTP headers)
