### ISSUE TITLE
Rename the `instrumentation-api-semconv` module into `instrumentation-api-incubator`

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#6310]
My understanding from following core repo discussions is that Java modules doesn't support when there are shared (leaf) package names between multiple artifacts.

If this is the case, maybe for simplicity we could just put everything in semconv artifact under `io.opentelemetry.instrumentation.api.semconv`?

**Comment by mateuszrzeszutek** [comment]
Since we want to move these classes to `instrumentation-api` when they (and their spec) stabilize, should we use `io.opentelemetry.instrumentation.api.incubator` or something similar?

**Comment by trask** [comment]
I think this is a great idea, and will help with my concern in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6191#pullrequestreview-1035214753

**Comment by laurit** [comment]
To me changing the package of semconv classes once they are stabilized seems a bit risky. For example consider that you have an extension that uses something from semconv and has compileOnly dependency to `opentelemetry-instrumentation-api-semconv`. Changing the package would break the extension that uses the class. I guess the extension could break anyway because of spec updates or us refactoring something, so maybe this is something that the extension authors have to keep an eye on.

**Comment by trask** [comment]
copy all of -api-semconv into a new module -api-incubator and deprecate all of -api-semconv?

I agree that it's not ideal to have to change the package name when we finally move it to the stable artifact, but since we will be doing these piecemeal as semantic conventions stabilize instead of stabilizing an entire artifact, it seems less bad

**Comment by trask** [comment]
@laurit and I discussed in SIG meeting and came up with this alt proposal:

* rename -api-semconv artifact to -api-incubator
* keep the `.http`, `.db` semantic convention package names as-is, and plan to move an entire package over to -api once the semantic convention stabilizes for smooth transition, and should avoid Java 9 module issues
* create `.incubator` package for other stuff, e.g. #6191 which we think probably should go through some kind of spec before stabilizing anyways
* after moving a package over to stable artifact, e.g. `.http`, if we need any further "incubator" classes for it, put them under `.incubator.http` going forward (so not using the `.incubator` package would be a one-time thing per semantic convention

**Comment by mateuszrzeszutek** [comment]
We could actually do this in the 2.0 release; in 2.0 we'd have `instrumentation-api-incubator` with the new packages, the 1.x line would still have the old artifact/package names (to. reduce thrash)

**Comment by mateuszrzeszutek** [comment]
Depends on https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9925 -- this issue can be picked up after it's merged.
