### ISSUE TITLE
How to spring instrumentation with only java agent

### ISSUE THREAD

**Issue by yingziisme** [open-telemetry/opentelemetry-java-instrumentation#6330]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring

**Comment by trask** [comment]
hi @yingziisme! there is a lot of spring instrumentation in the javaagent, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks

**Comment by yingziisme** [comment]
> 

hello, how to trace Feign or RestTemplate with opentelemetry-javaagent.jar?

**Comment by mateuszrzeszutek** [comment]
Hey @yingziisme ,
While the agent does not instrument Spring `RestTemplate` or openfeign (yet -- there's an open PR about this one) directly, it instruments all HTTP clients that are used internally by either of these (e.g. `HttpURLConnection`, OkHttp, Apache HTTP clients, etc). Try it out, all the HTTP client telemetry should already be there.

**Comment by yingziisme** [comment]
> 

right. I use http client for tracing now. but there is no remote service name by this way.

**Comment by laurit** [comment]
Feel free to reopen if you have more questions.
