### ISSUE TITLE
Jaeger gRPC exporter memory leak

### ISSUE THREAD

**Issue by tinnapat** [open-telemetry/opentelemetry-java-instrumentation#6337]
**Describe the bug**
Jaeger gPRC exporter keep using more and more memory when backend Jaeger collector is down.

**Steps to reproduce**
Using OpenTelemetry Java Agent with spring-petclinic application and configure gRPC exporter
```
export OTEL_TRACES_EXPORTER=jaeger
export OTEL_EXPORTER_JAEGER_ENDPOINT=http://xxx:14250
export OTEL_PROPAGATORS=b3multi,jaeger
export OTEL_METRICS_EXPORTER=none
export OTEL_SERVICE_NAME=spring-petclinic

java -javaagent:opentelemetry-javaagent.jar -jar target/*.jar
```
We start the application and then use jmeter to load test it using 100 concurrent thread continuously and use jmap to observe memory usage and allocation. After a short while, we kill the Jaeger collector.

Using jmap, I observe that the OpenTelemetry classes having more instances and consumer more memory 

```
jmap -histo 66487 | grep opentelemetry.exporter.jaeger
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   3:       3382817      162375216  io.opentelemetry.exporter.jaeger.KeyValueMarshaler
  14:        727046       23265472  io.opentelemetry.exporter.jaeger.TimeMarshaler
  17:        363523       17449104  io.opentelemetry.exporter.jaeger.SpanMarshaler
  22:        329902       10556864  io.opentelemetry.exporter.jaeger.SpanRefMarshaler
  28:        363523        5816368  [Lio.opentelemetry.exporter.jaeger.LogMarshaler;
  54:           711        1465472  [Lio.opentelemetry.exporter.jaeger.SpanMarshaler;
 255:          2056          32896  io.opentelemetry.exporter.jaeger.KeyValueMarshaler$$Lambda$1222/0x000000080155a700
 360:           711          17064  io.opentelemetry.exporter.jaeger.BatchMarshaler
 361:           711          17064  io.opentelemetry.exporter.jaeger.PostSpansRequestMarshaler
 362:           711          17064  io.opentelemetry.exporter.jaeger.ProcessMarshaler
2484:             5            120  io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter$$Lambda$1221/0x0000000801558930
5370:             1             24  io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter
6575:             1             16  io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporter$$Lambda$1220/0x0000000801558468
6576:             1             16  io.opentelemetry.exporter.jaeger.JaegerGrpcSpanExporterBuilder$$Lambda$159/0x0000000800d01398
```
Above output is after we run the application for 1 hour, OpenTelemetry Jaeger exporter already consume > 160 MB and it keep continuing.

**What did you expect to see?**
OpenTelemetry should not keep consuming more memory in case the Jaeger collector is down.

**What did you see instead?**
OpenTelemetry keep consuming more memory in case the Jaeger collector is down.

**What version are you using?**
opentelemetry-java-instrumentation 1.15.0

**Environment**
Compiler: OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OS: MacOS

**Additional context**
N/A

**Comment by laurit** [comment]
Could you share the heap dump? Have you tired analyzing this Eclipse Memory Analyzer or some other tool that automatically removes unreachable objects?

**Comment by tinnapat** [comment]
> Could you share the heap dump? Have you tired analyzing this Eclipse Memory Analyzer or some other tool that automatically removes unreachable objects?

Hi. I haven't done that yet. What I did was looking at the jvm memory graph in visualVM and see that it consume more and more memory and GC can not clear the memory used. Then I used jmap to see the number of object and memory used. 

I will try to reproduce it again and get the heap dump.
