### ISSUE TITLE
Have separate library instrumentation entry points for client/server, producer/consumer

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#6361]
**Is your feature request related to a problem? Please describe.**
Some of our library instrumentations (`ArmeriaTelemetry`, `GrcpTelemetry`) contain entry points for both server and client instrumentations (or producer and consumer). Because clients and servers often have different request/response types, they cannot use the same attributes extractors -- and even if they did you might want to configure client-side extractors separately (e.g. `PeerServiceAttributesExtractor`). You _could_ introduce `addClientAttributesExtractor()`/`addServerAttributesExtractor()` methods, but these get kinda awkward and unwieldy (see HTTP headers capture in Armeria for a great example), and they prevent the possibility of extracting a common abstract telemetry builder that could be shared across all instrumentation libraries.

**Describe the solution you'd like**
Split the instrumentation library entry points into several `*Telemetry` classes if they currently implement >1 scenario.

**Additional context**
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6302#discussion_r918086207

**Comment by trask** [comment]
Resolved by 

* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12851
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12853
* https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/12852
