### ISSUE TITLE
How can I get trace id from agent?

### ISSUE THREAD

**Issue by Anricx** [open-telemetry/opentelemetry-java-instrumentation#6405]
How can I get trace id from agent? 
I have an application witch is run with javaagent, is there any way to get agent request trace id from my application?

**Comment by mateuszrzeszutek** [comment]
Hey @Anricx ,
Have you tried
```java
Span.current().getSpanContext().getTraceId()
```
?

**Comment by Anricx** [comment]
Yes, but i get '0000000000000000000000'

**Comment by Anricx** [comment]
I wrote a demo, it works, 😄, it may be some rule cause it doesn't working in my app, thx!
