### ISSUE TITLE
Better config flexibility for log4j OpenTelemetryAppender

### ISSUE THREAD

**Issue by svetsch** [open-telemetry/opentelemetry-java-instrumentation#6409]
**Is your feature request related to a problem? Please describe.**

The LogEventMapper (https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/log4j/log4j-appender-2.17/library/src/main/java/io/opentelemetry/instrumentation/log4j/appender/v2_17/internal/LogEventMapper.java) lacks of config flexibility. We should be able to specify a simple mapping for fields, at least for context attributes.

**Describe the solution you'd like**
As a first step, remove the hard-coded prefix 'log4j.context_data.' added to all ThreadContext attributes. 
We should be able to configure this prefix.
Then using a kind of mapping using regexp for example would be nice.

**Describe alternatives you've considered**
So far as a workaround, I'm using transformer in the collector to remap those attributes. But this requires a set and a delete for each key and thus requires to know all the used attributes.

**Additional context**
--

**Comment by trask** [comment]
> As a first step, remove the hard-coded prefix 'log4j.context_data.' added to all ThreadContext attributes.

This was resolved by #9536

More advanced remapping can be done in the collector as you mention, or in a delegating SpanExporter (or ideally directly in the code that is setting the MDC values in the first place).
