### ISSUE TITLE
Agent log export

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#6447]
Is the otel agent support this feature: export the instrumentation logs to collector with otlp.
or there are any other solutions?

**Comment by mateuszrzeszutek** [comment]
Hey @xiangtianyu ,
What do you mean by "instrumentation logs"? Are these logs produced by the application? Or logs produced by the agent?

**Comment by xiangtianyu** [comment]
> Hey @xiangtianyu , What do you mean by "instrumentation logs"? Are these logs produced by the application? Or logs produced by the agent?

Thanks for answer. At beginning, I want to output some log to otlp, so i import java.util.logging to record log. And then it failed to export logs to otlp. Finally, i found java.util.logging was set to "relocation", so i changed a new logger.And the problem was solved.
