### ISSUE TITLE
Opentelemetry instrumentation for java with micrometer extension is not working

### ISSUE THREAD

**Issue by anuragk-sportsbet** [open-telemetry/opentelemetry-java-instrumentation#6448]
**Opentelemetry instrumentation for java with micrometer extension is not working**

**Steps to reproduce**
https://stackoverflow.com/questions/73289647/how-to-configure-otel-collector-with-spring-app-using-micrometer-library-and-jav

**What version are you using?**
JAVA instrumentation agent: `io.opentelemetry.javaagent:opentelemetry-javaagent:1.16.0`
Micrometer extension: `opentelemetry-micrometer-1.5-1.13.0-alpha.jar`

**Environment**
Compiler: 
```
openjdk 17.0.3 2022-04-19 LTS
OpenJDK Runtime Environment Zulu17.34+19-CA (build 17.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu17.34+19-CA (build 17.0.3+7-LTS, mixed mode, sharing)
```
OS: `Mac OS Big Sur. Version: 11.5. Chip: Apple M1 `

**Additional context**
<img width="922" alt="spring-micrometer-otel-prometheus" src="https://user-images.githubusercontent.com/44419007/183621008-d21cb28b-b768-4aa9-a3cf-5196067b03bc.png">

**Comment by laurit** [comment]
@anuragk-sportsbet firstly verify whether the agent reports the expected metrics. If it does not then please create a minimal application that reproduces the issue. If it does then the problem is not in the agent which means that we won't be able to help you.

**Comment by mateuszrzeszutek** [comment]
Hey @anuragk-sportsbet ,
Have you perhaps verified whether the javaagent prometheus endpoint reports the expected metrics (what Lauri posted above)?

**Comment by mateuszrzeszutek** [comment]
Ping @anuragk-sportsbet
