### ISSUE TITLE
Inconsistent metrics naming

### ISSUE THREAD

**Issue by goto1134** [open-telemetry/opentelemetry-java-instrumentation#6479]
**Describe the bug**
Opentelemetry javaagent appends "total" postfix to counter metrics exported via prometheus endpoint.

**Steps to reproduce**
I have a spring app with grpc that uses micrometer grpc meter binder.

When I use actuator prometheus, I get the following metric `grpc_server_requests_received`.
When I turn on the opentelemetry javaagent v0.16.0 with prometheus exporter the same metric name changes to `grpc_server_requests_received_total`.
When I use opentelemetry javaagent v0.16.0 with otlp exporter to opentelemetry collector and configure prometheus exporter on the collector, the metric name becomes the same as the original one: `grpc_server_requests_received`.

**What did you expect to see?**
I expect the original metric name using javaagent prometheus exporter.

**What did you see instead?**
The metric name changed to `<name>_total` using javaagent prometheus exporter.

**What version are you using?**
`v0.16.0`

**Comment by mateuszrzeszutek** [comment]
Hey @goto1134 ,
Micrometer `PrometheusMeterRegistry` adds the `_total` suffix to counters too: https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusNamingConvention.java#L66-L69
AFAIK this is a standard naming convention for Prometheus counters (that's why the collector strips this suffix)

**Comment by goto1134** [comment]
Oh, I see. This is a default behaviour indeed.

So where is the problem in the pipeline with a collector then? In the otlp javaagent exporter or in the otel collector's prometheus exporter? Who's responsibility is to add the propper counter postfix?

**Comment by mateuszrzeszutek** [comment]
Looks like the name normalization is turned off by default in the collector: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/pkg/translator/prometheus#full-normalization
I think you should ask the collector folks if this behavior is going to be default in the future. And this should be probably added to the [prometheus exporter spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/prometheus.md) -- right now it's really vague, it doesn't say anything about instrument naming.

**Comment by goto1134** [comment]
@mateuszrzeszutek, I have another example of metric naming inconsistency. Lets look at `jvm_memory_used`. In the prometheus exporters I used it is exported as `jvm_memory_used_bytes`, but the opentelemetry javaagent does not add the data type suffix to the metric name.

**Comment by goto1134** [comment]
@mateuszrzeszutek, can you, please, provide any comments or recommendations about the metric units in the name?
`jvm_memory_used` (javaagent) vs `jvm_memory_used_bytes`(collector/any other prometheus exporter).

**Comment by trask** [comment]
hi @goto1134! can you review the specification and let us know which name you think it is supposed to be?
