### ISSUE TITLE
Documentation Improvement: Authenticate options not documented in opentelemetry-spring-boot

### ISSUE THREAD

**Issue by fbutter** [open-telemetry/opentelemetry-java-instrumentation#6493]
It would be helpful to extend the [exporter documentation of the opentelemetry-spring-boot](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/5862ace233fad5dfd7ec1cbd5cbc6760336c10cd/instrumentation/spring/spring-boot-autoconfigure) with the information how authorization is configured.

**Comment by fbutter** [comment]
Thank you. I am looking for documentation on how to set the api key or bearer token, so the application can authorize against the monitoring backend.

**Comment by trask** [comment]
hi @fbutter! we definitely need help here with the spring boot starter documentation, if you are able to figure this out it would be great if you can submit a PR to update the documentation

**Comment by trask** [comment]
> I am looking for documentation on how to set the api key or bearer token, so the application can authenticate against the monitoring backend.

this sounds like you're looking for the equivalent in the spring boot starter of autoconfigure's `OTEL_EXPORTER_OTLP_HEADERS`, which I don't think we have yet, also see #8191

**Comment by jeanbisutti** [comment]
@zeitlinger Could you please confirm that this issue can be closed

**Comment by zeitlinger** [comment]
yes, that works now :smile:
