### ISSUE TITLE
Release stable version of opentelemetry-instrumentation-annotations

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#6494]

**Comment by mateuszrzeszutek** [comment]
Do we want to wait for the metrics annotations first?

**Comment by trask** [comment]
Note: need to update `reusable-create-website-pull-request.yml` when we do this (see #6869)

**Comment by Emily-Jiang** [comment]
I would like to see the stable annotations to be released under stable as early as possible. Can this be done within the next couple of weeks as we really want to pull in the stabled version asap.

**Comment by trask** [comment]
hi @Emily-Jiang! we discussed and are going to mark this module stable in the upcoming 1.20.0 release which is scheduled for Wed, Nov 16

**Comment by Emily-Jiang** [comment]
Thank you @trask !
