### ISSUE TITLE
Tomee Server - Monolithic Application Instrumentation

### ISSUE THREAD

**Issue by chandru-kumar** [open-telemetry/opentelemetry-java-instrumentation#6514]
I'm trying to instrument the Monolithic Application Hosted in Tomee server. I have passed below arguments in Tomee Catalina Opts and getting picked while the server is starting. But I dont see any traces exported. Also I have tried enabling debug and i dont see any verbose as well.

set "CATALINA_OPTS=%CATALINA_OPTS% -Djavaagent:C:/OpenTelemetry/opentelemetry-javaagent.jar"
set "CATALINA_OPTS=%CATALINA_OPTS% -Dotel.javaagent.debug=true"
set "CATALINA_OPTS=%CATALINA_OPTS% -Dotel.resource.attributes=service.name=MyApp"
set "CATALINA_OPTS=%CATALINA_OPTS% -Dotel.traces.exporter=zipkin"

Environment
Compiler: openjdk-11.0.13.8
Tomme version: apache-tomee-plume-8.0.10
OS: Windows 

Can anyone pls help on this about what am I missing?

**Comment by laurit** [comment]
instead of `-Djavaagent` you have to use `-javaagent`

**Comment by chandru-kumar** [comment]
Can you pls let me know if this applies to all arguments as well?

**Comment by mateuszrzeszutek** [comment]
Hey @chandru-kumar ,
No, the other ones are system properties -- and you pass system properties via the `-D` flag.

**Comment by chandru-kumar** [comment]
@mateuszrzeszutek Thank you..It works.
It exports the traces and spans now.

@laurit and @mateuszrzeszutek Thanks for the quick replies.
