### ISSUE TITLE
Got error when running  `./gradlew assemble`

### ISSUE THREAD

**Issue by alalag1** [open-telemetry/opentelemetry-java-instrumentation#6527]
**Describe the bug**

Got error when running  `./gradlew assemble`

```
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\dev\projects\upstream\opentelemetry-java-instrumentation\build.gradle.kts' line: 3

* What went wrong:
An exception occurred applying plugin request [id: 'otel.spotless-conventions']
> Could not find implementation class 'Otel_spotlessConventionsPlugin' for plugin 'otel.spotless-conventions' specified in jar:file:/D:/Users/xxxx/.gradle/caches/jars-9/d59a2b6e4c8e71e9196654267a77c70d/conventions.jar!/META-INF/gradle-plugins/otel.spotless-conventions.properties.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
20 actionable tasks: 20 up-to-date

A build scan was not published as you have not authenticated with server 'ge.opentelemetry.io'.
For more information, please see https://gradle.com/help/gradle-authenticating-with-gradle-enterprise.
```

**What version are you using?**
just clone the main brunch first time and try to build it

**Environment**
Compiler: openjdk 11.0.7
OS: win10

**Comment by laurit** [comment]
Looks similar to https://github.com/gradle/gradle/issues/20830 Inspect the `conventions.jar` that is mentioned in the error message, see if it contains `Otel_spotlessConventionsPlugin.class`. If it doesn't try deleting this jar (along with the directory that contains it) or delete the whole gradle cache.

**Comment by alalag1** [comment]
> Looks similar to [gradle/gradle#20830](https://github.com/gradle/gradle/issues/20830) Inspect the `conventions.jar` that is mentioned in the error message, see if it contains `Otel_spotlessConventionsPlugin.class`. If it doesn't try deleting this jar (along with the directory that contains it) or delete the whole gradle cache.

`conventions.jar` does not contains `Otel_spotlessConventionsPlugin.class`, and I've tried to delete the whole `./gradle/cache`， but it dit not work...

**Comment by laurit** [comment]
Firstly run `./gradlew clean` or delete conventions/build directory, then delete gradle caches and then try `./gradlew assemble`

**Comment by alalag1** [comment]
> Firstly run `./gradlew clean` or delete conventions/build directory, then delete gradle caches and then try `./gradlew assemble`

LGTM, Thanks a lot!
