### ISSUE TITLE
unable to get Kafka metrics

### ISSUE THREAD

**Issue by Shivanireddie** [open-telemetry/opentelemetry-java-instrumentation#6549]
After enabling Kafka we are able to see Kafka traces but we are not getting Kafka metrics.

Is there any configurations that needs to be added to get Kafka metrics.

we are using agent approach.

**Comment by mateuszrzeszutek** [comment]
Hey @Shivanireddie ,
Kafka metrics haven't been added yet to the javaagent -- there's an open PR that implements that: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6533
They should be available from the agent in the next release.
