### ISSUE TITLE
SQL from JDBC driver has newlines stripped

### ISSUE THREAD

**Issue by GavinRay97** [open-telemetry/opentelemetry-java-instrumentation#6610]
I swapped from the OpenTracing libraries to OTEL, and in Jaeger I used to be able to view SQL queries as they were originally represented.

Something happened after the upgrade and it looks like the whitespace is no longer being preserved in the queries, making them difficult to visually debug without copy-pasting them elsewhere and formatting them 🙁 

![image](https://user-images.githubusercontent.com/26604994/190036849-cc612611-c733-4f96-86db-ec873fc74c2f.png)

Is there a setting to enable newlines?

The version I'm using is `v1.16.0-alpha`, from Quarkus' BOM

**Comment by mateuszrzeszutek** [comment]
Hey @GavinRay97 ,
The whitespace is being truncated by our query sanitizer:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/0c41743888826d1eff057d1b5cc39927f0feed91/instrumentation-api-semconv/src/main/jflex/SqlSanitizer.jflex#L402-L405
It replaces query parameters hardcoded inline with a `?` character, and is enabled by default. If you don't need query sanitization, you can disable it by setting [`otel.instrumentation.common.db-statement-sanitizer.enabled`](https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#db-statement-sanitization) to `false` - the agent will no longer modify the query in any way.
