### ISSUE TITLE
Opentelemetry-k8s-sidecar agent request

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-java-instrumentation#6612]
**Is your feature request related to a problem? Please describe.**
K8S platform
A clear and concise description of what the problem is.
Need to deploy as k8s sidecar 

**Describe the solution you'd like**
Use sidecar replace agent to capture trace

**Describe alternatives you've considered**

**Additional context**

**Comment by mateuszrzeszutek** [comment]
Hey @sweetxiaodai ,
Perhaps the [OpenTelemetry Operator for K8s](https://github.com/open-telemetry/opentelemetry-operator#opentelemetry-auto-instrumentation-injection) could fit your needs -- the javaagent itself is not a standalone executable application, and cannot be deployed as a sidecar by itself.
