### ISSUE TITLE
Update docs for 0.6.0 release

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#663]
* New artifact name `opentelemetry-javaagent-all`
  * README.md
  * CONTRIBUTING.md
* New snapshot repository location: https://oss.jfrog.org/artifactory/oss-snapshot-local/io/opentelemetry/instrumentation/auto/opentelemetry-javaagent/
  * CONTRIBUTING.md

**Comment by anuraaga** [comment]
New env variables too I think

I case it helps,

https://github.com/aws-samples/aws-xray-sdk-with-opentelemetry-sample/commit/7cab8ad33e12df408e9f3211e59bbcd30f9f45b2
