### ISSUE TITLE
Opentelemetry agent cannot run with alibaba nacos client

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-java-instrumentation#6631]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem
Nacos client run with the opentelemetry agent has errors

POST http://xx.xx.xx.xx:xx/nacos/v1/cs/configs/listener
has errors

**Describe the solution you'd like**
Service cannot registered to nacos

**Describe alternatives you've considered**

**Additional context**

**Comment by mateuszrzeszutek** [comment]
Hey @sweetxiaodai ,
Can you provide some more details about your issue? What exactly are the errors that you're experiencing, how does the behavior differ from running the app without javaagent? What version of the javaagent are you using, what is your javaagent configuration? Can you provide a repro scenario?

**Comment by sweetxiaodai** [comment]
![278658C9-BC81-457A-823E-3EC992D79B3E](https://user-images.githubusercontent.com/90817719/191151164-94e1504b-f49b-4c6b-871f-c2a95d20d84b.png)
There is a API exposed by Nacos server has been impacted, please check the screenshots

**Comment by sweetxiaodai** [comment]
It is hard to reproduce the issue, and the error didn't occur after we changed to optelemetry operator, so close this one.
