### ISSUE TITLE
Add jvm memory and thread metric

### ISSUE THREAD

**Issue by wzy531a** [open-telemetry/opentelemetry-java-instrumentation#6638]
jvm memory metric in runtime-metric only collect memoryPool, refer to [splunk otel agent](https://docs.splunk.com/Observability/gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.html#memory-metrics) jvm memory metric:
p.r.jvm.memory.init
p.r.jvm.memory.max
p.r.jvm.memory.used
p.r.jvm.memory.committed

[thread](https://docs.splunk.com/Observability/gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.html#thread-metrics):
p.r.jvm.threads.live(Already exists)
p.r.jvm.threads.daemon
p.r.jvm.threads.peak
p.r.jvm.threads.states

About memory metric, I support [Add JVM implementation information and memory semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/pull/2777), use p.r.j.memory.pool.* and  p.r.j.memory.* to distinguish.

**Comment by mateuszrzeszutek** [comment]
Hey @wzy531a ,
With regards to memory metrics: [`MemoryPools`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/MemoryPools.java) and [`BufferPools`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/BufferPools.java) offer pretty much the same information as Splunk's memory metrics (except the first two, these are a part of the memory profiling feature).
About the thread metrics: #6635 implements the daemon thread counter; the other two metrics are still not defined though.

**Comment by wzy531a** [comment]
> Hey @wzy531a , With regards to memory metrics: [`MemoryPools`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/MemoryPools.java) and [`BufferPools`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/BufferPools.java) offer pretty much the same information as Splunk's memory metrics (except the first two, these are a part of the memory profiling feature). About the thread metrics: #6635 implements the daemon thread counter; the other two metrics are still not defined though.

Both [Splunk](https://docs.splunk.com/Observability/gdi/get-data-in/application/java/configuration/java-otel-metrics-attributes.html#jvm-metrics) and [Skywalking](https://github.com/apache/skywalking-data-collect-protocol/blob/master/language-agent/JVMMetric.proto) provide detailed metrics for memory and threads. So I think these metrics are necessary for memory and thread analysis.
