### ISSUE TITLE
Update attribute key of rocketmq's message tag

### ISSUE THREAD

**Issue by aaron-ai** [open-telemetry/opentelemetry-java-instrumentation#6676]
Since the [semantic convetions of rocketmq](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#apache-rocketmq) has been merged into [opentelemetry-specification](https://github.com/open-telemetry/opentelemetry-specification), the attribute key of rocketmq's message tag should be updated.

**Comment by sweetxiaodai** [comment]
Is there any one could tell me does the java-agent is compatible for RocketMQ 5.x?
