### ISSUE TITLE
Enhance  Attribute "messaging.url" 

### ISSUE THREAD

**Issue by Running-Li** [open-telemetry/opentelemetry-java-instrumentation#6678]
**Is your feature request related to a problem? Please describe.**
    "messaging. url" is an attribute that describes the connection string in Messaging System. [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#messaging-attributes)
But, it is unrealized until now. 
In my scene, Spans created by opentelemetry-java-instrumentation are used to graph the server-map which describes the dependencies between services.  So far The Node indicated Messaging System is grouped by topic. actually, It will group by broker's cluster address and topic. The broker's cluster address can be queried by the attribute "messaging.url" reported by opentelemetry-java-instrumentation. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
Clearly and concisely describe any alternative solutions or features you've considered.

**Additional context**

**Comment by trask** [comment]
`messaging.url` was removed from the specification in https://github.com/open-telemetry/opentelemetry-specification/pull/2957
