### ISSUE TITLE
What to do with the opentelemetry-javaagent.version file?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#669]
It seems to be unnecessary clutter in the jar root.

The version is already easily discoverable by people who want to find it via `META-INF/MANIFEST.MF`.

Proposal 1: Move it to the `io.opentelemetry.instrumentation.auto` package

Proposal 2: Remove it, and use "Implementation-Version" from `MANIFEST.MF`

Traditionally the reason for using a version file over `MANIFEST.MF` is that it survives in fat jars. I'm not sure if we have this problem with vendors consuming/wrapping the agent jar? Is that a feature that it will then log the vendor's "Implementation-Version"? Or would it still be useful to have a separate file to track the opentelemetry agent version?

**Comment by iNikem** [comment]
We log that version during startup. How easy it is to get it from manifest?

**Comment by trask** [comment]
I forgot, this is easy to get: `Agent.class.getPackage().getImplementationVersion()` reads Implementation-Version from the manifest

**Comment by iNikem** [comment]
I honestly don’t think it is a problem worth solving :)

**Comment by anuraaga** [comment]
Using the Manifest looks nice

**Comment by iNikem** [comment]
_IF_ this is a problem, then reading from Manifest seems fine to me. Vendors are free to provide there our version strings with or without Otel versions

**Comment by iNikem** [comment]
Have we an agreement?

**Comment by trask** [comment]
Yes, I think so, opened #750 with this action item and closing this discussion.
