### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#6693]
Today when i build my agent,it failed
error log:
`warning: URL https://docs.oracle.com/javase/8/docs/api/element-list was redirected to https://docs.oracle.com/en/java/javase/19/ -- Update the command-line options to suppress this warning.`

```
Execution failed for task ':instrumentation-api-semconv:javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/xiangtianyu/workspace/code/za/sky-opentelemetry-java-instrumentation/instrumentation-api-semconv/build/tmp/javadoc/javadoc.options'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

**Comment by laurit** [comment]
Fixed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6692 alternatively you can use `-x javadoc` to skip javadoc genteration
