### ISSUE TITLE
How to output the attributes defined in the baggage to the log

### ISSUE THREAD

**Issue by hubxx** [open-telemetry/opentelemetry-java-instrumentation#6708]
**Is your feature request related to a problem? Please describe.**
How to output the attributes defined in the bag to the log?

**Comment by mateuszrzeszutek** [comment]
Hey @hubxx ,
What do you mean by "output to the log"? Do you want baggage printed out with each log statement, e.g. as part of the thread context/MDC? Or are you perhaps using the OTLP logging exporter and sending logs to the collector, and want the baggage to be attached to the OTLP logs?

**Comment by hubxx** [comment]
Hey @mateuszrzeszutek ,
Yes, is there a simple way to extend Logger MDC auto-instrumentation。
For example, put order_id in baggage.
Then configure
Logging.pattern.level = trace_id=%mdc{trace_id} order_id=%mdc{bagage .order_id}

**Comment by trask** [comment]
hi @hubxx, this is not supported today, but seems like a good improvement if you or anyone else wants to contribute it!

**Comment by trask** [comment]
Resolved by #7892
