### ISSUE TITLE
Did not find embedded instrumentation properties file

### ISSUE THREAD

**Issue by ramatudaan** [open-telemetry/opentelemetry-java-instrumentation#6733]
**Describe the bug**
We are using dropwizard for developing our microservices and the version of the jaxrs we use is 2.0.1. Recently we tried to adopt opentelemetry and as a part of it, explored the java autoinstrumentation via injecting the agent into the application. We are getting the following error while checking the DEBUG logs of the agent and the spans are not getting generated and exported to the opentelemetry collector configured. 
[otel.javaagent 2022-09-23 19:42:26:423 +0000] [dw-34 - GET DEBUG io.opentelemetry.javaagent.shaded.instrumentation.api.internal.EmbeddedInstrumentationProperties - Did not find embedded instrumentation properties file META-INF/io/opentelemetry/instrumentation/io.opentelemetry.jaxrs-annotations-2.0.properties.

We are receiving the spans of the other library calls like async-http-client,Tomcat JDBC Pool Cleaner except for the jaxrs and jetty calls. Can someone please help to understand the issue

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)
v1.18.0

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6") Azul JDK8
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251") Azul JDK8
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by laurit** [comment]
```
[otel.javaagent 2022-09-23 19:42:26:423 +0000] [dw-34 - GET DEBUG io.opentelemetry.javaagent.shaded.instrumentation.api.internal.EmbeddedInstrumentationProperties - Did not find embedded instrumentation properties file META-INF/io/opentelemetry/instrumentation/io.opentelemetry.jaxrs-annotations-2.0.properties.
```
should be harmless. Please provide a minimal application that reproduces your issue.
