### ISSUE TITLE
Split out netty library instrumentation

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java-instrumentation#6734]
I want to be able to register a [HttpServerTracingHandler](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/netty/netty-4.1/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/netty/v4_1/server/HttpServerTracingHandler.java) directly in my netty channel pipeline. 

I've verified through local testing that its perfectly useful as standalone library instrumentation. Curious if there's any reason not to split it out?

**Comment by trask** [comment]
> Curious if there's any reason not to split it out?

I don't think so, I'd say go for it
