### ISSUE TITLE
How to observe the rocketmq trace via auto-instrumentation?

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-java-instrumentation#6739]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
I have two applications, one is rocketmq producer, the other one is consumer. I deployed the otel Java agent for both of them. But in jaeger dashboard, I didn’t capture the tcp trace of publish and consume the message.
**Describe the solution you'd like**
Is there any additional configuration I have to make to capture the trace? Or the features have not been implemented? Please kindly let me know, thanks
**Describe alternatives you've considered**
Is there any possibility let us know how to donate the community to implement this feature?
**Additional context**

**Comment by laurit** [comment]
@sweetxiaodai is this a duplicate of https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6741 or does this happen with rocketmq 4.x?

**Comment by sweetxiaodai** [comment]
Yes, will close this one.
