### ISSUE TITLE
Alibaba latest Rocket MQ cannot be auto-instrumented.

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-java-instrumentation#6741]
**Describe the bug**
Alibaba released their latest RocketMQ v5.0 meanwhile it published its client maven dependencies. However, the otel-
java-auto-instrumentation cannot capture the trace if we use the following client libraries.

Official SDK for public
```xml
		<dependency>
			<groupId>org.apache.rocketmq</groupId>
			<artifactId>rocketmq-client-java</artifactId>
			<version>5.0.0</version>
		</dependency>
```

If you use Alibaba cloud RocketMQ PaaS service, it also provide you with a all-in-one SDK. This also cannot be auto-instrumented by the javaagent.
```xml
		<dependency>
			<groupId>com.aliyun.openservices</groupId>
			<artifactId>ons-client</artifactId>
			<!--Replace this with latest Java SDK version-->
			<version>1.8.8.1.Final</version>
		</dependency>
```
**Steps to reproduce**
If possible, provide a recipe for reproducing the error.
Use above SDK connect to RocketMQ, and start the jar with javaagent. Observe in jaeger, you cannot find the span and trace.

**What did you expect to see?**
A clear and concise description of what you expected to see.
Capture produce and consume trace.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version are you using?**
v18.0

**Environment**
Compiler: OracleJDK1.8
OS: Ubuntu 20.04, MacOS
Runtime "Oracle JRE 8u251"
OS: MacOS

**Additional context**
contact me if you want to have a short discussion.

**Comment by aaron-ai** [comment]
@sweetxiaodai  @laurit  I'll fix it.

**Comment by sweetxiaodai** [comment]
It was done? @aaron-ai  awesome

**Comment by aaron-ai** [comment]
> It was done? @aaron-ai awesome

I am working on it. Related pull request will be created recently.

**Comment by aaron-ai** [comment]
@sweetxiaodai , thanks for you attention. 

This feature has been merged, and you could use it in next release, related issue: #6884 #7019

**Comment by mateuszrzeszutek** [comment]
I'll close this issue, since it's implemented now. If you run into any further issues, please reopen or open a new one.
