### ISSUE TITLE
Fix testLatestDeps in dubbo instrumentation

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#6746]
I temporarily disabled a test that was failing with testLatestDeps in #6745, but the test still needs to be fixed.

**Comment by trask** [comment]
@yingziisme let us know if you have a chance to look into this

**Comment by yingziisme** [comment]
> @yingziisme let us know if you have a chance to look into this

well, I will look into this in few days

**Comment by yingziisme** [comment]
> @yingziisme let us know if you have a chance to look into this

It fixed in #6754
