### ISSUE TITLE
Change configuration options prefix to “otel”

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#675]
Following https://github.com/open-telemetry/opentelemetry-specification/pull/666/files we should change the prefix of all our configuration options from `ota` to `otel`.

**Comment by trask** [comment]
For language specific environment variables, that PR is suggesting

```
OTEL_{LANGUAGE}_{FEATURE}
```

Some options (yay naming :smiling_face_with_three_hearts:):
* `OTEL_JAVA_AGENT_{FEATURE}`
* `OTEL_JAVA_AUTO_{FEATURE}`
* `OTEL_JAVA_{FEATURE}`

I think we are just talking about configuration options in [Config.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/7fd607617b97c5e4ea62bffa979d8bd5aa9a2aed/agent-bootstrap/src/main/java/io/opentelemetry/auto/config/Config.java#L58-L84)

* exporter.jar
* exporter
* propagators
* trace.config
* trace.enabled
* integrations.enabled
* trace.annotations
* trace.executors.all
* trace.executors
* trace.methods
* trace.methods.exclude
* trace.classes.exclude
* http.server.error.statuses
* http.client.error.statuses
* http.server.tag.query-string
* http.client.tag.query-string
* trace.scope.depth.limit
* trace.runtime.context.field.injection
* kafka.client.propagation.enabled
* log.injection.enabled
* experimental.log.capture.threshold
* endpoint.peer.service.mapping

So, e.g.
* `OTEL_JAVA_AGENT_EXPORTER`
* `OTEL_JAVA_AUTO_EXPORTER`
* `OTEL_JAVA_EXPORTER`

**Comment by iNikem** [comment]
Definitely `OTEL_JAVA`

**Comment by trask** [comment]
cc: @open-telemetry/java-approvers, we would like to share your namespace for language specific environment variables

**Comment by tylerbenson** [comment]
This seems reasonable to me.  👍
