### ISSUE TITLE
Spring Gateway will reboot when deploy the auto-instrumentation

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-java-instrumentation#6758]
**Describe the bug**
Spring gateway will reboot automatically if we deploy opentelemetry operator instrumentation.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.
simply put spring gateway into a docker, deploy to k8s, then attach the java instrumentation. the service will reboot.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: (e.g., "Ubuntu 20.04")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**

**Comment by trask** [comment]
hi @sweetxiaodai!

> Spring gateway will reboot automatically if we deploy opentelemetry operator instrumentation.

Are you able to test adding the -javaagent manually? Does that also cause the same issue?

> simply put spring gateway into a docker, deploy to k8s, then attach the java instrumentation. the service will reboot.

can you put together a small repository that reproduces the issue? that would be most helpful for us to be able to see what might be going on

**Comment by sweetxiaodai** [comment]
Sure, I will prepare a repository for this later. One more question, when I apply the instrumentation annotation to the pod of spring cloud gateway, it automatically create a new container which is named auto-instrumentation and inject agent to the java command line, which is not happened for other springboot applications, would you mind kindly let me know why? thanks.

**Comment by trask** [comment]
hey @sweetxiaodai, what versions of spring gateway and spring boot starter are you using? also, what version of Java (including minor version) are you using?

**Comment by sweetxiaodai** [comment]
Hi @trask after evaluate the system, we found the issue was caused by otel-java-agent is not compatible with another APM agent. Just keep one APM agent will solve this issue. It is not related to Spring Cloud Gateway. I will close this issue.
