### ISSUE TITLE
Name jdbc spans according to db operation/procedure name and not database name

### ISSUE THREAD

**Issue by akats7** [open-telemetry/opentelemetry-java-instrumentation#6765]
**Is your feature request related to a problem? Please describe.**
I am exporting my trace data to New Relic and want to use the database transaction tab to identify db operations that are the most time consuming, however, NR queries the operation off the name of the span which in this case is always the same db name, making it difficult to identify which db operation causes issues.

**Describe the solution you'd like**
I would like the jdbc spans to be named according to the operation (i.e, in the case of stored procedures, name according to the stored procedure name),   

**Additional context**
I'm looking on guidance on this, is there a reason this wasn't the default functionality, and if it deemed to be useful I'd be happy to discuss some approaches.

**Comment by trask** [comment]
hi @akats7!

I believe the jdbc span name should be `<db.operation> <db.name>.<db.sql.table>`, but it sounds like you are only seeing `<db.name>`?

that could be happening if we aren't able to parse out the operation and table from the query, so would be helpful to see specific queries and resulting span names you are seeing.

**Comment by akats7** [comment]
Hi @trask, 

Thanks for the reply, so it looks like even when all of the fields are able to be extracted, the span would be something along the lines of **INSERT postgres.table1**, what I was wondering is if it would be of interest for the name to essentially be **spInsertUser**, that way I can actually delineate which procedures are taking longer than others as many procedures might have the same <db.operation> <db.name>.<db.sql.table> permutation

**Comment by trask** [comment]
hey @akats7, are you specifically referring to the naming of stored procedures? maybe if you could give a few examples of complete sql statements and how you would propose to name them it might help to clarify, thx!

**Comment by akats7** [comment]
Hi @trask, yes I'm specifically referring to called stored procedures, is the proper naming for a stored procedure in the format "Call db_name.procedure_name", this seems to be the case when I see only the db.name get parsed out, and in turn the span is named "db_name"

**Comment by trask** [comment]
> yes I'm specifically referring to called stored procedures

makes sense to me, as stored procedure names are cardinality limited

stored procedures are even called out explicitly in the spec:

> The span name SHOULD be set to a low cardinality value representing the statement executed on the database. It MAY be a stored procedure name (without arguments)

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#semantic-conventions-for-database-client-calls

**Comment by akats7** [comment]
Hi @trask, just wanted to clarify, is this a valid enhancement. Just want to ensure that similar instrumentation does not already exist/existed in the past within the agent.

**Comment by trask** [comment]
> just wanted to clarify, is this a valid enhancement

I believe so

**Comment by akats7** [comment]
Can I please be assigned this issue

**Comment by mateuszrzeszutek** [comment]
Fixed by #7557

**Comment by akats7** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7557
