### ISSUE TITLE
testing vs test-utils

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#677]
I noticed we have two test helper packages (?) `:testing` and `:utils:test-utils`. Is there a reason to separate instead of combining into one?

**Comment by trask** [comment]
Probably separation was/is needed in dd-trace-java repo, but I don't see need in this repo. Looks like we can merge `:utils:test-utils` into `:testing`.

It looks like we can probably get rid of `:utils:test-utils:` also:
* CommonTaskExecutor
  * move to `auto-tooling` where it's used
  * also used in `GrpcTest` but this looks like it could be replaced there with standard executor
* DaemonThreadFactory
  * move to `cassandra-3.0` where it's used
  * also used in `CommonTraskExecutor` but could be replaced there with guava `ThreadFactoryBuilder`

**Comment by mateuszrzeszutek** [comment]
This issue can now be closed - `test-utils` was removed a few weeks ago, both `CommonTaskExecutor` and `DaemonThreadFactory` are now in `javaagent-tooling` where they're actually used.
