### ISSUE TITLE
Kafka Streams metrics

### ISSUE THREAD

**Issue by loicgreffier** [open-telemetry/opentelemetry-java-instrumentation#6778]
I expected to get [Kafka Streams metrics](https://docs.confluent.io/platform/current/streams/monitoring.html#built-in-metrics) from the Javaagent Instrumentation as it has been done for Kafka Clients recently #6533 but can't manage to get them.

I am using:
- Otel Javaagent v1.18.0
- Kafka Streams v3.2.0 (tested with v2.7.0 as well)

I managed to get `kafka_consumer_` and `kafka_producer_` metrics, but no Kafka Streams metrics

**Comment by PeterF778** [comment]
Perhaps the stream metrics can be extracted using the new JMX Metric Insight (PR https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6573)

**Comment by Samudraneel24** [comment]
Working on this issue. Adding Kafka Streams metrics via JMX using the newly added JMX Metric Insight module.

**Comment by trask** [comment]
(btw @Samudraneel24 if you want to [join the OTel org](https://github.com/open-telemetry/community/blob/main/community-membership.md#member), then we can add you as an assignee to an issue)

**Comment by loicgreffier** [comment]
Many thanks @PeterF778 @Samudraneel24 Kafka Streams metrics can be exported using JMX Metric Insight

The issue can be closed
