### ISSUE TITLE
Proposal: Use GitHub Actions for CI/CD

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#678]
Following open-telemetry/opentelemetry-java#1381

@anuraaga raised a concern if GitHub action infra can cope with our tests. I am willing to test this.

**Comment by anuraaga** [comment]
@trask Has already done a lot of work on this, warning before duplicating work!

**Comment by iNikem** [comment]
Holding my horses...

**Comment by trask** [comment]
Check out my comments here: https://github.com/open-telemetry/community/issues/398#issuecomment-656302206

And my branch here: https://github.com/trask/opentelemetry-java-instrumentation/blob/github-actions/.github/workflows/build.yaml

I'd be happy for you to take a look at it.

Using a custom container was slow b/c it had to download it each time, so was thinking next to try to remove the custom container.

I was not super happy about the lack of auto-cancelling old builds, but it's not a show stopper.

I did like the dynamic matrix. We could potentially speed up build time by going massively parallel, e.g. https://github.com/trask/opentelemetry-java-instrumentation/actions/runs/155926011.

**Comment by iNikem** [comment]
Massive parallelism is impressive :) But I don't understand if this parallelism is independent from `Github Actions has max 20 parallel builds across the whole org`? Is it still one job?

Not sure I like that the whole matrix gets canceled if one cell fails :( Can this be configured?

Definitely +1 for removing custom container, if GitHub can provide us with all needed java versions. And we can think later and separately about different java vendors.

Don't understand if action invocation somehow references branch and/or PR that triggered it?

**Comment by trask** [comment]
> Is it still one job?

Ah, no, that hit the max 20 parallel builds, and things backlogged.

> Not sure I like that the whole matrix gets canceled if one cell fails

I didn't get that far to even notice this. Yeah, that's too bad with our sporadic test failures. But good for conserving parallel builds if things are really broken.

> Don't understand if action invocation somehow references branch and/or PR that triggered it?

I was testing it on a PR if that helps: https://github.com/trask/opentelemetry-java-instrumentation/pull/1

**Comment by iNikem** [comment]
And we want to test with different java versions. So we have not 60 parallel jobs, but more like 200+

On a related note. I have started experimenting with speeding up our tests in https://github.com/open-telemetry/opentelemetry-java-instrumentation/compare/master...iNikem:faster-tests . So far I have around 30% decrease in run time for all tests. And I still have that nagging feeling about Gradle build cache...

So may be we don't need that massive parallelism if we can get test time into reasonable range.

**Comment by trask** [comment]
> Not sure I like that the whole matrix gets canceled if one cell fails

Semi-randomly ran across: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
