### ISSUE TITLE
Remove servlet dependency from :testing

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#679]
Many projects have to work around a servlet dependency in testing due to version issues. servlet seems too specific of a dependency for a generic testing helper to have.

**Comment by mateuszrzeszutek** [comment]
Maybe we could use the `com.sun.net.httpserver` that's already in JDK? We won't need to depend on any external HTTP server implementation. I wouldn't use the `com.sun` server in a production service, but maybe it makes sense to use it in our tests 🤷‍♂️

**Comment by mateuszrzeszutek** [comment]
Implemented in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3250
