### ISSUE TITLE
[Promethus Exporter] Failed to gathering metrics: collected metric "http_server_active_requests"

### ISSUE THREAD

**Issue by ychaydhari** [open-telemetry/opentelemetry-java-instrumentation#6797]
Hello,
There are two services with otel-java-agent running on my machine. 
When GET API hit from the second service. I'm getting this error to collect http_server_active_requests metrics.
The error message describes that the http_server_active_requests metric is already collected with the same label and value. I didn't get why this coming. is it a bug of OTEL or Prometheus?

Which is the java agent version used?
-- 2.38.0

config file for OTEL:- 

`service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]`

**Comment by bogdandrutu** [comment]
@trask this seems to be related to java instrumentation (or sdk), and was filed in community repo, so I moved it here.

**Comment by trask** [comment]
hi @ychaydhari, can you paste the full text of the error message you are getting?

**Comment by ychaydhari** [comment]
> hi @ychaydhari, can you paste the full text of the error message you are getting?

2022-10-18T12:18:52.888+0530    info    TracesExporter  {"kind": "exporter", "data_type": "traces", "name": "logging", "#spans": 30}
2022-10-18T12:18:53.681+0530    error   prometheusexporter@v0.59.0/log.go:34    error gathering metrics: collected metric "http_server_active_requests" { label:<name:"http_flavor" value:"1.1" > label:<name:"http_host" value:"localhost:7171" > label:<name:"http_method" value:"GET" > label:<name:"http_scheme" value:"http" > label:<name:"job" value:"cm_service" > gauge:<value:4 > } was collected before with the same name and label values
        {"kind": "exporter", "data_type": "metrics", "name": "prometheus"}
github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter.(*promLogger).Println
        github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.59.0/log.go:34
github.com/prometheus/client_golang/prometheus/promhttp.HandlerForTransactional.func1
        github.com/prometheus/client_golang@v1.13.0/prometheus/promhttp/http.go:139
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
        net/http/server.go:2462
go.opentelemetry.io/collector/config/confighttp.(*decompressor).wrap.func1
        go.opentelemetry.io/collector@v0.59.0/config/confighttp/compression.go:162
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2084
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.34.0/handler.go:204
go.opentelemetry.io/collector/config/confighttp.(*clientInfoHandler).ServeHTTP
        go.opentelemetry.io/collector@v0.59.0/config/confighttp/clientinfohandler.go:39
net/http.serverHandler.ServeHTTP
        net/http/server.go:2916
net/http.(*conn).serve
        net/http/server.go:1966

**Comment by trask** [comment]
hey @ychaydhari, sorry for the late reply, since this error is from `github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter@v0.59.0`, I'd suggest asking in https://github.com/open-telemetry/opentelemetry-collector-contrib

**Comment by jojotong** [comment]
Same problem.

**Comment by trask** [comment]
this error and log are from the collector, if you are still having this issue, please re-open in https://github.com/open-telemetry/opentelemetry-collector-contrib
