### ISSUE TITLE
CircleCI build is too slow (because no any Gradle cache was used)

### ISSUE THREAD

**Issue by donbeave** [open-telemetry/opentelemetry-java-instrumentation#680]
Hello!

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/1841/workflows/8ede82ad-c596-4272-a1b6-b8140882deb5/jobs/13444/steps

This really take a lot of time for each build. What guys do you think about adding Gradle cache here, it will increase building speed by re-using already downloaded dependencies include Gradle distribution. This can achieve by using cache folders in CircleCI. Another additional way to speed-up this build is add Gradle Build Cache Node: https://hub.docker.com/r/gradle/build-cache-node.

**Comment by iNikem** [comment]
@donbeave We already have #490 for Gradle build cache. I will close this issue as duplicate, if you don't mind. Please feel free to add your ideas to that issue :)
