### ISSUE TITLE
Method Level tracing info not getting emitted

### ISSUE THREAD

**Issue by ryadav-collab** [open-telemetry/opentelemetry-java-instrumentation#6803]
Hi Team,

I am facing similar issue, methods were not getting shown up in otlp logs ( trying auto instrumentation ).
Used below flag along with
output looks as below without method details
Span https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7
Trace ID : 25605110614ccd12b8d36435378c0c
Parent ID :
ID : 500f7ba49157f2
Name : INSERT INTO ERRORS
Kind : SPAN_KIND_CLIENT
Start time : 2022-10-03 15:13:45.84 +0000 UTC
End time : 2022-10-03 15:13:46.2299066 +0000 UTC
Status code : STATUS_CODE_UNSET
Status message :
Attributes:
-> db.user: STRING(scott)
-> net.peer.port: INT(1221)
-> db.connection_string: STRING(myhost:thin://mydb:1221)
-> net.peer.name: STRING(myhost)
-> db.system: STRING(mysystem)
-> db.statement: STRING(insert into test values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?))
-> db.sql.table: STRING(test)
-> thread.id: INT(73)
-> db.operation: STRING(INSERT)
-> db.name: STRING(mydb)
-> thread.name: STRING(Executor task launch worker for task 0)
{"kind": "exporter", "data_type": "traces", "name": "logging"}
2022-10-03T20:43:47.897+0530 info MetricsExporter {"kind": "exporter", "data_type": "metrics", "name": "logging", "#metrics": 22}
2022-10-03T20:43:47.897+0530 info ResourceMetrics #0
Resource SchemaURL:
Resource attributes:
-> service.name: STRING(otel-collector)
-> service.instance.id: STRING(localhost:8888)
-> net.host.port: STRING(8888)
-> http.scheme: STRING(http)

Properties used while running my app.
java -javaagent:opentelemetry-javaagent.jar -Dotel.traces.exporter=otlp -Dotel.metrics.exporter=otlp -Dotel.logs.exporter=otlp -Dotel.instrumentation.methods.include=myclass1[applyFunction]" myapp.jar

otlp exporter i run as below using config yaml file.

=======

cmd => .\otelcol.exe --config=file:./otel.config.yaml

otel.config.yaml
extensions:
health_check:
pprof:
endpoint: 0.0.0.0:1777
zpages:
endpoint: 0.0.0.0:55679

receivers:
otlp:
protocols:
grpc:
http:

opencensus:

Collect own metrics
prometheus:
config:
scrape_configs:
- job_name: 'otel-collector'
scrape_interval: 10s
static_configs:
- targets: ['localhost:8888']

jaeger:
protocols:
grpc:
thrift_binary:
thrift_compact:
thrift_http:

zipkin:

processors:
batch:

exporters:
logging:
logLevel: debug

service:

pipelines:

traces:
  receivers: [otlp, opencensus, jaeger, zipkin]
  processors: [batch]
  exporters: [logging]

metrics:
  receivers: [otlp, opencensus, prometheus]
  processors: [batch]
  exporters: [logging]
extensions: [health_check, pprof, zpages]

**Comment by mateuszrzeszutek** [comment]
Hey @ryadav-collab ,
I'm not sure what's the issue here (and what it is similar to). Can you explain what was expected and how does it differ from the actual behavior of the agent?

**Comment by mateuszrzeszutek** [comment]
Ping @ryadav-collab
