### ISSUE TITLE
Span over multiple messages

### ISSUE THREAD

**Issue by sigurd-cp** [open-telemetry/opentelemetry-java-instrumentation#6810]
Hey guys,

I'm currently investigating a span over more than one topic in kafka2.6+ instrumentation.
I understand the idea of a span from `send` to `receive` and finally to `process`.
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6443#issuecomment-1217995296
But in the end, I want to measure how much time the processing takes (overall).

Let's assume, there is the following process:

`message(initial_topic) -> multiple message(processing_topic) -> message(finish_topic)`

There is a unique message to initiate (that should start the span).
There are lots of messages for processing and there is a finish message, that is signaling that the work is done, therefore the span must be closed.
Then I would like to measure the time from the beginning to the end. The time of sending and consuming a message is not important.

I would expect, that every message, that is sent during a message is processed (between receiving and committing it) to have the same context and therefore must be part of the span. That would enable us to create an overall span.
I'm aware, that it is possible, that the finish message never happens, but still, we could understand which messages are created and how much time the process takes.
Also, it is possible in general, that a message is consumed by multiple groups. In my case, each message will be processed exactly once.

A link to another span does not help that much, at least the tools such as jaeger/tempo do not recognize that as a comprehensive span. I think links are not intended to use in that way.

**Comment by trask** [comment]
> A link to another span does not help that much, at least the tools such as jaeger/tempo do not recognize that as a comprehensive span. I think links are not intended to use in that way.

hi @sigurd-cp! the OpenTelemetry messaging semantic conventions rely heavily on links, for more background, check out https://github.com/open-telemetry/oteps/blob/main/text/trace/0220-messaging-semantic-conventions-span-structure.md

our hope is that monitoring backends which do not support links yet will support them in the future
