### ISSUE TITLE
Can we surpport any  configuration to enable or disable those metrics?

### ISSUE THREAD

**Issue by yingziisme** [open-telemetry/opentelemetry-java-instrumentation#6818]
If we use the metrics with HttpClientMetrics, we will get both there metircs those are http.client.duration, http.client.request.size, http.client.response.size. 

Can we surpport any  configuration to enable or disable those metrics?

**Comment by trask** [comment]
I think you can create a metric view to drop metrics that you don't want, see https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/incubator/README.md#view-file-configuration

**Comment by mateuszrzeszutek** [comment]
Hey @yingziisme ,
Have you tried Views, as Trask suggested in the comment above?
