### ISSUE TITLE
How to modify view with HttpClientMetrics 

### ISSUE THREAD

**Issue by yingziisme** [open-telemetry/opentelemetry-java-instrumentation#6819]
How to modify view with HttpClientMetrics or HttpServerMetrics? Only by modifying TemporaryMetricsView?

**Comment by trask** [comment]
hi @yingziisme! there is no good way currently, though this is needed. can you describe your use case? is it to capture additional attributes which are already on the span? or to remove some attributes? or to populate new attributes that are not already on the span?

**Comment by mateuszrzeszutek** [comment]
Linking a related issue #6209

**Comment by trask** [comment]
getting closer to being able to support this with https://github.com/open-telemetry/opentelemetry-java/pull/5677 and https://github.com/open-telemetry/opentelemetry-java/pull/5722
