### ISSUE TITLE
Any references for Opentelemetry Support for Java Bazel Project

### ISSUE THREAD

**Issue by Jeet0204** [open-telemetry/opentelemetry-java-instrumentation#6824]
The opentelemetry agent is added to the WORKSPACE in Bazel Project. How can I use it in service's BUILD file and spin it up in a container with service's jar file?

**Comment by mateuszrzeszutek** [comment]
Hey @Jeet0204 ,

I'm not sure how Bazel builds work, I've never even seen that tool before -- if you need information on Bazel-specific project setup you might want to ask a question in the https://github.com/bazelbuild/bazel project.

In general, though, the agent is a separate jar that is not added as a dependency, but instead specified as runtime `-javaagent` JVM argument. If you want to include it in a docker image you could put the following in your dockerfile:
```dockerfile
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar /opentelemetry-javaagent.jar
```
And then pass the `-javaagent` argument to the JVM:
```dockerfile
CMD java -javaagent:/opentelemetry-javaagent -jar /my-service.jar
```

**Comment by mateuszrzeszutek** [comment]
Hey @Jeet0204 ,
Did my comment above help with your problem?

**Comment by Jeet0204** [comment]
Hey @mateuszrzeszutek,
This makes sense and feasible to make it working. But I did manage integrating it by configuring individual dependencies.
