### ISSUE TITLE
Azure eventhub client auto instrument requirement

### ISSUE THREAD

**Issue by sweetxiaodai** [open-telemetry/opentelemetry-java-instrumentation#6831]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
Azure has its own messaging PaaS service called event hub. Microsoft released several client SDK to help developer to consume and produce message to the messaging systems. Is it possible that make otel-java-instrumentation support this SDK library as well? It would be very helpful for the cloud native design.

**Describe the solution you'd like**
Please provide support for this library to auto-instrument the trace from producer to consumer.
```xml
<dependency>
    <groupId>com.azure</groupId>
    <artifactId>azure-messaging-eventhubs</artifactId>
    <version>5.7.0</version>
</dependency>
```

**Describe alternatives you've considered**

**Additional context**

**Comment by trask** [comment]
hi @sweetxiaodai! this should already be supported (https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/azure-core)

**Comment by sweetxiaodai** [comment]
@trask thanks, just test the feature locally. Just one question.
All the send traffic created a trace for each, but the receive spans have been put together in one trace, is it correct? or is there any specific mechanism of azure eventhub?
![Screenshot 2022-10-08 at 05 29 53](https://user-images.githubusercontent.com/90817719/194660206-fc2f943d-f334-49f0-8c70-29e74ece408f.png)

**Comment by trask** [comment]
hi @sweetxiaodai, I'd recommend opening an issue at https://github.com/Azure/azure-sdk-for-java/issues, and including some example code to show how you are consuming the messages, feel free to tag myself and @lmolkova on the issue in that repository

**Comment by lmolkova** [comment]
Hi @sweetxiaodai, happy to help you with eventhubs.

We're adding a bunch of improvements for EventHubs tracing - they're coming in the Nov release and solving https://github.com/Azure/azure-sdk-for-java/issues/28559, https://github.com/Azure/azure-sdk-for-java/issues/28552. 
Here's the WIP PR https://github.com/Azure/azure-sdk-for-java/pull/31197 . 

Can you please check if any of these issues apply to your case? If not or if you're not sure, please create an issue in https://github.com/Azure/azure-sdk-for-java/issues as @trask suggested, and please include the following information:
- how do you send and receive events? in batches or individual?
- do you use a consumer client (sync or async?) or Processor? 

Thanks!
