### ISSUE TITLE
how to add local root span's name as a attribute to a span?

### ISSUE THREAD

**Issue by illidanzen163** [open-telemetry/opentelemetry-java-instrumentation#6837]
hello :
 I want to add local root span's name as an attribute to a span, then I can get a relationship between these span, and group the spans.
Is anyone could give me some suggestion? And why span don't have getName? Thank you

**Comment by trask** [comment]
hi @illidanzen163, one option is to write a SpanProcessor, and cast the parent Span to ReadableSpan to get the name / copy down the local root span name

**Comment by illidanzen163** [comment]
> hi @illidanzen163, one option is to write a SpanProcessor, and cast the parent Span to ReadableSpan to get the name / copy down the local root span name

Thanks very much for the suggestion ! I'll try
