### ISSUE TITLE
Failed to handle GenericMessage. IllegalStateException: No header accessor (not using the SimpMessagingTemplate?)

### ISSUE THREAD

**Issue by dinhan2411** [open-telemetry/opentelemetry-java-instrumentation#6855]
**Describe the bug**
An exception when i run my spring-boot app with opentelemetry-java-agent.jar

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
It works like when I run my app without agent.

**What did you see instead?**
It throws Internal Error.

**What version are you using?**
java 17
opentelemetry-java-agent.jar - version 1.18.0

**Additional context**
It relate to Websocket connection when I debug. I use SimpMessagingTemplate to connect to rabbitmq.

My stack trace:

> Failed to handle GenericMessage [payload=byte[91], headers={simpMessageType=MESSAGE, id=924f75a8-c2f3-50d3-51a3-fdf5694d8a91, contentType=application/json, simpDestination=/topic/53539-resource, traceparent=00-2b3fd0009cb316fb31579486e5550c77-832677f052ec2891-01, timestamp=1665543823786}] to org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask@65eb7676 in StompBrokerRelay[ReactorNettyTcpClient[reactor.netty.tcp.TcpClientConnect@37d2ca1f]]; 
nested exception is java.lang.IllegalStateException: No header accessor (not using the SimpMessagingTemplate?): GenericMessage [payload=byte[91], headers={simpMessageType=MESSAGE, id=924f75a8-c2f3-50d3-51a3-fdf5694d8a91, contentType=application/json, simpDestination=/topic/53539-resource, traceparent=00-2b3fd0009cb316fb31579486e5550c77-832677f052ec2891-01, timestamp=1665543823786}]",
"stackTraceElements":"org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:153) 
org.springframework.messaging.support.ExecutorSubscribableChannel.sendInternal(ExecutorSubscribableChannel.java:100) 
org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:139) 
org.springframework.messaging.support.AbstractMessageChannel.send(AbstractMessageChannel.java:125) 
org.springframework.messaging.simp.SimpMessagingTemplate.sendInternal(SimpMessagingTemplate.java:187) 
org.springframework.messaging.simp.SimpMessagingTemplate.doSend(SimpMessagingTemplate.java:162) 
org.springframework.messaging.simp.SimpMessagingTemplate.doSend(SimpMessagingTemplate.java:48) 
org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) 
org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:151) 
org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:129) 
org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:122) 
com.iaas.billinggateway.controller.PriceController.calculatePrice(PriceController.java:64) com.iaas.billinggateway.controller.PriceController$$FastClassBySpringCGLIB$$8d2c7361.invoke() org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

**Comment by mateuszrzeszutek** [comment]
Hey @dinhan2411 ,
Can you post a repro scenario for this bug?
I suspect the problem it somewhere in the `spring-integration` instrumentation, you might want to temporarily disable it and see if it helps.

**Comment by dinhan2411** [comment]
@mateuszrzeszutek  Thank You for reply me. Sorry I can't post repo to public but it's simple like that:

**WebSocketConfig.java**

```java
@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {

    @Value("${spring.rabbitmq.host}")
    public String host;
    @Value("${spring.rabbitmq.web-socket.port}")
    public Integer port;
    @Value("${spring.rabbitmq.username}")
    public String username;
    @Value("${spring.rabbitmq.password}")
    public String password;
    @Value("${spring.rabbitmq.virtual-host}")
    public String vHost;

    @Override
    public void configureMessageBroker(MessageBrokerRegistry config) {
        config
                .setApplicationDestinationPrefixes("/app")
                .enableStompBrokerRelay("/topic")
                .setRelayHost(host)
                .setRelayPort(port)
                .setClientLogin(username)
                .setClientPasscode(password)
                .setSystemLogin(username)
                .setSystemPasscode(password)
                .setVirtualHost(vHost);
    }

    @Override
    public void registerStompEndpoints(StompEndpointRegistry registry) {
        registry
                .addEndpoint("/websocket")
                .setAllowedOriginPatterns("*")
                .withSockJS();
    }

}
```

**TestSocketModel.java**
```java
@Data
@NoArgsConstructor
@Builder
@AllArgsConstructor
public class TestSocketModel {
    String message;
}
```


**PriceController.java**
```java
@RestController
@RequiredArgsConstructor
@RequestMapping(BaseUrl.v1 + "/price")
public class PriceController {
    @Autowired
    public SimpMessagingTemplate template;

    @PostMapping
    @LogControllerLayer
    public void test() {
        TestSocketModel testSocketModel = TestSocketModel.builder()
                .message("test socket")
                .build();

        template.convertAndSend("/topic/test", testSocketModel);
    }
}
```

**Comment by laurit** [comment]
Probably because https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/c1cdadab5d09eeba198e98a111d45cd7d7ed0e40/instrumentation/spring/spring-integration-4.1/library/src/main/java/io/opentelemetry/instrumentation/spring/integration/TracingChannelInterceptor.java#L104 makes a copy from the original message to add the context propagation header. There is a resolved spring issue for this https://github.com/spring-projects/spring-framework/issues/18851
@dinhan2411 This assertion was removed from spring code in https://github.com/spring-projects/spring-framework/commit/1e003a1c90fe7f5aa91f99a34fa5be53a43ad6d8, could you see if it works when you use a newer spring version.

**Comment by dinhan2411** [comment]
@mateuszrzeszutek @laurit I find out may be the error because of using this:
```java
                <dependency>
			<groupId>org.springframework.integration</groupId>
			<artifactId>spring-integration-redis</artifactId>
			<version>5.5.15</version>
		</dependency>
```

But I use it in many projects, it is hard to replace them all. Is there a better option for me?

**Comment by dinhan2411** [comment]
Thank @mateuszrzeszutek  and @laurit, I disable spring-integration and it works. But the trace doesn't have enough span as I expected. Hopefully it will be fixed in the future. Thank you again!

That's what I added to the config.properties file for the agent:
```java
otel.instrumentation.spring-integration.enabled=false
```
