### ISSUE TITLE
HttpServerTracer should not modify the actually returned status code

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#688]
Currently, when there's an exception but status is 200, it gets remapped to 500, but this is not reflecting the actual response (and can be completely wrong in protocols like gRPC).

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/285d4b0f0e1828a7e6467d3103dba6468fbf4c01/agent-bootstrap/src/main/java/io/opentelemetry/auto/bootstrap/instrumentation/decorator/HttpServerTracer.java#L218

**Comment by trask** [comment]
For servlets, I think this behavior is correct (well, we should also check `!response.isCommitted()`, and we should also doc why), based on [servlet spec](https://javaee.github.io/servlet-spec/downloads/servlet-4.0/servlet-4_0_FINAL.pdf):

> If a servlet generates an error that is not handled by the error page mechanism as described above, the container must ensure to send a response with status 500.

Agree that we should not apply this logic to other instrumentation.

**Comment by trask** [comment]
Closed by #870
