### ISSUE TITLE
netty client timedout, so the span did not end

### ISSUE THREAD

**Issue by XiaoWeiKIN** [open-telemetry/opentelemetry-java-instrumentation#6883]
version：v1.11.0

desc：

I used `recator-netty` so that the `netty-client` span end normally when the request is normal.
![image](https://user-images.githubusercontent.com/20626345/195818742-6c6b1acc-5889-42d7-bc7b-b5d2a4adf116.png)

but `netty 4.1` span doesn't seem to end properly when a request timesout
![image](https://user-images.githubusercontent.com/20626345/195819914-5c9f552e-c2be-4b74-a096-3f7657f974be.png)

**Comment by mateuszrzeszutek** [comment]
Hey @XiaoWeiKIN ,
Can you post a repro scenario?
