### ISSUE TITLE
More examples / documentation for java agent auto instrumentation extension

### ISSUE THREAD

**Issue by davidtam** [open-telemetry/opentelemetry-java-instrumentation#6888]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Some more clear example on adding custom auto instrumentation to java agent metrics / traces 

**Describe alternatives you've considered**
Alternatively perhaps extend the [readme.md](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension)

**Additional context**
I have added the following question
https://stackoverflow.com/questions/74083208/how-to-debug-open-telemetry-java-agent-extension-instrumentation

**Comment by mateuszrzeszutek** [comment]
Hey @davidtam ,
Some of your questions should perhaps be answered by https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/writing-instrumentation-module.md#use-advice-classes-to-write-code-that-will-get-injected-to-the-instrumented-library-classes; I also answered your on SO. Does this help you?
