### ISSUE TITLE
Remove span.origin.type attribute

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#689]
I'm not seeing that it provides much value over other attributes which are already captured:

* `org.h2.jdbc.JdbcPreparedStatement` (`db.url` already tells us we are connecting to `h2`, though we don't capture whether it's a prepared statement)
* `forwardToCompileError_jsp` (`spanName` already has this info: `Render /forwards/forwardToCompileError.jsp`)
* `org.apache.catalina.core.ApplicationFilterChain` (not too interesting)
* `org.apache.activemq.ActiveMQMessageConsumer` (this is sort of interesting, we don't capture currently that we are connecting to `activemq`)

Also, I think all general-purpose attributes (like this) should be defined by the semantic conventions.

If someone wants to capture one or more of these attribute values in some instrumentation-specific attribute(s) that would seem ok to me (see ongoing discussing of instrumentation-specific attributes in #602).

But I would suggest we remove this general-purpose attribute.

**Comment by iNikem** [comment]
I am happy to remove all attributes which are not in semantic conventions and which meaning is not obvious. But it @tylerbenson has some time, we could ask him for historical reasons for their introduction.

**Comment by tylerbenson** [comment]
I'm ok removing the `origin` attributes.  I do think it would be helpful to have a semantic attribute for this general concept at some point in the future, but it's not required.  Some of these attributes have been useful to me at some points when troubleshooting in identifying the source of a particular span, but that probably doesn't make sense in this project.
