### ISSUE TITLE
Third part sdk dependency handle question

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#6890]
In this issue #4958 , there provides a solution of third part sdk is to put it into id("otel.javaagent-bootstrap"). But in my situation, it cannot work well.

I am trying to integerate nacos discovery into instrumentation. So i put the nacos to bootstrap. But when the application include the nacos dependency to use nacos config, it will use the nacos in bootstrap, not the dependency that user included.

The nacos sdk invloved "discovery" and "config". My agent will only use discovery, but it will effect config. Is there any way to avoid this?

**Comment by laurit** [comment]
To get around this you should either shade the libraries you put in boot loader or instead of boot loader place them in agent loader and only put the api that allows using the library in boot loader.

**Comment by xiangtianyu** [comment]
> To get around this you should either shade the libraries you put in boot loader or instead of boot loader place them in agent loader and only put the api that allows using the library in boot loader.

I got it, thanks for suggestion!
