### ISSUE TITLE
Update SpanAssert method names to reflect the underlying Span method names

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#690]
Update `SpanAssert` method names to reflect the underlying `Span` method names:

* assertSpanNameContains → assertNameContains
* operationName → name
* operationNameContains → nameContains
* spanKind → kind
* parent → hasNoParent
* parentId → parentSpanId

**Comment by imavroukakis** [comment]
Hello 👋 may I work on this?

**Comment by anuraaga** [comment]
@imavroukakis Sure thanks for the help!

**Comment by imavroukakis** [comment]
Hey @anuraaga a heads up, your style configurations URL seems to be broken or not publicly accessible
![image](https://user-images.githubusercontent.com/1764981/94902566-4c7d1680-0490-11eb-85ad-f3a276e07238.png)
