### ISSUE TITLE
Programmatic injection of agent

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#691]
Some environments don't allow modifying JVM args to load an agent, such as FAAS (e.g., lambda). I randomly ran across an approach for injecting the agent by calling a method at the very first line of the app. It could be nice to support that here too

https://github.com/awslabs/disco/blob/master/disco-java-agent/disco-java-agent-inject-api/src/main/java/software/amazon/disco/agent/inject/Injector.java

/cc @mabdinur

**Comment by trask** [comment]
This is possibly good motivation to keep using the more generic term `auto` instead of `javaagent` (except for the actual `opentelemetry-javaagent` artifact)

**Comment by iNikem** [comment]
Recently one of the Splunk's client expressed its interest in such an approach. It was also discussed on SIG meeting and some maintainers expressed their support for adding this functionality.

**Comment by michaelhyatt** [comment]
Is there documentation on how to programmatically attach the agent to a running JVM?

**Comment by trask** [comment]
hi @michaelhyatt! check out https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/runtime-attach

**Comment by trask** [comment]
I believe this can be closed now, see https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/runtime-attach
