### ISSUE TITLE
runtime.jvm.gc.count metric reports invalid unit "collections"

### ISSUE THREAD

**Issue by PeterF778** [open-telemetry/opentelemetry-java-instrumentation#6929]
**Describe the bug**
Garbage Collection metric runtime.jvm.gc.count reports the unit as "collections", which is an invalid unit.

**Steps to reproduce**
Enable GC metrics by specifying -Dotel.instrumentation.runtime-metrics.experimental-metrics.enabled=true on the java command line with the agent. Watch the metric data stream for "runtime.jvm.gc.count".

**What did you expect to see?**
A correct unit can be "{collections}", or "1{collections}", or just "1".

**What did you see instead?**
The reported unit comes out as "collections".

**What version are you using?**
1.18

**Environment**

**Additional context**

**Comment by PeterF778** [comment]
Please go ahead or assign to me, whatever you prefer.

**Comment by trask** [comment]
assigning you, thx ❤️

**Comment by trask** [comment]
Closed by #6930
