### ISSUE TITLE
log4j2-Appender-like ability to filter log4j2 log events

### ISSUE THREAD

**Issue by JessHolle** [open-telemetry/opentelemetry-java-instrumentation#6967]
Unless I am missing something the current instrumentation will catch all attempts to log to a log4j2 logger -- without any regard to the target logger and/or log event severity level.

This may well result in overwhelming verbosity.  It would seem that filtering control is really needed on at least combinations of these 2 dimensions (logger name and severity level).

A seemingly attractive alternative to inventing another filtering configuration would be actually use a log4j Appender -- thus allowing "normal" filtering in this space.  This might entail disabling this portion of the auto instrumentation and configuring a log4j2 Appender that behaves like the current instrumentation.  Or it might involve the auto-instrumentation actually creating a NullAppender with a special (configurable) name and attaching it to the root logger if it does not already exist (but re-using an existing one and its configuration otherwise) and then instrumenting calls to that Appender.

**Comment by JessHolle** [comment]
Of course **now** I notice OpenTelemetryAppender...

So that's there.  The only mystery to me now is what is auto-instrumented in this regard if using the agent, and how to disable any such instrumentation if I want to use OpenTelemetryAppender instead.

**Comment by trask** [comment]
hi @JessHolle!

> Unless I am missing something the current instrumentation will catch all attempts to log to a log4j2 logger -- without any regard to the target logger and/or log event severity level.

this is surprising, the auto-instrumentation is applied after the application's logger level is checked, so it should not be capturing logs without any regard to the target logger or level, can you post a repro that we can look into to see why this might be happening for you?

**Comment by trask** [comment]
> A seemingly attractive alternative to inventing another filtering configuration would be actually use a log4j Appender -- thus allowing "normal" filtering in this space

check out discussion in #5464

**Comment by JessHolle** [comment]
> hi @JessHolle!
> 
> > Unless I am missing something the current instrumentation will catch all attempts to log to a log4j2 logger -- without any regard to the target logger and/or log event severity level.
> 
> this is surprising, the auto-instrumentation is applied after the application's logger level is checked, so it should not be capturing logs without any regard to the target logger or level, can you post a repro that we can look into to see why this might be happening for you?

As per my later comment, I belatedly tested and re-examined the code -- and discovered that the instrumentation is after logger level filtering takes place.  It still doesn't give the flexibility of an Appender, though.  For instance, we have a system where a fair amount of logging is done to a database -- of the same sort of material that would be covered by traces.  So while the auto-instrumentation is a good first pass, documentation for disabling that and applying the OpenTelemetryAppender where more control is needed would be great.

**Comment by JessHolle** [comment]
> > A seemingly attractive alternative to inventing another filtering configuration would be actually use a log4j Appender -- thus allowing "normal" filtering in this space
> 
> check out discussion in #5464

Thanks, I added a comment/query there -- as giving an ability to auto-instrument with minimal configuration sounds more attractive than manually configuring to use OpenTelemetryAppender.

**Comment by trask** [comment]
closing in favor of #5464
