### ISSUE TITLE
Implement database span semantic convention updates

### ISSUE THREAD

**Issue by justinfoote** [open-telemetry/opentelemetry-java-instrumentation#697]
The semantic conventions for database spans was recently updated.  See: 
https://github.com/open-telemetry/opentelemetry-specification/pull/575

The instrumentation needs to be updated with these new attributes. 

Primary among them is `db.system`, which applies to all database spans.
Also some connection-level attributes and the call-level attributes:
* `db.name`
* `db.statement`
* `db.operation`

**Comment by heyams** [comment]
Please assign this to me.  Thank you!
