### ISSUE TITLE
Configurable span attributes based on gRPC Metadata keys

### ISSUE THREAD

**Issue by fujin** [open-telemetry/opentelemetry-java-instrumentation#6979]
**Describe the solution you'd like**
I would like to be able to specify certain gRPC Custom Metadata keys from which Span Attributes should be set on the span for the RPC.

Similar to https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#capturing-http-request-and-response-headers 

**Describe alternatives you've considered**
- Manually propagating the value out of the grpc metadata
- Trying something like the CustomAttributesExtractor here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/aca80bee4085ed6bdf00f65702f49950c42ad4dd/instrumentation/grpc-1.6/library/src/test/java/io/opentelemetry/instrumentation/grpc/v1_6/GrpcTest.java#L128-L150

edit: Severin Neumann in the CNCF slack pointed out https://github.com/open-telemetry/opentelemetry-specification/issues/2843

**Comment by Tavh** [comment]
Recently opened and started working on this issue: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6991
Isn't it pretty much the same?

**Comment by fujin** [comment]
@Tavh I suppose this should be closed then?
