### ISSUE TITLE
Servlet span has 500 tag but response was 403

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-java-instrumentation#698]
I threw an exception in an authentication filter and the default servlet error handler took over and sent a 403 response. I'd expect that the parent span show a 403 error (what the response contained) instead of a 500 error.

![image](https://user-images.githubusercontent.com/17055695/87495845-371dec00-c607-11ea-9905-ae1d147b9080.png)

**Comment by trask** [comment]
Hey @FrankSpitulski, I assigned this to you as you mentioned on gitter that you may work on a PR. Keep us posted!

**Comment by iNikem** [comment]
@FrankSpitulski I am just curious, why do you think this is not the same issue as #688 ?

**Comment by trask** [comment]
I see benefit to treating them separately, because I think it's more clear what to do in general (#688), but less clear what to do in this particular case (how do we know what status code an error handler will return after the servlet throws an exception?)

**Comment by FrankSpitulski** [comment]
It very well could be. When I read #688 earlier I didn't realise it might have the same root cause since mine issue was caused by an error handler calling send response. I will keep that issue in mind to see if they can both be solved with the same PR.

**Comment by FrankSpitulski** [comment]
In the latest master branch this has been resolved. The root operation name is now ApplicationFilterChain.doFilter instead of the path and there is no longer any context (the exception) about why the 403 is sent but that's a different discussion since the response code accurately reflects what was sent.

**Comment by trask** [comment]
Great, thanks for the update!

**Comment by iNikem** [comment]
> The root operation name is now ApplicationFilterChain.doFilter instead of the path

That is unexpected. Can you please share with us the similar picture of your new trace as in original report, @FrankSpitulski ?

**Comment by FrankSpitulski** [comment]
@iNikem example auth filter failure with 0.7.0-SNAPSHOT compiled locally
![image](https://user-images.githubusercontent.com/17055695/87633085-96572b80-c6ef-11ea-88c2-ecd8e64f9c5d.png)

**Comment by iNikem** [comment]
@FrankSpitulski It would help us enormously if you could provide us with a small application demonstrating this problem. I think we have a bug which prevents root span from having proper name, but without actual working reproduction it is somewhat hard to find it.

**Comment by FrankSpitulski** [comment]
@iNikem here you go https://github.com/FrankSpitulski/rest-api-example

**Comment by iNikem** [comment]
Thank you very much @FrankSpitulski! I will take a look at this.

**Comment by iNikem** [comment]
Filed #718. Thank you @FrankSpitulski once again for this report.
