### ISSUE TITLE
Extension classes are not accessible to the application class loader

### ISSUE THREAD

**Issue by JBodkin** [open-telemetry/opentelemetry-java-instrumentation#6982]
**Describe the bug**
Instrumentation is being skipped, due to missing classes on the application class loader. These classes are provided by the extension.

```
WARN muzzleMatcher - Instrumentation skipped, mismatched references were found: cayenne [class com.example.opentelemetry.cayenne.CayenneInstrumentationModule] on jdk.internal.loader.ClassLoaders$AppClassLoader@ed17bee
WARN muzzleMatcher - -- com.example.opentelemetry.cayenne.CayenneInstrumentation$CayenneSelectAdvice:43 Missing class com.example.opentelemetry.cayenne.CayenneRequest
WARN muzzleMatcher - -- com.example.opentelemetry.cayenne.CayenneInstrumentation$CayenneSelectAdvice:44 Missing class com.example.opentelemetry.cayenne.CayenneSingletons
```

**Steps to reproduce**
See attached zip - [cayenne-extension.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/9870785/cayenne-extension.zip)

**What did you expect to see?**
The instrumentation should be applied successfully.

**What version are you using?**
1.19.1

**Comment by laurit** [comment]
You probably didn't implement `isHelperClass` method, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/writing-instrumentation-module.md

**Comment by JBodkin** [comment]
I did try adding the `getAdditionalHelperClassNames ` method, but that didn’t help. Is `isHelperClass` different?

**Comment by JBodkin** [comment]
I've tried `isHelperClass` and that works correctly.
