### ISSUE TITLE
how to customizer the http.route attribute for metrics

### ISSUE THREAD

**Issue by Shawn-Yang-AWX** [open-telemetry/opentelemetry-java-instrumentation#6987]
Hi, I want o use the `spans.duration.ns.p99` or `service.request.duration.ns.p99`, i found the http_route is not the exact one for jsonrpc request.

i want to let http_route combined with the json rpc url and the method name.  or add let it have a new attribute for  jsonrpc method name

I add a jsonrpc a listener, but it seems have no effect
```
class JsonRpcHttpRouteEnhanceListener : InvocationListener {
    override fun willInvoke(method: Method, arguments: List<JsonNode>) {
        val url = method.declaringClass.getAnnotation(JsonRpcService::class.java).value
        val finalHttpRoute = "${url}.${method.name}"
        Span.current().setAttribute("http.route", finalHttpRoute)
    }

    override fun didInvoke(
        method: Method,
        arguments: List<JsonNode>,
        result: Any?,
        error: Throwable?,
        duration: Long
    ) {
    }
}
```

any suggestion?

**Comment by mateuszrzeszutek** [comment]
Hey @Shawn-Yang-AWX ,
Try using the [`HttpRouteHolder`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api-semconv/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpRouteHolder.java) from the instrumentation-api-semconv -- that's what all our server/mvc instrumentations are using to provide the route.
