### ISSUE TITLE
is there any option of auto instrumentation to enable tracing spring `@Service` class methods?

### ISSUE THREAD

**Issue by kelystor** [open-telemetry/opentelemetry-java-instrumentation#6990]
open telemetry doesn't trace spring `@Service` class method invocation, is there any option to enable it when using auto instrumentation?

**Comment by laurit** [comment]
No, there is not. You could try using `-Dotel.instrumentation.methods.include`, see https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/#creating-spans-around-methods-with-otelinstrumentationmethodsinclude. Or you could build something on top of spring aop, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/aspects for ideas

**Comment by mateuszrzeszutek** [comment]
Alternatively, you could add [`@WithSpan`](https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/#creating-spans-around-methods-with-withspan) annotations to your service methods.

@kelystor I'm closing this issue - please reopen it (or create a new one) if you have anything else you'd like to ask about or suggest.
