### ISSUE TITLE
Add thread state as attribute to process.runtime.jvm.threads.count 

### ISSUE THREAD

**Issue by gabrielgiussi** [open-telemetry/opentelemetry-java-instrumentation#7006]
The current `process.runtime.jvm.threads.count` metric exported by the agent (or manually using [Threads#registerObservers](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/c170ec5315a41d8e2183c4566e649ca28dab9a70/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/Threads.java#L39) directly) only has as an attribute if corresponds to deamon threads or not, but knowing how many threads are in a particular state is also important.

We could include the state attribute to the existing metric `process.runtime.jvm.threads.count` or create a new one, IMO adding to the existing one makes more sense because otherwise it would be confusing having two metrics measuring the same with different attributes.

If you are ok with this change I can work on the PR.

**Comment by trask** [comment]
hey @gabrielgiussi!

> We could include the state attribute to the existing metric `process.runtime.jvm.threads.count`

this makes sense to me

the place to start would be proposing an update to the specification at https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md#jvm-metrics

cc @jack-berg @jonatan-ivanov @tuhao1020

**Comment by jonatan-ivanov** [comment]
Sounds like a good idea to me.
Please attach the javadoc about the thread states to the specs in your PR: https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.State.html

**Comment by mateuszrzeszutek** [comment]
Closing as won't do -- see the discussion in #7636 for the reason why we're not planning to implement this.
