### ISSUE TITLE
OTLP exporter does not work on java8 starting from 0.6.0

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java-instrumentation#702]
I attached log.
[log.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/4926656/log.txt)
[log2.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/4930359/log2.txt)

On of the errors is:
```
java.lang.UnsatisfiedLinkError: no io_opentelemetry_auto_shaded_io_grpc_netty_shaded_netty_tcnative_osx_x86_64 in java.library.path
```

But there are more in the log.

**Comment by malafeev** [comment]
even more strange: if I compile my application using oracle jdk-8 then I don't see traces in Lightstep dashboard,
but if with openjdk-11 then traces are available despite exceptions in the log

**Comment by anuraaga** [comment]
On Java 11 it's probably falling back to JVM's HTTP/2 support so does seem to corroborate.

**Comment by iNikem** [comment]
Compile??? Or run?

**Comment by malafeev** [comment]
run

**Comment by malafeev** [comment]
problem in shadowing of `io.grpc`.
If I remove next line from the _auto-exporters.gradle_:
`relocate "io.grpc", "io.opentelemetry.auto.shaded.io.grpc"`
then it works.

**Comment by trask** [comment]
Good find @malafeev!

I agree with your suggested fix 👍

**Comment by trask** [comment]
For background on this, that shading was probably copied from `opentelemetry-javaagent.gradle` at some point, but it doesn't apply to exporter case, and potentially causes issue for exporters which use gRPC themselves. (not sure why it suddenly broke. we definitely need e2e tests using the exporters: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/298#issuecomment-628810239)

**Comment by carlosalberto** [comment]
Hey @trask do you think a patch release will be possible, containing this fix? Or shall we wait for 0.7.0?

**Comment by trask** [comment]
What do you think @iNikem, want to test out the patch release steps?

**Comment by iNikem** [comment]
We can do that, but I personally will not have a capacity to troubleshoot it (if needed) until I deal with my "faster tests" :)
