### ISSUE TITLE
why different Baggage between SpanProcessor and Application code

### ISSUE THREAD

**Issue by yingziisme** [open-telemetry/opentelemetry-java-instrumentation#7027]
To get baggage by Baggage baggage = Baggage.current();
I put some attribute in baggage in SpanProcessor, but can not get from spring controller.

in SpanProcessor.
Baggage baggage = Baggage.current();
BaggageBuilder builder = baggage.toBuilder();
builder.put("test", "test");
builder.build().makeCurrent();

in Controller
Baggage baggage = Baggage.current();

this baggage is empty

**Comment by trask** [comment]
hi @yingziisme, calling `makeCurrent()` should generally only be done inside of a try-with-resources.

I don't think it's safe to use it in a span processor in case start/end are called from different threads

**Comment by yingziisme** [comment]
> Both SpanProcessor and Controller are in the same thread, but Baggage from Baggage.current() is different. 
how to put attributes to metrics that those attributes is in span.

**Comment by yingziisme** [comment]
> hi @yingziisme, calling `makeCurrent()` should generally only be done inside of a try-with-resources.
> 
> I don't think it's safe to use it in a span processor in case start/end are called from different threads

Both SpanProcessor and Controller are in the same thread, but Baggage from Baggage.current() is different.
how to put attributes to metrics that those attributes is in span.

**Comment by trask** [comment]
hi @yingziisme, we would probably need a standalone repro showing the issue you are facing in order to fully understand and help you further
