### ISSUE TITLE
can't active my LoggingCustomizer implementation

### ISSUE THREAD

**Issue by IcebergXTY** [open-telemetry/opentelemetry-java-instrumentation#7029]
**Is your feature request related to a problem? Please describe.**
Hello everyone,  I want to use OtlpJsonLoggingXXXExporter to export data to log file and implement my own io.opentelemetry.javaagent.tooling.LoggingCustomizer to use log4j2. 
But the LoggingCustomizer SPI loading order is random and only the first one will be active, so my implementation is not in effect.

**Describe the solution you'd like**
Add the io.opentelemetry.sdk.autoconfigure.spi.Ordered interface on LoggingCustomizer to implement sorting.

**Additional context**
bom-version: io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom-alpha:1.19.2-alpha

**Comment by IcebergXTY** [comment]
The SPI load code
```java
// io.opentelemetry.javaagent.tooling.AgentStarterImpl
  private void internalStart() {
    Iterator<LoggingCustomizer> loggingCustomizers =
        ServiceLoader.load(LoggingCustomizer.class).iterator();
    LoggingCustomizer loggingCustomizer;
    if (loggingCustomizers.hasNext()) {
      loggingCustomizer = loggingCustomizers.next();
    } else {
      loggingCustomizer = NoopLoggingCustomizer.INSTANCE;
    }

    Throwable startupError = null;
    try {
      loggingCustomizer.init();
      AgentInstaller.installBytebuddyAgent(instrumentation);
    } catch (Throwable t) {
      // this is logged below and not rethrown to avoid logging it twice
      startupError = t;
    }
    if (startupError == null) {
      loggingCustomizer.onStartupSuccess();
    } else {
      loggingCustomizer.onStartupFailure(startupError);
    }
  }
````

**Comment by mateuszrzeszutek** [comment]
The `LoggingCustomizer` is an internal interface - it's not a general purpose thing, and it will not work if you're building a javaagent extension. It was introduced to make replacing logging system in vendor distributions easier - it was not our aim to make it possible for regular users to replace the logger (for now, at least - we might make it a part of the public API in the future).

If you're building a custom distro, try excluding all the classes from the `io.opentelemetry.javaagent.logging.simple` package (you're probably interested in excluding [this one](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-internal-logging-simple/src/main/java/io/opentelemetry/javaagent/logging/simple/Slf4jSimpleLoggingCustomizer.java) the most). Then you just need to add your implementation of the `LoggingCustomizer` and `InternalLogger`.

**Comment by IcebergXTY** [comment]
@mateuszrzeszutek Thank you, it works for me.
