### ISSUE TITLE
NoClassDefFoundError when load java.sql.Date class

### ISSUE THREAD

**Issue by IcebergXTY** [open-telemetry/opentelemetry-java-instrumentation#7037]
**Is your feature request related to a problem? Please describe.**
I'm trying to custom my owe agent for our business, it works well on JDK8's project, but throws NoClassDefFoundError when running on JDK11's project (The agent is compiled by JDK8).

For some reason, I must load java.sql.Date class when agent running(etc. I use a library named [hutool](https://hutool.cn/) to simplify my work. It will load java.sql.Date when I use some util class).

After search Google, the problem can be explained by these pages([openjdk](https://bugs.openjdk.org/browse/JDK-8161269), [stackoverflow](https://stackoverflow.com/questions/67579291/why-cannot-load-java-sql-driver-with-urlclassloadername-null-in-java-11))

Then I found the io.opentelemetry.javaagent.bootstrap.AgentClassLoader not inherite PlatformClassLoader, so my code can't load java.sql.Date. (There is a JdkHttpServerClassLoader but it only loads class start with com.sun.net.httpserver ).

My question is, for what reason not to inherite the PlatformClassLoader and Is it possible to inherite? 😁

**Describe the solution you'd like**
Load java.sql.Date class success

**Describe alternatives you've considered**
If PlatformClassLoader can't inherite, I will try to contact hutool's author  if he can do something to compatible with this scenario.😳
Or maybe I can write util class myself😂, although this is not that I want to do.

**Comment by laurit** [comment]
Not delegating to `PlatformClassLoader` is deliberate, we don't wish application classes to affect agent (see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5156). To work around it you could use a custom class loader inside your agent that delegates to `PlatformClassLoader`. I think it would make sense to modify `JdkHttpServerClassLoader` to also delegate `java.sql.` (or maybe even `java.`?) to `PlatformClassLoader`  and perhaps make the list of delegated packages configurable.
