### ISSUE TITLE
Document OTEL_RESOURCE_ATTRIBUTES support in README

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#704]
Probably a new section, e.g. just above https://github.com/open-telemetry/opentelemetry-java-instrumentation#batch-span-processor.

Also, document how to use `OTEL_RESOURCE_ATTRIBUTES` to set the OTLP exporter `service.name` (probably directly within the OTLP config section, at least until #703 is resolved).

**Comment by tedsuo** [comment]
Just to clarify, does the OTEL_RESOURCE_ATTRIBUTES still exist? It seems like it is an option for OTLP, but also seems like it was removed in PR https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/424 (I assume it still does exist, based on the existence of this issue 😄 )

Related, there is an effort to standardize these common env vars here: https://github.com/open-telemetry/opentelemetry-specification/pull/666

cc @anuraaga as I saw you use this config option.

**Comment by trask** [comment]
Hey @tedsuo, `OTEL_RESOURCE_ATTRIBUTES` wasn't removed in #424. That environment variable directly configures the OpenTelemetry Java SDK.

**Comment by tedsuo** [comment]
Derp, thank you!!
