### ISSUE TITLE
Generate opentelemetry-javaagent "-all" artifact during "assemble"

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#708]
Currently

```
./gradlew assemble
```

does not generate the `-all` artifact.

Should we generate the `-all` artifact during `assemble`? (EDIT: based on @anuraaga's feedback below: yes!)

#707 is fixing `CONTRIBUTING.md` to accurately reflect the current state, but if we make this change then we can simplify `CONTRIBUTING.md` back to just running `assemble` in the future.

**Comment by anuraaga** [comment]
I think we should - I work on this repo and even then every time I do assemble, hrm?, oh shadowJar.

**Comment by trask** [comment]
I tried adding the obvious to the bottom of `javaagent.gradle`:

```
assemble.dependsOn lightShadow
assemble.dependsOn shadowJar
```

and it works great with `./gradlew :javaagent:assemble`:

```
  9180430 Aug 16 22:33 opentelemetry-javaagent-0.8.0-SNAPSHOT.jar
 25247132 Aug 16 22:33 opentelemetry-javaagent-0.8.0-SNAPSHOT-all.jar
   399555 Aug 16 22:33 opentelemetry-javaagent-0.8.0-SNAPSHOT-javadoc.jar
     3730 Aug 16 22:33 opentelemetry-javaagent-0.8.0-SNAPSHOT-sources.jar
```

**Comment by trask** [comment]
Ooops, hit comment too soon:

but it doesn't work with `./gradlew assemble`:

```
 9180430 Aug 16 22:36 opentelemetry-javaagent-0.8.0-SNAPSHOT.jar
 9180705 Aug 16 22:36 opentelemetry-javaagent-0.8.0-SNAPSHOT-all.jar
  399555 Aug 16 22:36 opentelemetry-javaagent-0.8.0-SNAPSHOT-javadoc.jar
    3730 Aug 16 22:36 opentelemetry-javaagent-0.8.0-SNAPSHOT-sources.jar
```

(note size of `-all` artifact in this case)

**Comment by anuraaga** [comment]
I think we may be able to use the shadow jar publishing configuration since we publish both unshaded and shaded

https://imperceptiblethoughts.com/shadow/publishing/

**Comment by anuraaga** [comment]
Oh but guess that's only publish, not assemble. Hmm - what's lightshadow? :)

**Comment by trask** [comment]
> what's lightshadow?

shadow, but without the exporters, therefore `light` `shadow` :smile:

**Comment by anuraaga** [comment]
Ah ok - hmm I'd expect problems with the light shadow (no classifier) but surprised to see a problem with the all one.

For replacing a jar with shadow, I always use this pattern to disable the jar task and have it depend on the shadow task (s)
https://github.com/anuraaga/aws-opentelemetry-java-instrumentation/blob/master/otelagent/build.gradle.kts#L65
