### ISSUE TITLE
Support for ForkJoinPool

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-java-instrumentation#709]
The executor instrumentation appears to be broken (not passing parent context). Tested with latest master. Steps to repro:

```java
// top level method
final ExecutorService executorService = Executors.newWorkStealingPool(10);
        executorService
                .submit(() -> IntStream.range(0, 20)
                        .parallel().unordered()
                        .forEach(this::doer))
                .get();

// traced method
@WithSpan
public void doer(int i) {
    log.info("{}", i);
}
```

Only one of the doer's spans was attached to the parent span from the top level method. The rest (19) of them had no parent. 
This issue also occurs when using a bare .parallelstream() with the common pool.
~I also tested this with a fixedThreadPool(10) and got 2 of the doer's to have the correct parent. Since there were 20 tasks and 10 threads I assume that means the context was only passed to one of the theads.~ Ignore the fixedThreadPool comment I made, forgot that parallelsteam() only uses the current executor's pool if it is a fork join pool.

**Comment by trask** [comment]
Thanks @FrankSpitulski!

I was able to reproduce this via our test infra, by adding a test to `CompletableFutureTest`:

<pre>
  def "test parallel"() {
    when:
    runUnderTrace("parent") {
      IntStream.range(0, 20)
        <b>.parallel()</b>
        .forEach({ runUnderTrace("child") {} })
    }

    then:
    assertTraces(1) {
      trace(0, 21) {
        basicSpan(it, 0, "parent")
        (1..20).each { index ->
          basicSpan(it, index, "child", span(0))
        }
      }
    }
  }
</pre>

**Comment by iNikem** [comment]
@trask Unless you are already fixing it, I would like to take it.

**Comment by trask** [comment]
Nope, all yours 👍👍

**Comment by pavolloffay** [comment]
@iNikem any update on this one?

**Comment by iNikem** [comment]
Absolutely not. Haven't even look into that direction
