### ISSUE TITLE
Document how to specify external exporter jar

### ISSUE THREAD

**Issue by malafeev** [open-telemetry/opentelemetry-java-instrumentation#713]
Document "-Dota.exporter.jar=" option

**Comment by malafeev** [comment]
I'm curious why I still cannot set label, assign it...

**Comment by trask** [comment]
Yeah, permissions is a problem. See https://github.com/open-telemetry/community/issues/397 and https://github.com/open-telemetry/community/pull/357 for hopeful solutions (cc: @tedsuo).

In the meantime, just post a comment if you want something assigned to you, and don't worry about adding labels.
