### ISSUE TITLE
Enhancement/GRPC - add additionalServerExtractors similar as already have additionalClientExtractors

### ISSUE THREAD

**Issue by arik-dig** [open-telemetry/opentelemetry-java-instrumentation#7153]
**Is your feature request related to a problem? Please describe.**
I want to add Server side extractors only, like there's already client side extractors

**Additional context**
I can create a simple PR for it, just give me the permission to do so.

**Comment by trask** [comment]
makes sense to me, go for it 👍

**Comment by arik-dig** [comment]
@trask I would be happy to do that, however I still don't have permissions to create PRs.
can you please give me the right permission?
