### ISSUE TITLE
How can I know if the application is using OpenTelemetry Java Agent?

### ISSUE THREAD

**Issue by xierunzi** [open-telemetry/opentelemetry-java-instrumentation#7178]
My application could use both agent and manually instrumentation in the same time. I want to know if the current application is using agent or not in runtime. Now I achieve this goal by checking the type of GlobalOpenTelemetry, something like below. But I don't think it is a proper way to do that, because it will initialize the GlobalOpenTelemetry, which could cause other problems.

```
            OpenTelemetry openTelemetry = GlobalOpenTelemetry.get();
            if (openTelemetry != OpenTelemetry.noop()) {
                return openTelemetry;
            }
            return customOpenTelemetry;
```

**Comment by mateuszrzeszutek** [comment]
Hey @xierunzi ,

You can check whether the [`OpenTelemetryAgent`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/OpenTelemetryAgent.java) class is loaded.

**Comment by mateuszrzeszutek** [comment]
Hey @xierunzi ,
Did my comment above answer your question?
