### ISSUE TITLE
Spring MVC does not update server span name in case of security validation failure

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#718]
Reproducible example is here https://github.com/FrankSpitulski/rest-api-example

When Spring Security filter denies request from proceeding, the name of `SERVER` span created by `Servlet3Instrumentation` is not updated to route string and remains to be `ApplicationFilterChain.doFilter`.

Not sure if routing information is available in request processing during security validation. Should investigate and fix is possible.

**Comment by kubawach** [comment]
Looking into the issue.

**Comment by iNikem** [comment]
Closed in #1122

**Comment by trask** [comment]
Thanks @FrankSpitulski for the repro!
