### ISSUE TITLE
Manually setting trace id and span id fails after v1.15.0

### ISSUE THREAD

**Issue by ham1** [open-telemetry/opentelemetry-java-instrumentation#7200]
**Describe the bug**
Before v1.15.0 (inclusive) the following code produced one trace that was linked to the expected span.

```
  // Class run in a "child" JVM
  public static void main(String[] args) {
        Span span = createSpanLinkedToParent();
        try (Scope scope = span.makeCurrent()) {
            // do stuff
        } finally {
            span.end();
        }
    }

    private static Span createSpanLinkedToParent() {
        // Fetch the trace and span IDs
        String traceIdHex = System.getProperty("otel.traceid");
        String spanIdHex = System.getProperty("otel.spanid");

        SpanContext remoteContext = SpanContext.createFromRemoteParent(
                traceIdHex,
                spanIdHex,
                TraceFlags.getSampled(),
                TraceState.getDefault());

        return GlobalOpenTelemetry.getTracer("")
                .spanBuilder("root span name")
                .setParent(Context.current().with(Span.wrap(remoteContext)))
                .startSpan();
    }
```

from v1.16.0
this seems to produce a trace in a new and separate trace.

**Environment**
OpenJDK 11.

**Comment by trask** [comment]
hi @ham1, just confirming, are you using the OTel Java agent?

**Comment by ham1** [comment]
Hello, ah yes to confirm we are using the OTel Java agent i.e. `-javaagent:opentelemetry-javaagent.jar`

**Comment by ham1** [comment]
This also seems to happen on v1.21.1.

Could this be related to having v1.2.0 imported into the application?

**Comment by trask** [comment]
@ham1 if you are able to post a standalone repro of the issue, I'd be happy to take a look at it. As @mateuszrzeszutek mentioned, the agent should support OTel API 1.0+, and if it doesn't then it's a bug.

**Comment by ham1** [comment]
Thank you for the replies, I'll close this issue for now, I don't have time to create a repro as it's not yet a big enough issue for me. I'll re-open if that changes though. :)
