### ISSUE TITLE
Use new Span.recordException method

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#723]
When open-telemetry/opentelemetry-java#1430 gets implemented, update Decorators/Tracers to use it.

**Comment by iNikem** [comment]
@anuraaga As you did open-telemetry/opentelemetry-java#1430, do you want/plan to do this soon as well? Or I can take it. I want to close this in the next few days if possible :)

**Comment by anuraaga** [comment]
Yup I'll get it :)

**Comment by anuraaga** [comment]
Fixed in #813
