### ISSUE TITLE
Support instrumentation of queue message services using aws-sdk-2.2

### ISSUE THREAD

**Issue by rafael-gumiero** [open-telemetry/opentelemetry-java-instrumentation#7243]
**Is your feature request related to a problem? Please describe.**
I currently have my microservices written in Java and would like to generate a trace of interactions with the Amazon SQS API, using aws-sdk-2.2. However, no attribute related to this interaction is generated in the trace event issued (eg: span.attributes.messaging@xxxxx).

**Describe the solution you'd like**
I would like attributes referring to Amazon SQS to be generated in my event (eg: span.attributes.messaging@destination, span.attributes.messaging@operation, span.attributes.messaging@message_id, etc).

**Describe alternatives you've considered**
We did some tests with the sdk version 1 and we didn't notice the generation either.  We were only able to generate in version 1 using the jms pattern, because in this case there is already an instrumentator for jms.

**Additional context**
N/A

**Comment by trask** [comment]
cc @rapphil
