### ISSUE TITLE
Adding servlet http.response_content_length as per spec

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-java-instrumentation#727]
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#common-attributes

**Comment by FrankSpitulski** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/726 closes this issue

**Comment by iNikem** [comment]
Closed by #726
