### ISSUE TITLE
Ability to update baggage from SpanProcessor

### ISSUE THREAD

**Issue by srinusanduri** [open-telemetry/opentelemetry-java-instrumentation#7283]
**Is your feature request related to a problem? Please describe.**
Opentelemetry Java instrumentation architecture provides the ability to plugin a custom SpanProcessor which provides the flexibility to perform our custom operations on every span start and end. However, there are some limitations on the operations we can perform from a SpanProcessor. The limitations are:

1. We can't add or update a baggage from SpanProcessor.
2. We can't add span attributes on span end. The onEnd operation in SpanProcessor is passed with `ReadableSpan`. The `oneEnd` operation is being called after marking the span as ended. Instead if the span is marked as ended after `onEnd` operation on SpanProcessor is called, it will give us the flexibility to add extra attributes towards the end of the span.

If baggage update and add attributes on span end functionalities are allowed from SpanProcessor, it will be very helpful extension that allows us to add rich custom functionalities using a SpanProcessor. 

For example, one would like to dynamically compute a baggage value from span data (attributes, events, links) in a span processor and add/update computed baggage value to current span context which can then be propagated to child spans. Similarly, one would want to compute value of a span attribute towards the end of the span and set the computed attribute on the span.

I believe, we can achieve many customizations around span start and end if these baggage and attributes management functionalities are supported from a Span Processor.

**Describe the solution you'd like**

- Ability to add/update baggage from Span Processor (both from `onStart` and `onEnd` operations).
- Ability to add span attributes from `onEnd` operation of Span Processor.

**Describe alternatives you've considered**
There is an [open enhancement](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6651) to support the baggage update functionality using global ContextCustomizer. But I believe Span Processor is the right place to achieve this. Moreover, SpanProcessor is applied to auto instrumented as well as manually instrumented spans whereas ContextCustomizers are applied only for auto instrumented spans.

**Comment by srinusanduri** [comment]
Thank you @trask. 

I will create an enhancement request in opentelemetry-java repository for baggage update in SpanProcessor functionality. And I will create a separate enhancement request for ability to add attribute from SpanProcessor's `onEnd` method.

Regarding GlobalContextCustomizer application for auto-instrumented spans and manual instrumented spans, I tested this doing a simple implementation of [this GlobalContextCustomizer enhancement](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/6651). Its NOT being applied for manually instrumented spans.

My simple implementation is: Created a `GlobalContextCustomizer` interface and a `GlobalContextCustomizersRegistry` with two static methods `register(GlobalContextCustomizer)` and `getGolablCustomizers()` in [instrumentation-api](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation-api). And applied registered GlobalContextCustomizers in [Instrumenter here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/Instrumenter.java#L186). And then registered a GlobalContextCustomizer in distro.

Manually created spans construct is as follows:
```
       Span span = tracer.spanBuilder("vdsn-preprocess").startSpan();
        try (Scope scope = span.makeCurrent()) {
            doSomeWork();
        } catch (Throwable t) {
            span.setStatus(StatusCode.ERROR, t.getMessage());
        } finally {
            span.end();
        }
```

Whereas **SpanProcessor** is being applied for both manual and auto spans. My observation is that SpanProcessor is being called from `SdkSpan` which is the Span implementation used for both manual and auto instrumented spans.

**Comment by trask** [comment]
yeah, it would only work for manual instrumentation that uses `opentelemetry-instrumentation-api`, not for manual instrumentation that uses the underlying `opentelemetry-api` directly.

(and it may require some bridging in https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/opentelemetry-instrumentation-api/javaagent to make even that work)

**Comment by tylerbenson** [comment]
+1.  I would also love the ability to update the baggage from within the span processor.  I think it will be very difficult though due to a lifecycle mismatch.  In OTel, Baggage is tied to a context scope and Spans are created independent of that. The best option I can think of where this would align is being able to modify the baggage when a span is added to the context. I don't think there is a place where you can modify both the span and baggage though.
