### ISSUE TITLE
Ideas for PR comment-driven automation

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#7290]
* `/spotless` - ./gradlew spotlessApply
* `/rebase`- merge main into the PR branch - this would be helpful for testLatestDeps fixes
* `/license` - ./gradlew generateLicenseReport - this would be helpful on some dependabot PRs
* `/rerun` - rerun failed tests, helpful for contributors who don't normally have this level of access

**Comment by mateuszrzeszutek** [comment]
Also maybe `/api-diff`? Would be quite useful in the SDK repo too

**Comment by 43754** [comment]
ludoviccroenne9@gmail.com

**Comment by 43754** [comment]
Aide

**Comment by trask** [comment]
Closing, as the more useful of these (spotless, license) require running gradle against PR branch changes under elevated permissions
