### ISSUE TITLE
Flag latestDepTest dependency configuration behind a property

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#730]
Sometimes IntelliJ will resolve all the dependencies of `latestDepTest` because it uses dynamic versions. This takes a long time and is not helpful at all during development so it would be nice if we can avoid it. I think it would allow us to consider reenabling source jar downloads for dependencies too which we recently disabled.

Most projects have a lot of duplication between defining dependencies for build and for latestDepTest. I suspect we can create our own custom configuration that adds to the normal compile classpath, but when it has dependencies added to it, also converts it into a latestDep dependency only when the property is enabled. So this would be a good chance to solve that duplication too.

**Comment by anuraaga** [comment]
Out of the contributor experience issues, I may consider this relatively high priority. It's really painful when the `latestDepTest` snapshots refresh during the middle of normal development because you need IDE to pick up a new dependency (but should only work on that new dependency instead of downloading the world...)

**Comment by iNikem** [comment]
I think we don't need another custom configuration. `useLatestDep` flag should change standard `testImplementation` dependencies. Although I don't remember from the top of my head what extra tools Gradle offers for custom dependencies...
