### ISSUE TITLE
Update the opentelemetry-spring-boot-autoconfigure to Spring Boot 3

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#7312]
Now that Spring Boot 3 is out, we should probably update our own starter to the latest version.

**Comment by jeanbisutti** [comment]
@mateuszrzeszutek Could you please explain why?

Today, the OpenTelemetry Spring Starter works with Spring Boot 2 and Spring Boot 3.
Update to Spring Boot 3 will require to compile with Java 17.
So, update to Spring Boot 3 will limit the use cases for which the OpenTelemetry starter could be used.

**Comment by mateuszrzeszutek** [comment]
Huh, I created this issue back when we had no support for Spring Boot 3. I think we've talked about several different approaches to handling this (e.g. separate starters for 2 and 3), but Lauri's managed to fix it without introducing any breaking changes.

Anyway, I think we can consider this issue closed by https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7784
