### ISSUE TITLE
Add OpenLiberty as a supported application server

### ISSUE THREAD

**Issue by fmhwong** [open-telemetry/opentelemetry-java-instrumentation#7346]
**Is your feature request related to a problem? Please describe.**
Add OpenLiberty as a supported application server

**Describe the solution you'd like**
Is it possible to add [OpenLiberty](https://openliberty.io/) to the list of application servers in the [Supported libraries, frameworks, application servers, and JVMs page](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#application-servers)? 

**Describe alternatives you've considered**

**Additional context**

**Comment by trask** [comment]
hi @fmhwong!

I think:

> Application server | Version | JVM | OS
> -- | -- | -- | --
> Websphere Liberty Profile | 20.x, 21.x | OpenJDK 8 | ubuntu-latest, windows-latest

is meant to be Open Liberty, as we are running smoke tests using the `open-liberty` docker image:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/bbcd3d1cb4352a1d110edc455f018fc1bb6eaefd/smoke-tests/images/servlet/src/liberty.dockerfile#L4

**Comment by fmhwong** [comment]
Would you mind to change the name from "WebSphere Liberty Profile" to "OpenLiberty" and link to https://openliberty.io/?  I can submit a PR if you're okay with this.

**Comment by trask** [comment]
> I can submit a PR if you're okay with this.

👍
