### ISSUE TITLE
Spring Boot auto instrumentation cannot be disabled entirely 

### ISSUE THREAD

**Issue by ViliusS** [open-telemetry/opentelemetry-java-instrumentation#7357]
**Describe the bug**
When `opentelemetry-spring-boot-starter` is used there is no possibility to disable OpenTelemetry SDK entirely. Even if I use `otel.sdk.disabled=true` SDK still gets loaded.

**Steps to reproduce**
1. Start empty Spring Boot project with imported `opentelemetry-spring-boot-starter` in POM file.
2. Set `otel.sdk.disabled=true` and `otel.exporter.logging.enabled=true` in `application.properties` file.
3. Watch tracer spans logged in stdout.

**What did you expect to see?**
I would have expected no traces logged.

**What version are you using?**
Spring Boot 2.7.4
opentelemetry-instrumentation-bom-alpha 1.20.2-alpha

**Additional context**
I also see that other Otel SDK autoconfigure parameters are not working either. For example `otel.metrics.exporter=none` doesn't work, I have to use `otel.exporter.otlp.metrics.enabled=false` from Spring Boot auto instrumentation instead. Not sure if this one by design.

**Comment by laurit** [comment]
System properties like `otel.sdk.disabled` only work when you are using [opentelemetry sdk autoconfigure extension](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md). Spring boot starter does not use it, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/933874be14f196c7b11b1e931f35e5a1e8b229ac/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/OpenTelemetryAutoConfiguration.java#L118

**Comment by ViliusS** [comment]
Is there another property which can be used as an all-kill switch for Spring Boot auto instrumentation?

**Comment by ViliusS** [comment]
Yes, I know I can create a custom property and do it programmatically, but this ticket is more about what properties are provided by `instrumentation-spring-boot-starter`. The expectation is that most Spring Boot "features" controlled by autoconfigure can be enabled/disabled.
If that's not the case with `instrumentation-spring-boot-starter`, then maybe this ticket needs to be requalified to Feature Request.

**Comment by mateuszrzeszutek** [comment]
> If that's not the case with `instrumentation-spring-boot-starter`, then maybe this ticket needs to be reclassified to Feature Request.

Yeah, I'd say that the spring starter definitely should support `otel.sdk.disabled`. Let's make it an enhancement then.
