### ISSUE TITLE
Markdown spotless should also be per-project

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#736]
I always get confused by the fact that all markdown in the repo is checked by the top level spotless check, even when the file is in a subproject. Presumably this also reduces the chance for up-to-date checks to work. Is it possible to make markdown in a subproject also checked by the subproject's spotless?

**Comment by trask** [comment]
I think this is because we have markdown outside of gradle modules that wouldn't get checked otherwise. Maybe we could scope down the top-level check to just `*.md,docs/**/*.md` (we don't have any markdown under `docs` yet, but we will soon #734).
