### ISSUE TITLE
Update attributes of span in auto-instrumentation

### ISSUE THREAD

**Issue by Ipuvi** [open-telemetry/opentelemetry-java-instrumentation#7365]
### Problem Statement
I'm using auto-instrumentation javaagent jar in my application but with that for QuartzJob the operation name generated seems a bit complex while debugging, I want to update the operation name and some span attributes only for these traces and want to keep rest of the traces generated from auto-instrumentation intact, is that possible? I tried looking at extensions but couldn't find much out of it.
Can someone please help?
#HelpWanted

**Comment by mateuszrzeszutek** [comment]
Hey @Ipuvi ,

In your job (or in a custom `JobListener`) you can use [`Span.current()`](https://opentelemetry.io/docs/instrumentation/java/manual/#get-the-current-span) to get the current span and update its name or attributes.

**Comment by Ipuvi** [comment]
@mateuszrzeszutek I was able to update name using your suggestions. Thanks :-) 
Quick question though, is it also possible to not end a particular span and continue the same span?

**Comment by mateuszrzeszutek** [comment]
> Quick question though, is it also possible to not end a particular span and continue the same span?

No, that'd require changing the instrumentation code.

**Comment by Ipuvi** [comment]
Ok, thanks :-)
