### ISSUE TITLE
Apply trace.classes.exclude only to annotation instrumentation

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#737]
The similarly named `trace.methods.exclude` only applies to annotation instrumentation.

I thought (incorrectly) that `trace.classes.exclude` also only applied to annotation instrumentation as well.

Do we want `trace.classes.exclude` to apply to all instrumentation? This seems dangerous as we have some instrumentation which works together (and can be turned on/off with the same "instrumentation name" flag).

See #344 for some potentially good background discussion about `trace.methods.exclude`.

Also see https://github.com/open-telemetry/opentelemetry-java-instrumentation#disabled-instrumentations and https://github.com/open-telemetry/opentelemetry-java-instrumentation#configuration for other data points.

**Comment by iNikem** [comment]
> Do we want `trace.classes.exclude` to apply to all instrumentation? This seems dangerous as we have some instrumentation which works together (and can be turned on/off with the same "instrumentation name" flag).

Yes, we do. This flag is meant to exclude a class from **all** instrumentations. Thus the second point is in fact invalid: if class is excluded, it is excluded from all instrumentations.

This configuration options is the only way that I know of to achieve 2 things:

- completely silence spans from a given class/package
- quick workaround for an instrumentation bug, when byte code in one specific class is problematic.

**Comment by trask** [comment]
Makes sense.

It would still be nice to resolve the confusion between `trace.classes.exclude` and `trace.methods.exclude` looking similar but not having the same behavior.

Some options:
* Make `trace.methods.exclude` also apply to all instrumentation
  * This doesn't seem to be a needed feature though
* Rename `trace.methods.exclude` to `trace.annotation.methods.exclude` (or similar)
  * This might look odd in [the doc](https://github.com/open-telemetry/opentelemetry-java-instrumentation#configuration) where we explain to use both `trace.classes.exclude` and `trace.annotation.methods.exclude` to control annotation instrumentation 
* Rename `trace.methods.exclude` to `trace.annotation.methods.exclude` and add `trace.annotation.classes.exclude` which only applies to annotation instrumentation

**Comment by iNikem** [comment]
I propose to rename `trace.methods.exclude` to `trace.annotated.methods.exclude` and to change our doc to speak about two `exclude` options separately.

**Comment by trask** [comment]
Great, I like that. Opened #760 for this change, and closing this.

**Comment by krinklesaurus** [comment]
Hey @trask @iNikem 
I know this is a pretty old issue but may I ask why the decision was made to only allow this for annotated methods? 

We would like to disable certain methods which are executed in a loop, and, if I understand correctly, we would now have to add the annotation just to be able to disable it 🤪 I think the generic approach is much more powerful and flexible. And it's also kind of confusing to have two different approaches, one for classes and one for methods

**Comment by trask** [comment]
hi @krinklesaurus! can you open a new issue and explain your use case in a bit more detail? thx

**Comment by krinklesaurus** [comment]
@trask sure thing, here you go: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7535 thanks for the quick response :-)
