### ISSUE TITLE
can we record 'thread name' in logback instrument

### ISSUE THREAD

**Issue by IcebergXTY** [open-telemetry/opentelemetry-java-instrumentation#7389]
**Is your feature request related to a problem? Please describe.**
Hi, I I found that logback was missing thread name and there is a comment on method `io.opentelemetry.instrumentation.logback.appender.v1_0.internal.LoggingEventMapper#mapLoggingEvent`
![image](https://user-images.githubusercontent.com/15325243/207007296-8f11816f-af6c-43da-886c-1136af2962ad.png)
'Marker' and 'MDC' can config to enable record,  the 'thread name' has no config to enable it.
But sometimes 'thread name' is so useful when troubleshooting problems（for example we can locate specific business by the name）.

**Describe the solution you'd like**
provide a config to enable record the 'thread name'

**Comment by trask** [comment]
hi @IcebergXTY! `-Dotel.instrumentation.logback-appender.experimental-log-attributes=true` should do what you want (though I don't see it documented anywhere)

**Comment by IcebergXTY** [comment]
It works, thank you
