### ISSUE TITLE
The otel.instrumentation.common.db-statement-sanitizer.enabled parameter is not effective for PreparedStatement?

### ISSUE THREAD

**Issue by lvguoqiang** [open-telemetry/opentelemetry-java-instrumentation#7400]
The otel.instrumentation.common.db-statement-sanitizer.enabled parameter is not effective for PreparedStatement?

**Comment by mateuszrzeszutek** [comment]
(Moving issue to the instrumentation repo)

Hey @lvguoqiang ,

Queries/statements passed to the `PreparedStatement` already contain placeholders; you're seeing them exactly as the JDBC API receives them.

**Comment by lvguoqiang** [comment]
Is there a way to show PreparedStatement as the original value, I tested by setting OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED false did not take effect

**Comment by mateuszrzeszutek** [comment]
If `otel.instrumentation.common.db-statement-sanitizer.enabled` is set to false then what you're seeing is the original value; when the sanitization is disabled the javaagent does not do anything with the DB statements, they're exported in the same form the JDBC API sees them.

**Comment by ryanrupp** [comment]
It would be nice to have an opt-in mode that "unbinds" the bind variables, maybe just for some subset of queries (slow), or writes etc. This can be done by having instrumentation intercept the `PreparedStatement` set arguments then lazily (if conditional) build into the literal SQL. I've written about this in the past for Elastic AMP agent [here](https://github.com/elastic/apm/issues/220) and in the OpenTelemetry slack [here](https://cloud-native.slack.com/archives/C0150QF88FL/p1647980832941739). I believe [New Relic](https://docs.newrelic.com/docs/apm/transactions/transaction-traces/security-transaction-traces/#database)  (unclear if this is just literals or binds as well, user [here](https://github.com/elastic/apm/issues/220#issuecomment-628191934) seems to say it's binds) and [AppDynamics](https://docs.appdynamics.com/appd/21.x/21.5/en/appdynamics-essentials/sensitive-data-collection-and-security#id-.SensitiveDataCollectionandSecurityv21.1-SuppressRawSQLCapture) have similar features although I haven't used them specifically. Understandably this has performance/security/privacy concerns though so would be opt-in with caution.

**Comment by trask** [comment]
can someone open a new issue to request this feature? surprisingly I don't think we have an issue for it yet

**Comment by ryanrupp** [comment]
@trask I logged https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7413

**Comment by trask** [comment]
@lvguoqiang let us know if this can be closed in favor of #7413? thx!

**Comment by Neptunium1129** [comment]
Why isn't there a basic binding method? Does no one use it anymore?
