### ISSUE TITLE
Fully support autoconfiguration arguments for otlp exporter in the Spring starter

### ISSUE THREAD

**Issue by vringar** [open-telemetry/opentelemetry-java-instrumentation#7403]
**Is your feature request related to a problem? Please describe.**
I can't specify the headers that I need to send spans to my backend using [the standard opentelemetry java properties](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#otlp-exporter-span-metric-and-log-exporters)

**Describe the solution you'd like**
I would like to be able to just have the spring instrumentation pick up these properties and configure the span exporter correctly.

**Describe alternatives you've considered**
I could also try to reimplement the default parsing logic myself or provide an OpenTelemtry bean from my vendor, so that the autoconfiguration picks it up instead.

**Comment by mateuszrzeszutek** [comment]
Hey @vringar ,

Are you using the javaagent? Or the opentelemetry-spring-starter module?

**Comment by vringar** [comment]
Hey @mateuszrzeszutek,

I'm using the spring Boot Starter Module.

**Comment by jeanbisutti** [comment]
`otel.exporter.otlp.headers` property was implemented in #9950

It seems that it remains the following properties to implement:
* `otel.exporter.otlp.traces.headers`
* `otel.exporter.otlp.metrics.headers`
* `otel.exporter.otlp.logs.headers`

**Comment by zeitlinger** [comment]
The signal specific headers are also supported :smile:
