### ISSUE TITLE
ContainerResource extract container.id in Host env

### ISSUE THREAD

**Issue by wzy531a** [open-telemetry/opentelemetry-java-instrumentation#7437]
**Describe the bug**
When I use javaagent to collect trace in the host environment, I found that there is containerID in the resource.attributes, and the problem seems to be the [isValidBase16String](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/ec2517686191f7cf8432e6a7e7345d77ba5134e4/instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/CgroupV1ContainerIdExtractor.java#L89) judgment method of [ContainerResource](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/resources/library/src/main/java/io/opentelemetry/instrumentation/resources/ContainerResource.java#L55)

**Steps to reproduce**
The **/proc/self/cgroup** content line is `1:name=systemd:/user.slice/user-0.slice/session-31207.scope`

**What did you see instead?**
It well extract `31207` as container.id, but the environment is host instead of container.

**What version are you using?**
otel-javaagent 1.20.2

**Environment**
centos 7.5

**Additional context**

**Comment by trask** [comment]
cc @breedx-splk in case you have any ideas

**Comment by breedx-splk** [comment]
Relates to #7176. Maybe relates to [golang #3508](https://github.com/open-telemetry/opentelemetry-go/pull/3508).
