### ISSUE TITLE
Zipkin B3 trace context to W3C trace context migration without breaking 

### ISSUE THREAD

**Issue by Ipuvi** [open-telemetry/opentelemetry-java-instrumentation#7457]
Hi Team
We have an application which was using brave for adding traces/spans in our application. In this application, we were adding the traceContextMap in events meta (in events sent to/from a kafka/grpc based application). 
These traceId/spanId from events meta was in turn used to segregate info specific to a particular trace. But now as we are migrating to opentelemetry-autoinstrumentation from brave, Can someone help on how to correlate these zipkins-b3-traceId to w3c one's without any breaking change?

**Comment by trask** [comment]
hi @Ipuvi !

you can specify multiple trace context propagation formats to support interop with other formats until you are able to move all of you systems to w3c

**Comment by mateuszrzeszutek** [comment]
Hey @Ipuvi ,
Have you tried Trask's suggestion?

**Comment by Ipuvi** [comment]
Hey @mateuszrzeszutek 
I tried I could still see only 1 type of trace Ids, all I did was added that VM option while running application along with javaagent, is there anything else to be done?

**Comment by mateuszrzeszutek** [comment]
Can you post your propagator config, and what exactly you're seeing and what you expect?
