### ISSUE TITLE
Don't run latestDepTest on PRs

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#748]
`latestDepTest` runs the instrumentation tests against the latest versions of the instrumented libraries that are found in maven central.

This can break CI any time a new version of an instrumented library is released (sometimes due to the instrumentation being incompatible, and sometimes due to the tests themselves being incompatible with the new version).

This can be confusing for contributors who submit a PR and see a CI failure in a completely unrelated module, e.g. https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/726#issuecomment-662157487

What do you think of only running `latestDepTest` on merge to master (or maybe nightly)?

**Comment by anuraaga** [comment]
Ah I completely forgot about this, and had the same idea. I recommend nightly - this is to catch breakage when a dependency releases their new version, and it's extremely rare for a dependency to release multiple versions in a day. We can catch most conceivable breakage with nightly I think.

**Comment by iNikem** [comment]
I would support nightly, but the current state of affairs shows, that we mostly ignore failures from nightly builds :( I will add a separate issue about notifications
