### ISSUE TITLE
How to ignore some traces or methods being collected

### ISSUE THREAD

**Issue by kingkongpoon** [open-telemetry/opentelemetry-java-instrumentation#7511]
Java 8
SpringBoot 2.3.5.RELEASE
otel 1.19.0

my project have a kafka consumer
then it will collect too many traces which I don't want 

code like this

```
@Component
public class KafkaMessageReceive {
    @KafkaListener(topics = "test-kafka")
    public void processMessageString(String content) {
        log.info("test-kafka", content);
    }
}
```

![image](https://user-images.githubusercontent.com/24726697/210761181-16f55afd-7603-4d23-a058-249644e4741c.png)

Operation like this 
KafkaMessageListenerContainer$ListenerConsumer$$Lambda$.run

this is otlp metrics for per minute
![image](https://user-images.githubusercontent.com/24726697/210761610-26ce72f8-15a8-4f52-a2be-d71ac53ef6a6.png)

```
-Dotel.traces.exporter=otlp -Dotel.exporter.otlp.endpoint=http://xxxx:xx -Dotel.metrics.exporter=otlp 
 -Dotel.service.name=666666  -Dotel.logs.exporter=none 
-Dotel.metric.export.interval=60000 -Dotel.javaagent.exclude-classes="com.example.service.KafkaMessageReceive"  
-javaagent:xxx\opentelemetry-javaagent.jar
```

how to ignore it?

**Comment by mateuszrzeszutek** [comment]
Hey @kingkongpoon ,

Can you post full contents of that unwanted span?

**Comment by kingkongpoon** [comment]
HI @mateuszrzeszutek .
do you mean this?

KafkaMessageListenerContainer$ListenerConsumer$$Lambda$.run
org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer$$Lambda$1163/1414529337

![image](https://user-images.githubusercontent.com/24726697/210912764-a166ad4a-f4ed-4bad-8f4a-92f2784b6f22.png)

or the original span data in elasticsearch ?

**Comment by kingkongpoon** [comment]
Although there is no new message from kafka ,it will still produce new traces from kafka listener consumer,why?

**Comment by mateuszrzeszutek** [comment]
Yeah, these spans are created by the spring scheduler.
To work around this issue, can you try running your application with the `-Dotel.instrumentation.spring-scheduling.enabled=false` option? It'll disable the spring scheduler instrumentation.

**Comment by kingkongpoon** [comment]
Ok, it works,thanks a lot.  :)

**Comment by kingkongpoon** [comment]
In the same project,why it notice 
clock skew adjustment disabled; not applying calculated delta of  xxxx ?
![image](https://user-images.githubusercontent.com/24726697/211520512-f9b117e2-daf9-4fab-be61-c64573ed2c73.png)

**Comment by mateuszrzeszutek** [comment]
That's a jaeger feature: https://www.jaegertracing.io/docs/1.21/deployment/#clock-skew-adjustment

**Comment by kingkongpoon** [comment]
Hello @mateuszrzeszutek 
I think this problem still exist
this is my env prod span data
![image](https://user-images.githubusercontent.com/24726697/212591790-e562441a-7fdd-40b6-ae1b-3a5ada326428.png)
jaeger
![image](https://user-images.githubusercontent.com/24726697/212592096-5fe36e22-e4bd-44f9-9a13-fce734b47cf0.png)
otlp
![image](https://user-images.githubusercontent.com/24726697/212592245-5ddee7b2-6218-41bc-9342-7e0c46c45e4e.png)
![image](https://user-images.githubusercontent.com/24726697/212592283-0be97f35-d79a-41b0-8395-dd5717998537.png)

otlp span collector metrics
![image](https://user-images.githubusercontent.com/24726697/212592538-a01855a7-2c89-4d8f-8c16-835f05af477c.png)
it still seem too many traces ?

**Comment by mateuszrzeszutek** [comment]
Hey @kingkongpoon ,

What version of the agent are you using? The fix I made was included as a part of the [1.22.0 release](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.22.0).

**Comment by kingkongpoon** [comment]
@mateuszrzeszutek Hello
the kafka problem has sloved,
but the new problem seem different
I update to 1.22.1
but the problem do not slove.
is there any metrics like processedSpans can tell me which method product such tracs/spans?
![image](https://user-images.githubusercontent.com/24726697/212644087-ee0aac62-53e4-4a93-a614-0cf28f44ed78.png)

**Comment by mateuszrzeszutek** [comment]
The `processedSpans` counter is defined in the SDK repo: https://github.com/open-telemetry/opentelemetry-java/blob/aa873a05be27137d276de5fa50557add5f78184c/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/export/BatchSpanProcessor.java#L200

If you're missing it, then perhaps there is a bug in the OTel SDK - please file an issue in the opentelemetry-java repo.

**Comment by kingkongpoon** [comment]
Hey @mateuszrzeszutek 
I can find processedSpans
but it only tell me how many spans, it can not tell me why my program product lot's of useless spans.
is there any metrics like this
![image](https://user-images.githubusercontent.com/24726697/212796147-922b6a12-7e9e-423f-9d9e-2377c5126842.png)
so I can find out why product so many spans ?

**Comment by kingkongpoon** [comment]
some spans like this how to exclude ?
may be like -Dotel.instrumentation.spring-scheduling.enabled=false ?
![image](https://user-images.githubusercontent.com/24726697/212826483-6e17073e-52a8-4d16-b3e2-ec04f420e4f9.png)
![image](https://user-images.githubusercontent.com/24726697/212825461-f9a36664-7cba-4b9b-869f-104e3b4fc847.png)

**Comment by mateuszrzeszutek** [comment]
> but it only tell me how many spans, it can not tell me why my program product lot's of useless spans.
> is there any metrics like this

No, there are no metrics like that. You can investigate the spans themselves though.

> some spans like this how to exclude ?
> may be like -Dotel.instrumentation.spring-scheduling.enabled=false ?

These look like SERVER spans; perhaps there is some process that periodically calls your application? Disabling the server instrumentations entirely is not exactly a good idea; you could use a custom sampler to filter these out though - take a look at #1060, might be useful for your case.

Anyway, since this deviated from the original topic, if you run into any other problems please open a new issue.

**Comment by trask** [comment]
hi @MartinEmrich, can you open a new issue for your question? thx

**Comment by MartinEmrich** [comment]
@trask done: #10076
