### ISSUE TITLE
Store un/shaded gRPC Context in the Context itself?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#752]
In #611 @iNikem found that performance of field vs context for storage often leans towards context being faster. There are some questions about environment, etc in the benchmark, but as a simple case, does it make sense to at least store the bridge Context using Context instead of `InstrumentationContext` (a mouthful :D)? I ran into this issue in #746 where @trask may still point me at some magic to do the translation outside the bytecode level, but wondering if we can simplify this in general.

**Comment by iNikem** [comment]
Can I ask for an explanation, why do we have 2 contexts here? Shaded/unshaded? Does it mean that we want to have a separate gRPC Context which is totally separate from the one that application potentially uses?

**Comment by trask** [comment]
> In #611 @iNikem found that performance of field vs context for storage often leans towards context being faster

Sorry, I had been meaning to dig into those findings, because they didn't align with my expectation.

Tracked down the issue today, the `StorageKey` class which was being used as the `InstrumentationContext` key, was part of the instrumentation itself, and so it wasn't being instrumented itself, and so the field was not being added to it, and so `InstrumentationContext` was falling back to a map.

New numbers:

```
Benchmark                                                     Mode  Cnt     Score     Error   Units
StorageBenchmark.contextStorage                               avgt   20    26.768 ±   0.331   ns/op
StorageBenchmark.contextStorage:·gc.alloc.rate                avgt   20  2089.803 ±  25.111  MB/sec
StorageBenchmark.contextStorage:·gc.alloc.rate.norm           avgt   20    88.000 ±   0.001    B/op
StorageBenchmark.fieldStorage                                 avgt   20     3.174 ±   0.045   ns/op
StorageBenchmark.fieldStorage:·gc.alloc.rate                  avgt   20     0.004 ±   0.001  MB/sec
StorageBenchmark.fieldStorage:·gc.alloc.rate.norm             avgt   20    ? 10??              B/op
StorageBenchmark.noStorage                                    avgt   20     3.838 ±   0.075   ns/op
StorageBenchmark.noStorage:·gc.alloc.rate                     avgt   20     0.004 ±   0.001  MB/sec
StorageBenchmark.noStorage:·gc.alloc.rate.norm                avgt   20    ? 10??              B/op
```

I pushed PR with my changes to @iNikem's branch: https://github.com/iNikem/opentelemetry-java-instrumentation/pull/2

**Comment by trask** [comment]
> Can I ask for an explanation, why do we have 2 contexts here? Shaded/unshaded? Does it mean that we want to have a separate gRPC Context which is totally separate from the one that application potentially uses?

We need shaded gRPC context to match our shaded OpenTelemetry API, which are all in the bootstrap class loader. Application may or may not bring unshaded OpenTelemetry API. If they do bring unshaded OpenTelemetry API then we do the bridge dance.

**Comment by anuraaga** [comment]
Now that the numbers are convincing, let me go ahead and close this :) It was tedious propagating the store down from the bytecode manipulation method but not terrible.
