### ISSUE TITLE
Create an issue if nightly build fails

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#753]
We postpone several of mandatory code checks to nightly builds, e.g. #748 . But nightly build failures are very easy to ignore. Should at least create a new issue whenever build fails. Probably requires #678

**Comment by trask** [comment]
hey @Brandon-Kimberly! do you have any suggestion for how to automatically create a github issue if our nightly build fails? Ideally, it would not keep spamming issues if we do not fix it for a few days, but that could be a future enhancement. @iNikem just submitted a PR that is adding Github actions nightly build: #775

**Comment by anuraaga** [comment]
I'd generally start with looking at awesome actions

https://github.com/sdras/awesome-actions

Looks like there's a create issue from file action there.

Not sure of a good way to avoid refiling the same issue but I'd be ok with it even if it refiles.
