### ISSUE TITLE
Allow exclusion from tracing for any method (not just annotated methods)

### ISSUE THREAD

**Issue by krinklesaurus** [open-telemetry/opentelemetry-java-instrumentation#7535]
**Is your feature request related to a problem? Please describe.**
It would be benefitial to be able to exclude a method from tracing. In our case, we have a background task polling some external resource, and we don't need to have spans in case there is nothing to process.

Some pseudo code illustrating the issue

        class Scratch {
            public static void main(String[] args) {
                while(true) {
                    String result = poll();
                    if(result!=null) {
                        process(result);
                    }
                }
            }

            public static void process(String process) {
                // do something with tracing
            }

            // no need to trace poll() *for us*
            public static String poll() {
                if (sometimes) {
                    return null;
                }
                return "someValue";
            }

        }

Issue https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/737 already addressed this, but for some reason it was decided to only support this for methods annotated with `@WithSpan`. So in our case we would have to add the annotation just to be able to exclude it from tracing. A similar functionality is already in place for classes where arbitrary classes can just be excluded. Imho it would be better to allow excluding any methods because it is more flexible and the feature would be the same for both classes AND methods.

Interestingly, the initial issue's title [Apply trace.classes.exclude only to annotation instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/737) sounds like the initial idea was to limit exclusion to annotated classes only, too.  

**Describe the solution you'd like**
`trace.annotated.methods.exclude` should be `trace.methods.exclude` and behave the same as `trace.classes.exclude` (but for methods, of course).

**Comment by trask** [comment]
hi @krinklesaurus, where is the span you are trying to suppress coming from? does your `poll()` method call some http client, and you are trying to suppress the span which is captured via auto-instrumentation of that http client?

**Comment by krinklesaurus** [comment]
Hey @trask 

so this is what it looks like in the UI

        ClassA.execute()
            -> ClassB.nextEvent()
                -> ClassB.someMethodCallingRedis()
        ClassA.execute()
            -> ClassB.nextEvent()
                -> ClassB.someMethodCallingRedis()
            -> ClassB.processEvent() // <- only run when event was polled
        ClassA.execute()
            -> ClassB.nextEvent()
                -> ClassB.someMethodCallingRedis()

This is what it looks like to us. We already excluded all Redis calls by setting `OTEL_INSTRUMENTATION_REDISSON_ENABLED=false`. We would also like to suppress `ClassB.nextEvent()` and `ClassB.someMethodCallingRedis()`.

**Comment by krinklesaurus** [comment]
I'm not sure I'm following, I think we just use the default Java instrumentation? The internal library we use it provided by another team of ours. Our config looks like this I think

    OTEL_EXPORTER_JAEGER_ENDPOINT	http://${_jaeger_host}:${_jaeger_port}/api/traces	
    OTEL_METRICS_EXPORTER	none	
    OTEL_PROPAGATORS	baggage,tracecontext,jaeger	
    OTEL_TRACES_EXPORTER	jaeger	
    OTEL_TRACES_SAMPLER	parentbased_always_off	
    OTEL_RESOURCE_ATTRIBUTES	snow.id=${_snow_id},service.name=${_service_name}
    OTEL_INSTRUMENTATION_REDISSON_ENABLED	false

Does this answer your question? 🤔

**Comment by trask** [comment]
no, sorry, I'm not following either 😄

maybe if you can provide a small repro that would help clarify?
