### ISSUE TITLE
Package rename: io.opentelemetry.auto.instrumentation -> io.opentelemetry.instrumentation.auto

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#754]
Boring but I think we do need to make this change to match our artifacts and follow the general pattern of a common prefix for packages in a project.

**Comment by trask** [comment]
this will give us something like:

* `io.opentelemetry.instrumentation.armeria`
* `io.opentelemetry.instrumentation.apachehttpclient`
* ...
* `io.opentelemetry.instrumentation.vertx`
* <b>`io.opentelemetry.instrumentation.api`</b>
* <b>`io.opentelemetry.instrumentation.auto`</b>
  * `io.opentelemetry.instrumentation.auto.armeria`
  * `io.opentelemetry.instrumentation.auto.apachehttpclient`
  * ...
  * `io.opentelemetry.instrumentation.auto.vertx`
  * <b>`io.opentelemetry.instrumentation.auto.api`</b>

i like this.

but i'm not quite sure how `auto-tooling`, `auto-bootstrap` fit in here best.

putting these under `io.opentelemetry.instrumentation.auto` pollutes that namespace which would be nice to be reserved for instrumentation ( + the `api` package).

so maybe:

* `io.opentelemetry.instrumentation.agent.tooling`
* `io.opentelemetry.instrumentation.agent.bootstrap`

or even better i think:

* `io.opentelemetry.javaagent.tooling`
* `io.opentelemetry.javaagent.bootstrap`

after #884, there won't be circular dependency between `io.opentelemetry.javaagent` and `io.opentelemetry.instrumentation`, which was something i didn't like about this idea earlier https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/597#issuecomment-651429565

**Comment by iNikem** [comment]
If our build scripts and other tooling can cope with 2 namespaces, then I think io.opentelemetry.javaagent is a good one

**Comment by trask** [comment]
While doing this, need a better name for `io.opentelemetry.auto.bootsrap.Agent`, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/955#discussion_r469707190
