### ISSUE TITLE
Configuration file passed as argument is ignored in 1.21

### ISSUE THREAD

**Issue by axelczk** [open-telemetry/opentelemetry-java-instrumentation#7540]
**Describe the bug**
When laughing a Java application with opentelemetry 1.21 and a configuration file passed as argument (-Dotel.javaagent.configuration-file), the configuration file is ignored and properties are not loaded in the agent. 

In our case, we have done some test using the debug log and a configuration file with these information:
```
otel.javaagent.enabled=false
otel.metrics.exporter=none
otel.logs.exporter=none
```

In this case the agent start the instrumentation and send trace to the collector.

If we use environment variable to disable the agent it works fine. 

**Steps to reproduce**
Launch a Java  with the java auto instrumentation agent in version 1.21 with a configuration file as property. 

**What did you expect to see?**
The agent is loaded but does not instrument the code and does not send trace to the collector. 

**What did you see instead?**
The agent is loaded and instrument the code and send trace to the collector. 

**What version are you using?**
1.21.0

**Environment**
Compiler: OpenJDK 17.0
OS: Debian 

Tell me if you need additional information or some logs. 

Thanks

**Comment by mateuszrzeszutek** [comment]
Hey @axelczk ,

`otel.javaagent.enabled` is one of these few configuration settings that actually don't work with the configuration file - the reason for that is that when this property is checked, the configuration file is not even loaded. 

> In this case the agent start the instrumentation and send trace to the collector.

You could set `otel.traces.exporter = none` or `otel.sdk.disabled = true` to turn off the tracing instead.

**Comment by mateuszrzeszutek** [comment]
Yeah, we did not really list it in the release notes, must have happened around 1.17/1.18 I think.

It definitely is a breaking change, and it does make things kinda confusing if there are some properties that work with the file and some that don't - I think we should fix that.
