### ISSUE TITLE
Reactive Webclient - Traces not connected

### ISSUE THREAD

**Issue by janchristian-haddorp** [open-telemetry/opentelemetry-java-instrumentation#7546]
Using the reactive Webclient (Spring Boot Webflux) leads to not correctly connected traces.

Instead of four traces just one connected trace should be reported.
![image](https://user-images.githubusercontent.com/75397840/211674170-ddbd15f5-f680-4ff4-9ce7-9ddc25b33164.png)

Our setup is based on two applications. The "application" does a HTTP call to the "service". Then the "services" calls an external HTTP endpoint. These HTTP calls are executed via Webflux Webclient - the reactive way.

Traces are collected via the latest Java agent (v1.21.0). 
```
-javaagent:lib/opentelemetry-javaagent.jar
```

Following the reported traces it seems that the link to the parent trace got lost whenever doing a reactive HTTP call.

Replacing the Webclient by the traditional Spring Boot RestTemplate works as expected - one long trace.

Is there any special configuration required? Or is a sample application showing usage of Java agent in a reactive setup provided?

**Comment by trask** [comment]
hi @janchristian-haddorp! it's supposed to work without any special configuration, can you create a github repository with a small repro that we can use to troubleshoot and see what's happening in your case which is different from the cases covered by our tests?

**Comment by trask** [comment]
@janchristian-haddorp are you using spring-webflux 6? if so watch #7203

**Comment by janchristian-haddorp** [comment]
@trask, yes, it is a Spring Boot 3 / Webflux 6 project.
Small repro still helpful ot not needed as known issue?

**Comment by mateuszrzeszutek** [comment]
> Small repro still helpful ot not needed as known issue?

Hey @janchristian-haddorp , we probably don't need a repro scenario for this case (or, we don't need it yet 😅 ), the javaagent still does not fully support all Spring 6/Spring Boot 3 libraries, so I'm almost certain that is the reason behind your issues. Thanks for the help though, much appreciated!

**Comment by trask** [comment]
#7538 may fix this

**Comment by trask** [comment]
@janchristian-haddorp can you try with the just release 1.22.0 version?

**Comment by janchristian-haddorp** [comment]
@trask, thanks for the fix - looks good now!
