### ISSUE TITLE
Certain libraries (ones that use lots of lambdas?) take minutes to instrument

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#757]
Noticed in #756 that applying java_concurrent takes forever for the Armeria tests.

**Comment by anuraaga** [comment]
This was solved by not using a ClassRule to initialize the server in the linked PR. I'm not sure why that triggered the slowness but I think this was not actually indicative of normal behavior. @trask or someone please reopen though if you think this could actually happen in real code.

**Comment by anuraaga** [comment]
Oops nevermind, looked at the wrong test >< Yeah still slow

**Comment by anuraaga** [comment]
Sorry for the noise! Accidentally had a change that was eager loading the server again. Yes it seems to only happen when classes are loaded before the traits.

**Comment by trask** [comment]
😅
