### ISSUE TITLE
ParentContextExtractor should read tracing info from system property

### ISSUE THREAD

**Issue by smirnoal** [open-telemetry/opentelemetry-java-instrumentation#7579]
**Is your feature request related to a problem? Please describe.**
Java does not have a good mechanism for modifying environment variables. There are some hacky solutions which use Reflection API, and modify the UnmodifiableMap which [holds](https://github.com/openjdk/jdk/blob/d732c3091fea0a7c6d6767227de89002564504e5/src/java.base/windows/classes/java/lang/ProcessEnvironment.java#L283) the variables. This technique is now discouraged by Oracle. Good reads on this topic: [blog post by Oracle](https://blogs.oracle.com/javamagazine/post/a-peek-into-java-17-continuing-the-drive-to-encapsulate-the-java-runtime-internals)

Because of this, setting tracing information via `_X_AMZN_TRACE_ID` is challenging in new versions of Java, even with the hack.

Would it be possible to implement reading tracing information from a system property, not from an environment variable?  `aws-x-ray-sdk-java` implemented this some time ago: [link](https://github.com/aws/aws-xray-sdk-java/issues/251)

**Describe the solution you'd like**
Optionally read tracing information from `com.amazonaws.xray.traceHeader` system property.
Similarly to this PR: https://github.com/aws/aws-xray-sdk-java/pull/252/files

**Additional context**
Perhaps, this class should be modified: [link](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/94ba33e3950cf680714074c6375699a65ee11028/instrumentation/aws-lambda/aws-lambda-core-1.0/library/src/main/java/io/opentelemetry/instrumentation/awslambdacore/v1_0/internal/ParentContextExtractor.java#L25)

**Comment by trask** [comment]
> Would it be possible to implement reading tracing information from a system property, not from an environment variable? `aws-x-ray-sdk-java` implemented this some time ago: [link](https://github.com/aws/aws-xray-sdk-java/issues/251)

it looks like that issue is still open?

**Comment by smirnoal** [comment]
and still actual. Would be great if someone can pick it up. Looks pretty straightforward to implement

**Comment by trask** [comment]
copying folks who may have knowledge/thoughts/interest: @willarmiros @tylerbenson @open-telemetry/lambda-extension-approvers

**Comment by tylerbenson** [comment]
Note that in #7970, the span context in this env var becomes a span link instead of the parent so maybe this becomes less important to populate?  If you still find it useful, I have no objection to reading from both locations for populating the span link.

**Comment by smirnoal** [comment]
I believe with the PRs merged, this issue can be closed. Would be good to know which release will contain the fix

**Comment by mateuszrzeszutek** [comment]
That will be release 1.27.0, which should happen in ~2 weeks.

**Comment by smirnoal** [comment]
aws docs were updated: https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-runtime
