### ISSUE TITLE
OpenTelemetry-agent conflicts with skywalking-agent,OpenTelemetry-agent overrode the modification logic of skywalking-agent to bytecode

### ISSUE THREAD

**Issue by oswin886** [open-telemetry/opentelemetry-java-instrumentation#7594]
**Describe the bug**
**OpenTelemetry-agent conflicts with skywalking-agent**,OpenTelemetry-agent overrode the modification logic of skywalking-agent to bytecode.

**Steps to reproduce**
Through pre-research, it is found that openTelemetry-agent and skywalking-agent have also enhanced the bytecode of the org.eclipse.jetty.server.HttpChannel file.Therefore, a test application jetty-demo based on jetty9 has been developed here.

1. Only install skywalking-agent, and then monitor the contents of the bytecode file of org.eclipse.jetty.server.HttpChannel in real time through arthas, as shown in the following figure.  `-javaagent:D:\data\skywalking-agent\skywalking-agent.jar`
![only-skywalking](https://user-images.githubusercontent.com/19281429/212839141-6e2b252a-c90f-4380-8372-a2c257810114.png)

2. Only install OpenTelemetry-agent, and then monitor the contents of the bytecode file of org.eclipse.jetty.server.HttpChannel in real time through arthas, as shown in the following figure. ` -javaagent:D:\data\opentelemetry-javaagent.jar`
![only-opentelemetry](https://user-images.githubusercontent.com/19281429/212839281-63d95f1c-baa5-4934-a2e7-57a030653cc3.png)

3. Install openTelemetry-agent and skywalking-agent at the same time, and then monitor the contents of the bytecode file of org.eclipse.jetty.server.HttpChannel in real time through arthas, as shown in the following figure. `-javaagent:D:\data\skywalking-agent\skywalking-agent.jar -javaagent:D:\data\opentelemetry-javaagent.jar`. 
![both and before request](https://user-images.githubusercontent.com/19281429/212839618-e2727b9b-34cb-4e9e-84f0-7b585930974f.png)

4.After the third step is completed, request the `/test` api and then monitor the contents of the bytecode file of org.eclipse.jetty.server.HttpChannel in real time through arthas, as shown in the following figure.
![both and after request](https://user-images.githubusercontent.com/19281429/212839728-de6b80f9-4326-43cc-9eb7-57d6172b95b6.png)

If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
OpenTelemetry-agent and skywalking-agent do not affect each other.

**What did you see instead?**
The jetty9.x plugin of skywalking-agent does not work.

**What version are you using?**
opentelemetry: v1.20.0
skywalking: v8.10.0

**Environment**
Compiler: JDK 1.8
OS: Windows10
test app: Jetty9

**Additional context**
other env: idea+maven3.8.6+arthas3.6.2.

Other plugins have similar situations, such as Tomcat9.x, Mysql5.x.

I(@oswin886) have put the test application and tools required for the reproduction in the opentelemetry-new-issue.zip package. In addition, I have communicated with the development engineer of the skywalking community. He(@wu-sheng) suggested that I submit an issue to the opentelemetry community. If you have any questions or other things I need to provide, please feed me or he(@wu-sheng) back as soon as possible.

[opentelemetry-new-issue.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/10432680/opentelemetry-new-issue.zip)

**Comment by mateuszrzeszutek** [comment]
Hey @oswin886 ,

In general, we don't recommend or support using other javaagents together with the OTel javaagent. However, we will accept patches that fix these kind of issues (as long as they don't break anything important).

**Comment by wu-sheng** [comment]
@mateuszrzeszutek An interested behavior of OTel javaagent is, it seems intentional to retransfer the codes in the runtime, even SkyWalking's agent has done everything after OTel javaagent did in the booting stage.
Do you know any mechanism or setup to control this?

**Comment by mateuszrzeszutek** [comment]
I think this might be the code responsible for enabling it: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/0ace238eeb0fd6c7dd54dddc0c39b6a0048077fa/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/AgentInstaller.java#L136-L137

(+ the jar manifest entries)

**Comment by trask** [comment]
(just linking to related #1534)

**Comment by oliver-zhang** [comment]
Hey @mateuszrzeszutek ,
When  I disable retransformation use the following way
<img width="790" alt="image" src="https://user-images.githubusercontent.com/4388551/216559190-c56f8613-59f6-45c1-b9db-393de489ad10.png">
My springboot application fail to start , bellow is the error message
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/4388551/216559939-ad93c9b5-79e7-4c84-bd47-7c929dbc3e36.png">
Is there any other way to deal this problem ?

**Comment by laurit** [comment]
@oliver-zhang the default value for redefinition strategy is `DISABLED` which will break the agent. Besides `RETRANSFORMATION ` the other option is `REDEFINITION`.

**Comment by laurit** [comment]
@oswin886 @oliver-zhang @wu-sheng try https://oss.sonatype.org/content/repositories/snapshots/io/opentelemetry/javaagent/opentelemetry-javaagent/1.24.0-SNAPSHOT/opentelemetry-javaagent-1.24.0-20230302.081319-55.jar and let us know whether this fixes the issue you had

**Comment by oliver-zhang** [comment]
> @oswin886 @oliver-zhang @wu-sheng try https://oss.sonatype.org/content/repositories/snapshots/io/opentelemetry/javaagent/opentelemetry-javaagent/1.24.0-SNAPSHOT/opentelemetry-javaagent-1.24.0-20230302.081319-55.jar and let us know whether this fixes the issue you had

Yes, It's fixed
