### ISSUE TITLE
TracerCustomizer packaging

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-java-instrumentation#762]
io.opentelemetry.auto.bootstrap.spi.TracerCustomizer should be in the contrib.auto package like io.opentelemetry.sdk.contrib.auto.config.SpanExporterFactory so that it can be imported by other projects. I've worked around it by copying the file with the same package name into my own initializer jar.

**Comment by anuraaga** [comment]
This makes sense to me. I wonder should we move that package to this repo? If it's for configuring auto instrumentation, not sure why it is living in the SDK (and even claims to be merged into the SDK itself at some point :O)

https://github.com/open-telemetry/opentelemetry-java/tree/master/sdk_extensions/auto_config

**Comment by trask** [comment]
> If it's for configuring auto instrumentation, not sure why it is living in the SDK

Good point, created #772 to move it here

**Comment by anuraaga** [comment]
@FrankSpitulski Now that `TracerCustomizer` is in the java-bootstrap project which is published, is the issue with `TracerCustomizer` solved? Just want to check

**Comment by FrankSpitulski** [comment]
@anuraaga is io.opentelemetry.javaagent.tooling.exporter.SpanExporterFactory available to include as a jar without pulling in the whole java agent instrumentation jar? That was my primary issue with using io.opentelemetry.auto.bootstrap.spi.TracerCustomizer, I had to include the whole jar or create an identical file and package it in my own jar to use the interface.

**Comment by anuraaga** [comment]
Yeah we publish the javaagent-tooling jar as well which is just that module without the inst/ renaming. How does that sound?

**Comment by FrankSpitulski** [comment]
Sounds good then
