### ISSUE TITLE
Support for Jodd

### ISSUE THREAD

**Issue by neroux** [open-telemetry/opentelemetry-java-instrumentation#7629]
**Is your feature request related to a problem? Please describe.**

It is not.

**Describe the solution you'd like**

I would be lovely if there was automatic instrumentation for https://jodd.org

First and foremost, that could be for https://http.jodd.org but Jodd also has a couple of other libraries

* https://mail.jodd.org
* https://petite.jodd.org
* https://db.jodd.org

**Describe alternatives you've considered**
N/A

**Additional context**

Following the advice from https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md

**Comment by mateuszrzeszutek** [comment]
Hey @neroux ,

Thanks for filing this issue! The maintainers of this project most likely won't implement it, but we're open to contributions -- and we'll definitely help with implementing the instrumentations correctly.

Also: while we don't currently support the Jodd Db library, it seems that it's a wrapper over the JDBC API -- which we do instrument; you should be able to see some telemetry about the SQL statements you run.

**Comment by neroux** [comment]
Thank you for the swift response, @mateuszrzeszutek.

I did not expect an immediate implementation 🙂 but just wanted bring it up in general.

Thanks once more.

**Comment by neroux** [comment]
Thanks a lot for the swift implementation, @PhilKes and @mateuszrzeszutek.

Tagging @igr as FYI
