### ISSUE TITLE
Unexistant content-length causing NPE

### ISSUE THREAD

**Issue by driverpt** [open-telemetry/opentelemetry-java-instrumentation#7637]
**Describe the bug**
Using Micronaut 3.8.2 + Micronaut Tracing 4.5.0, we've detected that when a response that has no `Content-Length` it's causing a NullPointerException which has the side-effect of causing a Request to become a Ghost.

**Steps to reproduce**
Create App using [Micronaut Launch](https://micronaut.io/launch/) using the following options:

Type: Application

- graalvm
- amazon-api-gateway
- aws-lambda

Create simple Micronaut Controller

Add the following dependencies:

```
    implementation("io.micronaut.tracing:micronaut-tracing-opentelemetry-http:4.5.0")
    implementation("io.opentelemetry:opentelemetry-exporter-otlp")
    implementation("io.opentelemetry:opentelemetry-extension-aws")
    implementation("io.opentelemetry.instrumentation:opentelemetry-aws-sdk-2.2")
    implementation("io.opentelemetry.contrib:opentelemetry-aws-xray")
    implementation("io.micronaut.aws:micronaut-function-aws-api-proxy")
    implementation("io.micronaut.aws:micronaut-function-aws-custom-runtime")
    implementation("io.micronaut.aws:micronaut-aws-sdk-v2")
```

Set the function to use GraalVM:

```
micronaut {
    runtime("lambda_provided")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("<application package>.*")
    }
    aot {
        // Please review carefully the optimizations enabled below
        // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading.set(true)
        convertYamlToJava.set(true)
        precomputeOperations.set(true)
        cacheEnvironment.set(true)
        optimizeClassLoading.set(true)
        deduceEnvironment.set(true)
    }
}

```

**What did you expect to see?**
Requests to go through normally

**What did you see instead?**
AWS Lambda Invocations become ghosts, leading to ServiceUnavailable.

**What version are you using?**
1.19.0

**Environment**
Compiler: Amazon Corretto 17
OS: MacOS
Runtime: GraalVM 22.3.0

**Additional context**
[Link](https://github.com/micronaut-projects/micronaut-aws/issues/1568)

**Comment by driverpt** [comment]
cc @n0tless @sdelamo

**Comment by n0tl3ss** [comment]
Can you try to use this: https://github.com/micronaut-projects/micronaut-aws/pull/1578

**Comment by driverpt** [comment]
I have custom `Serde<SingleValueHeaders` which parses properly. But i will try

This is in fact a possible OTEL issue because Instrumenter will throw NPE and should do it as a best-effort

**Comment by trask** [comment]
hi @driverpt!

> This is in fact a possible OTEL issue because Instrumenter will throw NPE in case there is no Content-Length and should extract the attribute as a best-effort

`firstHeaderValue()` is only called on the return values from `getRequestHeaders()` and `getResponseHeaders()`, which should not return `null`:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/db6b7644217fea0c36a96b7d4a47b6674d273041/instrumentation-api-semconv/src/main/java/io/opentelemetry/instrumentation/api/instrumenter/http/HttpCommonAttributesGetter.java#L39-L40

does Micronaut have its own implementation of `getRequestHeaders()` or `getResponseHeaders` which can return null?
