### ISSUE TITLE
Fail to connect to localhost

### ISSUE THREAD

**Issue by davideduma** [open-telemetry/opentelemetry-java-instrumentation#7645]
**Describe the bug**
Fail to connect  to localhost 

![image](https://user-images.githubusercontent.com/86481341/214391605-2080e4bc-38c8-4714-ae08-85be89750ff8.png)

**Steps to reproduce**
execute next command: java -javaagent:opentelemetry-javaagent.jar -jar demo.jar

**What did you expect to see?**
Not faile to connect

**What did you see instead?**
 Failed to connect to localhost/0:0:0:0:0:0:0:1:4317

**What version are you using?**
 version: 1.22.1

**Environment**
Compiler: OpenJDK 11
OS: Windows 11

**Comment by mateuszrzeszutek** [comment]
Hey @davideduma ,
Does anything on your machine listen on localhost:4137? E.g. the OTel Collector.
(In the default collector configuration port 4137 is used by the OTLP receiver)

**Comment by laurit** [comment]
@davideduma If you are not interested in metrics you can disable exporting them with `-Dotel.metrics.exporter=none`

**Comment by davideduma** [comment]
> @davideduma If you are not interested in metrics you can disable exporting them with `-Dotel.metrics.exporter=none`

I use "-Dotel.metrics.exporter=none" but the issue continue:
![image](https://user-images.githubusercontent.com/86481341/214589483-e827ff22-e38f-43f0-8cee-77b5acd3877f.png)

I'm exec  exclude  metrics exporter with this command: 
java -javaagent:opentelemetry-javaagent.jar -Dotel_metrics_exporter=none -jar demo.jar

But issue continue.
I don't have any component that use the port 4317 and in the firewall this port is open IN OUT rules

**Comment by davideduma** [comment]
> Hey @davideduma , Does anything on your machine listen on localhost:4137? E.g. the OTel Collector. (In the default collector configuration port 4137 is used by the OTLP receiver)

hi @mateuszrzeszutek.

I use "-Dotel.metrics.exporter=none" but the issue continue:
![image](https://user-images.githubusercontent.com/86481341/214589483-e827ff22-e38f-43f0-8cee-77b5acd3877f.png)

I'm exec  exclude  metrics exporter with this command: 
java -javaagent:opentelemetry-javaagent.jar -Dotel_metrics_exporter=none -jar demo.jar

But issue continue.
I don't have any component that use the port 4317 and in the firewall this port is open IN OUT rules

**Comment by mateuszrzeszutek** [comment]
> I'm exec exclude metrics exporter with this command: java -javaagent:opentelemetry-javaagent.jar -Dotel_metrics_exporter=none -jar demo.jar

Try ` -Dotel.metrics.exporter=none` instead.

**Comment by davideduma** [comment]
@mateuszrzeszutek Thanks for you help. I think the issue continue when i use "-Dotel.metrics.exporter=none"

I try and result is this. Is normally when i getting the error fail to connect to port 4317?
When i send request POST to demo.jar (microservice api rest) OpenTelemetry response with fail to connect to port 4317.
I don't know if this is normally. 

![image](https://user-images.githubusercontent.com/86481341/214598302-eb9f6445-b0ac-4a0e-b537-921ec624e90c.png)

![image](https://user-images.githubusercontent.com/86481341/214600245-51d3f560-5762-4992-aa04-c3a4b607600d.png)

**Comment by mateuszrzeszutek** [comment]
Do you have an [OpenTelemetry collector](https://opentelemetry.io/docs/collector/) deployed on your machine?

The javaagent collects telemetry (metrics, spans, logs), but it doesn't really do anything with it locally -- it simply sends it somewhere (to the collector; or directly to your chosen observability backend). By default, the javaagent is configured to use the OTLP exporter -- which, by default, sends OTLP-formatted telemetry to the localhost:4137 address (the default address of a locally deployed OTel collector).

**Comment by davideduma** [comment]
@mateuszrzeszutek 

Thanks for you help. 
Your comment was very helpful. 
I did it. it's working now.
i did not have install OpenTelemetry-collector.

would you like if i will change the file readme to improve it and specify that it is necessary to install the opentelemetry-collector before using the agent in case of using the export metrics?

**Comment by mateuszrzeszutek** [comment]
> would you like if i will change the file readme to improve it and specify that it is necessary to install the opentelemetry-collector before using the agent in case of using the export metrics?

The [readme](https://github.com/open-telemetry/opentelemetry-java-instrumentation#getting-started) already kinda mentions that:

> By default, the OpenTelemetry Java agent uses [OTLP exporter](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/otlp) configured to send data to [OpenTelemetry collector](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md) at http://localhost:4317.
