### ISSUE TITLE
Reconsider not using cache for muzzle

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#767]
We currently don't use a cache for muzzle

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/.circleci/config.yml#L125

I think many of muzzle flaky failures happen when downloading artifacts though. We should verify that not using a cache is actually helping more than hurting.

An idea also is to use a custom command for caching using `lz4` - I've found it to work great for large (multi-gigabyte) CI caches composed of already-compressed artifacts, while the general default of gzip does indeed perform terribly.

Example lz4 command - https://github.com/curioswitch/curiostack/blob/master/cloudbuild.yaml#L40

**Comment by iNikem** [comment]
Can we consider this problem in scope of #678 ?

**Comment by anuraaga** [comment]
Yeah if we take care of it in an action that works well.

**Comment by iNikem** [comment]
Do you want to have a separate cache for muzzle job?

**Comment by anuraaga** [comment]
Interesting, didn't think about that. I think if we can use a faster compression, like lz4, it wouldn't matter. But if we can't, then we can potentially offset the size of the muzzle cache (every version of every dependency) vs the fact that muzzle runs much faster that other tests by having a separate cache.

**Comment by breedx-splk** [comment]
Is this now stale?  Seems like we do have CI/CD in github actions now (#678 an the PRs mentioned there) and there is a muzzle cache in place.  Can this be closed, or is there more to do?

**Comment by anuraaga** [comment]
Yeah seems to not be flaking that much, so close time.
