### ISSUE TITLE
GetAddress not present in httpcore < 4.3

### ISSUE THREAD

**Issue by anuragagarwal561994** [open-telemetry/opentelemetry-java-instrumentation#7674]
So we have used `target.getAddress()` here but the method was added in http core v4.3

If I see on maven central with apache httpasyncclient v4.1 https://mvnrepository.com/artifact/org.apache.httpcomponents/httpasyncclient/4.1

The default version that comes along for httpcore is 4.4.x but that doesn't mean that the user doesn't have a way to override this.

Hence someone using httpasyncclient 4.1.x with < 4.4.x version of httpcore, things will break.

_Originally posted by @anuragagarwal561994 in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/6503#issuecomment-1407493400_

**Comment by anuragagarwal561994** [comment]
Ideally imho a lot of things changed between 4.0 and 4.3 version of httpcore.

I believe that a separate implementation of the same can be built if it adds value

**Comment by laurit** [comment]
@anuragagarwal561994 do you have an application that uses httpasyncclient 4.1.x with httpcore < 4.4.x? Is this issue created out of necessity to support such configurations or does it only imply that there is a theoretical possibility to mix these components in such a way? As far as I can tell httpasyncclient 4.1 uses classes that were added in httpcore 4.4, such as https://github.com/apache/httpcomponents-client/blob/rel/v4.4/httpclient/src/main/java/org/apache/http/conn/util/PublicSuffixMatcherLoader.java, which makes me question the viability of using httpcore < 4.4.x? with httpasyncclient 4.1.x.

**Comment by anuragagarwal561994** [comment]
I will check this once @laurit by creating a sample application. So generally we can't rely on developers to update 2 separate dependencies by checking their compatibility generally we update the ones where we want to use the newer functions of a library. If a application is using http client and http async client where in httpclient they have specified httpcore < 4.4 then issue can come up. But I will check if httpasyncclient even works with < 4.4 because in that case the developer will be forced to upgrade httpcore even when they have mentioned in their pom.xml file.

**Comment by anuragagarwal561994** [comment]
@laurit 

> Release 4.0 Beta 4
-------------------

The 4.0 BETA4 release delivers significant performance improvements in request execution,
especially for short HTTP messages, and also re-aligns programming interfaces used by the library 
with HttpCore 4.3 and HttpClient 4.3 APIs. Configuration and preference APIs of HttpAsyncClient
are now consistent with those used by HttpClient 4.3.

Users of previous releases of HttpAsyncClient are advised to upgrade.

Quoting the release notes we can confirm that httpasyncclient is compatible with httcore 4.3
