### ISSUE TITLE
JDBC autoinstrumentation uses a static OpenTelemetry instance and is not DI (Spring Boot) friendly

### ISSUE THREAD

**Issue by FranPregernik** [open-telemetry/opentelemetry-java-instrumentation#7677]
**Is your feature request related to a problem? Please describe.**
We are using Spring Boot Actuator and its OpenTelemetry metrics and tracing (via micrometer-tracing) autoconfiguration. These set up a OpenTelemetry bean instance.

We added the opentelemetry-jdbc instrumentation and wrapped our instance of the datasource (Hikari) with the OpenTelemetryDataSource. But all the wrappers there rely on the GlobalOpenTelemetry.get() which does not notice the OpenTelemetry bean. Also it is a race condition since the jdbc setup is in static methods which is OK for the opentelemetry javaagent setup.

**Describe the solution you'd like**
Allow the OpenTelemetryDataSource to accept an instance of OpenTelemetry in the constructor which it will wrap with the Instrumentor lazily and pass on to the other JDBC wrappers in the same way. In case the constructor OpenTelemetry is passed a null it will fall back to GlobalOpenTelemetry.get()

We did this in our codebase and it works but we would like this support to be in the official library.

**Describe alternatives you've considered**
We considered using the javaagent instead.

**Comment by trask** [comment]
hi @FranPregernik! you're right that all library instrumentation should allow injecting `OpenTelemetry` instance, please feel free to send a PR for this, thx

**Comment by FranPregernik** [comment]
Thanks for getting back to me. I will go through the contribution guide and submit a PR.
