### ISSUE TITLE
All caches should be size constrained

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java-instrumentation#7678]
**Describe the bug**
(Related to #7669.)
Reliance on manual weak map cleaning can cause unpredictable memory swings. This is demonstrated by systems that use dynamically generated classloaders such as janino. The following cache in `AgentCachingPoolStrategy` ends up growing unconstrained:

```java
  final Cache<ClassLoader, WeakReference<ClassLoader>> loaderRefCache = Cache.weak();
```

**Steps to reproduce**
Here's an test case to demonstrate the problem similar to what is happening in #7669.

```java
  @Test
  void testDynamicGeneratedClassLoaderMemory() throws InterruptedException {
    AgentBuilder.PoolStrategy poolStrategy = AgentTooling.poolStrategy();
    GcUtils.awaitGc();
    long startingHeapBytes = Runtime.getRuntime().totalMemory();
    for (int i = 0; i < 1_000_000; i++) {
      URLClassLoader classLoader = new URLClassLoader(new URL[0], null);
      ClassFileLocator locator = ClassFileLocator.ForClassLoader.of(classLoader);
      TypePool pool = poolStrategy.typePool(locator, classLoader);
      TypePool.Resolution resolution = pool.describe(String.class.getName());
      TypeDescription typeDescription = resolution.resolve();
      assertNotNull(typeDescription);
    }
    GcUtils.awaitGc();
    long endingHeapBytes = Runtime.getRuntime().totalMemory();
    // unconstrained cache size with many keys->null references.
    assertTrue(endingHeapBytes - startingHeapBytes < 10_000_000,
        (endingHeapBytes - startingHeapBytes)/1_000_000 + "MB is more than 10MB");
  }
```

**What did you expect to see?**
Caches should have a strict upper limit.  By nature, caches should store temporary data, so choosing to regenerate the value more frequently is a reasonable tradeoff instead of storing everything in memory.

**What did you see instead?**
Unconstrained growth on the size of the cache. (If added quickly enough before GC takes effect.)

**Comment by trask** [comment]
@tylerbenson are you still seeing an issue with this after I think some improvements that @laurit(?) made?
