### ISSUE TITLE
MDC tracing fields are always null if retrieved 

### ISSUE THREAD

**Issue by fpaparoni** [open-telemetry/opentelemetry-java-instrumentation#7679]
I'm using automatic instrumentation for my Spring Boot application and I can see the tracing information in the logs. I would like to return trace id also in a response header of my http endpoints, but if I try to get MDC field it returns null. Of course if I use manual instrumentation I can do whatever I want with trace id, but I would like to use automatic instrumentation. 

Is it possible to retrieve and use these fields in the automatic instrumentation scenario?

**Comment by fpaparoni** [comment]
I saw the mechanism related to the propagation of the tracing information (the example is related to AWS XRay integration)

https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/instrumentation/logback-1.0/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/logback_1_0/AwsXrayLoggingEventInstrumentation.java#L11

If I want to use the automatic instrumentation and I want to retrieve these tracing information, extending the agent is the only way?

**Comment by mateuszrzeszutek** [comment]
Hey @fpaparoni ,

Are you using the javaagent or the Spring Boot starter?

**Comment by fpaparoni** [comment]
Hi @mateuszrzeszutek ,

using Java agent I have this problem (MDC fields null) but only if I try to retrieve it. In the logs I see everything and I would like to use the Java agent. If I use the Spring Boot starter I can access to every information using the Tracer, but I don't have all the automatic instrumentation provided by the Java agent

**Comment by mateuszrzeszutek** [comment]
That's because the javaagent does not actually insert these values into MDC; it injects them directly to the logging events when they're being constructed.

If you want to get the current trace id or span id, you can always use `Span.current().getSpanContext().getTraceId()`.

**Comment by fpaparoni** [comment]
Oh yes great it works. I think that I don't have access to this sort of information using Java agent, but I suppose the context is injected in a similar way as done with MDC.

**Comment by chenzhihao1040728129** [comment]
> That's because the javaagent does not actually insert these values into MDC; it injects them directly to the logging events when they're being constructed.
> 
> If you want to get the current trace id or span id, you can always use `Span.current().getSpanContext().getTraceId()`.

Hi, is there an official way or custom implementation that is compatible with the previous use of MDC.get("trace_id") to get link information?

**Comment by trask** [comment]
hi @chenzhihao1040728129, can you open a new issue and describe more what you are trying to do? (and e.g. why calling `Span.currentSpan().getSpanContext().getTraceId()` doesn't work for your use case)
