### ISSUE TITLE
Use Zipkin as propagator, and don't have parent span id

### ISSUE THREAD

**Issue by lvqytx** [open-telemetry/opentelemetry-java-instrumentation#7693]
**Is your feature request related to a problem? Please describe.**
When I send a header "b3={TraceId}-{SpanId}-{SamplingState}-{ParentSpanId}" to the service with javaagent, it won't send parentSpanId to the next service. I want to know why to design this? 
I saw the doc said "MUST NOT propagate X-B3-ParentSpanId as OpenTelemetry does not support reusing the same id for both sides of a request." But i don't understand it.

**Comment by mateuszrzeszutek** [comment]
Hey @lvqytx ,

OpenTelemetry does not use the parent span id anywhere; it's an optional part of the B3 header, we chose to not implement it.
For more context, take a look at https://github.com/open-telemetry/opentelemetry-specification/issues/1004 and https://github.com/open-telemetry/opentelemetry-specification/pull/1045; perhaps they'll explain the reason why it works the way it does. If you have further questions, please open an issue in the spec repo.
