### ISSUE TITLE
How to handle JMX mbean attributes which really have a "." in them?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#7706]
It appears it's possible to have real "." in an mbean attribute name, but [JMX metrics insights](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jmx-metrics/javaagent/README.md) will interpret that to be a nested mbean attribute.

Here's a simple way to generate an mbean with a real "." in its name (the attribute will be named `NestedObject.Value`):

```
        <dependency>
            <groupId>org.weakref</groupId>
            <artifactId>jmxutils</artifactId>
            <version>1.22</version>
        </dependency>
```

```
    MBeanExporter exporter = new MBeanExporter(ManagementFactory.getPlatformMBeanServer());
    exporter.export("test:name=X", new NestedExample());

    public static class NestedExample {
        private final NestedObject nestedObject = new NestedObject();

        @Nested
        public NestedObject getNestedObject() {
            return nestedObject;
        }

        public static final class NestedObject {
            @Managed
            public String getValue() {
                return "someValue";
            }
        }
    }
```

One thought is to allow escaping the `.`, e.g. `\.` in cases where it doesn't mean nesting.

Wondering what others think?

cc @PeterF778

**Comment by PeterF778** [comment]
This issue was resolved in Feb 2023 (allowing to escape embedded dots by '\') and can be closed.
