### ISSUE TITLE
Play instrumentations does not work as expected

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#771]
Play instrumentations for all version has a functionality of changing root span name to the route of the request, see e.g. https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/play/play-2.4/src/main/java/io/opentelemetry/auto/instrumentation/play/v2_4/PlayDecorator.java#L35

But even tests themselves expect totally different name of the server span: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/play/play-2.4/src/test/groovy/server/PlayServerTest.groovy#L100

Thus, it seems, that name changing functionality does not work

**Comment by mcmho** [comment]
I have couple years of java agent experience, and recently i have worked on a project using the opentelemetry sdk and api. 
I wonder if this is a good starter bug i can help fix?   @trask  @iNikem  👌 ❓

**Comment by trask** [comment]
oh! I think this is probably the same as #1415. and yes, it's hard to know if something like this is a good starter bug, but worth giving it a look
