### ISSUE TITLE
Azure-core tests fail agains 1.36.0

### ISSUE THREAD

**Issue by laurit** [open-telemetry/opentelemetry-java-instrumentation#7729]
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7722

**Comment by lmolkova** [comment]
I'm the one to be blamed. Is it possible to ignore tests for now? I will come back and fix them the next week - I was going to make some improvements to the instrumentation that come with the new version anyway.

**Comment by mateuszrzeszutek** [comment]
No problem - we've already limited the latest dep version; this can wait until you have some time.

**Comment by heyams** [comment]
> I'm the one to be blamed. Is it possible to ignore tests for now? I will come back and fix them the next week - I was going to make some improvements to the instrumentation that come with the new version anyway.

@lmolkova i can help fixing the tests if that works for you? if yes, i can assign this issue to myself.

**Comment by lmolkova** [comment]
@heyams thank you for the offer! I was going to do some feature work based on azure-core tracing improvements anyway and since tests are not blocking anymore, I can take care of it :)
