### ISSUE TITLE
Any way to have otel.instrumentation.methods.include add all method of class?

### ISSUE THREAD

**Issue by Pratik151** [open-telemetry/opentelemetry-java-instrumentation#7733]
**Is your feature request related to a problem? Please describe.**
Looking to instrument all methods of some of the classes in our code with auto instrumentation. otel.instrumentation.methods.include might be helpful but not able to figure out how to use it at to create span for all method instead of mentioning them individually.

**Describe the solution you'd like**
otel.instrumentation.methods.include=package.class should span for all method in class.

**Comment by trask** [comment]
hi @Pratik151! check out similar thread at #2574

**Comment by trask** [comment]
Closing in favor of #2574
