### ISSUE TITLE
Support  for propagation of `trace_id`, `span_id` and `trace_flags` in logs for custom spans

### ISSUE THREAD

**Issue by santoshkashyap** [open-telemetry/opentelemetry-java-instrumentation#7740]
**Is your feature request related to a problem? Please describe.**
I have a scenario with CloudEvents and also a few other scenarios where-in auto-instrumentation with JavaAgent is not yet possible.  For this reason, I use `OpenTelemetryAPI` for Java to add custom spans for CloudEvent processing. Even though the spans are generated, the corresponding log statements in the CloudEvent processing doest not have `trace_id`, `span_id` and `trace_flags` in the logs. (FYI: our logs are enabled to log `trace_id` and `span_id`. This is working fine for auto-instrumentation code).

**Describe the solution you'd like**
Support automatic logging of `trace_id`, `span_id` and `trace_flags` for custom spans as well.

**Describe alternatives you've considered**
I have not implemented any alternative solution as yet, but as explained in the [logger-mdc-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/logger-mdc-instrumentation.md), one possible solution is to write the `trace_id` in the MDC manually:

```
// manually persist `trace_id` for custom spans
MDC.put("trace_id" ,Span.current().getSpanContext().getTraceId());

// CloudEvent processing logic..

// remove the attribute when done manually.
MDC.remove("trace_id");

```

**Additional context**

Following is the code snippet for processing CloudEvents.:

```java

@RequestMapping(path = "/api/somepath", produces = { MediaType.APPLICATION_JSON_VALUE })
@Async("eventWebhookExecutor")
	@PostMapping(consumes = { JsonFormat.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE })
	@ResponseStatus(code = HttpStatus.NO_CONTENT)
	public void handleEvent(
			@RequestHeader @CloudEventHeader(skipMissingHeaders = true) final MultiValueMap<String, String> headers,
			@RequestBody final byte[] body) {

final String traceParentHeader = "ce-traceparent";
final String ceTraceParent = headers.getFirst(traceParentHeader);
// simple util method (See below code) to get active context for a traceparent.
final Context activeContext = TracingUtil.getActiveTraceContext(ceTraceParent);
final Tracer tracer = this.openTelemetry.getTracer(Application.class.getName());
final SpanBuilder currentSpanBuilder = tracer.spanBuilder(OPERATION_NAME).setSpanKind(SpanKind.CONSUMER);

if (activeContext != null) {
			currentSpanBuilder.setParent(activeContext);
		}
final Span currentSpan = currentSpanBuilder.startSpan();

try (Scope scope = currentSpan.makeCurrent()) {

cloudEvent = HttpMessageFactory.createReaderFromMultimap(headers, body).toEvent();
			cloudEventHeaders = getCloudEventHeaders(cloudEvent);
// attributes as required by CE processing: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/cloudevents.md#processing
addSpanAttributesFromCloudEvent(cloudEvent, currentSpan);
  
 // BELOW LOG STATEMENT DOES NOT HAVE `trace_id`
 LOGGER.info( "Received Cloud Event with ID '{}' ", cloudEvent.getId());

 // Rest of the code ...

```

**TracingUtil.java**
```java
public static Context getActiveTraceContext(final String traceParent) {
		Context activeContext = null;
		if (traceParent != null && !traceParent.isEmpty()) {
			/*
			 * expected values in tokens [version, traceid_value, spanid_value,
			 * trace_flag]
			 */
			final String[] traceCtxTokens = parseTraceParent(traceParent);
			if (traceCtxTokens != null && traceCtxTokens.length >= 3) {
				// we don't require "version" info from traceCtxTokens[0]
				final String traceId = traceCtxTokens[1];
				final String spanId = traceCtxTokens[2];
				// Default the traceFlag to not propagate the trace i.e. 00 (not sampled)
				TraceFlags traceFlag = TraceFlags.getDefault();
				// If the incoming request has traceFlag, use it.
				if (traceCtxTokens.length > 3) {
					traceFlag = TraceFlags.fromByte(Byte.parseByte(traceCtxTokens[3]));
				}
				final SpanContext activeSpanContext = SpanContext.createFromRemoteParent(traceId, spanId, traceFlag,
						TraceState.getDefault());
				final Span activeSpan = Span.wrap(activeSpanContext);
				activeContext = Context.current().with(activeSpan);
			}
		}
		return activeContext;
	}

	private static String[] parseTraceParent(final String traceParent) {
		String[] tokens = new String[4];
		if (traceParent != null && !traceParent.isEmpty()) {
			tokens = traceParent.split("-");
		}
		return tokens;
	}

```

Even though the above sample is for `CloudEvents` for  CONSUMER side , in general for manually generated spans alongside JavaAgents, the application logs are missing the `trace_id`, `span_id ` , `trace_flags` (as mentioned in the [logger-mdc-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/logger-mdc-instrumentation.md)). My question is, can this be supported out-of-the box ? or Do I need to always add the trace specific fields manually (using  `MDC` apis).

**Best**,
Santosh

**Comment by laurit** [comment]
Are you using manual instrumentation together with java agent or just the manual instrumentation?

**Comment by santoshkashyap** [comment]
> Are you using manual instrumentation together with java agent or just the manual instrumentation?

Auto-instrumentation and just the OpenTelemetry API to add custom spans:


```
<properties>
    <opentelemetry.version>1.20.1</opentelemetry.version>
</properties>
....
<dependencyManagement>
   <dependencies>		
      <dependency>
        <groupId>io.opentelemetry</groupId>
        <artifactId>opentelemetry-bom</artifactId>
        <version>${opentelemetry.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
  </dependencies>
</dependencyManagement>
  ....

<dependencies>
<dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-api</artifactId>
</dependency>
</dependencies>

```
```java
@Configuration
public class OpenTelemetryConfig {

	@Bean
	public OpenTelemetry openTelemetry() {
		return GlobalOpenTelemetry.get();
	}

}
```

**Comment by laurit** [comment]
> Auto-instrumentation and just the OpenTelemetry API to add custom spans:

By auto-instrumentation we mean java agent, not sure whether you mean the same. Assuming you are using javaagent we'll need a minimal application that reproduces the issue. Try to trim it down as much as possible. Perhaps you don't need cloud event and spring at all to reproduce this?
If you aren't using the javaagent then you'll probably have to include the mdc instrumentation for your logging framework.

**Comment by santoshkashyap** [comment]
Yes, I'm using JavaAgent for auto-instrumentation. I will come back again with a simple app

**Comment by santoshkashyap** [comment]
Apologies! I should have verified this properly. Surprisingly, the issue seems to be with the buggy logic implemented in our logging backend solution. I had `trace_id` (for tracing & log correlation) and `correlation_id` (used internally for log msg correlation) in the application logs, the backend service seems to retain only the original value for `correlation_id`.  Hence, closing the ticket
