### ISSUE TITLE
can't get ContextKey value in SpanProcessor

### ISSUE THREAD

**Issue by tuhao1020** [open-telemetry/opentelemetry-java-instrumentation#7763]
I referenced the example to create a custom extension for the purpose of passing certain data to upstream services.
Here are the 2 classes I used：

MySpanProcessor
```
public class MySpanProcessor implements SpanProcessor {
  @Override
  public void onStart(Context parentContext, ReadWriteSpan span) {
    Long start = Context.current().get(ContextKey.named("propagation.start"));
    System.out.println("propagation.start = " + start);
    span.setAttribute("propagation.start", String.valueOf(start));
    return;
  }
  ......
}
```

DemoPropagator
```
public class DemoPropagator implements TextMapPropagator {
  private static final String FIELD = "X-demo-field";
  private static final ContextKey<Long> PROPAGATION_START_KEY =
          ContextKey.named("propagation.start");

  @Override
  public List<String> fields() {
    return Collections.singletonList(FIELD);
  }

  @Override
  public <C> void inject(Context context, C carrier, TextMapSetter<C> setter) {
    Long propagationStart = context.get(PROPAGATION_START_KEY);
    if (propagationStart == null) {
      propagationStart = System.currentTimeMillis();
    }
    setter.set(carrier, FIELD, String.valueOf(propagationStart));
  }

  @Override
  public <C> Context extract(Context context, C carrier, TextMapGetter<C> getter) {
    String propagationStart = getter.get(carrier, FIELD);
    if (propagationStart != null) {
      return context.with(PROPAGATION_START_KEY, Long.valueOf(propagationStart));
    } else {
      return context;
    }
  }
}
```

`x-demo-field` has being added to request headers, but `Context.current().get(ContextKey.named("propagation.start"))` always return null in SpanProcessor

<img width="1048" alt="image" src="https://user-images.githubusercontent.com/26807520/217588714-4402be12-4ee4-44f3-b0f3-8664a627e286.png">

**Comment by laurit** [comment]
See https://github.com/open-telemetry/opentelemetry-java/blob/43c88b911d7b092c6b65722b5501d508ccdfcdc4/context/src/main/java/io/opentelemetry/context/ContextKey.java#L9-L11 You'll have to use the same key in the propagator and span processor.

**Comment by tuhao1020** [comment]
@laurit I changed `X-demo-field` to `propagation.start` , still got null value
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/26807520/217697775-31ae6910-f8ca-4d61-ba2c-132850dc615e.png">

**Comment by laurit** [comment]
@tuhao1020 that won't help. In `MySpanProcessor` change `Long start = Context.current().get(ContextKey.named("propagation.start"));` to 
`Long start = Context.current().get(DemoPropagator.PROPAGATION_START_KEY);`

**Comment by tuhao1020** [comment]
@laurit  thanks! 
Now I find that the value of `propagation.start` inside some spans is still null, is there a way to solve this problem?
<img width="784" alt="image" src="https://user-images.githubusercontent.com/26807520/217750804-57818448-ce7c-4c22-b26c-f9b65bd417ed.png">

**Comment by laurit** [comment]
In `MySpanProcessor` instead of `Context.current()` try using `parentContext`.

**Comment by tuhao1020** [comment]
@laurit  thanks！
