### ISSUE TITLE
Internal Span Tag Enhancement

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-java-instrumentation#777]
I'd like the Kind.INTERNAL spans to tag their parameters and maybe their return values. I'd be happy to implement this.

**Comment by trask** [comment]
can you give a concrete example of what you're looking to capture? thx!

**Comment by FrankSpitulski** [comment]
Two cases- the first being the internal span of a servlet's controller method. I'd like to be able to see which (java, not query) parameters were passed into this method. 
![image](https://user-images.githubusercontent.com/17055695/88352957-9ae39b80-cd10-11ea-861b-6540b4b07fa7.png)

the second case is @WithSpan methods. I'd like to be able to see their parameters too.

**Comment by FrankSpitulski** [comment]
With respect to what I'd like to capture, I'd like to see their toString representations.

**Comment by FrankSpitulski** [comment]
given the method
```java
@WithSpan
public void doAThing(String arg, Object objectWithNoToStringDefined) {
    // I lied, it doesn't do anything
}
```
if I call it as 
```java
doAThing("1", new Object());
```
I'd like to see `params.arg="1"` and `params.objectWithNoToStringDefined="Object@12345"`

**Comment by iNikem** [comment]
I have two concerns here. One, is the amount of data. Recording parameter values may add significant amount of data to span. Second is security. Method parameters may contain sensitive information and I don't think we should record them.

**Comment by trask** [comment]
I could see something like this as part of `@WithSpan`.

Glowroot's equivalent annotation allows you to define a template for the span name, which I found very useful:

> The template can be populated with values from the method invocation:
> * {{0}}, {{1}}, ... resolve to the method parameters
> * {{this}} resolves to the object that the method is invoked on (except for static methods)
> * {{_}} resolves to the return value (if not void)
> * {{methodName}} resolves to the method name, which can be useful if * or | are used to define the method name above
>
> Nested paths are resolved as well, e.g. {{0.size}} and {{this.class.name}}. If a path resolves to null at any point, then the entire path will resolve to null. The final resolved value is rendered into the template using String.valueOf() . If the final resolved value is a byte array, it will be rendered as hex, or you can specify a charset to decode it, e.g. {{0.someBytes|charset:UTF-8}} or {{0.someBytes|charset:default}} to use the default (platform) charset.

**Comment by FrankSpitulski** [comment]
How about a flag inside the @WithSpan annotation that enables it on a per method basis?

The internal controller span is a different story though since it is automatically created. I think it is very useful to know what parameters the controller is called with. The info is mostly available in the parent servlet span, in the case of path and query parameters at least, but they are not parsed out and so they are not searchable. What about an option like the query parameter tagging that is disabled by default?
