### ISSUE TITLE
Bug/Kafka Instrumentation missing some major attributes such as messaging.kafka.consumer.group

### ISSUE THREAD

**Issue by arik-dig** [open-telemetry/opentelemetry-java-instrumentation#7771]
**Describe the bug**
The trace/span of Kafka consumer is missing major attributes - its missing the context of that specific consumer.

**Steps to reproduce**
I ran the sample app by spring-kafka with OTEL agent (version 1.22.1)

**What did you expect to see?**
I expected to see the following attributes being set

1) `messaging.consumer.id` or `messaging.consumer_id` - based on [semantic conventions of messaging consumer](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#consumer) it should be filled

2) `messaging.kafka.consumer.group` or `messaging.kafka.consumer_group` - standard for kafka messaging

3) `messaging.kafka.client.id` or `messaging.kafka.client_id` - standard for kafka messaging

**What did you see instead?**
I did not see the attributes at all

**What version are you using?**
OTEL agent 1.22.1

**Environment**
Compiler: JDK 17
OS: Windows 11

**Comment by arik-dig** [comment]
Here's the trace as captured via Jaeger:

**Trace (as JSON):**
[trace_f44507f70dc13771ba88aedca9f25b73.json.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/10695835/trace_f44507f70dc13771ba88aedca9f25b73.json.txt)

**View from jaeger:**

<img width="404" alt="image" src="https://user-images.githubusercontent.com/104715391/217780124-55d91937-f493-4b65-a74a-f9a080d01752.png">

**Comment by arik-dig** [comment]
BTW seems like in project SmallRye-Reactive-Messaging-Kafka they managed to add those attributes.
[see class KafkaAttributesExtractor](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/tracing/KafkaAttributesExtractor.java#L37)

**Comment by mateuszrzeszutek** [comment]
Hey @arik-dig ,

The maintainers of this project are a very small group, we're aware of this problem but we haven't had enough time yet to fully implement the latest messaging spec changes.

**Comment by arik-dig** [comment]
thanks @mateuszrzeszutek ,
is there any plan to do so?

**Comment by mateuszrzeszutek** [comment]
Yeah, I just started working on that today.

**Comment by arik-dig** [comment]
@mateuszrzeszutek thank you
