### ISSUE TITLE
Getting invalid SpanContext in mongo extension for java OpenTelemetry automatic instrumentation

### ISSUE THREAD

**Issue by vaibhav-paharia** [open-telemetry/opentelemetry-java-instrumentation#7783]
I am writing an extension of OpenTelemetry to input traceId as comment in mongo query. For this I have put an Advice on the find method in com.mongodb.client.MongoCollection. Inside the Advice when I call spanContext.isValid() it returns false, also spanId and traceId have all zeros in them.

`MongoQueryInstrumentation.java
`
```
public class MongoQueryInstrumentation implements TypeInstrumentation {

  @Override
  public ElementMatcher<TypeDescription> typeMatcher() {
    return implementsInterface(named("com.mongodb.client.MongoCollection"));
  }

  public void transform(TypeTransformer transformer) {
    transformer.applyAdviceToMethod(
        named("find").and(takesArgument(0, Bson.class)).and(ElementMatchers.isPublic()),
        AdvicesFind.class.getName());
  }

  @SuppressWarnings("unused")
  public static class AdvicesFind {

    @Advice.OnMethodExit(suppress = Throwable.class)
    public static void onExit(@Advice.Return(readOnly = false) FindIterable<?> result) {
      SpanContext spanContext = Java8BytecodeBridge.currentSpan().getSpanContext();
      System.out.println("traceId:" + spanContext.getTraceId());
      System.out.println("VALID :" + spanContext.isValid());
      result.comment(spanContext.getTraceId());
    }
  }
}
```
`MongoInstrumentationModule.java
`
```
@AutoService(InstrumentationModule.class)
public final class MongoInstrumentationModule extends InstrumentationModule {
  public MongoInstrumentationModule() {
    super("mongo-ext", "mongo-4.0");
  }

  @Override
  public int order() {
    return 1;
  }

  @Override
  public ElementMatcher.Junction<ClassLoader> classLoaderMatcher() {
    return hasClassesNamed("com.mongodb.internal.async.SingleResultCallback");
  }

  @Override
  public List<TypeInstrumentation> typeInstrumentations() {
    return Collections.singletonList(new MongoQueryInstrumentation());
  }
}
```
OUTPUT:

```
traceId:00000000000000000000000000000000
VALID :false
```

I am exporting the logs to zipkin, there db.statement is

`{"find": "sampleCollection", "filter": {"title": "MongoDB"}, "comment": "00000000000000000000000000000000", "$db": "myDb", "lsid": {"id": {"$binary": {"base64": "nOpqMCwHRWe2h+qmVEgGIQ==", "subType": "04"}}}}`

I tried doing similar thing in JDBC by adding a comment containing traceId and spanId and there it worked as expected. There I patched sendQueryString method of NativeProtocolInstrumentation. There Java8BytecodeBridge.currentSpan().getSpanContext() returned a valid spanId but in mongo it does not.

**Comment by laurit** [comment]
I would start by printing out the stack trace from where you observe the invalid context. Check whether this call is running on the same thread that sets the context you expect to see. If it is not you'll need to figure out how to pass context there.
