### ISSUE TITLE
Not possible to use Netty instead of OKHttp

### ISSUE THREAD

**Issue by yassenb** [open-telemetry/opentelemetry-java-instrumentation#7785]
**Describe the bug**
From what I understand it should be possible to switch the underlying implementation of GRPC from the default - OKHttp to Netty. If so, how to do it? If not, please implement

**Steps to reproduce**
Run the java agent. I'm getting weird HTTP 2 errors and would like to try another transport like Netty

**What did you expect to see?**
Support for Netty

**What did you see instead?**
No matter what is on the classpath OKHttp is used foe GRPC OTLP calls

**What version are you using?**
1.22.1

**Environment**
Latest Ubuntu 22.10, Java 17, Kotlin

**Comment by laurit** [comment]
> Run the java agent. I'm getting weird HTTP 2 errors and would like to try another transport like Netty

You will have to give instructions to reproduce the errors you are seeing or at least describe the errors in sufficient detail if you expect someone to attempt doing anything about the said errors.

> No matter what is on the classpath OKHttp is used foe GRPC OTLP calls

Agent uses its own classes not the ones you have in your application.

> From what I understand it should be possible to switch the underlying implementation of GRPC from the default - OKHttp to Netty. If so, how to do it? If not, please implement

I believe the last version where we used netty is https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.7.2 If you so wish you could attempt to build an extension or custom agent that  replaces the default otlp exporter using `ConfigurableSpanExporterProvider` SPI. Calling https://github.com/open-telemetry/opentelemetry-java/blob/d22567480c54b4f0fd87c70554f76716fb19dbe4/exporters/otlp/all/src/main/java/io/opentelemetry/exporter/otlp/trace/OtlpGrpcSpanExporterBuilder.java#L63 should let you use `grpc-java` along with netty. I have not tried it myself so apologies if it doesn't work.

**Comment by mateuszrzeszutek** [comment]
> the only way to use Netty and not the built-in OKHttp GRPC client is to create a custom build of the agent.

Not necessarily -- it should be enough to implement a custom [extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension) that contains a custom [span exporter](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/traces/ConfigurableSpanExporterProvider.java) implementation, along with all the dependencies (netty).
