### ISSUE TITLE
[Request help] how can i get context in my app

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#7802]
I create a propagator to propagate my headers between apps, but i want to get this headers in my app, so i use `Context.current().get(ContextKey.named("ip"));` to get it, but it failed, in the context. i found the key "ip" is in agentcontext, is it possible to get in my app use sdk api?

**Comment by laurit** [comment]
Context keys use identity comparison. Usually it is not possible to read an element that was put in context on agent side from application side. You could create an api where you do the reading from context inside agent code and call that api from the application code, something like https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/distro/bootstrap/src/main/java/com/example/javaagent/bootstrap/AgentApi.java

**Comment by xiangtianyu** [comment]
> Context keys use identity comparison. Usually it is not possible to read an element that was put in context on agent side from application side. You could create an api where you do the reading from context inside agent code and call that api from the application code, something like https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/examples/distro/bootstrap/src/main/java/com/example/javaagent/bootstrap/AgentApi.java

But agent api is not accessible for my application, or you means to instrument the method in my application?

**Comment by laurit** [comment]
> But agent api is not accessible for my application, or you means to instrument the method in my application?

You could have it as a compile time dependency.

**Comment by xiangtianyu** [comment]
> > But agent api is not accessible for my application, or you means to instrument the method in my application?
> 
> You could have it as a compile time dependency.

Are you means that i should load my sdk api in boostrap classloader ? I tried, and that's useless

**Comment by trask** [comment]
@xiangtianyu can you use baggage for this? baggage keys (unlike context keys) should interop be accessible from both agent and app side

**Comment by xiangtianyu** [comment]
> 

I know baggage can, but i want to use my special header. So i want to make a "tiny imitate baggage" and i failed. :<

**Comment by mateuszrzeszutek** [comment]
Hmm, you could use `Baggage` and implement a custom [`TextMapPropagator`](https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java) that'd serialize it into the header you want (see the [baggage propagator](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java) for an example).

**Comment by xiangtianyu** [comment]
> Hmm, you could use `Baggage` and implement a custom [`TextMapPropagator`](https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/propagation/TextMapPropagator.java) that'd serialize it into the header you want (see the [baggage propagator](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/baggage/propagation/W3CBaggagePropagator.java) for an example).

Good idea, i will try
