### ISSUE TITLE
[Request help]Does kafka-Instrument support adding extra tags(attributes)？

### ISSUE THREAD

**Issue by labulalala** [open-telemetry/opentelemetry-java-instrumentation#7807]
I read the source code, but  I coun't find the way to add extra tags. 
I foud that  the tags were created by KafkaProducer.class with code  `Map<String, String> metricTags = Collections.singletonMap("client-id", clientId);` and were set to Instrument  by ` Attributes attributes = toAttributes(metricName.tags());`

So, doses kafka-Instrument support adding extra tags(attributes)？

**Comment by mateuszrzeszutek** [comment]
Hey @labulalala ,

What is your use case? Are you using the javaagent or the Kafka library instrumentation? I'm assuming that you want to add attributes to the producer span -- is that correct?

**Comment by labulalala** [comment]
@mateuszrzeszutek So sorry for my unclear description. I jsut want to add some common tags of my microservice such as microservice name or others to **Attribute Keys**  when kafka reporting metrics.  For example, [according to the usage of metrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/kafka/kafka-clients/kafka-clients-2.6/library/README.md), records-consumed-total is reported with attribute key [client-id, topic], I expect the attribute key contains my tags like [microservice-name, client-id, topic].


I use the Kafka library instrumentation with dependency
```xml
<dependencies>
  <dependency>
    <groupId>io.opentelemetry.instrumentation</groupId>
    <artifactId>opentelemetry-kafka-clients-2.6</artifactId>
    <version>OPENTELEMETRY_VERSION</version>
  </dependency>
</dependencies>
```
and merge the config properties from `KafkaTelemetry.create(OpenTelemetry).metricConfigProperties()` with the configuration used when creating my producer or consumer...

**Comment by trask** [comment]
hi @labulalala, `microservice-name` would typically be set as a resource attribute, which is then available on all span data (depending a bit on whether/how your monitoring backend maps resource attributes)

**Comment by mateuszrzeszutek** [comment]
@labulalala for the microservice name you could use the [`service.name`](https://opentelemetry.io/docs/reference/specification/resource/semantic_conventions/#service) resource attribute. If you're using the javaagent or the autoconfigure module you could do that by setting the `OTEL_SERVICE_NAME` env var.

**Comment by labulalala** [comment]
@mateuszrzeszutek thanks for your suggestion. But if I want to add any custom label(just as the code below)，I cannot find any way to do that.

```java
io.opentelemetry.instrumentation.kafka.internal.KafkaMetricRegistry#toAttributes
private static Attributes toAttributes(Map<String, String> tags) {
    tags.put("custom-label-1", "aaa");  // add label custom-label-1
    tags.put("custom-label-2", "bbb");  // add label custom-label-2

    AttributesBuilder attributesBuilder = Attributes.builder();
    tags.forEach(attributesBuilder::put);
    return attributesBuilder.build();
}
```

**Comment by trask** [comment]
@labulalala if you aren't able to get resource attributes in your monitoring backend, you write a SpanProcessor to add them, e.g. https://github.com/open-telemetry/opentelemetry-android/blob/c911c819f2922657eb85a178c90f8d2318f6cadb/instrumentation/src/main/java/io/opentelemetry/android/GlobalAttributesSpanAppender.java#L27
