### ISSUE TITLE
Should we just remove docs/semantic-conventions.md?

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#7809]
I wanted to update the [docs/semantic-conventions.md](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/semantic-conventions.md) to make sure that it reflects the latest changes in the spec and in this repo, but somewhere in the middle I started asking myself "what's the purpose of this file?"
Is it supposed to contain attributes that we support (i.e. that we have `*AttributeGetter`s for)? (In which case it'd be just a copy of the spec, since we're aiming to support all of them)
Or is it supposed to tell which instrumentation implement which attributes? (In which case perhaps we should document them one by one, instead of tryin to group them all in one file?)
Anyway, in its current shape it doesn't seem to me that this file is useful at all.

**Comment by trask** [comment]
I support removing it, we can revisit later if the need arises for something more detailed than the new semantic conventions column in the supported-libraries doc
