### ISSUE TITLE
Fix JMH benchmark project so that it can run in CI

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#782]
Currently there are some hard-coded paths to make tests run with/ and without/ the javaagent, so some work is needed before they can run in CI.

**Comment by iNikem** [comment]
@trask Why do we want to run JMH in CI? You can actually compare them run to run. Does #595 speak about JMH benchmarks or some new, yet unwritten ones?

**Comment by trask** [comment]
#595 is about new unwritten end-to-end macro benchmarks

I _think_ my goal here was only to have CI validate that the JMH benchmarks are runnable (by doing a short run)

**Comment by iNikem** [comment]
> @trask Why do we want to run JMH in CI? You can actually compare them run to run. Does #595 speak about JMH benchmarks or some new, yet unwritten ones?

Grrr, I meant you CANNOT compare them.

> I think my goal here was only to have CI validate that the JMH benchmarks are runnable (by doing a short run)

Do you still want it? Is it worth spending our time on this?

**Comment by trask** [comment]
Yeah, let's close. I'm sure we'll need to revisit the JMH benchmarks at some point and probably have better ideas then anyways.
