### ISSUE TITLE
More meaningful Span Names for JDBC Instrumentation

### ISSUE THREAD

**Issue by hannahchan** [open-telemetry/opentelemetry-java-instrumentation#7821]
Hi,

I work on a multi-tenanted application where each customer gets their own database. As a result the span names in my JDBC instrumentation look like the following.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/22674140/218925198-94161727-37b5-4825-a048-a8497a4a3338.png">

This results in high cardinality when I generate span metrics because each tenant database is named after the tenant's GUID. Can we update span names from the JDBC instrumentation so that this doesn't happen?

Also do you know why these spans always come in pairs? Just from looking at the first span and its attributes, I can't figure out what the first span is for. I'm assuming it's getting a connection to the database. This span name should also be more descriptive.

**Comment by mateuszrzeszutek** [comment]
Hey @hannahchan ,

> Can we update span names from the JDBC instrumentation so that this doesn't happen?

Right now - no, unfortunately not. The JDBC library instrumentation (the `DataSource` wrapper, to be more precise) could be modified to allow span name customization though.

> Also do you know why these spans always come in pairs? Just from looking at the first span and its attributes, I can't figure out what the first span is for. I'm assuming it's getting a connection to the database. This span name should also be more descriptive.

What's the instrumentation library name? Does the `db.statement` attribute contain any useful info?

**Comment by hannahchan** [comment]
Both spans come from the `io.opentelemetry.jdbc` instrumentation.

Span attribute wise, they both have exactly the same attributes except `db.operation` and `db.statement` is empty on the first span.

**Comment by breedx-splk** [comment]
The [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md) has the database name indicated pretty prominently in span names. 

You might be able to transform the data in a collector pipeline to accomplish what you need.

**Comment by trask** [comment]
@hannahchan are you using the javaagent or library instrumentation?

if using the javaagent, you could create a [javaagent extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension) to modify the span name prior to exporting

if using the library instrumentation, span name customization could be added to that as @mateuszrzeszutek mentioned above

**Comment by hannahchan** [comment]
I'll close this issue. We're not sure yet what we're going to do in this space but will look at using the Java agent extensions.
