### ISSUE TITLE
How opentelemetry support async framwork?

### ISSUE THREAD

**Issue by CHYhave** [open-telemetry/opentelemetry-java-instrumentation#7840]
Firstly, sorry for my poor english. 
In short，i'm building observability of scg(spring cloud  gateway )by open-telemty sdk. However scg is async framework, the thread will be reused by request. For example,  get request A and B, A and B are processed in same thread, A enter the gateway first, then B enter. when A's response return, Span.current() get B's span, A's trace context is overrided by B. Because open-telemtry sdk is thead based.

Have any best practice for async framework like scg?  

I implemented tracing by scg filter as follows.
```
public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        Span startSpan = tracer.spanBuilder("some.request").startSpan();
        Scope scope = startSpan.makeCurrent();
        ServerHttpRequest.Builder requestBuilder = exchange.getRequest().mutate();
        W3CTraceContextPropagator.getInstance().inject(Context.current(), requestBuilder, setter);
        ServerHttpRequest request = requestBuilder.build();
        exchange.getAttributes().put("span", startSpan);
        Mono<Void> returnMono = chain.filter(exchange.mutate().request(request).build()).doOnSuccess((aVoid) -> {
            this.onSuccess(exchange, startSpan);
            String name = Thread.currentThread().getName();
            startSpan.end();
            scope.close();
        }).doOnError((throwable) -> {
            this.onError(exchange, startSpan);
            startSpan.recordException(throwable);
            startSpan.end();
            scope.close();
        });
        return returnMono;
 
 }

```

I use io.opentelemetry.instrumentation.logback.v1_0.OpenTelemetryAppender to record traceId in log, however this appender is thread based, which get Context in treadLocal. In request A and B example, the log will always record B's traceId which result in repeat traceId.Here are part of code of OpenTelemetryAppender.
```
public static ILoggingEvent wrapEvent(ILoggingEvent event) {
    Span currentSpan = Span.current(); // get span from threadLocal
    if (!currentSpan.getSpanContext().isValid()) {
      return event;
    }

   // .....
  }

```

**Comment by laurit** [comment]
Start by examining our reactor instrumentation https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/reactor/reactor-3.1 If you are not using the javaagent then look at the library instrumentation, it is meant to be used without the javaagent. As for the threading issues you should be careful with `makeCurrent`, close the scope when control is transferred to another thread and call `makeCurrent` there again if needed.
