### ISSUE TITLE
opentelemetry-jdbc static init of the Instrumenter is incompatible with SDK Auto-configuration. 

### ISSUE THREAD

**Issue by brunobat** [open-telemetry/opentelemetry-java-instrumentation#7867]
**Describe the bug**
Calling OpenTelemetry.get() from a static block at `io.opentelemetry.instrumentation.jdbc.internal.JdbcSingletons` will instantiate the SDK before any container using `AutoConfiguredOpenTelemetrySdkBuilder` is able to do it at runtime.

When creating a service with the native image, using the Auto-configuration, I see the SDK being initialised in build time:
```
OTel GlobalOpenTelemetry.get() called. stack:java.lang.Throwable
        at io.opentelemetry.api.GlobalOpenTelemetry.get(GlobalOpenTelemetry.java:78)
        at io.opentelemetry.instrumentation.jdbc.internal.JdbcSingletons.<clinit>(JdbcSingletons.java:31)
```
... later, at runtime, when the Auto-configuration kicks in, will try to set it again, blowing up the service.

There is also this bug, not related with Auto-configuration but with live code reload: 
https://github.com/quarkusio/quarkus/issues/29849 On Quarkus dev mode, OTel breaks because we cannot change the SDK instance when reloading the app source.

Basically… Static init calling OpenTelemetry.get() is not really compatible with the auto-configuration. 
**Steps to reproduce**

Create a service using AutoConfiguredOpenTelemetrySdkBuilder at runtime... Can be injected by a bean producer.
Include the opentelemetry-jdbc dependency (will trigger static init of the SDK).
Start the service... It will blow onde the AutoConfiguredOpenTelemetrySdkBuilder builder is called because the sdk was already set.

**What did you expect to see?**
jdbc instrumentation works with AutoConfiguredOpenTelemetrySdkBuilder used at runtime

**What did you see instead?**
```
Caused by: java.lang.IllegalStateException: GlobalOpenTelemetry.set has already been called. GlobalOpenTelemetry.set must be called only once before any calls to GlobalOpenTelemetry.get. If you are using the OpenTelemetrySdk, use OpenTelemetrySdkBuilder.buildAndRegisterGlobal instead.
```
**What version are you using?**
v1.21 and up, at least

**Environment**
% mvn --version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: .../.sdkman/candidates/maven/current
Java version: 17.0.4.1, vendor: Eclipse Adoptium, runtime: .../.sdkman/candidates/java/17.0.4.1-tem
Default locale: en_PT, platform encoding: UTF-8
OS name: "mac os x", version: "13.2", arch: "aarch64", family: "mac"

**Additional context**
The issue can be observed in these PRs: 
https://github.com/quarkusio/quarkus/pull/30033
https://github.com/quarkusio/quarkus/issues/29849

**Comment by brunobat** [comment]
This was happening with otel 1.22... I see that this was merged in the meantime:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7677

**Comment by mateuszrzeszutek** [comment]
Even after that fix `OpenTelemetryDriver` is still using the `GlobalOpenTelemetry`.

WDYT about refactoring your code to use the [`OpenTelemetryDataSource`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/datasource/OpenTelemetryDataSource.java) instead? You can your own `OpenTelemetry` there

**Comment by brunobat** [comment]
That's a good hit, thanks @mateuszrzeszutek

**Comment by mateuszrzeszutek** [comment]
Hey @brunobat ,
Did the [`OpenTelemetryDataSource`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/datasource/OpenTelemetryDataSource.java) solve your issue?

**Comment by brunobat** [comment]
Yes, @mateuszrzeszutek. We are now using the [OpenTelemetryDataSource].
Will close this issue.
