### ISSUE TITLE
Missing jaxrs span in Open Liberty 

### ISSUE THREAD

**Issue by fmhwong** [open-telemetry/opentelemetry-java-instrumentation#7870]
**Describe the bug**
Running a simple JAX-RS application in both WebSphere Application Server traditional and Open Liberty with the latest version of Agent.

I got 3 spans from WebSphere Application Server traditional version 9.0.5.12 on Java 8.
1. `HTTP GET /properties`
2. `JAX-RS getProperties()`
3. `@WithSpan SystemResources.sleep()`

However, I got 2 spans from Open Liberty version 23.0.0.1 on Java 11.
1. `HTTP GET /properties`
2. `@WithSpan SystemResources.sleep()`

The JAX-RS span is missing from Open Liberty.

**Steps to reproduce**

```
import java.util.Random;

import javax.enterprise.context.RequestScoped;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

import io.opentelemetry.instrumentation.annotations.WithSpan;

@RequestScoped
@Path("/properties")
public class SystemResource {

    private static Random rand = new Random(); 
    
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public Response getProperties() throws InterruptedException {
        sleep(rand.nextInt(500));
        return Response.ok(System.getProperties()).build();
    }

    @WithSpan
    private static void sleep(long ms) throws InterruptedException {
        Thread.sleep(ms);
    }
}
```

**What did you expect to see?**
Three spans should be created from Open Liberty.

**What did you see instead?**
Only two spans were created as described above.

**What version are you using?**
opentelemetry-javaagent version 1.23.0

**Environment**
Compiler: OpenJDK 11.0.11
OS: MacOS
Runtime (if different from JDK above): OpenJDK 11.0.17
OS (if different from OS compiled on): Ubuntu 20.04.5 LTS (Focal Fossa) in a container

**Additional context**

**Comment by fmhwong** [comment]
[open-liberty-json.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/10799059/open-liberty-json.txt)
[websphere-application-server-json.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/10799060/websphere-application-server-json.txt)

**Comment by mateuszrzeszutek** [comment]
OpenLiberty 23 uses Javarta EE 9: https://openliberty.io/docs/latest/jakarta-ee9-feature-updates.html
The app server probably does not contain the `javax.*` classes, it has `jakarta.*` classes instead.

Have you tried running the example above using the `jakarta.ws.*` annotations instead?

**Comment by fmhwong** [comment]
I was testing the above class with `jaxrs-2.1` feature in Open Liberty 23.0.0.1.  I also tested with the Jakarta EE 9 version of the app with `restfulWS-3.0` feature in Open Liberty 23.0.0.1.  None of them show the JAX-RS spans.

**Comment by trask** [comment]
@fmhwong if you're able to troubleshoot this and send a PR to fix that would be much appreciated!

**Comment by fmhwong** [comment]
Someone has made a PR.  I can test it when the fix is available.

**Comment by fmhwong** [comment]
The fix is working.  Thanks for the quick turnaround!
