### ISSUE TITLE
Inconsistency on `non_heap` vs. `nonheap` value for memory metrics

### ISSUE THREAD

**Issue by AlexanderWert** [open-telemetry/opentelemetry-java-instrumentation#7876]
## Description
**Describe the bug**
In the [semantic conventions for JVM runtime metrics](https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/runtime-environment-metrics/#jvm-metrics) (on the `process.runtime.jvm.memory.*` metrics) the attribute values for the `type` attribute are defined as `heap` and **`nonheap`**.

Here (in the Java instrumentation) the values are `heap` and **`non_heap`** (**_with underscore!_**) which is not what the semantic conventions define:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/335e36d6e43018eb1fa5942a5614ab8f401045c3/instrumentation/runtime-metrics/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/MemoryPools.java#L50

**Steps to reproduce**
Run the Java agent and observe the JVM memory metrics.

**What did you expect to see?**
The attribute values for `type` to be aligned with the semantic conventions. 

**What did you see instead?**
`non_heap` instead of `nonheap`

**What version are you using?**
1.23.0

**Environment**
not relevant

## Solution alternatives

1. Either fix it in the Java instrumentation / agent to comply with the semantic conventions
2. OR fix the semantic conventions to comply with the Java implementation.

Since this aspect of the semantic conventions only affects Java, Option 2 seems to be the simpler and less intrusive approach.

**Comment by laurit** [comment]
@jack-berg should we change semantic conventions or the code?

**Comment by trask** [comment]
+1 on using `non_heap` (I *think* that's most consistent)

i'll send a spec PR to float the proposal

**Comment by jack-berg** [comment]
Agreed on `non_heap`.
