### ISSUE TITLE
Spring boot actuator not working when deployed in kubernetes with spring-boot-starter 2.7.8

### ISSUE THREAD

**Issue by AkselAllas** [open-telemetry/opentelemetry-java-instrumentation#7891]
Very similar issue to https://stackoverflow.com/questions/75218237/spring-boot-2-7-8-or-3-x-upgrade-tomcat-http-status-404-not-found-on-azure

In kubernetes I get 404 for /actuator/health/liveness with 2.7.8 but not with 2.7.7

Can it be a problem with tomcat version going from 9.0.70 to 9.0.71 in spring-boot-starter 2.7.8?

Using otel agent v1.18.0

**Comment by laurit** [comment]
Firstly verify whether the issue is present with the latest version of opentelemetry java agent. If it is, give instructions how to reproduce, preferably without involving kubernetes.

**Comment by trask** [comment]
> Can it be a problem with tomcat version going from 9.0.70 to 9.0.71 in spring-boot-starter 2.7.8?

ya, it's this backport: https://github.com/apache/tomcat/commit/10a1a6d46d952bab4dfde44c3c0de12b0330da79

we had the same issue when Tomcat 10.1.0 was released which first introduced this change

**Comment by AkselAllas** [comment]
@trask Any suggestions on how to fix this?

**Comment by trask** [comment]
upgrade to the latest opentelemetry-javaagent
