### ISSUE TITLE
Should we make the "test" task also run "integrationTest" task?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#790]
I started to update the contributing docs to reflect that we now have two testing tasks to run, and I ended up wondering if it makes sense to have the `test` task depend on the `integrationTest` so that everything can be run using the `test` task?

And if we want a way to run non-`integrationTest` tests separately, maybe add `unitTest` and have `test` depend on both of those?

EDIT: motivation for this is from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/785#issuecomment-663892862

**Comment by anuraaga** [comment]
I think so - we separated out `integrationTest` to work around issues with instrumenting the JVM, not to run the suites separately so it'd be simpler to have `test` run everything.

**Comment by anuraaga** [comment]
This will also solve an issue I found, I think, where currently `./gradlew :instrumentation:check` doesn't run `integrationTest`

**Comment by iNikem** [comment]
I came from the background, where the majority of tests in a project were "unit", fast tests. And `gradle test` runs those. And `integrationTest` is a separate job for slower tests.

But in this project probably this does not make sense indeed, as 90% of all tests are slow integration tests.

**Comment by iNikem** [comment]
But still, running unit tests before integration ones in a given module may give benefit of fail fast. So we can try not `test.dependsOn integrationTest` but `test.finalizedBy integrationTest`. Maybe that will work too.
