### ISSUE TITLE
Where is the pressure report? I can't find it

### ISSUE THREAD

**Issue by AVANZHAOYONG** [open-telemetry/opentelemetry-java-instrumentation#7915]
I could only find a less detailed report [summary](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/gh-pages/benchmark-overhead/results/release/summary.txt)

**Comment by trask** [comment]
hi @AVANZHAOYONG, can you give us more details what you are looking for?

cc @breedx-splk
