### ISSUE TITLE
Content length for servlet response sometimes recorded as 0

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#793]
Content length for servlet responses is sometimes being recorded as 0. For now we have ignored that case in the assertions.

https://github.com/anuraaga/opentelemetry-auto-instr-java/pull/2#discussion_r460479702

**Comment by FrankSpitulski** [comment]
The tests don't always send the body. In practice I've only ever seen it record 0 when it doesn't send one. I think this is more of a testing issue.

**Comment by anuraaga** [comment]
I think I was seeing it not set in async but set for sync for the same test, could be misremembering though.

**Comment by trask** [comment]
Closing, capturing content length was removed in #1167
