### ISSUE TITLE
Tracer Bean not created

### ISSUE THREAD

**Issue by amexboy** [open-telemetry/opentelemetry-java-instrumentation#7957]
**Describe the bug**
I am trying to use the spring-boot-starter in my very basic demo project. I am trying to use the `Tracer` bean by auto-wiring it in my controller. My gradle build script is aa

**Steps to reproduce**
My gradle build script looks like this

```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.3'
    id 'io.spring.dependency-management' version '1.1.0'
}

group = 'de.kreuzwerker'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation("io.opentelemetry.instrumentation:opentelemetry-jaeger-spring-boot-starter:1.21.0-alpha")
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

```

```

import io.opentelemetry.api.trace.Tracer;
import lombok.AllArgsConstructor;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController("/test")
@AllArgsConstructor
public class TestController {
   private final Tracer tracer;
}
```

**What did you expect to see?**
I expect a Tracer bean to be available [as noted here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md#opentelemetry-tracer-auto-configuration)

**What did you see instead?**
Spring complains that there is no such bean 

**What version are you using?**
1.21.0-alpha

**Environment**
Compiler: (e.g., "Zullu  17")
OS: (e.g., "Mac Ventura 13") 

** Additional Context

For enabling auto-configuration in spring-boot 3, I had to copy the spring.factories file into my repository as described [here](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration)

**Comment by laurit** [comment]
@amexboy Thanks for reporting. The documentation is outdated, you can use either the `OpenTelemetry` or `TracerProvider` bean to get the tracer.

**Comment by laurit** [comment]
I believe the plan was to have separate starters for spring-boot 2 and spring-boot 3 but before that happens doing what @amexboy described feels like a good idea. @mateuszrzeszutek is this ok with you?

**Comment by mateuszrzeszutek** [comment]
I think it's a good idea even if we end up having separate starters for v2 and v3 - in that case it'll allow us to reuse even more code between the two versions.
