### ISSUE TITLE
Drop "apache-" from apache-camel and apache-pulsar instrumentation module names?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#8004]
And maybe apache-dubbo (even though there's also the original alibaba dubbo).

Other top-level apache projects don't have "apache-" in front, e.g.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/a51535d08ee02b3e8e9d8d8390e5b362a1199a2e/docs/supported-libraries.md?plain=1#L24-L39

**Comment by mateuszrzeszutek** [comment]
I think it's fine if we drop it for camel or pulsar; we should keep it if there's any possibility for confusion though (HttpClient, Dubbo too probably)
