### ISSUE TITLE
Remove Advice classes from helperClassNames

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#801]
Nothing is broken, but it can be confusing to see Advice classes in `helperClassNames` (mostly unnecessarily).

A quick search for `Advice",` looks like we are doing this in 5-10 places.

In cases where there's a static method in an Advice class that really is needed, it should probably be moved into another class that is already in the `helperClassNames`

**Comment by mateuszrzeszutek** [comment]
I think that we can close this one since `helperClassNames()` method does not exist anymore.
