### ISSUE TITLE
OpenTelemetry JAVA auto instrumentation is not exporting JVM details to Elastic.

### ISSUE THREAD

**Issue by chandru-kumar** [open-telemetry/opentelemetry-java-instrumentation#8035]
I'm uisng opentelemetry agent to instrument the spring boot application. I built jar and attaching the agent while running the application to export the traces, metrics and logs. I can see the traces exported. But the JVM or host metrics like Heap Memory, GC, Threads, CPU , Memory etc.
`java -javaagent:"C:\OpenTelemetry Demo\opentelemetry-javaagent.jar" -Dotel.resource.attributes=service.name=otel-experimental-service,service.version=1.1,deployment.environment=production -Dotel.exporter.otlp.endpoint=<elastic_apm_url> -Dotel.exporter.otlp.headers="Authorization=Bearer <elastic_secret_key>" -Dotel.metrics.exporter="otlp" -Dotel.logs.exporter="otlp" -jar todo-service-0.0.1-SNAPSHOT.jar`

I expected to see the host and JVM metrics as well. But I cannot see it. Can you pls help in that to export the JVM and host details as well?

Env-
OpenJDK - 17
Otel agent  - 1.23

**Comment by mateuszrzeszutek** [comment]
Hey @chandru-kumar ,

Can you try using the `logging` metrics exporter (or sending the metrics to a [collector](https://github.com/open-telemetry/opentelemetry-collector) instance with debug logging turned on) and check if the javaagent generates the metrics you need?

Also, have you tried contacting someone from Elastic to check if your configuration is correct, and supported by Elastic?

**Comment by chandru-kumar** [comment]
HI @mateuszrzeszutek 
I have checked the elastic configs and it seems correct as I try with Elastic agent, it exports the JVM metrics and Host metrics. 

How can I mention the logging metrics exporter in above command while running the application?

**Comment by mateuszrzeszutek** [comment]
> How can I mention the logging metrics exporter in above command while running the application?

Try `-Dotel.metrics.exporter=logging`. 

> I have checked the elastic configs and it seems correct as I try with Elastic agent, it exports the JVM metrics and Host metrics.

Does Elastic accept OTLP metrics? (Disclaimer: none of the maintainers of this project work for Elastic, so we don't really know its capabilities)

**Comment by chandru-kumar** [comment]
I will check it and update you @mateuszrzeszutek . 

Any other tools visualize the traces, logs and metrics together? I see only Elastic has that ability. If there are any, pls suggest.

**Comment by mateuszrzeszutek** [comment]
Hey @chandru-kumar ,
Did you manage to verify whether the metrics get printed out?
