### ISSUE TITLE
messages from log4j1 library missing in logs from log4j2 application (fails in 1.22.1, but is fixed in 1.23.0)

### ISSUE THREAD

**Issue by stevesea** [open-telemetry/opentelemetry-java-instrumentation#8071]
**Describe the bug**
When a log4j2 application has a dependency on a library using log4j1, log messages are not forwarded to the exporter.

I noticed there was slf4j/log4j fix in the release notes for 1.23, and it looks like that likely fixed this too.

**Steps to reproduce**
Reproduced with this repo: https://github.com/stevesea/2023-03-otel-troubleshooting

**What did you expect to see?**
All log messages I see in a console appender for an app should also be sent to the otel-collector 

**What did you see instead?**
Some log messages from application and its dependent libraries were sent to the otel-collector. But messages from a handful of the app's client libraries were not. 

**What version are you using?**
1.22.1 (will upgrade to latest, 1.24.0)

**Environment**
Compiler: eclipse temurin 1.8.0 362
OS: reproduced on centos VM, and Alpine-based dockerfile

**Comment by laurit** [comment]
@stevesea You are saying that this is already fixed in `1.23.0`. What do you expect from us?

**Comment by stevesea** [comment]
@laurit Sorry, I was unclear. I expected the team to close this issue - marking it already fixed or whatever the appropriate label was for your workflow.

After reproducing the issue with my test case, and finding I could solve it by upgrading the javaagent, I figured I might as well write it up -- maybe it'd help the next user searching the issues for log4j & log exporter problems.
