### ISSUE TITLE
Inconsistence relation between server and child spans

### ISSUE THREAD

**Issue by asafc64** [open-telemetry/opentelemetry-java-instrumentation#8083]
**Describe the bug**
Inconsistence relation between `io.opentelemetry.tomcat-xx` span and `io.opentelemetry.spring-webmvc-xx`.

**Steps to reproduce**
- Have 2 services A and B, where A calls B.
- Make a call to A.
- Open Jaeger, and see that in service A the `io.opentelemetry.tomcat-xx` is **parent** of `io.opentelemetry.spring-webmvc-xx`, and in service B `io.opentelemetry.tomcat-xx` is **sibling** of `io.opentelemetry.spring-webmvc-xx`.

Can also reproduce by:
- Clone https://github.com/piomin/sample-spring-microservices-new
- Add instrumentation by agent to all `department`, `employee`, `organization`, and `gateway` services.
- Run all of them.
- Call `http://localhost:<organization-port>/2/with-employees`

**What did you expect to see?**
Both of the those 2 spans should be parent and child.

**What did you see instead?**
The spans in the inner service where sibling.

**What version are you using?**
1.24.0-alpha

**Environment**
Compiler: Oracle OpenJDK 17.0.3
OS: Microsoft Windows 11 Home

**Additional context**
![image](https://user-images.githubusercontent.com/6837849/226171604-49dd3cff-4fb0-42b9-a3fb-3005e5913ef3.png)

**Comment by laurit** [comment]
These applications include micrometer tracing that seems to interfere. Try removing
```xml
<dependency>
	<groupId>io.micrometer</groupId>
	<artifactId>micrometer-tracing-bridge-otel</artifactId>
</dependency>
<dependency>
	<groupId>io.opentelemetry</groupId>
	<artifactId>opentelemetry-exporter-zipkin</artifactId>
</dependency>
```
from  https://github.com/piomin/sample-spring-microservices-new/blob/75b2175e758a2be362ee47a7684b1b04262f7224/employee-service/pom.xml#L48 (the same dependencies are also in other modules) and see if it works any better.
