### ISSUE TITLE
Instrumentation for xxl-job

### ISSUE THREAD

**Issue by freshchen** [open-telemetry/opentelemetry-java-instrumentation#8084]
I want to add a Instrumentation for xxl-job, a lightweight distributed scheduling framework

**Comment by breedx-splk** [comment]
Project is here: https://github.com/xuxueli/xxl-job. Latest is xxl-jb release is 2.4.0 as of today. 👍🏻

**Comment by steverao** [comment]
Please assign it to me, I will complete it soon. @laurit

**Comment by freshchen** [comment]
@steverao Thank you very much. Are you in Lao Jiang’s WeChat group?

**Comment by steverao** [comment]
> @steverao Thank you very much. Are you in Lao Jiang’s WeChat group?

Yes：）
