### ISSUE TITLE
Trace context is empty in Spring ErrorHandler

### ISSUE THREAD

**Issue by amseager** [open-telemetry/opentelemetry-java-instrumentation#8086]
Suppose you have this kind of [ErrorHandler](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/ErrorHandler.html):

```
@Component
public class MyErrorHandler implements ErrorHandler {

  @Override
  public void handleError(Throwable throwable) {
    <some code>
  }
}
```

If you throw an exception somewhere, you'll have an empty trace context inside of the error handler (both trace id and span id will contain zeroes) even though in the "original" code it's filled properly.

I'm using java agent instrumentation (1.23.0), so I can't add annotations like `@WithSpan` here.

**Comment by laurit** [comment]
Could you provide a minimal application that reproduces your issue.

**Comment by amseager** [comment]
@laurit please check https://github.com/amseager/oteltest

Basically, for this kind of method:

```
	@Scheduled(fixedRate = 10000)
	public void test() {
		log.info("test1");
		throw new RuntimeException("test2");
	}
```
and this error handler method:
```
	@Override
	public void handleError(Throwable t) {
		log.error("caught: ", t);
	}
```
we have trace & span ids set correctly for a "successful" test1 log but we don't have them for an "error" test2 log:
```
2023-03-20T23:45:16.877+02:00 trace_id=158451678213014fa11713601fae6684 span_id=ecf4836d3f592b31  INFO 13364 --- [   scheduling-1] com.example.oteltest.MyScheduler         : test1
2023-03-20T23:45:16.877+02:00 trace_id= span_id= ERROR 13364 --- [   scheduling-1] com.example.oteltest.MyErrorHandler      : caught: 

java.lang.RuntimeException: test2
	at com.example.oteltest.MyScheduler.test(MyScheduler.java:14) 
...
```
