### ISSUE TITLE
Ratpack instrumentation seems to over-record exceptions

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#810]
I found that Ratpack instrumentation records exceptions twice when a user defines an error handler

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/ratpack-1.4/src/main/java/io/opentelemetry/auto/instrumentation/ratpack/TracingHandler.java#L71

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/ratpack-1.4/src/main/java/io/opentelemetry/auto/instrumentation/ratpack/ErrorHandlerAdvice.java#L32

Gut feeling is latter doesn't need to be instrumented.

**Comment by trask** [comment]
I tried it out, `ErrorHandlerAdvice` is needed for async and "forked" requests (whatever those are :smile:)
