### ISSUE TITLE
Code samples in spring instrumentation documentation are outdated

### ISSUE THREAD

**Issue by laurit** [open-telemetry/opentelemetry-java-instrumentation#8103]
Spring instrumentation documentation in https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring contains code samples that don't work any more. Such as injecting tracer with
```java
@Autowired
private Tracer tracer;
```
or
```java
OpenTelemetrySdk.getTracerManagement()
```

**Comment by breedx-splk** [comment]
@shubhamtechgeek are you still updating the samples? Thanks in advance!

**Comment by shubhamtechgeek** [comment]
Hey @mateuszrzeszutek , @breedx-splk  was not able to dedicate time as I was dealing with some personal issues. Will release this one for someone else.

**Comment by zenvzenv** [comment]
Is there any new progress on this document?
