### ISSUE TITLE
ClassNotFound error when using extension with static initialization outside advice class methods

### ISSUE THREAD

**Issue by valera7979** [open-telemetry/opentelemetry-java-instrumentation#8108]
**Describe the bug**
I'm trying to write extension to manage spans for my methods. I tried to use this [code ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/a51535d08ee02b3e8e9d8d8390e5b362a1199a2e/instrumentation/methods/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/methods) and little modify it for my purposes. But when I run my application with opentelemetry-javaagent and my extension I get ClassNotFoundError for MethodSingletons class. When I add my module to open-telemetry project in `instrumentation` module and build javaagent all works fine with this javaagent. So obviously something wrong with how extensions implemented in open-telemetry. When I'm creating simple extension without any code outside of advice class methods all works fine also. But I need static Instrumenter<ClassAndMethod, Void> instance instantiated outside of advice class methods.

**Steps to reproduce**
1. Create extension with this [code ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/a51535d08ee02b3e8e9d8d8390e5b362a1199a2e/instrumentation/methods/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/methods). 
2. Hardcode the methods you want to collect spans:
```
@AutoService(InstrumentationModule.class)
public class MethodInstrumentationModule extends InstrumentationModule {
  public MethodInstrumentationModule() {
    super("methods");
  }

  @Override
  public List<TypeInstrumentation> typeInstrumentations() {
    Set<String> methods = Set.of("someMethod");
    return List.of(new MethodInstrumentation("org.some.SomeClass", methods),
        new MethodInstrumentation("org.some.SomeOtherClass", methods));
  }
```

3. Build extension and run your app with opentelemetry-javaagent and your extension.
 4. Run `someMethod` in your app.

**What did you expect to see?**
`someMethod` spans.

**What did you see instead?**
ClassNotFoundError in the log

**What version are you using?**
1.23.0

**Environment**
Compiler: "AdoptOpenJDK 11
OS: MacOS

**Comment by laurit** [comment]
Could you also provide the full stack trace that you get and the extension that reproduces this issue. Without looking at what exactly you have done it is hard to say what exactly fails. Maybe you are building your extension without the `muzzle-generation` plugin? However the issue could also be in something else.

**Comment by valera7979** [comment]
I'm building my extension without muzzle-generation plugin. Just building jar with mvn install. The simplest code to reproduce error: build next extension:

MethodInstrumentationModule class (define here your classes you want to intercept):

```
import com.google.auto.service.AutoService;
import io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule;
import io.opentelemetry.javaagent.extension.instrumentation.TypeInstrumentation;

import java.util.List;
import java.util.Set;

@AutoService(InstrumentationModule.class)
public class MethodsInstrumentationModule extends InstrumentationModule {

    public MethodsInstrumentationModule() {
        super("some-methods");
    }

    @Override
    public List<TypeInstrumentation> typeInstrumentations() {
        return List.of(
                new MethodSpans(
                        Set.of(
                        "org.some.package.Some1",
                        "org.some.package.Some2",
                        "org.some.package.Some3"))
        );
    }

}
```

MethodSpans:

```
import io.opentelemetry.instrumentation.api.instrumenter.Instrumenter;
import io.opentelemetry.instrumentation.api.instrumenter.util.ClassAndMethod;
import io.opentelemetry.javaagent.extension.instrumentation.TypeInstrumentation;
import io.opentelemetry.javaagent.extension.instrumentation.TypeTransformer;
import net.bytebuddy.asm.Advice;
import net.bytebuddy.description.type.TypeDescription;
import net.bytebuddy.matcher.ElementMatcher;

import java.util.Set;

import static io.opentelemetry.javaagent.extension.matcher.AgentElementMatchers.hasSuperType;
import static net.bytebuddy.matcher.ElementMatchers.namedOneOf;

public class MethodSpans implements TypeInstrumentation {
    private final Set<String> classNames;
    private final Set<String> methodNames;

    public MethodSpans(Set<String> classNames) {
        this.classNames = classNames;
        this.methodNames = Set.of("someMethod");
    }

    @Override
    public ElementMatcher<TypeDescription> typeMatcher() {
        return hasSuperType(namedOneOf(classNames.toArray(new String[0])));
    }

    @Override
    public void transform(TypeTransformer transformer) {
        transformer.applyAdviceToMethod(
                namedOneOf(methodNames.toArray(new String[0])),
                MethodSpans.class.getName() + "$MethodAdvice");
    }

    @SuppressWarnings("unused")
    public static class MethodAdvice {
        public static Instrumenter<ClassAndMethod, Void> INST = null;

        @Advice.OnMethodEnter(suppress = Throwable.class)
        public static void onEnter() {
            System.out.println(INST);
        }
    }

}

```

The dependency list:
```
<dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk-extension-autoconfigure-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-instrumentation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.javaagent</groupId>
            <artifactId>opentelemetry-javaagent-extension-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.auto.service</groupId>
            <artifactId>auto-service</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.javaagent</groupId>
            <artifactId>opentelemetry-javaagent</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-instrumentation-api-semconv</artifactId>
            <version>1.23.0-alpha</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-instrumentation-api-annotation-support</artifactId>
            <version>1.15.0-alpha</version>
            <!--            <scope>runtime</scope>-->
        </dependency>

```
I'm using 1.24.0 opentelemetry version. 
Build this and add path to jar to `-Dotel.javaagent.extensions` variable in VM options or corresponding env variable.
When someMethod will be invoked you get error:

```
java.lang.NoClassDefFoundError: org/my/opentelemetry/javaagent/extension/MethodSpans$MethodAdvice
	at org.some.package.Some1.someMethod(Some1.java:33)
```

Some1 class content is not influent on this error.  Also you can use [code ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/a51535d08ee02b3e8e9d8d8390e5b362a1199a2e/instrumentation/methods/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/methods) from opentelemetry instrumentation module and build it as extension. Just hardcode methods to intercept them.

**Comment by laurit** [comment]
`muzzle-generation` plugin automatically figures out which classes your advice needs. If you are not using it you'll have to do this manually. See
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/writing-instrumentation-module.md#inject-additional-instrumentation-helper-classes-manually-with-the-getadditionalhelperclassnames-method

**Comment by valera7979** [comment]
Thanks. I missed 
```
@Override
  public List<String> getAdditionalHelperClassNames() {
    return typeInstrumentations.isEmpty()
        ? emptyList()
        : singletonList("io.opentelemetry.javaagent.instrumentation.methods.MethodSingletons");
  }
```

in https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/a51535d08ee02b3e8e9d8d8390e5b362a1199a2e/instrumentation/methods/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/methods/MethodInstrumentationModule.java
But in my implementation this class worked without this method if build it as javaagent part,  so I decided it's extension issue. In my last example It is required to add something like :

```
@Override
    public List<String> getAdditionalHelperClassNames() {
        return List.of(MethodSpans.MethodAdvice.class.getName());
    }
```

It works.
