### ISSUE TITLE
The agent reports an error trace after using shardingsphere

### ISSUE THREAD

**Issue by huange7** [open-telemetry/opentelemetry-java-instrumentation#8109]
**Describe the bug**
When using shardingsphere for database and table splitting, the trace data reported by the agent is not the actual database and table executed.

**Steps to reproduce**
The springboot web project introduces shardingsphere for database and table splitting, and then reproduces it when db writes are performed.

**What did you expect to see?**
In the tag data of trace, `db.table` and `db.name` should show the actual database table name and database name, not the alias before the sub-base and sub-table

**What did you see instead?**
In the tag data of trace, db.table and db.name show the aliases before splitting the database and table
<img width="899" alt="image" src="https://user-images.githubusercontent.com/48885776/226927863-86077970-b4b6-4009-9e3f-e0270ee3153f.png">

**What version are you using?**
1.24.0

**Environment**
Compiler: ("jdk 1.8")
SpringBoot: 2.3.3.RELEASE
mybatis-spring-boot-starter: 2.1.3
sharding-jdbc-spring-boot-starter: 4.1.1

**Comment by laurit** [comment]
Resoled with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8110
