### ISSUE TITLE
Default bytebuddy advice to non-inline for tests?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#811]
I don't know if this is a good idea in case inline / non-inline can expose different bugs. But if the "reflects production" aspect isn't a big concern, it could be nice to default tests to run with non-inline instrumentation to make IntelliJ debugging much simpler.

**Comment by iNikem** [comment]
IMO tests should definitely reflect intended production usage as much as possible.

**Comment by trask** [comment]
I would want CI tests to inline (reflecting prod), not sure if we can make that behavior conditional(?)

**Comment by anuraaga** [comment]
Yeah I think it means having a back-of-the-hand estimate on how often there could be a difference that results in breakage. If a CI test failure can't be reproduced locally at first due to the inlining behavior <1% of the time, then I would say defaulting the tests (not CI) to non-inline could provide an overall better debugging experience. But if it would cause mysterious failure 5% of the time, then probably should just close this without doing anything.

**Comment by trask** [comment]
I think it's worth trying. Better debug experience would be a big plus.

**Comment by trask** [comment]
> not sure if we can make that behavior conditional(?)

just clarifying: this question was about the technical feasibility (I forgot that annotation values can be assigned to constants, which we can calculate conditionally)

**Comment by trask** [comment]
Hm, I don't think `inline = false` works with `@Advice.Argument(readOnly = false)`, `@Advice.Return(readOnly = false)` or `@Advice.Local`

**Comment by anuraaga** [comment]
Ah that's pretty limiting. Guess we have to stick with inline then.
