### ISSUE TITLE
HttpServerTest calls runUnderTrace for controllers

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#812]
I noticed HttpServerTest calls runUnderTrace which creates a new span

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/testing-common/src/main/groovy/io/opentelemetry/auto/test/base/HttpServerTest.groovy#L217

I don't understand how to grok this, I would expect our instrumentation to create all the needed spans for server tests and this makes debugging harder for me. What is this runUnderTrace for?

**Comment by iNikem** [comment]
Instrumentation under test, e.g. servlet's one, will not create spans for downstream controller call. This `runUnderTrace` wraps a new span around controller method invocation. I suspect they are there to unify middleware tests, e.g. servlets, with framework tests, e.g. Spring MVC: for both of them to have both SERVER and INTERNAL spans.

**Comment by anuraaga** [comment]
Hmm - I found it pretty confusing when debugging (e.g., `recordException` is called from test code, not instrumentation) :( If it's just to save test lines of code, I'd generally err on the side of copy-paste then make tests too complex or harder to reason about - work fine until the test fails and then it hurts.

**Comment by trask** [comment]
I think the purpose of the `controller` spans is to make sure we are propagating context down to the place in the server framework where users write their code.

**Comment by anuraaga** [comment]
Ah that makes sense, but I guess it could just validate there's a context instead of creating a new span? That would match my expectations of the test better.

**Comment by trask** [comment]
i'm not sure how we would validate that it's the right context, without exporting a span and verifying it in the test?

**Comment by anuraaga** [comment]
We could probably save off the span context somewhere and assert on it, there's probably something possible. A bit of complexity will be worth to get confidence that e.g. an exception will be on the server span, not an artificial one, by looking at the test. This is what really confused me.

**Comment by iNikem** [comment]
You cannot read data from Spans. They are write only for the moment. Until they are exported, that is :)

**Comment by anuraaga** [comment]
If it's for checking the context, I guess it'd be ok we can read the `SpanContext` and check the IDs right? I'm guessing that's what @trask means by "validate that it's the right context"

**Comment by trask** [comment]
> we can read the `SpanContext` and check the IDs

I'm not sure what we would check the IDs against?

**Comment by trask** [comment]
> We could probably save off the span context somewhere and assert on it

Oh I see, save it to some global that we can assert on?

**Comment by trask** [comment]
> get confidence that e.g. an exception will be on the server span, not an artificial one

Were you not getting the exception at all on the server span, or were you getting the exception in two places (server span and artificial span)?

**Comment by trask** [comment]
Closed by #897
