### ISSUE TITLE
OTEL javaagent way: Tracing request body and response body

### ISSUE THREAD

**Issue by KamJohn** [open-telemetry/opentelemetry-java-instrumentation#8129]
**Is your feature request related to a problem? Please describe.**

OTEL javaagent way: Tracing request body and response body 

**Why i am heer**
super embarrassing ...

![image](https://user-images.githubusercontent.com/33511022/227531526-5c03c2e4-2cd7-4199-b408-5dc04e50f974.png)

**Comment by trask** [comment]
@KamJohn did you mean to close this?
