### ISSUE TITLE
Un-sampled spanContext created in OpenCensus-Shim is lost when agent is enabled

### ISSUE THREAD

**Issue by jianwu** [open-telemetry/opentelemetry-java-instrumentation#8148]
**Describe the bug**
When a Span with scope is created in OpenCensus and converted by OpenCensus-Shim, if the span is not sampled by OC sampler, when we immediately query the current SpanContext, we will always got invalid span. So all the sub-span created under the scope becomes orphan spans. 

**Steps to reproduce**
Following is code snippet on how to re-produce it: 
```java
// Set OC sampler as 50% in initialization code
    TraceConfig traceConfig = Tracing.getTraceConfig();
    traceConfig.updateActiveTraceParams(
        traceConfig
            .getActiveTraceParams()
            .toBuilder()
            .setSampler(Samplers.probabilitySampler(0.5)).build());

// Create a parent span scope and log the span context information
   for(int i = 0; i < 10; i ++){
      try(Scope ignore = tracer.spanBuilder("greetMethod").startScopedSpan()) {
        Context context = Context.current();
        Span currentSpan = Span.fromContext(context);
        log.info( "traceId=" + tracer.getCurrentSpan().getContext().getTraceId() +
            ";otTraceId=" + currentSpan.getSpanContext().getTraceId());
      }
   }
```
Run with `OTel-Agent` and `OpenCensus-Shim` as dependencies, we will get following out put. 
```
INFO - traceId=TraceId{traceId=00000000000000000000000000000000};otTraceId=00000000000000000000000000000000 
INFO - traceId=TraceId{traceId=a69fb3fd993dac23095dcc9559ebb4ec};otTraceId=a69fb3fd993dac23095dcc9559ebb4ec 
...
```
In 50% chance, the span is invalid. after debugging, this is when the span is not sampled. 

**What did you expect to see?**
We should see all the valid trace/span id in the sub-scope 

**What did you see instead?**
traceId/SpanId is invalid if it's the parent span is not sampled.

**What version are you using?**
1.24.0

**Environment**
Compiler: openjdk version "17.0.5" 2022-10-18 LTS
OS: MacOS

**Additional context**
After some debugging, found the root cause is in class: `io.opentelemetry.javaagent.instrumentation.opentelemetryapi.trace.Bridging.toAgentOrNull()`, which expects type of `ApplicationSpan`. However when it's not sampled, it's set as: `OpenTelemetryNoRecordEventsSpanImpl` in class: `io.opentelemetry.opencensusshim.OpenTelemetrySpanBuilderImpl`, so this method will returns null.

**Comment by jianwu** [comment]
One possible fix is to skip the OC sampler. Just depends on OT sampler. In practice, if we use agent, that means we will also collect OT traces, so OT sampler should be configured, in that case, it doesn't make sense to be sampled by both OC and OT sampler.

**Comment by trask** [comment]
@jianwu is this resolved by https://github.com/open-telemetry/opentelemetry-java/pull/5604?
