### ISSUE TITLE
Cannot inject custom label into metric 

### ISSUE THREAD

**Issue by gophper** [open-telemetry/opentelemetry-java-instrumentation#8150]
How does the opentelemetry java agent add default attributes to all metrics, such as host, so that  to distinguish specific machine instances from the chart,

``
java -Dotel.service.name="myapp" -Dotel.resource.attributes="host=test01"  -Dotel.traces.exporter="otlp" -Dotel.metrics.exporter="otlp"  -Dotel.exporter.otlp.endpoint="http://127.0.0.1:4317" -javaagent:./opentelemetry-javaagent.jar -jar target/example-spring-boot-app.jar

``

I want:

process_runtime_jvm_system_cpu_load_1m{job="myapp",label1="value1",host="test01"} 2.89306640625

actually: 

process_runtime_jvm_system_cpu_load_1m{job="myapp",label1="value1"} 2.89306640625

Env-
OpenJDK - 8
Otel agent - 1.23

thanks

**Comment by mateuszrzeszutek** [comment]
Hey @gophper ,

All the metrics exported using the OTLP exporter should have a resource attached to them -- that includes the attributes you pass through `otel.resource.attributes`.
In Prometheus (since you posted a Prometheus example) the resource attributes are included as the [`target_info`](https://opentelemetry.io/docs/reference/specification/compatibility/prometheus_and_openmetrics/#resource-attributes-1) metric.

**Comment by gophper** [comment]
don't know what to do，how to achieve the effect by adding host resources?

**Comment by gophper** [comment]
like this common issue. it would be nice if otel could provide some example

**Comment by caorong** [comment]
@mateuszrzeszutek I have the same problem. 
In my situation, my cluster e.g book-service has 2 instance, but the `process.runtime.xx` metric exported do not have instance ip to distinguish 2 instance. 

the metric exported to otel-collector are covered by the latter instance.

**Comment by mateuszrzeszutek** [comment]
> don't know what to do，how to achieve the effect by attaching host resources?

I don't really know what your setup is, and where the problem actually lies. Are you using OTLP or Prometheus? What metrics backend are you using? Does the metrics backend you're using support OTLP resource/Prometheus `target_info`?

**Comment by mateuszrzeszutek** [comment]
Please include a reproduction scenario that shows the difference between the actual and expected output.
