### ISSUE TITLE
Cannot configuration multiple target to otel.instrumentation.methods.include 

### ISSUE THREAD

**Issue by KyongSik-Yoon** [open-telemetry/opentelemetry-java-instrumentation#8172]
**Describe the bug**
When configure otel.instrumentation.methods.include property to Opentelemetry javaagent java process start failed.  

Start failed -> -Dotel.instrumentation.methods.include=a.b.C[d,e];aa.bb.CC[dd,ee]
Start succeed -> -Dotel.instrumentation.methods.include=a.b.C[d,e]

I found this option here. -> https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/#creating-spans-around-methods-with-otelinstrumentationmethodsinclude

**Steps to reproduce**
Install javaagent with otel.instrumentation.methods.include option.

**What did you expect to see?**
Span should be collected in otel.instrumentation.methods.include option.

**What did you see instead?**
Process start failed.

**What version are you using?**
1.24.0

**Environment**
Compiler: Temurin JDK 11
OS: Ubuntu 20.04

**Comment by trask** [comment]
hi @KyongSik-Yoon did you mean to close this? thx

**Comment by KyongSik-Yoon** [comment]
@trask It's my mistake. I reopened it.

**Comment by trask** [comment]
what error are you getting?

> -Dotel.instrumentation.methods.include=a.b.C[d,e];aa.bb.CC[dd,ee]

maybe it's a shell issue with escaping the `;`?

try

java -javaagent:opentelemetry-javaagent.jar "-Dotel.instrumentation.methods.include=a.b.C[d,e];aa.bb.CC[dd,ee]" -jar ...

**Comment by KyongSik-Yoon** [comment]
@trask Thanks! It's working for me.

before
--
ENV JAVA_OPTS="$JAVA_OPTS -Dotel.instrumentation.methods.include=jdbc.GhostStatement[executeQuery,executeUpdate];jdbc.GhostStatement[executeQuery,executeUpdate]"

after
--
ENV JAVA_OPTS="$JAVA_OPTS \"-Dotel.instrumentation.methods.include=jdbc.GhostStatement[executeQuery,executeUpdate];jdbc.GhostStatement[executeQuery,executeUpdate]\""

**Comment by mateuszrzeszutek** [comment]
> But how about print log in this case?

If the shell treats everything after `;` as a separate statement, we're effectively only getting `-Dotel.instrumentation.methods.include=a.b.C[d,e]` in the agent - which is in a valid format. We have no way of knowing if there was anything after `]` in the Java process.

**Comment by KyongSik-Yoon** [comment]
I undestand. Close this issue.
