### ISSUE TITLE
service.version does not appear as metric label

### ISSUE THREAD

**Issue by spedersen-emailage** [open-telemetry/opentelemetry-java-instrumentation#8176]
**Describe the bug**

The `service.version` attribute does not appear as a label in metrics, but _does_ appear as a resource in spans.

**Steps to reproduce**

Enable `service.version` attribute via Java option or environment variable.

**What did you expect to see?**

A `version` (or equivalent) label in metrics.

**What did you see instead?**

No `version` (or equivalent) label in metrics.

**What version are you using?**

1.24.0

**Environment**

OS: Amazon Linux 2
Runtime (if different from JDK above): openjdk 17.0.6 2023-01-17 LTS

**Additional context**

We have three resource attributes defined via the `OTEL_RESOURCE_ATTRIBUTES` environment variable:

* `service.name`
* `service.instance.id`
* `service.version`

We found that `service.name` and `service.instance.id` appear as labels in our metrics, but `service.version` does not. It does, however, appear in spans/traces as a resource. This is outlined in the table below:

| Attribute           | Metric Label | Span Resource       |
|:--------------------|:-------------|:--------------------|
| service.name        | job          | service.name        |
| service.instance.id | instance     | service.instance.id |
| service.version     | -            | service.version     |

At this point I'm uncertain if this "problem" originates from the JIA, OTel itself, or Grafana. Or if this is by design. I can move this to a feature enhancement issue if it becomes one.

I would appreciate any insight you could offer while I continue to troubleshoot.

**Comment by trask** [comment]
hi @spedersen-emailage, I'm guessing you are using prometheus exporter for metrics? check out: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#resource-attributes, it looks like `service.version` should be available via the `target_info` metric

**Comment by spedersen-emailage** [comment]
Unfortunately, the `target_info` doesn't exist. :(

Aside from the default instrumentation metrics, the only additional metrics for the associated job are:

* `otlp_exporter_exported{}`
* `otlp_exporter_seen{}`
* `processedSpans{}`
* `queueSize{}`

We use the [`prometheusremotewrite`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/README.md) exporter to send metrics to an `/api/prom/push` endpoint.

Could this be an issue with Prometheus?

**Comment by trask** [comment]
> Unfortunately, the `target_info` metric doesn't exist. :(

it looks like this was implemented and should be available in 1.24.0: https://github.com/open-telemetry/opentelemetry-java/pull/5039

> We use the [`prometheusremotewrite`](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/README.md) exporter to send metrics to an `/api/prom/push` endpoint.

ah, it looks like you are using OTLP from Java -> Collector? The PR above implements `target_info` in the Java SDK's prometheus (pull) exporter.

you may need to see what the level of support for `target_info` is in the Collector's prometheusremotewrite

**Comment by mateuszrzeszutek** [comment]
Hey @spedersen-emailage ,

Did you manage to consult the collector team about this?
