### ISSUE TITLE
Can we hide the `integrationTest` and `latestDepTest` task from Intellij Run?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#818]
Any idea if we can hide the `integrationTest` and `latestDepTest` task from Intellij Run, so it doesn't always prompt you to pick one of `test` vs `integrationTest` vs `latestDepTest`? Or is this a bad idea?

**Comment by trask** [comment]
Ok, hiding `latestDepTest` is probably a bad idea. But hiding `integrationTest` would be nice after #817

**Comment by iNikem** [comment]
Why does it bother you enough? You have to pick one only once for a given test.

But answering your question: I don't think it's possible. If there are several Gradle tasks of type `Test` IDEA has to know which one to use.

Locally you can instruct IDEA not to use Gradle to run tests, that may solve your problem as well.

**Comment by trask** [comment]
thx, this makes sense, closing this, and opened #819
