### ISSUE TITLE
Document how to run tests in Intellij

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#819]
A couple of confusing things:

* ~which to choose: `test`, `integrationTest` or `latestDepTest`~
  * ~(this is not confusing from command-line since not prompted for these others)~
* ~how to run `slickTest`, `lagomTest`, and `resteasy31Test` (which run `onlyIf` Java 8)~
  * ~(also document how to run these from command line)~

EDIT: `integrationTest` has been consolidated into `test`

EDIT: `onlyIf` Java 8 tests have been fixed to run on Java 11 (or are to be deleted #1007)

EDIT: `latestDepTest` is now property based `-DlatestDepTest=true`

**Comment by iNikem** [comment]
@trask It seems that this can be closed?

**Comment by trask** [comment]
👍
