### ISSUE TITLE
Align spring boot starter configuration properties with SDK autoconfigure properties

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#8191]
Spring boot starter configuration properties: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md#configuration-properties

SDK autoconfigure properties: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md

Examples:

* in the spring boot starter we have `otel.exporter.otlp.enabled=false` and in the SDK autoconfigure module we have `otel.(traces|metrics|logs).exporter=none`
* in the spring boot starter we have `otel.springboot.resource.attributes` and in the SDK autoconfigure module we have `otel.resource.attributes`
* in the spring boot starter we have `otel.springboot.resource.attributes.service.name` and in the SDK autoconfigure module we have `otel.service.name`

**Comment by jeanbisutti** [comment]
> I will rename `otel.springboot.resource.attributes` and `otel.springboot.resource.attributes.service.name `. cc @zeitlinger

@zeitlinger Just noticed you have just done it in #https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9950!

**Comment by zeitlinger** [comment]
yes, didn't actually see this ticket. I'll implement the rest as well.
