### ISSUE TITLE
in opentelemetry , only springmvc span and jdbc span ,not exists method span 

### ISSUE THREAD

**Issue by freshgeek** [open-telemetry/opentelemetry-java-instrumentation#8197]
in opentelemetry , only springmvc span and jdbc span ,not exists method span 

like this :
<img width="862" alt="image" src="https://user-images.githubusercontent.com/20513615/229343373-355278ab-2454-443d-9a84-4547eebed687.png">

acturally, this many level methods , thread executor, spring event publish and consumer 

this is my env : 

```
export OTEL_EXPORTER_OTLP_PROTOCOL=grpc
export OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED=true

```

**Comment by freshgeek** [comment]
maybe , I'm blind

[https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2574](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2574)

[https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/#creating-spans-around-methods-with-otelinstrumentationmethodsinclude](https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/#creating-spans-around-methods-with-otelinstrumentationmethodsinclude)

same , can support wildcard ,or another good idea for batch add my project method span  with agent

**Comment by trask** [comment]
@freshgeek let us know if this is still an issue, or if it's a duplicate of #2574

**Comment by freshgeek** [comment]
> @freshgeek let us know if this is still an issue, or if it's a duplicate of #2574

yep

**Comment by DGuhr** [comment]
I had the same problem, so I created a java agent extension and published it at https://github.com/DGuhr/spring-otel-extended to solve it. Maybe it is of help for some other folks, feel free to grab it as base for your extension.
