### ISSUE TITLE
OpenTelemetry Automatic instrumentation - General usability question

### ISSUE THREAD

**Issue by banandh** [open-telemetry/opentelemetry-java-instrumentation#8227]
I'm using automatic instrumentation in my springboot app.

1. Would like to return the traceId being generated from Opentelemetry agents in my application response header so it will be used for request tracing.

2. Currently adding -javaagent for automatic instrumentation, would like to include this javaagent jar in classpath and enforce this instrumentation via manifest.mf 

SpringBoot maven plugin creates a executable jar , in that i wanted to include this Launcher-Agent-Class to point to the opentelemetry agent class so that it can be automatically added whenever the jar is executed

**Comment by trask** [comment]
> Would like to return the traceId being generated from Opentelemetry agents in my application response header so it will be used for request tracing.

this isn't supported out-of-the-box since it's not part of the OpenTelemetry specification (yet?), but you could implement it using a [javaagent extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension#extensions) using the new `HttpServerResponseCustomizer` implemented in #7990 and #8095

> SpringBoot maven plugin creates a executable jar , in that i wanted to include this Launcher-Agent-Class to point to the opentelemetry agent class so that it can be automatically added whenever the jar is executed

I'm not sure if anyone has tried this. It may not work since we add the javaagent jar to the bootstrap classpath, and that could be problematic if the javaagent classes are in an uber jar. Let us know how if you have any success / run into any problems.

**Comment by trask** [comment]
also check out https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/runtime-attach

**Comment by banandh** [comment]
> also check out https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/runtime-attach

This really helps. Will try out  :)

**Comment by banandh** [comment]
> specification

May be I missed to convey my requirement clearly. What I wanted is "use automatic instrumentation and get the traceId inside the service either by adding opentelemetry api jars as dependency or someother way".

**Comment by mateuszrzeszutek** [comment]
> May be I missed to convey my requirement clearly. What I wanted is "use automatic instrumentation and get the traceId inside the service either by adding opentelemetry api jars as dependency or someother way".

We have that feature already -- you can add the `opentelemetry-api` dependency to your app, and use the [`Span.current()`](https://opentelemetry.io/docs/instrumentation/java/manual/#get-the-current-span) to retrieve the current span in your code. (you can also use the OTel API to add any manual instrumentation that you want, and that the agent does not provide out of the box)

**Comment by banandh** [comment]
> custom launcher agent class

Can you point some examples. Not sure whether , i understood it rightly

**Comment by banandh** [comment]
> > also check out https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/runtime-attach
> 
> This really helps. Will try out :)

This runtime attach has a limitation "The application is running on a JRE (a JDK is necessary, see https://github.com/raphw/byte-buddy/issues/374)". Usually runtime contains JRE not the JDK so it can fail in higher environment

**Comment by laurit** [comment]
> > custom launcher agent class
> 
> Can you point some examples. Not sure whether , i understood it rightly

I don't believe anybody has tried this before, so there is no sample code.
