### ISSUE TITLE
[help wanted]A question about AdditionalLibraryIgnoredTypesConfigurer

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#8241]
There are some code in AdditionalLibraryIgnoredTypesConfigurer
```java
.allowClass("org.springframework.boot.web.embedded.tomcat.TomcatWebServer$")
.allowClass("org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader")
.allowClass("org.springframework.boot.web.servlet.DelegatingFilterProxyRegistrationBean$")
.allowClass("org.springframework.boot.StartupInfoLogger$")
```
I found some class such as "org.springframework.boot.StartupInfoLogger", there are "$" at the end of classname, but there is no inner class in there classes, what's the design reasons of it?

**Comment by laurit** [comment]
There are inner classes in older versions of `StartupInfoLogger`, see https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot/src/main/java/org/springframework/boot/StartupInfoLogger.java

**Comment by xiangtianyu** [comment]
> There are inner classes in older versions of `StartupInfoLogger`, see https://github.com/spring-projects/spring-boot/blob/1.5.x/spring-boot/src/main/java/org/springframework/boot/StartupInfoLogger.java

I cannot find inner class in this link... 
Is this config means that i cannot instrument the method directlly in StartupInfoLogger?

**Comment by laurit** [comment]
There is an inner class in https://github.com/spring-projects/spring-boot/blob/10a5cef4ef33e7c86d18e1f92793c2aaa57d5a82/spring-boot/src/main/java/org/springframework/boot/StartupInfoLogger.java#L102-L106 there are more in the following methods.

> Is this config means that i cannot instrument the method directlly in StartupInfoLogger?

Yes, by `AdditionalLibraryIgnoredTypesConfigurer ` excludes classes in `org.springframework.boot` from instrumentation. You can use a custom `IgnoredTypesConfigurer` and `allowClass` to override this.

**Comment by xiangtianyu** [comment]
> There is an inner class in https://github.com/spring-projects/spring-boot/blob/10a5cef4ef33e7c86d18e1f92793c2aaa57d5a82/spring-boot/src/main/java/org/springframework/boot/StartupInfoLogger.java#L102-L106 there are more in the following methods.
> 
> > Is this config means that i cannot instrument the method directlly in StartupInfoLogger?
> 
> Yes, by `AdditionalLibraryIgnoredTypesConfigurer ` excludes classes in `org.springframework.boot` from instrumentation. You can use a custom `IgnoredTypesConfigurer` and `allowClass` to override this.

I see, thanks for answering
