### ISSUE TITLE
[Help wanted]WARN muzzleMatcher  Missing method 

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#8242]
I create a new instrumentation module like this:
```
@AutoService(InstrumentationModule.class)
public class MineInstrumentationModule extends InstrumentationModule {
  public MineInstrumentationModule() {
    super("mine", "mine-1.0");
  }

  @Override
  public List<TypeInstrumentation> typeInstrumentations() {
    return Arrays.asList(new MineHeaderInstrumentation(), new MineEventInstrumentation());
  }
}
```

and i add a Instrumentation:
```
public class MineHeaderInstrumentation implements TypeInstrumentation {
  @Override
  public ElementMatcher<TypeDescription> typeMatcher() {
    return named("com.example.api.MineUtils");
  }

  @Override
  public void transform(TypeTransformer transformer) {
    transformer.applyAdviceToMethod(
        named("getHeader"),
        MineHeaderInstrumentation.class.getName() + "$MagicAdvice");
  }

  @SuppressWarnings("unused")
  public static class MagicAdvice {
    @Advice.OnMethodExit(onThrowable = Throwable.class, suppress = Throwable.class)
    public static void onExit(
        @Advice.Return(readOnly = false) FlowHeader result) {
      // do something use my sdk
    }
  }
```

cause i used my sdk, so i add it into bootstrap:
```
plugins {
  id("otel.javaagent-bootstrap")
}

dependencies {
  implementation("com.example:example-api:1.0.0")
}
```

It works well so far, but when i add a new Instrumentation like this:
```
public class MineEventInstrumentation implements TypeInstrumentation {
  @Override
  public ElementMatcher<TypeDescription> typeMatcher() {
    return named("com.example.springreceiver.SpringReceiverApplication");
  }

  @Override
  public void transform(TypeTransformer transformer) {
    transformer.applyAdviceToMethod(
        named("main"),
        MineEventInstrumentation.class.getName() + "$EventAdvice");
  }

  public static class EventAdvice {
    @Advice.OnMethodEnter(suppress = Throwable.class)
    public static void onEnter(
    ) {
      System.out.println("1212121212121");
    }
  }
}
```

it will print such error :
```
[otel.javaagent 2023-04-07 18:23:19:884 +0800] [main] WARN muzzleMatcher - Instrumentation skipped, mismatched references were found: mine [class io.opentelemetry.javaagent.shaded.instrumentation.javaagent.mine.MineInstrumentationModule] on jdk.internal.loader.ClassLoaders$AppClassLoader@5c8da962
[otel.javaagent 2023-04-07 18:23:19:885 +0800] [main] WARN muzzleMatcher - -- io.opentelemetry.javaagent.shaded.instrumentation.javaagent.mine.MineHeaderInstrumentation$MagicAdvice:35 Missing method com.example.api.mineheader.MineHeader#fromContext(Lio/opentelemetry/javaagent/shaded/io/opentelemetry/context/Context;)Lcom/example/api/mineheader/MineHeader;
```

And when i remove the `new MineEventInstrumentation()`, it works all right. What happens?

**Comment by laurit** [comment]
Agent includes a shaded version of the `opentelemetry-api` where `io.opentelemetry.context` package is renamed to `io.opentelemetry.javaagent.shaded.io.opentelemetry.context`. We automatically apply these renames to extension classes as they are loaded, but for classes that you add to boot loader you'll have to do the shading yourself. I believe this is implemented in the sample distro https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/distro

**Comment by xiangtianyu** [comment]
emmm, i can understand it, but why it works all right when i removed `MineEventInstrumentation`, it's strange because `MineEventInstrumentation` even do nothing

**Comment by laurit** [comment]
> emmm, i can understand it, but why it works all right when i removed MineEventInstrumentation, it's strange because MineEventInstrumentation even do nothing

Sorry, without reproducing it I don't think it is possible to explain that. Perhaps you commented out `MineHeaderInstrumentation` instead of `MineEventInstrumentation`? Or perhaps when you test it you load `com.example.api.MineUtils` but don't load `com.example.springreceiver.SpringReceiverApplication`. Having the empty advice would still trigger muzzle check for the whole module.

**Comment by xiangtianyu** [comment]
Actually, `com.example.api.MineUtils` was only imported by sdk, but didn't use at all. And i found that the "muzzleMatcher log" prints when my `MineEventInstrumentation` was running(but the code is in `MineHeaderInstrumentation`), it's really strange. I was completely confused. : (

The code with only `MineHeaderInstrumentation` is running successfully for month, but when i add a new Instrumentation `MineEventInstrumentation`, it can't work well. Can it be a problem for the index of muzzle check? Or something special?

**Comment by xiangtianyu** [comment]
I create a demo to reproduce it.

Agent code demo  [https://github.com/xiangtianyu/opentelemetry-java-instrumentation branch muzzle_debug](https://github.com/xiangtianyu/opentelemetry-java-instrumentation/tree/muzzle_debug)

sdk code demo https://github.com/xiangtianyu/otel-agent-sdk

user application code demo https://github.com/xiangtianyu/spring-demo

you can run `gradle assemble` in agent to get the agent jar and run `mvn install` in sdk code to get sdk

and then you can run the application demo with agent and sdk. You will get logs like this:
```
[otel.javaagent 2023-04-11 12:21:09:927 +0800] [main] WARN io.opentelemetry.javaagent.tooling.instrumentation.MuzzleMatcher - Instrumentation skipped, mismatched references were found: mine [class io.opentelemetry.javaagent.instrumentation.demo.MineInstrumentationModule] on sun.misc.Launcher$AppClassLoader@18b4aac2
[otel.javaagent 2023-04-11 12:21:09:927 +0800] [main] WARN io.opentelemetry.javaagent.tooling.instrumentation.MuzzleMatcher - -- io.opentelemetry.javaagent.instrumentation.demo.MineHeaderInstrumentation$MineAdvice:30 Missing method com.example.otel.MineHeader#fromContext(Lio/opentelemetry/javaagent/shaded/io/opentelemetry/context/Context;)Lcom/example/otel/MineHeader;

```

But if you modify the agent code to delete the `MineEventInstrumentation` in instrumentation/demo/javaagent, the warn log won't output again.

**Comment by xiangtianyu** [comment]
> I think this happens because the sdk classes (e.g. `com.example.otel.MineUtils`) are available in both the boot loader and application class loader. When `MineEventInstrumentation` instruments `com.example.springdemo.SpringDemoApplication` it triggers muzzle match in application class loader that finds `MineUtils` in application class loader not the one in boot loader that would actually be loaded. When `MineHeaderInstrumentation` instruments `MineUtils` it works because this class is loaded from boot loader. Strictly speaking it does not make sense to instrument a class that is inside agent, @xiangtianyu you may wish to check whether this is really what you want. Perhaps you should be shading the sdk that you put inside the agent? Or perhaps you should not include the sdk in the application?

why the class appears in both classloader? When i set it into bootstrap, the application should not load it again.

**Comment by xiangtianyu** [comment]
I tried to build a my custom ability likes "baggage", but i found it's difficult to do like this. In my imagination, i can do propagator in agent, and get the data in context in application with my sdk. But i found agent do many job to serve for baggage, and i cannot to do the same for my "custom baggage"

**Comment by laurit** [comment]
> why the class appears in both classloader? When i set it into bootstrap, the application should not load it again.

Your demo application also depends on the sdk https://github.com/xiangtianyu/spring-demo/blob/544cacfcae0281819f36cbd169fee1216317fe27/pom.xml#L31-L35 So the application class loader also contains the sdk. As the application class loader uses parent first delegation sdk classes are loaded from boot loader. Muzzle check uses resource lookups. There the situation is a bit tricky. Agent gets added to boot loader with https://docs.oracle.com/javase/9/docs/api/java/lang/instrument/Instrumentation.html#appendToBootstrapClassLoaderSearch-java.util.jar.JarFile- which only makes agent classes available for loading in boot loader but not for resource lookups. To compensate for this we let muzzle search from the agent jar after the class loader. But as class loader already found the resource we end up doing the muzzle check with the resource in the app loader not the one in boot loader.

**Comment by laurit** [comment]
> By the way, i didn't find how the agent add class to bootstrap by using `id("otel.javaagent-bootstrap")` Could you please tell me where is the code implementation?

Agent adds itself to boot loader in https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/2dfe64a08b4a328f12dabd32475982280cd29366/javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/OpenTelemetryAgent.java#L65-L98 using `Instrumentation.appendToBootstrapClassLoaderSearch`

**Comment by xiangtianyu** [comment]
IMO, Agent will add itself to bootstrap by `appendToBootstrapClassLoaderSearch`, but it does not mean that it must be loaded by bootstrap. Otherwise use 
```
the plugins {
  id("otel.javaagent-bootstrap")
}
```
means it will be forced to add to bootstrap classloader. So my application will not load the class in bootstrap again.

Am i misunderstand about it ?

**Comment by laurit** [comment]
```
plugins {
  id("otel.javaagent-bootstrap")
}
```
Is just a build time thing that places the classes from given module to the root of the agent jar instead of the `inst` directory.  `appendToBootstrapClassLoaderSearch` is needed to make boot loader load the classes from the root of the jar. Also https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/bootstrap/BootstrapPackagesConfigurer.java may be needed to ensure that these classes are visible in other class loaders. Content of `inst` is loaded by a different class loader.

**Comment by xiangtianyu** [comment]
Ok, i see. Back to the original problem, it seems that "shade my sdk in agent to distinguish it from the sdk import from application" can solve the problem.

**Comment by laurit** [comment]
Please reopen if you have more questions.
