### ISSUE TITLE
BASE2_EXPONENTIAL_BUCKET_HISTOGRAM aggregation causes histogram data loss

### ISSUE THREAD

**Issue by spedersen-emailage** [open-telemetry/opentelemetry-java-instrumentation#8248]
**Describe the bug**

The `BASE2_EXPONENTIAL_BUCKET_HISTOGRAM` option for `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION` caused histogram data loss.

**Steps to reproduce**

Set `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION to `BASE2_EXPONENTIAL_BUCKET_HISTOGRAM`.

**What did you expect to see?**

Histogram data.

**What did you see instead?**

No Histogram data. 

**What version are you using?**

v1.24.0

**Environment**

OS: Amazon Linux 2
Runtime: openjdk 17.0.6 2023-01-17 LTS
OTel: v0.72.0
Java IA: v1.24.0

**Additional context**

We have a containerized Java app that runs the JIA and sends metrics via OTLP to the host's OTel agent by way of the bridge0 interface. The OTel agent sends metrics to Prometheus using the `prometheusremotewrite` exporter. We use default instrumentation for both JVM and Spring Boot. Today we tried to set `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION` to `BASE2_EXPONENTIAL_BUCKET_HISTOGRAM` and it "broke" the default histograms:

* http_server_duration
* http_server_request_size
* http_server_response_size
* http_client_duration
* http_client_response_size
* http_client_response_size
* process_runtime_jvm_gc_duration

After the update was rolled out, all data from these histograms stopped. When reverted back to the default after approx. 40 minutes, data resumed. The default for `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION` is `EXPLICIT_BUCKET_HISTOGRAM`, which we do not explicitly set.

We didn't see any errors logged to stdout or stderr. Reviewing documentation, we didn't spot anything additional that needed to be configured or any caveats to be considered.

https://opentelemetry.io/docs/reference/specification/metrics/sdk_exporters/otlp/
https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#exporters

Here are the parameters we set, with `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION` included:

```
OTEL_METRICS_EXPORTER="otlp"
OTEL_TRACES_EXPORTER="otlp"
OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION="BASE2_EXPONENTIAL_BUCKET_HISTOGRAM"
OTEL_EXPORTER_OTLP_ENDPOINT="http://172.17.0.1:4317"
OTEL_SERVICE_NAME="fake-app-name-otlp"
OTEL_RESOURCE_ATTRIBUTES="service.instance.id=$(cat /proc/self/cgroup | head -n 1 | cut -d '/' -f3),service.version=$(echo $BUILD_ID)"
```

Data (or lack thereof) was visualized in Grafana. I've opened a case w/ them as well to see if it's a problem with Prometheus or Grafana itself.

<img width="2488" alt="base2_data" src="https://user-images.githubusercontent.com/92553912/230652592-8a683f4c-05f0-4682-a559-aa01fcd24f4a.png">

**Comment by spedersen-emailage** [comment]
This could be an issue w/ Prometheus. Just covering all bases while we continue to research the issue.

**Comment by spedersen-emailage** [comment]
Enabled debug, nothing currently stands out - but unless it's an obvious error, we don't know what we're looking for.

Confirmed it only affects histograms; other metrics are doing fine. I pulled what I assume is the metrics section from `DEBUG io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdkBuilder`:

```
meterProvider=SdkMeterProvider{
  clock=SystemClock{}, 
    resource=Resource{
    schemaUrl=https://opentelemetry.io/schemas/1.18.0, 
    attributes={
      container.id="<unique_container_id>", 
      host.arch="amd64", 
      host.name="465eca8f5cd1", 
      os.description="Linux 4.14.309-231.529.amzn2.x86_64", 
      os.type="linux", 
      process.command_line="/usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/java -Xmx5G -javaagent:/opentelemetry-javaagent.jar -Dotel.javaagent.debug=true -Djava.security.egd=file:/dev/./urandom", 
      process.executable.path="/usr/lib/jvm/java-17-amazon-corretto.x86_64/bin/java", 
      process.pid=1, 
      process.runtime.description="Amazon.com Inc. OpenJDK 64-Bit Server VM 17.0.6+10-LTS", 
      process.runtime.name="OpenJDK Runtime Environment", 
      process.runtime.version="17.0.6+10-LTS", 
      service.instance.id="<unique_task_id>", 
      service.name="<app_name>-otlp", 
      service.version="20230410.1", 
      telemetry.auto.version="1.24.0", 
      telemetry.sdk.language="java", 
      telemetry.sdk.name="opentelemetry", 
      telemetry.sdk.version="1.24.0"
    }
  }, 
  metricReaders=[
    PeriodicMetricReader{
      exporter=io.opentelemetry.exporter.otlp.metrics.OtlpGrpcMetricExporter@36b4fe2a, 
      intervalNanos=60000000000
    }
  ], 
  views=[]
}, 
```

There are few mentions of `*metric*` in the debug logs. Here are the unique entries:

```
[otel.javaagent <timestamp>] [main] DEBUG io.opentelemetry.javaagent.tooling.instrumentation.InstrumentationLoader - Loading instrumentation dropwizard-metrics [class io.opentelemetry.javaagent.instrumentation.dropwizardmetrics.DropwizardMetricsInstrumentationModule]
[otel.javaagent <timestamp>] [main] DEBUG io.opentelemetry.javaagent.extension.instrumentation.InstrumentationModule - Instrumentation dropwizard-metrics is disabled
[otel.javaagent <timestamp>] [main] DEBUG io.opentelemetry.javaagent.shaded.instrumentation.jmx.engine.JmxMetricInsight - Empty JMX configuration, no metrics will be collected for InstrumentationScope io.opentelemetry.jmx
[otel.javaagent <timestamp>] [supportability_metrics_reporter] DEBUG io.opentelemetry.javaagent.shaded.instrumentation.api.internal.SupportabilityMetrics - Suppressed Spans by 'io.opentelemetry.apache-httpclient-4.0' (CLIENT) : <#>
```

**Comment by spedersen-emailage** [comment]
When this was run locally with `OTEL_METRICS_EXPORTER=logging` with BASE2 enabled, we could see hits in the logs from `ImmutableMetricData` for histograms like `http.server.duration`. When moved to our dev environment and using `OTEL_METRICS_EXPORTER=otlp`, there were no longer any hits in the logs.

```
[otel.javaagent 2023-04-10 09:42:20:480 -0700] [PeriodicMetricReader-1] INFO io.opentelemetry.exporter.logging.LoggingMetricExporter - Received a collection of 22 metrics for export.
...
[otel.javaagent 2023-04-10 09:42:20:481 -0700] [PeriodicMetricReader-1] INFO io.opentelemetry.exporter.logging.LoggingMetricExporter - metric: ImmutableMetricData{resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.18.0, attributes={host.arch="x86_64", host.name="<hostname>", os.description="Mac OS X 12.6.3", os.type="darwin", process.command_line="/Users/<user>/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/java -javaagent:opentelemetry-javaagent.jar -Dotel.javaagent.debug=true", process.executable.path="/Users/<user>/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/java", process.pid=2299, process.runtime.description="Amazon.com Inc. OpenJDK 64-Bit Server VM 17.0.3+6-LTS", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="17.0.3+6-LTS", service.name="<app_name>-otlp", telemetry.auto.version="1.24.0", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.24.0"}}, =InstrumentationScopeInfo{name=io.opentelemetry.tomcat-7.0, version=1.24.0-alpha, schemaUrl=null, attributes={}}, name=http.server.duration, description=The duration of the inbound HTTP request, unit=ms, type=HISTOGRAM, data=ImmutableHistogramData{aggregationTemporality=CUMULATIVE, points=[ImmutableHistogramPointData{getStartEpochNanos=1681144880463960000, getEpochNanos=1681144940469531000, getAttributes={http.flavor="1.1", http.method="POST", http.route="/api/v7", http.scheme="http", http.status_code=200, net.host.name="localhost", net.host.port=5000}, getSum=1075.200716, getCount=7, hasMin=true, getMin=8.603985, hasMax=true, getMax=1014.889514, getBoundaries=[0.0, 5.0, 10.0, 25.0, 50.0, 75.0, 100.0, 250.0, 500.0, 750.0, 1000.0, 2500.0, 5000.0, 7500.0, 10000.0], getCounts=[0, 0, 5, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], getExemplars=[ImmutableDoubleExemplarData{filteredAttributes={}, epochNanos=1681144907994410000, spanContext=ImmutableSpanContext{traceId=51fed7c05ee60ad4962f3795b78e287a, spanId=0fc5edfc7a97a522, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, value=8.603985}, ImmutableDoubleExemplarData{filteredAttributes={}, epochNanos=1681144904508772000, spanContext=ImmutableSpanContext{traceId=cc9d46ce08dc6bbe9a1294878f640b17, spanId=2e1ccf521e219e03, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, value=13.627508}, ImmutableDoubleExemplarData{filteredAttributes={}, epochNanos=1681144901956243000, spanContext=ImmutableSpanContext{traceId=b704e56e2e8e54f7f89c3382149fc7bb, spanId=2cfa571560a3c10d, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, value=1014.889514}]}]}}
...
[otel.javaagent 2023-04-10 09:42:20:481 -0700] [PeriodicMetricReader-1] INFO io.opentelemetry.exporter.logging.LoggingMetricExporter - metric: ImmutableMetricData{resource=Resource{schemaUrl=https://opentelemetry.io/schemas/1.18.0, attributes={host.arch="x86_64", host.name="<hostname>", os.description="Mac OS X 12.6.3", os.type="darwin", process.command_line="/Users/<user>/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/java -javaagent:opentelemetry-javaagent.jar -Dotel.javaagent.debug=true", process.executable.path="/Users/<user>/Library/Java/JavaVirtualMachines/corretto-17.0.3/Contents/Home/bin/java", process.pid=2299, process.runtime.description="Amazon.com Inc. OpenJDK 64-Bit Server VM 17.0.3+6-LTS", process.runtime.name="OpenJDK Runtime Environment", process.runtime.version="17.0.3+6-LTS", service.name="<app_name>-otlp", telemetry.auto.version="1.24.0", telemetry.sdk.language="java", telemetry.sdk.name="opentelemetry", telemetry.sdk.version="1.24.0"}}, instrumentationScopeInfo=InstrumentationScopeInfo{name=io.opentelemetry.runtime-metrics, version=1.24.0-alpha, schemaUrl=null, attributes={}}, name=process.runtime.jvm.gc.duration, description=Duration of JVM garbage collection actions, unit=ms, type=HISTOGRAM, data=ImmutableHistogramData{aggregationTemporality=CUMULATIVE, points=[ImmutableHistogramPointData{getStartEpochNanos=1681144880463960000, getEpochNanos=1681144940469531000, getAttributes={action="end of minor GC", gc="G1 Young Generation"}, getSum=176.0, getCount=34, hasMin=true, getMin=1.0, hasMax=true, getMax=18.0, getBoundaries=[0.0, 5.0, 10.0, 25.0, 50.0, 75.0, 100.0, 250.0, 500.0, 750.0, 1000.0, 2500.0, 5000.0, 7500.0, 10000.0], getCounts=[0, 25, 8, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], getExemplars=[]}]}}
```

**Comment by breedx-splk** [comment]
> Switched to OTEL_METRICS_EXPORTER=logging in our dev environment and confirmed that with OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION="BASE2_EXPONENTIAL_BUCKET_HISTOGRAM" set, it still appears to generate metrics.

FWIW the boundaries in the log message above don't look to be exponential...they look to be the default explicit ones.

When troubleshooting situations like this, it is often helpful to enable the debug logging exporter in the collector as well. That way you can get a stronger sense of what the _external_ process is seeing.

Relevant snips from `collector.yaml`:
```yaml
exporters:
  logging/debug:
    loglevel: debug
...
service:
  pipelines:
    metrics:
      exporters: [logging/debug, otlphttp, etc/whatever]
```

**Comment by spedersen-emailage** [comment]
> > Switched to OTEL_METRICS_EXPORTER=logging in our dev environment and confirmed that with OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION="BASE2_EXPONENTIAL_BUCKET_HISTOGRAM" set, it still appears to generate metrics.
> 
> FWIW the boundaries in the log message above don't look to be exponential...they look to be the default explicit ones.
> 
> When troubleshooting situations like this, it is often helpful to enable the debug logging exporter in the collector as well. That way you can get a stronger sense of what the _external_ process is seeing.
> 
> Relevant snips from `collector.yaml`:
> 
> ```yaml
> exporters:
>   logging/debug:
>     loglevel: debug
> ...
> service:
>   pipelines:
>     metrics:
>       exporters: [logging/debug, otlphttp, etc/whatever]
> ```

Yeah, that's a good point. They're definitely the default boundaries. Changing the collector's configuration is a bit more of a pain; we might need to figure out an easier way to test this.

**Comment by spedersen-emailage** [comment]
After I spent some time to debug this locally and confirm that both the Java IA and OTel collector appeared to function fine, Grafana confirmed there was currently no support for exponential histograms in Grafana Cloud/Prometheus at this time. It's on the roadmap.

**Comment by breedx-splk** [comment]
Thanks for taking the time to circle back on this @spedersen-emailage.
