### ISSUE TITLE
[Help Needed] Trace ID and Span Id is showing as 00000000000

### ISSUE THREAD

**Issue by vkroy100** [open-telemetry/opentelemetry-java-instrumentation#8269]
I have created a simple Maven project using Intellij, and i have written a code for accepting a HTTP request and invoking other Maven project service. When i tried to inject trace Id and span Id in the logs using logback, it is showing as blank string and when i manually tried to print the trace id and span id, it showing as 0000000000.

I expect to see the actual trace id and span id but not able to see it in the logs.

I have followed the following documentation : https://help.sumologic.com/docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/java/traceid-spanid-injection-into-logs-configuration/

**Comment by laurit** [comment]
Trace and span id of all zeroes denote a missing/invalid trace. Perhaps there isn't an active trace in the code path that logs these? If you believe this is a bug then please provide a minimal application that reproduces your issue.

**Comment by vkroy100** [comment]
I am trying to log the spanId and trace id inside the handle() function of HttpHandler class, 
In io.opentelemetry.exporter.logging.LoggingSpanExporter section the traceId and span id are coming but when i am trying to log it then it is not coming. Is there any extra configuration which is needed ?

**Comment by laurit** [comment]
@vkroy100 `HttpHandler` is a common interface name that is used in many frameworks, which one of them are you using? Do you use manual instrumentation or javaagent?

**Comment by vkroy100** [comment]
i am trying with javaagent automatic instrumentation. I am using HttpHandler in a maven project

**Comment by vkroy100** [comment]
Code Snippet : 
package org.example;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import io.opentelemetry.api.trace.Span;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;

import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

public class Main {

    static Logger logger = LoggerFactory.getLogger(Main.class);
    private static class MyHttpHandler implements HttpHandler {

        @Override
        public void handle(HttpExchange httpExchange) throws IOException {
            String requestParamValue=null;
            logger.info(Span.current().getSpanContext().getTraceId());
            if("GET".equals(httpExchange.getRequestMethod())) {
                requestParamValue = "Hello world";
                HttpClient httpClient = HttpClient.newHttpClient();
                HttpRequest request = HttpRequest.newBuilder()
                        .version(HttpClient.Version.HTTP_1_1)
                        .uri(URI.create("http://localhost:5002/test"))
                        .header("Content-Type", "application/json")
                        .GET()
                        .build();
                HttpResponse response = null;
                try {
                    response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
                    request = HttpRequest.newBuilder()
                            .version(HttpClient.Version.HTTP_1_1)
                            .uri(URI.create("http://localhost:5001/client"))
                            .header("Content-Type", "application/json")
                            .header("Access-Control-Allow-Origin", "*")
                            .header("Access-Control-Allow-Methods", "GET, POST, DELETE, PUT, OPTIONS, HEAD")
                            .header("Access-Control-Allow-Headers", "Content-Type, Accept, X-Requested-With")
                            .header("Access-Control-Allow-Credentials", "true")
                            .GET()
                            .build();
                    response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
                } catch (InterruptedException e) {
                    throw new RuntimeException(e);
                }

            }
            handleResponse(httpExchange,requestParamValue);
        }
        private void handleResponse(HttpExchange httpExchange, String requestParamValue)  throws  IOException {
            OutputStream outputStream = httpExchange.getResponseBody();
            httpExchange.sendResponseHeaders(200, requestParamValue.length());
            outputStream.write(requestParamValue.getBytes());
            outputStream.flush();
            outputStream.close();
        }
    }
    public static void main(String[] args) throws IOException {
        HttpServer httpServer = HttpServer.create(new InetSocketAddress("localhost",
                5000),0);
        httpServer.createContext("/test", new MyHttpHandler());
        httpServer.start();
    }
}

**Comment by mateuszrzeszutek** [comment]
Hey @vkroy100 ,
We do not have instrumentation for the `com.sun` HTTP server; so it is quite natural that no SERVER span is created for `HttpHandler`.

**Comment by vkroy100** [comment]
Hi @mateuszrzeszutek ,then which one i have to use, any recommendation ?

**Comment by mateuszrzeszutek** [comment]
We publish the list of supported libraries and application servers [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md).
If you're looking for something simple to set up in a small demo app, I've used the embedded Jetty for such purposes before -- we're actually using it in several test classes in this project, e.g. [this one](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/tapestry-5.4/javaagent/src/test/groovy/TapestryTest.groovy).

**Comment by vkroy100** [comment]
ok let me try these

**Comment by vkroy100** [comment]
Hi @mateuszrzeszutek , from where i can download the below dependency to add it in a TIBCO Software project. 
The dependencies are : 
<dependency>
    <groupId>io.opentelemetry.instrumentation</groupId>
    <artifactId>opentelemetry-logback-1.0</artifactId>
    <version>1.9.2-alpha</version>
    <scope>runtime</scope>
</dependency>

**Comment by laurit** [comment]
@vkroy100 you can download it from maven central repository https://central.sonatype.com/ Note that `opentelemetry-logback-1.0` was renamed to `opentelemetry-logback-mdc-1.0` a while ago.
