### ISSUE TITLE
Use github tags to control project version

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java-instrumentation#8295]
Instead of needing to update the version for each release, consider using a plugin to determine the version based on the repo's git tag:

https://github.com/allegro/axion-release-plugin
https://github.com/qoomon/gradle-git-versioning-plugin

This has the added benefit in reducing merge conflicts with branches between versions.

Maybe this is less beneficial because we like to update other things as part of the release like the changelog:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8294

**Comment by tylerbenson** [comment]
Thanks for the links.  I'm not familiar with that plugin.  Does it automate all the file changes needed?
It seems like the version is still part of the source code, which doesn't help with the conflicts as I mentioned.
Anyway, just seeing if this was something anyone had interest in.  Not trying to push it.

**Comment by trask** [comment]
I personally like having the version number (somewhere) in source control, and found using only the git tag a little too magical

**Comment by tylerbenson** [comment]
Sounds good.  I'll close the issue then.
