### ISSUE TITLE
instrumentationScopeName can't custom?

### ISSUE THREAD

**Issue by daoweili** [open-telemetry/opentelemetry-java-instrumentation#8301]
**Describe the bug**
 When I use a custom meter and set instrumentationScopeName，but the scopeName is not effective.
i used version is 1.24.0.

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/3362644/232013730-c9e7af00-0860-4b4e-ab4b-89cb24f9e19c.png)
![image](https://user-images.githubusercontent.com/3362644/232014028-e0b241a9-4f1a-45df-a0db-2490ef7df6c3.png)
![image](https://user-images.githubusercontent.com/3362644/232014363-1967ea99-504a-4839-8bf8-db9c09ec79d4.png)

![image](https://user-images.githubusercontent.com/3362644/231999164-00f44a69-2e56-4cd1-a9f6-82eee85ab39e.png)

How can i get the right scopeName?

**Comment by trask** [comment]
hi @daoweili! are you using the Java agent or no? is this only a problem for metrics or also for traces (spans)?

**Comment by daoweili** [comment]
> 

yes, i use the Java agent, metrics and traces are seems to be the same.

**Comment by daoweili** [comment]
> > 
> 
> hi @trask! yes, i used the Java agent, this problem is only in the metrics.

this problem is in the clickhouse exporter, i compare the column of Kafka and Clickhouse.
