### ISSUE TITLE
Document test bytecode manipulation infrastructure

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#831]
I dove into `SpockRunner`, `AgentSpecification` yesterday, primarily with the goal of understanding why we need to have separate `test` and `integrationTest` - our agent goes to so much effort to not affect a user's app, I sort of would expect the same machinery to work for tests.

I think some documentation on what's going on in the tests can be helpful, I'll jot down my notes from digging and questions here

`SpockRunner` has several functions
- "Shadow" the test class - it causes the test class to be loaded in a custom classloader instead of junit's default which is the app classloader
- It sets this custom classloader as the context classloader, presumably for servlet engines like tomcat
- Setup the bootstrap classpath. This seems to be injecting the same classes into the bootstrap loader which our agent would. Primarily the OpenTelemetry API, logging, and servlet
- It ensures there aren't any bootstrap classes in test classes
- Initializes `ByteBuddy` by calling `ByteBuddy.install`. This creates an `Instrumentation` object which can be used by `AgentTestRunner` to install the agent and reset it

`AgentSpecification` seem to only be to override `private static final Config INSTANCE` to be public and non-final.

Some questions

- The custom classloader in `SpockRunner` still delegates to `SpockRunner.class.getClassLoader()`, the app classloader. What is the purpose of `shadowTestClass`?
- `SpockRunner` asserts there are no bootstrap classes in test classes. Why do we need this check? Why do I feel this has never restricted me when writing tests? `AgentTestRunner`, inherited by the test classes, has a field of type `Tracer` which seems to work ok

And some findings

- Trying to add `SpockRunner` to `AgentSpecification` complains with the bootstrap class check, because tests have a field of type `Tracer`. I'm still not sure why this isn't allowed but it works ok for `AgentTestRunner`
- Trying to add `SpockRunner` to `AgentSpecification` and temporarily disable the bootstrap class check results in missing classes like `org.groovy.lang.Object`. Since the custom classloader created by `SpockRunner` delegates to the app classloader, not sure why this would happen

**Comment by trask** [comment]
@anuraaga ok to close this as resolved by #1643?
