### ISSUE TITLE
Send logs to stdout instead of stderr

### ISSUE THREAD

**Issue by sefaYavuz** [open-telemetry/opentelemetry-java-instrumentation#8318]
**Describe the bug**
I'm using the OpenTelemetry Operator and i'm trying to send the logs of the agent to stdout instead of stderr. Because our product runs on GCP, every log entry provided by the agent get's marked as an error. 

I've found that you could change this by setting this property: `-Dio.opentelemetry.javaagent.slf4j.simpleLogger.logFile=System.Out`

But this doesn't work.

**Steps to reproduce**

To the OpenTelemetryCollector CR I pass the env `JAVA_TOOL_OPTIONS` with the value `-Dio.opentelemetry.javaagent.slf4j.simpleLogger.logFile=System.Out`

```
manifest = {
    "apiVersion" = "opentelemetry.io/v1alpha1"
    "kind" = "OpenTelemetryCollector"
    "metadata" = {
      "name" = "default"
      "namespace" = "default"
    }
    "spec" = {
      "env" = [{
        name = "JAVA_TOOL_OPTIONS"
        value = "-Dio.opentelemetry.javaagent.slf4j.simpleLogger.defaultLogLevel=off"
      }]
      "mode" = "deployment"
      "serviceAccount" = "k8-sa"
      "config" = ""
  }
}
```

I'm using terraform to create this.

**What did you expect to see?**
Logs to appear as their level on GCP.

**What did you see instead?**
Logs in error severity in GCP.

<img width="834" alt="image" src="https://user-images.githubusercontent.com/7534379/233061605-926b9363-18b6-42dc-8354-8b4a01db07b1.png">

**What version are you using?**
open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.24.0

**Comment by laurit** [comment]
The logs on the screenshot are from opentelemetry collector not from the java agent. You are better off asking this question from the operator or collector folks, we can't help you.
