### ISSUE TITLE
Speed up SpockRunner.setupBootstrapClasspath

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#832]
I found that `setupBootstrapClasspath` in `SpockRunner` is quite slow and is what results in tests often having a large period at 0% before showing debug logs for instrumentation. It'd be nice if it's possible to speed this up. Perhaps there's a way for Gradle to prepare the bootstrap jar instead of doing it at runtime, which could benefit from up-to-date checks, etc.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/testing-common/src/main/groovy/io/opentelemetry/auto/test/SpockRunner.java#L166

**Comment by anuraaga** [comment]
I'm also somewhat scared to look at my temp directory since I realize it's probably full of bootstrap jars!

**Comment by iNikem** [comment]
@anuraaga haven't you fixed that already?
