### ISSUE TITLE
Change ota.propagators to ota.propagator (at least for now)

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#833]
As far as I understand, this property currently supports only a single one of: `tracecontext`, `b3`, `b3single`, `jaeger`.

This question was asked earlier about changing this property from list to single value:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/451#issuecomment-635350699

The answer given at the time was that while we are supporting just one propagator per "concern", there could be multiple "concerns".

But I think all 4 of the values that we support today are part of the same "concern" (distributed tracing), so really we only support a single value today.

If that's the case, I suggest we rename `ota.propagators` to `ota.propagator`, at least for now to avoid confusion (until that property really does support more than one value).

cc: @carlosalberto @malafeev in case I'm missing something about the current state of propagator support

EDIT: this issue inspired by #834

**Comment by FrankSpitulski** [comment]
Why not support multiple propagators? If you provide multiple to the builder it will use the multi propagator internally.

**Comment by trask** [comment]
@FrankSpitulski 👍 I just updated https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/637#issuecomment-666145318.

Closing this, and will see if we can get #637 in time for `0.7.0`.
