### ISSUE TITLE
Can we limit the length of the exception message and the length of the statement by default in DatabaseClientTracer?

### ISSUE THREAD

**Issue by dengliming** [open-telemetry/opentelemetry-java-instrumentation#835]
Production environments occasionally has long exception stack messages and statements, and it makes sense to limit their length by default, This will also reduce the memory footprint.

**Comment by iNikem** [comment]
@dengliming I think this is actually a duplicate of open-telemetry/opentelemetry-java#1478. Do you agree?

**Comment by dengliming** [comment]
yes. thx.
