### ISSUE TITLE
Auto instrumentation with Undertow has loop stitching issue in high concurrency scenario

### ISSUE THREAD

**Issue by yzhuang93** [open-telemetry/opentelemetry-java-instrumentation#8353]
**Describe the bug**
We recently bumped up our Java agent version from 1.6.2 to 1.25.0, and found a regression issue that when and only when the Undertow service is running with high concurrent requests, the server span of some traces is missing (Or suppressed), and the client spans from different requests mistakenly stitched to the same server span, and eventually generates a loop of spans.

Example:
The trace generated with Java agent **1.6.2**:
ServiceA Server Span (manual instrumentation)
======> ServiceA Client Span (manual instrumentation)
===============> ServiceB Server Span (auto instrumentation io.opentelemetry.undertow-1.4)
========================> ServiceB Client Span1 (auto instrumentation io.opentelemetry.http-url-connection)
========================> ServiceB Client Span2 (auto instrumentation io.opentelemetry.http-url-connection)

The trace generated with Java agent **1.7.0+**:
Trace with loop:
ServiceA Server Span (manual instrumentation)
======> ServiceA Client Span (manual instrumentation)
===============> ServiceB Server Span (auto instrumentation io.opentelemetry.undertow-1.4)
========================> ServiceB Client Span1 (auto instrumentation io.opentelemetry.http-url-connection)
========================> ServiceB Client Span2 (auto instrumentation io.opentelemetry.http-url-connection)
========================> ServiceB Client Span1 (auto instrumentation io.opentelemetry.http-url-connection)
========================> ServiceB Client Span2 (auto instrumentation io.opentelemetry.http-url-connection)
========================> ServiceB Client Span1 (auto instrumentation io.opentelemetry.http-url-connection)
========================> ServiceB Client Span2 (auto instrumentation io.opentelemetry.http-url-connection)
....

Trace without loop but missing all the ServiceB Spans:
ServiceA Server Span (manual instrumentation)
======> ServiceA Client Span (manual instrumentation)

**Steps to reproduce**
Run a service with Undertow and send requests with 100 RPS and 20 threads.

**What did you expect to see?**
All spans stitch correctly.

**What did you see instead?**
Some traces have loop span issue, and some traces miss some spans.

**What version are you using?**
We were using 1.6.2 and we dont observe this issue, after testing, this issue is introduced in 1.7.0+ version

**Environment**
Runtime (if different from JDK above): openjdk version "1.8.0_362"
OS (if different from OS compiled on): CentOS Linux 7

**Additional context**
Since we are pretty sure that this issue is only observed in 1.7.0+ version, we investigated the release note and the commits in opentelemetry java agent, found that remove this block of code seems can bypass the issue:[https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/ins[…]/javaagent/instrumentation/undertow/HandlerInstrumentation.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/undertow-1.4/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/undertow/HandlerInstrumentation.java#L66-L68)

And this was added in the commit: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4239/files

From a quick look into the code, this code is trying to suppress some spans, and in our case, looks like it suppressed the server span in some of the traces, and somehow caused the later-on client spans to mistakenly all stitched to the same server span context.

We are still trying to do some more investigation and see if we can provide an example repo to repro this issue (We tried but failed to repro), but just with the current information, a couple of questions here:
1. Is it possible that someone can provide us with some hints about what this issue could be caused? 
2. Is there any way to bypass this without changing the Java agent source code? 
3. If we remove this block of code, is there any penalty for the application?

Appreciate your help in advance.

**Comment by yzhuang93** [comment]
Also found an previous open issue that might relate to this: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4639

**Comment by yzhuang93** [comment]
Also one question here is that seems like the span suppressing is for the client span only (Maybe I am understanding this incorrectly), why do we also do it for the server span generation here: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4239/files#diff-6cbe0fc2f72799726ae2701f4f1aa99af837b8b6dfe4a6e4041834bf8f1b59b9R65-R70 ?

**Comment by laurit** [comment]
@yzhuang93 Could you provide a minimal application that reproduces the issue. Span suppression isn't the problem here, the problem is that the context from previous request has leaked over to the new request. We need to understand how that happens.

**Comment by yzhuang93** [comment]
@laurit thanks for responding, we are trying to provide one application that could reproduce the issue. 
I agree that span suppression might not be the root cause, but we are trying to make a workaround to bypass this issue temporarily, so my question is, if we just remove those lines of code for span suppression, is there any penalty besides redundant span generation? And why that client span suppression code is used for server span as well?

**Comment by laurit** [comment]
We use the same suppression code every time we create a span. Suppression isn't specific to client spans, server spans could also be created by multiple instrumentations and then the nested server span is suppressed.

**Comment by yzhuang93** [comment]
Thanks for clarifying, I was confused since the doc here https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#instrumentation-span-suppression-behavior was specifying the suppression is only for client span

**Comment by Jayrajgondaliya** [comment]
Created Repo to reproduce this issue 
Please refer : https://github.com/Jayrajgondaliya/loop-trace-debug-app

cc: @yzhuang93

**Comment by laurit** [comment]
@Jayrajgondaliya could you also provide instructions on how to configure envoy

**Comment by yzhuang93** [comment]
Need to clarify a little bit about this issue, after some more verification tests, we found that actually this is not related to the envoy routing, instead, it is possibly related to the HTTP client connect mechanism used by our gateway service with undertow, we will try to do more investigation and see if we can provide 2 apps to reproduce the issue.

**Comment by yzhuang93** [comment]
@laurit It is still tricky for us to provide the minimal setup for debugging since one of the components involved in this issue has many customized client codes and need some time to simplify into a small project.
Meanwhile, I did some more tests and investigation into this issue, before I found that by removing the span suppression code we don't see this issue, it is possible because that server span always gets generated then, even in a loop scenario, and it will always try to stitch to the context extracted from the upstream requests first, so it won't stitch to the leaking active span in the current scope.

So I did another test with the same Java agent jar without the span suppression for undertow instrumentation. Didn't pass any span context from the upstream this time and reproduced the issue. So I can see that server span for each request got generated and still stitched in a loop.

I attached the Trace JSON file and all the Java agent debug logs here, which has a stack trace of the context leaking issue.
[loop_trace.zip](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/11368840/loop_trace.zip)

```
[otel.javaagent 2023-05-01 20:11:06:233 +0000] [XNIO-2 task-12] ERROR io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug - Unexpected non-root current context found when extracting remote context!
[otel.javaagent 2023-05-01 20:11:06:233 +0000] [XNIO-2 task-12] ERROR io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug - It contains this span: SdkSpan{traceId=f1a18d1981cad0b7dfad5ba77e0aa182, spanId=178412b48194641c, parentSpanContext=ImmutableSpanContext{traceId=f1a18d1981cad0b7dfad5ba77e0aa182, spanId=2727f5e47b97c4ff, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, name=TestControllers.test1, kind=INTERNAL, attributes=AttributesMap{data={thread.id=47, thread.name=XNIO-2 task-12}, capacity=128, totalAddedValues=2}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1682971865231049956, endEpochNanos=1682971866233282623}
[otel.javaagent 2023-05-01 20:11:06:233 +0000] [XNIO-2 task-12] ERROR io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug - a context leak was detected. it was propagated from: 
carrier of type: io.undertow.server.protocol.http.HttpReadListener
    io.opentelemetry.javaagent.bootstrap.executors.ExecutorAdviceHelper.attachContextToTask(ExecutorAdviceHelper.java:66)
    java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1343)
    org.xnio.XnioWorker.execute(XnioWorker.java:749)
    io.undertow.server.protocol.http.HttpReadListener.exchangeComplete(HttpReadListener.java:364)
    io.undertow.server.protocol.http.HttpServerConnection.exchangeComplete(HttpServerConnection.java:232)
    io.undertow.server.HttpServerExchange$ExchangeCompleteNextListener.proceed(HttpServerExchange.java:1891)
    io.opentelemetry.javaagent.instrumentation.undertow.EndSpanListener.exchangeEvent(EndSpanListener.java:24)
    io.undertow.server.HttpServerExchange$ExchangeCompleteNextListener.proceed(HttpServerExchange.java:1889)
    io.undertow.server.handlers.accesslog.AccessLogHandler$AccessLogCompletionListener.exchangeEvent(AccessLogHandler.java:159)
    io.undertow.server.HttpServerExchange.invokeExchangeCompleteListeners(HttpServerExchange.java:1276)
    io.undertow.server.HttpServerExchange.terminateResponse(HttpServerExchange.java:1563)
    io.undertow.server.Connectors.terminateResponse(Connectors.java:159)
    io.undertow.server.protocol.http.ServerFixedLengthStreamSinkConduit.channelFinished(ServerFixedLengthStreamSinkConduit.java:58)
    io.undertow.conduits.AbstractFixedLengthStreamSinkConduit.exitFlush(AbstractFixedLengthStreamSinkConduit.java:316)
    io.undertow.conduits.AbstractFixedLengthStreamSinkConduit.flush(AbstractFixedLengthStreamSinkConduit.java:234)
    org.xnio.conduits.ConduitStreamSinkChannel.flush(ConduitStreamSinkChannel.java:162)
    io.undertow.channels.DetachableStreamSinkChannel.flush(DetachableStreamSinkChannel.java:119)
    org.xnio.channels.Channels.flushBlocking(Channels.java:63)
    io.undertow.servlet.spec.ServletOutputStreamImpl.flushInternal(ServletOutputStreamImpl.java:494)
    io.undertow.servlet.spec.ServletOutputStreamImpl.flush(ServletOutputStreamImpl.java:476)
    sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:297)
    sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:141)
    java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
    org.springframework.util.StreamUtils.copy(StreamUtils.java:147)
    org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:126)
    org.springframework.http.converter.StringHttpMessageConverter.writeInternal(StringHttpMessageConverter.java:44)
    org.springframework.http.converter.AbstractHttpMessageConverter.write(AbstractHttpMessageConverter.java:227)
    
```

**Comment by yzhuang93** [comment]
I do believe it will still cost us some time to provide a reproducible setup for you, so if possible, could you please also take a look at the above trace and log we captured to see if it can be some hint to find the root cause? I really appreciate your help in advance.
