### ISSUE TITLE
How to generate a otel Context/SpanContext based on a string like trace_id:span_id

### ISSUE THREAD

**Issue by wys199703** [open-telemetry/opentelemetry-java-instrumentation#8358]
I want to extract a otel Context/SpanContext from a String format like "trace_id:span_id". In the legacy jaegertracing implementation we can get it form io.jaegertracing.internal.propagation.TextMapCodec.contextFromString(String). So I wonder is there a similar way to do this in opentemeletry-java. I checked  opentelemetry-instrumentation-java has four propagators. Seems none to extract from a String. 
![image](https://user-images.githubusercontent.com/34131545/234247579-675de72e-69e8-4eb8-8ddf-d25d526d7f49.png)

Is there any way to do this ?

my maven opentelemetry dependencies are :

`<dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-jaeger-spring-boot-starter</artifactId>
                <version>1.25.0-alpha</version>
            </dependency>`

            `<dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-logback-mdc-1.0</artifactId>
                <version>1.25.0-alpha</version>
            </dependency>`

**Comment by wys199703** [comment]
@laurit   Yes, I checked that propagator extracts trace from header 'uber-trace-id'.
And does otel-java support to filter which requests with specefied expressions not to be traced?  Like skippattern definition in jaegertracing

**Comment by laurit** [comment]
@wys199703 it is possible to write a sampler for this, for example see https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/samplers/src/main/java/io/opentelemetry/contrib/sampler

**Comment by wys199703** [comment]
Hi @laurit,  Maybe there is something misunderstanding about my question. Actually my situation is I do not want to generate a otel context for some specefied http paths like '/actuator/*' but not in the export stage. I've read the code of 'WebMvcTelemetryProducingFilter' and does that can be done in this filter‘s judgement statement 'this.instrumenter.shouldStart(parentContext, request)'  by adding the path pattern match judgement？ 
![image](https://user-images.githubusercontent.com/34131545/236397752-63240761-63ad-4050-bdca-4a0177ee4fd5.png)

**Comment by wys199703** [comment]
Hi @trask  I checked that issue. Maybe it met my issue. Actually I'm using otel-instrumentation by a otel springboot starter. So I need to replace the default sampler with a self managed 'RuleBasedRoutingSampler'. is that correct? 

And another question is I also use otel 'opentelemetry-logback-mdc-1.0' to auto inject trace_id & span_id to my log line. For my understanding is all requests which return true in below judgement 'this.instrumenter.shouldStart(parentContext, request)' will generate trace context in the 'WebMvcTelemetryProducingFilter' and inject the trace info to log line, even through whose  trace will not export to the backend. Is that correct?
![image](https://user-images.githubusercontent.com/34131545/236681848-84fdd0f3-70da-421c-8533-0609f554207d.png)

BTW. I want to confirm does otel can also propagate from a 64 bits trace id by padding zero to the hex high 16~31 like below example ?
`SpanContext.createFromRemoteParent( 
                 "00000000000000000000000000000001", 
                 "0000000000000002", 
                 TraceFlags.getSampled(), 
                 TraceState.getDefault())))`
