### ISSUE TITLE
OkHttpExporter: Unable to find acceptable protocols

### ISSUE THREAD

**Issue by aolear** [open-telemetry/opentelemetry-java-instrumentation#8371]
**Describe the bug**
When attempting to instrument a Java 8 application hosted on IBM WebSphere 8.5.5, we receive the following error when attempting to configure an endpoint for the OTEL exporter that is HTTPS:

```
[otel.javaagent 2023-04-26 17:05:40:585 -0400] [OkHttp https://collectorurl.com/...] ERROR io.opentelemetry.exporter.internal.okhttp.OkHttpExporter - Failed to export logs. 
The request could not be executed. Full error message: Unable to find acceptable protocols. isFallback=false, modes=[ConnectionSpec(cipherSuites=[TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA],
tlsVersions=[TLS_1_3, TLS_1_2], supportsTlsExtensions=true), ConnectionSpec()], supported protocols=[TLSv1]
```

The javaagent and OTEL settings are being set as environment variables for the websphere application server, which is running on a development machine in a docker container:
```
      - JAVA_TOOL_OPTIONS="-javaagent:/opt/opentelemetry-javaagent.jar"
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://collectorurl.com
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
```

When using a non-TLS endpoint, logs are sent as expected to the non-TLS endpoint. 

I have tried several variations of setting the default TLS version to 1.2 through JVM arguments, with no luck. I understand this may not be a bug w/ the agent itself, but I would appreciate any insight!

**Steps to reproduce**
Configure an https URL for the OTEL Exporter for a Java 8 WebSphere application

**What did you expect to see?**
The opentelemetry agent is able to communicate over HTTPS to the configured endpoint or the agent provides settings to set the TLS version to use for communication.

**What did you see instead?**
OkHttp appears to be attempting to use TLSv1 to call an endpoint that does not support it. Either that or OkHttp will only use TLSv1.2 or TLSv1.3, but cannot because the runtime environment is defaulting to TLSv1 only

**What version are you using?**
[otel.javaagent 2023-04-26 17:05:29:282 -0400] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.24.0

**Environment**
Compiler of application:
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

OS:
Based on this websphere docker image: https://hub.docker.com/r/ibmcom/websphere-traditional/
version 8.5.5 (unsure which tag)

**Comment by laurit** [comment]
As far as I understand this message tells that okhttp wants to use `TLS_1_3` or `TLS_1_2` but jvm only provides `TLSv1`. Documentation at https://www.ibm.com/support/pages/how-do-i-change-default-ssltls-protocol-my-java%E2%84%A2-application-will-use hints that TLSv1.3 & TLSv1.2 should be enabled on ibm java 8. Perhaps you have disabled these yourself? Check your jvm arguments. You can check what tls versions are supported with
```java
import java.util.Arrays;
import javax.net.ssl.SSLSocket;
import javax.net.ssl.SSLSocketFactory;

public class Main {
    public static void main(String[] args) throws Exception {
        String host = "google.com";
        Integer port = 443;
        SSLSocketFactory sslsocketfactory = (SSLSocketFactory) SSLSocketFactory.getDefault();
        SSLSocket sslsocket = (SSLSocket) sslsocketfactory.createSocket(host, port);
        System.err.println(Arrays.asList(sslsocket.getEnabledProtocols()));
    }
}
```
You could run it with the same vm that is used to run websphere and see what it prints out.
