### ISSUE TITLE
Add trace information in responses.

### ISSUE THREAD

**Issue by lurbanski-equinix** [open-telemetry/opentelemetry-java-instrumentation#8421]
Hi guys,

Is your feature request related to a problem? Please describe.
When I receive request/response from client. I don't see trace-id header in http response. With that debugging a problem would be a lot faster.
I think it refers to all kind of responses. e.g. grpc, http etc

Describe the solution you'd like
I would gladly see "trace-id" in responses e.g. as http header etc.

Best,
Łukasz

**Comment by laurit** [comment]
For http servers we provide https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/bootstrap/http/HttpServerResponseCustomizer.java that can be used to add headers to the http response. For example see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/testing/agent-exporter/src/main/java/io/opentelemetry/javaagent/testing/http/TestAgentHttpResponseCustomizer.java that we use in tests. You can use this SPI in an agent extension https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension
