### ISSUE TITLE
Spans submitted to the same trace ID when using Flux.retryWhen

### ISSUE THREAD

**Issue by livmackintosh** [open-telemetry/opentelemetry-java-instrumentation#8432]
**Describe the bug**

Spans are submitted the same trace ID. The only thing that has changed has been upgrading from 1.19.0 (Honeycomb 1.4.0) to 1.25.0 (Honeycomb 1.5.0).[

When I first reported this bug I had thought that enabling the add-baggage flag `-Dotel.instrumentation.logback-mdc.add-baggage=true` was causing this problem however I have bisected the change and simply changing to 1.25.0 of the agent is causing the problem.

**Steps to reproduce**
* Update from v.1.19.0 to v.1.25.0
~* Add the flag `-Dotel.instrumentation.logback-mdc.add-baggage=true`~

**What did you expect to see?**
A normal number of spans per trace within a root span

**What did you see instead?**
Hundreds of thousands of spans and no root trace detected

**What version are you using?**
v1.25.0

**Environment**
Compiler: Eclipse Temurin JDK 17
OS: Ubuntu 22.04
~Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")~
OS Alpine 3.17

**Additional context**
We are using the Honeycomb distribution (v1.5.0) which is a thin wrapper around the OTel agent providing easy configuration for their cloud platform.

We are using auto-instrumentation

We are using `-Dotel.instrumentation.kafka.experimental-span-attributes=true`

**Comment by livmackintosh** [comment]
Bisected our changes and can confirm that the upgrade from 1.19.0 to 1.21.0 alone was the culprit.

**Comment by livmackintosh** [comment]
Now, I'm not sure if there are some breaking changes that we are not aware of... that's the current line of investigation to try to refine this further.

**Comment by mateuszrzeszutek** [comment]
Can you say a bit more about the trace itself? It is leaking HTTP server spans? Or some background job ones? What related frameworks/libraries are you using?

**Comment by livmackintosh** [comment]
We're using Spring framework as our HTTP gateway but behind that we have Micronaut microservices however the span leaks seem to be occuring at many points in the stack but primarily within Spring. At the service level but also futher down in ReadOperationHandler.

**Comment by livmackintosh** [comment]
```
    val kotlinVersion = "1.8.21"
    kotlin("jvm") version kotlinVersion apply false
    kotlin("kapt") version kotlinVersion apply false
    kotlin("plugin.allopen") version kotlinVersion apply false
    kotlin("plugin.spring") version kotlinVersion apply false
    kotlin("plugin.serialization") version kotlinVersion apply false
    id("com.diffplug.spotless") version "6.18.0" apply true
    id("com.google.protobuf") version "0.9.3" apply false
    id("io.micronaut.application") version "3.7.9" apply false
    id("com.github.johnrengelman.shadow") version "7.1.2" apply false
    id("com.github.imflog.kafka-schema-registry-gradle-plugin") version "1.11.0" apply false
    id("org.springframework.boot") version "2.7.5" apply false
    id("io.spring.dependency-management") version "1.1.0" apply false
    id("io.gatling.gradle") version "3.9.2" apply false
    id("org.openapi.generator") version "6.5.0" apply false
    jacoco
```

**Comment by livmackintosh** [comment]
```
    implementation(group = "org.springframework.boot", name = "spring-boot-starter-webflux")
    implementation(group = "org.springframework.boot", name = "spring-boot-starter-actuator")
    implementation(group = "org.springframework.boot", name = "spring-boot-starter-validation")
    implementation(group = "org.jetbrains.kotlin", name = "kotlin-reflect")
    implementation(group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8")
    implementation(group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version = coroutinesVersion)
    implementation(platform("io.arrow-kt:arrow-stack:$arrowVersion"))
    implementation("io.arrow-kt:arrow-core")
    implementation("io.arrow-kt:arrow-fx-stm")
    implementation("io.arrow-kt:arrow-fx-coroutines")
    implementation(group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version = jacksonVersion)
    implementation("io.honeycomb:honeycomb-opentelemetry-sdk:$honeycombVersion")
    compileOnly("io.honeycomb:honeycomb-opentelemetry-javaagent:$honeycombVersion")
    implementation("io.grpc:grpc-netty-shaded:$grpcVersion")
    implementation("com.google.protobuf:protobuf-java-util:$protoVersion")
    implementation(group = "io.fabric8", name = "kubernetes-client", version = k8sClientVersion) // <- k8s client for using grpc endpoints watching
    runtimeOnly(group = "net.logstash.logback", name = "logstash-logback-encoder", version = logstashLogbackEncoder)
    testImplementation(group = "org.springframework.boot", name = "spring-boot-starter-test")
    testImplementation(group = "org.hamcrest", name = "hamcrest-all", version = hamcrestVersion)
    testImplementation(group = "org.mockito", name = "mockito-core", version = mockitoVersion)
    testImplementation(group = "org.mockito.kotlin", name = "mockito-kotlin", version = mockitoKotlinVersion)
    testImplementation(group = "org.mockito", name = "mockito-inline", version = mockitoInlineVersion)
    testImplementation(group = "io.cucumber", name = "cucumber-java", version = cucumberVersion)
    testImplementation(group = "io.cucumber", name = "cucumber-junit", version = cucumberVersion)
    testImplementation(group = "io.cucumber", name = "cucumber-spring", version = cucumberVersion)
    testRuntimeOnly(group = "org.junit.vintage", name = "junit-vintage-engine", version = junitVersion.toString())
```

**Comment by livmackintosh** [comment]
Potentially a dupe of interest https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8125

**Comment by laurit** [comment]
@livmackintosh If you believe that what you are seeing is a bug and desire a fix for it then you need to either provide a minimal application that reproduces your issue or describe your issue in sufficient detail to allow others to reproduce it. This far the only details included are that you are seeing a lot of spans in one trace and that you are using spring, which is not enough to even guess where the issue might lie.

**Comment by livmackintosh** [comment]
@laurit Completely understand. I'm providing as much information as I can given time constraints and knowledge of our stack. Started last month at a new company so lots of moving parts and not familiar with Otel internals which a rather complicated or at least not simple. Bear with me and I will follow with more information and potentially a PR ;)

**Comment by livmackintosh** [comment]
Probably also related: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8454

**Comment by livmackintosh** [comment]
I'm going to test against 09b63d22944c86d8511658f0730cbbc7087ed0b2 as well as the parent comment. If this commit introduces the problem I will close this issue and consider #8125 to trump this. The reporter of this issue kindly added a repro so it may be more helpful. I can dig further into the root cause and either make a fix or test any related PRs.
