### ISSUE TITLE
improve the documentation regarding R2dbc integration for Spring Boot projects

### ISSUE THREAD

**Issue by 62mkv** [open-telemetry/opentelemetry-java-instrumentation#8438]
**Describe the bug**

Currently, suggested way to initialize the listener for Spring applications does not seem to work - `ConnectionFactoryInitializer` does not do anything with a `ConnectionFactory`. So, what the suggested sample [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/r2dbc-1.0/library#usage) does is just creating a Proxy and "dropping it". Its listeners are never activated.

**Steps to reproduce**

Build a simple Spring Boot-based application with Spring Data R2DBC and follow the documentation

**What did you expect to see?**
This configuration worked for me: 

```
@Configuration
public class TracingConfiguration {

    @Bean
    ConnectionFactory connectionFactory(R2dbcProperties properties) {
        var openTelemetry = GlobalOpenTelemetry.get();
        var factoryOptions = ConnectionFactoryOptions.parse(properties.getUrl())
                                                     .mutate()
                                                     .option(ConnectionFactoryOptions.USER, properties.getUsername())
                                                     .option(ConnectionFactoryOptions.PASSWORD, properties.getPassword())
                                                     .build();

        return wrapWithProxyFactory(openTelemetry, ConnectionFactories.get(factoryOptions), factoryOptions);
    }

    private ConnectionFactory wrapWithProxyFactory(OpenTelemetry openTelemetry, ConnectionFactory originalFactory, ConnectionFactoryOptions factoryOptions) {
        return R2dbcTelemetry
                   .create(openTelemetry)
                   .wrapConnectionFactory(originalFactory, factoryOptions);
    }
}
```

**What did you see instead?**

No traces were collected because the provided configuration was just ignored

**What version are you using?**

OTel 1.24.0; 
io.opentelemetry.instrumentation:opentelemetry-r2dbc-1.0:1.25.0-alpha 

**Environment**

**Additional context**

**Comment by mateuszrzeszutek** [comment]
Hey @62mkv ,

Can you try the following snipper instead?

```java
@Configuration
class R2dbcConfiguration {

  @Bean
  public R2dbcInstrumentingPostProcessor r2dbcInstrumentingPostProcessor(
      OpenTelemetry openTelemetry,
      ConnectionFactoryOptions options) {
    return new R2dbcInstrumentingPostProcessor(openTelemetry, options);
  }
}

class R2dbcInstrumentingPostProcessor implements BeanPostProcessor {

  private final OpenTelemetry openTelemetry;
  private final ConnectionFactoryOptions options;

  R2dbcInstrumentingPostProcessor(OpenTelemetry openTelemetry, ConnectionFactoryOptions options) {
    this.openTelemetry = openTelemetry;
    this.options = options;
  }

  @Override
  public Object postProcessAfterInitialization(Object bean, String beanName) {
    if (!(bean instanceof ConnectionFactory)) {
      return bean;
    }

    ConnectionFactory connectionFactory = (ConnectionFactory) bean;
    return R2dbcTelemetry.create(openTelemetry).wrapConnectionFactory(connectionFactory, options);
  }
}
```

Using a `BeanPostProcessor` is a bit less invasive, as it does not force the user to construct the `ConnectionFactoryOptions` from scratch.

**Comment by 62mkv** [comment]
thanks @mateuszrzeszutek ! I will give it a try; this seems to be more idiomatic indeed. But what about updating the README, the suggested snippet is clearly not working?

**Comment by 62mkv** [comment]
and this issue is Closed :(

**Comment by mateuszrzeszutek** [comment]
Oof, looks like Spring Boot does not actually publish the `ConnectionFactoryOptions` as a bean.

@62mkv can you try the following code?
```java
@Configuration
class R2dbcConfiguration {

  @Bean
  public R2dbcInstrumentingPostProcessor r2dbcInstrumentingPostProcessor(
      OpenTelemetry openTelemetry) {
    return new R2dbcInstrumentingPostProcessor(openTelemetry);
  }
}

class R2dbcInstrumentingPostProcessor implements BeanPostProcessor {

  private final OpenTelemetry openTelemetry;

  R2dbcInstrumentingPostProcessor(OpenTelemetry openTelemetry) {
    this.openTelemetry = openTelemetry;
  }

  @Override
  public Object postProcessAfterInitialization(Object bean, String beanName) {
    if (!(bean instanceof ConnectionFactory)) {
      return bean;
    }
    ConnectionFactory connectionFactory = (ConnectionFactory) bean;
    return R2dbcTelemetry.create(openTelemetry)
        .wrapConnectionFactory(connectionFactory, getConnectionFactoryOptions(connectionFactory));
  }

  private static ConnectionFactoryOptions getConnectionFactoryOptions(ConnectionFactory connectionFactory) {
    OptionsCapableConnectionFactory optionsCapableConnectionFactory =
        OptionsCapableConnectionFactory.unwrapFrom(connectionFactory);
    if (optionsCapableConnectionFactory != null) {
      return optionsCapableConnectionFactory.getOptions();
    } else {
      // in practice should never happen
      // fall back to empty options; or reconstruct them from the R2dbcProperties
      return ConnectionFactoryOptions.builder().build();
    }
  }
}
```

**Comment by 62mkv** [comment]
Hi @mateuszrzeszutek this last snippet seems to work well enough! 

One tiny question though: how does one get this `OpenTelemetry` bean defined? Is there a particular SB starter module with auto-configuration? I only seem to be getting instance of `OpenTelemetry` via `GlobalTelemetry.get()` static call; otherwise I have this 

> Parameter 0 of method r2dbcInstrumentingPostProcessor in com.example.opentelemetryr2dbcspringboot.tracing.TracingConfiguration required a bean of type 'io.opentelemetry.api.OpenTelemetry' that could not be found.

**Comment by mateuszrzeszutek** [comment]
> One tiny question though: how does one get this `OpenTelemetry` bean defined? Is there a particular SB starter module with auto-configuration? I only seem to be getting instance of `OpenTelemetry` via `GlobalTelemetry.get()` static call; otherwise I have this

Ohh, good point. By default, it does not get defined at all anywhere (which is why it only worked when you used the global).

Our own spring starter (`opentelemetry-spring-boot-starter`) defines it; I suspect the Spring Sleuth OTel module also defines it somewhere if you're using that.

Anyway, thanks for testing all of that! I'll update our docs.
