### ISSUE TITLE
Library instrumentation experience confusing because of SDK dependency requirement?

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#846]
Just want to throw this out there, I wonder if the requirement that instrumentation only depends on the OTel API and not SDK is too surprising to users. If someone depends on `opentelemetry-instrumentation-grpc-1.5`, it seems natural to expect there to be actual instrumentation happening but it'd be no-op without also adding `opentelemetry-sdk`. At the very least, I haven't checked yet, but we might not even have a scary log message for this case.

**Comment by trask** [comment]
I think that without the user adding an exporter (which would then bring in `opentelemetry-sdk`), nothing (much) is going to happen even with `opentelemetry-sdk`

**Comment by iNikem** [comment]
@anuraaga This task looks like it should have `discussion` label, shouldn't it?

**Comment by trask** [comment]
hey @anuraaga do you have additional thoughts about this?

@mabdinur asked about this too: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/878#discussion_r464546751

**Comment by anuraaga** [comment]
Yeah it's true that if adding the exporter, it's not a huge step to also add the SDK so I guess it's ok as-is.

For @mabdinur I think we do have to decide for the spring boot starters - spring boot starters are usually more self-contained and I think it'd be idiomatic to have both SDK and OTLP exporter included for batteries included.

**Comment by trask** [comment]
Does adding an exporter pull in the sdk transitively?

**Comment by iNikem** [comment]
As it was conscious decision from Otel to clearly separate API vs SDK, I think we should continue doing so. Which means that user has to opt-in into actually collecting monitoring data. Even if some of their libraries are instrumented. This opt-in happens either by adding SDK to _application_ dependencies or by installing java agent.

Thus I think our library instrumentations should not depend on SDK.

**Comment by anuraaga** [comment]
Yeah I think we can close this since adding the exporter will generally be enough!
