### ISSUE TITLE
The "spring-boot-autoconfigure" module should provide configuration metadata

### ISSUE THREAD

**Issue by zoobert** [open-telemetry/opentelemetry-java-instrumentation#8474]
Spring provides an annotation processor that can generate a `spring-configuration-metadata.json`. This descriptive file contains the necessary information for interaction with the configuration properties that IDEs can leverage to provide autocompletion and other configuration hints.

This file can automatically be generated by the `spring-boot-configuration-processor` during the build process. It serves a different purpose than the existing `spring-boot-autoconfigure-processor`, but is just as helpful.

Adding the following line to the `build.gradle.kts` should generate the file that can be distributed with the library. This file is generated for official spring boot dependencies. 

```
  annotationProcessor("org.springframework.boot:spring-boot-configuration-processor:$springBootVersion")
```

**Comment by trask** [comment]
hi @zoobert! this sounds like a nice addition, are you interested to contribute it?

**Comment by trask** [comment]
great! I linked them
