### ISSUE TITLE
jaeger does not correctly show the query time to a db

### ISSUE THREAD

**Issue by brianmolinaspring** [open-telemetry/opentelemetry-java-instrumentation#8482]
hello friends, my question is to see if you can help me, I am currently configuring a microservice in my java project that goes against an oracle bd, but I am seeing that it does not mark the time that the query takes in the trace that is shown in jaeger, the database takes approximately 8 seconds to respond and I want those 8 seconds to be shown by jaeger for what JDBC openTelemetry is, but this sample is 1 second, I followed this documentation: https://es.quarkus.io/guides/opentelemetry

I attach the print of the jaeger, in itself the ms marks the 8 seconds that encompasses everything, but in the trace of the bd those 8 seconds that I need to see do not appear.

![jaeger error](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/100229126/d249ed44-c253-418c-90f8-c455759874be)

**Comment by laurit** [comment]
Jdbc instrumentation measures the time for the `execute...` method. If your method returns a cursor then iterating it is not included in the execution time. You can easily verify this by adding timing code to your method and seeing where the time is consumed.

**Comment by brianmolinaspring** [comment]
@laurit  Good morning, thank you for answering, in fact we are consulting a stored procedure and it returns a course and the DB is the one that handles it, it takes time to iterate those times, I thought that Jaeger could measure this time, tell me is it possible or does it only work if I do a direct query ?

**Comment by laurit** [comment]
Currently instrumentation measures only the time it takes to run the `execute/executeQuery/executeUpdate` method. It does not measure the time it takes to iterate the `ResultSet`. If you need this then you can use the manual instrumentation api to create the span that suites your needs.

**Comment by brianmolinaspring** [comment]
@laurit do you have any example ?

**Comment by laurit** [comment]
```java
    Tracer tracer = GlobalOpenTelemetry.get().getTracer("test-tracer");
    Span span = tracer.spanBuilder("test").startSpan();
    try (Scope ignore = span.makeCurrent()) {
      // your code goes here
    } finally {
      span.end();
    }
```
Also see https://opentelemetry.io/docs/instrumentation/java/manual/#create-spans Note that as you are using the agent you should not construct the `OpenTelemetry` instance yourself, but rather use `GlobalOpenTelemetry.get()`

**Comment by brianmolinaspring** [comment]
Excelent @laurit thanks for helpme, the bug is fixed
