### ISSUE TITLE
WebClient/Netty instrumentation produces broken traces on Kubernetes

### ISSUE THREAD

**Issue by rajankamdi0706** [open-telemetry/opentelemetry-java-instrumentation#8513]
**Describe the bug**
We have two Java services running on Kubernetes. Service A calls Service B using WebClient. [Webflux version 5.3.1]. Both are using open telemetry agent version 1.25.0. We observed that the trace id is broken when a WebClient call is made to Service B.
Whereas when we tested local java microservice running without Kubernetes container trace id is propagated.
When used rest-template trace-id is propagated with/without Kubernetes. Looks like it's a problem with Weblcient in Kubernetes container.

**Steps to reproduce**
1) Have two Java microservice running in a Kubernetes container. Service A using WebClient call to Service B. Webflux version - [Webflux version 5.3.1]
2) Use the Opentelemetry version 1.25.0
3) Invoke Service B from Service A using WebClient.
4) Trace id generated by open telemetry agent is broken. [Not matching in both the service]

**What did you expect to see?**
Trace id should be propagated from Service A to Service B [both services running in different Kubernetes containers] when making call using WebClient. It should behave similar to rest-template call.

**What did you see instead?**
Different trace IDs in both services.

**What version are you using?**
Opentelemetry 1.25.0

**Environment**
AdoptOpenJDK 11.0.6

**Additional context**

**Comment by laurit** [comment]
@rajankamdi0706 please provide a minimal sample application that reproduces your issue. If complex software such as kubernetes is required to reproduce do not assume that the person who will attempt to repro this know how to use it.

**Comment by rajankamdi0706** [comment]
Should be able to share the code by today/tomorrow EOD. Interim sharing similar bug raised by someone earlier 
https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/2229

**Comment by rajankamdi0706** [comment]
I am working on sharing the code but it might take a while. Interim sharing the agent logs which are generated when a web client call is made from service 1 to service 2. 
[otel.javaagent 2023-05-19 11:24:52:106 +0530] [reactor-http-nio-4] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'GET' : **15fff68c85644378375bccb3e0a75ac6** 36ab9941b509b3c5 CLIENT [tracer: io.opentelemetry.spring-webflux-5.3:1.25.0-alpha] AttributesMap{data={http.url=<Endpoint>, http.status_code=200, thread.name=http-nio-8081-exec-1, http.method=GET, thread.id=27, net.peer.name=<service_host_name>, net.transport=ip_tcp}, capacity=128, totalAddedValues=7}
[otel.javaagent 2023-05-19 11:24:52:210 +0530] [reactor-http-nio-4] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - 'GET' : **991ef098b6d100ebd251ba7ba0ee5a44** 667654df53737c20 CLIENT [tracer: io.opentelemetry.netty-4.1:1.25.0-alpha] AttributesMap{data={net.protocol.name=http, http.url=<Endpoint>, http.status_code=200, net.protocol.version=1.1, thread.name=reactor-http-nio-4, http.method=GET, net.sock.peer.port=443, user_agent.original=ReactorNetty/0.8.5.RELEASE, thread.id=46, net.peer.name=<service_host_name>, net.transport=ip_tcp, net.sock.peer.addr=10.7.16.1}, capacity=128, totalAddedValues=12}
