### ISSUE TITLE
gradle reload error

### ISSUE THREAD

**Issue by aholeye** [open-telemetry/opentelemetry-java-instrumentation#8538]
**Describe the bug**
No matching variant of com.diffplug.spotless:spotless-plugin-gradle:6.18.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.1.1' but:

**Steps to reproduce**
git clone this repo and open the directory with idea, and then reload gradle project

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version are you using?**
master

**Environment**
Compiler: azul-17 17.0.5
OS: macOS Ventura 13.2
Runtime (if different from JDK above): azul-17 17.0.5
OS (if different from OS compiled on): macOS Ventura 13.2

**Additional context**

**Comment by laurit** [comment]
This could happen when you have configured Idea to run gradle with java 8. Check settings -> build, execution, deployment -> build tools -> gradle under gradle projects find opentelemetry-java-instrumentation and verify that gradle jvm is set to jdk 17.

**Comment by aholeye** [comment]
Indeed, that's the case. Thank you for taking the time to reply regarding this matter.
