### ISSUE TITLE
grpc reflection call will be suppressed when otel.instrumentation.experimental.span-suppression-strategy is semconv default

### ISSUE THREAD

**Issue by domyway** [open-telemetry/opentelemetry-java-instrumentation#8587]
**Describe the bug**
when the project code use grpc reflection : ClientCalls.blockingUnaryCall(channel, methodDescriptor, callOptions, requestMessage) ,  the real call span will be suppresed in agent 1.23.0 , and be called server side can`t get the traceparent in grpc md. 

it works well in 1.11.1 .
it fails after upgrade the agent to 1.23.0. but if 1.23.0 otel.instrumentation.experimental.span-suppression-strategy is none , it also works well.

**Steps to reproduce**

**What did you expect to see?**
grpc real call span should be sampled if suppression-strategy is semconv default . 

**What did you see instead?**
change otel.instrumentation.experimental.span-suppression-strategy to none for now.

**What version are you using?**
agent 1.23.0

**Environment**
Ubuntu
java 8.0

**Additional context**
None

**Comment by laurit** [comment]
@domyway could you provide a minimal application that reproduces this issue.
