### ISSUE TITLE
Jaeger remote sampling not working as expected for Operation Strategy

### ISSUE THREAD

**Issue by sakthiraam** [open-telemetry/opentelemetry-java-instrumentation#8589]
**Describe the bug**
I'm using Jaeger Remote sampling to do sampling at the agent level. The **default strategy and service level strategy is working as expected** but when I set up Operation Strategy it's not working as expected.

When I set specific endpoints to probabilistic sampling with a value of 0 I still see the traces in our backend.  I found a similar issue which got fixed but in our environment, it's not working.

[https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/5899](url)

So we tried with 0.1, 0.2 and hit multiple requests against the endpoint but only the default strategy is applied.

Note: We waited for our strategy file to reload and verified using grpccurl if the latest strategy is available. We also restarted our application to make sure the latest strategy is available. We enabled Otel debug logs and verified if the remote sampling endpoint is polled.

**Steps to reproduce**
Set up an Otel collector with Jaeger remote sampler extension enabled. Pass the strategy.json available in the below link as a file
[https://www.jaegertracing.io/docs/1.45/sampling/#file-based-sampling-configuration](url)

**What did you expect to see?**
/health & /metrics endpoints are not sampled

**What did you see instead?**
We still see those endpoints in our tracing backed.

**What version are you using?**
v1.24.0

**Environment**
OS:  RHEL 8
Runtime (if different from JDK above): JRE 17
OS (if different from OS compiled on):  RHEL 8 (UBI 8 Image)

**Comment by mateuszrzeszutek** [comment]
Hey @sakthiraam ,

We've changed the HTTP span naming pattern to match the current OTel HTTP semantic convention in version [1.23.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.23.0) of the javaagent, see the excerpt from the release notes:
> HTTP span names are now "{http.method} {http.route}" instead of just "{http.route}", reflecting the recent change in the HTTP semantic conventions

Can you try using `GET /health` and `GET /metrics` in your jaeger sampler config?

**Comment by sakthiraam** [comment]
Hi @mateuszrzeszutek, Thanks a lot for your response. I tried the approach you stated, sorry, but it didn't work. We can still see the traces and we can verify it in our back-end. Waited for the collector to reload the strategy file and even restarted my application to make sure it has the latest.
We are trying to setup a remote-debugger and test. Will post updates if any.

Our OTEL configuration

otel.traces.sampler=jaeger_remote
otel.traces.sampler.arg=endpoint=https://<OTEL-Jaeger-Endpoint>,pollingInmtervalMs=60000,initialSamplingRate=1.0

OTEL Debug logs 

**OTEL-Jaeger-Endpoint is listening on jaeger_grpc port - Configured as a pass-through route with TLS termination happening at pod level**

[OkHttp OTEL-Jaeger-Endpoint] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10004 scheduled after   0 µs: OkHttp OTEL-Jaeger-Endpoint applyAndAckSettings
[OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10004 starting              : OkHttp OTEL-Jaeger-Endpoint applyAndAckSettings
[OkHttp OTEL-Jaeger-Endpoint applyAndAckSettings] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10006 scheduled after   0 µs: OkHttp OTEL-Jaeger-Endpoint onSettings
[OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10006 starting              : OkHttp OTEL-Jaeger-Endpoint onSettings
[OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10004 finished run in   2 ms: OkHttp OTEL-Jaeger-Endpoint applyAndAckSettings
[OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10006 finished run in 308 µs: OkHttp OTEL-Jaeger-Endpoint onSettings
[OkHttp OTEL-Jaeger-Endpoint] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10004 scheduled after   0 µs: OkHttp OTEL-Jaeger-Endpoint ping
[OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10004 starting              : OkHttp OTEL-Jaeger-Endpoint ping
[OkHttp TaskRunner] DEBUG okhttp3.internal.concurrent.TaskRunner - Q10004 finished run in 542 µs: OkHttp OTEL-Jaeger-Endpoint ping


Do let us know if you want me to try with any other changes.

`{
  "default_strategy": {
    "type": "probabilistic",
    "param": 0.5,
    "operation_strategies": [
      {
        "operation": "GET /health",
        "type": "probabilistic",
        "param": 0.0
      },
      {
        "operation": "GET /metrics",
        "type": "probabilistic",
        "param": 0.0
      }
    ]
  }
}`

**Comment by laurit** [comment]
Using span name in a sampler doesn't always work as expected because the sampling decision is made when the span is started but the final name of a `SERVER` span is often set later when the route becomes available. For example if you are using tomcat then the initial span name is the http method name, so `GET` and `POST` etc are the only things you could use in a span name based sampler.

**Comment by sakthiraam** [comment]
Hi @laurit , Thanks for your reply. So the options available for us is to do server side sampling at OTEL collector end using processors such as tail sampling processor. Is that correct ?.

Most of the services are based on spring-boot so by right the sampling is not working based on your tomcat example.

Did a testing using remote debugger and can see the traceidratio is set to 0.0 correctly for those endpoints we are interested so the SDK extension is doing its job correctly.

And we can use Jaeger remote sampling only for service based sampling. Is my understanding correct ?
