### ISSUE TITLE
The Name of Netty Span is meaningless and not helpful for analysis

### ISSUE THREAD

**Issue by qiansheng91** [open-telemetry/opentelemetry-java-instrumentation#8613]
**Describe the bug**
The name of Netty span is `GET` and the name is meaningless and not helpful for analysis ，I think that the Name of Netty Span should be `GET /hello`

**Steps to reproduce**
https://github.com/qiansheng91/span-not-end-demo

**What did you expect to see?**
The Name of Span `746768c4dcdea939 ` should be `GET /hello`

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version are you using?**
1.26.0

**Comment by laurit** [comment]
@qiansheng91 For span names we follow guidelines given in specification https://github.com/open-telemetry/semantic-conventions/blob/main/specification/trace/semantic_conventions/http.md#name As a low level framework netty doesn't have a concept of a "route", but often times the higher level framework that is build on top of netty has. If you are interested in improving the server spans for spring cloud gateway then you'd be better of asking for improving span names for spring cloud gateway than netty. Perhaps one could use the path from https://github.com/qiansheng91/span-not-end-demo/blob/89be6e39ef6bb22c698990a9f805af823ed23088/springboot-gateway/src/main/resources/application.yml#L9 to get a better span name. You could also use something like https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/c888c085ec628466ea21db949f568825a1ca659e/instrumentation/jsf/jsf-jakarta-common/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/jsf/jakarta/JsfServerSpanNaming.java#L19-L34 to set the span name to whatever you like.

**Comment by qiansheng91** [comment]
OK, Thanks for your response, Does this mean that one needs to write a plugin about Spring Gateway to rewrite the Span Name?

**Comment by qiansheng91** [comment]
OK, I'll try to write the plugin, Thanks @laurit
