### ISSUE TITLE
OverheadTests not working

### ISSUE THREAD

**Issue by Groenig20** [open-telemetry/opentelemetry-java-instrumentation#8627]
**Describe the bug**
Unfortnalty, the benchmark-overhead test cant be executed.

**Steps to reproduce**
Run OverHeadTests in benchmark-overhead or use the './gradlew test' command

**What did you expect to see?**
The successful execution of the benchmark

**What did you see instead?**
See attached logfile.
[Test Results - OverheadTests.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/11619444/Test.Results.-.OverheadTests.txt)

**What version are you using?**
Current master state

**Environment**
Compiler: Oracle OpenJDK version 19.0.1 also tested with Amazon Coretto 17
OS: Windows 11 and 10

**Comment by laurit** [comment]
I believe this issue only happens on windows @Groenig20 have you considered attempting to fix it yourself?
