### ISSUE TITLE
Keep the ExporterProperties of spring boot starter consistent with the Export builder on sdk

### ISSUE THREAD

**Issue by dengliming** [open-telemetry/opentelemetry-java-instrumentation#864]
Now. I found that `io.opentelemetry.instrumentation.spring.autoconfigure.exporters.otlp.OtlpGrpcSpanExporterProperties` has field `serviceName`, but` io.opentelemetry.exporters.otlp.OtlpGrpcSpanExporter.Builder#Builder` don't have this field to config.

**Comment by trask** [comment]
Good catch!

It looks like `OtlpGrpcSpanExporterProperties.serviceName` is not being used.

Currently the way to set service name for OTLP is via `OTEL_RESOURCE_ATTRIBUTES`:

> In order to configure the service name for the OTLP exporter, you must add service.name key to the OpenTelemetry Resource (see below), e.g. OTEL_RESOURCE_ATTRIBUTES=service.name=myservice

(https://github.com/open-telemetry/opentelemetry-java-instrumentation#otlp-exporter)

There's hopefully some simplification coming in https://github.com/open-telemetry/opentelemetry-specification/issues/709.

But that still doesn't address programmatic configuration of service name for the OTLP exporter, which I think is important for a good Spring Boot experience.

I think we either need a way to set OpenTelemetry Resource Attributes programmatically, and/or a way to set the serviceName directly on the OtlpGrpcSpanExporter (e.g. which would then override service.name set via Resource Attributes).

Both of these will require changes in the SDK, so do you mind opening an issue in that repo to discuss these changes (referencing this issue), and we can keep this issue open to track the corresponding changes that will then be needed here?

**Comment by dengliming** [comment]
@trask Thanks for quick reply.  agree.  It's important for a good Spring Boot experience. Already opened an issue in SDK repo.
