### ISSUE TITLE
Allow setting SimpleSpanProcessor for export

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#866]
Users on a FAAS like lambda will need to flush spans directly without batching or the function will often be terminated before it has a chance to flush. And it seems the way these runtimes work it's common that even a shutdown hook like in #797 won't be called when the function exits, and instead all threads are just paused.

**Comment by trask** [comment]
`SimpleSpanProcessor` still isn't going to give synchronous flushes anymore with https://github.com/open-telemetry/opentelemetry-java/pull/1428, so can still leave you with lost telemetry data.

Is there any chance to add instrumentation for Lambda that does a synchronous flush before the execution environment is frozen?

**Comment by anuraaga** [comment]
I found the lambda Java framework here

https://github.com/awslabs/aws-serverless-java-container

Presumably we'll need to auto instrument this to flush before a response is returned to the framework. Is this an appropriate repo for vendor specific instrumentation? Believe I saw dropwizard which is possibly similar.

**Comment by trask** [comment]
> Is this an appropriate repo for vendor specific instrumentation?

Will this instrumentation be useful to customers of Splunk, New Relic, etc when running in AWS? If so, then I think this is an appropriate repo for it.

**Comment by anuraaga** [comment]
@trask Yeah I think so, any lambda user will need it regardless of the tracing vendor. Thanks for confirming :)

**Comment by trask** [comment]
@anuraaga should we close this particular issue since `SimpleSpanProcessor` won't imply a synchronous export soon?

**Comment by anuraaga** [comment]
Moved to after ga. We could close too but presumably since it exists we would want a knob at some point.

**Comment by anuraaga** [comment]
Closing this since even on FaaS, BSP + forceFlush is always going to be more appropriate than SSP, and is what our instrumentation is using now
