### ISSUE TITLE
Unable to access the original Runnable object in SpringSchedulingRunnableWrapper

### ISSUE THREAD

**Issue by kes2464** [open-telemetry/opentelemetry-java-instrumentation#8661]
Opening a bug. Could this be looked into?

Thanks

### Discussed in https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/8657

<div type='discussions-op-text'>

<sup>Originally posted by **kes2464** June  6, 2023</sup>
Hi

```
if (scheduledTask instanceof ScheduledMethodRunnable) {
  // do something
}
```

One of my applications have the above code which checks a type of Runnable instance and does something.
It's scheduled through Spring Task scheduler, so it's auto-instrumented. 

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/a2fd908d47e638aa85fc4ce3666c1b29e0258b33/instrumentation/spring/spring-scheduling-3.1/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/spring/scheduling/v3_1/TaskSchedulerInstrumentation.java#L47-L52

However, TaskSchedulerInstrumentation wraps the object and replaces the argument, so the condition is never true.

There's also no getter of the original instance in the wrapper.

Is there any common practice/workaround that people use apart from using reflection?</div>

**Comment by laurit** [comment]
@kes2464 could you elaborate how do you observe our wrapped runnable or provide a sample app that reproduces the issue.

**Comment by kes2464** [comment]
Hi @laurit,

I have my own implementation of TaskScheduler which implements schedule methods.
Within the schedule methods it checks the type of the task runnable and do something.

So it's something like this
```
@Override
public ScheduledFuture<?> schedule(Runnable task, Trigger trigger) {
  if (scheduledTask instanceof ScheduledMethodRunnable) {
    // do something
  }
``` 
 
Basically, the Runnable is wrapped to SpringSchedulingRunnableWrapper before entering the method, it never goes into the if block.

**Comment by laurit** [comment]
@kes2464 then it should be resolved with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8676

**Comment by kes2464** [comment]
> @kes2464 then it should be resolved with #8676

@laurit If I understood the change correctly, my implementation of TaskScheduler won’t be auto-instrumented and I probably need to add manual instrumentations, is that correct?

**Comment by laurit** [comment]
@kes2464 if your scheduler delegates to another scheduler that is one of the instrumented ones then that scheduler will produce spans. If not, then yes, you'll need to manually instrument it.

**Comment by kes2464** [comment]
> @kes2464 if your scheduler delegates to another scheduler that is one of the instrumented ones then that scheduler will produce spans. If not, then yes, you'll need to manually instrument it.

Sounds good, thanks.
