### ISSUE TITLE
How to monitor OpenTelemetry Agent internal metrics

### ISSUE THREAD

**Issue by lcappuccio** [open-telemetry/opentelemetry-java-instrumentation#8686]
Hi, is there a way to export to prometheus the agent internal metrics, e.g., accumulated items in queue, amount of dropped spans that were not pushed to the collector and possibly also used heap space memory used.

**Comment by laurit** [comment]
@lcappuccio agent metrics are just like other metrics, if you want to export them to prometheus you'll have to configure the prometheus exporter https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#prometheus-exporter
