### ISSUE TITLE
[HTTP semconv] Some of the attributes will no longer be available for sampling

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#8695]
In the process of implementing the new HTTP semconv (and simplifying the getter interfaces) I've moved extraction of some of the attributes from `onStart` to `onEnd` -- this will cause them to be unavailable for sampling. We might want to revisit this topic 
before 2.x and try to figure out if there's a way to extract them on start. 

See https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8616#discussion_r1223777103 (and some other examples in the server/client semconv PRs)

**Comment by trask** [comment]
wdyt of `ServerAttributesGetter` (etc) having two `getServerInetSocketAddress` (etc) methods, one that takes only request, and one that takes both request/response?

this way instrumentations that don't need the response to emit `server.address` can produce that in `onStart`?

I think `server.address` is a fairly useful sampling attribute

**Comment by mateuszrzeszutek** [comment]
`server.{address,port}` is always extracted on start, the spec even requires it to be sampling relevant; it's the `server.socket.*` (and `client.scoket.*`) attributes that aren't.

**Comment by mateuszrzeszutek** [comment]
@trask this issue might be slightly out of date when it comes to attribute naming, but it's still valid -- we extract all the `network.*` attributes `onEnd()` now (I think it used to be we extracted some of these `onStart()` in HTTP server instrumentations). Do you think that's a problem?

**Comment by trask** [comment]
this sounds good, I don't think it's a problem that `network.*` attributes are extracted onEnd()
