### ISSUE TITLE
Open Telemetry - Clarifications

### ISSUE THREAD

**Issue by banandh** [open-telemetry/opentelemetry-java-instrumentation#8702]
I have enabled automatic instrumentation in the java application and able to view metrics and traces in the respective backends. Have below questions related to productionizing this solution.

1. What will happen if the Otel Collector is not reachable by the application. Will the telemetry data lost or any other config options to collect those failures and retry from application?
2. How to ensure high availability of this Otel collector in production? 
3. Earlier log related configurations on collector was on Beta phase is that complete? can we use Otel for exporting application logs also?

**Comment by laurit** [comment]
1. When collector is not available data is dropped. There is an experimental option to enable retry`otel.experimental.exporter.otlp.retry.enabled`, see https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#otlp-exporter-retry
2. You should ask this question from collector folks
3. Logging signal was recently declared stable in spec. Application logs can be exported, this project includes appenders for popular logging frameworks that one can configure manually or automatically with javaagent.

**Comment by laurit** [comment]
It is for agent and is enabled with `otel.experimental.exporter.otlp.retry.enabled` property, see https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure

**Comment by banandh** [comment]
Thank you @laurit
