### ISSUE TITLE
Move AWS specific attributes definitions in AWS SDK instrumentation modules into semconv package 

### ISSUE THREAD

**Issue by mxiamxia** [open-telemetry/opentelemetry-java-instrumentation#8710]
**Is your feature request related to a problem? Please describe.**
In AWS SDK instrumentation module, there are multiple AWS Resource attributes are being defined separately([examples](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/0070148b3424db5b11be257b1e086cf8ba59ed0b/instrumentation/aws-sdk/aws-sdk-1.11/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v1_11/AwsExperimentalAttributes.java#L15)) from semconv package.  It will introduce the inconsistent AWS resource attribute name among different packages in OTel.  

**Describe the solution you'd like**
We suggest to add these AWS Resource name attributes in [semconv#SemanticAttributes](https://github.com/open-telemetry/opentelemetry-java/blob/main/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java) so it can be consistent with the same attribute names on AWS Resources.  

**Describe alternatives you've considered**
N/A

**Additional context**
The issue is related to https://github.com/open-telemetry/opentelemetry-java-contrib/pull/906#discussion_r1227041743

**Comment by trask** [comment]
> We suggest to add these AWS Resource name attributes in [semconv#SemanticAttributes](https://github.com/open-telemetry/opentelemetry-java/blob/main/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java) so it can be consistent with the same attribute names on AWS Resources.

hi @mxiamxia! `SemanticAttributes.java` is code generated from the yaml files in https://github.com/open-telemetry/semantic-conventions/tree/main/semantic_conventions

**Comment by mxiamxia** [comment]
> > We suggest to add these AWS Resource name attributes in [semconv#SemanticAttributes](https://github.com/open-telemetry/opentelemetry-java/blob/main/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java) so it can be consistent with the same attribute names on AWS Resources.
> 
> hi @mxiamxia! `SemanticAttributes.java` is code generated from the yaml files in https://github.com/open-telemetry/semantic-conventions/tree/main/semantic_conventions

Thanks, will move this issue to semantic_conventions repo.
