### ISSUE TITLE
Servlet snippet inject do not work

### ISSUE THREAD

**Issue by oliver-zhang** [open-telemetry/opentelemetry-java-instrumentation#8734]
**Describe the bug**
Servlet snippet inject do not work

**Steps to reproduce**
I am using auto java instrumentation and set -Dotel.experimental.javascript-snippet="<script src="http://cdn.jsdelivr.net/webjars/jquery/2.1.4/jquery.min.js"></script>" from my springboot project
My html is as follows:
```html
<html xmlns:th="http://www.thymeleaf.org">
<head lang="en">
    <title>Spring Framework Sample</title>
</head>
```
**What did you expect to see?**
```html
<html xmlns:th="http://www.thymeleaf.org">
<head lang="en">
    <script src="http://cdn.jsdelivr.net/webjars/jquery/2.1.4/jquery.min.js"></script>
    <title>Spring Framework Sample</title>
</head>
```
**What did you see instead?**
```html
<html xmlns:th="http://www.thymeleaf.org">
<head lang="en">
    <title>Spring Framework Sample</title>
</head>
```
**What version are you using?**
1.26

**Comment by oliver-zhang** [comment]
I haved check the code, the html content must contains <head>, if not this functionlly can not work, can we check the content start with ```<head ...``` and end with ```>``` ?

**Comment by oliver-zhang** [comment]
The config ```otel.experimental.javascript-snippet``` only support system properties,  It may be better support system env at the same time

**Comment by mateuszrzeszutek** [comment]
FYI @siyuniu-ms 

> The config `otel.experimental.javascript-snippet` only support system properties, It may be better support system env at the same time

It does support env vars actually -- you can use `OTEL_EXPERIMENTAL_JAVASCRIPT_SNIPPET`
