### ISSUE TITLE
Support Gauge for JVM Metrics

### ISSUE THREAD

**Issue by visonliamazon** [open-telemetry/opentelemetry-java-instrumentation#8748]
**Is your feature request related to a problem? Please describe.**

The current implementation of Java JVM metrics uses the [upDownCounter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#updowncounter) 
(For example, [MemoryPools.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/ca24c388463cb36baa4b3926b26d7fc4b348b237/instrumentation/runtime-telemetry/runtime-telemetry-java8/library/src/main/java/io/opentelemetry/instrumentation/runtimemetrics/java8/MemoryPools.java#L89))

However, most of the metrics in JVM should display as the "current values" instead of the "increments/decrements"
For example, there are metrics like `process.runtime.jvm.memory.usage`, and `process.runtime.jvm.memory.limit`
It's more useful to see the current values of memory usage and limit.

**Describe the solution you'd like**
Supports the `GaugeCounter` for the [JVM runtime metrics](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/ca24c388463cb36baa4b3926b26d7fc4b348b237/instrumentation/runtime-telemetry/runtime-telemetry-java8/library)

**Additional context**
When I use the [automatic instrumentation](https://opentelemetry.io/docs/instrumentation/java/automatic/) of OpenTelemetry, and publish the metrics to CloudWatch, the `memory.limit` metrics shows `0` since there is no increment.

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/133038422/9e5b896c-9998-46ba-af99-76a58e23bbde)

**Comment by trask** [comment]
hi @visonliamazon!

The Java SDK follows the specification, which emits UpDownCounters as cumulative, even if you choose delta:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/otlp.md#additional-configuration

Could this be an issue in your specific exporter pipeline?

**Comment by visonliamazon** [comment]
Hi @trask , thanks for the quick response.

I am really new to the OpenTelemetry, maybe there are some configurations could resolve my problem.
But yes, we do encounter the issue where we use publish metrics with `UpDownCounters` to CloudWatch.
The metrics in dashboard shows the `delta` instead of `cumulative` values as the screenshot above

**Comment by trask** [comment]
hi @visonliamazon, were you able to figure this out? if you still need help, can you provide a minimal repro using the logging exporter, so we can rule out it being an issue with your specific monitoring backend?
