### ISSUE TITLE
How to break dependency of logger appenders on the global OpenTelemetry instance

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#8760]
Proposal from last Thu Java SIG meeting is to configure the appenders like normal (e.g. in logback or log4j configuration files), but don't have them use the GlobalOpenTelemetry, and instead have them be noop until someone injects an OpenTelemetry instance into them.

Then in the spring boot starter we can (somehow) dynamically loop through all the appenders (for logback/log4j respectively) and if we find one of our OpenTelemetry Appenders, then we can inject the OpenTelemetry instance.

The limitation here is that we will miss any spring boot startup logs. One option here would be to cache some number of logs in the OpenTelemetry Appenders until the OpenTelemetry instance is injected.

**Comment by jeanbisutti** [comment]
Interesting Spring Boot stack in #8773

**Comment by mateuszrzeszutek** [comment]
> Proposal from last Thu Java SIG meeting is to configure the appenders like normal (e.g. in logback or log4j configuration files), but don't have them use the GlobalOpenTelemetry, and instead have them be noop until someone injects an OpenTelemetry instance into them.

I don't think that we have much choice in that matter, really; we probably have to implement it the way you described. Logging systems are usually one of the first things to get initialized in an application (and the Spring starter bug is a great example of that), and I can't really think of a better way to handle this.

> The limitation here is that we will miss any spring boot startup logs. One option here would be to cache some number of logs in the OpenTelemetry Appenders until the OpenTelemetry instance is injected.

I think we could do this as an option - users could enable the caching if they decide they really need these startup logs.

**Comment by jeanbisutti** [comment]
For Logback, the `OpenTelemetryAppender` could be dynamically retrieved with this kind of code:

```java
    private static Optional<OpenTelemetryAppender> findOtelAppenderWithLogback(LoggerContext loggerContext) {
        for (Logger logger : loggerContext.getLoggerList()) {
            Iterator<Appender<ILoggingEvent>> appenderIterator = logger.iteratorForAppenders();
            while (appenderIterator.hasNext()) {
                Appender<ILoggingEvent> appender = appenderIterator.next();
                if (appender instanceof OpenTelemetryAppender) {
                    return Optional.of((OpenTelemetryAppender) appender);
                }
            }
        }
        return Optional.empty();
    }
```

**Comment by jeanbisutti** [comment]
> For Logback, the `OpenTelemetryAppender` could be dynamically retrieved with this kind of code:
> 
> ```java
>     private static Optional<OpenTelemetryAppender> findOtelAppenderWithLogback(LoggerContext loggerContext) {
>         for (Logger logger : loggerContext.getLoggerList()) {
>             Iterator<Appender<ILoggingEvent>> appenderIterator = logger.iteratorForAppenders();
>             while (appenderIterator.hasNext()) {
>                 Appender<ILoggingEvent> appender = appenderIterator.next();
>                 if (appender instanceof OpenTelemetryAppender) {
>                     return Optional.of((OpenTelemetryAppender) appender);
>                 }
>             }
>         }
>         return Optional.empty();
>     }
> ```

To inject after an `OpenTelemetry` instance, a `set(OpenTelemetry)` method would have to be added to the Logback `OpenTelemetryAppender`.

**Comment by jeanbisutti** [comment]
For Log4j 2, the appenders may be retrieved with this kind of code (_not yet tested_):

```java
      List<Appender> appenders = new ArrayList<>();
      LoggerContext context = (LoggerContext) LogManager.getContext();
      Configuration configuration = context.getConfiguration();

      Collection<LoggerConfig> loggerConfigs = configuration.getLoggers().values();

      for (LoggerConfig loggerConfig : loggerConfigs) {
        Collection<Appender> otherAppenders = loggerConfig.getAppenders().values();
        appenders.addAll(otherAppenders);
      }
```

**Comment by FWinkler79** [comment]
This may be a heretical question, but why do you consider injecting the SDK into the appender at all?
I think Logback and Log4J appenders are not especially injection-friendly, and even though from a dependency-injection pov it may not be the nicest solution, why not creating an SDK instance in the appender itself (just with the required OTLP log exporters) and configuring it with properties in the logback.xml file? In case anyone wants to see what this would look like you can find sample code [here](https://github.com/FWinkler79/spring3-observability/blob/main/spring3-demo-client/src/main/java/com/acme/observability/demo/client/LogbackOpenTelemetryAppender.java).

**Comment by jeanbisutti** [comment]
This issue is fixed as far as I know.

**Comment by FWinkler79** [comment]
@jeanbisutti: Would you mind sharing the details how this was fixed or a link that points to the fix, please?
I'd really be curious how this is handled now.
Thanks!

**Comment by jeanbisutti** [comment]
@FWinkler79 The updated documentation: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/logback/logback-appender-1.0/library 

PRs: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8791, https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8888, https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9798

In your example, you use Spring Boot. With the [OTel starter](https://opentelemetry.io/docs/instrumentation/java/automatic/spring-boot/), you don't have to inject an `OpenTelemetry` instance into the OTel log appender. It is automatically done by this starter. You have just to add the OTel appender inthe logback.xml or log4j2.xml file. This remaining thing could probably be done automatically by the OTel starter.

"why not creating an SDK instance in the appender itself ": the OTel starter provides an `OpenTelemetry` bean that can bean injected into other Spring beans.
