### ISSUE TITLE
How to Capturing HTTP request and response headers.

### ISSUE THREAD

**Issue by zwskymoon** [open-telemetry/opentelemetry-java-instrumentation#8768]
In the official document, there is this sentence:You can configure the agent to capture predefined HTTP headers as span attributes, according to the [semantic convention](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#http-request-and-response-headers).

Now, I set the Environment variable: OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_CLIENT_REQUEST
as http.request.header.my_custom_header=["abc", "def"].

And a Client requet my server with the request header:"my_custom_header:abc".

In my java project ,how can I get the custom request header using span attributes.

**Comment by mateuszrzeszutek** [comment]
Moving to the instrumentation repo.

Hey @zwskymoon ,
Are you using the javaagent? If so, you can configure the capture of the HTTP headers using [these configurations settings](https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#capturing-http-request-and-response-headers).

**Comment by zwskymoon** [comment]
@mateuszrzeszutek  Yes,I am using javaagent ,and I set the Environment variable using [these configurations settings](https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#capturing-http-request-and-response-headers).
As follows：
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/26498964/743ba53f-7a83-40d7-8514-6863e08e75c2)

**Comment by mateuszrzeszutek** [comment]
That setting requires a comma-separated list of HTTP header names.

Try 
```properties
OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_CLIENT_REQUEST=abc,def
```

**Comment by zwskymoon** [comment]
Hey @mateuszrzeszutek ,
I have followed the settings you mentioned, but it still doesn't seem to work.

**Comment by mateuszrzeszutek** [comment]
Please post your agent configuration here.

**Comment by zwskymoon** [comment]
@mateuszrzeszutek 
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/26498964/63834bf0-e6a1-43d4-b88d-c4067bc77658)

**Comment by zwskymoon** [comment]
But,I think my previous writing method was quite correct.  
You can refer to:
[semantic convention](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#http-request-and-response-headers)

**Comment by mateuszrzeszutek** [comment]
Sorry, I don't understand what this window is setting; and how (if at all) the environment variables set here are propagated to your Java process. Don't you have some `bat`/`sh` start script where you add the `-javaagent:/path/to/opentelemetry-javaagent.jar` param?

**Comment by mateuszrzeszutek** [comment]
> But,I think my previous writing method was quite correct. You can refer to: [semantic convention](https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#http-request-and-response-headers)

The examples in the spec refer to the final attributes extracted from the HTTP headers, not the configuration. The spec does not say anything about how this feature is supposed to be configured (which is intentional -- the configuration layer is left to the implementation).
The docs link I posted describes the value format explicitly:

> A comma-separated list of HTTP header names.

**Comment by mateuszrzeszutek** [comment]
Just to make sure: are you pasting the header name you expect to capture instead of the example `abc,def`? What HTTP client are you using?

**Comment by zwskymoon** [comment]
I set as follows:
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/26498964/6d310d09-d80e-488a-a2b9-2671d7dab078)

And I use postman to request my localhost:
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/26498964/0d9b9dd8-d5f6-4e24-9166-d435733c33ef)

Is this right？

**Comment by zwskymoon** [comment]
@mateuszrzeszutek , If right, how do I obtain this custom header named "my_custom_header" in span attributes?

**Comment by laurit** [comment]
`otel.instrumentation.http.capture-headers.client.request` is for capturing headers for a request made from within the instrumented application. If you are using an external application to make a request to your instrumented application then you probably should be using `otel.instrumentation.http.capture-headers.server.request`.

**Comment by zwskymoon** [comment]
@laurit ,I have also set this environment variable:otel.instrumentation.http.capture-headers.server.request,
but it does not work either

**Comment by zwskymoon** [comment]
@mateuszrzeszutek ,I have already OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_CLIENT_REQUEST to my_custom_header.

**Comment by laurit** [comment]
@zwskymoon could you provide a minimal application and describe what environment variables you are setting so we could reproduce your issue.
