### ISSUE TITLE
Allow overriding propagation of tracing headers

### ISSUE THREAD

**Issue by giovanniberti** [open-telemetry/opentelemetry-java-instrumentation#8786]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Azure API Management without Diagnostic Logs enabled injects `traceparent` headers with the `sampling` flag set to 0.
This causes the agent to not emit traces on instrumented services, and there's no easy way to override this behaviour from APIM without enabliing Diagnostic Logs.

**Describe the solution you'd like**

I would like a configuration option to allow the agent to ignore incoming tracing headers, like [this option](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-trace-continuation-strategy) on the Elastic APM.

**Describe alternatives you've considered**

An alternative would be to use `AlwaysOn` sampler, but I'd rather have something more fine-grained if possible :)

**Additional context**

**Comment by trask** [comment]
hi @giovanniberti! you could use a [java agent extension](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension) to provide your own sampler which is not "parent based" (i.e. ignores the traceparent sampling flag)
