### ISSUE TITLE
Context propagation issue in AWS SQS with auto instrumentation

### ISSUE THREAD

**Issue by teammakdi** [open-telemetry/opentelemetry-java-instrumentation#8789]
**Describe the bug**

I've configured my spring boot app for auto telemetry with the following config

```dockerfile
CMD java -javaagent:opentelemetry-javaagent.jar \
            -Dotel.service.name=test \
            -Dotel.metrics.exporter=none \
            -Dotel.traces.exporter=otlp \
            -Dotel.exporter.otlp.endpoint=http://xxx.xx.xx.xx:4317	\
            -Dotel.node.resource.detectors=all \
            -Dotel.instrumentation.common.default-enabled=true \
            -Dotel.instrumentation.aws-sdk.experimental-use-propagator-for-messaging=true \
            -Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=true \
            -Dotel.instrumentation.jdbc-datasource.enabled=true \
            -jar /usr/src/app/test-1.0.0.jar
```

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

With the `-Dotel.instrumentation.aws-sdk.experimental-use-propagator-for-messaging` flag, I was expecting the application would send the context to the SQS and can also be seen in the AWS SQS message attributes section.

<img width="801" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/125042792/c1cf7d26-0a86-48dd-aa38-be23d21591c6">

**What did you see instead?**
A clear and concise description of what you saw instead.

The application did not attach any context and was not able to trace the log end to end since the app architecture is like

```
App1 --> SQS --> App2
```
**What version are you using?**
(e.g., `v0.9.0`, `393e4a2`, etc)
latest `jar` from https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar

**Environment**
Docker base image: eclipse-temurin:17-jre-alpine

**Additional context**

**Comment by abhisheksurve45** [comment]
Update, now I'm using micrometer to achieve this, followed this article

https://amithkumarg.medium.com/distributed-tracing-with-spring-boot-micrometer-opentelemetry-and-jaeger-fafd5c0bd282

However still I'm not sure how to pass the trace ID though SQS, if it can be done automatically with some flag or has manual effort.

**Comment by teammakdi** [comment]
Update, now I'm using micrometer to achieve this, followed this article

https://amithkumarg.medium.com/distributed-tracing-with-spring-boot-micrometer-opentelemetry-and-jaeger-fafd5c0bd282

However still I'm not sure how to pass the trace ID though SQS, if it can be done automatically with some flag or has manual effort.

**Comment by mateuszrzeszutek** [comment]
CC @Oberon00

**Comment by mateuszrzeszutek** [comment]
@teammakdi would you be able to produce a reproduction scenario for this issue?

**Comment by Oberon00** [comment]
There are some cases that are not implemented (yet): The v1 SDK does not have this feature at all, and in the v2 SDK it only works with SendMessage and not with SendMessageBatch. Which SDK versions and API calls are you using?

**Comment by teammakdi** [comment]
@Oberon00  @mateuszrzeszutek Not an issue, I just want to know how I can instrument applications if amazon SQS queue is present in between. 

Is it a manual process (by manually adding span and trace ID) or happens automatically if run with opentelemetry jar.

At the moment my application is on spring boot 3, hence I'm using micrometer https://micrometer.io/docs/tracing.

For apache kafka it has automatically instrumented it.

**Comment by teammakdi** [comment]
Ah, I'm using SDK v2 with `SendMessageBatch`, maybe thats the issue!

Is there any issue/thread where this discussion is going on? Or any ETA by when the support for `SendMessageBatch` is expected?

@Oberon00

**Comment by Oberon00** [comment]
Actually I already have an implementation locally that I'm looking to contribute in the next few days 😃 So if my contribution is accepted it might be in the next release already.

**Comment by Oberon00** [comment]
But the XRay propagation (enabled by default, but also still on if you enable the additional experimental message propagator usage) should also work for SendMessageBatch, even though you won't see any attributes in the AWS Web UI.

**Comment by teammakdi** [comment]
@Oberon00 So I'm assuming we would be sending the span and trace to all the messages in the batch, however at receiving end if the receiver is listening different batch size, would the tracing still work fine?

**Comment by Oberon00** [comment]
The XRay injection works by seting a HTTP header. This is then picked up by the SQS backend and it sets a message system attribute all messages, copying the value from the HTTP header to all messages separately. There is actually no way to store any attributes on the batch itself. So it won't matter if receive batch size / send batch size does not match (this will anyways be the case 99% of the time)

**Comment by teammakdi** [comment]
Since you mentioned it should work for `sendMessage`

I've 2 apps in my case, App1 (producer) (Java spring app) and  App2 (consumer) Node JS app and theres the SQS queue in between

- `App1` config

Java: `17`

```dockerfile
CMD java -javaagent:opentelemetry-javaagent.jar \
            -Dotel.service.name=app1 \
            -Dotel.metrics.exporter=none \
            -Dotel.traces.exporter=otlp \
            -Dotel.exporter.otlp.endpoint=http://xxx.xx.xx.xx:4317	\
            -Dotel.node.resource.detectors=all \
            -Dotel.instrumentation.common.default-enabled=true \
            -Dotel.instrumentation.aws-sdk.experimental-use-propagator-for-messaging=true \
            -Dotel.instrumentation.messaging.experimental.receive-telemetry.enabled=true \
            -Dotel.instrumentation.jdbc-datasource.enabled=true \
            -jar /usr/src/app/app1.jar
```

- `App2` config

Node JS: `16`


```
OTEL_EXPORTER_OTLP_ENDPOINT='http://xxx.xx.xx.xx:4317'
OTEL_TRACES_EXPORTER='otlp'
OTEL_NODE_RESOURCE_DETECTORS='all'
OTEL_SERVICE_NAME='app2'
OTEL_EXPORTER_OTLP_PROTOCOL='grpc'
```

```bash
npm install --save @opentelemetry/instrumentation-grpc @opentelemetry/api @opentelemetry/auto-instrumentations-node 
node --require @opentelemetry/auto-instrumentations-node/register app.js
```

With this given configuration, I'm expecting to get an end to end trace, however not able to.

**Comment by Oberon00** [comment]
I can't really help you with node. But with sendMessage and the experimental setting, you should see the message attributes (traceparent and possible tracestate) in the AWS Web console.

**Comment by teammakdi** [comment]
There is this doc https://www.aspecto.io/blog/getting-started-with-opentelemetry-aws/ which says to set few configs on receiver end

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/125042792/af1712bc-3c1a-4fb6-9cc3-82eb43c970fa)

However not tried it

**Comment by teammakdi** [comment]
> I can't really help you with node. But with sendMessage and the experimental setting, you should see the message attributes (traceparent and possibly tracestate) in the AWS Web console.

I still dont see any message attributes being passed with `sendMessage` on the AWS console 

Just to clarify trying to poll messages from the SQS section

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/125042792/ed0f1cb6-a996-4e87-9b8d-255c9a36ed07)

**Comment by Oberon00** [comment]
Do you get the SendMessage span in your tracing system?

**Comment by abhisheksurve45** [comment]
> Do you get the SendMessage span in your tracing system?

Yes

Cool, will try out with this jar

**Comment by trask** [comment]
@abhisheksurve45 any update?

**Comment by teammakdi** [comment]
Hey @trask, sorry was caught up in something else, will check it out this week.

**Comment by teammakdi** [comment]
Will check it out this week.
