### ISSUE TITLE
AKKA Initializer Error after using OTEL Java Agent [1.26,1.27]

### ISSUE THREAD

**Issue by yashwanth522** [open-telemetry/opentelemetry-java-instrumentation#8807]
**Describe the bug**
AKKA Initializer Error after using OTEL Java Agent

**Steps to reproduce**

- Try to instrument the application with OTEL Java Agent 1.26/1.27.
- Restart the service and observe that the restart fails and eventually fails to start and shuts down

**What did you expect to see?**

- An integration with OTEL Java Agent 1.26/1.27 should be successful
- Should see the Traces being published

**What did you see instead?**

- Service startup failure with AKKA Initializer Error.
- _2023-05-31 14:56:32.243 ERROR [localhost-startStop-1] LP-MRS-SERVICE_LOGGER -  - Error Occurred in AKKA Initilizer
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'otelGlobalChannelInterceptor': Unsatisfied dependency expressed through constructor parameter 0: Could not convert argument value of type [io.opentelemetry.javaagent.shaded.instrumentation.spring.integration.v4_1.TracingChannelInterceptor] to required type [org.springframework.integration.channel.ChannelInterceptor]: Failed to convert value of type 'io.opentelemetry.javaagent.shaded.instrumentation.spring.integration.v4_1.TracingChannelInterceptor' to required type 'org.springframework.integration.channel.ChannelInterceptor'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'io.opentelemetry.javaagent.shaded.instrumentation.spring.integration.v4_1.TracingChannelInterceptor' to required type 'org.springframework.integration.channel.ChannelInterceptor': no matching editors or conversion strategy found_

**What version are you using?**

- Tried with 1.26/1.27 and 0.9
- None of them worked

**Environment**
Compiler/Runtime:  jdk1.8.0_172
Server: tomcat-7.0.81
OS: NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"

**Comment by laurit** [comment]
You can probably work around this by disabling `spring-integration` instrumentation as described in https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#suppressing-specific-agent-instrumentation If you wish to help us fix it then a minimal sample app that reproduces the issue would be awesome. It is a bit hard to see how this could happen, perhaps your application has spring integration jars in multiple class loaders? If you are handy with debugger you could verify whether `TracingChannelInterceptor` extends the expected `ChannelInterceptor` class or `ChannelInterceptor` class in some other class loader when the `IllegalStateException` is thrown.

**Comment by yashwanth522** [comment]
@laurit We use akkaVersion = '2.4.16' springRelease = '4.2.3.RELEASE' springCloudRelease = '2.2.8.RELEASE'
I haven't seen any references to TracingChannelInterceptor/ChannelInterceptor in our code.

**Comment by yashwanth522** [comment]
After using the flag -Dotel.instrumentation.spring-integration.enabled=false
our application is starting fine. We can close this one. Thanks
