### ISSUE TITLE
Project doesn't compile with Java 20

### ISSUE THREAD

**Issue by tylerbenson** [open-telemetry/opentelemetry-java-instrumentation#8814]
**Describe the bug**
Kotlin doesn't yet support Java 20, so Gradle doesn't support it either yet.
See: https://github.com/gradle/gradle/issues/23488

**Steps to reproduce**
Using a Java 20 release, try building the project. `./gradlew compileJava` for example.

**What did you see?**
```
> Task :conventions:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':conventions:compileKotlin'.
> Error while evaluating property 'compilerOptions.jvmTarget' of task ':conventions:compileKotlin'.
   > Failed to calculate the value of property 'jvmTarget'.
      > Unknown Kotlin JVM target: 20
```

**Additional context**
I don't expect us to fix anything right now.  Just documenting the problem as [CONTRIBUTING.md](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/CONTRIBUTING.md) suggests Java 17+ is required.  Perhaps we should specify an upper range of what has been tested?

**Comment by trask** [comment]
I'm good with changing our recommendation to "Java 17" (no "+"), since that's what all of our builds use.
