### ISSUE TITLE
Save "artifacts" at the end of GitHub Nightly build

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#882]
Capturing the same things as we are capturing for CircleCI via `collect_libs.sh`, `collect_reports.sh` and `collect_results.sh`

From what I can tell this looks like standard action https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts, and we can only upload single files or zips. Which is too bad, I like being able to browse and link to the html artifacts in CircleCI, but not a deal breaker.

**Comment by iNikem** [comment]
I have some thoughts about publishing test reports.

Is it enough to have jar files published to oss.jfrog.com or do you want them in GitHub UI as well?

**Comment by trask** [comment]
I think they will be much more discoverable (e.g. new contributors looking at why their PR build failed) if they are stored in the normal GitHub actions artifacts, so would prefer that unless we can store them somewhere where you can navigate and link to the html reports, in which case those benefits may outweigh GitHub actions artifacts.

**Comment by trask** [comment]
The build scans look really nice for investigating failures, e.g.

https://scans.gradle.com/s/a3rvevp7invbc/tests/failed

Can we make them more visible somehow, e.g. a link to it in the artifacts section?

**Comment by trask** [comment]
E.g. this build report makes it look like `AkkaExecutorInstrumentationTest` caused the build to fail:

https://app.circleci.com/pipelines/github/open-telemetry/opentelemetry-java-instrumentation/2700/workflows/d458b21f-fb47-411d-9909-0a0c641ffd4a/jobs/16258/tests

but really it was retried and then succeeded, and it was another test that caused the build to fail (which is reported lower down in the above report).

While the build scan makes it clear that `AkkaExecutorInstrumentationTest` was FLAKY, and others really FAILED.

**Comment by iNikem** [comment]
Visible links to Gradle build scans are in my pipeline

**Comment by iNikem** [comment]
Nightly build runs have links (unfortunately not clickable) to all build scans: https://github.com/open-telemetry/opentelemetry-java-instrumentation/actions/runs/253140819
