### ISSUE TITLE
Add OTEL instrumentation to JDBC connection creation

### ISSUE THREAD

**Issue by doppleware** [open-telemetry/opentelemetry-java-instrumentation#8838]
**Is your feature request related to a problem? Please describe.**
In order to see in the trace if the connection pool settings need to be modified I'd like to have a span indicating the connection statement 

**Describe the solution you'd like**
A Span instrumentation for the db connection creation

**Describe alternatives you've considered**
I tried to infer the data from the traces in different ways but while I can see the delays happening when connection pooling is misconfigured I cannot attribute it to the specific root cause

**Comment by mateuszrzeszutek** [comment]
Hey @doppleware ,

The agent actually contains a `DataSource` instrumentation, but due to its noisiness it's [disabled by default](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#disabled-instrumentations). Can you try enabling it (`-Dotel.instrumentation.jdbc-datasource.enabled=true`) and check if it fits your needs?

**Comment by doppleware** [comment]
Thanks @mateuszrzeszutek ! That sounds promising. I'll give it a try

**Comment by doppleware** [comment]
Hi, first of all, thanks for the suggestion - I was able to use this data to identify issues with the connection pool.
I think there is still a missing piece here. Unlike queries, there are various attributes that are not set for identifying the database. This makes it harder to use the data generically to automate finding issues with specific data sources.
Please see below data from a 'Select' span:
<img width="1628" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/93863/88a69eac-65c6-4f77-abd6-c5520e0a9a60">

vs. data from the getConnection span where that information is missing:
<img width="1245" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/93863/f6c68cd5-7ed6-487d-a215-9202b27fc7bb">

It would be awesome if you could include the connection string + db.name in this span as well.

**Comment by mateuszrzeszutek** [comment]
> It would be awesome if you could include the connection string + db.name in this span as well.

That's a great idea -- fixed that in #8966
