### ISSUE TITLE
SpringWebTelemetry span name contains only HTTP method

### ISSUE THREAD

**Issue by jkamon** [open-telemetry/opentelemetry-java-instrumentation#8839]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Interceptor created by SpringWebTelemetry creates spans named only by HTTP method. Metadata correctly contains also original URL wich would be much more specific and describing in span.  Probably best solution would be to implement getRoute method on SpringWebMvcHttpAttributesGetter which would most probably generate correct name

**Describe alternatives you've considered**
Change in SpringWebTelemetryBuilder to allow custom name extractor would be also acceptable since user will be able to define its own name extractor which would generate more descriptive names.

**Additional context**
Used version 1.27.0-alpha

**Comment by laurit** [comment]
`SpringWebMvcHttpAttributesGetter ` is used by `SpringWebMvcTelemetry`(server instrumentation) not `SpringWebTelemetry`(client instrumentation). Which are you interested in `SpringWebTelemetry` or `SpringWebMvcTelemetry`?

**Comment by jkamon** [comment]
Thanks for clarification. Now when you pointed it out it is clear that it should be implemented in both:
`SpringWebMvcHttpAttributesGetter`
`SpringWebHttpAttributesGetter`
they both share the same 'mistake' and final spans are reported like this:
![onlyHTTPmethod](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/100095655/79c159df-d722-400b-b8e1-42f2355a1095)

Top level span comes somewhere from OtelPropagator or something like this and is named somehow OK. Later two are created by mentioned classes and are named only POST (green one is from my application named pokus, blue one is from http which is resttemplate). Please do not mind the failures it was only local test.

**Comment by laurit** [comment]
Otel specification gives guidelines for naming these spans https://opentelemetry.io/docs/specs/otel/trace/semantic_conventions/http/#name
@mateuszrzeszutek wdyt about letting users override the span name? Should we let users set `SpanNameExtractor` or `Function<SpanNameExtractor, SpanNameExtractor>` so that the original extractor could be wrapped or something else?

**Comment by mateuszrzeszutek** [comment]
> Should we let users set `SpanNameExtractor` or `Function<SpanNameExtractor, SpanNameExtractor>` so that the original extractor could be wrapped or something else?

It should be a `Function<SpanNameExtractor, SpanNameExtractor>` -- we want to allow decoration of the original extractor.
