### ISSUE TITLE
Flag for Span Links not working for Pulsar 

### ISSUE THREAD

**Issue by damienburke** [open-telemetry/opentelemetry-java-instrumentation#8859]
**Describe the bug**
The flag OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED has no impact when publishing / consuming messages using Apache Pulsar

**Steps to reproduce**
Run an Apache Pulsar Producer and Consumer app and simply publish a message.  

**What did you expect to see?**
With OTEL_INSTRUMENTATION_MESSAGING_EXPERIMENTAL_RECEIVE_TELEMETRY_ENABLED set to true, i would expect to see 2 traces, with a Span link. 

**What did you see instead?**
I just see 1 trace though, for the send, receive and process spans.

**What version are you using?**
1.26.0 of Otel
Tested against v2.8.4 and 2.11.1. pulsar client.

**Environment**
Compiler: eclipse-temurin:17.0.7_7
OS: MacOS 13.4
<img width="1168" alt="Screenshot 2023-07-03 at 17 41 04" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/3668342/b6b69515-cb46-4b32-b13b-6580c5a31e6c">

**Additional context**
This is a very straight forward, happy path use case. My screen shot is of New Relic, which I am aware does not support Span Links. What I did though in addition, was compare the io.opentelemetry.exporter.logging.LoggingSpanExporter output, and they were "identical" for when the flag was true and false. Thanks

**Comment by trask** [comment]
cc @tjiuming

**Comment by tjiuming** [comment]
acked
