### ISSUE TITLE
Bug/JavaAgent plus SpyMemcached plus Mockito won't work together

### ISSUE THREAD

**Issue by arik-dig** [open-telemetry/opentelemetry-java-instrumentation#8862]
**Describe the bug**
I tried to run Unit test with OTEL agent and mocking `OperationFuture` (of spymemcached) . and mockito failed

**Steps to reproduce**

1. write this test class 

```
import net.spy.memcached.internal.OperationFuture;
import org.junit.jupiter.api.Test;

import static org.mockito.Mockito.mock;

public class MyTest {

    @Test
    public void test_OperationFuture() {
        System.out.println("start");
        OperationFuture<Boolean> mockedFuture = mock(OperationFuture.class);

        System.out.println("end");
    }

}
```

2. run the test with JavaAgent

JAVA_TOOL_OPTIONS=/tmp/opentelemetry-javaagent-1.27.0.jar
./gradlew test 

**What did you expect to see?**
test continues to the end

**What did you see instead?**
mockito logged the following : 

```
[otel.javaagent 2023-07-04 08:52:01:398 +0300] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.27.0
start
Mockito cannot mock this class: class net.spy.memcached.internal.OperationFuture.
```

full console log: 
[mockito-spymemcached-log.txt](https://github.com/open-telemetry/opentelemetry-java-instrumentation/files/11945075/mockito-spymemcached-log.txt)

**What version are you using?**
1.27.0

**Environment**

Java               : 17
JVM vendor name    : Oracle Corporation
JVM vendor version : 17.0.6+9-LTS-190
JVM name           : Java HotSpot(TM) 64-Bit Server VM
JVM version        : 17.0.6+9-LTS-190
JVM info           : mixed mode, sharing
OS name            : Mac OS X
OS version         : 13.4.1

**Additional info**
I tried to disable spy memcached with system property `otel.instrumentation.spymemcached.enabled` being set to false
but it did not help

`JAVA_TOOL_OPTIONS=/tmp/opentelemetry-javaagent-1.27.0.jar -Dotel.instrumentation.spymemcached.enabled=false`

**Comment by laurit** [comment]
@arik-dig what do you hope to gain from running such a test with opentelemetry agent? Try `-Dotel.javaagent.experimental.field-injection.enabled=false` and see if it makes any difference (if it still fails check whether there are less classes in the `Could not modify all classes` list in the exception message).

**Comment by arik-dig** [comment]
@laurit seems that flag `otel.javaagent.experimental.field-injection.enabled=false `does help. 
thanks 🙏 

the question left is on which frameworks it affects, can I have this flag toggled **only** for **specific** module for example `spymemcached` ?

**Comment by arik-dig** [comment]
> what do you hope to gain from running such a test with opentelemetry agent?

@laurit, I'm trying to use the Memcached Client and get auto instrumentation on it

**Comment by laurit** [comment]
> the question left is on which frameworks it affects, can I have this flag toggled **only** for **specific** module for example `spymemcached` ?

this flag can not be set per instrumentation
