### ISSUE TITLE
Add tests for the log4j ThreadContext baggage attributes 

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#8863]
The aim of this issue is to implement tests for the feature introduced in #8810; this could be done in a very similar way to what we already have for logback.
Also see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8810#discussion_r1245006010

**Comment by swar8080** [comment]
hey @mateuszrzeszutek I can add some tests later this week

**Comment by mateuszrzeszutek** [comment]
That'd be great, thanks!
