### ISSUE TITLE
How to pass parameters to OpenTelemetry's Java agent in attach mode?

### ISSUE THREAD

**Issue by shenlvcheng** [open-telemetry/opentelemetry-java-instrumentation#8877]
How to pass parameters to OpenTelemetry's Java agent in attach mode? I noticed that the first parameter agentArgs in the premain(String agentArgs, Instrumentation inst) method of the source code has been discarded. Why was it discarded, which is preventing me from passing parameters into the Java agent?

**Comment by laurit** [comment]
Opentelemetry java agent does not use arguments passed to `premain` or `agentmain` we instead use system properties and environment variables to pass configuration to the agent. If you are using runtime attach you can set the system properties via `System.setProperty(...)` before attaching the agent.
