### ISSUE TITLE
Filename too long error on git cloning

### ISSUE THREAD

**Issue by dvsingh9** [open-telemetry/opentelemetry-java-instrumentation#8886]
**Describe the bug**
When cloning the project there are few files with long name/path, then windows complaint saying filename too long. Hence, unable to even create few files that results other project errors.

**Steps to reproduce**
git clone https://github.com/open-telemetry/opentelemetry-java-instrumentation.git
on windows

**What did you expect to see?**
It should clone without errors.

**What did you see instead?**
Error saying file too long

**What version are you using?**
main branch

**Environment**
Compiler: (e.g., "AdoptOpenJDK 11.0.6")
OS: (e.g., "Windows")
Runtime (if different from JDK above): (e.g., "Oracle JRE 8u251")
OS (if different from OS compiled on): (e.g., "Windows Server 2019")

**Additional context**
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/5511465/aedaf2ff-c312-4a7a-b209-b3f817dd48f1)

**Comment by mateuszrzeszutek** [comment]
Hey @dvsingh9 ,

I think you might have to set `longpaths` to true:
```
git config --system core.longpaths true
```

(I'm not a Windows user, cc @trask if you have some tips)

**Comment by dvsingh9** [comment]
yup @mateuszrzeszutek it works.

Anyway adding .gitconfig with

```
[core]
longpaths = true
```

can solve it at application level ?

**Comment by laurit** [comment]
> can solve it at application level ?

@dvsingh9  what do you mean by this?

**Comment by dvsingh9** [comment]
I mean it can be solved by creating .gitconfig under root directory of project. then users need not to set any gitconfig for longpaths.

**Comment by mateuszrzeszutek** [comment]
Do you mean the `.git/config` file? That file cannot be checked in, it contains your local project-specific settings.

**Comment by dvsingh9** [comment]
Agreed, it keeps user related info also.

solution for this error is to run
`git config --system core.longpaths true`

Thanks for quick reply!!
