### ISSUE TITLE
Confusing how to run tests for modules with maxJavaVersionForTests = JavaVersion.VERSION_1_8

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#891]
E.g. it's confusing how to run `netty-4.0` tests.

Running them in Intellij reports success but no tests are run.

Running them via normal command line:

```
./gradlew :instrumentation:netty:netty-4.0:test
```

also succeeds but no tests are run.

The "correct" way currently is:

```
export JAVA_8_HOME=...
./gradlew :instrumentation:netty:netty-4.0:testJava8
```

At least we can document/highlight this in [running-tests.md](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/docs/contributing/running-tests.md).

But also, @anuraaga mentioned at one point about automatically downloading and configuring Java versions to run with. I think this could give us a really nice solution. Especially if we can automatically run every test using the `minJavaVersionForTests` when you run the normal `test` task.

**Comment by anuraaga** [comment]
Gradle 6.7 will support automatically downloading Java for running tests, can't wait!

https://docs.gradle.org/6.7-rc-1/userguide/toolchains.html#specify_custom_toolchains_for_individual_tasks

**Comment by iNikem** [comment]
That's cool :)
