### ISSUE TITLE
Receiving different names for the same field

### ISSUE THREAD

**Issue by ManoharMirle** [open-telemetry/opentelemetry-java-instrumentation#8910]
We are getting 2 different field names for the same parameter from the source. messaging.message_payload_size_bytes comes in one trace, messaging.message.payload_size_bytes comes in another trace. The difference here is _ & . in these fields. We are using 0.55.0 version of the OTEL collector. Pls let me know whether this issue resolved in the agent ? Any other fields have the similar issue ?
Here is the agent details:
-javaagent:/tmp/telemetry/opentelemetry-javaagent.jar
                {
                    "key" : "process.executable.path",
                    "value" : {
                      "stringValue" : "/usr/local/openjdk-11:bin:java"
                    }
                  {
                    "key" : "process.runtime.description",
                    "value" : {
                      "stringValue" : "Oracle Corporation OpenJDK 64-Bit Server VM 11.0.12+7"
                    }
                  }

**Comment by laurit** [comment]
This attribute was renamed in spec in https://github.com/open-telemetry/opentelemetry-specification/pull/2957 If you are using different versions of the agent you could get both of these if the versions of the agent that you use implement different versions of the spec.
