### ISSUE TITLE
Spring boot starter: what do you think about pulling in the appender instrumentation by default, similar to the other library instrumentations?

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#8925]
> what do you think about pulling in the appender instrumentation by default, similar to the other library instrumentations?

_Originally posted by @trask in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/8888#discussion_r1258848645_

cc @mateuszrzeszutek

**Comment by mateuszrzeszutek** [comment]
Sure, why not (I can't really remember any reason not to include it in the first place now 😅 )
