### ISSUE TITLE
MuzzleMatcher: Missing method boolean#clone()Ljava/lang/Object

### ISSUE THREAD

**Issue by twogoods** [open-telemetry/opentelemetry-java-instrumentation#8940]
**Describe the bug**
ot will collector helperClasses，if  class has code
```
  boolean[] arr = new boolean[]{};
  arr.clone();
```

muzzleMatcher log `Missing method boolean#clone()Ljava/lang/Object`

change boolean to Boolean will work

```
  Boolean[] arr = new Boolean[]{};
  arr.clone();
```

if this code in thirdparty library，it's not easy to change the code

**What version are you using?**
1.17.0

**Environment**
Compiler: 17.0.4
OS: mac m1

**Comment by laurit** [comment]
Should be fixed in the latest version, update your muzzle plugin.
