### ISSUE TITLE
Migrate the Spring Starter docs to opentelemetry.io

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#8946]
The aim of this issue is to migrate these two files [(1)](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-boot-autoconfigure/README.md) [(2)](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/starters/spring-boot-starter/README.md) to the opentelemetry.io repo, so that they appear on the main web page. We'll definitely want to trim and edit these a bit; and we might want to make some last minute fixes to make the spring starter a bit similar to the javaagent when it comes to configuration.

**Comment by trask** [comment]
Closing in favor of https://github.com/open-telemetry/opentelemetry.io/issues/3040
