### ISSUE TITLE
Discuss feature idea of instrument alibaba/druid DB connection pool 

### ISSUE THREAD

**Issue by xiongchun** [open-telemetry/opentelemetry-java-instrumentation#8958]
hi,

i want to instrument alibaba/druid database connection pool.

Druid is one of the best database connection pools written in JAVA. Druid provides powerful monitoring functionalities and more.

it's open source page: https://github.com/alibaba/druid. (Starred 27.1K)

English Docs: https://github.com/alibaba/druid/wiki/FAQ

I wonder if I can do this task. Thaks a lot!  

@jack-berg @mateuszrzeszutek @jkwatson 

BTW：
（1）I already have some secondary development experience on opentelemetry-java-instrumentation.
（2）This connection pool is used in many systems in China, and if I implement it, it will be a very beneficial complement to OTEL's ecology in China.

**Comment by mateuszrzeszutek** [comment]
Hey @xiongchun ,

Sure! What kind of instrumentation do you have in mind? The [connection pool metrcs](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-metrics.md#connection-pools), or something else?

**Comment by xiongchun** [comment]
@mateuszrzeszutek yes. Just connection pools mertric, like [hikaricp-3.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/hikaricp-3.0), DBCP , etc...

**Comment by breedx-splk** [comment]
> i want to instrument alibaba/druid database connection pool.

Does that mean that you are offering to build the instrumentation and submit a PR? If so, I can assign this issue to you.

**Comment by xiongchun** [comment]
@breedx-splk yes, i will do it. please assign to me, thanks.

**Comment by dpzain** [comment]
@xiongchun Hi  How is the development progress? I didn't find your PR.Can I participate in it？
