### ISSUE TITLE
OpenTelemetryAppender cannot be import

### ISSUE THREAD

**Issue by roychshao** [open-telemetry/opentelemetry-java-instrumentation#8959]
**Describe the bug**
I use log4j and want to send logs to otelcol, and I follow https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library to add package with maven like this
```xml
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-log4j-appender-2.17</artifactId>
            <version>1.28.0-alpha</version>
            <scope>runtime</scope>
        </dependency>

```
also have a log4j2.xml the same with https://github.com/open-telemetry/opentelemetry-java-examples/blob/main/log-appender/src/main/resources/log4j2.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" packages="io.opentelemetry.instrumentation.log4j.appender.v2_17">
    <Appenders>
        <Console name="ConsoleAppender" target="SYSTEM_OUT" follow="true">
            <PatternLayout pattern="log4j2: %d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
        </Console>
        <OpenTelemetry name="OpenTelemetryAppender" captureMapMessageAttributes="true" captureExperimentalAttributes="true"/>
    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="OpenTelemetryAppender" />
            <AppenderRef ref="ConsoleAppender" />
        </Root>
    </Loggers>
</Configuration>
```
However the line 1 is not worked, it cannot resolve it. 
The import io.opentelemetry.instrumentation cannot be resolved (Java 268435846)
```java
import io.opentelemetry.instrumentation.log4j.appender.v2_17.OpenTelemetryAppender;
import io.opentelemetry.sdk.OpenTelemetrySdk;

public class Application {

  public static void main(String[] args) {
    OpenTelemetrySdk openTelemetrySdk = // Configure OpenTelemetrySdk

    // Find OpenTelemetryAppender in log4j configuration and install openTelemetrySdk
    OpenTelemetryAppender.install(openTelemetrySdk);

    // ... proceed with application
  }
}
```

**Environment**
Compiler: OpenJDK 19.0.2
OS: Ubuntu 22.04 LTS

**Additional context**
Also I didn't see package io.opentelemetry.instrumentation in the java api doc
please help me to solve this problem, thanks!

**Comment by mateuszrzeszutek** [comment]
This question belongs in the instrumentation repo; moving.

Hey @roychshao ,

When you include the appender dependency with scope `runtime`, it means that it won't be available during compilation. Can you change the scope to `compile` (or remove it altogether, `compile` is the default scope in maven)?

**Comment by roychshao** [comment]
Thanks a lot, @mateuszrzeszutek ! 
It works! And I am sorry for my  carelessness.
