### ISSUE TITLE
Gather links to various presentations about this project

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#896]
A wiki page seems appropriately informal for this.

Basically looking for some place people can go to reuse ideas/slides when constructing their own presentations.

Here's a couple to get started:
* [initial design doc](https://docs.google.com/document/d/1Z5UWGk3d4vLIxx9TBfrU8g_L-J6sWIp0KheO03-GFGo)
  * not really a presentation, but useful diagram/content to copy-paste from
* https://trask.github.io/bytecode-instrumentation/#1
  * note: this refers to "muzzle" as "library shape matcher"

Please add any additional in comments here, and whether you think wiki is good place, or have other suggestions.

Thanks!

**Comment by anuraaga** [comment]
OTel Java Agent Tech Intro slides - https://docs.google.com/presentation/d/1S8UeTuWN74D1UOZBf0juqiXVawlJNmXg_J03hqLIAYc/edit#slide=id.p

I think a docs folder or a GitHub wiki are both good options for collecting these. In particular, design docs close to the code is nice for reference.

**Comment by trask** [comment]
Links to blog posts would be good too!

* https://medium.com/wwblog/auto-instrumentation-with-opentelemetry-3b096fdd068f

**Comment by iNikem** [comment]
+1 for GitHub wiki

**Comment by pizzaz93** [comment]
I added this page in the wiki [https://github.com/open-telemetry/opentelemetry-java-instrumentation/wiki/Presentation-Materials](https://github.com/open-telemetry/opentelemetry-java-instrumentation/wiki/Presentation-Materials) per the discussion in this issue.

**Comment by trask** [comment]
Closing, can revisit later if anyone has renewed interest.
