### ISSUE TITLE
Make the batch span processor of the OTel Spring starter configurable

### ISSUE THREAD

**Issue by jeanbisutti** [open-telemetry/opentelemetry-java-instrumentation#8962]
Make the batch span processor of the OTel Spring starter configurable with [existing OTel properties](https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#batch-span-processor).

**Comment by jeanbisutti** [comment]
@open-telemetry/java-instrumentation-approvers Could you please assign it to me?

**Comment by zeitlinger** [comment]
No, that's actually not done - depends on https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/10409
