### ISSUE TITLE
Remove scopes that only exist for internal agent log correlation

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#898]
There are many places that create scopes who's purpose is unclear, e.g.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/227bde87ce7aa8f9ae725f2daaf7b0c312117b7e/instrumentation/rabbitmq-2.7/src/main/java/io/opentelemetry/auto/instrumentation/rabbitmq/amqp/RabbitChannelInstrumentation.java#L270-L278

The original purpose of this was so that internal logging within the agent that occurred within this block of code could include the active span info, but that purpose is very hidden and not clear to anyone reading the code.

I suggest we remove them.

An alternative, if we want to keep them, would be to apply this pattern everywhere, and use a wrapper named something like `startLoggingScope` to make it's purpose clear.

**Comment by heyams** [comment]
Please assign it to me.  Thanks!

**Comment by trask** [comment]
👍 assigned, let's give 24 hours in case anyone wants to weigh in on this proposal

**Comment by iNikem** [comment]
@trask @heyams I am somewhat confused, if this solved or not?
