### ISSUE TITLE
I am not getting http.route with full path from IBM ODM

### ISSUE THREAD

**Issue by naga-nayudu** [open-telemetry/opentelemetry-java-instrumentation#8982]
**Used below annotations and container env variables.**

# deployment label
product_id: dp

# deployment annotations
prometheus.io/scrape: "true"
prometheus.io/port: "9464"
prometheus.io/path: "/actuator/prometheus"

# container port
ports:
- name: prometheus-port
  containerPort: 9464
  protocol: TCP

# container env vars
env:
- name: JAVA_TOOL_OPTIONS
  value: "-javaagent:/opt/otel/opentelemetry-javaagent.jar"
- name: OTEL_TRACES_EXPORTER
  value: "otlp"
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: "http://grafana-agent-traces.platform-monitoring.svc:4317"
- name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
  value: "http://grafana-agent-traces.platform-monitoring.svc:4317"
- name: OTEL_METRICS_EXPORTER
  value: "prometheus"

**Additional context**
I get below metrics from  http://localhost:9464/actuator/prometheus but without full path for http_route ("/DecisionService/ws/*"). Please can you help us to get **full path** instead of wildcard at the end.

http_server_duration_bucket{otel_scope_name="io.opentelemetry.liberty-20.0",otel_scope_version="1.26.0-alpha",http_method="GET",http_route="/DecisionService/ws/*",http_scheme="https",http_status_code="200",net_host_name="dp-company-digital.net",net_protocol_name="http",net_protocol_version="1.1",le="1000.0"} 1.0 1688965647832

http_server_duration_count{otel_scope_name="io.opentelemetry.liberty-20.0",otel_scope_version="1.26.0-alpha",http_method="GET",http_route="/DecisionService/ws/*",http_scheme="https",http_status_code="200",net_host_name="dp-pricing.company-digital.net",net_protocol_name="http",net_protocol_version="1.1"} 2.0 1688965647832

**Comment by mateuszrzeszutek** [comment]
Hey @naga-nayudu ,

What HTTP framework/library are you using? (e.g. spring)
Can you post a repro scenario?

**Comment by anwin-kuruvila** [comment]
@mateuszrzeszutek The application seems to be using a custom [HTTP server from IBM](https://www.ibm.com/docs/en/odm/8.0.1?topic=parts-http-server-odm)

**Comment by breedx-splk** [comment]
This might be intentional to avoid creating high cardinality. Please review the http metrics spec: https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-metrics.md
