### ISSUE TITLE
Document which methods we typically static import

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#900]
This will help new contributors know and follow existing style / convention.

**Comment by trask** [comment]
Or even better, if there's a way to automate this, e.g. via spotless?

**Comment by breedx-splk** [comment]
There are a large number of different static imports: https://gist.github.com/breedx-splk/2c5e1fff1d0d2337c4775d934a6ec7bb

Are we thinking that we want to draw some categories out of these?  Something like:
* mockito
* junit
* Collections helpers
* ElementMatchers
* immutable constants
* singleton instances
* tracer() methods that expose singletons

Any other obvious categories I'm missing?
Should this go in `style-guideline.md` ?

**Comment by trask** [comment]
yes, this sounds great 👍
