### ISSUE TITLE
InstrumentationConfig.get().getString("otel.service.name") return null on websphere 8.5.5.21

### ISSUE THREAD

**Issue by xiongchun** [open-telemetry/opentelemetry-java-instrumentation#9010]
i deploy otel-java-agent.jar on websphere  version 8.5.5.21. When i use the API InstrumentationConfig.get().getString("otel.service.name") to get the value, it return null. 
But I can use System.getProperty("otel.service.name") get the value.

anyone can give me some advice? Thanks a lot!

BTW: otel.service.name has been setted on WebSphere application servers -> (Server_Name) -> Server Infrastructure -> Java and process management -> Process definition -> Java virtual machine -> Custom properties.
AND can see the variable on running process through ps -ef | grep XXX.

**Comment by mateuszrzeszutek** [comment]
Hey @xiongchun ,

[`InstrumentationConfig`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-extension-api/src/main/java/io/opentelemetry/javaagent/bootstrap/internal/InstrumentationConfig.java#L27-L28) is an internal class, and we do not recommend (or support) using it outside of this project.

**Comment by xiongchun** [comment]
ok. thanks for ur answer. mybe have some relations with classloader.
