### ISSUE TITLE
Failed to export metrics with error message "data dropped due to high memory usage"

### ISSUE THREAD

**Issue by onfla11** [open-telemetry/opentelemetry-java-instrumentation#9019]
Failed to export metrics with error message "data dropped due to high memory usage"

**Steps to reproduce**
Micronaut java jdk17 based service, gradle dependencies are as below:
```
 api "io.opentelemetry:opentelemetry-sdk-extension-autoconfigure"
 api ('io.opentelemetry:opentelemetry-exporter-otlp') 
```
Configured metrics exporters and used simple custom metric with `LongCounter`, code snippet.
```
AutoConfiguredOpenTelemetrySdk sdk = AutoConfiguredOpenTelemetrySdk.builder().build();
sdk.getOpenTelemetrySdk().getMeter("TestMetric");
```
Environment Variable set is:
`OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: http://servicename.namespace.svc.cluster.local:4317`

**What did you expect to see?**
My expectation is periodically Prometheus should scrape the metrics and I should be able to query the prometheus metrics.

**What did you see instead?**
I see metrics get reported to Prometheus. However, initial 1-2 mins, I see following errors in my service.
```
Jul 21, 2023 11:27:14 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export metrics. Server responded with gRPC status code 2. Error message: data dropped due to high memory usage
```

**What version are you using?**
opentelemetry sdk version 1.19.0

**Environment**
Compiler: zulu17.42.20-sa-jre17.0.7-linux_musl_x64
OS: Alpine Linux v3.18 (Dockerimage)

**Additional context**

**Comment by trask** [comment]
hi @onfla11, this error message is coming from the opentelemetry collector, I'd suggest asking about this in the collector repo https://github.com/open-telemetry/opentelemetry-collector

**Comment by onfla11** [comment]
Thanks @trask I have reported issue in open telemety collector repo. https://github.com/open-telemetry/opentelemetry-collector/issues/8123#issue-1817540082
