### ISSUE TITLE
Use opentelemetry-java some question

### ISSUE THREAD

**Issue by CodingMakeWordBetter** [open-telemetry/opentelemetry-java-instrumentation#9027]
Hey,when i use opentelemetry-java agent in my springboot project. i find some singularity.
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/68694239/1da340aa-8d2f-4665-9ccf-301a846ea114)
as this picture. This is a alibaba trace tool to collect agent data to show. I find the request come to controller spend 32.8 second. This phenomenon is not often happen. it on some point of time.In Another time,It show normal.You can see next picture happen in the point of time.
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/68694239/27a20934-2464-42c7-b16d-544339d92f40)
At ordinary times, This Interface just spend 1~2ms.
Based on the current situation.I think it spend Most time on request start To Controller.Have you dealt with similar issues before?I would be very grateful if you could give me some advice.

**Comment by trask** [comment]
hi @CodingMakeWordBetter! if it's only the first request that is slow, it could be startup overhead, otherwise I'd suggest using JFR to profile and that may show you more details about why specific requests are taking a long time

**Comment by CodingMakeWordBetter** [comment]
I am honored that you can answer my question.I would like to know where the start time of OpenTelemetry Java recording starts. I speculate that it started recording when tasks were assigned to Tomcat, right？

**Comment by CodingMakeWordBetter** [comment]
By the way, at that time, the indicators displayed by jvm monitoring and server monitoring were normal, which made me so confused about this issue

**Comment by trask** [comment]
hi @CodingMakeWordBetter, we would probably need a standalone repro that we could use in order to investigate this issue further
