### ISSUE TITLE
Peer Service Mapping per host, name and base-path

### ISSUE THREAD

**Issue by mmorel-35** [open-telemetry/opentelemetry-java-instrumentation#9047]
**Is your feature request related to a problem? Please describe.**
On a service if I have
- service A on localhost:8001
- service B-V1 on localhost:8002/api/v1
- service B-V2 on localhost:8002/api/v2
- service C on mycompany.org

The [`otel.instrumentation.common.peer-service-mapping`](https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#peer-service-name) property is unable to map the services correctly

**Describe the solution you'd like**
The first thing is that I would to be able to map a service based on host and port.
And if possible also per base path so I can provide something like

```properties
otel.instrumentation.common.peer-service-mapping=localhost:8001=service-a,localhost:8002/api/v1=service-b-v1,localhost:8002/api/v2=service-b-v2,mycompany.org=service-c
```

**Comment by trask** [comment]
hi @mmorel-35! this makes sense, we probably don't have time to implement ourselves but would welcome a contribution, let us know if you have any questions
