### ISSUE TITLE
Feature to provide getting header in the IdGenerator implementation class

### ISSUE THREAD

**Issue by bajrangprasad01** [open-telemetry/opentelemetry-java-instrumentation#9048]
**Not able to fetch or get the request header on the implementation class of IdGenerator**
I am trying to create a custom IdGenerator implementation class where I can manipulate the tracing id and I want to put tracing id as one of the request header but I am unable to get it from the Context class.

**Provide a way to get request object from the context**
If in the Context class someone will get a way to access the request then they can able to get the header or other component and make use of it according to there needs.

When I searched in the internet I found there is something like from which we can get the request header from the context but currently it is not present in latest version.

Thanks in advance for the help.

**Comment by trask** [comment]
I think this can be accomplished with a custom context propagator, have you explored that option already?

**Comment by bajrangprasad01** [comment]
> have you explored that option already?
Yes I am already trying to write a custom context propagator in which I need to inject the request object but I don't know how will I get the request object in the propagator.

**Comment by mateuszrzeszutek** [comment]
The `carrier` and the `TextMapSetter` and `TextMapGetter` are abstractions for outgoing/incoming requests; you can use the to inject/extract span context from the HTTP headers.

**Comment by mateuszrzeszutek** [comment]
> I just need help to fetch the request object or HttpServlet Object in the IdGenerator implementation class

You cannot do that: you can only access the headers. The API is purposefully designed to be as generic as possible to fit all 
kids of instrumentations.

**Comment by bajrangprasad01** [comment]
`you can only access the headers` How can I able to access only Header that is also good to go for me.

**Comment by trask** [comment]
> How can I able to access only Header that is also good to go for me.

`TextMapGetter.get("<header name>")`
