### ISSUE TITLE
Nightly build report should link to the action run

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#906]
Presume it'd be relatively easy to fill the issue with a link to the run itself.

**Comment by iNikem** [comment]
That's the problem: I have not found the way to link to a specific run. But probably just link to a list of job runs will be enough...

**Comment by anuraaga** [comment]
I believe we can use `{{ github.run_id }}` to construct the URL

https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

**Comment by iNikem** [comment]
Why did I thought it is not good for us? :) Ok, will do.

**Comment by iNikem** [comment]
Fixed by #1943
