### ISSUE TITLE
OpenTelemetry with java agent stops sending logs to Elastic APM

### ISSUE THREAD

**Issue by yasminfeitosa** [open-telemetry/opentelemetry-java-instrumentation#9069]
**Describe the bug**
I'm facing an issue with my Kotlin-Spring Boot application. It's using OpenTelemetry (v1.28.0) with the Java Agent to send logs to Elastic APM (v8.8.1).
The problem is that after a deploy, the logs look good, but after a while, the app stops sending logs to Elastic APM. Sometimes they come back on their own, but other times, we need to do another deploy to fix it.
Has anyone dealt with this before? Any ideas on what could be causing it or where to start investigating?

**Steps to reproduce**
I don't know how to reproduce this error.

**What did you expect to see?**
All logs from my app.

**What did you see instead?**
No logs after a while.

**What version are you using?**
OpenTelemetry v1.28.0
Elastic v8.8.1

cc: @heitorneves91

**Comment by mateuszrzeszutek** [comment]
Hey @yasminfeitosa ,

Please provide more details about your setup; we can barely suggest anything with this little information.
Are you using the collector? Or sending logs directly to Elastic? Can you enable debug logging in the agent (and collector) and see whether there's anything about the logs exporter/pipeline? The OTLP exporters emit [metrics](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/common/src/main/java/io/opentelemetry/exporter/internal/ExporterMetrics.java), can you check whether these point out to log records being dropped by the agent?

**Comment by yasminfeitosa** [comment]
Hey @mateuszrzeszutek, thanks for the reply!

Here are some more informations:

Our setup is actually very simple from the application side. We use Elastic Cloud and simply point the otel javaagent there.

These are the interesting parts of the Dockerfile:
```
RUN wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.24.0/opentelemetry-javaagent.jar --output-document /lib/opentelemetry-javaagent-all.jar
RUN mv /lib/opentelemetry-javaagent-all.jar opentelemetry-javaagent-all.jar
ENTRYPOINT [ "java", "-Djava.security.egd=file:/dev/./urandom", "-javaagent:opentelemetry-javaagent-all.jar", "-jar", "app.jar" ]
```
Those are the envvars:
```
OTEL_TRACES_EXPORTER=otlp
OTEL_METRICS_EXPORTER=otlp
OTEL_LOGS_EXPORTER=otlp
OTEL_EXPORTER_OTLP_ENDPOINT="[https://XXXXXXXX.apm.us-east-2.aws.elastic-cloud.com:443](https://xxxxxxxx.apm.us-east-2.aws.elastic-cloud.com/)"
OTEL_EXPORTER_OTLP_HEADERS="Authorization=Bearer XXXXXXX"
OTEL_RESOURCE_ATTRIBUTES="service.name=core-api,deployment.environment=prod"

OTEL_TRACES_SAMPLER=always_on
```

**Comment by breedx-splk** [comment]
Is the syntax on `OTEL_EXPORTER_OTLP_ENDPOINT` correct? It looks like maybe some markdown was pasted.

**Comment by yasminfeitosa** [comment]
It was! Just fixed it, thanks for the reply.

**Comment by mateuszrzeszutek** [comment]
Hey @yasminfeitosa ,

If the javaagent does not print out any errors/warnings about the exporters, we can't really help you here. Please contact Elastic, the issue might be on their side.

**Comment by yasminfeitosa** [comment]
Ok! 
Thanks for the feedback @mateuszrzeszutek !

**Comment by mateuszrzeszutek** [comment]
I'll close this issue for now. If you end up discovering that this issue lies with the javaagent, please reopen it or open a new one.
