### ISSUE TITLE
Error with JAXWS - Undefined property javax.xml.ws.servlet.request

### ISSUE THREAD

**Issue by josecoelho96** [open-telemetry/opentelemetry-java-instrumentation#9070]
**Describe the bug**
When a SOAP request is received by our server, the response is always a HTTP 500 with the following message:
`<?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Server</faultcode><faultstring>Undefined property javax.xml.ws.servlet.request</faultstring></S:Fault></S:Body></S:Envelope>`

It only happens with the OpenTelemetry javaagent flag on. Otherwise we handle the request as expected.

**Steps to reproduce**
Just running the application with the javaagent connected reproduces the problem.

**What did you expect to see?**
A 200 OK HTTP response with some expected payload for success.

**What did you see instead?**
A 500 HTTP response with the response body as seen above.

**What version are you using?**
1.28.0 (also happened in 1.27.0)

**Environment**
Compiler: OpenJDK 11.0.9.1
OS: Debian 11

Runtime (if different from JDK above): OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1deb11u1)
OS (if different from OS compiled on): Debian 11

**Additional context**
It's not possible to provide a sample application, but I'm willing to try and debug/provide any additional context.
I decided to do some debugging on my own, and found something that I think might be helpful. 

The problem seems to happen during a call to `MetroServerSpanNaming#updateServerSpanName`:
```java
    HttpServletRequest request = (HttpServletRequest) packet.get(MessageContext.SERVLET_REQUEST);
```  

Could this be a configuration problem?

**Comment by mateuszrzeszutek** [comment]
Hey @josecoelho96 ,

I fixed that in #9075
In the meantime, you can temporarily disable the metro instrumentation (`-Dotel.instrumentation.metro.enabled=false`) to fix your issue.

**Comment by josecoelho96** [comment]
Thanks for the quick fix! Do you want me to test a snapshot version to make sure it’s fixed? (I saw that you weren’t able to test it in the pull request)

**Comment by mateuszrzeszutek** [comment]
That would be great! 🙏 
I just merged the PR, it'll probably take a while to publish the snapshot. If you could test it out in a few hours (or tomorrow) I'd really appreciate that.

**Comment by josecoelho96** [comment]
I downloaded the last snapshot available and couldn't reproduce the problem. The trace started to be visible.
Seems to be fixed, thanks for the quick response!
