### ISSUE TITLE
Issue importing and using logback appender

### ISSUE THREAD

**Issue by guadalupe-duolingo** [open-telemetry/opentelemetry-java-instrumentation#9077]
**Describe the bug**
I'm getting an unresolved reference error when adding this line 
`import io.opentelemetry.instrumentation.logback.OpenTelemetryAppender;`

**Steps to reproduce**
I added this line to my build.gradle file
`implementation group: "io.opentelemetry.instrumentation", name: "opentelemetry-logback-appender", version: '1.28.0-alpha'`

**What did you expect to see?**
No error

**What did you see instead?**
Unresolved reference error when trying to import logback appender

**What version are you using?**
1.28.0-alpha for the logback appender

**Comment by mateuszrzeszutek** [comment]
The class you're trying to import is in different package: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/65d4c4bf4c58525dc21dce82de6b6efa2dbc70ab/instrumentation/logback/logback-appender-1.0/library/src/main/java/io/opentelemetry/instrumentation/logback/appender/v1_0/OpenTelemetryAppender.java#L6
