### ISSUE TITLE
Span not end if request canceled in webflux application

### ISSUE THREAD

**Issue by darcydai** [open-telemetry/opentelemetry-java-instrumentation#9116]
**Describe the bug**
This issue can be reliably reproduced. In a WebFlux application, when using WebClient to request services from downstream, if the downstream service does not respond for a long time, the browser will disconnect from the WebFlux service. It has been found that the first span (netty-4.1) in the trace is missing. I suspect a bug where the agent under the WebFlux application does not end the span when it receives a cancel signal.

**Steps to reproduce**
There are two web applications both Webflux and Servlet.

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/20854418/20d72129-81dd-4e4c-bd32-127385d19a03)

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/20854418/8787d8d0-04b9-4ee7-a9e1-0650b69ebc5a)

the Webflux application will send a request to the Servlet application. the normal trace status is as follows image.

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/20854418/2ca86527-def4-4924-acdc-344223354bd5)

If sleeps for a long time in downstream service（as the comment in the code）, use `curl` to send a request to the first web flux application， then interrupt the request. the netty span was missed.
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/20854418/c0153664-47df-432c-8c7a-48ea59823c78)

**What version are you using?**
1.16.*,  and the latest has this problem also

**Environment**
mac *  jdk 8

**Additional context**
the missed span from netty instrumentation
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/20854418/50ee3405-c528-466f-bd0c-531677f860c2)

**Comment by mateuszrzeszutek** [comment]
Hey @darcydai ,
What javaagent version are you using? If the issue can be reliably reproduced, please include a repro scenario.

**Comment by darcydai** [comment]
> 
yes 


> Hey @darcydai , What javaagent version are you using? If the issue can be reliably reproduced, please include a repro scenario.
I have already supplemented the relevant information.

**Comment by darcydai** [comment]
> Hey @darcydai , What javaagent version are you using? If the issue can be reliably reproduced, please include a repro scenario.

I have already supplemented the relevant information.

**Comment by darcydai** [comment]
The web client span  status should not ok
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/20854418/bf93c2c3-9e96-4756-980f-289fbc3c8f2d)

**Comment by laurit** [comment]
@darcydai Having a sample app that allows reproducing the issue with minimal effort greatly increases the chances that someone will attempt to fix this. Unless you plan to fix it yourself do consider providing a reproducer.

**Comment by darcydai** [comment]
> @darcydai Having a sample app that allows reproducing the issue with minimal effort greatly increases the chances that someone will attempt to fix this. Unless you plan to fix it yourself do consider providing a reproducer.
https://github.com/darcydai/otel-test-application/tree/main and see README

**Comment by darcydai** [comment]
> > @darcydai Having a sample app that allows reproducing the issue with minimal effort greatly increases the chances that someone will attempt to fix this. Unless you plan to fix it yourself do consider providing a reproducer.
@laurit 
https://github.com/darcydai/otel-test-application/tree/main and see README
