### ISSUE TITLE
Follow up tasks from PR #893

### ISSUE THREAD

**Issue by heyams** [open-telemetry/opentelemetry-java-instrumentation#912]
- [x] // Copy of HttpServerDecorator url handling (extract a method) in httpclienttracer
- [x] make spanNameForRequest protected in HttpClientTracer.java
- [x] update the package using tracer not decorator
- [x] clean up common code between client and server tracers
- [x] consider a new class for static methods extracted from BaseTracer
~~- [x] remove port and url in UrlInstrumentation. this requires updating tests. #1039.~~
- [x] rename and update unit tests under :instrumentation:agent-bootstrap:test
- [x] refactor startSpan(String spanName, Kind spanKind) in the BaseTracer.java
add startSpan(spanName) to clientTracer => Kind.CLIENT.
- [x] delete httpclientdecorator

**Comment by trask** [comment]
After "add ClientDecorator.CONTEXT_CLIENT_SPAN_KEY to the context inside startScope", I think we can remove

```
      // WARNING: this might be a chain...so we only have to trace the first in the chain.
      boolean isRootClientHandler = null == request.getProperties().get(CONTEXT_ATTRIBUTE);	      boolean isRootClientHandler = null == request.getProperties().get(CONTEXT_ATTRIBUTE);
      if (isRootClientHandler) {
```

from `JaxRsClientV1Instrumentation`

**Comment by trask** [comment]
@iNikem thx :thumbsup:
