### ISSUE TITLE
Does OpenTelemetry support auto instrumentation for https://spring.io/projects/spring-cloud-gateway?

### ISSUE THREAD

**Issue by rajankamdi0706** [open-telemetry/opentelemetry-java-instrumentation#9121]
**Is your feature request related to a problem? Please describe.**
Does OpenTelemetry support auto instrumentation for https://spring.io/projects/spring-cloud-gateway.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by trask** [comment]
hi @rajankamdi0706!

check out https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md#libraries--frameworks

while spring cloud gateway isn't listed, I believe the underlying spring libraries used by spring cloud gateway are

**Comment by rajankamdi0706** [comment]
Hi, @trask - Thanks for the prompt revert. I have gone through supported libraries. 
Do you mean Spring Cloud Gateway instrumentation would work as the underlying libraries it uses are spring libraries?
