### ISSUE TITLE
Annotations to inject and extract data with auto-instrumentation

### ISSUE THREAD

**Issue by SimoneGiusso** [open-telemetry/opentelemetry-java-instrumentation#9128]
**Is your feature request related to a problem? Please describe.**

- Tell Auto-instrumentation to add attribute to current active span
- Tell Auto-instrumentation to extract attribute from current span

**Describe the solution you'd like**
```
    // when calling this method the parameter1 and parameter2 are added to the current span
    @WithCurrentSpan
    public void myMethod(@SpanAttribute("parameter1") String parameter1,
        @SpanAttribute("parameter2") long parameter2) {
        <...>
    }

    // when calling this method the parameter1 is returned
    @WithCurrentSpan
    public String myMethod(@SpanAttribute("parameter1") String parameter1) {
        return paramter1;
    }
```

**Describe alternatives you've considered**
Use manual instrumentation.

**Comment by mateuszrzeszutek** [comment]
ping @SimoneGiusso 

> can you clarify, maybe with some psuedo code, how you would do this today with the OpenTelemetry API?

**Comment by laurit** [comment]
@SimoneGiusso opentelemetry also has baggage api.
```java
// on client
Baggage baggage = Baggage.builder().put("key", "value").build();
try (Scope ignore = baggage.makeCurrent()) {
  // call the server      
}

// on server
String value = Baggage.current().getEntryValue("key");
```

**Comment by mateuszrzeszutek** [comment]
@SimoneGiusso as discussed in https://github.com/open-telemetry/opentelemetry-java/discussions/5651, OTel baggage API is simply different from OpenTracing. It's not possible to 1:1 map OpenTracing to OTel, you have to restructure your code.

**Comment by SimoneGiusso** [comment]
> @SimoneGiusso as discussed in https://github.com/open-telemetry/opentelemetry-java/discussions/5651, OTel baggage API is simply different from OpenTracing. It's not possible to 1:1 map OpenTracing to OTel, you have to restructure your code.

I'll try to restructure the code since where I set the baggage I don't make the call to the server.
