### ISSUE TITLE
@WithSpan annotation not functioning with 0.7.0

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java-instrumentation#913]
A little bird told me that the shading might need to be updated for the new packaging of the extensions code.

**Comment by iNikem** [comment]
I will be **very** interested to know, why our test does not show this 🤔

**Comment by anuraaga** [comment]
Word on the street is it's because our unit tests don't have the runtime otel shading. Or something like that :) Smoke tests do and we don't have the annotation there.

A random idea I had recently for unrelated reasons is we could probably migrate our tests to use an actual TestAgent instead of runtime bytebuddy injection. This would be similar to how I moved the runtime bootstrap injection into Gradle - doing similar for agent would let tests match production even more closely.

**Comment by trask** [comment]
> we could probably migrate our tests to use an actual TestAgent instead of runtime bytebuddy injection

a potential downside of this is the debugging experience may require a bit more effort if launching a remote JVM

**Comment by trask** [comment]
> > we could probably migrate our tests to use an actual TestAgent instead of runtime bytebuddy injection
> 
> a potential downside of this is the debugging experience may require a bit more effort if launching a remote JVM

oh, i think i understand what you were suggesting now. adding `-javaagent` to the gradle test JVM itself does sound very interesting.

**Comment by iNikem** [comment]
Our tests will have to change significantly in that case. There will be much more spans captured by them when every test will have all our instrumentations applied. But it still may be a good idea.

**Comment by trask** [comment]
I think(?) the idea is (or could be?) that we wouldn't use the full opentelemetry-javaagent, but some small delegating javaagent jar that would honor the module's existing classpath somehow.

For example, Glowroot runs tests in both "local" mode (similar to bytebuddy attach, but using disposable ClassLoader) which is nice for debugging, and "javaagent" mode which works similar to this idea, but launches separate JVM from inside the test which makes debugging less friendly (and why my comment above).

This idea sounds like it could be best of both.

**Comment by iNikem** [comment]
Do you mean that instead of current per-module bootstrap jar we will package per-module javaagent, which has only those instrumentation that are on the classpath of this module? It may be very interesting idea indeed! :)

**Comment by anuraaga** [comment]
@iNikem Yup that's exactly what I'm thinking :)

**Comment by trask** [comment]
So we don't lose this idea once this issue closes out, created #936

**Comment by rjean-gilles** [comment]
Would anybody be able to tell me if the @WithSpan works for earlier versions, in particular 0.6.0? Thanks.

**Comment by trask** [comment]
I think it was broken in `0.6.0` also. Should work in `0.5.0`, or you can try latest SNAPSHOT https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/CONTRIBUTING.md#snapshot-builds

**Comment by trask** [comment]
hm, latest SNAPSHOT can be tricky, because it may only interoperate with OpenTelemetry API SNAPSHOT

**Comment by rjean-gilles** [comment]
Thanks for looking it up.
I guess I'll keep creating the spans using my own helpers then.
