### ISSUE TITLE
TraceId Can't be connected when using RocketMQ sends batch messages

### ISSUE THREAD

**Issue by catkkt** [open-telemetry/opentelemetry-java-instrumentation#9141]
I'm attempting to test how to convey in producer and consumer by using RocketMQ. and I send batch messages in producer application, then observing consumption situation in consumer application. But I find the traceId is diffrent in producer and consumer. It's meaning that otel can't connect them together？ I'm looking forward  to a solution, thanks.
(ps: I use 1.25.X version.)
As the following:
producer's traceId:
![send](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/132581549/e0a90e93-c8eb-42d8-8cf6-53f41b6cc2e7)

consumer's traceId:
![process](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/132581549/51d6a718-b83e-4202-be54-cc6dbc3e328b)

**Comment by aaron-ai** [comment]
Well, could you provide more information about the SDK version you used? The gRPC/Protobuf-based SDK has not support the batch message sending yet...

**Comment by catkkt** [comment]
> Well, could you provide more information about the SDK version you used? The gRPC/Protobuf-based SDK has not support the batch message sending yet...

I used opentelemetry-javaagent-1.25.1.jar.

**Comment by aaron-ai** [comment]
@catkkt I means the version of RocketMQ client you used...

**Comment by catkkt** [comment]
> @catkkt I mean the version of RocketMQ client you used...

Ok. It's org.apache.rocketmq:rocketmq-client:4.4.0.

**Comment by aaron-ai** [comment]
cc @addname

**Comment by laurit** [comment]
As far as I can tell batch messages use span links to link back to the producer from the consumer. These span links are not visible in the logging exporter output. To see the span links either send the traces to a backend that supports span links, such as jaeger, or send the traces to the collector and use a logging exporter in traces pipeline.

**Comment by catkkt** [comment]
> As far as I can tell batch messages use span links to link back to the producer from the consumer. These span links are not visible in the logging exporter output. To see the span links either send the traces to a backend that supports span links, such as jaeger, or send the traces to the collector and use a logging exporter in traces pipeline.

I try it by using jaeger,but they also cannot be linked. Please refer the screenshot.

![batch messages](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/132581549/80dcacd4-4d4a-40cf-8472-12b75b214f6f)

**Comment by laurit** [comment]
Are you sure that the span links are visible from that view? See https://stackoverflow.com/questions/70263046/can-opentelemetry-instrumentation-be-used-to-track-kafka-span-propagation-in-any for a sample how span link is displayed in jaeger (follows_from type reference).

**Comment by catkkt** [comment]
> Are you sure that the span links are visible from that view? See https://stackoverflow.com/questions/70263046/can-opentelemetry-instrumentation-be-used-to-track-kafka-span-propagation-in-any for a sample how span link is displayed in jaeger (follows_from type reference).

What I need is making the producer( "test send" span) and the consumer("test process" span) be linked. And It seems that the "FOLLOWS_FROM" and "CHILD_OF" of "test process" are both pointed to "multi_sources receive", then they cannoot be linked to "test send".  Or can't this be achieved?
The following is expanding all span:

![send](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/132581549/c96a4183-36ce-43ec-aa25-6724b2eeb3ba)
![receive](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/132581549/478faac0-fac6-4a76-a3db-8a51136d893c)

**Comment by laurit** [comment]
Having `child_of` and `follows_from` point to the same span is strange. I guess it could happen if the message didn't contain tracing headers. Could you provide a minimal application that reproduces this issue.

**Comment by catkkt** [comment]
@laurit
Hi, I cannot upload the application to this issue, Can you push demos from my  repository--rocketmq?

**Comment by laurit** [comment]
@catkkt a repository that could be cloned would be best

**Comment by catkkt** [comment]
> @catkkt a repository that could be cloned would be best

Ok. Now you can pull it.

**Comment by mateuszrzeszutek** [comment]
Linking the repro: https://github.com/catkkt/rocketmq

**Comment by laurit** [comment]
@catkkt I ran the sample app you provided and couldn't reproduce the issue. For me `CHILD_OF` and `FOLLOWS_FROM` point to different spans as expected.
