### ISSUE TITLE
Breaks Kafka configuration when `METRIC_REPORTER_CLASSES_CONFIG` is a `List`

### ISSUE THREAD

**Issue by davsheld-te** [open-telemetry/opentelemetry-java-instrumentation#9143]
Kafka supports the property METRIC_REPORTER_CLASSES_CONFIG as being either a `String` - comma separated list of class names, or a List of String class names, or a List of Class objects.

If it's a list then initialisation will fail as open telementry will just treat it like a string. E.g.
```
  props.put("metric.reporters", Lists.of(MyClass.class));
```
Open telemetry will change that to the string `[class com.example.MyClass], io.opentelemetry.javaagent.shaded.instrumentation.kafka.internal.OpenTelemetryMetricsReporter`, which means kafka tries to load a class with the invalid name of `[class com.example.MyClass]`.

The current code in  [KafkaSingletons.java](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/03664f2d6b5eb268879261c68eb7453d343c1c5c/instrumentation/kafka/kafka-clients/kafka-clients-0.11/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/kafkaclients/v0_11/KafkaSingletons.java#L79-L93) acknowledges it might not be a String, but doesn't deal with the other case.

It might be worth converting other formats into the expected format first:

```
        (class1, class2) -> {
          // class1 can be List<String>, List<Class<?>> or String
          if (class1 instanceof List<?>) {
            class1 = ((List<?>)class1).stream().map(klass -> {
              if (klass instanceof Class<?>) return klass.getName();
              else return String.valueOf(klass);
            }).collect(Collectors.joining(","));
          }
          if (class1 instanceof String) {
            String className1 = (String) class1;
            if (className1.isEmpty()) {
              return class2;
            }
            if (METRIC_REPORTER_PRESENT_PATTERN.matcher(className1).find()) {
              return class1;
            }
          }
          return class1 + "," + class2; // <- implicit toString() on class1 which can be a List
```
Or handling each case separately, and adding the metrics class without changing the types.

**Comment by trask** [comment]
hi @davsheld-te! this sounds like a good addition if you are able to send a PR for it that would be great
