### ISSUE TITLE
Capture servlet request parameters，Add wildcards * Capture all request parameters function

### ISSUE THREAD

**Issue by zhangjiabin1010** [open-telemetry/opentelemetry-java-instrumentation#9183]
**Is your feature request related to a problem? Please describe.**
Capture servlet request parameters function
Currently capture the specified parameters through otel.instrumentation.servlet.experimental.capture-request-parameters=parameter
need to be added to automatically capture all parameters of the request

**Describe the solution you'd like**
otel.instrumentation.servlet.experimental.capture-request-parameters=*
 Add wildcards automatically capture all parameters

**Describe alternatives you've considered**
Integrate this functionality into javaagent

**Comment by breedx-splk** [comment]
Hi @zhangjiabin1010 -- please take a look at some of the discussion in #9189 and understand that there has been considerable hesitation to add a feature like this. If this is a real need on your end, perhaps you can leverage some of the work in #9189 to implement your own extension.

**Comment by zhangjiabin1010** [comment]
> 你好@zhangjiabin1010-- 请看一下#9189中的一些讨论，并了解添加这样的功能一直存在相当大的犹豫。如果您确实需要这样做，也许您可​​以利用#9189中的一些工作来实现您自己的扩展。

Thank you very much for your efforts on this, I have achieved this requirement through extension.

**Comment by JessHolle** [comment]
Hmm... seems like this would be a *really* commonly desired feature.

And it seems like the solution to avoiding including something sensitive is likely a blacklist of parameters not to include.

Same to a lesser extent for HTTP request headers -- seems like you'd want to include all but the Authorization header in many cases.
