### ISSUE TITLE
Investigate and either fix or better document tests that require independent classloaders

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#919]
Some of our tests will not pass due to classload ordering reasons if they are run with other ones, so we separate a classloader for them. It's better if we can sort out ordering issues, or better document what could cause these in the first place to provide reference.

**Comment by anuraaga** [comment]
I think this happens for tests which use a `static` block to update config - multiple classes can get loaded and have their static blocks run before the tests get to. Will think if there's a faster solution for these than separating classloaders but luckily there aren't so many of them.

**Comment by trask** [comment]
I believe this was resolved by #1643
