### ISSUE TITLE
Allow independent instrumentation library injection

### ISSUE THREAD

**Issue by onespacer** [open-telemetry/opentelemetry-java-instrumentation#9197]
**Is your feature request related to a problem? Please describe.**
Currently to capture instrumentation for any custom/new library, have to add the module in instrumentation module of this project. Is there a way to create the instrumentation library/javaagent independently and pass as a parameter to the javaagent?  

**Describe the solution you'd like**
Allow creating and passing custom instrumentation library as a parameter to java agent.

**Describe alternatives you've considered**
Manual Instrumentation directly in the target library.

**Additional context**
None

**Comment by laurit** [comment]
You can also write an agent extension https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension that you can distribute independently of the agent or embed inside the agent or build a custom distro https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/distro

**Comment by onespacer** [comment]
> You can also write an agent extension https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension that you can distribute independently of the agent or embed inside the agent or build a custom distro https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/distro

Thanks for responding. Can extension behaves like another 3rd party instrumentation module with javaagent?

**Comment by onespacer** [comment]
> hi @onespacer!
> 
> the Java agent interoperates with manual instrumentation, so you should be able to instrument the library normally, and the Java agent will pick that up

I would not want to instrument manually, want to use javaagent, for that I have to build my own module (not a common third party library and proprietary).

**Comment by trask** [comment]
> > You can also write an agent extension https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/extension that you can distribute independently of the agent or embed inside the agent or build a custom distro https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/examples/distro
> 
> Thanks for responding. Can extension behaves like another 3rd party instrumentation module with javaagent?

yes

**Comment by laurit** [comment]
please reopen if you have more questions
