### ISSUE TITLE
Auto-instrumentation lite

### ISSUE THREAD

**Issue by onespacer** [open-telemetry/opentelemetry-java-instrumentation#9198]
**Is your feature request related to a problem? Please describe.**
Current version of agent jar is too big to be used among multiple processes across multiple servers. (redundancies). (long build time)

**Describe the solution you'd like**
A lite version of auto instrumentation that comes with just a selected or none third party libraries. This would make the agent jar super lite than the current one. Allows you to pass additional instrumentation modules or jar as param

**Describe alternatives you've considered**
Manually build the agent jar locally and remove all unwanted third party dependencies. 

**Additional context**
None

**Comment by breedx-splk** [comment]
@onespacer Interesting idea, but I'm curious to hear more about your environment. What is your runtime like such that a 17MB javaagent is "too big"?

I think that most users actually prefer dealing with a single jar and are ok with the size. While I could see a more modular "lite" agent jar being useful in some resource constrained environments (embedded?), the effort required for users to go track down coordinates and jar artifacts for a buffet-style bring-your-own instrumentation is too much for most users. Do you have any ideas on how to make that a better user experience?

**Comment by onespacer** [comment]
@breedx-splk We have been working in shared environment with tight resource constraints. 17MB is not too big, but there are processes which are monolith and are already in the process of redesigning their system due to resource crunches, meanwhile we would want to add support for dtrace.

If most users are ok with the size, there could be an option of having two jars (uber/lite) with and without third party libraries. Or three jars uber, lite and all third party libs into another jar (probably used via extension)

**Comment by laurit** [comment]
@onespacer when you say "without third party libraries" which libraries do you mean? Have you investigated how much dropping these would reduce the agent size?

**Comment by onespacer** [comment]
@laurit - third party instrumentation libs like kafka/rabbitmq/aws etc..  I dont see a lot of size optimization (~12.5MB without third party instrumentation libs), however, the build is super fast. The build/assemble time is about 10/20 seconds without libs and with libs its over 10 mins (still counting).

**Comment by trask** [comment]
> the build is super fast

I'm not sure I follow why this is a reason to publish a "lite" jar?

**Comment by onespacer** [comment]
The size of the jar after adding all third party libs, does not make make any significant difference here. So I would not call it "lite" jar anymore and I will use it as is at the moment. However, I still feel the third party instrumentations and the tracing core should be separate. If having that choice, I would have chosen the jar without libs. I wish we could allow pick and choose which all libs we want to add part of the agent. (and not as a config param for javaagent)

**Comment by trask** [comment]
> I wish we could allow pick and choose which all libs we want to add part of the agent. (and not as a config param for javaagent)

can you expand on your reasons why? thx
