### ISSUE TITLE
Subscribe to Bean notifications

### ISSUE THREAD

**Issue by dcsstinger** [open-telemetry/opentelemetry-java-instrumentation#9206]
**Is your feature request related to a problem? Please describe.**
It is possible to create a custom rule to subscribe to the notifications of a particular MBean?

**Describe the solution you'd like**
For now, I can create as many counters or gauges to monitor my MBeans using a custom yaml file and it works great.
However, I would like to subscribe to the notifications of some MBeans to be able to extract more complex information in the form of text messages, not only counters.

**Comment by trask** [comment]
I don't quite follow how this is related to backend monitoring capabilities?
