### ISSUE TITLE
How to access files under java/src/main/resources in OTEL javaagent?

### ISSUE THREAD

**Issue by Anyuoo** [open-telemetry/opentelemetry-java-instrumentation#9232]
I am developing a custom configuration with SPI and trying to access files under java/src/main/resources in  javaagent.  Can anyone help me with how to access these files in a javaagent? Thank you!

**Comment by Anyuoo** [comment]
I am building an extension and I want to know how to access these files within the application.

**Comment by Anyuoo** [comment]
I encountered the second scenario where, in custom javaagent extension, I directly use ClassLoader.getResource or ClassLoader.getResourceAsStream to access the extension's classpath, rather than the application's classpath. Is there any way to access resources under the application's classpath in a javaagent extension?

**Comment by mateuszrzeszutek** [comment]
> Is there any way to access resources under the application's classpath in a javaagent extension?

Realistically - no.
If you make some assumptions about the instrumented application (e.g. it's a simple spring boot app) then you _could_ implement a particular scenario, but it is not possible to do that in general for any Java app.

**Comment by Anyuoo** [comment]
Okay, thank you @mateuszrzeszutek @laurit . I still have some doubts and questions. If I cannot access the application.yaml file in the agent extension for the instrumented spring boot application, how does this configuration file work in the agent according to the official documentation?
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/37858147/be801c32-6f25-4d84-857b-02ed6eeeae3d)

**Comment by trask** [comment]
`otel.javaagent.configuration-file` is a path on the filesystem, as opposed to a resource on the application class path

**Comment by Anyuoo** [comment]
Okay, I understand what to do now. Thank you @trask .
