### ISSUE TITLE
Rename io.opentelemetry.auto.bootstrap.AgentBootstrap

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#924]
Updated javaagent-jar-components.md in #884 makes it seem strange that this class named "bootstrap" is the 1 class that is not in the bootstrap class loader. It does "bootstrap" the agent, but I think better to rename and avoid this confusion. Since this is the `Premain-Class`, we should probably do this on the sooner side if we are going to do it.

As far as what to rename it to.... maybe `io.opentelemetry.auto.Agent`?

**Comment by anuraaga** [comment]
Agent or OpenTelemetryAgent SGTM

**Comment by dengliming** [comment]
OpenTelemetryAgent +1
