### ISSUE TITLE
Add gradle retry to all sporadic failing tests

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#925]
I propose that we:

* add the new gradle retry (#908) to all ~sporadic failing~ tests (EDIT: see https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/925#issuecomment-671747602)
* close all issues labeled as `sporadic test failure`
* open an issue to implement something that will give us an aggregated view into flaky tests, e.g. a report of all flaky tests across all CI runs over the past month [and this issue can be tagged `after-ga`]

**Comment by anuraaga** [comment]
SGTM. I sent a mail with Gradle's form to see if there is any possibility of using Gradle Enterprise for the flaky test console, will report if I hear back!

**Comment by trask** [comment]
Blocked on #926

**Comment by iNikem** [comment]
@anuraaga is it your doing? https://scans.gradle.com/s/vh7xffiag6wfi/tests/:instrumentation:play:play-2.6:test/server.PlayServerTest/test%20tag%20query%20string%20for%20SUCCESS#2

**Comment by anuraaga** [comment]
Yup that's what a successful retry looks like in a build scan.

**Comment by anuraaga** [comment]
Ah by the way if you're wondering whether that's Gradle Enterprise no, still hoping to hear back. Gradle Enterprise has a dashboard for tracking flakiness across bulds, but even within it we do get that reporting on a per-scan basis. And if we had to roll our own parsing the test reports it's probably not terrible.

**Comment by trask** [comment]
it looks like Gradle Enterprise provides build cache also 👍

**Comment by trask** [comment]
I ❤️ the flaky test reporting

**Comment by iNikem** [comment]
Gradle Enterprise is only self-hosted, AFAIK. They don't provide SaaS version of it. At least that was the case in the spring...

**Comment by trask** [comment]
@iNikem @anuraaga any objection to applying `retry` globally for now (instead of per module), so we don't need to keep playing whack-a-mole prior to GA at least?

**Comment by anuraaga** [comment]
I didn't expect anyone to actually notice the flaky tests on the build reports :) Since we seem to be tracking those sort of ok SGTM.

**Comment by trask** [comment]
This is done.

Btw, look at all the green builds since enabling retry!!

![image](https://user-images.githubusercontent.com/218610/89975519-cf18f080-dc1a-11ea-88b9-3be75bc2b702.png)

**Comment by anuraaga** [comment]
I just remembed one caveat as I debug a test - I think we need to set it to only retry when `System.getenv("CI")` is set :D
