### ISSUE TITLE
Emit events w/ dependency information

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/opentelemetry-java-instrumentation#9253]
Its useful to be able to understand various information about the set of libraries an application uses, such as the library name, version, checksum, and more. This information can be used to understand the context in which an application is running, or to detect usage of vulnerable dependencies.

In a java application, its possible to inspect every loaded class using javaagent instrumentation. From a class, you can resolve the CodeSource, and the URL of the JAR. Given the URL of a JAR, you can do things like inspect its manifest, find / inspect the POM, compute checksums, and more. From these data sources, you can compute useful metadata about the JAR, including:

- The JAR Manifest “Implementation-Title”, e.g. “Apache Log4j SLF4J 2.0 Binding”
- The JAR Manifest “Implementation-Vendor”, e.g. “The Apache Software Foundation”
- The POM group id, artifact id, version, e.g.: “org.apache.logging.log4j:log4j-slf4j2-impl:2.20.0”
- The JAR file name, e.g. “log4j-slf4j2-impl-2.20.0.jar”
- The JAR SHA-1 checksum, e.g. “155c8b9bbdac91d8461d9a403a646e6bd0d365d8”
- Useful for verifying JAR content as published on mvn, e.g. [org.apache.logging.log4j:log4j-slf4j2-impl:2.20.0.jar.sha1](https://repo1.maven.org/maven2/org/apache/logging/log4j/log4j-slf4j2-impl/2.20.0/log4j-slf4j2-impl-2.20.0.jar.sha1)

I propose we add a javaagent feature to collect this data and emit it as [OpenTelemetry Events](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/events.md), with details as follows:

- Use existing ECS conventions where applicable.
  - [Package Field conventions](https://www.elastic.co/guide/en/ecs/current/ecs-package.html) mapping:
    - package.name: “org.apache.logging.log4j:log4j-slf4j2-impl”
    - package.version: 2.20.0
    - package.type: jar
    - package.description: Apache Log4j SLF4J 2.0 Binding by The Apache Software Foundation
    - package.checksum: 155c8b9bbdac91d8461d9a403a646e6bd0d365d8
    - package.path: log4j-slf4j2-impl-2.20.0.jar
  - ECS [event.category ](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-category.html)and [event.type](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-type.html):
    - event.domain: [package](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-category.html#ecs-event-category-package)
    - event.name: [info](https://www.elastic.co/guide/en/ecs/current/ecs-allowed-values-event-type.html#ecs-event-type-info)
- Rate limit the jar processing.
  - Processing of JARs requires processing the content InputStream, which can use significant CPU / disk IO if unbounded. We should rate limit the process and add a reasonable default limit (e.g. 10 JARs / second).
- Periodically resend the events.
  - Some backends will have data retention limits that would make these dependency events eventually inaccessible for long running JARs. To accommodate this, we should allow this capability to configure resending the data on some sort of interval (e.g. every 24 hours).
- Allow this capability to be turned off.
  - Like other instrumentation, we should allow this to be turned off, and maybe keep it off by default while we work out the details.

I have a prototype otel java agent extension which produces this telemetry. I still need to add some additional error handling for edge cases, but when things go right, it emits log records as follows (OTLP JSON encoding):
```
{
	"timeUnixNano": "1692389915691751000",
	"observedTimeUnixNano": "1692389915691796000",
	"body": {
		"stringValue": ""
	},
	"attributes": [{
		"key": "event.domain",
		"value": {
			"stringValue": "package"
		}
	}, {
		"key": "event.name",
		"value": {
			"stringValue": "info"
		}
	}, {
		"key": "package.checksum",
		"value": {
			"stringValue": "30d16ec2aef6d8094c5e2dce1d95034ca8b6cb42"
		}
	}, {
		"key": "package.description",
		"value": {
			"stringValue": "Jackson datatype: JSR310 by FasterXML"
		}
	}, {
		"key": "package.name",
		"value": {
			"stringValue": "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
		}
	}, {
		"key": "package.path",
		"value": {
			"stringValue": "jackson-datatype-jsr310-2.15.2.jar"
		}
	}, {
		"key": "package.type",
		"value": {
			"stringValue": "jar"
		}
	}, {
		"key": "package.version",
		"value": {
			"stringValue": "2.15.2"
		}
	}]
}
```

Looking forward to hearing what people think. Happy to contribute this feature we folks agree.

**Comment by tylerbenson** [comment]
I support adding a feature like this and think it would be beneficial to users to have more visibility into dependencies. My main question is if we should start a discussion on this in the semantic conventions repo to get consensus on the attribute names.
