### ISSUE TITLE
[Help wanted]Too long command line

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#9258]
I am using otel agent 1.15.0 version.
The upload trace info include the resource label "process.command_line", and in my situation, the command line info always very long, so i want to remove this attribute in the upload data.
In the version >= 1.19.0, the resources provider is moved from core sdk to agent. So i can modify the agent code. But i am using 1.15.0, so i cannot modify the code in core sdk.

Is there any suggestion about it ?

**Comment by laurit** [comment]
You can disable the `ProcessResourceProvider` as described in https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#disabling-automatic-resourceproviders Or you could drop the `process.command_line` attribute in the collector.

**Comment by xiangtianyu** [comment]
> You can disable the `ProcessResourceProvider` as described in https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#disabling-automatic-resourceproviders Or you could drop the `process.command_line` attribute in the collector.

Thanks, Since drop in the collector will also affects the apps net and memory, i will try the disable setting.
