### ISSUE TITLE
Reactor: ContextPropagationOperator should allow retrieval from ContextView

### ISSUE THREAD

**Issue by philsttr** [open-telemetry/opentelemetry-java-instrumentation#9263]
**Is your feature request related to a problem? Please describe.**

Starting in reactor 3.4+, to read from the subscriber context, reactor provides a read-only object of type `reactor.util.context.ContextView`.

Prior to 3.4, reactor provided a read-write object of type `reactor.util.context.Context` when reading.

Currently, `ContextPropagationOperator.getOpenTelemetryContext` takes an object of type `reactor.util.context.Context`.  Unfortunately this method cannot be used easily with reactor 3.4+, since an object of type `reactor.util.context.Context` is not available when reading values from the context.

**Describe the solution you'd like**

I'd like `ContextPropagationOperator` to provide an efficient method of reading values from a `reactor.util.context.ContextView`.

Having said that `ContextPropagationOperator` needs to continue to work with older reactor versions that do not have `reactor.util.context.ContextView`.

**Describe alternatives you've considered**

Create a `Context` from a `ContextView`, and pass that to `ContextPropagationOperator.getOpenTelemetryContext`.  Potentially creates garbage.

Iterate over values in `ContextView` looking for one whose `key.toString().equals("otel-trace-context")`.  Inefficient.

**Comment by mateuszrzeszutek** [comment]
Hey @philsttr ,

Thanks for filing this! This definitely makes sense to me 👍 

Reactor introduced `ContextView` in 3.4 -- we'll have to bump the minimum supported version to 3.4, and probably add a new common module for the code that's shared between the library (now 3.4) and javaagent (still 3.1) instrumentation.
