### ISSUE TITLE
Cannot build `examples/extension` Gradle project

### ISSUE THREAD

**Issue by gczarnocki** [open-telemetry/opentelemetry-java-instrumentation#9298]
**Describe the bug**
After checking out `master` branch of this repositoty, I cannot build the project as defined in `README.md` due to:

```text
xxx@xxx MINGW64 /c/Source/opentelemetry-java-instrumentation/examples/extension ((v1.29.0))
$ ./gradlew clean build
Starting a Gradle Daemon, 2 stopped Daemons could not be reused, use --status for details

FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\Users\xxx\.gradle\init.gradle' line: 63

* What went wrong:
A problem occurred configuring root project 'opentelemetry-java-instrumentation-extension-demo'.
> Could not set unknown property 'classifier' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 40s
```

**Steps to reproduce**
1. Clone the repository,
2. `git checkout v1.29.0`
3. `./gradlew clean build`

**What did you expect to see?**

Built JAR with extension.

**What did you see instead?**

A failure, see above.

**What version are you using?**

`v1.29.0`

**Environment**

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 8.2.1
------------------------------------------------------------

Build time:   2023-07-10 12:12:35 UTC
Revision:     a38ec64d3c4612da9083cc506a1ccb212afeecaa

Kotlin:       1.8.20
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          11.0.15 (Eclipse Adoptium 11.0.15+10)
OS:           Windows 10 10.0 amd64

$ java --version
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
```

OS:

```text
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19045 Build 19045
```

**Comment by breedx-splk** [comment]
Hey @gczarnocki ...We don't have a branch with the name you gave above, but I assume you meant `main` but that's probably irrelevant anyway since you are checking out the tag.

Anyway, I could not reproduce this. I tried both on `main` HEAD and on the tag, and both built fine. What version of java are you running?

**Comment by laurit** [comment]
As can be seen in the error message
```
* Where:
Initialization script 'C:\Users\xxx\.gradle\init.gradle' line: 63
```
the failure occurs in gradle init script, which is not part of this project. Try removing it. Also see https://docs.gradle.org/current/userguide/upgrading_version_7.html#abstractarchivetask_api_cleanup

**Comment by gczarnocki** [comment]
Of course, I was blind at the time - was looking at the error in `build.gradle` of your subproject. After renaming `init.gradle` to  `init.gradle.old` - it worked. It contained local project set-up needed for work that was Gradle 7 compatible.

Solved. Sorry for confusion!
