### ISSUE TITLE
`io.opentelemetry.api.GlobalOpenTelemetry` occurred ClassNotFound Exception, when agent autoconfigure sdk

### ISSUE THREAD

**Issue by Anyuoo** [open-telemetry/opentelemetry-java-instrumentation#9311]
## discribe promble
When the agent is working fine, I want to use `GlobalOpenTelemetry` util within an app(eg: a spring boot app) , but it don't autoconfigure completely. So i try to debug , I found can't load class `GlobalOpenTelemetry` .
![image](https://github.com/open-telemetry/opentelemetry-java/assets/37858147/c75d31cd-a550-4658-8a0c-d0c237f5427b)

## What version and what artifacts are you using?
```xml
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk</artifactId>
           <version>1.27.0</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-exporter-otlp</artifactId>
           <version>1.27.0</version>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-semconv</artifactId>
            <version>1.27.0-alpha</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.opentelemetry/opentelemetry-sdk-extension-autoconfigure -->
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-sdk-extension-autoconfigure</artifactId>
            <version>1.27.0-alpha</version>
        </dependency>
```
## What did you expect to see?
Are there any configurations or dependencies that I need to set up for it?

**Comment by laurit** [comment]
Agent shades opentlemetry api under a different package name so the exception is correct, class `io.opentelemetry.api.GlobalOpenTelemetry` does not exist in the agent. See https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/contributing/debugging.md#shadow-renaming

**Comment by Anyuoo** [comment]
Okay, I got it. Thank you, everyone.
