### ISSUE TITLE
Remove support for the old `@WithSpan` annotation in javaagent 2.0

### ISSUE THREAD

**Issue by mateuszrzeszutek** [open-telemetry/opentelemetry-java-instrumentation#9323]
Since we're cleaning up lots of things in 2.0, we could as well remove the support for the old `io.opentelemetry.extension.annotations.WithSpan` annotation.

**Comment by trask** [comment]
I have some hesitation about this because I see it as somewhat similar to [dropping support for older library versions](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/VERSIONING.md#javaagent-instrumentation)

**Comment by mateuszrzeszutek** [comment]
> I have some hesitation about this because I see it as somewhat similar to [dropping support for older library versions](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/VERSIONING.md#javaagent-instrumentation)

Hmm, yes, you're right.
I thought it would be a good thing to drop in the 2.0 release, but on the second thought, I guess there's little harm in leaving it as it is. Closing.
