### ISSUE TITLE
[otel.javaagent 2023-08-28 13:50:18:653 +0000] [Ok*****local:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message:

### ISSUE THREAD

**Issue by Curlybraces3** [open-telemetry/opentelemetry-java-instrumentation#9329]
### Describe the bug

Hello,

I am getting below errors in one of the login service.
[otel.javaagent 2023-08-28 13:50:18:653 +0000] [Ok*****local:4317/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message:

[java.io.IOException: FRAME_SIZE_ERROR: 4740180, java.io.IOException: closed]

I am using below params in the pipeline
FROM amazoncorretto:17

EXPOSE 8080

RUN mkdir app

COPY build/libs/appLogin.jar app/appLogin.jar

ADD https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar /aws-opentelemetry-agent.jar
# OpenTelemetry agent configuration

ENV OTEL_RESOURCE_ATTRIBUTES "service.name=LoginService"
ENV OTEL_METRICS_EXPORTER=none
ENV OTEL_EXPORTER_OTLP_ENDPOINT=***.local:4317

ENTRYPOINT ["java", "-Djava.io.tmpdir=/mnt/tmp", "-javaagent:/aws-opentelemetry-agent.jar", "-jar","/app/appLogin.jar"]

### Steps to reproduce

I am using aws-opentelemetry-agent.jar 

### Expected behavior

It should not create the above error i have mentioned

### Actual behavior

creating IOException with FRAME_SIZE_ERROR: 4740180

### Javaagent or library instrumentation version

latest release from github

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
This happens when you are sending grpc to and endpoint that accepts http 1.1 instead of http 2 that is used for grpc. Check your configuration and verify that you are sending to the correct endpoint. Also see https://github.com/grpc/grpc-java/issues/8164#issuecomment-838877435

**Comment by Curlybraces3** [comment]
I have some similar services with same end point but those are not causing any warning like above.

**Comment by laurit** [comment]
@Curlybraces3 if other service work then perhaps they are using otlp over http/protobuf instead of otlp over grpc? I believe that this is a configuration error on your side. If you believe it is a bug then please provide instructions to reproduce.

**Comment by Curlybraces3** [comment]
@laurit 
please find my configuration below.
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch/traces:
    timeout: 1s
    send_batch_size: 50

exporters:
  awsxray:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch/traces]
      exporters: [awsxray]

  extensions: [health_check]

**Comment by laurit** [comment]
@Curlybraces3 just the collector configuration is not enough, you need to provide exact instructions that allow reproducing this with minimal effort.

**Comment by breedx-splk** [comment]
@Curlybraces3 You've also indicated that you're using a vendor-specific distribution of otel java instrumentation. How sure are you that it defaults to using OTLP over GRPC as the default exporter? It might be nice to get someone from AWS to help confirm this....

**Comment by Curlybraces3** [comment]
@laurit 

I am not sure about the minimal configuration you have requested. 


Note: After adding one param _ENV OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf_ in the environment variable i am getting different error now. see below

[otel.javaagent 2023-08-30 05:36:12:409 +0000] [OkHttp http://******.local:4317/...] WARN io.opentelemetry.exporter.internal.http.HttpExporter - Failed to export spans. Server responded with HTTP status code 405. Error message: Unable to parse response body, HTTP status message: Method Not Allowed

> @Curlybraces3 just the collector configuration is not enough, you need to provide exact instructions that allow reproducing this with minimal effort.

**Comment by laurit** [comment]
@Curlybraces3 we are asking for a minimal application that would reproduce the issue. Usually such reproducers are provided as a github repo. In your case this should include a docker container that sets ups the collector, or at least the collector conf file and the version of the collector you are using, and an application that sends traces to the collector and produces the warning you observed. This should be accompanied with instructions on how to run the app, which env variables to set etc. If we can reproduce your issue we can determine where your configuration issue is, or if there is a bug, fix it.

**Comment by sahilcool-nsut** [comment]
Were you ever able to fix this @Curlybraces3 ? I'm having the exact same problem with only one specific services giving this error, while the same config working for other services.

**Comment by rpgdev** [comment]
@sahilcool-nsut did you? I'm getting the same, same arguments work with the agent and a Jaeger backend but autoconfigure doesn't work. My org decided to go with otel for traces. God help us lol.

**Comment by rpgdev** [comment]
Ok, I set this property `otel.exporter.otlp.protocol=grpc` and changed the port and then it worked BUT it's the same backend I've been using with the agent jar setup, not sure why I had to change those properties once I started to do autoconfiguration instead of the agent.jar

**Comment by bharatbandu1** [comment]
@rpgdev, may I know which port you used instead of 4317?. Facing same issue with otel auto-instrumetation for java using otel operator. I've tried adding env OTEL_EXPORTER_OTLP_PROTOCOL to use grpc with 4317,4318 and 14250 as well without any luck.

Below is my otel-collector receivers config:
receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

[OkHttp http://opentelemetry-opentelemetry-collector.opentelemetry.svc.cluster.local:14250/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: FRAME_SIZE_ERROR: 4740180
