### ISSUE TITLE
Config opentelemetry-log4j-appender-2.17 to log4j2.properties

### ISSUE THREAD

**Issue by peng3693** [open-telemetry/opentelemetry-java-instrumentation#9334]
### Describe the bug

I saw that the [usage](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library#usage) is config log4j2.xml, but now I want to configure log4j2.properties, but it has been unsuccessful

### Steps to reproduce

This is my log4j2.properties:

```
rootLogger.level = INFO
rootLogger.appenderRef.stdout.ref = STDOUT
logger.packages = io.opentelemetry.instrumentation.log4j.appender.v2_17
rootLogger.appenderRef.OpenTelemetryAppender.ref = OpenTelemetryAppender

appender.stdout.type = Console
appender.stdout.name = STDOUT
appender.stdout.layout.type = PatternLayout
appender.stdout.layout.pattern = %highlight{%-5p [%t] %X{RemoteAddr}%X{Tenant}%X{CronJob}[%c{1}] %m%n}


appender.OpenTelemetryAppender.type = OpenTelemetry
appender.OpenTelemetryAppender.name = OpenTelemetryAppender
appender.OpenTelemetryAppender.captureMapMessageAttributes = true
appender.OpenTelemetryAppender.captureExperimentalAttributes = true
appender.OpenTelemetryAppender.captureContextDataAttributes = *
```

### Expected behavior

Achieve the same effect as the log4j2.xml configuration

### Actual behavior

Project start failed

### Javaagent or library instrumentation version

1.29.0

### Environment

**JDK**:
**OS**:

**Comment by mateuszrzeszutek** [comment]
Hey @peng3693 

Instead of `logger.packages`, use `packages`:
```properties
packages = io.opentelemetry.instrumentation.log4j.appender.v2_17

rootLogger.level = INFO
rootLogger.appenderRef.stdout.ref = STDOUT
rootLogger.appenderRef.OpenTelemetryAppender.ref = OpenTelemetryAppender
# ...
```

Otherwise log4j tries to configure a logger named `packages`, and finds that configuration invalid.
