### ISSUE TITLE
Use a real javaagent for tests instead of bytebuddy dynamic attach

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#936]
To match production more closely.

From https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/913#issuecomment-670313037

> we could probably migrate our tests to use an actual TestAgent instead of runtime bytebuddy injection. This would be similar to how I moved the runtime bootstrap injection into Gradle - doing similar for agent would let tests match production even more closely.

**Comment by FrankSpitulski** [comment]
Maybe it could be run with both? I'd like to keep being able to dynamically attach with bytebuddy for production use.

**Comment by iNikem** [comment]
Duplicates ##1146
