### ISSUE TITLE
What is the recommended way to add custom auto instrumentation?

### ISSUE THREAD

**Issue by FrankSpitulski** [open-telemetry/opentelemetry-java-instrumentation#938]
for example adding a custom tag on server spans based on the request

I remember there being some discussion about repackaging the agent jar with spi hooks for custom functionality.

There's also the question of completely new auto instrumentation such instrumenting a new library, or maybe replacing an existing auto instrumentation all together.

**Comment by trask** [comment]
> for example adding a custom tag on server spans based on the request

the current thought is #778

> completely new auto instrumentation such instrumenting a new library, or maybe replacing an existing auto instrumentation all together

ya, we just broke out a couple of "api" artifacts in #884, to help us get there, but still work to do

it is in our P1 required for GA issues:

* Basic configuration points
  * Add custom auto-instrumentation
  * Ability to build "custom distro"

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/docs/ga-requirements.md

**Comment by iNikem** [comment]
Will be implemented by #566
