### ISSUE TITLE
Add support for Jetty 12 HTTP Client

### ISSUE THREAD

**Issue by jorge-branco-dt** [open-telemetry/opentelemetry-java-instrumentation#9380]
### Is your feature request related to a problem? Please describe.

We'd be looking for a solution similar to #2837 (Jetty 9 HTTP Client) but for Jetty 12, instead. 
Unfortunately, Jetty 12 has gone through some serious API changes, and as such the previous instrumentation will definitely not work as it is.

### Describe the solution you'd like

It seems the current Jetty 9.x implementation opted to instrument `org.eclipse.jetty.client.HttpRequest.send()`, which then calls `org.eclipse.jetty.client.HttpClient,send()`. `HttpClient` seems public so if I'm reading the situation correctly this may mean that calls to `send()` done directly through `HttpClient` may not currently be monitored..

On the other hand, in Jetty 12, `HttpClient` no longer seems to have a `send()` method, so one should indeed instrument `org.eclipse.jetty.client.transport.HttpRequest.send(Response.CompleteListener)` instead. Do note the change of package of `HttpRequest`, from `org.eclipse.jetty.client` to `org.eclipse.jetty.client.transport`.

**Comment by mateuszrzeszutek** [comment]
Hey @jorge-branco-dt ,

We likely won't have time and resources to implement this instrumentation ourselves, but we would find an external contribution welcome.

**Comment by andythsu** [comment]
+1. @jorge-branco-dt Did you figure a way to instrument the client library in the meantime? or are you working on adding this?

**Comment by jorgedfbranco** [comment]
> +1. @jorge-branco-dt Did you figure a way to instrument the client library in the meantime? or are you working on adding this?

Hi, unfortunately I won't have the time and it's not on our current roadmap.

**Comment by stevenschlansker** [comment]
There's now initial support, this issue can probably be closed?

**Comment by steverao** [comment]
> support jettyclient 12 #11519

Sure, thank for your reminder!
