### ISSUE TITLE
Cannot compile the source code because of spotless plugin issue

### ISSUE THREAD

**Issue by phil-rice-HCL** [open-telemetry/opentelemetry-java-instrumentation#9387]
### Describe the bug

When I checkout the code and build it, I get an issue that it cannot find the spotless plugin

### Steps to reproduce

- Check out the code from https://github.com/open-telemetry/opentelemetry-java-instrumentation.git
- Check java version is 17
- ./gradlew assemble

### Expected behavior

The code should build

### Actual behavior

I get the following:

* What went wrong:
A problem occurred configuring project ':conventions'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':conventions:classpath'.
      > Could not resolve com.diffplug.spotless:spotless-plugin-gradle:6.21.0.
        Required by:
            project :conventions > com.diffplug.spotless:com.diffplug.spotless.gradle.plugin:6.21.0
         > No matching variant of com.diffplug.spotless:spotless-plugin-gradle:6.21.0 was found. The consumer was configured to find a library for use during runtime, compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.3' but:
             - Variant 'apiElements' capability com.diffplug.spotless:spotless-plugin-gradle:6.21.0 declares a library, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component for use during compile-time, compatible with Java 11 and the consumer needed a component for use during runtime, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')
             - Variant 'javadocElements' capability com.diffplug.spotless:spotless-plugin-gradle:6.21.0 declares a component for use during runtime, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')
             - Variant 'runtimeElements' capability com.diffplug.spotless:spotless-plugin-gradle:6.21.0 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
                 - Incompatible because this component declares a component, compatible with Java 11 and the consumer needed a component, compatible with Java 8
                 - Other compatible attribute:
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')
             - Variant 'sourcesElements' capability com.diffplug.spotless:spotless-plugin-gradle:6.21.0 declares a component for use during runtime, and its dependencies declared externally:
                 - Incompatible because this component declares documentation and the consumer needed a library
                 - Other compatible attributes:
                     - Doesn't say anything about its target Java version (required compatibility with Java 8)
                     - Doesn't say anything about its elements (required them packaged as a jar)
                     - Doesn't say anything about org.gradle.plugin.api-version (required '8.3')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1s
PS C:\git\opentelemetry-java-instrumentation> 

### Javaagent or library instrumentation version

latest (compiling from main branch)

### Environment

**JDK**:
java 17.0.6 2023-01-17 LTS

**OS**:
Windows 11 or Ubunut 22. Fails identically on both

This is running on a personal laptop with minimal security: no proxy, no firewalls other than windows defender. 

### Additional context

I an downloading and compiling the code in order to troubleshoot https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9359

**Comment by laurit** [comment]
This error happens when you try to build this project with java 8. In the terminal window where you execute `./gradlew assemble` verify that `java -version` and `echo $JAVA_HOME` both report java 17. You can also execute `./gradlew --version` and see what it reports for the JVM.

**Comment by phil-rice-HCL** [comment]
Thanks for the quick response!

I did note in the documentation that it needed Java 17 and I thought I had done that (so many javas/so many version). It looks like I 'half did it'

java -version
```
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
```
JAVA_HOME is empty

Gradle is much more interesting. It is here that I have the problem:
```
------------------------------------------------------------
Gradle 8.3
------------------------------------------------------------

Build time:   2023-08-17 07:06:47 UTC
Revision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5

Kotlin:       1.9.0
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          1.8.0_202 (Oracle Corporation 25.202-b08)
OS:           Windows 10 10.0 amd64

PS C:\git\opentelemetry-java-instrumentation> 
```

I've not really used Gradle much (Maven and SBT are my go-tos) but I will try and see why it is reporting this

**Comment by phil-rice-HCL** [comment]
Correction JAVA_HOME was the guilty party: It was pointing to JDK 8.

This appears to have been the issue. Thank you very much
