### ISSUE TITLE
Lot of non stop dual calls to db from OpenTelemetry agent

### ISSUE THREAD

**Issue by chandru-kumar** [open-telemetry/opentelemetry-java-instrumentation#9439]
### Describe the bug

I have used OpenTelemetry agent to instrument a web app - PrimeFaces, deployed in Tomee 8 server and connected to Oracle DB. Using zipkin to view the traces. But the dual calls to DB is infinitely hitting and cursors are filled up throwing - Internal Exception: java.sql.SQLException: ORA-01000: maximum open cursors exceeded.

Anyway to exclude the dual calls infinitely hitting DB and exporting it as trace?

### Steps to reproduce

Added this configuration in Tomee setupenv to instrument application.

set "CATALINA_OPTS=%CATALINA_OPTS% -javaagent:C:/OpenTelemetry/opentelemetry-javaagent-1.jar"
set "CATALINA_OPTS=%CATALINA_OPTS% -Dotel.resource.attributes=service.name=HISApp"
set "CATALINA_OPTS=%CATALINA_OPTS% -Dotel.traces.exporter=zipkin"

### Expected behavior

Expected to only capture the actions that user navigates and not all unncessary dual db hits.

### Actual behavior

The dual calls to DB is infinitely hitting and cursors are filled up throwing - Internal Exception: java.sql.SQLException: ORA-01000: maximum open cursors exceeded.

### Javaagent or library instrumentation version

Version 1.29.0

### Environment

JDK: OpenJDK 11
OS: Windows
OpenTelemetry agent :Version 1.29.0

**Comment by laurit** [comment]
@chandru-kumar you'll have to either provide a minimal application that reproduces your issue or describe the issue in sufficient detail to allow fixing it. What do you mean by dual calls to db? Where do these come from?
