### ISSUE TITLE
Don't model aws-sdk instrumentation using HttpClientTracer

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#944]
There are several things in the aws-sdk instrumentation which don't really fit into the normal `HttpClientTracer` model.

Motivation from https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/918#discussion_r468815884.

**Comment by anuraaga** [comment]
Yeah we probably need `Rpc*Tracer` for RPC libraries like AWS SDK and probably gRPC

**Comment by trask** [comment]
Closing, I think what we have is good, and will only improve with #2596
