### ISSUE TITLE
Need an aggregate view into flaky tests

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#945]
Now that we are using the gradle retry plugin, the build scans show us flaky tests, but we need an aggregated view into the flaky tests over a period of time in order to prioritize work on reducing flakiness.

**Comment by iNikem** [comment]
Solved by https://ge.opentelemetry.io/scans/tests?search.relativeStartTime=P7D&search.timeZoneId=Europe/Tallinn&tests.sortField=FAILED&tests.unstableOnly=true
