### ISSUE TITLE
Discover service.version attribute from Spring Boot's build-info.properties file

### ISSUE THREAD

**Issue by philsttr** [open-telemetry/opentelemetry-java-instrumentation#9457]
### Is your feature request related to a problem? Please describe.

Not really a "problem", but just a minor annoyance that I have to find some alternative way to specify the `service.version` attribute, even though the metadata is available in the application's jar.

### Describe the solution you'd like

The Spring Boot maven/gradle plugins provide a way to [generate a build information](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto.build.generate-info) for Spring Boot applications.  The plugins generate a file named `META-INF/build-info.properties`.  For example, the generated file might look like the following:

```properties
build.artifact=example-app
build.group=com.example
build.name=example-app
build.time=2023-08-24T12\:04\:36.605Z
build.version=1.0.0
```

Notice the `build.version` property.

It would be great if the [spring-boot-resources](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring/spring-boot-resources) instrumentation defined a `ResourceProvider` that would set the `service.version` resource attribute from the `build.version` property found in the `META-INF/build-info.properties` file.

This would make version discovery automatic for Spring Boot applications that already include build info.

### Describe alternatives you've considered

alternative 1:
Manually set the `service.version` resource attribute.

alternative 2:
A more-generic `ResourceProvider` could be created that takes the name of a class as input, and then retrieves its version information via `clazz.getPackage().getImplementationVersion()`, which pulls info from its jar's META-INF/MANIFEST.MF.

This alternative is not as "automatic" as using the Spring Boot `build-info.properties` file, since it requires additional input.  But it would support any Java application (assuming the metadata is in its manifest).  Not just Spring Boot apps.

**Comment by mateuszrzeszutek** [comment]
> It would be great if the [spring-boot-resources](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/spring/spring-boot-resources) instrumentation defined a `ResourceProvider` that would set the `service.version` resource attribute from the `build.version` property found in the `META-INF/build-info.properties` file.

That's a great idea 👍 
We would welcome a contribution that implements that.

**Comment by Hayanesh** [comment]
Hi @mateuszrzeszutek, Please find the [Pull Request](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9480) for this issue.
