### ISSUE TITLE
True correlation between trace,logs and metrics

### ISSUE THREAD

**Issue by gajavallisantosh** [open-telemetry/opentelemetry-java-instrumentation#9458]
### Describe the bug

True correlation between trace,logs and metrics

True correlation between trace,logs and metrics

Describe the bug
Unable to correlate with the same tarceid/span id between a trace,log and metrics

Expected behavior
Please give a working example or show me a link where i can get true correlation between 3 pillars of observability

in .NET this feature is unavailable, just want to know whether Java supports it

### Steps to reproduce

NA

### Expected behavior

NA

### Actual behavior

NA

### Javaagent or library instrumentation version

NA

### Environment

**JDK**:
**OS**:

**Comment by trask** [comment]
hi @gajavallisantosh, if you are asking about exemplars, yes they are supported in Java

you can check the support for other languages here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#metrics

> Please give a working example or show me a link where i can get true correlation between 3 pillars of observability

this sounds like a good question for https://github.com/open-telemetry/opentelemetry-demo
