### ISSUE TITLE
Don't use boxed numerics in tracer type parameters

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#946]
I noticed that because of numeric expansion, it's actually very easy to call the wrong method when a subclass uses a boxed type like `Integer` in the tracer. It's probably best to avoid boxed types in type parameters because of this. The specific case I found is HTTP response code, and it could be worth adding a `HttpStatus` enum to our instrumentation API with a factory to convert from a response code, to avoid using integers more than needed in instrumentation.

**Comment by trask** [comment]
@anuraaga I see

```
HttpUrlConnectionTracer extends HttpClientTracer<HttpURLConnection, Integer>
```

Is this the one you ran into? I couldn't find any others with a quick search.

**Comment by anuraaga** [comment]
Yup that's what I ran into - didn't do the quick scan myself but indeed it's probably the only one.

**Comment by trask** [comment]
Marked `after-ga` since we won't be exposing `HttpUrlConnectionTracer` publicly as part of library instrumentation in GA (or maybe ever)
