### ISSUE TITLE
I want the agent to collect common system metrics data

### ISSUE THREAD

**Issue by zhangjiabin1010** [open-telemetry/opentelemetry-java-instrumentation#9463]
### Is your feature request related to a problem? Please describe.

For example:
cpu utilization,
memory usage,
Network io and other indicators.
These metrics are important for discovering problems with the service, and I no longer want to start external processes like prometheus node_exporter

I observed that there is already a receiver in the opentelemetry-collector-contrib repository
/hostmetricsreceiver/.
But this can only collect the metrics information of the host where the collector is located.
A common scenario is that multiple services push host metrics data to the collector.
Instead of deploying a collector on each service host.

### Describe the solution you'd like

I hope to integrate the generated host metrics data into agent.jar. This saves a lot of steps. Is my idea correct, or is there any solution that can achieve my needs? Please give me some advice

**Comment by zhangjiabin1010** [comment]
> 嘿@zhangjiabin1010,
> 
> > 并且在javaagent.debug中没有找到oshi的相关日志。我怀疑 oshi 可能尚未初始化，
> > 请给我一些建议。谢谢。
> 
> Oshi 检测有点特殊，因为您首先需要将 Oshi 添加到类路径中；有关更多详细信息，请参阅[#1566 。](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/1566)

Thank you for your reply. I saw this issue, but I couldn't find any specific documentation.
Do I need to modify the code as per the file changes mentioned here，
[#1530](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1530/files/b6a570ae331a47f8d7672dff1857cd2cd489b788#diff-a6cda2dc8cf8b2318375b4c5821b1a7a4 7bb47d15df384051294ea094169f814)


The source code of version 1.29.0 is already different from the code in this link.
I think it would be better to have detailed documentation, thank you

**Comment by mateuszrzeszutek** [comment]
No, you just need to add Oshi to your classpath, as #1566 says:

```
java -javaagent:opentelemetry-agent.jar -cp oshi-core-5.3.6.jar -jar springboot-1.0.jar
```

**Comment by zhangjiabin1010** [comment]
> 不，你只需要将 Oshi 添加到你的类路径中，如#1566所示：
> 
> ```
> java -javaagent:opentelemetry-agent.jar -cp oshi-core-5.3.6.jar -jar springboot-1.0.jar
> ```

I have tried this solution and tried oshi-core-5.3.6.jar
oshi-core-5.3.1.jar these two versions. 
No system indicators were collected.
And there is no relevant log of oshi shown in the service log.
Set -Dotel.javaagent.debug=true in the startup parameters. 
I haven’t seen the startup log of oshi either.

**Comment by kes2464** [comment]
Made it working using `-Xbootclasspath/a` option to add oshi-core jar file

So like
`java -javaagent:opentelemetry-agent.jar -Xbootclasspath/a:oshi-core.jar:jna.jar:slf4j-api.jar -jar springboot-1.0.jar`

However, not sure if I am supposed to also add jna.jar and slf4j-api.jar, I added them due to NoClassDefFoundError when only oshi-core was added.

**Comment by trask** [comment]
@zhangjiabin1010 can you see if @kes2464's solution works for you?

we are also planning to make using the oshi instrumentation simpler to use (and packaged up into a single agent extension jar) in the future, see #9517

**Comment by zhangjiabin1010** [comment]
> slf4j-api.jar

After testing, your solution is feasible, thank you very much for your suggestion.

**Comment by zhangjiabin1010** [comment]
> @zhangjiabin1010你能看看吗@kes2464的解决方案适合您吗？
> 
> 我们还计划将来使 oshi 工具的使用更简单（并打包到单个代理扩展 jar 中），请参阅#9517

@trask，His solution is feasible, but this configuration solution is not very elegant. It is strongly supported to include it in agent extension as soon as possible.
