### ISSUE TITLE
Be able to configure OkHttp client and Retrofit in dedicated functions

### ISSUE THREAD

**Issue by GerardPaligot** [open-telemetry/opentelemetry-java-instrumentation#9470]
### Is your feature request related to a problem? Please describe.

Because the [OkHttp interceptor](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/776e2ec4a8914ce2b2334b58ff8df77ba404905f/instrumentation/okhttp/okhttp-3.0/library/src/main/java/io/opentelemetry/instrumentation/okhttp/v3_0/OkHttpTelemetry.java#L56) has been deprecated, if we want to instrument correctly our http requests, we need to configure all `Retrofit` configurations with this kind of snippet:

```kotlin
 Retrofit.Builder()
    .baseUrl("base-url")
    // others configuration
    .callFactory(
        OkHttpTelemetry.builder(openTelemetry)
            .build()
            .newCallFactory(okHttpClient)
    )
    .build()
```

The main issue with this approach is the necessity to have a dependency everywhere to OpenTelemetry instance. If I take an Android application as context, we generally declare few OkHttpClients (the minimum as possible) but we need to create so much more `Retrofit` instance (one per micro service implemented in the mobile application) because it is there we generally configure the base url of the micro service.

### Describe the solution you'd like

It would be great to distinguish the `OkHttpClient` and `Retrofit` configuration with something like this:

```java
public OkHttpClient.Builder addTracingInterceptors(OkHttpClient.Builder builder) {
    // add our interceptors before other interceptors
    builder.interceptors().add(0, new ContextInterceptor());
    builder.interceptors().add(1, new ConnectionErrorSpanInterceptor(instrumenter));
    builder.networkInterceptors().add(0, newInterceptor());
    return builder;
}

public static Call.Factory tracingCallFactory(OkHttpClient baseClient) {
    // Check if required interceptors are configured in the client.
    return new TracingCallFactory(tracingClient);
}
```

Retrofit configuration will be reduced to this:

```kotlin
 Retrofit.Builder()
    .baseUrl("base-url")
    // others configuration
    .callFactory(OkHttpTelemetry.tracingCallFactory(okHttpClient))
    .build()
```

### Describe alternatives you've considered

Another interesting contract with this new approach (but require to configure Kotlin in the library) would be to add an extension on `OkHttpClient.Builder` and `Retrofit.Builder` classes:

```kotlin
// OkHttpClient.Builder
fun OkHttpClient.Builder.addTracingInterceptors(telemetry: OkHttpTelemetry) {
    interceptors().add(0, ContextInterceptor())
    interceptors().add(1, ConnectionErrorSpanInterceptor(instrumenter))
    networkInterceptors().add(0, TracingInterceptor(telemetry.instrumenter, telemetry.propagators))
}

// Retrofit.Builder
fun Retrofit.Builder.tracingClient(client: OkHttpClient) {
  // Check if required interceptors are configured in the client.
  callFactory(TracingCallFactory(client))
}
```

**Comment by laurit** [comment]
You could either create and instance of `OkHttpTelemetryBuilder` with `OkHttpTelemetry.builder(openTelemetry).build()` or  `Call.Factory tracingCallFactory = OkHttpTelemetry.builder(openTelemetry).build().newCallFactory(okHttpClient)` and use the builder/call factory everywhere to avoid passing the OpenTelemetry instance. Would that work for you?

**Comment by GerardPaligot** [comment]
Yes, it would work!

**Comment by mateuszrzeszutek** [comment]
@GerardPaligot did that resolve your problem? Can we close this issue?

**Comment by GerardPaligot** [comment]
Yes, I close it!
