### ISSUE TITLE
Provide a way to disable tracing for a library/framework without disabling metrics (and vice versa)

### ISSUE THREAD

**Issue by lordpixel23** [open-telemetry/opentelemetry-java-instrumentation#9481]
### Is your feature request related to a problem? Please describe.

The Java Agent allows suppressing specific library instrumentation using environment variables or system properties as is very well documented here:
https://opentelemetry.io/docs/instrumentation/java/automatic/agent-config/#suppressing-specific-agent-instrumentation

Unfortunately I believe at present setting these flags disables both tracing and metrics. What I would like is a way to keep metrics but disable tracing.

### Describe the solution you'd like

Some way to set an option either in config or in code which allows more fine grained control. To keep metrics on and turn tracing off for a library, though naturally someone else might want the opposite and the mechanism should be flexible enough to support both.

### Describe alternatives you've considered

The only alternative seems to be to turn off the instrumentation altogether, though perhaps there is some way to suppress specific spans from tracing?

**Comment by mateuszrzeszutek** [comment]
Hey @lordpixel23 ,

You could implement a custom [`Sampler`](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/Sampler.java) that filters out spans you don't want. If you don't want any spans at all, you might also turn off the span exporter altogether (`-Dotel.traces.exporter=none`)

**Comment by lordpixel23** [comment]
The spans I don’t want are process and publish. I was hoping there was a simple answer like a value for OTEL_JAVAAGENT_EXCLUDE_CLASSES. 

I can see what you’re saying with a Sampler would probably work but as I looked through what it would take it means maintaining and deploying an agent extension. I was hopeful some simple property based confit exists.

**Comment by lordpixel23** [comment]
Ah, sorry, clarification. The process and publish spans from the Kafka instrumentation. I realized just now I hadn’t said that.

**Comment by mateuszrzeszutek** [comment]
> I can see what you’re saying with a Sampler would probably work but as I looked through what it would take it means maintaining and deploying an agent extension. I was hopeful some simple property based confit exists.

No, aside from the `Sampler` (and the instrumentation enabled config flag) there isn't anything else that'd support this scenario.  You can look up the [`RuleBasedRoutingSampler` ](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/samplers/src/main/java/io/opentelemetry/contrib/sampler/RuleBasedRoutingSampler.java) from the contrib repo, but that still requires an extension unfortunately.

Alternatively, if you're using the collector, you should be able to configure the [tail sampler](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/README.md) to drop the spans that you don't want to keep.

**Comment by lordpixel23** [comment]
Right, so "the collector" and "the agent" are mutually exclusive I assume. 

For my particular use case I think I've actually found a workaround: 

After much trial and error setting an exclude appears to have worked. The instrumentation in the agent isn't actually on these classes of course, but, it seems to register itself with these names and therefore be possible to exclude:

OTEL_JAVAAGENT_EXCLUDE_CLASSES=org.apache.kafka.clients.consumer.ConsumerRecords, org.apache.kafka.clients.producer.KafkaProducer 

(though maybe the second one was org.apache.kafka.clients.producer.Producer -- I don't have it in front of me right now) 

Recording it here in the hope it helps the next person searching.

**Comment by mateuszrzeszutek** [comment]
> Right, so "the collector" and "the agent" are mutually exclusive I assume.

No, it's quite the opposite actually! We recommend using [the collector](https://opentelemetry.io/docs/collector/) together with instrumentation, as it can server as a sort of enhancing/filtering/buffering layer before the telemetry gets sent to your chosen APM backend.

**Comment by trask** [comment]
we've opened #9518 to make this easier
