### ISSUE TITLE
Set the data format of metrics otlp exporter to gauge

### ISSUE THREAD

**Issue by zhangjiabin1010** [open-telemetry/opentelemetry-java-instrumentation#9485]
### Is your feature request related to a problem? Please describe.

Current background:
javaagent parameter setting-Dotel.metrics.exporter=otlp,
The exporter of otel-collector is clickhouse
Most of the indicators collected so far are of cumulative SUM type.
It is not conducive to trend chart indicator analysis. Is there any way to configure it so that metrics otlp exports Gauge type values?

The ideal situation is similar to the metrics format exported by -Dotel.metrics.exporter=prometheus.

My ultimate goal is to store the collected jvm indicators in clickhouse in Gauge type format for query analysis.

### Describe the solution you'd like

Added javaagent configuration items to set the default indicator export format

### Describe alternatives you've considered

OTEL_EXPORTER_OTLP_METRICS_DATA_TYPE=gauge

**Comment by laurit** [comment]
Try using collector transform processor https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md `convert_sum_to_gauge` seems like the transformation you are looking for.

**Comment by zhangjiabin1010** [comment]
> Try using collector transform processor https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/transformprocessor/README.md `convert_sum_to_gauge` seems like the transformation you are looking for.

This is a good solution, thanks for the answer。
