### ISSUE TITLE
automatic java agent send spans to jaeger - timeout issue.

### ISSUE THREAD

**Issue by matixoooo** [open-telemetry/opentelemetry-java-instrumentation#9497]
Hello, I have been trying to configure my Java application to send spans to Jaeger for some time.

I have configured environment variables for the java agent in the deployment
          - name: OTEL_TRACES_EXPORTER
            value: jaeger
          - name: OTEL_EXPORTER_JAEGER_ENDPOINT
            value: http://example.telemetry.pl:14250
          - name: OTEL_SERVICE_NAME
            value: backend-{{ .Values.environment }}
          - name: OTEL_METRICS_EXPORTER
            value: none
          - name: OTEL_JAVAAGENT_DEBUG
            value: "true

if my jaeger is running on vm, everything works as it should, but the problem occurs when my jaeger is running on a kubernetes cluster.
traffic to jaeger on 14250 is assured, but I see timeout information in the logs

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/92515985/acd64d7f-4a53-4aea-9bcf-2c1de46e2c30)

I see such entries in the Collector Jaeger logs

{"level":"info","ts":1695107953.7723224,"caller":"grpc@v1.54.0/server.go:935","msg":"[core][Server #1] grpc: Server.Serve failed to create ServerTransport: connection error: desc = \"transport: http2Server.HandleStreams failed to receive the preface from client: unexpected EOF\"","system":"grpc","grpc_log":true}

can u guys help me with that?

**Comment by mateuszrzeszutek** [comment]
This looks like a networking issue; the fact that it works on a vm seems to support that theory. I'd suggest investigating your network connectivity; and if you find there's an issue with something in the OTel setup, please provide a repro scenario, we're not really able to do anything without it.

**Comment by matixoooo** [comment]
repo scenario:

1. Installation Jaeger Helm Chart:

helm install jaeger jaegertracing/jaeger -n jaeger --create-namespace

2. adding the opentelemetry-agent for java file to the Java application image.

3. adding environment variables to the deployment:

javaOptions: |
  -javaagent:/opentelemetry-javaagent.jar

envConfigTelemetry:
  - name: OTEL_TRACES_EXPORTER
    value: jaeger
  - name: OTEL_EXPORTER_JAEGER_ENDPOINT
    value: http://telemetry.example.pl:14250
  - name: OTEL_SERVICE_NAME
    value: backend-dev
  - name: OTEL_METRICS_EXPORTER
    value: none
    
    trying to send spans to jaeger
    
    
    access to jaeger from the kubernetes cluster where the applications are located is ensured, traffic to collector port 14250 is open.

does the jaeger itself need to move in the other direction?

**Comment by matixoooo** [comment]
it turned out to be the fault of the company's loadbalancer.

namely, my jaeger-collector was issued as a nodeport and then it is forwarded to the company's load balancer where the port is mapped to 14250.

HTTP processing was enabled on the load balancer. after disabling http and enabling tcp, everything started working
