### ISSUE TITLE
Instrumentation for Ktor Client does not appear in OTEL APM

### ISSUE THREAD

**Issue by pkgonan** [open-telemetry/opentelemetry-java-instrumentation#9501]
### Describe the bug

Instrumentation for Ktor Client does not appear in OTEL APM

Ktor Version (use CIO engine)
* 2.3.4

### Steps to reproduce

Version
```
object Libs {
    // Kotlin
    const val kotlin_bom = "org.jetbrains.kotlin:kotlin-bom:1.8.22"

    // Ktor
    const val ktor_bom = "io.ktor:ktor-bom:2.3.4"
    const val ktor_client_core = "io.ktor:ktor-client-core"
    const val ktor_client_cio = "io.ktor:ktor-client-cio"
    const val ktor_client_content_negotiation = "io.ktor:ktor-client-content-negotiation"
    const val ktor_serialization_jackson = "io.ktor:ktor-serialization-jackson"
}
```

How to use ktor
```
        private val client: HttpClient = HttpClient(CIO) {
            install(ContentNegotiation) {
                jackson()
            }
        }
```

### Expected behavior

Ktor Client instrumentation should be measured and exposed in OTEL APM.

### Actual behavior

Ktor Client instrumentation is not measured and exposed in OTEL APM.

### Javaagent or library instrumentation version

Version 1.29.0

### Environment

Kotlin - 1.8.22
ktor - 2.3.4

### Additional context

It is developed as an SDK so that code can be imported and used on other systems.

**Comment by laurit** [comment]
Please provide a minimal sample app that reproduces the issue.
