### ISSUE TITLE
A plan for opentelemetry-java-instrumentation to support JDK 20?

### ISSUE THREAD

**Issue by sadadw1** [open-telemetry/opentelemetry-java-instrumentation#9505]
### Is your feature request related to a problem? Please describe.

Does opentelemetry-java-instrumentation plan to support JDK 20? Specifically:

1. JVM support for ZGC monitoring.
2. Previously, traces were chained between Threads, but now there's a need to propagate them between coroutines.
3. opentelemetry-java-instrumentation used to internally store Context using ThreadLocal. However, in the context of coroutines, ThreadLocal is not an ideal solution.

### Describe the solution you'd like

opentelemetry-java-instrumentation support JDK 20

**Comment by tylerbenson** [comment]
For clarification, by coroutines do you mean virtual threads?

**Comment by trask** [comment]
hi @sadadw1! we discussed in the weekly Java meeting today and I added notes here: #9534

I wasn't clear about some of your points above though, can you expand here in this issue of anything not mentioned in #9534? thx!

**Comment by sadadw1** [comment]
> For clarification, by coroutines do you mean virtual threads?

yes, you are right

**Comment by SylvainJuge** [comment]
Hi @sadadw1 , as @trask mentioned in his last comment support for virtual threads (and also the thread-local) is already described in #9534 , could you describe what do you mean exactly with `JVM support for ZGC monitoring.` ?

In general, if there is something to change it's better to keep track in a separate issue as work and progress on both topics might not be done at the same time.
