### ISSUE TITLE
Custom prefix for attributes from logback MDC

### ISSUE THREAD

**Issue by SHaaD94** [open-telemetry/opentelemetry-java-instrumentation#9506]
### Is your feature request related to a problem? Please describe.

Then I use MDC while sending logs, I expect to see the attributes delivered as is to the end system. Instead prefix `logback.mdc.` is being attached to all such keys. 
<img width="383" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/10290975/2a6c71b8-b43e-4ca4-bbbd-a75f1e8ae7c6">

### Describe the solution you'd like

I would like to have this prefix parameterized with `logback.mdc.` as default value. Parameter name could be something like `mdcAttributesPrefix`.

### Describe alternatives you've considered

I could probably drop this prefix on centralized collector side/ingesting side, but it could be done on client side

### Additional context

Would be happy to raise a PR with such change.

Thank you

**Comment by trask** [comment]
hi @SHaaD94! we discussed this in the weekly Java meeting today and we think it makes sense to drop the prefix for MDC attributes (for all users).

Setting MDC attributes seems like the equivalent of setting log attributes, and we want users to use the existing Java logging frameworks for this, so it makes sense to just stamp MDC attributes directly onto log records (without a prefix).

If we see a need for prefix in the future we can add that as an opt-in (and configurable) feature.

If you are able to send a PR removing the prefix on MDC attributes across both logback and log4j that would be great!

**Comment by SHaaD94** [comment]
Hi @trask and thanks for prompt response.

I raised a [PR](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9536), with a change.

**Comment by SHaaD94** [comment]
Hi @trask.

Could you please help to merge the PR above, unless there is some more stuff needed to be fixed from my side.

Thanks in advance

**Comment by breedx-splk** [comment]
I think this feature is in place now, and was included in the [2.0.0 release](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.0.0). If I'm mistaken, please reopen. Thanks!
