### ISSUE TITLE
Is there some way to append instrumentation on the default instrumentation?

### ISSUE THREAD

**Issue by saulocn** [open-telemetry/opentelemetry-java-instrumentation#9522]
### Is your feature request related to a problem? Please describe.

I'm testing OpenTelemetry on an application that have some methods, but we neet do instrument some internal methods like driver `getConnection`.
Is ther some way to do that?
I tested the environment variable `OTEL_INSTRUMENTATION_METHODS_INCLUDE` but i noticed that when we set it, it's override the default instrumentation that gets all application methods on a span.

### Describe the solution you'd like

Mayme the `OTEL_INSTRUMENTATION_METHODS_INCLUDE` could only append the custom instrumentation on the default instrumentation and don't override it if it's possible.

### Describe alternatives you've considered

Mayme sobe way to do it programatically setting spans in internal methods.

**Comment by trask** [comment]
hi @saulocn! this is probably the easiest way to create new spans: https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/

**Comment by saulocn** [comment]
Hi @trask ! Yeah, i saw the docs. That's where saw the config (`OTEL_INSTRUMENTATION_METHODS_INCLUDE` or `otel.instrumentation.methods.include) but when i try this config i lost the default span config.
When i don't use this config, all application methods are instrumented, but when i use it, only the methods in the env are instrumented.
Thanks for the attention!

**Comment by trask** [comment]
hi @saulocn, we wouldn't expect `otel.instrumentation.methods.include` to affect the existing instrumentation, can you give more specific details on what you are setting that property to, and which existing instrumentation is affected? thx!
