### ISSUE TITLE
Support for Pekko (fork of Akka)

### ISSUE THREAD

**Issue by samwright** [open-telemetry/opentelemetry-java-instrumentation#9528]
### Is your feature request related to a problem? Please describe.

Apache Pekko (https://pekko.apache.org/) is a fork of Akka 2.6 with an Apache 2.0 license. My company [Kognic](https://www.kognic.com) is making the switch over to Pekko, and we're starting to roll out otel's auto-instrumentation, so we're keen to add instrumentation for Pekko.

I've had a go at it myself, and it seems to work well! My process here was:

1. Copy the akka instrumentation modules
2. Refactor everything to point to pekko classes
3. Rename everything from "akka" to "pekko"
4. In `ExecutorMatchers` and `FutureInstrumentation` copy references to akka to also refer to pekko

The only change I noticed is that there is no equivalent to the `akka.dispatch.forkjoin.ForkJoinPool` which the
 `:instrumentations:akka-actor-fork-join-2.5` module was instrumenting.
 As such I didn't copy that module over.

I've instrumented a pekko-based test app and am seeing metrics and traces being exported as I found before with an akka-based test app.

Here's my PR: https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9527

### Describe the solution you'd like

If you like my solution, let's merge it?

**Comment by laurit** [comment]
Resolved with https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9527
