### ISSUE TITLE
JAR versions don't correspond to SDK versions

### ISSUE THREAD

**Issue by mpayne-coveo** [open-telemetry/opentelemetry-java-instrumentation#9540]
### Describe the bug

The most recently published jar, v1.30.0, corresponds to the sdk version v1.30.1. We have some automation in place that performs automatic updates to our SDK version, then pulls the same version for the JAR as well so that they correspond. Is there a reason why the versions don't match? Would it be an issue to publish jar versions that sync exactly with the sdk counterparts?

### Steps to reproduce

If you have a `pom.xml` with a variable that's used to control opentelemetry sdk/bom versions like-
```
<otel.instrumentation.version>1.30.1</otel.instrumentation.version>
```
and a dependabot mechanism that's used to keep this version up-to-date, then some bash script in your infra like-
```
OTEL_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=otel.instrumentation.version -q -DforceStdout)
wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v${OTEL_VERSION}/opentelemetry-javaagent.jar
```
This fails, since it can't find `1.30.1`.

### Expected behavior

Versions between the sdk/jar correspond exactly and are in sync with each other.

### Actual behavior

Versions do not correspond exactly.

### Javaagent or library instrumentation version

1.30.0

### Environment

**JDK**:
**OS**:

**Comment by trask** [comment]
hi @mpayne-coveo! check out #9525, hopefully that should explain what's going on, and why these versions will diverge even more in the future, thx

**Comment by mpayne-coveo** [comment]
Great, thank you! This provides more insight, we'll change up the automation on our side.
