### ISSUE TITLE
logback instrumentation loses context data

### ISSUE THREAD

**Issue by otbe** [open-telemetry/opentelemetry-java-instrumentation#9543]
### Describe the bug

Hello 👋

Im playing around with the current java agent and a very simple spring boot app. My goal is to ship the logs via OTLP to a collector sidecar. This works amazingly well and was easy to do. However, after taking a closer look to the logs being shipped  I missed certain things.

Lets say my application looks like this:

```
@Slf4j
class MyService {
   public MyService() {
        LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
        loggerContext.putProperty("hello", "world");
    }

    public void doIt() {
        MDC.put("foo", "bar");
        MDC.put("bar", "baz");

        log.info("Did it");
    }
}
```

After configuring some properties for the java agent (I tried a lot of combinations but in total these):
```
-Dotel.instrumentation.logback-appender.experimental-log-attributes=true 
-Dotel.instrumentation.logback-appender.experimental.capture-mdc-attributes=* 
-Dotel.instrumentation.logback-mdc.add-baggage=true 
-Dotel.instrumentation.logback-appender.experimental.capture-key-value-pair-attributes=true
```

I was able to see the MDC values and some thread (name, id) meta data, however Im not able to see data from the `LoggerContext`. We add meta data early in the application lifecycle which does not change afterwards. 

My logback-spring.xml looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="nop"
              class="ch.qos.logback.core.helpers.NOPAppender">
    </appender>

    <root>
        <appender-ref ref="nop"/>
    </root>
</configuration>
```
My idea was that I don't need to ship the logs anywhere if the java agent takes over shipping via autoinstrumentation of the NOP appender. Seems to work quite fine. 

I tried with a Spring Boot 2/logback 1.2.x/slf4 1.7/java11 and a Spring Boot 3/logback 1.4/slf4 2.x/java17 app. Result was the same for both.

Usually we use the aws flavoured java agent but I tried both to be sure its not related to the aws one. Interestingly I also dont see the `AWS-XRAY-TRACE-ID` in the log entries which should be added here: https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/instrumentation/logback-1.0/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/logback_1_0/AwsXrayLoggingEventInstrumentation.java#L90
Before trying to use the OTLP log shipping we used the `logstash-logback-appender` and both `AWS-XRAY-TRACE-ID` and our custom context data properly showed up in the log entries.

Is this expected behaviour or is there a way to get the context data into the logs?

### Steps to reproduce

No repro yet but I can try to setup something if this is considered to work as I expect.

### Expected behavior

Would be nice to have this context data added as attributes/resources attributes :)

### Actual behavior

Thats the log entry that gets shipped to the collector.

| 2023-09-23T10:43:45.556+02:00 | Resource SchemaURL: https://opentelemetry.io/schemas/1.21.0
| 2023-09-23T10:43:45.556+02:00 | Resource attributes:
| 2023-09-23T10:43:45.556+02:00 | -> aws.ecs.container.arn: Str(foo)
| 2023-09-23T10:43:45.556+02:00 | -> aws.ecs.container.image.id: Str(foo)
| 2023-09-23T10:43:45.556+02:00 | -> aws.ecs.launchtype: Str(fargate)
| 2023-09-23T10:43:45.556+02:00 | -> aws.ecs.task.arn: Str(foo)
| 2023-09-23T10:43:45.556+02:00 | -> aws.ecs.task.family: Str(foo)
| 2023-09-23T10:43:45.556+02:00 | -> aws.ecs.task.revision: Str(1)
| 2023-09-23T10:43:45.556+02:00 | -> cloud.platform: Str(aws_ecs)
| 2023-09-23T10:43:45.556+02:00 | -> cloud.provider: Str(aws)
| 2023-09-23T10:43:45.556+02:00 | -> container.id: Str(foo)
| 2023-09-23T10:43:45.556+02:00 | -> container.image.name: Str(foo)
| 2023-09-23T10:43:45.556+02:00 | -> container.image.tag: Str(foo)
| 2023-09-23T10:43:45.556+02:00 | -> container.name: Str(app)
| 2023-09-23T10:43:45.556+02:00 | -> host.arch: Str(amd64)
| 2023-09-23T10:43:45.556+02:00 | -> host.name: Str(foo.compute.internal)
| 2023-09-23T10:43:45.556+02:00 | -> os.description: Str(Linux 5.10.186-179.751.amzn2.x86_64)
| 2023-09-23T10:43:45.556+02:00 | -> os.type: Str(linux)
| 2023-09-23T10:43:45.556+02:00 | -> process.command_args: Slice(....)
| 2023-09-23T10:43:45.556+02:00 | -> process.executable.path: Str(/usr/lib/jvm/java-17-amazon-corretto/bin/java)
| 2023-09-23T10:43:45.556+02:00 | -> process.pid: Int(34)
| 2023-09-23T10:43:45.556+02:00 | -> process.runtime.description: Str(Amazon.com Inc. OpenJDK 64-Bit Server VM 17.0.8.1+8-LTS)
| 2023-09-23T10:43:45.556+02:00 | -> process.runtime.name: Str(OpenJDK Runtime Environment)
| 2023-09-23T10:43:45.556+02:00 | -> process.runtime.version: Str(17.0.8.1+8-LTS)
| 2023-09-23T10:43:45.556+02:00 | -> telemetry.sdk.version: Str(1.30.1)
| 2023-09-23T10:43:45.556+02:00 | -> telemetry.auto.version: Str(1.30.0-aws)
| 2023-09-23T10:43:45.556+02:00 | -> telemetry.sdk.language: Str(java)
| 2023-09-23T10:43:45.556+02:00 | -> telemetry.sdk.name: Str(opentelemetry)
| 2023-09-23T10:43:45.556+02:00 | ScopeLogs #0
| 2023-09-23T10:43:45.556+02:00 | ScopeLogs SchemaURL:
| 2023-09-23T10:43:45.556+02:00 | InstrumentationScope foo.MyService
| 2023-09-23T10:43:45.556+02:00 | LogRecord #0
| 2023-09-23T10:43:45.556+02:00 | ObservedTimestamp: 2023-09-23 08:43:44.563790608 +0000 UTC
| 2023-09-23T10:43:45.556+02:00 | Timestamp: 2023-09-23 08:43:44.563 +0000 UTC
| 2023-09-23T10:43:45.556+02:00 | SeverityText: INFO
| 2023-09-23T10:43:45.556+02:00 | SeverityNumber: Info(9)
| 2023-09-23T10:43:45.556+02:00 | Body: Str(Did it)
| 2023-09-23T10:43:45.556+02:00 | Attributes:
| 2023-09-23T10:43:45.556+02:00 | -> logback.mdc.bar: Str(baz)
| 2023-09-23T10:43:45.556+02:00 | -> logback.mdc.foo: Str(bar)
| 2023-09-23T10:43:45.556+02:00 | -> thread.id: Int(48)
| 2023-09-23T10:43:45.556+02:00 | -> thread.name: Str(Thread-5)
| 2023-09-23T10:43:45.556+02:00 | Trace ID:
| 2023-09-23T10:43:45.556+02:00 | Span ID:
| 2023-09-23T10:43:45.556+02:00 | Flags: 0

### Javaagent or library instrumentation version

1.30.0

### Environment

**JDK**: corretto 17/11
**OS**: amzn2

Spring Boot 2/logback 1.2.x/slf4 1.7/java11 
Spring Boot 3/logback 1.4/slf4 2.x/java17

**Comment by breedx-splk** [comment]
Hey @otbe sorry for the delay. Please have a look at https://opentelemetry.io/docs/zero-code/java/spring-boot-starter/out-of-the-box-instrumentation/#logback and note that there was a feature merged a few days after you logged this. You probably just want to enable `otel.instrumentation.logback-appender.experimental.capture-logger-context-attributes`.

I assume that you've probably worked this out by now, but wanted to follow up regardless.

Feel free to let us know either way. Cheers.
