### ISSUE TITLE
Suspected memory leak

### ISSUE THREAD

**Issue by xiangtianyu** [open-telemetry/opentelemetry-java-instrumentation#9550]
### Describe the bug

My application caused oom and i dump the heap, and find it might be memory leak.

<img width="985" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/10825900/8e58d91d-4f19-4b36-a16f-29641111d451">
<img width="808" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/10825900/a4f1c455-811b-4fe5-bb5e-8da1ff213e23">
<img width="1087" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/10825900/c436259e-12d1-4fdc-91fc-0bf357a2f548">

### Steps to reproduce

Some applications will oom when running for a period of time.

### Expected behavior

Run with normal memory 

### Actual behavior

OOM

### Javaagent or library instrumentation version

1.14.0

### Environment

**JDK**: OpenJ9 jdk8
**OS**: ubuntu20

**Comment by xiangtianyu** [comment]
I know the 1.14.0 is an old version, but we cannot easily update the version since we are widely used in our prd env.

**Comment by laurit** [comment]
All know issues with excessive memory usage from WeakLockFreeCache were solved a while ago, I'd suggest you to upgrade.

**Comment by xiangtianyu** [comment]
> All know issues with excessive memory usage from WeakLockFreeCache were solved a while ago, I'd suggest you to upgrade.

Emmm, which version is the proper one? I want to get the most cheap cost to upgrade. The newest version has too much gap.

**Comment by laurit** [comment]
It is hard to say just based on the screenshot. Probably either https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.25.0 or https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.21.0
