### ISSUE TITLE
Have Tracer "handle request" both at start and end

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#957]
I think one of the reasons we have to customize the `Tracer` in many instrumentations is because we expect much information to be available when processing a request, even though the instrumented library may be split into multiple lifecycles that span across what we're exposing in Tracer. I think a way to work with this without customizing `Tracer` so much is in `onRequest`, collect as much information about the request as possible (only really useful if we switch to setting these on `Span.Builder` which we currently don't do but probably should), ignoring e.g. `null` values, and in `onResponse`, read them again, presumably any previous `null` are filled by then. This is the approach Brave takes FWIW.

**Comment by trask** [comment]
this is moving forward in #2596

**Comment by trask** [comment]
Closing, implementation of new Instrumenter API is being tracked in #2713
