### ISSUE TITLE
netty pipeline remove method return the otlp handler

### ISSUE THREAD

**Issue by peachisai** [open-telemetry/opentelemetry-java-instrumentation#9580]
### Describe the bug

Netty instrumentation adds its own handlers into the Netty pipeline. When calling the ```removeLast``` or ```removeFirst``` method, if the removed handler is one that was added by the instrumentation, it should remove a business handler as well. Though OTLP indeed does this, the result is still an OTLP handler rather than a business handler.
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/96932958/e97aa3b3-43d7-49b4-8d50-3f6df665a7d6)

### Steps to reproduce

as the description

### Expected behavior

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/96932958/bfd4acde-33c8-4066-b235-4912a2ba6ad9)

### Actual behavior

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/96932958/89b7272d-0653-432b-a641-283dbd6c008d)

### Javaagent or library instrumentation version

1.14.0

### Environment

**JDK**:
**OS**:

**Comment by trask** [comment]
hi @peachisai!

> 1.14.0

this is quite old, can you verify whether your issue still exists with the latest release?

**Comment by laurit** [comment]
I tested it and the issue seems to be present for `removeLast`. As far as I can tell `removeFirst` works as expected.

**Comment by peachisai** [comment]
> hi @peachisai!
> 
> > 1.14.0
> 
> this is quite old, can you verify whether your issue still exists with the latest release?

It still exists in the latest release. I have seen the pull request for the fix, and I will close my issue.
