### ISSUE TITLE
Inconsistency in gRPC onMessage() instrumentation between Client and Server

### ISSUE THREAD

**Issue by kenfinnigan** [open-telemetry/opentelemetry-java-instrumentation#9605]
### Describe the bug

It may not be a bug, but I noticed that `TracingClientIntercepter.onMessage()` wraps the call to `delegate().onMessage()` inside a `Scope`:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/540b9fbb9868c23033e3c7b2a5c247d2695cb279/instrumentation/grpc-1.6/library/src/main/java/io/opentelemetry/instrumentation/grpc/v1_6/TracingClientInterceptor.java#L139-L151

but `TracingServerIntercepter.onMessage()` does not wrap the `delegate().onMessage()` inside a `Scope`:
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/540b9fbb9868c23033e3c7b2a5c247d2695cb279/instrumentation/grpc-1.6/library/src/main/java/io/opentelemetry/instrumentation/grpc/v1_6/TracingServerInterceptor.java#L124-L134

Is there a deliberate reason for this, or is it an omission?

### Steps to reproduce

I've instrumented the `onMessage()` method of `io.grpc.ServerCall$Listener`, except for when it's the `TracingServerInterceptor` from OTeL, and the span in the Context of the execution is not the `SERVER` span, but an empty one.

If needed I can push a branch showing broken tests

### Expected behavior

I expected the `onMessage()` to be wrapped in `context.makeCurrent()` to have the active `SERVER` span available for the delegated `onMessage()` execution.

### Actual behavior

Only span available is the empty ROOT span

### Javaagent or library instrumentation version

v1.2.7 (But code in main has the same problem)

### Environment

**JDK**: Temurin-17.0.8.1+1
**OS**: MacOSX

**Comment by laurit** [comment]
> Is there a deliberate reason for this, or is it an omission?

It was deliberately done in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2634 Otel context is now restored along with grpc context with `io.grpc.Contexts$ContextualizedServerCallListener`
