### ISSUE TITLE
Ktor 2.0 client intrumenter don't show route in span name

### ISSUE THREAD

**Issue by acunap** [open-telemetry/opentelemetry-java-instrumentation#9607]
### Describe the bug

<img width="246" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/53953899/ded8ac3f-a334-4194-ae0c-0ab79c0b7abe">

Because of this instrumenter is using `io.opentelemetry.instrumentation.api.instrumenter.http.HttpSpanNameExtractor` the route is not part of the name. here is why:

```
private String extractRoute(REQUEST request) {
    if (getter instanceof HttpServerAttributesGetter) {
      return ((HttpServerAttributesGetter<REQUEST, ?>) getter).getHttpRoute(request);
    }
    return null;
}
```

In this case, the `getter` is an instance of `HttpClientAttributesGetter` so it returns `null` always.

How can I send the route in the span name using this instrumenter?

### Steps to reproduce

Install Ktor 2.0 plugin to Ktor REST API and send a span.

### Expected behavior

The span contains the HTTP method and the route name as it works with incoming requests.

### Actual behavior

The span name is empty

### Javaagent or library instrumentation version

1.30.0-alpha

**Comment by breedx-splk** [comment]
Hey @acunap, thanks for the issue. This is by design. Please see the [otel semantic conventions for http client span naming](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#name):

```
HTTP client spans have no http.route attribute since client-side instrumentation is not generally aware of the "route", and therefore HTTP client spans SHOULD be [{method}](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/http/http-spans.md#method-placeholder).
```

If you absolutely need this functionality you would have to build it yourself or take up the issue with the specification.
