### ISSUE TITLE
Indicating agent was used in spans

### ISSUE THREAD

**Issue by anuraaga** [open-telemetry/opentelemetry-java-instrumentation#962]
I realized that right now we use the same tracer name for library and auto instrumentation

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/master/instrumentation/armeria-1.0/library/src/main/java/io/opentelemetry/instrumentation/armeria/v1_0/server/ArmeriaServerTracer.java#L45

And the `Resource` has attributes related to the OTel SDK. I think this means that there isn't any way to determine whether spans came from the agent or not, which may be useful (x-ray has metrics to see how many people use an agent vs manual instrumentation). Should we add an attribute to the resource to indicate that the agent is running? Or maybe we should make sure tracer name is different. I lean towards former since it seems simpler and has the important information of whether they are an agent user or not. Or if it's not actually important in a general sense we don't need to add anything :)

**Comment by iNikem** [comment]
I think that having different names for tracers and thus different instrumentation library names is more idiomatic

**Comment by trask** [comment]
> Should we add an attribute to the resource to indicate that the agent is running?

Yes, @iNikem opened https://github.com/open-telemetry/opentelemetry-specification/pull/799

> Or maybe we should make sure tracer name is different.

Also yes 😄.

**Comment by mateuszrzeszutek** [comment]
Implemented in https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1112, closing
