### ISSUE TITLE
Making use of agentArgs in the OpenTelemetryAgent to set System Properties

### ISSUE THREAD

**Issue by sarkisjad** [open-telemetry/opentelemetry-java-instrumentation#9645]
### Is your feature request related to a problem? Please describe.

I was using the opentelemetry-javaagent in order to make use of OTel auto-instrumentation. 
While I was looking at the code, I noticed that the use of agentArgs inside the [premain and agentmain](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/6980b693dca42e10715f1ca54f6a9ea52a2256d5/javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/OpenTelemetryAgent.java) classes are unused.
I think making use of this parameter would be benificial. 

In my case, I make use of the agentmain() method because I am loading the javaagent dynamically. 
While I do so, I also want to add, let's say, the following system property dynamically, and not directly from the command line:
`-Dotel.exporter.otlp.endpoint=localhost:8800`

I can only add the property dynamically because I can render the value of the URL at runtime.

### Describe the solution you'd like

As a solution, I passed the value of the key `otel.exporter.otlp.endpoint` in the `loadAgent()` method. This method allowed me to start the javaagent dynamically to the target VM by passing to it the path of the javaagent. More information of the method can be found [here](https://docs.oracle.com/javase/8/docs/jdk/api/attach/spec/com/sun/tools/attach/VirtualMachine.html#loadAgent-java.lang.String-java.lang.String-).
I can also pass options, which is where I passed the value of the key (the URL of the endpoint). The value is then passed to the [agentmain()](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/6980b693dca42e10715f1ca54f6a9ea52a2256d5/javaagent-bootstrap/src/main/java/io/opentelemetry/javaagent/OpenTelemetryAgent.java#L48) method as `agentArgs`.

Since `agentArgs` is not used in the method, the new system property can't be added. 
My solution to the problem was to simply create my own javaagent that would make a call the to the `premain()` and `agentmain()` methods in OpenTelemetry. But before I made those calls, I added this code to each method. 
`System.setProperty("otel.exporter.otlp.endpoint", agentArgs);`

I understand that if we were to generalize the feature, there would be some kind of a parser that would read the `agentArgs` string. A better idea would be to pass the key:value pairs together in the options and parse them in the `premain()` and `agentmain()` methods. Additionally, if we wanted to pass multiple system properties, we could comma-seperate them. 

### Additional context

This feature is more useful for dynamically loading javaagent. 
Indeed, adding system properties can be done directly from the command line if we were to add a javaagent statically, rendering their passing in the options as redundant.

**Comment by breedx-splk** [comment]
I don't understand the ask here. We already support environment variables and system properties and config files, but now you're asking for yet another way to pass configuration to the agent? Are you not able to set the system properties in code because it originates in a separate process or something?

In any case, we haven't talked about dynamic attach much in recent years, and I'm not sure that supporting dynamic attach is very desirable considering [JEP 451](https://openjdk.org/jeps/451).
