### ISSUE TITLE
Enable Otel JDBC instrumentation for multiple data sources

### ISSUE THREAD

**Issue by toL-A-edoC** [open-telemetry/opentelemetry-java-instrumentation#9660]
### Describe the bug

Hey Team!

We use in our project **two data sources.** We want to enhance both with the Open Telemetry Driver so we are able to view JDBC traces in AWS for both data sources. 

When I build (mvn clean install) the application I get the following error:
```[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.2.5.Final:build (default) on project rest: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: jakarta.enterprise.inject.spi.DeploymentException: Found 2 deployment problems:
[ERROR] [1] Data source '<default>' is using unsupported JDBC driver 'io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver', please activate JDBC instrumentation by setting the 'quarkus.datasource.jdbc.telemetry' configuration property to 'true' instead
[ERROR] [2] Data source 'nativeDataSource' is using unsupported JDBC driver 'io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver', please activate JDBC instrumentation by setting the 'quarkus.datasource.jdbc.telemetry' configuration property to 'true' instead
[ERROR] 	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1443)
[ERROR] 	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:174)
[ERROR] 	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:502)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1623)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] 	Suppressed: io.quarkus.runtime.configuration.ConfigurationException: Data source '<default>' is using unsupported JDBC driver 'io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver', please activate JDBC instrumentation by setting the 'quarkus.datasource.jdbc.telemetry' configuration property to 'true' instead
[ERROR] 		at io.quarkus.opentelemetry.deployment.OpenTelemetryProcessor.validateDataSourcesWithEnabledTelemetry(OpenTelemetryProcessor.java:191)
[ERROR] 		... 9 more
[ERROR] 	Suppressed: io.quarkus.runtime.configuration.ConfigurationException: Data source 'nativeDataSource' is using unsupported JDBC driver 'io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver', please activate JDBC instrumentation by setting the 'quarkus.datasource.jdbc.telemetry' configuration property to 'true' instead
[ERROR] 		at io.quarkus.opentelemetry.deployment.OpenTelemetryProcessor.validateDataSourcesWithEnabledTelemetry(OpenTelemetryProcessor.java:191)
[ERROR] 		... 9 more
```

Here are both configurations in Quarkus for both data sources:
```
# Default data source
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.datasource.jdbc.telemetry=true
quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
quarkus.datasource.jdbc.url=<URL>
quarkus.datasource.username=<Username>
quarkus.datasource.password=<Password>
```

```
# Native data source
quarkus.datasource.nativeDataSource.db-kind=other
quarkus.datasource.nativeDataSource.jdbc.driver=io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver
quarkus.datasource.nativeDataSource.jdbc.url=<URL>
quarkus.datasource.nativeDataSource.username=<Username>
quarkus.datasource.nativeDataSource.password=<Password>
```

Best regards!

### Steps to reproduce

As seen earlier both configurations with command `mvn clean install`

### Expected behavior

I thought that my build accepts both configurations of the data sources.

### Actual behavior

The described error message above.

### Javaagent or library instrumentation version

1.30.0-alpha

### Environment

**JDK**: 11.0.19
**OS**: Mac OS X 13.5.2 x85_64
**Mvn**: 3.9.3
**Quarkus**: 3.2.5.Final

### Additional context

If I remove the second "native" data source, everything seems to work. Is it possible that multiple data sources are not supported?

**Comment by laurit** [comment]
Your chances of getting this answered would be better if you'd ask this from quarkus developers. cc @brunobat

**Comment by brunobat** [comment]
Quarkus should not be instrumented with the OTel agent because of the reactive/imperative context propagation and because the agent won't work on native mode. Please use the `quarkus-opentelemetry` extension along with the `opentelemetry-jdbc` library dependency. Then just activate this property:
`quarkus.datasource.jdbc.telemetry=true`

This way you don't need to configure any driver different driver.
See: https://quarkus.io/version/3.2/guides/opentelemetry#jdbc

**Comment by brunobat** [comment]
Clarifying a bit more... The OTel agent uses `ThreadLocal` to keep the OTel Context. 
This is fine for classic imperative code but Quarkus is built on to of Vert.x. The agent doesn't now how to properly propagate the the OTel context between `ThreadLocal` and the Vert.x duplicated context used in the reactive code of Vert.x and Smallrye Mutiny. Quarkus makes sure this propagation happens properly. The agent is oblivious to this because it's too generic and there are many different reactive stacks, each one with it's own context propagation mechanism. 
In the end you might end up with disconnected spans.

**Comment by laurit** [comment]
> The OTel agent uses ThreadLocal to keep the OTel Context. This is fine for classic imperative code but Quarkus is built on to of Vert.x. The agent doesn't now how to properly propagate the OTel context between ThreadLocal and the Vert.x

Agent's internal usage of `ThreadLocal` for context propagation isn't really an issue. We do have some instrumentation for vert.x and it seems to be working fine. If there is interest from users and contributors existing instrumentation can be added and new instrumentations developed to cover a wider range of use cases.

**Comment by trask** [comment]
> Quarkus should not be instrumented with the OTel agent because of the reactive/imperative context propagation

@brunobat just want to clarify that this is not true

> The agent is oblivious to this because it's too generic and there are many different reactive stacks, each one with it's own context propagation mechanism.

this is not true either, the agent is very aware of many different reactive stacks, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md

**Comment by brunobat** [comment]
@trask the agent seems to work ok when we use simple rest endpoints, both classic and Reactive, however we got some problems with code leveraging Mutiny.
Now it looks much better than the last time I checked, however there is no way to be sure unless I create a test suit... I will add that to the roadmap. 
In any case, if you need native mode, the agent won't work. I've seen one examples in the wild using the OTel agent in native mode, but that's not the case with Quarkus. 

The current recommendation for Quarkus is to use the extension and not the Agent.

**Comment by trask** [comment]
> we got some problems with async code leveraging Mutiny

please report issues to this repo in the future. there are definitely users who are using Quarkus with the OpenTelemetry Java agent who will benefit from your reports.

> I've seen one example in the wild using the OTel agent in native mode

you've seen one more than me then 😂
