### ISSUE TITLE
Kafka can not (fully) customize consumer instrumenter

### ISSUE THREAD

**Issue by kares** [open-telemetry/opentelemetry-java-instrumentation#9683]
### Is your feature request related to a problem? Please describe.

There's a [feature in the internal `KafkaInstrumenterFactory`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v1.31.0/instrumentation/kafka/kafka-clients/kafka-clients-common/library/src/main/java/io/opentelemetry/instrumentation/kafka/internal/KafkaInstrumenterFactory.java#L75-L79) using the `messagingReceiveInstrumentationEnabled` flag, which causes the "consumer operation instrumenter" to consider the OTel default text-map extractors: 
```java
    if (messagingReceiveInstrumentationEnabled) {
      builder.addSpanLinksExtractor(
          new PropagatorBasedSpanLinksExtractor<>(
              openTelemetry.getPropagators().getTextMapPropagator(),
              KafkaConsumerRecordGetter.INSTANCE));
      return builder.buildInstrumenter(SpanKindExtractor.alwaysConsumer());
    } else {
      return builder.buildConsumerInstrumenter(KafkaConsumerRecordGetter.INSTANCE);
    }
```
https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v1.31.0/instrumentation/kafka/kafka-clients/kafka-clients-common/library/src/main/java/io/opentelemetry/instrumentation/kafka/internal/KafkaInstrumenterFactory.java#L143-L151

However, when using **kafkaclients.v2_6** and it's `KafkaTelemetryBuilder` this feature is not exposed (there's [no way to change the flag's default](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v1.31.0/instrumentation/kafka/kafka-clients/kafka-clients-2.6/library/src/main/java/io/opentelemetry/instrumentation/kafkaclients/v2_6/KafkaTelemetryBuilder.java#L89-L92) `false` value), I am wondering whether this is intentional or not...

### Describe the solution you'd like

Have a supported option which would use the configured OTel text-map extractors with Kafka (such as the baggage extractor)?

### Describe alternatives you've considered

Alternative is to use [`addConsumerAttributesExtractors`](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v1.31.0/instrumentation/kafka/kafka-clients/kafka-clients-2.6/library/src/main/java/io/opentelemetry/instrumentation/kafkaclients/v2_6/KafkaTelemetryBuilder.java#L46), was still wondering if there's more that could be done.

### Additional context

Haven't checked the full sources, maybe this is by design...

**Comment by trask** [comment]
it looks like the same property has been exposed on `SpringKafkaTelemetryBuilder` already:

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/b64bd208fa52174559adfa5d4838ff21bae0665e/instrumentation/spring/spring-kafka-2.7/library/src/main/java/io/opentelemetry/instrumentation/spring/kafka/v2_7/SpringKafkaTelemetryBuilder.java#L54

seems reasonable to expose it in other library instrumentation as needed
