### ISSUE TITLE
Cannot use Java 17 Metrics in 1.31.0

### ISSUE THREAD

**Issue by dmarsh26** [open-telemetry/opentelemetry-java-instrumentation#9696]
### Describe the bug

Getting class not found:
Caused by: java.lang.ClassNotFoundException: io.opentelemetry.extension.incubator.metrics.LongUpDownCounterAdviceConfigurer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 161 common frames omitted

When using

            <dependency>
                <groupId>io.opentelemetry</groupId>
                <artifactId>opentelemetry-bom</artifactId>
                <version>1.31.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-instrumentation-bom</artifactId>
                <version>1.31.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>io.opentelemetry.instrumentation</groupId>
                <artifactId>opentelemetry-instrumentation-bom-alpha</artifactId>
                <version>1.31.0-alpha</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        <dependency>
            <groupId>io.opentelemetry</groupId>
            <artifactId>opentelemetry-extension-incubator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-runtime-telemetry-java17</artifactId>
        </dependency>

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/7771071/933132dc-6de6-4e89-a46a-8e6657d8e59b)

Seems I do not get all the classes from: opentelemetry-extension-incubator ?

### Steps to reproduce

Create Manual Instrumentation project with above dependencies.

        OpenTelemetry openTelemetry = OpenTelemetrySdk.builder()
                .buildAndRegisterGlobal();

        // Register runtime metrics instrumentation
        RuntimeMetrics.builder(openTelemetry)
                .enableFeature(JfrFeature.GC_DURATION_METRICS)
                .enableFeature(JfrFeature.CPU_UTILIZATION_METRICS)
                .enableFeature(JfrFeature.LOCK_METRICS)
                .enableFeature(JfrFeature.THREAD_METRICS)
                .enableFeature(JfrFeature.MEMORY_POOL_METRICS)
                .enableFeature(JfrFeature.CLASS_LOAD_METRICS)
                .enableFeature(JfrFeature.BUFFER_METRICS)
                .build();

### Expected behavior

Classpath should be valid when using correct dependencies and boms.

### Actual behavior

Caused by: java.lang.ClassNotFoundException: io.opentelemetry.extension.incubator.metrics.LongUpDownCounterAdviceConfigurer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 161 common frames omitted

### Javaagent or library instrumentation version

1.31.0 and 1.31.0-alpha

### Environment

**JDK**: Oracle 64 bit 17 JDK
**OS**: Windows 11

**Comment by laurit** [comment]
You sure you haven't mixed dependencies from different versions? Would it be possible for you to provide a sample app that reproduces the issue or at least the full stack trace.

**Comment by dmarsh26** [comment]
Look at the picture of the contents of the Jar. Many files are missing.
Where are they supposed to come from if not that jar?
________________________________

**Comment by dmarsh26** [comment]
It looks like you published a jar with 50% the classes in it? or you moved the stuff around since the JDK 17 artifact was creaed?
________________________________

**Comment by dmarsh26** [comment]
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/7771071/ff02a17d-8110-4bf3-94b4-f915fb4402f1)

**Comment by laurit** [comment]
As can be seen from the last image you are mixing artifacts from versions `1.30.1` and `1.31.0`. `LongUpDownCounterAdviceConfigurer` was deleted in `1.31.0`. Use `1.31.0` for all the otel dependencies.

**Comment by dmarsh26** [comment]
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/7771071/c19afec0-e95d-428b-b72a-01929e861ef9)

**Comment by dmarsh26** [comment]
OK it seems this bom is the culprit I will fix.
            <dependency>
                <groupId>io.micrometer</groupId>
                <artifactId>micrometer-tracing-bom</artifactId>
                <version>1.1.6</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
