### ISSUE TITLE
issue in connecting otel-agent from java through docker

### ISSUE THREAD

**Issue by chhavi-gupta-maxeda** [open-telemetry/opentelemetry-java-instrumentation#9714]
Please help!

Received a lot of error:
[otel.javaagent 2023-10-19 07:28:04:430 +0000] [OkHttp http://172.17.0.1:9080/...] WARN io.opentelemetry.exporter.internal.grpc.GrpcExporter - Failed to export spans. Server responded with gRPC status code 2. Error message: Failed to connect to /172.17.0.1:9080

configuration in dockerfile file:
RUN curl --create-dirs -sSL -o /path/to/splunk-otel-javaagent.jar 'https://github.com/signalfx/splunk-otel-java/releases/download/v1.28.0/splunk-otel-javaagent.jar'
CMD OTEL_EXPORTER_OTLP_ENDPOINT="http://172.17.0.1:9080" java -javaagent:"/path/to/splunk-otel-javaagent.jar"

**Comment by laurit** [comment]
Verify that your container can connect to `172.17.0.1:9080` and that otel collector grpc endpoint is listening on that port.
