### ISSUE TITLE
Support collecting time series data on JVM runtime duration

### ISSUE THREAD

**Issue by Anyuoo** [open-telemetry/opentelemetry-java-instrumentation#9750]
### Is your feature request related to a problem? Please describe.

Runtime-metrics only support time series data related to GC or memory. I am looking for time series data on JVM runtime duration.

### Describe the solution you'd like

is there some instrumentation can support time series data on JVM runtime duration.

**Comment by laurit** [comment]
Could you elaborate what do you mean by `time series data on JVM runtime duration`.

**Comment by Anyuoo** [comment]
My expression is a bit inaccurate. it's mean duration of JVM process execution

**Comment by trask** [comment]
are you looking for "uptime"? (see related https://github.com/open-telemetry/oteps/pull/185)

**Comment by Anyuoo** [comment]
@trask yes, i'm looking`process.uptime`  from `intrumentation` module,  I want to know which instrumentation implements process.uptime?

**Comment by trask** [comment]
there's no `process.uptime` metric yet defined in [semantic conventions](https://github.com/open-telemetry/semantic-conventions)

**Comment by Jojoooo1** [comment]
Any plan on including `process.uptime` as it seems to be defined in https://github.com/open-telemetry/semantic-conventions/blob/main/docs/system/process-metrics.md#metric-processuptime ?

**Comment by laurit** [comment]
Currently we only implement jvm runtime metrics https://opentelemetry.io/docs/specs/semconv/runtime/jvm-metrics/ I'm not aware of any ongoing effort to add this metric. Usually we rely on contributors to submit such PRs.
