### ISSUE TITLE
log4j MDC attribute capture configuration

### ISSUE THREAD

**Issue by stevesea** [open-telemetry/opentelemetry-java-instrumentation#9758]
### Describe the bug

the log4j1 instrumentation uses `otel.instrumentation.log4j-appender.experimental.capture-mdc-attributes`, which aligns with the name of the logback/jboss logging configuration

The log4j2 instrumentation uses `otel.instrumentation.log4j-appender.experimental.capture-context-data-attributes`

can log4j2 instrumentation be updated to use `.capture-mdc-attributes`, to align it with the log4j1, logback and jboss instrumentation?

### Steps to reproduce

n/a

### Expected behavior

if I want to capture MDC attributes, I should use `otel.instrumentation.{instrumentation-name}.experimental.capture-mdc-attributes

### Actual behavior

log4j2 uses '.capture-context-data-attributes'

### Javaagent or library instrumentation version

1.31.0

### Environment

**JDK**: temurin 17
**OS**: centos

**Comment by trask** [comment]
I'm not opposed to this, even though I don't believe Log4j2 calls it "MDC" (either in their API or in their documentation). This could allow us to have a single config, e.g.

```
otel.instrumentation.common.logging.capture-mdc-attributes
```

see also https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8637#issuecomment-1579264473

**Comment by stevesea** [comment]
I'd love to have a single config, rather than having framework-specific configuration flags.

**Comment by zeitlinger** [comment]
I would propose to use `.capture-mdc-attributes` everywhere, because many devs are familiar with that term.
