### ISSUE TITLE
Need more complete instrumentation of Context

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#976]
In particular, if you call `Context.withValues()` directly, and then pass that resulting `Context` back over the bridge to the agent, then you'll get:

```
java.lang.Exception: unexpected context
```

because we are currently expecting all `Context` instances to have been created via the bridge.

**Comment by iNikem** [comment]
@trask @anuraaga We can close this right? gRPC context did go away.

**Comment by trask** [comment]
I think the particular issue above still stands with the new OpenTelemetry `Context` and our existing instrumentation at least.

Let's leave this open until we pull in the new `Context` and revisit how we bridge it.
