### ISSUE TITLE
Document flags used to capture enduser attributes

### ISSUE THREAD

**Issue by laurit** [open-telemetry/opentelemetry-java-instrumentation#9783]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9751 and https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9777 define flags to capture enduser attributes these need to be documented in the website repo where the rest of the common flags are documented.

**Comment by jaydeluca** [comment]
I have a draft PR to add these config options: https://github.com/open-telemetry/opentelemetry.io/pull/3982

Is this what you had in mind? If so I will mark the PR as ready for review.

**Comment by trask** [comment]
there's also these: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/spring/spring-security-config-6.0/javaagent/README.md

**Comment by jaydeluca** [comment]
I updated the PR to include those flags. I added a description for their context based on [this comment](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9777#issuecomment-1808714904), but if I misinterpreted anything I can update it

**Comment by jaydeluca** [comment]
I believe this issue can now be closed as completed unless theres anything else we want documented

**Comment by laurit** [comment]
Thanks.
