### ISSUE TITLE
Disable controller and view spans by default in 2.0

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java-instrumentation#9787]
Discussed in 10/26 SIG meeting, since there are no semantic conventions for controller, view, handler (etc) spans, it seems to make sense to make these opt-in.

Wondering if we should apply this to other INTERNAL spans, e.g. make hibernate instrumentation opt-in?

**Comment by heyams** [comment]
i would like to work on this next. can someone please assign it to me? thanks!

**Comment by heyams** [comment]
@trask/@mateuszrzeszutek what is the name of the system property for handler span?

**Comment by steverao** [comment]
> Discussed in 10/26 SIG meeting, since there are no semantic conventions for controller, view, handler (etc) spans, it seems to make sense to make these opt-in.
> 
> Wondering if we should apply this to other INTERNAL spans, e.g. make hibernate instrumentation opt-in?

Making other instrumentations opt-in when they only produce internal spans, whether we have a final conclusion now?

**Comment by trask** [comment]
I'm not sure if we have a super general recommendation at this point. Do you have a specific use case that we can discuss?

**Comment by steverao** [comment]
> I'm not sure if we have a super general recommendation at this point. Do you have a specific use case that we can discuss?

In PR #10258, @laurit set it to disabled by default. He told me that later in Slack:

> for 2.0 release, we disabled by default a bunch of instrumentations that don’t implement any semantic conventions and only produce internal spans. While there are still other instrumentations that do this and are enabled we may disable more of them in the future. We may revise this decision later and enable this or some of the currently disabled instrumentations by default.

When I saw the issue, so I want to know if there is a more formal decision on this problem?
