### ISSUE TITLE
testBootstrapJar is not cacheable

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java-instrumentation#981]
Gradle says "Caching has not been enabled for the task." for `testBootstrapJar` . Although usually jar tasks are not cacheable in Gradle, we have a lot of them. Each takes couple of seconds, quite a lot of time in total. Can it be made cacheable?

**Comment by anuraaga** [comment]
I think it should be possible, though even better will be to only have one bootstrap jar since I think it's the same for almost all or all of the tests, will play with it :)
