### ISSUE TITLE
Spring Session with Redis storage does not report any spans

### ISSUE THREAD

**Issue by trajano** [open-telemetry/opentelemetry-java-instrumentation#9812]
### Describe the bug

I switched from manual instrumentation using micrometer and OTEL bridge to the agent based instrumentation.  I found that the Redis client calls are no longer being traced.

I don't see anything particular in the logs either.

I've asked here https://github.com/open-telemetry/community/discussions/1777#discussioncomment-7490327 

### Steps to reproduce

I don't have an MVCE but https://github.com/trajano/simple-auth is a simple authentication app where I added the instrumentation.

Basically just webflux + spring-data-redis (no actual repositories) + spring-session

In Docker I download the OTEL agent
```
FROM --platform=$BUILDPLATFORM alpine/curl AS download-otel-agent
RUN curl -sL -o /tmp/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar
```
Then use the following env vars, note I turn stuff on and off while I was trying to debug but no luck.

```
      JAVA_TOOL_OPTIONS: "-javaagent:/opentelemetry-javaagent.jar"
      OTEL_JAVAAGENT_LOGGING: application
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otelcol:4317
      OTEL_PROPAGATORS: tracecontext,baggage,b3,b3multi
      OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED: "false"
      OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED: "true"
      OTEL_INSTRUMENTATION_LETTUCE_ENABLED: "true"
      OTEL_INSTRUMENTATION_LETTUCE_EXPERIMENTAL_SPAN_ATTRIBUTES_ENABLED: "true"
      OTEL_INSTRUMENTATION_COMMON_PEER_SERVICE_MAPPING: "redis=redis"
      OTEL_TRACES_SAMPLER: parentbased_always_off

      SPRING_SESSION_STORETYPE: redis
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_SESSION_TIMEOUT: 86400
      SPRING_SECURITY_USER_NAME: user
      SPRING_SECURITY_USER_PASSWORD: verySecretWord
      SPRING_SECURITY_USER_ROLE: admin
      SPRING_APPLICATION_JSON: |
        {
          "spring": {
            "security": {
              "oauth2": {
                "client": {
                  "registration": {
                    "google": {
                      "client-id": "some-client-id",
                      "client-secret": "some-client-secret",
                      "scope": "openid,email,profile"
                    }
                  }
                }
              }
            }
          }
        }
```

### Expected behavior

Redis client traces are present in jaeger

### Actual behavior

Redis client traces are missing in jaeger

### Javaagent or library instrumentation version

latest

### Environment

FROM amazoncorretto:17-alpine-jdk

**Comment by laurit** [comment]
A minimal sample app that reproduces the issue would be helpful. What version of lettuce are you using? Have you tried removing this line https://github.com/trajano/simple-auth/blob/4afe7544726a16fa8007a56bf3bd26ad90b9c9a5/src/main/kotlin/net/trajano/simpleauth/RequestLoggingFilter.kt#L146 Opentelmetry instrumentation agent registers tracing the same way, I'd guess (didn't attempt to verify) that this line will overwrite the tracing added by the agent.
