### ISSUE TITLE
shardingsphere display the error tag

### ISSUE THREAD

**Issue by Jamel-jun** [open-telemetry/opentelemetry-java-instrumentation#9830]
### Describe the bug

db.name show incorrectly displayed.
db.statement unfused specific value.

### Steps to reproduce

Install the official example operation, the bug appears.

### Expected behavior

db.name It should be the actual database name.
'?' Should be replaced with actual parameters.

### Actual behavior

![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/50609931/7e59cea1-211f-43f9-a742-acec053b9313)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/50609931/4dd725f9-44fb-430d-af09-a1f50ca57cfe)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/50609931/b4a0feb2-32d3-4f7e-a78d-061721fdf0f0)

### Javaagent or library instrumentation version

Javaagent: 1.31.0

### Environment

**JDK**: openjdk:21-jdk-slim
**OS**: Docker
Spring Boot 3.1.5, shardingsphere-jdbc-core-spring-boot-starter 5.2.1.

agent environment.
```

              <OTEL_EXPORTER_OTLP_COMPRESSION>gzip</OTEL_EXPORTER_OTLP_COMPRESSION>
              <OTEL_EXPORTER_OTLP_PROTOCOL>grpc</OTEL_EXPORTER_OTLP_PROTOCOL>
              <OTEL_LOGS_EXPORTER>otlp</OTEL_LOGS_EXPORTER>
              <OTEL_SERVICE_NAME>${service.name}</OTEL_SERVICE_NAME>
              <OTEL_EXPORTER_OTLP_ENDPOINT>https://${sls.project}.${sls.region-endpoint}</OTEL_EXPORTER_OTLP_ENDPOINT>
              <OTEL_EXPORTER_OTLP_HEADERS>x-sls-otel-project=${sls.project},x-sls-otel-instance-id=${sls.trace-instance-id},x-sls-otel-ak-id=${sls.access-key},x-sls-otel-ak-secret=${sls.secret-key}</OTEL_EXPORTER_OTLP_HEADERS>
              <OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED>false</OTEL_INSTRUMENTATION_COMMON_DB_STATEMENT_SANITIZER_ENABLED>
              <OTEL_EXPERIMENTAL_RESOURCE_DISABLED_KEYS>process.executable.path,process.runtime.description,process.runtime.name,host.arch,os.description,os.type,telemetry.sdk.name</OTEL_EXPERIMENTAL_RESOURCE_DISABLED_KEYS>
              <OTEL_JAVAAGENT_LOGGING>application</OTEL_JAVAAGENT_LOGGING>
```

**Comment by laurit** [comment]
> '?' Should be replaced with actual parameters.

we don't replace `?` in prepared statements with the actual values

> db.name It should be the actual database name.

please provide a minimal application that reproduces the issue

**Comment by Jamel-jun** [comment]
> > '?' Should be replaced with actual parameters.
> 
> we don't replace in prepared statements with the actual values`?`

What does this configuration refer to?
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/50609931/b4d50e58-2f9d-4182-becc-26ba85f758cb)

**Comment by laurit** [comment]
@Jamel-jun sorry I don't follow your question.

**Comment by Jamel-jun** [comment]
> @Jamel-jun sorry I don't follow your question.

Sorry, I didn't express myself clearly. What I mean is, what is this configuration used for? I thought it was used to display the actual value.

**Comment by mateuszrzeszutek** [comment]
> What I mean is, what is this configuration used for? I thought it was used to display the actual value.

No, not exactly. The sanitization is enabled by default -- and if you turn it off, we'll just set the statements as they are. If you are using prepared statements, we will not replace the placeholders (`?` or `:1` or `:param`) with the actual values.

**Comment by trask** [comment]
@Jamel-jun is this the feature you're looking for? #7413

**Comment by Jamel-jun** [comment]
> @Jamel-jun is this the feature you're looking for? #7413

Yes. very grateful.

**Comment by Jamel-jun** [comment]
> 
> db.name It should be the actual database name.
> 
In this question, I will sort out a minimal application afterwards
