### ISSUE TITLE
Unresolved reference: getPlatformClassLoader

### ISSUE THREAD

**Issue by mitht** [open-telemetry/opentelemetry-java-instrumentation#9847]
### Describe the bug

$ ./gradlew assemble
Downloading https://services.gradle.org/distributions/gradle-7.3-bin.zip
...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%

Welcome to Gradle 7.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3/release-notes.html

Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

> Task :gradle-plugins:compileKotlin FAILED
e: /Users/rht/source-code/opentelemetry-java-instrumentation/gradle-plugins/src/main/kotlin/io.opentelemetry.instrumentation.muzzle-check.gradle.kts: (130, 72): Unresolved reference: getPlatformClassLoader
e: /Users/rht/source-code/opentelemetry-java-instrumentation/gradle-plugins/src/main/kotlin/io.opentelemetry.instrumentation.muzzle-check.gradle.kts: (241, 81): Unresolved reference: getPlatformClassLoader
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle-plugins:compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 23s
12 actionable tasks: 5 executed, 7 up-to-date

A build scan was not published as you have not authenticated with server 'ge.opentelemetry.io'.

### Steps to reproduce

git clone https://github.com/open-telemetry/opentelemetry-java-instrumentation.git
git checkout v1.9.2
git switch -c v1.9.2
./gradlew assemble

### Expected behavior

Packaged successfully

### Actual behavior

./gradlew assemble Packaging has been unsuccessful

### Javaagent or library instrumentation version

v1.9.2

### Environment

$ gradle -version

------------------------------------------------------------
Gradle 7.6.3
------------------------------------------------------------

Build time:   2023-10-04 15:59:47 UTC
Revision:     1694251d59e0d4752d547e1fd5b5020b798a7e71

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          1.8.0_361 (Oracle Corporation 25.361-b09)
OS:           Mac OS X 13.1 x86_64
--------
$ java -version
java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 1.8.0_361-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.361-b09, mixed mode)

------

**Comment by laurit** [comment]
See https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/v1.9.2/CONTRIBUTING.md Java 11 is required. Note that you are attempting to build an old version, current version requires java 17 to build.
