### ISSUE TITLE
ApplicationDoubleHistogramBuilder bucket boundaries via setExplicitBucketBoundariesAdvice

### ISSUE THREAD

**Issue by nluk** [open-telemetry/opentelemetry-java-instrumentation#9872]
### Describe the bug

Crated by [request](https://github.com/open-telemetry/opentelemetry-java/pull/5897#issuecomment-1799014373).

The histogram builders provided by agent autoinstrumentation do not support setting explicit bucket boundaries. That is [io.opentelemetry.javaagent.instrumentation.opentelemetryapi.v1_10.metrics.ApplicationDoubleHistogramBuilder](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/da024f9462407856de09cd2da2aee96ad49bfcfa/instrumentation/opentelemetry-api/opentelemetry-api-1.10/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/opentelemetryapi/v1_10/metrics/ApplicationDoubleHistogramBuilder.java) does not implement `io.opentelemetry.extension.incubator.metrics.ExtendedDoubleHistogramBuilder` or any similiar interface.

### Steps to reproduce

```java
var builder = GlobalOpenTelemetry.get()
    .getMeter("test_meter")
    .histogramBuilder("test_histogram");
if (builder instanceof io.opentelemetry.extension.incubator.metrics.ExtendedDoubleHistogramBuilder extendedBuilder) {
    extendedBuilder.setExplicitBucketBoundariesAdvice(List.of(1.0, 100.0));
}
```

### Expected behavior

It is possible to set explicit bucket bounderies when running with **only** java agent.

### Actual behavior

When run with `opentelemetry-sdk` or `opentelemetry-sdk-testing` the explicit boundaries are set. With `opentelemetry-javaagent` only [default boundaries](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation) apply.

### Javaagent or library instrumentation version

1.31.0

### Environment

**JDK**: OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
**OS**: Ubuntu 22.04.3 LTS (Jammy Jellyfish)

**Comment by mateuszrzeszutek** [comment]
Hey @nluk ,

Thanks for filing this, this is most definitely a bug.
