### ISSUE TITLE
KTor plugin instrumentation does not include instrumentation library field

### ISSUE THREAD

**Issue by doppleware** [open-telemetry/opentelemetry-java-instrumentation#9912]
### Describe the bug

The OTEL spec includes the [instrumentation library](https://opentelemetry.io/docs/specs/otel/glossary/#instrumentation-library) details. The instrumentation library is the "library that enables OpenTelemetry observability for another library".  This data is missing from the KTOR instrumented traces.

### Steps to reproduce

Enable KTOR plugin, run the code,  examine trace 

For example this is the code I used:

```
    val openTelemetry: OpenTelemetry = GlobalOpenTelemetry.get()

    embeddedServer(Netty, port=8080,host="0.0.0.0") {
        install(KtorServerTracing) {
            setOpenTelemetry(openTelemetry)
        }
        routing {
            get("/") {
                   call.respondText("Hello World!")
            }
        }
    }.start(wait = true)
```

### Expected behavior

Trace should include instrumentation library details. For example, here is a trace with Tomcat auto instrumentation:
<img width="1721" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/93863/6bb61c7c-4b0f-4cfa-852c-4c301bdd9833">

Ii would expect to see an instrumentation library similar to `io.opentelemetry.ktor-2.0`

### Actual behavior

Does not include instrumentation library details:
<img width="1726" alt="image" src="https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/93863/f5bdce6d-1eec-4311-b20e-b32f8324dc82">

### Javaagent or library instrumentation version

1.29.0

### Environment

**JDK**: 17.0.7
**OS**: MacOS

**Comment by laurit** [comment]
Could you provide a minimal sample app that reproduces this issue
