### ISSUE TITLE
Xray propagator not resolved in Spring Boot project

### ISSUE THREAD

**Issue by rBrda** [open-telemetry/opentelemetry-java-instrumentation#9917]
### Describe the bug

Propagator "xray" cannot be resolved since the classpath in the `CompositeTextMapPropagatorFactory` can't be resolved.

The factory imports the Xray propagator as following:
```
import io.opentelemetry.contrib.awsxray.propagator.AwsXrayPropagator;
```

but then tries to check its class path like this:
```
isOnClasspath("io.opentelemetry.contrib.awsxray.AwsXrayPropagator")
```

Spring Boot version: 2.6.6
Otel version: 1.22.0

I also checked newer Otel release versions on Github, they are most probably also affected by the issue.

application.yaml
```
otel:
  exporter:
    otlp:
      metrics:
        enabled: false
  traces:
    exporter: otlp
  propagation:
    enabled: true
    type: xray
```

gradle.build
```
implementation("io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter:1.22.0-alpha")
implementation("io.opentelemetry.contrib:opentelemetry-aws-xray:1.22.0")
implementation("io.opentelemetry.contrib:opentelemetry-aws-xray-propagator:1.22.0-alpha")
implementation("io.micrometer:micrometer-tracing:1.1.6")
runtimeOnly("io.micrometer:micrometer-registry-otlp:1.11.5")
runtimeOnly("io.micrometer:micrometer-tracing-bridge-otel:1.1.6")
```

### Steps to reproduce

Create a sample Spring Boot project using the configuration I provided above, and try to use "xray" as the propagator.

### Expected behavior

Xray propagator is resolved.

### Actual behavior

`CompositeTextMapPropagatorFactory::getCompositeTextMapPropagator()` is not able to resolve the configured propagator.

### Javaagent or library instrumentation version

1.22.0

### Environment

**JDK**:  JDK 11.0.13
**OS**:  MacOS 13.6

**Comment by rBrda** [comment]
Hi @laurit and @trask !

Thank you for your PR!

I'm not sure if any of you can answer my question, but I ask anyway.

Will this fix also be published as a patch for 1.22.0 (and other versions)?

The Spring Boot project I work can only use 1.22.0 of Opentelemetry (higher doesn't work, we get errors because of our JDK version), and I'm not allowed to upgrade neither the Spring Boot version nor the JDK version. We're blocked because of this bug, and it would be great if the version we use (1.22.0) would receive this change as a patch/hotfix.

**Comment by laurit** [comment]
@rBrda 
> Will this fix - if approved - also be published as a patch for 1.22.0 (and other versions)?

no, we don't do patch releases for old versions

> The Spring Boot project I work can only use 1.22.0 of Opentelemetry (higher doesn't work, we get errors because of our JDK version), and I'm not allowed to upgrade either the Spring Boot version or the JDK version. 

please elaborate, perhaps we can fix whatever it is

You can probably work around this bug by disabling https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/b23926fb1dab7a500ff44f3ff4ae10df05459eed/instrumentation/spring/spring-boot-autoconfigure/src/main/java/io/opentelemetry/instrumentation/spring/autoconfigure/propagators/PropagationAutoConfiguration.java#L26 and creating these beans yourself.

**Comment by rBrda** [comment]
@laurit 

Ok, thank you, we'll then disable `PropagationAutoConfiguration` and create our custom config class with the beans.

Yes, I can elaborate.

We get the following error message when we try to build our project:
```
Execution failed for task ':bootJarMainClassName'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not resolve io.opentelemetry.instrumentation:opentelemetry-spring-webmvc-6.0:1.23.0-alpha.
     Required by:
         project :
         project : > io.opentelemetry.instrumentation:opentelemetry-spring-boot-starter:1.23.0-alpha > io.opentelemetry.instrumentation:opentelemetry-spring-boot:1.23.0-alpha
      > No matching variant of io.opentelemetry.instrumentation:opentelemetry-spring-webmvc-6.0:1.23.0-alpha was found. The consumer was configured to find a runtime of a library compatible with Java 11, packaged as a jar, and its dependencies declared externally but:
          - Variant 'apiElements' capability io.opentelemetry.instrumentation:opentelemetry-spring-webmvc-6.0:1.23.0-alpha declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 17 and the consumer needed a runtime of a component compatible with Java 11
          - Variant 'javadocElements' capability io.opentelemetry.instrumentation:opentelemetry-spring-webmvc-6.0:1.23.0-alpha declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
          - Variant 'runtimeElements' capability io.opentelemetry.instrumentation:opentelemetry-spring-webmvc-6.0:1.23.0-alpha declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 17 and the consumer needed a component compatible with Java 11
          - Variant 'sourcesElements' capability io.opentelemetry.instrumentation:opentelemetry-spring-webmvc-6.0:1.23.0-alpha declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
```

**Comment by laurit** [comment]
@rBrda could you create a new issue for that so we could fix it

**Comment by rBrda** [comment]
@laurit yes, sure. I'm going to create a new issue for it. Thank you!

**Comment by rBrda** [comment]
@laurit I've created a new issue for the problem: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/9949
