### ISSUE TITLE
Span reported to wrong parent trace span when sharing a CompletableFuture

### ISSUE THREAD

**Issue by nluk** [open-telemetry/opentelemetry-java-instrumentation#9934]
### Describe the bug

We've got a small sorts-of rate limiting solution built for reducing traffic in auth token issuance. The idea is that when a common token needs to be issued, the first thread **T1** that gets to that stage stores a `CompletableFuture<String>` in a `ConcurrentHashMap`. The source of the future is `java.net.http.HttpClient::sendAsync`. The other thread **T2** encounters the future in the map and calls its respective `thenApply` operations. When the future is completed it is removed from the map. This way we get the same auth token issued for both threads with just a single http call, and without explicit blocking via `Lock` / `synchronised`, as the future is just NIO.

The problem is that spans reported in the **T2** after receiving the token are attributed to the parent trace initiated in the **T1**. This is probably because of the `Future` / `Runnable` / `Callable` / `Executor` instrumentation and `PropagatedContext` stored as a `VirtualField`.

### Steps to reproduce

I've created a new unit test in [a fork](https://github.com/nluk/opentelemetry-java-instrumentation/blob/57ca5bd787ddfff5a18f0cb123829668bdc1341b/instrumentation/executors/javaagent/src/test/java/io/opentelemetry/javaagent/instrumentation/executors/CompletableFutureTest.java#L207), in the executor instrumentation module.

### Expected behavior

For the test provided either:

```
Span[controller1-start, fetchToken, controller1-end] +
Span[controller2-start, controller2-end]
```

or:

```
Span[controller1-start, controller1-end] +
Span[controller2-start, fetchToken, controller2-end]
```

depending on the order of execution.

It's hard to say what the fix for this should be. I've considered two workarounds:
1. Explicit blocking or synchronisation of the `fetchToken` call instead of relying on CompletableFuture
2. `var originalContext = Context.current()` prior to token fetch + `originalContext.makeCurrent()` **without** try-with resources after the fetch is completed. This means that the resulting scope will not be closed, and the original context will overwrite threadlocal context copied from the virtual field. This in fact works, but also seems to be an extremely bad solution, as the overwritten threadlocal will not be restored later. Also the `@MustBeClosed` annotation is kinda scary.

### Actual behavior

For the test provided either:

```
Span[controller1-start, fetchToken, controller1-end, controller2-end] +
Span[controller2-start] 
```

or:

```
Span[controller1-start] +
Span[controller2-start, fetchToken, controller2-end, controller1-end]
```

### Javaagent or library instrumentation version

1.31.0 Agent AWS flavour (software.amazon.opentelemetry:aws-opentelemetry-agent:1.31.0)

### Environment

**JDK**: Temurin-17.0.5+8
**OS**: Ubuntu 22.04.3 LTS

**Comment by nluk** [comment]
UP - OpenTelemetry 1.32.0 - still the same issue.

**Comment by breedx-splk** [comment]
I was able to modify the test somewhat to eliminate the amount of async future work. The controllers are still executed concurrently in their own threads, but without using `CompletableFuture`, and internally they are synchronous. The token fetch is still async, but joined immediately so effectively sync.

https://gist.github.com/breedx-splk/2dea7731632b3a7f4335bfb1af6cd8ab

The test passes. This doesn't fix the issue and I'm NOT suggesting this as a real workaround, I'm just offering it as a datapoint to future troubleshooters who may benefit from this.  Still not sure what the fix ought to be.

**Comment by laurit** [comment]
Callbacks are run in the context where `CompletableFuture` is completed or in the current context if the said future is already completed. In your case both of the end branches are driven by the same uncompleted future so they will both run in the same context once the future completes. Completion of that future is triggered by the `singleTokenFetch.get()` call which happens in one of the start branches, that start branch will be parent of the rest of the spans.
If you want to run your actions in a specific context then you could try wrapping the callback in `try (Scope ignored = context.makeCurrent()) {...}` or wrapping the future.

**Comment by nluk** [comment]
> Callbacks are run in the context where CompletableFuture is completed or in the current context if the said future is already completed.

You mean callbacks as in the body of `thenApplyAsync` lambda, or just the submission of the lambda to the executor? I agree the callback is submitted  by the thread that has the `tokenFetch` context (the one that completes the future), but the callback payload runs on the executor provided as the second `thenApplyAsync` arg. I kinda understand how this happens, but the result is less than satisfying. I get traces that seem broken - 'start' without 'end', and a single trace that has a bunch of 'end's seemingly unrelated to whatever started it.
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38426907/3174bf38-56d1-425d-bcab-d7d8c6755f37)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38426907/688d9401-8c90-4095-9228-d858a12e4295)
![image](https://github.com/open-telemetry/opentelemetry-java-instrumentation/assets/38426907/b0c8c5a1-1309-406d-85d0-f151559e07a8)

The point is that technically this could be correct. There's no bug in how the context is propagated to the `tokenFetch` and further from there. But my `POST /trace/start` does return a result from the call to `POST /trace/middle` + `POST /trace/end`. But that's not reflected in the tracing. The tracing reflects how the context is moved, not the chain of requests and responses. I don't ask for a rewrite of `CompletableFuture` instrumentation, just for some tips on how I could manually setup context/scope to produce more reasonable tracing.

> If you want to run your actions in a specific context then you could try wrapping the callback in try (Scope ignored = context.makeCurrent()) {...} or wrapping the future.

What instance of the context are you referring to here? And again, which callback?

**Comment by laurit** [comment]
> You mean callbacks as in the body of thenApplyAsync lambda

yes

> but the callback payload runs on the executor provided as the second thenApplyAsync arg

it doesn't really matter which executor runs it

> What instance of the context are you referring to here? And again, which callback?

By context I mean [opentelemetry context](https://opentelemetry.io/docs/specs/otel/context/). Opentelemetry context contains the active span that is by default used as the parent of the new spans. You can capture this context with `io.opentelemetry.context.Context.current()` and activate it at a later point to have new spans appear under whatever is the current span in that context.
By callback I mean the piece of code you attached to the `CompletableFuture` with `thenApply`, `whenComplete` etc. that is run when the `CompletableFuture` completes.
For example see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/338b03efb15d88378c9f0b388315bc7cd9ec5aae/instrumentation/java-http-client/library/src/main/java/io/opentelemetry/instrumentation/httpclient/internal/OpenTelemetryHttpClient.java#L145 In java 11 http client instrumentation when user calls `sendAsync` we return a `CompletableFuture` that is completed in the context that was active when `sendAsync` was called to ensure that the spans from "callbacks" appear in the same trace.

**Comment by nluk** [comment]
> In java 11 http client instrumentation when user calls sendAsync we return a CompletableFuture that is completed in the context that was active when sendAsync was called to ensure that the spans from "callbacks" appear in the same trace.

Makes sense if you want to fan out with a sendAsync call, and maintain the context from parent thread. But in my case, where I use just reuse the future - I already have a new context from a separate request, and it's disregarded in favour of _the context that was active when sendAsync was called_. 

I see no point in further dwelling on it, it works as intended.
