### ISSUE TITLE
How can I connect the trace data under multi-threading without modifying the original project code?

### ISSUE THREAD

**Issue by detongz** [open-telemetry/opentelemetry-java-instrumentation#9962]
### Describe the bug

for example, I have both java springboot project demoA,demoB

in demoA, I have

@RequestMapping("/testA")
public String callback(HttpServletRequest request) {
    new Thread(() -> {
        dopost("url of demoB/testB");
    }).start();
    return "ok";
}

my opentelemetry agent param is:
-Dotel.traces.exporter=jaeger
-Dotel.traces.jaeger.endpoint=xxx

When I view the trace data of demoA on jaeger，I got two trace data
1. demoA/testA
2. demoA --> demoB/testB，this trace not include requestMapping testA，and traceId and span data cannot be related to testA.

I wish to get only one trace data of demoA  demoA/testA --> demoB/testB

### Steps to reproduce

two springboot project
create a new thread in project A to call project B

### Expected behavior

wish to get only one trace data of demoA  demoA/testA --> demoB/testB

### Actual behavior

got two trace data and can not be related

### Javaagent or library instrumentation version

1.27.0

### Environment

**JDK**:
**OS**:

**Comment by laurit** [comment]
We don't propagate context to new threads. Context is propagated automatically with some `ExecutorService` implementations like `ThreadPoolExecutor`.
