### ISSUE TITLE
Disable all the Spring configurations with otel.sdk.disabled

### ISSUE THREAD

**Issue by jeanbisutti** [open-telemetry/opentelemetry-java-instrumentation#9980]
### Is your feature request related to a problem? Please describe.

Today, only the `OpenTelemetrySdkConfig` Spring configuration is disabled if the `otel.sdk.disabled` property is equal to `true`.

Other Spring configurations should also be disabled (annotation, jdbc, kafka, logging, micrometer, web, webflux, webmvc).

### Describe the solution you'd like

Two possibilities: disable configurations based on the `otel.sdk.disabled` property or disable the configurations if `OpenTelemetrySdkConfig`  is disabled (absent).

**Comment by jeanbisutti** [comment]
@open-telemetry/java-instrumentation-approvers Could you please add the `spring boot starter` label?

**Comment by zeitlinger** [comment]
This is not a bug
