### ISSUE TITLE
Auto instrumentation of RestTemplate/RestClient/WebClient does not work with Spring Boot 3.2.0

### ISSUE THREAD

**Issue by nilsga** [open-telemetry/opentelemetry-java-instrumentation#9987]
### Describe the bug

When upgrading our applications to Spring Boot 3.2.0, we noticed that we stopped getting spans from http client invocations. After some digging, we think the reason is that the http request factory has changed: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#resttemplate-http-clients

If we opt in to `JdkClientHttpRequestFactory`, as described, tracing works. However, Apache HttpClient 5 request factory, or the jetty 12 client factory, does not seem to work. For Apache Http Client 5, the problem seem to be that Spring send `null` as `HttpHost` here: https://github.com/spring-projects/spring-framework/blob/main/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequest.java#L95

which results in a `NullPointerException` in `RequestWithHost`:

```java
public RequestWithHost(HttpHost httpHost, ClassicHttpRequest httpRequest) {
    super(httpRequest);
    this.scheme = httpHost.getSchemeName();
    this.authority = new URIAuthority(httpHost.getHostName(), httpHost.getPort());
  }
```

Intuitive fix is to fetch `URIAuthority` and `scheme` from `httpRequest`:

```java
this.scheme = httpRequest.getScheme();
this.authority = httpRequest.getAuthority();
```

but perhaps there is a reason this is not done in the first place.

For Jetty 12 http client, it seems that support just does not exist.

### Steps to reproduce

* Create a new Spring Boot 3.2.0 application
* Add Apache HttpClient 5 or Jetty 12 Http Client to classpath.
* Create endpoint using RestClient to invoke a http service

### Expected behavior

Span is created for the RestClient call

### Actual behavior

No span is created

### Javaagent or library instrumentation version

1.32.0

### Environment

**JDK**: Azul 17
**OS**: MacOS

**Comment by trask** [comment]
hi @nilsga! if you'd like to send a PR to fix that would be great

cc @jeanbisutti

**Comment by luolong** [comment]
It seems Jetty support is still not available. 
should this issue be re-opened or should there be another issue for adding jetty support as well.

**Comment by laurit** [comment]
> It seems Jetty support is still not available. should this issue be re-opened or should there be another issue for adding jetty support as well.

please create a new issue, include a minimal sample application that illustrates the problem
